### ISSUE TITLE
ptxprint.exe not responding when selecting a project from the Paratext Project menu

### ISSUE THREAD

**Issue by klassenjm** [sillsdev/ptx2pdf#1]
First of all -- _congratulations_ on the effort and perseverance to produce ptxprint and for making an early version available for testing.

I have downloaded the Windows .exe. I have accepted the Windows security warning and run it (including as Administrator). I seem to be able to navigate the UI in general. I have successfully created a PDF for a project.

On my first attempt using the app, I selected a project from the Paratext Project menu, and the app appeared to freeze (Windows "Not Responding") for a fairly long time. I eventually forced a quit. I tried the same project again, waited again, and the app did eventually return control to me (after a pause -- perhaps 8-10 seconds?). After this I created a PDF for this project, and from this point it can be selected and the app responds quickly now for this project. The same slowness (apparent freeze) happens when I select another new project.

**Comment by mhosken** [comment]
Dear Jeff,

My assumption is that you have a lot of fonts installed on your machine.
Ptxprint and xetex both scan the complete list to map from font name to
font file and they do it a total of 8 times. We should probably think how
to reduce that. But for now either uninstall lots of fonts or be patient.
Not fun, I realise. Sorry about that. My assumption is that paratext print
draft would also be painfully slow.

GB,
Martin

**Comment by mhosken** [comment]
I have done some work to speed up fonts, but I don't think that's what you were seeing. It seems that clearing the book list when you change project takes a looong time. I've made a change to only do that if you really do switch project. So when you select your first project, either from the gui or via the command line, it should not 'hang'.

**Comment by markpenny** [comment]
Jeff, could you try the latest version v0.2.1 to see if this is behaving better now? [tiny.cc/ptxprint](http://tiny.cc/ptxprint)

**Comment by klassenjm** [comment]
I have 0.2 and it is performing much better. Selecting a project or switching between projects has an immediate response (no hanging). Thank you.

**Comment by mhosken** [comment]
Fixed
