### ISSUE TITLE
Variable Line Spacing trial

### ISSUE THREAD

**Issue by jangossner** [sillsdev/ptx2pdf#1001]
I watched the video the other day about Variable Line Spacing, etc., and I tried turning on Variable Line Spacing. The output I got has at the beginning and end what looks like a list of adjustments it made:
<plus 2.0pt* 1plus 2.0pt* 1+ 3.0 ptplus
2.0pt
plus 2.0pt* 1plus 2.0pt* 1+ 3.0 ptplus 2.0pt
plus 2.0pt* 1plus 2.0pt* 1+ 3.0 ptplus 2.0pt
plus 2.0pt* 1plus 2.0pt* 1+ 3.0 ptplus 2.0pt
plus 2.0pt* 1plus 2.0pt* 1+ 3.0 ptplus 2.0pt
plus 2.0pt* 1plus 2.0pt* 1+ 3.0 ptplus 2.0pt
plus 2.0pt* 1plus 2.0pt* 1+ 3.0 ptplus 2.0pt
plus 2.0pt* 1plus 2.0pt* 1+ 3.0 ptplus 2.0pt
plus 2.0pt* 1plus 2.0pt* 1+ 3.0 ptplus 2.0pt
plus 2.0pt* 1plus 2.0pt* 1+ 3.0 ptplus 2.0pt>

File attached.

Thanks,
Jan Gossner
jan_gossner@sil.org

[ETRBible_TeamReadthrough-sglspaced2col-heavierfont_HEB_ptxp.pdf](https://github.com/user-attachments/files/17730068/ETRBible_TeamReadthrough-sglspaced2col-heavierfont_HEB_ptxp.pdf)

**Comment by markpenny** [comment]
Ugh! That's not very pretty is it! Are you able to create an archive using the button on the Help tab? If so, please drop the .zip file into [this Google folder](https://drive.google.com/drive/folders/1S63WeFUg96ZdlA5IdS4E3AI7kC3HaxUo?usp=drive_link).

**Comment by markpenny** [comment]
Fixed for 2.6.12
https://github.com/sillsdev/ptx2pdf/issues/1000#issuecomment-2484090391
