### ISSUE TITLE
\s fails in XXB

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#101]
I don't know exactly what is happening, but marker \s (or \s1) causes an error in book XXB which is a multi-chapter "Read through the Bible" type of supplemental material. (Worked fine in v0.7.0)

No idea what is going on yet. To test other stuff I've just excluded this book from the Output for now.

**Comment by davidc86** [comment]
The problem is NOT with the \s field (the error reported the wrong issue). But the error occurs because I am trying to get the table header to use the centered table header field marker (\thc1, etc., which is supported in the Paratext editor). But it certainly crashes the PTXprint ouptut. So I guess I'll just have to revert my changes back to \th1, \th2, etc.!

**Comment by mhosken** [comment]
Continue discussion in #85
