### ISSUE TITLE
Footnote text seems rather spacious now

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#1013]
I'm not sure what might have changed in the ensuing versions, but I'm noticing again that the footnote text is stretching out again, rather excessively it seems to me: 

![Image](https://github.com/user-attachments/assets/a63c8a99-20e3-473d-9391-9e501cf37d3f)

I count room for at least 11 extra characters on the first line of the footnote, plenty of space for "**kbuanke**" and maybe even "**kbuanke o**" to come up to the previous line. 

This was an issue that was fixed quite a while ago. Is it possible some default setting was changed during a version update, and I just didn't notice until now?  Or is it due to USFM character style markers in the footnote which disappear but leave behind their spacing?

**Comment by markpenny** [comment]
There's nothing that we are aware of that we changed in this area recently. And we continue to run tests from one release to the next to make sure that things do move unexpectedly. I'm wondering whether (in this case) that word _kbuanke_ is too long to fit without excessive squeezing (which would invoke a higher penalty than just breaking the line). Let us know if you come up with any other evidence to prove me wrong, but for now, I'm just tagging this as 'No action'.

**Comment by davidc86** [comment]
But look at all that space between words in the first line of the footnote. It clearly has like 2 spaces between each word. (Or that's what my eyeballs say.) Count them up and there are 11 extra spaces, whereas "kbuanke" is like maybe 7 spaces. (Yeah, I know this is not a very accurate calculation.)

I suppose I could just turn off justification on footnotes and see if it closes up those words on the first line more.

But as it is, it looks kind of like PTXprint is using word-spacing suitable for main scripture text sizes for the word-spacing it is using in footnote paragraphs with a much smaller font size. (I suspect this is not so, but it sure looks like it is doing this.)

________________________________

**Comment by mhosken** [comment]
Allow your word spacing to shrink and it'll probably squeeze in.

GB,
Martin

**Comment by davidc86** [comment]
Thanks Martin!
For some reason my Space Adjustments settings had been turned off.
So I turned them on and adjusted them to look like the training video from Mark: 

![Image](https://github.com/user-attachments/assets/4ff74bc8-1852-4400-be15-234919463c19)

And then reran the Make PDF to get this: 

![Image](https://github.com/user-attachments/assets/dba21e64-ca61-48d7-bf0b-f9bb158973a9)
