### ISSUE TITLE
App gets confused as to which PicList to use

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#102]
I opened the app and generated PicLists. 
These are saved in the **C:\My Paratext 9 Projects\SLU\shared\ptxprint\PicLists** folder.
I then created a new Saved Configuration (e.g. **AlkitabSelaru-2020-06a**).
The app saves a copy of these PicList files in the folder:
**C:\My Paratext 9 Projects\SLU\shared\ptxprint\AlkitabSelaru-2020-06a\PicLists**

THIS IS GOOD!

BUT if I then need to tweak a PicList file, and EDIT it (either in PTXprint's Viewer tab or by launching a View/Edit app), PTXprint shows and edits the PicList file --but pulls it from the  **...\shared\ptxprint\PicLists** folder NOT the Configuration's PicList folder. 

BUT when it builds the PDF file, it READS the PicLists from the Configuration's PicList folder. (So no edits get reflected in the output.) 

This was a bit of a head-scratcher. So now I use a Folder Compare program to update my edits to the Configuration folder and then run the output, and it works.

PTXprint needs to keep track of which set of PicList files it is paying attention to. 

I think: 
* If a configuration is listed in the Basic tab, that should be the *only* place PTXprint looks.
* If no configuration is active on the Basic tab, only then should PTXprint look in the "root" folder.

**Comment by markpenny** [comment]
This should now be fixed in 0.7.2 - please check and re-open if you find otherwise.
