### ISSUE TITLE
Version 2.7.8 is non-functional

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#1021]
I just installed v2.7.8 and almost everything is grayed out.

![Image](https://github.com/user-attachments/assets/a074d0a9-2ee5-44c3-91f7-f68ca0241531)

Picture tab even worse:

![Image](https://github.com/user-attachments/assets/335349e7-13d0-4295-a2e9-76a1ebc371c7)

We'll need to use 2.7.7 until 2.7.9 fixes the glitch.

**Comment by markpenny** [comment]
Thanks for the heads-up, David. I've pulled 2.7.8 down off the site.
