### ISSUE TITLE
diglot gets things wrong when different baselineskips are in force

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#105]
Here, it seems like the RHS baseline has been used to join the 2 sections:

![image](https://user-images.githubusercontent.com/58848232/84505535-8b5f4480-acc6-11ea-981d-9265425a6b87.png)
Logic to fix this will need to take into account which side was full, and the appropriate spacing.

**Comment by JDNystrom** [comment]
Could this be the same problem that causes our diglots to have misaligned titles? 

![image](https://user-images.githubusercontent.com/67346393/85623459-10831b80-b62e-11ea-8353-9f2efbbad7a4.png)

**Comment by davidg-sil** [comment]
Hmm. That looks more like a different issue, sorry. Can you look at the
merged sfm and check it is actually merging properly? That snippet looked
like some lefttext...righttext grouping got missed, somehow.

**Comment by davidg-sil** [comment]
Fix to my initial issue now committed to git. Expect it in future release. Therefore, I'm calling this closed
