### ISSUE TITLE
\Bold and \Italic flags don't work unless we select Fake Fonts on Layout page

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#106]
Apparently the PrintDraft-mods.sty is being ignored. Or the changes I make are being saved into a place the program is not looking at. 

Or maybe it is just ignoring certain character style settings I've put into the PrintDraft-mods.sty file. This includes bolding for section headings, italic on picture captions, bolding for footnote and cross-reference chapter:verse references, certain colors show as gray, but some colors are correct, like words of Jesus, or chapter numbers, and certain font size specifications are recognized.

Anybody else noticing this? (v0.8.1)

**Comment by mhosken** [comment]
It may well mean that you have an error earlier in the chain of .sty files. If a .sty file is faulty, the macros will ignore the rest of the file (I'm not sure if it ignores files after it as well). I would love us to be able to flag that, but, from within TeX we can't. So check your .sty files for casing issues (field markers must be of the correct case), comments in the wrong place, etc.

We've done a lot to improved things in this area, but we are far from perfect.

**Comment by davidc86** [comment]
Odd. I haven't changed anything on my end. So some change made between 0.7.1 to 0.8.1 caused this to fail.

**Comment by davidc86** [comment]
Okay, so I've check several things, and the ONLY setting that don't seem to work are \Bold and \Italic all the rest "seem" to work (I haven't checked everything). I'm using the Charis SIL fonts (regular, bold,  italic, and bold/italic). Even color setting further down in the PrintDraft-mods.sty file WORK. So I know PTXprint is reading the PrintDraft-mods.sty file successfully, and it is parsing it successfully, but for some reason the **Bold** and *Italic* flags are no longer reflected in the text ANYWHERE. (I am *not* using the "Fake" bold/italic settings.

**Comment by davidc86** [comment]
Further testing: If I check the boxes for "FAKE" Bold, Italic, etc. then the style comes through!
But if I use the UNchecked versions (yeah, the actual Bold Font and Italic Font options) then it fails. So the problem is NOT in PrintDraft-mods.sty like I thought but rather something is broken on the Layout page, where PTXprint is not using the selected fonts when it should.

**Comment by mhosken** [comment]
Bug found and fixed. Check in 0.8.2

**Comment by davidc86** [comment]
FIXED! Thanks.
