### ISSUE TITLE
Clicking "Download current version" freezes program

### ISSUE THREAD

**Issue by sewhite** [sillsdev/ptx2pdf#107]
If I go to the About page, and click "Download current version", the program seems to get into a loop. It doesn't detect that I have the current version, or make the browser download anything, but sits there not responding to input. I cannot close the "About" dialog or the main program except with Task Manager.

Version 0.81.

**Comment by mhosken** [comment]
Good to know. Best to download from outside the program or once it has downloaded. restart the program. We should probably force that to happen.

**Comment by markpenny** [comment]
Thanks for finding this bug @sewhite . Yes, I can confirm the behaviour that you describe. In fact, what is happening is that it is bringing up an error BEHIND the About box which can't be seen until the About box has been moved. Obviously a regression, and hopefully easy to fix.
![image](https://user-images.githubusercontent.com/12962708/85096518-1a61e480-b212-11ea-9c67-6a4f70be9f11.png)

**Comment by markpenny** [comment]
Fixed in 0.8.3
