### ISSUE TITLE
Character styles wj and +wj are acting this same

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#108]
I don't know for sure if the regular character styles and the + character styles are supposed to act the same, but I was under the impression they were used in different situations. I assumed the + markers could be used in Footnotes, and treated differently than main text character styles. For example \wj ...\wj* might add RED and no specified \FontSize -- this works fine for main text, but if Words of Jesus need to be quoted in a footnote, (which is \FontSize 9), I thought using +wj...+wj* would mark it uniquely. But when I specify +wj...+jw* in the PrintDraft-mods.sty file, with \FontSize 9 and a different color (just to check), PTXprint ignores these settings and treats it the same as \wj ...\wj* (RED and Large text).  

Anybody know if these are supposed to be treated the same or different (especially when specified differently in the STY file? 
Anybody know how to get the text marked with character styles in footnotes to ONLY add specified attributes. (Like for example, \wj...\wj* should ONLY ADD RED -- NOTHING ELSE. And so if this marker occurs in the main text it uses the FONT, FONTSIZE, etc. of the underlying text, and it just adds RED for the bits it marks. IF it acted this way, then we could easily mark \wj in footnotes without any problems, because that text would inherit the underlying text style (FontSize 9, etc.) and only add RED to that. 

What am I missing here? 
Thanks

**Comment by mhosken** [comment]
We have gone the route of treating \wj and \+wj identically. We have also done a lot of work in the area of chained styles such that I would hope that you can simply define:
```
\Marker wj
\Color 128
```
Unfortunately usfm.sty declares a \FontSize for this marker. How do we undo that? FontScale takes precedence over FontSize so:
```
\Marker wj
\FontScale 1
\Color 128
```

**Comment by mhosken** [comment]
See issue #96 and continue discussion there.
