### ISSUE TITLE
Footnotes don't use the supplied caller mark

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#109]
In v0.8.2 it looks like the footnote callers are not reflecting what I've specified in the Head+Foot tab in PTXprint. Here is a shot of the current PDF output:

![image](https://user-images.githubusercontent.com/65363206/84775111-c86c5500-afac-11ea-85cc-43ce045ee776.png)

And here is what I've specified in PTXprint:

![image](https://user-images.githubusercontent.com/65363206/84775168-d7eb9e00-afac-11ea-8b29-8a9b85fce23d.png)

See where I have requested footnotes to use a * and cross-references to use nothing. But in the PDF the footnotes are using a + sign. (It doesn't look bad, but it isn't what I asked for.)

**Comment by markpenny** [comment]
Fixed in 0.8.3
