### ISSUE TITLE
0.2.2 List of projects puts upper case first and lower case last

### ISSUE THREAD

**Issue by philleckrone** [sillsdev/ptx2pdf#11]
This confused me when I couldn't immediately find the project I was looking for - eventually I realized that the lower case titles were at the bottom of the list.

**Comment by markpenny** [comment]
Thanks for pointing that out. It is fixed now, and will be in the latest .exe (v0.2.3) in a few hours time.
![image](https://user-images.githubusercontent.com/12962708/69400049-6dc09280-0d16-11ea-9807-9d8ec0a25da1.png)
