### ISSUE TITLE
Cross-references do not reflect the specified FontSize

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#110]
Maybe I just noticed this, but it looks like in v0.8.2 the cross-references DON'T pay attention to the specified font size in the PrintDraft-mods.sty file. Here is what I'm seeing in the PDF output:

![image](https://user-images.githubusercontent.com/65363206/84776354-336a5b80-afae-11ea-9ef0-2e913c3f264f.png)

Here is how it is defined in the stylesheet: 

![image](https://user-images.githubusercontent.com/65363206/84776466-5563de00-afae-11ea-9faf-e2183da15e03.png)

I have all footnote and cross-reference markers set to FontSize 9, but if you look carefully at the PDF screenshot, you can see that the References in the \xt field are larger than the text in the footnote right above it.

Also note that the actual calling verse ref is correct (9pt) but the contents of the xref field are larger, like 10pt or so. Is there another "marker" I need to add to the PrintDraft-mods.sty file to control this, or is this a bug? Thanks.

**Comment by markpenny** [comment]
@davidc86 Could you clarify whether you are looking at NestedStyles.sty* in the stylesheet above, or a different stylesheet? From what I understand, the easiest way to control the size and line-spacing of the footnotes and xrefs is by adjusting them on the Head+Foot tab:
![image](https://user-images.githubusercontent.com/12962708/85096156-1f726400-b211-11ea-8576-0b7ea149d7d8.png)
But if your PrintDraft-mods.sty stylesheet has other settings, then these settings (through the UI) should be overridden. If you are seeing some other behaviour, then we may need to fix it.
*NestedStyles.sty is generated by PTXprint when the job is run and should be found (as a temporary file) in the output/PrintDraft folder.

**Comment by davidc86** [comment]
That section is taken from my "PrintDraft-mods.sty" file. I don't know anything about a NestedStyles.sty file. Also the Font Size in my Head+Foot tab was set to "10" so apparently I had enough attributes specified in the PrintDraft-mods.sty file to get the footnote to look like "9pt" but the 10 in the TAB controlled the Xrefs. Changing that to "9" solved the differences. Thanks.
