### ISSUE TITLE
"Include Pictures" prevents anything from happening

### ISSUE THREAD

**Issue by viverechristus** [sillsdev/ptx2pdf#111]
(Using 0.8.2, had the same issue in 0.8.1)

If I select "Include Pictures" in the Pictures tab, then press Print, nothing happens - the blue progress bar doesn't start doing anything, and it continues not doing anything indefinitely. However, if I subsequently deselect "Include Pictures" and press Print again, it immediately starts working.

This apparent bug prevents output even if I'm outputting a chapter with no images in it.

**Comment by davidc86** [comment]
I don't have that issue. I always "Include Pictures" and PTXprint generates the PDF just fine (mine is a multi-book output as a single PDF including back matter, so rather complex). I'm wondering if the set of PicList files need to be generated first in order to get this working for you. But I'm just a tester, so my comment is probably not helpful, and just an FYI that it does works okay on my configuration.

**Comment by viverechristus** [comment]
Thanks, David. I tried going to the Viewer tab and generating a PicList (that worked). Then I went back to the Pictures tab and selected first "Use a PicList..." (Print doesn't work) then "Use Pictures marked..." (Print doesn't work). I've tried turning on and off various other settings and simply can't get it to output a PDF (or even pretend to try to!) when "Include Pictures" is selected. 

I'm happy to test any other ideas, or provide any diagnostic data needed.

**Comment by mhosken** [comment]
We are just fixing up an issue that arises if a picture filename starts with a digit. This may be what you are seeing. Anyway, we are onto that one at least.

**Comment by viverechristus** [comment]
That doesn't seem to be the issue here. Here's my PicList:

![image](https://user-images.githubusercontent.com/915182/85369239-ef033080-b556-11ea-9803-763f5842e3e0.png)

**Comment by mhosken** [comment]
Wait for the next release. We've been working hard in this area today.

**Comment by markpenny** [comment]
@viverechristus - Okay... 0.8.4 is now available - let me know if we've managed to fix all the illustration-related issues. Note that I haven't yet attempted to fix the .tiff and .jpeg problem. Perhaps later this week, or early next week I'll get to that one.

**Comment by viverechristus** [comment]
Alas, it's still not working. It seems unrelated to actually having images! If I select just the book of Philemon in our project -- which has not a single image! -- and then click Print, nothing happens if "Include Pictures" is selected (with either Use a Pic List, or Use Pictures Marked). However, if I deselect "Include Pictures", the output goes without a hitch.

**Comment by markpenny** [comment]
Sorry to hear this. Very strange. Could you please share the project and the font (either a zipped backup of the project files), or by Send/Recv. (If by s/r, my ptxt name is "Mark Penny"). I'll delete the project after we've done some troubleshooting....

**Comment by viverechristus** [comment]
You're now an observer on the project. Is that sufficient?

**Comment by markpenny** [comment]
Great - got it, and have been able to replicate the problem. Working on a fix now. Thanks for your help.

**Comment by markpenny** [comment]
Right - please give 0.8.5 a go now and let me know if this has finally solved this issue. Thanks for finding and reporting this bug, It must have been affecting a number of users, but only a couple of people reported it. Once you've confirmed that it is fixed, I'll remove the shared project from my machine.

**Comment by viverechristus** [comment]
Resolved! Thanks so much.
