### ISSUE TITLE
UI Enhancement: display non-Roman characters

### ISSUE THREAD

**Issue by viverechristus** [sillsdev/ptx2pdf#112]
It would be super if the UI displayed non-Roman (specifically for us, Khmer) characters!

![image](https://user-images.githubusercontent.com/915182/85247244-55188680-b477-11ea-9c20-72550a11f0bc.png)

**Comment by markpenny** [comment]
Thinking about this request as it may cause other issues for many other teams:
![image](https://user-images.githubusercontent.com/12962708/85360620-34176a80-b537-11ea-804a-5c2bfa396636.png)
Here is the footer box in the font for the language (as requested), BUT that font (which happens to be the ONLY font for that script) doesn't contain any latin/english characters... so now they can't even see what is says "Reference, Page Number, etc."

For now, just pray for a good solution to be found!. Perhaps a "fallback font" which could get applied...

**Comment by viverechristus** [comment]
Wow, that's too bad. Better to have Roman, since we need that more often than Khmer in those boxes. Thanks for trying.

**Comment by markpenny** [comment]
Hold on... @mhosken found a way to specify the fallback font! So, yes! - it will be fixed in the next version that is released (hopefully 0.9.0 RC later today).

**Comment by viverechristus** [comment]
Cool, thanks!

**Comment by viverechristus** [comment]
Beautiful! Thanks!

![image](https://user-images.githubusercontent.com/915182/85404879-c9dbe580-b589-11ea-8eb9-73a0f2e409dd.png)
