### ISSUE TITLE
How do we make the header bold?

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#113]
We normally make the Book name and chapter number bold in the running hear.  (The page number doesn't need to  be.) I don't see how to do this. I guess I'd like a cheat sheet of these resultant fields that are built by PTXprint and then go out the door, but we users never see it, so we don't know the "marker" to use to specify "\Bold" even if we wanted to.

**Comment by mhosken** [comment]
I had just written an FAQ on this. The font used in the head line is defined by the specification for the `\h` marker.

**Comment by markpenny** [comment]
https://github.com/sillsdev/ptx2pdf/blob/master/docs/documentation/ptx2pdf-faq.md#how-can-i-format-the-page-number

One day we might make this user-configurable through a stylesheet editor, but for now the FAQ should allow you to do what you need. Note that you can type whatever you want to in the Header/Footer fields (and aren't restricted to the drop-down choices).
