### ISSUE TITLE
Pic List ignores .tiff files (but .tif are fine)

### ISSUE THREAD

**Issue by viverechristus** [sillsdev/ptx2pdf#114]
(0.8.2) -- I noticed that an image wasn't showing up in the Pic List. However, if I changed the filename extension from .tiff to .tif, it shows up in the Pic List when I regenerate the list. 

(Unfortunately, this doesn't seem related to my bigger problem -- my inability to create any output if Include Pictures is selected -- which I've posted about elsewhere.)

**Comment by viverechristus** [comment]
Of course, I should note that this has nothing to do with the file itself, but the filename in the \fig tag. I troubleshot the issue without ever changing the original filename, only changing the reference in the \fig tag.

**Comment by markpenny** [comment]
I've added capability to handle the .tiff (and .jpeg) files but have hit a strange issue: pictures are coming out as expected when using a PicList in both single- and double-column mode. But for the life of me, I can't get them to display when in single-col mode when using \fig inline \fig* markup. They all show up for double-column layout, but disappear in single-col. Can you confirm whether you get this same behaviour (in 0.8.5 or earlier)? It all works fine in other projects - which makes me wonder if there is something peculiar about your setup which is causing it to trip.

**Comment by viverechristus** [comment]
I can confirm that in 0.8.5, I get the following behavior:

- Double column: pictures output **correctly** for either inline or Pic List
- Single column: pictures output **correctly** for Pic List
- Single column: **inline produces only white spaces**

These are simply .jpg files.

**Comment by viverechristus** [comment]
Identical behavior in 0.8.6 (but you already know that).

**Comment by markpenny** [comment]
Fixed by MH in 0.8.7
