### ISSUE TITLE
Saving Config to a new name does not save an exact copy of the current Config files

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#115]
Just before updating to 0.8.4, I edited the name of the current configuration, and saved it. PTXprint acted like it saved the configuration.

A folder compare did indeed show a new folder in the Shared folder that had the new config name.
But when I installed 0.8.4 and tried to open that new configuration, it wasn't listed.
Comparing the new folder with the original folder I noticed a few differences (when there should not have been any difference):
1) the file  "ptxprint.cfg" was missing! (Hence PTXprint didn't list this configuration in the dropdown.
2) a few of the PicList files were out of date! 
So, it appears PTXprint copied a different folder in order to create the new folder, rather than copying the one that was currently active. 
NOTE: This might is NOT just be a bug that was in 0.8.2 -- as that is the version that messed this up. I just checked this again with 0.8.4 and it acted exactly the same way. 

Here is the pattern:
* Some time ago I created a configuration "Alkitab-Selaru-2020-06"
* Then I updated it and changed its name to "Alkitab-Selaru-2020-06a" 
* Later I updated it and changed its name to "Alkitab-Selaru-2020-06b" 
* This morning (in 0.8.2) I changed its name in the dropdown list to "Alkitab-Selaru-2020-06c" and Saved it.
* This created a folder with that name, but it did NOT save the "ptxprint.cfg" file! (And the files were *not* identical to "Alkitab-Selaru-2020-06b".)
* I installed 0.8.4 and noticed in the dropdown list "Alkitab-Selaru-2020-06c" was NOT listed. (This is where I discovered the "ptxprint.cfg" file was missing.)
* I closed PTXprint, and I copied the correct "ptxprint.cfg" file from "Alkitab-Selaru-2020-06b" into the ...06c folder. And I also synched the files, as they were not the same. 
* I opened it in v0.8.4. and the configuration opened properly!
* Then I renamed the configuration in the dropdown to "Alkitab-Selaru-2020-06 (v084)" and Saved it.
* PTXprint (v0.8.4) acted exactly the same as v0.8.2, and created a folder named "Alkitab-Selaru-2020-06 (v084)" and copied files into it. BUT it did NOT include the "ptxprint.cfg" file! Nor did it copy the correct files! (So it behaved exactly like v0.8.2)
* Comparing the various folders I found that PTXprint was copying the files from the original configuration folder "Alkitab-Selaru-2020-06" rather than from the current configuration.
* And it was not copying the current settings out to the new folder either. 
 
Expected behavior: All control files, PicList and STY files etc. that are currently active in the RUNNING copy of PTXprint would be the source for the contents of the NEW configuration folder. 

Hopefully this isn't a major issue to fix.

**Comment by davidc86** [comment]
Well, it gets a bit worse... When I finally ran the project, PTXprint finally saved the ptxprint.cfg file (and created a NestedSty.sty file too, but it created these files in the WRONG place, and with the wrong content (even though the content had been correct to begin with). 
It saved these files into a folder named "Alkitab-Selaru-2020-06(v084)" <-- note: no space! (I take it this might be a Linux limitation?) So a warning on "no spaces" would be a good idea, if we try to save a configuration with a space in the name. 

BUT earlier PTXprint DID create the folder "Alkitab-Selaru-2020-06 (v084)" (with a space) and copied files into that folder. BUT the "ptxprint.cfg" and "NestedSty.sty" files were not put there. AND the control files and PicList files were NOT copied into the "Alkitab-Selaru-2020-06(v084)" (no space) folder! So basically the left hand isn't talking to the right hand.

After manually copying all the files I needed for the current configuration into the "no space" folder and restarting PTXprint, it produced the PDF without mishap.

**Comment by markpenny** [comment]
I've tried to explain why this has happened, and your comments here tell me that **we really should warn people at the next release that previous Saved Config settings are likely to get "broken"** - especially if the name contains a space. As painful as this is, I'm glad we're doing this before ver 1.0 - after which it would be painful to 100s or 1000s of users. So bear with us...
Closing issue.
