### ISSUE TITLE
Setting the values of Font Size and Line Spacing on Head-Foot tab puts really odd values in CFG file 

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#116]
Just a heads-up, not sure it matters, but if we change the Font Size from say 10 to 9 using the + - buttons, the underlying file saves the "9" value as "9.000000000000004". Similarly for the Line Spacing and Internote spacing. Just an FYI really. 
Here is the section from my ptxprint.cfg file:
...
fnfontsize = 9.000000000000004
fnlinespacing = 10.500000000000005
fnomitcaller = True
...
includexrefs = True
internotespace = 2.9999999999999996
keepbookwithrefs = True
...
The selected values were: 9, 10.5, and 3 respectively. Just wondering where this precision comes from? And is it intentional or just a silly computed value?

**Comment by markpenny** [comment]
I'll let the TeXperts explain the why, or maybe it is a Python/Glade interaction thing... but I agree - we need to round it to 1 or 2 decimal places so that it reflects what the user set and not 2.9999999999996 (which really is 3.0)! Thanks for the heads-up.

**Comment by markpenny** [comment]
@mhosken [Not urgent - it can wait until next week...] 
I can't see any difference in output (in the .cfg file) when using either of these two options:
`    "paper/fontfactor":         ("s_fontsize", lambda w,v: round((v / 12), 3) or "1.000"),`
vs
`    "paper/fontfactor":         ("s_fontsize", lambda w,v: "{:.3f}".format(v / 12) or "1.000"),`
So where does the .cfg file writer determine what gets written, how it is rounded and how many dec places to use?

**Comment by markpenny** [comment]
Fixed in 0.8.7 - all these values now have 3 dec points in the cfg file.
