### ISSUE TITLE
Diglots with illustrations only work if illustrations are in the primary project

### ISSUE THREAD

**Issue by JDNystrom** [sillsdev/ptx2pdf#118]
Our cluster project's print publication strategy is to publish one back translation as the secondary text in diglot Publications for multiple translations in related languages. We have three of these secondary texts for the 11 primary translations in the cluster. For simplicity, we put the illustrations in the secondary text only. Putting the illustrations in the primary text would mean we would have to do that 11 times, one time for every translation, and fix any errors or make any changes in all those places. It is much simpler for us to do it just three times, one time for each of the secondary texts. 

Currently (Beta 0.8.5), the only way we can get a PDF with illustrations is by switching the primary and secondary texts so that the real secondary text is primary to the software. Then PTXprint will put the illustrations in the PDF. That is a work-around we might be able to live with, but only if the secondary text would actually appear on the left (inner) side, which is an option on the Diglot tab. Currently, ticking that box has no effect. (I have submitted that as a separate issue.)

Even if that option did work, the work-around is still counter-intuitive. Every time a user wants a diglot, he has to remember that, for the purpose of the software, his primary text is the secondary text and his secondary text is the primary text. I do not think that will work well for most of the users I support. So I would like to see PTXPrint able to make a diglot PDF from projects where the illustrations are only in the secondary project. 

I tried using the option to have PTXprint look in a folder for all the illustration files, but that did not work. I need to check tomorrow to see if I actually got all of them in there. I copied in all the ones in the secondary project, but it is possible PTXprint was finding some of them somewhere else.

**Comment by davidg-sil** [comment]
From the  XeTeX side of things... XeTeX "doesn't care" where the picture commands come from. Except... (a) it needs to know where the pictures are (and will moan if they're missing) and (b) it can't have TWO values of \PicPath. I understand why MP & MH have chosen to have 'primary' and 'secondary' projects, but I've always seen a diglot as its own thing, and I'd strongly encourage users to have a specific version of settings for diglot printing vs monoglot, as fontsizes, spacing etc. that work on monoglot may not work alongside another translation. It might even be that the one text looks too light / dark compared to another and different font choices are needed.

From the description, it sounds like the captions will then always be in the back-translation language. Is that what's desired?

Anyway, my suspicion is that the python code has been told to generate the .piclist from the primary file only and remove picture specifications from the secondary. I can't verify this, as I don't have any samples with embedded \pic commands, myself, (I've always used piclists for our own work). I know I suggested a few weeks ago that pictures from the secondary get put into the piclist, but commented out. I don't know if that's what's happening. If that IS happening, (the piclist is generated, but with a % in front of the lines) then remove the '%'s and all should be well.

If not, then you probably need to moan at MP to let the user choose which pictures get included!
In the mean time, once the back-translation project has a working piclist (or piclists), that file/those files can be copied and put into another project directory (renaming may be necessary).

**Comment by JDNystrom** [comment]
I moved the \fig references from the back translation to the primary translation. That produced a PDF with the pics in all the right places and the primary text in the correct column.

**Comment by markpenny** [comment]
I've now added code and a dropdown chooser in the UI so that the user has a choice about where the PicList is built from. Primary/Secondary/Both - and if the option for "Both (Pri+Sec)" is selected, then the resulting PicList lines will show an L or R after the initial 3-letter book code (which helps TeX know how to format their captions, etc.) We still have a few other pieces of the puzzle to tidy up (DG: implementing this in TeX diglot code, and MP: making sure that the gather illustrations code looks in the secondary project locations as well for needed illustrations) but we'll get there soon.

**Comment by davidg-sil** [comment]
`there have been some changes in 0.90. Is this issue now fixed?`
