### ISSUE TITLE
Question: putting images in Glossary

### ISSUE THREAD

**Issue by viverechristus** [sillsdev/ptx2pdf#119]
It would be lovely to be able to include images with individual glossary entries. But it's a Catch 22: If I add verse numbers to glossary entries, PT glossary alphabetization (and maybe other things) break. If it's all one verse, ptxprint fails to place the images. Is there a recommended work-around, or possibility of functionality in the future?

**Comment by davidg-sil** [comment]
I guess one option is that non-versified 'books' don't get pictures lifted out into piclists.
Another option is that we make a glossary-entry aware version of piclist

**Comment by markpenny** [comment]
The way that the system is built, images in PicLists **don't** get included in the peripheral (non-scripture) books, **BUT** they **do** get included as regular in-line images. So, they should just show up (if illustrations are enabled) - even if they don't appear in the PicList. This was our only way of getting around the Catch 22 problem you mentioned.
Closing the issue - but feel free to re-open it if you find the behaviour doesn't match what I've described above.

**Comment by viverechristus** [comment]
០.8.6 - Glad to know this. I have a question.

If I specify a partial column's length in the \fig code, I get an error.

`\fig |co00964c.jpg|span*.6||||1:0\fig*`

![image](https://user-images.githubusercontent.com/915182/85843330-35f95c00-b7cb-11ea-8112-f85fdf877921.png)

Is there a way to scale the images in the Paratext code (similar to what I've attempted) - since without a piclist, any adjustments have to be made outside PTXprint. Thanks!

**Comment by davidg-sil** [comment]
I've just seen this, away from my PC, but shouldn't it be 0.6*span?

**Comment by viverechristus** [comment]
The code used in the Pic List is span*0.6.

![image](https://user-images.githubusercontent.com/915182/86307338-b8a56f80-bc40-11ea-932c-12be0b84c140.png)

However, I tried 0.6*span and still got an error:

![image](https://user-images.githubusercontent.com/915182/86307383-db378880-bc40-11ea-9d0b-3ed51fd77cc4.png)

**Comment by davidg-sil** [comment]
Yes, you're right, it was just my mind playing tricks.  I've no idea if
it's related but we came across a bug recently where footnotes gave an
error when inside character styles (e.g. \wj...\wj*). If Pics are normally
working, can you confirm that the error isn't happening in any 'unusual'
environment?

**Comment by davidg-sil** [comment]
I've just realised... Inside SFM files, TeX has been told to treat numbers
as letters, so that you can inclde them  in \s2, etc. But  you can't
multply things by a letter..
