### ISSUE TITLE
Included figures causing orphaned verse numbers

### ISSUE THREAD

**Issue by viverechristus** [sillsdev/ptx2pdf#121]
Now that I can include figures (thanks!) I'm noticing that sometimes the verse number of the verse to which a figure is "attached" is orphaned - a line break comes between the verse number and the text of the verse.

![image](https://user-images.githubusercontent.com/915182/85523028-a324ba00-b630-11ea-9adf-75dfe31eea36.png)

Out of about 11 images in Matthew, three of them cause this problem. I scanned the whole book and can't find any orphaned verse numbers where there aren't images.

**Comment by davidg-sil** [comment]
Hmm. Probably means there's a stray space in the picture-handling code.

**Comment by viverechristus** [comment]
This may be related to the em space issue: nearly all of our verse numbers
are preceded by em space.

**Comment by viverechristus** [comment]
Confirmed: now that em space isn't sticky (it can come at the end of a line), there are no more orphaned verse numbers in connection with images.

**Comment by davidg-sil** [comment]
I've found one stray space in the picture handling code, so maybe that'll have fixed it for everyone.
