### ISSUE TITLE
Glossary lacks page numbers

### ISSUE THREAD

**Issue by viverechristus** [sillsdev/ptx2pdf#122]
If I output MAT+GLO, and in Head+Foot I select Page Number for Center Header, it doesn't appear at all in the Glossary.

**Comment by markpenny** [comment]
Thanks for finding this issue @viverechristus  Yes, I confirm your findings. The only way I can get page numbers in peripheral books is to use the "Print Page Number at the bottom of Intro page(s)" - [bottom right of the Head+Foot tab]  OR  to set the center Footer to print the page number. None of the header options work in the peripheral books.
@davidg-sil Do you know why this might be happening (both in monodoc and didoc). I'm not sure if this bug/feature/issue has always been there, or whether it is a new regression in 0.8.x

**Comment by davidg-sil** [comment]
OK... well: There are 3 styles of running headers/footers: odd, even and title. Ideally, I guess there'd be a 'glossary' option too, but that doesn't exist (yet?).

If a certain value (\p@gefirstmark), normally containing the last 'mark' on the previous page (marks record the book-chapter-verse), then it's considered a 'title' page. I guess titles set this special value to empty.
The peripheral books don't have any chapter-verse marks, so there'll be nothing to trigger the odd or even running header, and so you're using the 'title' set of headers/footers.

So for peripheral books, what you want to be able to set is \RHtitleleft, \RHtitlecenter, \RHtitleright and RF versions of the same for the footer. 
Note that there's no left/right option here (yet?). The fact that the GUI doesn't expose anything except RFtitlecenter is up to @markpenny, I assume.

You need to bear in mind that changing these will affect the first page of text as well as any introductory pages, unless you fiddle with them before starting the glossary, which is of course possible.

**Comment by davidg-sil** [comment]
New patch made to XeTeX macros that adds another set of RH..., RF...  defines, for when there are no verses on a page. Also RHtitle and RFtitle are now actually applied.

**Comment by davidg-sil** [comment]
Is this fixed, or is there a need for python coding too?

**Comment by markpenny** [comment]
Fixed now in 1.1 to be released shortly.

**Comment by viverechristus** [comment]
This is fixed for me (prior to 1.1.9 -- I can't test in 1.1.9 because I can't Print anymore). Do I need to click "Close" myself, or is that your job?

**Comment by davidg-sil** [comment]
Thank for confirming that its working. You could have closed it, I think.

**Comment by mnjames** [comment]
> 
> 
> New patch made to XeTeX macros that adds another set of RH..., RF... defines, for when there are no verses on a page. Also RHtitle and RFtitle are now actually applied.

I'm commenting here for future reference. (It took me a half hour or so to track down the code to find what the new header/footer defines were and then to find out why they weren't being implemented correctly).

From the documentation on the relevant patch: https://github.com/sillsdev/ptx2pdf/commit/0ae2a69e225c5d2ad15f3edb995d16c9b75de363

> Patch introduces new set of running header and footer positions, for odd and
even pages without verses (mnemnonic: noV[erses]):
>
>\RHnoVoddleft, \RHnoVoddcenter, \RHnoVoddleft
\RHnoVevenleft, \RHnoVevencenter, \RHnoVevenleft
>
>and RF equivalents for footer.

Also, it may be necessary to also add `\def\FooterPosition{1.0}` in your ptxprint-mods.tex file.

**Comment by davidg-sil** [comment]
Sorry you spent half  an hour looking at git commits...
The parameters are documented in the README.md:

https://github.com/sillsdev/ptx2pdf/blob/master/docs/documentation/README.md#ptx2pdf-MacroSetupParameters-NoVpage
