### ISSUE TITLE
Verse decoration breaking diglot alignment

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#124]
I have two projects that both use PrintDraftChanges.txt to add Arabic style verse decorations to verse numbers.
```
"(\\v (‏)?[0-9]+?(‏)?-)" > "\1۝"  # The (‏)? surrounds an optional RTL marker 0x200f
"(\\v (‏)?)" > "\1۝"
```
However, when these are in affect the diglot tool cannot use "Align at Verses". Commenting them out fixes the problem.

This may be too specific of an issue to be fixed within ptxprint, and I already have a solution, so if there's not an obvious fix you can probably close this immediately. But I would expect that if two verses had the same "number", even if it included non-digit material, that the diglot would align things properly. For example, if both projects say a verse is `۝۱` I would expect them to line up [note the font in github isn't combining those characters properly].

I wouldn't necessarily expect ptxprint to align things if both projects weren't using the same changes, e.g. to align `۝۱` with ‌`۱`.

**Comment by davidg-sil** [comment]
OK.. well, I'm actually surprised the RTL marker doesn't totally confuse the alignment, but wonders never cease.

I'd suggest that merging should happen before any processes that do stuff to verse numbers are applied.
Sorry @markpenny, more complexity for you.

**Comment by mhosken** [comment]
Would it be better to use \va here?

**Comment by mnjames** [comment]
I hadn't thought of hooks, but I don't think they'd work because we need the same decoration around multiple numbers in ranges.

\va markers might work. If I end up going that route I can probably write a regex to automate the change.

However, I hadn't known about \AdornVerseNumber and it looks very promising. Adding `\def\AdornVerseNumber#1{۝#1}` into `PrintDraft-mods.tex` works correctly in multiple projects when printing from PT, but only works in 1 out of 3 I tested when using ptxprint. Is there some reason `PrintDraft-mods.tex` would be read by some ptxprint projects but not others?

**Comment by mhosken** [comment]
We have now changed PrintDraft-mods.tex to ptxprint-mods.tex and have made it unique to the configuration. I suspect that you may not have clicked the advanced checkbox to enable it. And yes you'll need to copy it into existing configurations in Paratext?Projects/PID/shared/ptxprint/<config>. New configs will copy it from PrintDraft/PrintDraft-mods.tex.

**Comment by mnjames** [comment]
Thank you. Adding `\def\AdornVerseNumber#1{۝#1}` to `ptxprint-mods.tex` did indeed fix that problem.

I'm still have two problems with the diglot though.
1) My introduction ends with a \pb page break before the first chapter. When printing each text on its own, I have no problem. But when printing a diglot I get a message that says `orphan marker \pb: may only occur under \c`. This is true even when all introduction options are turned off in the Body tab. The resulting diglot is missing the entire leftside text.
2) (after removing the \pb from the source text) When I run the diglot, I get a message that says `missing space after verse number '___'`, with different numbers filled in. When I checked the location I find that those are verse ranges in one language but not in the other. Can ptxprint not create a diglot if there are verse ranges? Note that this is a RTL text, so there's a Paratext-added RTL marker hidden in the range: `\v # RTL dash #`
