### ISSUE TITLE
Piclist only lists two pics, and only in one book. 

### ISSUE THREAD

**Issue by JDNystrom** [sillsdev/ptx2pdf#125]
I have not been able to figure out why I can't generate a piclist for any book but one, and in that one, only three pics are listed. I have not been able to discern why those two instances are different from all the rest. I have stared at the various entries and have confirmed it's not punctuation in the caption. It's not quotation marks anywhere. It's not span vs. column. It's not whether or not the book is included in the reference at the end. It's not whether the "copy" field is included or not. I don't think it's the SFM around the \fig...\fig* sequence. It's not .TIF vs. .tif. It's not \fig at end of paragraph or not. Moving the \fig at JAS 1.6 to 1.8 (to the end of the paragraph) did not help. 

I don't know what else to look for.

**Comment by markpenny** [comment]
@JDNystrom - let's chat on Skype tonight (29th pm IST=GMT+5.5, which is Monday morning for US time) if you're available. Buzz me and I'll call back as soon as I can. Is this for scripture books or peripheral books - as currently you can only generate a PicList for books with Book Ch:Vs references. There's talk of adding an option to allow PicLists for peripheral books too, but that won't happen yet. Inline figures should just show up in those other books.
The "Generate" button will/should attempt to make a PicList for any/all books listed. So if you only got a PicList for ONE book, check to see what books are listed to be printed.

**Comment by JDNystrom** [comment]
I'm trying to get a PicList for James. I only have James selected on the Basic tab, and also have it selected on the Viewer tab. It finds two pics in James, but not the others that are in the text and that do get formatted and printed in the PDF.

**Comment by JDNystrom** [comment]
Today I got it working. PTXPrint will not put a pic in the piclist if the "reference" contains the book name.

**Comment by markpenny** [comment]
Yes John, I've fixed that but we haven't released 0.8.7 yet.

Just checked in for our internal flight to Mumbai! ... We're on our way to
NZ

Mark
