### ISSUE TITLE
Can't get 0.8.6 to close

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#128]
This is weird. The program looks to be closed and no indication in the Task Switch view or the taskbar showing PTXprint v0.8.6 is running, but Task Manager says it is still a running application. (Granted it isn't doing anything, but it is still showing in the Task Manager list.) End Task does nothing. It I try it more than once I get an error saying:

![image](https://user-images.githubusercontent.com/65363206/86053615-bd8ed700-ba26-11ea-8700-52d109266e07.png)
  
Like I said. Kind of weird. I haven't noticed this before, so I'll keep an eye on it, and let you all know if I see a pattern. (I haven't run PTXprint today, so this might be a "resume from sleep" ghost.

**Comment by markpenny** [comment]
Thanks for reporting it. Yes, there are a few show-stopping looping bugs that we're trying to eliminate before posting the next version. But it is hard to know if we've found them all... So keep us in the loop if you find this still happening post 0.8.7

**Comment by markpenny** [comment]
We've done our best to eliminate the ugly looping bugs. If something really goes wrong then PTXprint will abort the job after 10,000 pages have been output - so you can at least recover ...

Closing this for now. Feel free to re-open it if you're seeing similar behaviour in >= 0.8.8
