### ISSUE TITLE
Readme says 64bit program, won't run on 32-bit machine but it installs in the 32-bit program folder

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#129]
Readme says PTXprint is a 64bit program, and it won't run on 32-bit machine.
But in Windows, it installs in the 32-bit program folder (**C:\Program Files (x86)\PTXprint**) 
Rather than in the true 64-bit program folder (**C:\Program Files\PTXprint**)
Any reason for that?

**Comment by markpenny** [comment]
@mhosken Should I attempt tweaking the .iss file to see if we can make it behave as a true 64-bit citizen? Or is there more to it than that?

**Comment by davidc86** [comment]
I believe software settings are marked in the Registry in a different place as well for 64-bit programs (if you are fooling with the Registry at all).

**Comment by markpenny** [comment]
This is now happening in 0.8.7 (and @davidc86 - I'd appreciate you testing it out [using this link](https://drive.google.com/file/d/1P6qVX4MfqxY51LzH8FheUOYwKssSEiOi/view?usp=sharing) before it goes onto the official SIL site).

![image](https://user-images.githubusercontent.com/12962708/86767962-e6574200-c0a0-11ea-85c7-1d8fd21c2555.png)

**Comment by davidc86** [comment]
I got it! Thanks.

It installed cleanly, and no errors reading the files and settings from 0.8.6, and it formatted the PDF without error.

It did NOT *uninstall* 0.8.6, and so that might be something to mention to testers should do, as the CFG file has now changed (looking at a file-compare), so I suspect 0.8.6 is basically orphaned now anyway. (I.e. one can’t really switch back and forth between these versions, right?)

So, yup, worked just fine on my system. (Win10 v1909)

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
