### ISSUE TITLE
0.2.3 Job won't print when \em marker doesn't have space before.

### ISSUE THREAD

**Issue by philleckrone** [sillsdev/ptx2pdf#13]
I've redone the acr project that I had shared and removed the nested markers (just removed the +) so that all of the books will work except Job. Here is the log file 
[ptxprint-JOBMP1.log](https://github.com/sillsdev/ptx2pdf/files/3880192/ptxprint-JOBMP1.log).

When I deleted the footnote at 15:7 then the book works:
\f + \fr 15:7 \ft Pa hebreo kubꞌiꞌij\em Adán\em*.\f*

I'm not sure I can tell what is causing the failure - actually I figured it out. If I add a space before the \em then the output works. That is probably the correct thing to do (it really should have a space), but it seems like the PDF creator is being a little overly aggressive in verifying my markup. Paratext doesn't complain about this and I've seen situations where someone might mark up only part of a word (affixes on the name of God for instance).

**Comment by mhosken** [comment]
Sorry. I'm tired and sick and cranky. This is a core problem. Do we follow
the spec or allow whatever relaxations paratext supports today and so have
another standard? There is no way that other tool creators can be expected
to divine the ways paratext doesn't require the standard. So let's
endeavour to create texts that do confirm to the standard as specified,
however incompletely. To that end we'll probably add a pretty strict usfm
linter to ptxprint to stop people reporting bugs against the macro package
that are the result of data not confirming to the spec.

GB,
Martin

**Comment by mhosken** [comment]
Having said my piece. I would have to take a look, but I would hope that a
space before a marker isn't required.

GB,
Martin

**Comment by klassenjm** [comment]
Hi Martin ... I am sorry about the illness, and its effects (I understand :-))

I don't *think* we're talking about any relaxations which Paratext supports. Paratext has implemented support for \+ ...\+* since PT 7.4 (I believe), following the standard.

What PubAssist does for these combinations which occur (like \add ... \+nd ...\+nd* ...\add*; or in a footnote \ft ....\+nd Lord\+nd* ...\f*) is to flatten them. InDesign (or any other word processor or page layout tool I'm aware of) does not support nested character styles. PA generates combined named styles for any combinations - like \add+nd or \ft+nd etc. Bev (PA lead developer) could likely explain how that happens, and perhaps that's a similar for making nested styles work through ptxprint (or Print Draft).

**Comment by klassenjm** [comment]
I'm sorry guys ... I replied here to a related issue #10 (about nested markup). Sorry about that.

**Comment by philleckrone** [comment]
Just to be clear about what I am reporting. The issue is that if I have a \em marker touching the text preceding as in this example:  
\f + \fr 15:7 \ft Pa hebreo kubꞌiꞌij\em Adán\em*.\f*
then the PDF fails. If I add the space before the \em then the PDF is created.

**Comment by mhosken** [comment]
I added the line '\+' > '' to your PrintDraftChanges.txt and without inserting the space in that verse, the text ran just fine. It did raise the question why '\\\+' > '\\' doesn't work and why ptxprint doesn't reread the changes file correctly, but I don't think there is a xetex issue here.

**Comment by mhosken** [comment]
Further digging finds that the problem with the \em in the above example is not the lack of space before \em, but the NBSP inserted after it by the change brought about by 'Prevent Orphan Words in Poetry'.

The regexp problem in parsing PrintDraftChanges has been found and is hopefully being fixed.

**Comment by markpenny** [comment]
Phil, is this issue solved now? Please check out the latest version 0.2.6 at the usual link: [tiny.cc/ptxprint](http://tiny.cc/ptxprint)

**Comment by philleckrone** [comment]
Thanks Mark I'm on vacation now for Thanksgiving here in the US I'll take a
look at it when I get back next week.

**Comment by philleckrone** [comment]
Yes, the issue seems to be resolved. Thanks!
Phil Leckrone
Americas Area Language Technology Coordinator
language_software_amareasil@sil.org
704-843-6064 (Office at JAARS)
704-213-2604 (Cell)
Skype name: phil_leckrone
