### ISSUE TITLE
Is there a way to localize the UI?

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#130]
We'd like the local translation organization to be able to access this great tool! But being in English is a hinderance to most everybody in our area (only the very educated and the computer geeks are somewhat comfortable with English). 

Indonesian is a straight Roman-based orthography, so displaying the UI in Indonesian is a no-brainer (unlike for South Asia!). So I was just wondering if there is a way to substitute strings in the install folder, or are there plans to allow for this in the future?

**Comment by markpenny** [comment]
This is on our radar, but is non-trivial right now. I'm guessing we will make this possible later in the year (maybe). But what happens about supporting other languages? Would you be happy if we send and Indonesian support requests your way?

**Comment by davidc86** [comment]
Sure. I know folk who are helping keep the Indo UI up to date on Paratext. They are using an online tool for tracking what strings need updating, etc. Way better than the old method. I assume you know the tool I'm talking about. I wonder if that is something that could be done for PTXprint?

**Comment by mhosken** [comment]
Anyone interested in starting to localize ptxprint into another language, please respond to this bug and we'll send you the necessary .po file and you can start translating some 700 strings.

**Comment by davidc86** [comment]
I'd like to get an Indonesian version going. (I know some guys. :) )

**Comment by markpenny** [comment]
OK, now that this is possible, we probably need some instructions for anyone who would like to localize (some or all of PTXprint's User Interface). In short, here's the temporary process:
a) Inform the team which language you're planning to work on and download the latest .pot (PO Template) [file from here](https://github.com/sillsdev/ptx2pdf/tree/master/python/locales).
b) Download the [POedit app from this page](https://poedit.net/download) or use this [direct link for the Windows installer](https://download.poedit.net/Poedit-2.4.1-setup.exe). 
c) When PO Edit starts up, select the option to Create a New Translation as shown here:
![image](https://user-images.githubusercontent.com/12962708/94668124-28281980-036c-11eb-868a-f8957d6294ba.png)

d) Then enter the name of the language (preferably selecting it from the list):
![image](https://user-images.githubusercontent.com/12962708/94668218-44c45180-036c-11eb-9765-b6012d6484a3.png)

e) And then start filling in the Translation box at the bottom of the screen:
![image](https://user-images.githubusercontent.com/12962708/94668308-5c9bd580-036c-11eb-8137-411cd0fc892f.png)

f) Ensure that you save the resulting .po file (without the 't' on the end) as shown:
![image](https://user-images.githubusercontent.com/12962708/94668478-953baf00-036c-11eb-9b4f-082b02bcd873.png)

g) Send it back to the developers at ptxprint_support@sil.org 

h) Wait for the next version of PTXprint to be released which should include the Localization.

**Comment by markpenny** [comment]
Woohoo!
![image](https://user-images.githubusercontent.com/12962708/99067656-f57e6b80-260f-11eb-9a6f-7be451d3fe35.png)

**Comment by markpenny** [comment]
Just to confirm that we have succeeded in localizing the UI into Spanish. So now we're just waiting for people to supply translated localization files.
If you are thinking of doing this, PLEASE write first to ask for the latest ".po template" file with all the most recent strings.
