### ISSUE TITLE
Linespacing is hard to control

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#131]
Likely I'm missing something, but linespacing seems very hard to control. The Helpfile says it has 3 values:
\Linespace 0  = single space
\Linespace 1  = 1.5 space
\Linespace 2  = double space

To me that is way too general (and it is not clear what the values are when then fontsize is a smaller size, say 9pt). 
Seems to me the specs should be more like this:
\Linespace 0     = NO SPECIFICATION
\Linespace 1     = single space
\Linespace 1.5  = 1.5 space
\Linespace 2     = double space

This approach would allow for:
\Linespace 0.75  (in order to scrunch the linespacing so it isn't quite so spaceous for smaller fonts)

BUT, it'd be more helpful if this worked like Word or other applications, where it is measured in **POINT size**, something like this:
\Linespace 10  = 10pt space between font lines (**regardless** of the fontsize)

This allows for very accurate specifications. Granted, this also allows the user to make the font lines overlap if the fontsize is large and the linespacing is small, so it needs to be used correctly. But this make more sense and acts similar to other applications. 

I realize changing an established spec is a "no-no" as the ripple effect can be huge. But maybe if we supported a new spec like **\LinespacePoints** or some such? (Unless there is a trick already to specify this kind of detail)

Thanks

**Comment by davidg-sil** [comment]
I wonder about how recent that helpfile is. Maybe it needs rebuilding, someone? Absolute control of the line spacing via the style file has been available for quite a long time, and is available via the \Baseline  option or more recently  \Linespace(they are equivalents now),  and it MUST to be set with a TeX-recognisable unit. E.g 0.2in, 10pt (72.27 per in), 10pt (big, aka postscript, points, 72 per inch). etc.

If Baseline / Linespace are set, then other calculations (LineSpacingFactor, etc) are ignored.

**Comment by davidc86** [comment]
So, are you saying we can add identifiers like "in" or "pt" on the numbers to define the units?

**Comment by davidg-sil** [comment]
I'm saying that the version of \baseline I'm familiar with (in the style
sheet) has  always required a unit (a decade or so for ptxplus / diglot
branches). Depending how recent your copy of the macros is, perhaps a
change has  made to linespace, and it is not now a synonym for baseline, or
perhaps you have an old copy and that was the behaviour before it was made
a synonym.

Sent from my phone, sorry for any errors.

**Comment by davidg-sil** [comment]
I've just checked, and the document you initially referred to is **not** current, assuming you're writing about the stylesheet. Could you please specify which helpfile you're referring to, and the date  / version of it if there is one, so we can update it if needed / possible?
There are multiple ways of defining the line spacing. Here they are:

Stylesheet marker-specific entry of \BaseLine. Remember this is marker-specific (i.e. it may make sense to set it for \mt, but not for p, unless you also change it for m, q1, q2, etc). It also ignores the scaling factors \FontSizeUnit and LineSpacingFactors, and will override the default value of the low-level \baselineskip measurement that can be set (see below).

If you want to alter all line-spacing (outside the GUI), relative to font-sizes, then altering the global \LineSpacingFactor makes most sense.  If \baselineskip (see below) has not been set previously, then when the first usfm file is read it is calculated as follows: 
\LineSpacingFactor  * "stylesheet \FontSize of Marker p" * \FontSizeUnit * 14 / 12.

usfm.sty defines \FontSize of Marker p  to be 12, and \FontSizeUnit is often set to something like 0.75pt - 1pt (giving 9pt - 12pt text), but don't quote me.
Thus: \def\LineSpacingFactor{1} gives single-space (14pt if the font is set at 12pt), \def\LineSpacingFactor{1.3} gives 1.3 space, etc. These calculations are done for each change of paragraph size unless the marker has \Baseline defined.

Setting \baselineskip=13.3pt (e.g in the main .tex file)  will override the above start-up calculations for marker p.

**Comment by mhosken** [comment]
See the FAQ for details on how we have addressed this.
