### ISSUE TITLE
Footnote error: Can't place it due to large illustration; causes infinite loop

### ISSUE THREAD

**Issue by KimB2017** [sillsdev/ptx2pdf#132]
In my Christmas Story Bible module I have a few figs placed close to each other. There are also a few footnotes in the specified verses, which are usually included in the printed module. Footnote printing works fine for other PT books, but when I try to PTXprint my module (RTTT XXA) I get an infinite loop. The first time I realized it was hung, the log said it was trying to print page 325,000-something, with a missing footnote.

The module does print fine in PT9–Export draft PDF, so I checked in that output around page 18, where the ptxprint error starts. There is a footnote in between 2 large pictures that looks like it might be the problem.

Interestingly, in my module specs (attached), the project window and both ptxprint and PrintDraft output in both PT8 and PT9 **include footnotes** even when I change the specification **to omit them** (\inc marker).

Also, after a few experiments with ptxprint on XXA, the computer appeared hung: In the attached System Monitor screenshot the two xdvipdfmx instances were "ptxprint-XXARTTT.pdf" files. I have 24GB RAM; it was showing 100% used and the 4 CPU cores were going crazy as well until I killed these instances.

Anyway, here is the relevant portion of the log, along with the PrintDraft output pages  which I think caused the problem. The hung ptxprint output pdf is unreadable, but it's related to the whole issue. If you want to see it I can try to send it.

In addition, [Paratext9-Linux very slow, ptxprint was xkilled 10 min ago; print draft pdf invoked but finished](https://user-images.githubusercontent.com/25071218/86482331-134fe000-bd95-11ea-945d-02c651149181.png)
 and a couple of screenshots.
[ptxprint-XXARTTT_error.log](https://github.com/sillsdev/ptx2pdf/files/4870386/ptxprint-XXARTTT_error.log)
[printdraft-RTTT-XXA,partial.pdf](https://github.com/sillsdev/ptx2pdf/files/4870388/printdraft-RTTT-XXA.partial.pdf)
![Paratext9-Linux very slow, ptxprint was xkilled 10 min ago; print draft pdf invoked but finished](https://user-images.githubusercontent.com/25071218/86482516-75104a00-bd95-11ea-9288-51d0cb72f888.png)

**Comment by KimB2017** [comment]
A couple more files you might find helpful.... Renamed because I can't attach a .sfm file.

[94XXARTTT-draft.SFM.txt](https://github.com/sillsdev/ptx2pdf/files/4870590/94XXARTTT-draft.SFM.txt)
[Christmas Story Module 2019_Nov_noSweet.sfm.txt](https://github.com/sillsdev/ptx2pdf/files/4870595/Christmas.Story.Module.2019_Nov_noSweet.sfm.txt)

**Comment by markpenny** [comment]
@mhosken - do you have any idea what might have gone wrong here? It could be one of the infamous loops that we've fixed in the last week.

And related to this, is there something that we need to do on the TeamCity server to get the Linux packages to be built, or will that always be a manual process? In other words, it would be great to have the Linux installer also available when each Win version is released (zero-lag).

**Comment by mhosken** [comment]
ptxprint is being built and packaged daily. @KimB2017 any chance you could update and do a quick retest. If the problem persists I will dig based on the files above. TIA.
