### ISSUE TITLE
Make PicLists easier to edit

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#134]
Present a GRID/table view of the PicList so that users don't have to deal with the | separator and have CB's for choices (like col/span) etc. (Probably post 1.0)

**Comment by davidg-sil** [comment]
Alternative mght be to use the usfm3 style named parameters.

**Comment by davidc86** [comment]
I don't find it too hard to edit now. But yes, maintaining the exactly correct format with the right number of ||| etc. is a bit fiddly. So, yes, a table/grid would be great. I like seeing all the pictures listed one after the other, as it makes it easy to verify that we are being consistent in formatting and labeling etc. So the list idea is great. 
But I had thought of maybe making it so if a user clicks on one of the picture rows, it opens that picture's specs in a dialog (kind of like in Paratext), with all the options limited to valid values. Clicking OK repopulates the grid/list with the updated information. But I have no idea what is easiest to implement.  
Maybe just having a grid/table/list with a header that tells us what are valid values? Anyway, what we have now works well, if we are careful.
