### ISSUE TITLE
Additional position codes for pictures (Opinion poll)

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#136]
It would be helpful to us if non-scripture books would by default handle pictures "in-line", so that they are not positioned anywhere on the page in particular (not Top or Bottom), but rather dealt with paragraph by paragraph, so if a title or a paragraph occurs first, it goes above the picture, than the picture, then the next paragraph and text, etc. This would help me get my "Maps" section of the PDF to come out looking better than it does now (where PTXprint puts the first map ABOVE the title of the "book"). 
 
Allowing pictures to occur "in-line" would also help us get the organizations' logos to position properly in the Front Matter. 

_Originally posted by @davidc86 in https://github.com/sillsdev/ptx2pdf/issues/135#issuecomment-654265293_

**Comment by davidg-sil** [comment]
I've no significant objection(given time) to implementing some other layout-options, but it needs better definition.
The 'obvious' (at least to me) non-float options are
- in-line (will this always mean centred?)  
- cutout (left/right, but expect clashes with drop-caps chapter numbers)
- before a given verse (from a piclist) 
- at end of paragraph (from a piclist)

**Comment by davidc86** [comment]
Well, "inline" can also just mean between paragraphs, so if the \fig line is sitting in a \m paragraph all by itself, then it is probably left aligned. But then I also thought there was a way to mark centered, left, right in the \fig field itself.
One step at a time though.
* **In line centered** would accomplish MOST needs right out of the gate.
The idea of "before a verse" or after a paragraph are interesting and might be very useful too, but what we have now, plus inline-centered would cover almost everything for now.

**Comment by davidg-sil** [comment]
Current thoughts / status
- cutout left / right [working, crudely, currently only at top of following paragraph, not in same paragraph as chapter number cutout]
- inline centered [working]
- inline left/right-aligned [todo] 
- after paragraph [todo]

**Comment by davidg-sil** [comment]
Please take the opinion-poll on this [Here]( https://docs.google.com/forms/d/e/1FAIpQLSdtbYfYqF98jDwxsQCYNxW5h6jDmHm5NqSTr9pV4u5XRSTbtQ/viewform)
