### ISSUE TITLE
Picture set bottom left pushes text right, set top-right vanishes.

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#139]
Reposting from a early this week, on the wrong board...

(at least on a small page). I'm guessing that moving to the right is a balancing issue. The vanishing image may be related, not sure which most serious.

[test.pdf](https://github.com/ubsicap/usfm/files/4886504/test.pdf)

test.tex:
```
\input "paratext2.tex"
\stylesheet{usfm.sty}
\BodyColumns=2
%\input "usfmTex-ext.tex"
%\input "hooks.tex"
\tracing{g}
% Set added material in desired form
\csname ColorFontstrue\endcsname
\ptxfile{test.usfm}
\bye
```

test.usfm:
```
\s This is a title
\p
\v 1 This is normal text. 
\fig This is a rose, not a fig |loc="bl" src="image.jpg" alt="Figs are tasty"  ref="1:1" size="col*0.5"\fig*
\v 2 I wonder what happens here.
```
(get rid of the *0.5 if using historic macro versions)

**Comment by mhosken** [comment]
try with the next version

**Comment by mhosken** [comment]
assume fixed
