### ISSUE TITLE
Suppressing black bar showing overfull hboxes

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#14]
I believe this is a feature request. Or I just missed the setting I needed in the existing tool.

Could you add a toggle to prevent xetex from putting a black bar in the margin to indicate overfull hboxes. The actual code to do this in xetex is `\overfullrule=0pt`

An unrelated small suggestion would be to add to the `Apply Watermark PDF` description when you hover over it so it also says `This is often used to add borders to a text.`

**Comment by markpenny** [comment]
Great suggestion. Now implemented. You will find the toggle on the Advanced tab. (it will be in 0.2.4 whenever that becomes available).
