### ISSUE TITLE
New Generated Pic List files have errors

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#142]
I just compared a set of newly generated Pic List files with ones that I'd worked on a few days ago, and there are serious differences. It looks like the "Generator" is not processing the files correctly. The specified verse reference anchor is not even close to the one listed in the \fig field. I.e. The \fig fields in **single-digit chapter numbers** are formed correctly:

GEN 1.19 |CO00600B.TIF|col|tl||Hulasokwe yala masire ror manunare|1:19
GEN 1.31 |CO00601B.TIF|col|tl||Hulasokwe yala nam ribun mamin lasmyerke khaha ne ma ktei mumu de|1:31
GEN 3.10 |CO00609B.TIF|col|tl||Adam yor Hawa rmay kali ramleh|3:10

But in double-digit chapters the 10s value in the reference verse is truncated (and for some, even the verse number changes, but that might be due to where the actual \fig field is in the chapter): 

GEN 1.7 |CO00638B.TIF|col|tl||Iry Babel-are rsadiri sey atatke|11:5
GEN 2.3 |CO00661B.TIF|col|tl||Abram byetik toha hnu Haranke|12:3
GEN 2.19 |CO00646B.TIF|col|tl||Firaun yal haretke ti wasi irire ma rtian Abram yor sawa Sarai toha Mesir|12:19
GEN 5.11 |CO00649b.tif|col|tl||Abram yatos thunare o laitke|15:5
GEN 9.8 |CO00651b.tif|col|tl||Wamwany mamin ti hnu Sodomke rkoal eta Lot wasi sekye|19:8
GEN 9.26 |CO00656B.TIF|col|tl||YANWE nyauk us akye ode us hatw maharharke kyosy a laitke ma ti ktyuhar hnu Sodom o Gomora|19:26
GEN 1.16 |CO00659B.TIF|col|tl||Hagar tyutuk anan desy ti sitw o tnyei krintyotan|21:16
GEN 2.8 |CO00663b.tif|col|tl||Abraham lyatak Ishak ti lat raeh heal ti Hulasokwe|22:8
GEN 4.17 |CO00667B.TIF|col|tl||Abraham wasi makaryake iten werke toha Ribka|24:17
GEN 4.61 |CO00670B.TIF|col|tl||Ribka syai untake ma rba|24:61
GEN 5.28 |CO00674B.TIF|col|tl||Esau iten slyety mermerke toha Yakub|25:28
GEN 6.9 |JACOB318.tif|col|tl||Raja Abimelekh kyeyer a Ishak|26:9
GEN 6.20 |JACOB316.tif|col|tl||Iry a Gerar-are rala ma railir ror Ishak hatnimanare|26:20
GEN 7.17 |CO00681B-full.tif|col|tl||Yakub yety kotw ti ama Ishak ma nya|27:17
GEN 7.26 |CO00679B-flipped.tif|col|tl||Ishak iten eraske ti anan Yakub|27:26
GEN 7.30 |CO00678b.tif|col|tl||Esau idoha heal ma enmo mya|27:30
GEN 8.15 |CO00683b.tif|col|tl||Hulasokwe wasi nyasoare rorw de rsai areske|28:15
GEN 9.12 |CO00687B.TIF|col|tl||Yakub lyilik hatkwe toha wer desy ti Rahel|29:12
GEN 1.39 |CO00689B.TIF|col|tl||Yakub kyeyer a memi Laban|31:39
GEN 1.47 |JACOB350.tif|col|tl||Yakub yor Memi Laban rautun hatw ma klyosu tun rahatetakare|31:47
% GEN 2.8 |CO00690b.tif|col|tl||Yakub a ihe a wasi tairke enaru|32:8
GEN 2.26 |CO00686B-shining.tif|col|tl||Yakub ibesak a ia yor Hulasokwe|32:26
GEN 3.4 |CO00693B.TIF|col|tl||Esau ila ti yoy a Yakub ma rasera sir|33:4
GEN 5.8 |CO00760B.TIF|col|tl||Yakub yor hatnimanare rsoru wait laklakutke|35:8
% GEN 6.8 |co01489b.TIF|col|tl||Yakub yor Esau it de ituli it kali kotkwe lema lan ti wen desy|36:8
GEN 7.7 |CO00699B.TIF|col|tl||Yakub lyobak anan Yusuf ma kbyilak wainare|37:7
GEN 7.24 |CO00704B.TIF|col|tl||Yusuf wainare rkumak a i|37:24
GEN 7.28 |CO00709B.TIF|col|tl||Yusuf wainare ratos iry a Ismaelare (Midian-are) ma rma|37:28
GEN 7.35 |CO00710B.tif|col|tl||Ruben syusu Yusuf wasi rabitke ti amatke|37:35
GEN 9.6 |CO00716B.TIF|col|tl||Potifar sawa-na hyury a Yusuf|39:6
GEN 9.23 |CO00719B.TIF|col|tl||Yusuf imin ti sey metmetke kralake|39:23

I haven't noticed this odd behavior before, so this must be a new glitch?

**Comment by markpenny** [comment]
Thanks for spotting this as well @davidc86  I also discovered it while working on PicLists (for Diglots) last week, and it has been fixed. AFAIK, this glitch only affected DC and JN's testing. An official 0.8.7 should be available on the site later today which won't have that issue.
HEB 9.1 |co00843b.tif|col|tr||Offering altar|9:1
HEB 9.15 |cn02103b.jpg|col|tl||ciṭi lihi kiyval|9:15
HEB 9.15 |cn02103b.jpg|col|tr||Writing a letter|9:15
HEB 10.20 |cn01843b.tif|col|tl||mandirta paḍda poroḍalte būḍ sarval|10:19-20
HEB 10.20 |cn01843b.tif|col|tr||The temple's curtain tearing from top to bottom|10:19-20
HEB 11.2 |co00604b.jpg|span|t||kalita jivras ani mara meṭa gaḍe māyval|11:2
HEB 11.2 |co00604b.jpg|col|tr||Creating the animals and plants|11:2
HEB 11.7 |co00626b.jpg|span|t||nōvahu tanva kuṭumbatun baci kiyle rūka tayar kītor|11:7
HEB 11.7 |co00626b.jpg|col|tr||Noah made a boat to save his family|11:7
