### ISSUE TITLE
PicList comes from where? Because v8.8 is showing the wrong list. 

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#144]
Thanks for fixing the problem where there are no PicList files when a new configuration is saved (or printed) and we want to use the PicList feature.
And now, if I open a fully functional configuration, and I save it to a new name, PTXprint copies the whole folder over. And the PicList is identical to the ones in the previous configuration. Woohoo!

This is really strange bit: If I open the configuration file (the one with special tweaks in the PicList files) in PTXprint, and I jump to the View page, PTXprint shows the wrong PicList file! Clicking on View/Edit button does nothing!
BUT If I open the PicList file from the Pictures tab, it shows the correct one!  And then the View/Edit button works!
So, on initial opening of a configuration, the Pic List file displayed in the View tab is the wrong one.

**Comment by davidc86** [comment]
Okay, I determined that when PTXprint starts, and we open a config file, the View tab by default shows the PicList files listed in the folder: **<project>\shared\ptxprint\PicLists** 

I'm not even sure why there is such a folder on my computer but there is. Maybe it came from an **unsaved configuration/print run**. If so, I think it would  be clearer to users if these "unsaved" files were stored/saved into an "default" or "unsaved" configuration folder, so they would exist on the same level as the named configuration folders.

**Comment by markpenny** [comment]
I think there is an assumption (which may or may not be true) that most [non-advanced] users will never bother saving their configuration. So for them, anything they do which creates config file (.cfg PicLists, AdjList, etc.) will cause these things to be stored within \shared\ptxprint   And so for most users there won't be any "Saved Configuration" folders. However, if they do save a particular config it will copy those settings to a new folder.

If you want to intentionally reset the default settings, then deleting the **\shared\ptxprint\ptxprint.cfg** file should do the trick.
