### ISSUE TITLE
V0.8.8b trashes the Pic List files when I click PRINT

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#146]
So I just opened a nicely working configuration in the new 0.8.8b version of PTXprint, and clicking PRINT does nothing (BIG problem).
But the other problem is that it completely rebuilt my entire list of PicList files when I hit PRINT, and it built them **incorrectly**. 
It eliminated all the SPAN specs I had in it and changed them to COL and also changed all my "t" specs to "tl" specs and messed up the captions too. See this screen shot: the RIGHT side is the GOOD v0.8.8 version, the LEFT side is the BAD 0.8.8b version:
![image](https://user-images.githubusercontent.com/65363206/87565229-5e200080-c68f-11ea-87e4-94599847d952.png)

**Comment by markpenny** [comment]
This is solved in 0.9.0 but we're still weeding out bugs in this area so feel free to re-open again if it is still an issue.
