### ISSUE TITLE
V0.8.8b won't PRINT

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#147]
If we click PRINT, the new v0.8..8b does nothing. (Well, yes, it does, it trashes my PicList files, but other than that, it does nothing.)

**Comment by mhosken** [comment]
Often in such situations, python, which is running ptxprint, will print an error with stack backtrace and then carry on. I'm not sure whether running ptxprint.exe from a command prompt will enable you to see that error. If so, do submit it here. TIA.

**Comment by mhosken** [comment]
Further to this, I have just committed a change such that if you run ptxprint.exe -l it will route stderr and stdio to the file "ptxprint.log" in the current directory. Hopefully this will allow you to catch such error messages.

**Comment by markpenny** [comment]
This should be fixed in 0.9.0

**Comment by davidc86** [comment]
Bummer but this is not fixed (on my machine anyway).
