### ISSUE TITLE
v0.8.8 and v0.8.8b can't read some configuration files correctly

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#148]
I have two folders with identical contents:
"AlkitabSelaru-2020-07-14" 
"AlkitabSelaru-2020-07-15"

PTXprint opens the contents of the ...14 folder just fine, with all my settings and specs checked properly.

But if I select the ...15 configuration, PTXprint doesn't load any of the configurations specs, even though the two configuration files are IDENTICAL. 

Any clues? 

BTW, I was having so much trouble with v0.8.8b that I uninstalled it and went back to v0.8.8. It will now print again, but ODDLY, it won't open up the saved "AlkitabSelaru-2020-07-15" configuration file correctly either. Though it will open the ...14 file just fine! These two files and their associated folders are **_identical_**. I looked for some sort of path or folder name inside but I'm not seeing anything that might be confusing PTXprint, so I'm baffled on this one.

**Comment by markpenny** [comment]
I trust these things will be sorted in 0.9.0 about to be released as soon as we can.
