### ISSUE TITLE
Request: Add "omit pictures..." option for Generate PicList

### ISSUE THREAD

**Issue by viverechristus** [sillsdev/ptx2pdf#149]
In our project, we have two pictures attached to some verses, one of the picture marked with "p" for printing and the others marked with "a" for app.

This works fine if we simply "Use Pictures Marked in the Text," because we can select "Omit Pictures Only Meant for Web or App." But if we want more control using the PicList, it doesn't work, since Generating the PicList gives an error ("Multiple Illustrations attached to a single verse"). The resulting list omits many of the pictures.

REQUEST: Ideally, there would be an option in the (Re)Generate section that says something like "Omit Pictures Only Meant for Web or App" or "Include Only Pictures Meant for Print."

Thanks!

**Comment by viverechristus** [comment]
Incidentally, a workaround is the place the "print" picture AFTER the "web/app" picture, because for whatever reason, the PicList omits the first of the two illustrations attached to a single verse. I can then go through and delete all the web/app pictures in the list.

**Comment by davidc86** [comment]
But isn't the "no more than one picture on a verse" just a silly limitation that the software currently can't handle two illustrations pinned to the same verse? 

There are a few places where this is the logical way to enter the pictures, like when in Genesis they are listing the ancestors of various skills, and one guy is the ancestor of all who play stringed instruments and the flutes. Our team wants a harp picture on the left and a flute picture on the right, side-by-side. In James he writes of two kinds of trees, and the team wants both types shown. So, saying we can't link two pictures to one verse is a rather odd restriction.

We use the PicList files, and I first let PTXprint generated the lists and whine about the two pictures on one verse. Then I just change the second one to attach to the next verse. This way at least we get both pictures printed on the same page. But what would be ideal is to be able to specify TL and TR to get the two pictures on the Top-Left and Top-Right of the same page. But so far, that is not doable, right?

Anyway, this is not exactly related to the request, so the ability to flag a set of pictures to be ignore is still a legitimate enhancement for those that need it. 

And the idea of putting the "print" pics after the "web" pics is creative, I'm only concerned that leveraging a program "limitation" to get some unique behavior is bound to break once the program is enhanced to not have that limitation. (Like automatically attaching the 2nd picture to the next verse.)

**Comment by davidg-sil** [comment]
> But isn't the "no more than one picture on a verse" just a silly limitation that the software currently can't handle two illustrations pinned to the same verse?

Someone in the past wrote in the documentation that TeX can't have several images attached to a single line of text. I don't know why that ought to be, it sounds like a bug if it's true. But, because of that 'report' the code doesn't try to look for a second line in the piclist matching the current verse. Post 1.0 I plan to do some testing of a 'so, does this new entry match where we are now' check, to allow 2+ piclist entries on the same verse. (That'll be in the XeTeX macros, not the python stuff. I don't program in python, so the python might still get in the way.)

**Comment by mhosken** [comment]
If a picture has a media attribute (either through using usfm3 attributes or usfm2 columns interpretted as a media) which does not contain "p", it will not be considered for inclusion by ptxprint.
