### ISSUE TITLE
PDF/X-1a:2003 format option not complete?

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#153]
When I check the option "Output in PDF/X-1a:2003 format", the output is not actually compliant to that format, according to Adobe Acrobat Pro:

![image](https://user-images.githubusercontent.com/14953913/88532829-2e60e900-cffd-11ea-9225-2c28099d9f3c.png)

Is this deemed to be "close enough" for SIL GPS publishing requirements? If not, I believe Adobe Acrobat Pro can fix those errors, so I think we would at least have a path forward.

Is it the addition of the color profile, i.e. the lines in the .tex file around this:
`\special{pdf:fstream @OBJCVR (C:/Program Files (x86)/PTXprint/ptxprint/ps_cmyk.icc)}`
that is supposed to be the main part of according compliance? I'm pretty sure putting the following lines in the docinfo doesn't ensure compliance:
`/GTS_PDFXVersion(PDF/X-1:2003)%`
`/GTS_PDFXConformance(PDF/X-1a:2003)% `
It just says "we comply!" without really making any changes...

And it looks like Adobe Acrobat Pro in this preflight report was looking for PDF/X-1a:2001, not PDF/X-1a:2003. But still I’m wondering in those lines that you output, isn’t there a missing ’a’? I imagine it should be:
`/GTS_PDFXVersion(PDF/X-1a:2003)%`

The RGB images reported are page borders. I suppose that if I can get those PDF images into CMYK, that probably would fix that problem?

**Comment by markpenny** [comment]
We are aware of some issues in here and will work on them post ver 1.0

**Comment by mhosken** [comment]
We won't be able to just make all output conformant (or we wouldn't want to), so we will want a ptxprint UI checkbox for this.

How to meet these requirements:

- Call xetex -no-pdfs and call xdvidpdfmx directly with -z 0
- Add \ifDropActions to allow disabling generation of TOC for conformance [DONE]
- Call xdvipdfmx -c to disable colours and/or disable colour fonts in the ptxprint UI.
- Fix docinfo. Yes GTS_PDFXVersion is only PDF/X-1:2001 and not PDF/X-1a:2001, according to specs. [DONE]
- Change GTS_PDFXConformance to PDF/X-1a:2001. [DONE]
- Only use either \TrimBox or \ArtBox (need to decide which)

Thankfully the requirements for PDF/X-1a:2001 are far less stringent that PDF/A.

**Comment by jeffheath-sil** [comment]
I don't see this as a show-stopper, but as nice to have. Someone with Acrobat Pro can force a PTXPrint output to conformity to a standard, if it is required. And you can even rent Acrobat for a month or two.

From my (limited) testing, the main culprit of non-conformance was the PDF files used by XeTeX to produce the output. E.g. in my case various borders or decorations. I was able to do some manipulation of those input files (force to CMYK, remove \TrimBox or \ArtBox, etc.) which made for a clearer XeTeX output, but the holy grail would be taking input files in whatever state (e.g. RGB), and then manipulating the output so that it meets the standard.

But I think your first-draft attempts are fine for version 1.0 of PTXPrint.

**Comment by mhosken** [comment]
Artbox removed in 1.1.9. I plan to do the other 2 steps post 1.2.

**Comment by mhosken** [comment]
All steps are now complete in 1.2.8.
