### ISSUE TITLE
Verse Number Decorator broken

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#154]
I tried to use the Verse Number Decorator, and selected a file "Verse number start.pdf" (in the border-art folder). It seems to sort of leave space, but no stars show up. But this is what I see in the .tex file:

`\setbox\versestarbox=\hbox{\XeTeXpdffile "verseNumDecorator.pdf"\relax}`

No wonder the stars are not showing up... it's got the wrong file name!

**Comment by jeffheath-sil** [comment]
And same is true for the Section Header border... no matter what file you choose, it puts this:

`    \global\setbox\sectionheadbox=\hbox{\XeTeXpdffile "sectHeadDecorator.pdf"\relax}%`

**Comment by davidc86** [comment]
Any chance saving your PDF files to those default names would force it to do what you want? Just guessing here.

**Comment by jeffheath-sil** [comment]
Yes, that probably would work, but that negates the whole idea of being able to select your border, and even have it in a different folder. I wasn't looking for a work-around, but pointing out a bug that needed to be fixed... :-)

**Comment by davidc86** [comment]
Right, I did figure this was more of a "reporting a problem/bug" than "I need a solution", but the hacker in me took over! This is a very cool tool, and these decorative features are a huge benefit to printing in major areas of this planet. I hope this can continue to develop and mature.

**Comment by mhosken** [comment]
Fixed in dev/
