### ISSUE TITLE
Decoration for end of book

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#155]
There is some .tex code that says "NOT YET SURE WHAT THIS IS USED FOR. Commented out until we have clarity on whether it is needed". That is to put a decoration at the end of each book. The decoration I used was:

![image](https://user-images.githubusercontent.com/14953913/88558459-772b9880-d023-11ea-9136-547b748919fe.png)

My processing added a \z at the end of each book, and the code that is commented out defined \z to insert the decoration.

So that's what it does, and now you can decide if you want it or not.

**Comment by davidc86** [comment]
That is very cool.
So isn't there an End of Book marker? Or am I thinking of the End of Introduction (\ie) marker?
Well, I looked at USFM v2.4 and nope, no end of book marker. Weird. There should be one; they have everything else under the sun. 

How about **\eb**? This would be a good, unused SF Marker for "End of Book". 

But what is the desire here, to have this marker trip a standard behavior without having to add a \fig spec field at the end of every book manually? 

I think the idea of being able to add something cool like your symbol "at the end of each book" would be a great option to add to PTXprint (and then we wouldn't have to add it to the Paratext project files). The people we work with would probably like this to be a motif pattern from their traditional handwoven cloth. 

I suppose if the PTXprint development team would rather not add this, then a \fig field could be added manually to the end of each book, right?

**Comment by jeffheath-sil** [comment]
The way I implemented the end of book character was to add a \z at the end of the book (not in Paratext, but through a pre-processing script), and then the code in the .tex file inserted the decoration. If you wanted this in PTXPrint, I would think that you would just have a checkbox and a file selector (like for the section head border and verse number decorator), and if the checkbox is checked, the SFM processing would add some marker to the end of each SFM file (\z or \zz or \eb or whatever), and the .tex file would convert that into the proper decoration.

**Comment by davidc86** [comment]
Yes, I like what you say: *If you wanted this in PTXPrint, I would think that you would just have a checkbox and a file selector (like for the section head border and verse number decorator), and if the checkbox is checked, the SFM processing would add some marker to the end of each SFM file (\z or \zz or \eb or whatever), and the .tex file would convert that into the proper decoration.*

Sounds very useful for anyone making more culturally sensitive books with borders and verse number decorations. I guess this would be an "Enhancement" request?

**Comment by jeffheath-sil** [comment]
Yes more of an "enhancement" request than a bug fix, but something that I think they were intending to implement with the borders and verse number decorations.

**Comment by markpenny** [comment]
Are you happy with the placement (especially when in two-column mode), or would you expect it to be placed somewhere else?
![image](https://user-images.githubusercontent.com/12962708/88922012-98121900-d2c3-11ea-8537-57cc8c3a332b.png)

And in Single-Col mode:
![image](https://user-images.githubusercontent.com/12962708/88922137-d0b1f280-d2c3-11ea-97f2-0846da45596a.png)

Coming in 0.9.0...

**Comment by davidc86** [comment]
Looks great to me! That was how I envisioned this looking. But Jeff would be the one to confirm it. 
Thanks for adding this kind of enhancement already! 
I assume v0.9 will allow users to specify different pic files for this feature, right?

**Comment by jeffheath-sil** [comment]
This is the way that we have used it, both in 2-column and single-column mode. I think Martin was suggesting that some people might want to have the final columns balanced, and then put the decoration in the center of the whole page. If that were added as a checkbox (with the corresponding .tex code, which I'll leave for the experts...), some people might appreciate that. But certainly as a first draft, just centering it on the column would be good. And yes, being able to select the decoration would be important.

**Comment by davidc86** [comment]
Agreed, an option for balancing the 2-columns at the end of a chapter with a single decoration centered on the page would be elegant. But might that be much harder to implement? (As you say, "I'll leave for the experts...") 

But such an option would be nice for Diglots. I think a single decoration marking the close across both versions of the chapter would probably look nicer than having a decoration in each column (which I suspect this feature would do now).

**Comment by mhosken** [comment]
So it's an inline figure scaled not to fill its col, but centred and output either before or after \singlecolumn.

**Comment by jeffheath-sil** [comment]
That's the way I would suggest it is handled, i.e. not scaled at all (the user can scale his/her PDF decoration to change the size), and centered on the column. Some people may want to center the decoration across the entire page of a two-column layout. I assume that's what you meant by saying that it could be output after \singlecolumn. That would require a checkbox in the UI, something like "Cross Columns", which would have no effect in single-column mode.

BTW the help text that comes up when you hover over the "End of Book" checkbox gives the help for Section Header - that needs to change.

**Comment by mhosken** [comment]
@davidc86 Please make any comments about things not working post v1.0 in this issue rather than opening new issues. Thank you. There is no point telling us this doesn't work pre 1.0 because while we might try to work on it, this is not a blocking bug for 1.0.

**Comment by mhosken** [comment]
Useful discussion in #174. Nothing in #215.

**Comment by davidc86** [comment]
Version 1.2
Still not working. 
Here is the relevant settings in my configuration:
![image](https://user-images.githubusercontent.com/65363206/95663768-da4fa600-0b0f-11eb-8d17-ee3192e0ebf5.png)

Here is one of the chapter breaks: 

![image](https://user-images.githubusercontent.com/65363206/95663932-54ccf580-0b11-11eb-9750-5b27986fa1ff.png)

Anybody have a clue why many of us can't get this to work, while the developers have no trouble getting these features to work?

**Comment by mhosken** [comment]
Apparantly this isn't working for some in 1.3.8. If you are one of those people, you know what to do: send an archive.

**Comment by jeffheath-sil** [comment]
This seems to work consistently now.
