### ISSUE TITLE
ptx2pdf code broken - footnotes

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#156]
I have been using the ptx2pdf macros outside of PTXPrint, and with a recent update to the macros in this repo (in the /src folder), I can't run XeTeX anymore. It seems to choke on the first footnote it comes to, with nothing unusual about it:

\f + \fr 1.21 \ft Iisa pa sawwaŋgee daare kolaa kulla goo Yaasu. Ma beneyco Ebireenigeyyo pa, goo Yaasuwa. Seme kooko pa goo: « Mella najjayya. »\f*

This is the error I get:
Unexpected closing marker +fcaller* on stack c+fcaller,P+p,+,. Ignoring
Unexpected closing marker +fcaller* on stack c+fcaller,c+fcaller,P+p,+,. Ignori
ng
! Missing } inserted.
<inserted text>
                }
<to be read again>
                   \endgroup
\n@xt ...et \n@xt \relax \fi \aftern@te \endgroup
                                                  \n@xt
l.80 ... Seme kooko pa goo: « Mella najjayya. »\f*
                                                   asan ga ay gata appe ma a...

?

The code from a few days ago was working fine, and I'm tempted to go back to it, but I'm not sure exactly when it was from. I haven't changed anything on my end relating to footnotes. Is no one else seeing this problem with the latest code?

**Comment by mhosken** [comment]
Try now

**Comment by jeffheath-sil** [comment]
Much better! Thank you! :-)

**Comment by markpenny** [comment]
0.9.0 has just been released and is available on the sil.org site
