### ISSUE TITLE
Editing the Config file outside of PTXprint has no effect

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#158]
I must be missing something, but when I try to make changes to my config files **inside** PTXprint, they don't seem to save properly. So I exit PTXprint and try to make the corrections to the config file **outside** of PTXprint, and load it. But PTXprint ignores the changes, or worse loads a blank config file.

I'm not sure what is going on here. It appears that if the config file deviates at all from what it is expecting PTXprint blows it away and opens a RESET configuration. If it's going to do that, then where can we set the "default" so it is at least close to what we want?

**Comment by markpenny** [comment]
I'm not seeing this behaviour since we fixed the faulty config pathnames. Could you please re-test and get back to me if you're still seeing it do this.
