### ISSUE TITLE
PTXprint v0.9 seems to ignore existing PicList files

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#159]
When I set up a new config file. 
Exit PTXprint
Copy my good PicList files into the PicList folder
And reopen PTXprint and reload that config file, PTXprint doesn't see the PicList files.

**Comment by markpenny** [comment]
Thanks for pointing out this bug. This has been fixed for 0.9.1 Please check/confirm and then close the issue.
