### ISSUE TITLE
Overfull \hbox

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#162]
With the latest changes to the macros, there is a new problem that seems to have crept in. There is nothing that has changed on my end (other than applying the latest macros), but now I get these errors, probably a couple hundred of them in a NT:
```
(./Texts/41MATMIGMA.SFM [1] [2] [3] [4] [5] [6] [7]
Overfull \hbox (8.52644pt too wide) in paragraph at lines 165--167
\font<m-11.0> k a t t a. G a a b e n e y y i y y e e g a a: «G a a a y m a s e
e n e a ɗ e g o ŋ ŋ a k i t e k i|
[8] [9] [10] [11] [12] [13] [14] [15] [16]

```
This produces:
![image](https://user-images.githubusercontent.com/14953913/89384028-618a3300-d6f5-11ea-8c22-ceadf04ccc0a.png)

Not good... Some sort of side-effect of the recent changes?

FYI, I am using inter-letter spacing, so between each pair of letters I have:
`\XeTeXinterchartoks\allLetters\allLetters{\nobreak\hskip0pt plus .2pt\relax}
`
But this wasn't a problem as of the macros of a couple of days ago.

**Comment by mhosken** [comment]
You can't have it both ways, either you get overfull boxes or really stretchy spaces. Personally I consider it a design bug in TeX.

**Comment by jeffheath-sil** [comment]
I seem to have had it both ways before... With the old macros, I'm able to adjust a paragraph +1, and it spreads it across the spaces throughout the paragraph. And I don't get any of these Overfull \hbox's. Although, please note that these Overfull \hbox's have nothing to do with paragraph adjustments - they do not occur where I am making adjustments.

Anyway, I'm going to need to find a fix for this problem. Any suggestions?

**Comment by jeffheath-sil** [comment]
I removed the interletter spacing, and that had no effect on this problem. So is it more related to the spaces between words, not flowing throughout the paragraph, but somehow stuck on one verse? Although I think the adjustment +1 is now working across all verses of a paragraph.

Is no one else seeing this problem?

**Comment by mhosken** [comment]
duplicate, in effect, of #161
