### ISSUE TITLE
Watermark vs page border

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#164]
I see that the latest 0.9.1 beta has a section for borders (I like the blue highlight when enabled!), and the Page Border option seems to work fine (with the caveat that gutters are still not taken into account #152 ).

But what then is "Apply Watermark PDF" on the Advanced page? It appears that if I apply that, then my page border goes away. And furthermore, even if I use the same border PDF (in both page border and in watermark), the size of the border changes width between the two options. Is it possible that the Watermark PDF takes the gutter into account, but the page border doesn't? If so, then copying that functionality to the page border would be appreciated!

So if you have some way to allow both the watermark and the page border to be active, then that would be fine, but the watermark shouldn't deactivate an active page border (i.e. make it disappear). If you can't allow both, then I suggest you get rid of the watermark option on the Advanced tab, and change the Page Border option to "Page Border / Watermark".

**Comment by markpenny** [comment]
Yes - this should all be working fine in the next update 0.9.3
![image](https://user-images.githubusercontent.com/12962708/89973006-5fa30f80-dcb3-11ea-8fc1-582b88e598bb.png)

And yes the page border now moves according to the page gutter specification as seen here:
![image](https://user-images.githubusercontent.com/12962708/89973075-895c3680-dcb3-11ea-8939-1274c1c74bb2.png)

**Comment by jeffheath-sil** [comment]
I'm afraid this issue needs to be re-opened. With 0.9.3 I can now get both watermark and border, but it gives an extra "media" in the lower left of the page, if I add a watermark:
![image](https://user-images.githubusercontent.com/14953913/90117765-3c2da280-dd4f-11ea-8385-b8f6c1a71238.png)

Also, I don't see the gutter adjustment fix. Here’s what I see that it puts in the .tex file for the border (0.9.3):
\def\PageBorder{"C:/Users/jeff_/Data/Technology/Publishing/Migaama Typesetting/Borders/MIGMA-NT Page Border rough1 w black seeds.pdf" **width 5.25in height 8.25in**}

But here is my Layout:
![image](https://user-images.githubusercontent.com/14953913/90117915-71d28b80-dd4f-11ea-8f41-78fa94d5c1a7.png)

If the page border took into account the gutter, it should be:

width 5.05in height 8.25in
or
width 128mm height 210mm

or something like that. I realize that changing dimensions could be a pain…

The other possibility would be to not put any dimensions in. That’s actually what I do in my typesetting:
\def\PageBorder{"MIGMA-NT Page Border.pdf"}

But I would say that would be a bit risky in PTXPrint, since people will no doubt try borders of inappropriate sizes. Maybe in the next version you should have a checkbox “Force border to page size” (checked by default), which would put in dimensions of page size (minus gutter), but if not checked, it would just put in the PDF file “as is”.

**Comment by jeffheath-sil** [comment]
Extra "media" text on the page with watermark still a problem with V1.0...

**Comment by davidg-sil** [comment]
OK, reopening

**Comment by mhosken** [comment]
try again. Still fixed!

**Comment by markpenny** [comment]
We seem to be going around in circles here. When I build the .exe locally on my machine this all works fine. But the version of the .exe built on the server fails to put in any of the other decorative PDFs (except for the border). Very strange behaviour indeed, and we're trying to track it down...

**Comment by markpenny** [comment]
I believe we have now finally fixed this - it should be working in 1.1.9.2 which has just been uploaded. 
[**Note** that there is a known regression/bug where the config selection box is disabled when you first start PTXprint. By selecting a couple of different projects it comes back to life. Will have that one solved before 1.2 is released.] @jeffheath-sil please confirm that it is working for you too.

**Comment by jeffheath-sil** [comment]
Hurray! I think we’re finally getting somewhere... I can now get the end of book decoration and the verse number decorators. There are still some issues, however. First is that I’m not getting the section head borders, but that is because the .tex file attaches them to \s markers, but in my current project I’m using \s1. Should you maybe \sethook{start} not just for {s}, but also for {s1}, {s2}, etc.? You probably are also going to need a vertical positioning fine-tune for those borders. In the code it is:
`\kern-21pt % adjust value of \kern here to shift graphic up or down`
You probably will need to add a field in the UI, how many "points" (or whatever dimension) you need to add to that -21pt.

Regarding the verse number decorators, I usually prefer to not have the verse numbers superscript when they are in decorators. You can see here that they are currently "superscripted":
![image](https://user-images.githubusercontent.com/14953913/94432992-a1a1eb00-0165-11eb-8664-17e44ef05947.png)
The code currently performs all of that positioning manually:
`\rlap{\raise1pt\box\versenumberbox}\lower4pt\copy\versestarbox`
I don't know if there might be a way to make it more automatic. In the example, the numbers are not vertically aligned within the decoration. But the exact position would also depend on the shape and size of the decoration.

You can also see that the footnote markers are getting the decoration, which shouldn't happen. That might be due to some configuration problem on my end, but it would be good to make sure you aren't getting them on your end.

Good progress!
