### ISSUE TITLE
inter note space - doesn't work anymore

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#165]
Sorry, me again...  The "Inter note space option" doesn't seem to work anymore (in 0.9.1 beta). If I make it big or small, the space between notes stays the same. The "Space Above" and "Line spacing" options seem to work fine.

**Comment by markpenny** [comment]
I'm a little confused as to whether you're referring to the horizontal inter-note-space (which _isn't_ even mentioned in the UI), or whether you are finding that the vertical inter-note-space is having no effect. And we've realised that the old wording doesn't help make that clear. So how does this look to you:
 
![image](https://user-images.githubusercontent.com/12962708/89776227-9109c700-db5d-11ea-919e-151b11929f9f.png)

And note that this setting (now) ONLY applies if the option above is unchecked (so if you are **blending footnotes and cross-references**, then there is only one type of paragraph and therefore [vertical] inter note space is meaningless, and henceforth disabled):
![image](https://user-images.githubusercontent.com/12962708/89776269-a67ef100-db5d-11ea-8b3a-0571717954fb.png)

OTOH, I'm wondering if you are saying that you are applying (horizontal) inter note space outside of the UI, and are finding that it isn't working as advertised...

**Comment by jeffheath-sil** [comment]
I was talking about the Inter Note Space in the interface, i.e. the vertical spacing between footnotes. (I don't have any Cross-References, so I can't comment on those.) So that thing that you renamed "Vertical Spacing Between Notes & Cross-References" is the thing that seemed to have no effect on my output; whether it was 1mm or 10mm, the output looked the same.

**Comment by davidc86** [comment]
Maybe it has no effect for you, because you say you don't have any Cross-references, so then there won't be any vertical space to create between Footnotes and Cross-references for you (whether you check the Blend box or not).

**Comment by jeffheath-sil** [comment]
The effect I saw before was that this defined the space between each pair of two footnotes, not only the space between footnotes and cross-references. That's the way I understand this parameter.

**Comment by mhosken** [comment]
InterNoteSpace is inserted between classes of footnotes, not between footnotes of the same class. Sorry if we gave the wrong impression there. The UI has been changed to say "Vertical spacing between Notes & Cross-references".

**Comment by jeffheath-sil** [comment]
Interesting... I didn't think that was what I was seeing before. But I think that is fine. So basically the Line Spacing would define the spacing that would be between lines of a footnote that has multiple lines, and **also** between separate footnotes. (I.e. all of the footnote line spacing would be identical.) Correct?

Then the other parameter (the one in the middle) defines the space between the footnotes and the cross-references, unless they are blended together. I would recommend calling that parameter "Space Separating Footnote and Cross-reference Blocks".

**Comment by markpenny** [comment]
Yes, that's correct: Font Size and Line spacing apply to BOTH footnotes and x-refs.

Thanks for the helpful feedback on the wording which I've incorporated (and added tooltips too). I've also moved things around slightly to be neater, and (hopefully) more intuitive as well:
![image](https://user-images.githubusercontent.com/12962708/89962686-9bc97680-dc99-11ea-996c-dd14574e6b35.png)
