### ISSUE TITLE
\Regular doesn't allow style afterwards

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#166]
The normal way to change, for example, an \mt2 from italic (its default definition in usfm.sty) to bold is to user \Regular and then follow it by \Bold, like this:

```
\Marker mt2
\Regular
\Bold
```

This doesn't seem to work anymore (with 0.9.1). The \Regular "sticks" and doesn't allow you to apply the bold. If you remove the \Regular, then you can turn the style into bold + italic. But I can't find a way to just make it bold.

**Comment by mhosken** [comment]
This is a debatable question as to whether `\Regular` is sticky or not, but a workaround is:
```
\Italic -
```
Or at least it should be.

**Comment by jeffheath-sil** [comment]
You are right! The formulation:
\Italic -
does indeed work. I should have tried that before, but in an earlier discussion, it was stated that it didn't work in Paratext Print Draft:
https://support.paratext.org/t/print-draft-ignoring-printdraft-mods-sty/2447/4
Obviously you have fixed that in this later version of the macros. I'm grateful, as this syntax is a lot cleaner than using \Regular to turn everything off. Thank you!
