### ISSUE TITLE
Decorative PDF at the end of books doesn't work in 0.9.1

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#168]
Just a bug report that the end of  book decoration feature is not working in 0.9.1 either (it didn't work in 0.9.0 also).

Oddly, the section in the Config file for marking fancy borders and decorations does not seem to keep track of the PDF file(s) selected. I assumed these would be tracked in the Config file, but this information must be kept somewhere else, since PTXprint still knows about the file, it just doesn't list it in the Config file.

**Comment by mhosken** [comment]
Duplicate of #155 which is an enhancement request that is post 1.0

**Comment by markpenny** [comment]
![image](https://user-images.githubusercontent.com/12962708/89971761-3765e180-dcb0-11ea-8d5c-1fcaeaf10a5b.png)

![image](https://user-images.githubusercontent.com/12962708/89971803-4c427500-dcb0-11ea-9c0a-391742439817.png)

Should be working as expected in next update.
