### ISSUE TITLE
Selecting "Exclusively use selected folder" for pictures breaks the Print process (immediately)

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#169]
Well, I found another issue in the Config file. In 0.9.1, if I unselect the "Exclusively use selected folder" option, I can get my "bad" (old v0.8x test) Config file to print. But if I select this option, clicking the Print button immediately fails. (And all picture files are in this "local/figures" folder -- except maybe the "front matter.pdf" file, but that is not "pictures" so I didn't think it would matter.) So, I'm not sure why, but PTXprint doesn't like it when we try to limit it to a particular picture folder.

**Comment by markpenny** [comment]
Thanks for reporting it. Fixed now for 0.9.3
