### ISSUE TITLE
Head+Foot tab has no popup helps on the Header and Footer sections 

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#171]
Just an FYI, but the Head+Foot tab has no popup helps on the Header and Footer sections. The Other section has Helps. I was just wondering what the various bits meant, like "Top margin factor", and couldn't get any information.

**Comment by markpenny** [comment]
Partly because I hardly know what those settings do ;-)

Working on fixing that now...

**Comment by markpenny** [comment]
**Top Margin Factor:**
The primary margin is set on the Layout tab, but
this setting can be used to increase/decrease the 
space at the top of the page and determines
where the main text begins. This setting is a 
factor (without units) and is multiplied by the
Margins value on the Layout tab.

**Header Position:** 
This setting can be used to increase/decrease the 
space at the top of the page and determines the
vertical positioning of the header line. This setting
is a factor (without units) and is multiplied by the
Margins value on the Layout tab.

**Header Drop-downs boxes:**
The header line on each page can contain
the page number, and/or reference(s) in
various forms. Select a preset option, or
type in your own TeX key word with additional
adornments or text as needed. 
For example:
[\pagenumber]   places square brackets around the page number
\rangerefL     places the Left text's reference range in a diglot
\rangerefR    places the Right text's reference range in a diglot
-empty-     places nothing in that location

**Omit Chapter Numbers From Header References**
By default, the chapter number will be included
in any references in the header line. If you prefer
to suppress that (and just show the book name)
then check this option.

**Include Verse numbers in Header References**
By default only the Book and Chapter number
is included in the Header. If you also want to
include the verse numbers, then check this option.

Keep in mind that including the verse numbers
actually makes it harder to read/absorb when
flicking through pages to find the right chapter.

**Bottom Margin Factor:**
The primary margin is set on the Layout tab, but
this setting can be used to increase/decrease the 
space at the bottom of the page and determines
where the main text and footnotes and 
cross-references end. This setting is a 
factor (without units) and is multiplied 
by the Margins value on the Layout tab.

**Center Footer:**
It is not considered best-practice to include 
information in a footer for scripture publications.
This is usually better placed in the header. However,
if there is a need to have the page number at the
footer for all pages (not just the 1st page of each book)
then that can be set here. Similarly, you may want to add
a DRAFT message and/or date to the end of each page.
Note that you can select a preset option OR type your own
text as needed.
Note that if you really must have Inner/Outer Footers,
these can be set in the ptxprint-mods.tex file.
