### ISSUE TITLE
Feature request: Control Font and Attributes of Running Headers and Footers directly in PTXprint

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#172]
Maybe others disagree, but it might be nice for users to have direct control over the look of their Running Headers and Footers in PTXprint for specifying a unique Font or Size or other attribute.  

I realize we can create something like this in the PTXprint-mods.sty:
\Marker h
#\Bold
\FontScale 0.9
\Fontname Calibri Light

But for many, it would simply be more convenient to do it right there in the Head+Foot page, right? (clearly just an "enhancement").

**Comment by davidg-sil** [comment]
I think a style editor is planned. It seems unwise to devote much  coding time to this one aspect
