### ISSUE TITLE
Footnote Font size number popup helps says Line spacing

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#173]
In the Footnote tabs, hovering over label "Footnote Font Size" gives a nice popup for what this is for. BUT if we move the mouse slightly to the right, over the number spinner area, we actually get the "line spacing" blurb, rather than a "font size" blurb. 

I think you only need to change the blurb so "Line spacing" says "Font size" and it says something like adjusts the size of the font (rather than increases the space between lines).

NOTE: the line spacing blurb that shows up on the line spacing number spinners is fine.

**Comment by markpenny** [comment]
Yup - fixed a couple of hours ago. Working on other tooltips now...
