### ISSUE TITLE
PTXprint PicList generator fails to work properly if a \fig field is missing reference content 

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#176]
I've rebuilt the list (using v1, btw, congrats!). And I see an issue: 
If I choose **_not_** to include a Reference in the \fig field, PTXprint has troubles building the PicList file. 
Here is how it fails: 
1) it doesn't create an entry line for that picture in the PicList file, and 
2) it messes up the following \fig by putting part of its alt="..." text into its scr="...." section messing up that picture's file name.

So those are some problems I've sussed out while try to figure out why Acts won't print now. (It has been printing just fine for over a month now.)  PTXprint gives no information, but I can tell it bails on the process right when it is about to put blue in the progress indicator. (Right before it says "Not responding") I'm pretty stumped on this one. It prints just fine with the older PicList format. Weird eh?

**Comment by davidc86** [comment]
Also, I see now where PT9.1 is forcing me to enter a Reference in the Figure dialog. But for some pictures, like maps, which are relevant to several chapters, I'd rather leave the Ref line blank, and put the range in the caption. BUT, that now messes up Paratext, and it messes up your macros. So... how does one enter a reference to keep PT and PTXprint from complaining or messing up, and yet **exclude certain references** from the illustration's caption? (Not all references from all captions, just some of them?)

**Comment by markpenny** [comment]
I'm seeing the bug described in 1. (no entry for figures that don't have a Ref), but I can't yet see 2 happening.

**Comment by davidc86** [comment]
GREAT! Well, I've already added bogus REFs to my 5 map \fig fields. But if you fix that problem, you won't see the other problem. It happened when there were 2 illustrations in one chapter, and the first one was a \fig without a REF specified. This caused PicList generator to not complete the conversion of that \fig spec, and remain "open" while it kept looking for stuff. Then when it hit the second \fig field, it filled in the contents with kind of a mixture of stuff from the first one and also from the second one. So, hopefully, your fix for 1. fixed 2. also. 
If we download again the v1.0 from the SIL site, do we get the latest?

**Comment by markpenny** [comment]
ver 1.1 should be out soon - please wait for that one. It should also solve several other issues - including the signing of the installer.

**Comment by davidc86** [comment]
Okay, so now PTXprint doesn't FAIL if the \fig field lacks a \ref specification, but even if we remove the \ref from the \fig field, PTXprint still includes a (16:5) ref in the caption, when there isn't such a reference anymore in the \fig field. Is this residual? Or is this "by design" -- because I'd rather the program not be so smart, because for some illustrations, I want a ref specified, while for maps etc. I don't.

**Comment by mhosken** [comment]
I hope it's residual. There's nothing in the code that tries to create a ref if one is missing. Please check the piclist in the piclist editor to see if a ref is leaking in.
