### ISSUE TITLE
Version 1 Config file won't launch PTXprint properly

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#177]
The release notes for v1 say Config files now will launch PTXprint.
I just tried it and got this: 

![image](https://user-images.githubusercontent.com/65363206/90303698-1ce16300-de7e-11ea-926c-19836b219bf1.png)

So, something isn't quite right yet.

**Comment by markpenny** [comment]
Hi again David. I've just tried this on another (non-development) machine and it all worked fine. But digging into the issue some more, I have discovered that it is related to the case in the path. 
![image](https://user-images.githubusercontent.com/12962708/90360316-885e4700-e0af-11ea-8b24-897cd747ade9.png)
(i.e. it only works if PTX is capitalized - grrrrr!)
Thanks for uncovering the bug. We'll fix it for the next version.
