### ISSUE TITLE
When PTXprint generates the PicList files it would be nice to chose which ones to redo 

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#178]
Currently, if I click Generate, PTXprint will create a PicList file for each book in the Config file. Thankfully it warns me that all of these files exist already and asks if I want to write over them.
Well, there's the rub. I'd like to create them all when I first start out, but after that, I usually just want to rebuild a single file not the whole set. (i.e. I've messed something up and I want one book PicList file to start from scratch again, but to not mess up anything else I've done.) 

So an "enhancement" would be to allow us to say "this current book" or "all selected books in config file" and PTXprint just rebuilds what we tell it to rebuild. Or PTXprint just rebuilds them all, but then lets us select from a list which ones we want to save over the existing files. Either way would be better than the current way, but this is v1 so hey, we are cool with having to back up and restore stuff. But more trusting people might find the current process a bit frustrating, if they didn't remember to save a backup of their PicList files before  the hit Generate.

**Comment by markpenny** [comment]
There is already a way to ONLY (re)generate the PicList for one book:
![image](https://user-images.githubusercontent.com/12962708/90355315-1af6ea00-e0a0-11ea-9069-b2e153d56daa.png)
The "Generate" button looks at the scope (which books are in focus) and only works on that. So if ONE book is selected, it won't overwrite the other files in that Config setting.
I can update the Tooltip for the button which makes this explicit rather than being "un-intuitive but discoverable".

**Comment by davidc86** [comment]
Well, okay, but what does that mean for a multi-book configuration? 
Say I've already set up a very complicated configuration of all publishable books, and I have saved that configuration to a named configuration. Then what? 
If I uncheck Multiple books, and select a single book, and rebuild the PicList file for that book, it will over write only that book's PicList file in the Named Configuration folder? 

If so, that is nice to know. (I have verified that this is how it works!) 

But apparently the UI did not clue me into that ability. 
Maybe I've just not thought about it much yet, but it seems to me the UI indicates that if I turn off Multiple Books, and go with a Single Book, and I test Print that book (thus saving the current configuration to the named folder), I would LOSE the whole set of Multiple Books I had set up already. But, as you say, and I have confirmed, this isn't the case. PTXprint's Config file will keep track of the Multiple Books list, and still allow me to mess with one book at a time, and then once they are all good, I can turn on the Multiple Books list again, and Print the whole set. This is good to know. 

I don't have a better UI idea to suggest. But just letting you know, the UI told my gut that this was an Either/Or option, rather than a both sort of option, and I had to pick one. So in light of this new understanding, then my thought process is now more like this:
1) Pick the Project
2) Choose ALL valid books in that Project that can be printed at this point.
3) If something doesn't work right, or you don't want to print all books right now, but just want to work on one book (e.g. the one that failed), then UN-check Multiple books, and pick a single book from the list.
4) When all is good, recheck the Multiple books option and Print.

I'm not saying this is how others will look at the logic, but this is how a team that has several books already done will likely look at the logic. 

The UI is fine as is, I just didn't know this was how it worked.

**Comment by markpenny** [comment]
Yes, I like your logic, and is indeed what I often do when things don't work for ALL books. I switch to see if *any* books work and then start to expand the list again until it fails. Then when I know which book is failing, I switch to using just that one to see WHY it might be failing, until I can resolve the issue. (And finally back to all books needed). But, yes, this can happen all within the same Config.

I'll update the tooltip, but also need to add to the FAQs. Someone proposed that we do an overview demo video which takes people through the entire process in a systematic way -- that would also be helpful to many.

Closing this issue now. Thanks for helping us see things from a user's perspective.
