### ISSUE TITLE
Burmese chapter numbers interfere with ascenders in line of text below

### ISSUE THREAD

**Issue by oj-gamache** [sillsdev/ptx2pdf#179]
![image](https://user-images.githubusercontent.com/69705981/90304924-e2f67800-dee2-11ea-840a-92276567b6e2.png)

One solution would be to just use chapter numbers centered in the column, but when I try to use "Handling Special Books" to do that, it forces me to put some word or character before the chapter number which I don't want.

**Comment by mhosken** [comment]
Burmese numbers are a pain. Some have huge descenders and some have huge ascenders. But none have both. What would be ideal would be to have a shift on some digits but not others. But then what do you do about chapter 23 (where the first digit is like the above with a big descender, and the second has a tall ascender)?

What do you want us to do?
- scale the font size back so that descenders don't clash (not hard)
- shift digits by digit, thus making 23 look really odd (trick)
- something else.

**Comment by davidg-sil** [comment]
What about this little bit of USFM/tex ?
```
\cl \ZWNBSP
```
Or find out how to type U+FEFF and putting that as 'text before the chapter number". Either would get you a zero-width non-breaking space before the number. Would that work?

**Comment by oj-gamache** [comment]
Number 6 is the tall one. There is still room above the 6 in 16 as shown below. Would it be possible to just shift all the numerals up a bit?
![image](https://user-images.githubusercontent.com/69705981/90422900-89a86780-e0e1-11ea-94ef-a962fb7291cb.png)

**Comment by oj-gamache** [comment]
Here's 2̂6 in a typeset Bible - it's tight, but it works
![image](https://user-images.githubusercontent.com/69705981/90461418-37d8ff00-e12c-11ea-830a-41f746c49576.png)

**Comment by oj-gamache** [comment]
I don't know what I'm intended to do with: \cl \ZWNBSP
I was able to insert a U+FEFF in Word - and tried copying and pasting from there into "text before the chapter number" but that didn't work

**Comment by mhosken** [comment]
OK I think I have this fixed. It'll come out in v1.1 (not v1.0.x). Here are some quick samples:
![image](https://user-images.githubusercontent.com/5687149/90482373-599eaa00-e15d-11ea-8fb0-690b18774d01.png)
and from the same document: 
![image](https://user-images.githubusercontent.com/5687149/90482437-691df300-e15d-11ea-9683-9f25974e7a9a.png)

**Comment by davidg-sil** [comment]
> I don't know what I'm intended to do with: \cl \ZWNBSP
It was a suggestion of how to have centred numbers. \cl  is for text to precede the chapter number.
I was suggesting that rather than some unwanted text you could 'fool' it into having centred numbers with no text by putting a zero-width character there.

**Comment by oj-gamache** [comment]
I am still interested in the option of centered chapter numbers with no preceding text.

Your suggestions sounds like it might work, I just don't have the technical know-how to implement your suggestion. Am I supposed to type \cl \ZWNBSP somewhere? If so, where?

If you can get it to work in a sample project you have (it doesn't have to be Burmese), and then give me step-by-step instructions of what to do, that would be helpful.

**Comment by markpenny** [comment]
Here are the settings which would give you centered chapter numbers:
![image](https://user-images.githubusercontent.com/12962708/91266759-01ebe880-e7c6-11ea-87dc-ea30155891c0.png)

I hope that helps.

**Comment by oj-gamache** [comment]
Thanks a lot. That works well.
Maybe the \ZWNBSP trick could be added to the info in the black pop-up
help window for "Chapter Label" so that others could benefit from it.

As far as I'm concerned this issue can now be closed in Github.

Thanks,
O.J.
