### ISSUE TITLE
Issue in getting PDF in NT

### ISSUE THREAD

**Issue by prabhujes123** [sillsdev/ptx2pdf#18]
when I select all books of New Testament in the option multiple books to create PDF, instead of getting all books in PDF  I'm getting only Mathew introduction pages(3 pages). same thing happening with  NT Single book also.
But interestingly, when I did the same thing for the books of Old Testament, it worked well with it.
Please find attached screen shots.

![image](https://user-images.githubusercontent.com/56344868/69490214-777aff00-0eaa-11ea-8781-919c9eda76af.png)

![image](https://user-images.githubusercontent.com/56344868/69490232-af824200-0eaa-11ea-8a55-8b01920e5cc3.png)

![image](https://user-images.githubusercontent.com/56344868/69490242-c9238980-0eaa-11ea-9113-7836947c2313.png)

**Comment by mhosken** [comment]
This is the same as issue #13 due to the \+ embedding
