### ISSUE TITLE
Book name doesn't/can't appear in the header when only a single book is printed

### ISSUE THREAD

**Issue by oj-gamache** [sillsdev/ptx2pdf#180]
It would be helpful to be able to at least specify that the book name should appear in the reference in the header. If only chapter numbers are shown with no book name, they look like page numbers. If I have both page numbers and chapter numbers (with no book name) on the page it just gets confusing.

**Comment by mhosken** [comment]
Could it be that you have a missing `\mt` line? I ask because in every other project the book does show up for single book documents. But the macros base the knowledge of the book on the `\mt` line. So if that is missing, they won't show a book name in the heading.

**Comment by oj-gamache** [comment]
After experimenting a bit, I found that it is actually looking for \h 
(this wasn't just an issue with single books, but all books need \h)
