### ISSUE TITLE
A slight difference in PicList crashed PTXlist

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#183]
Here is the relevant line from my Acts PicList that was causing the Print function to do nothing:

This one caused Print to fail:
ACT 10.12 Petrus yatos heal a salno salik rasusinare ti kainke kralake|src="CN01945B.TIF" size="col" pgpos="t" ref="10:12" alt="Peter's vision"

This one allowed Print to run:
ACT 10.12 Petrus yatos heal a salno salik rasusinare ti kainke kralake|src="CN01945B.TIF" size="span" pgpos="t" ref="10:12" alt="Peter's vision"

The only difference in these lines is the "col" vs "span". This is for a Config file that is SINGLE column. So I assumed these "size" specs would act exactly the same way.

As a test, I changed it back to "col", then I reran it, and it worked too! The Print operation was able to produce the PDF even though I had changed the Act PicList file back to exactly how it was moments before. 

This is really weird. I had made sure that the two PTXprint config folders were exactly the same but for the ACTS PicList file, because for one Config file, with the whole set of books, would print just fine; while for the other Config file would print ONLY if I removed ACTS from the list. 

So, since the only difference at that point was the Acts PicList file, I began making exact comparisons of the "good" Acts PicList file with the "bad" one. (The reason I didn't want to just pitch the "bad" one, it because it had better verse references and sizes, which I had manually setup earlier, while the "good" one was generated automatically by PTXprint.) I did find a few typos in my "bad" PicList, but even after these were fixed, it still would not Print. So, I started changing one line at a time making them identical. Then when I changed the above line from "col" to "span" and tried again, it worked! 

But as I said, when, as a test, I changed it back to "col" and tried again, then it worked that way too! 

SO... I'm thinking the REAL problem is not in the PicList file, but in some temp file in some temp folder that is not getting cleared properly. And by tweaking the PicList file just enough, I got something to refresh and it started working. But that is just a guess. (This reminds me of an earlier problem I never solved where the config folder "Alkitab-Selaru-2020-07-14" worked great, but the IDENTICAL folder "Alkitab-Selaru-2020-07-15" wouldn't run at all (and even opened with the wrong content!). Maybe it's related?

**Comment by markpenny** [comment]
I'm still unable to replicate this one. When I change a figure from "col" to "span" and back again (without changing anything else) it behaves predictably (with SINGLE col layout). But this points to the fact that it is still too hard for most people to edit PicLists (without causing something somewhere along the lines to fail). On our to-do list is a friendly GUI-based "PicList editor" which should hopefully make it easier to edit (by picking options) and harder to break.

**Comment by davidc86** [comment]
Yes, it is very hard to edit these files manually. I had several errors in there to begin with (like scr= rather than src=), but even after I got everything right, it still failed to run. But somehow making that final small change caused PTXprint to work. Clearly that small change was NOT the problem, but something happened to cause PTXprint to reload something and flush out the "bad" copy that was jammed up somewhere. 

So the real issue is this: Is there a way to clean out all the left over files in the temp folders and start fresh each time? Because I think there is something about filename length and PTXprint getting confused over it. And something doesn't get replace properly in the temp folders, etc. It just doesn't make any sense to me how changing "col" to "span" or "span" to "col" would change anything. But it did. Or maybe I did something else in the mean time, like exited PTXprint and then later reopened it and tried changing it back. Or something out of the obvious caused something to change for PTXprint -- not in the Configuration folder, because that didn't hardly change -- but something caused PTXprint to start accepting the PicList file, whereas before it didn't. (This is where I suspect a bad typo copy was laying around in the temp folder, so it kept killing the process, even after I fixed the "bad" PicList file. I wonder if I switched to another config file to test it, and then switched back, and that is what cleared a bad file?)

**Comment by markpenny** [comment]
For technical troubleshooters (like us) it is likely that we leave this setting turned on so that we can track and trace what went wrong with a job:
![image](https://user-images.githubusercontent.com/12962708/90573051-8b6d4a80-e209-11ea-8724-7697e61c2dc4.png)

But by default (ie. for most people) this setting should be OFF (otherwise they end up with a cluttered output folder).

Note that **when you turn OFF that switch**, it warns you that it will delete all the temporary files in that (output/PrintDraft) folder. This should also remove the tmpPics and tmpPicList folders.
![image](https://user-images.githubusercontent.com/12962708/90573199-f61e8600-e209-11ea-9ab9-95e78f0ccbde.png)

**Comment by davidc86** [comment]
Works! Thanks.
