### ISSUE TITLE
PTXprint and SIL.org are still flagged as dangerous/unknown

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#184]
PTXprint and SIL.org are still flagged as dangerous/unknown, so Edge first tries to keep me from completing the downloading of the PTXprint file. And then Windows10 tries to stop me from installing it. So all in all it takes about 5 extra clicks to get it to allow me to install it. 

I realize this probably has nothing to do with you guys working on PTXprint, and it might be an SIL.org website issue (not being registered properly?) Or maybe nefarious people are trying to "take down" sil.org so people can't get to our apps, but I hope this can be fixed.

**Comment by markpenny** [comment]
Yes, I acknowledge that this has started recently when it was all working fine before without any warnings. I've contacted the TeamCity buildserver team to help us figure out why it suddenly changed. Watch this space...

**Comment by mhosken** [comment]
This is due a signing certificate just going out of date. Hopefully this will get fixed by LSDev in the next few days.

**Comment by markpenny** [comment]
LSDev have resolved the issue with the certificate and so we hope to have a 1.1 installer released soon which works as it used to.

**Comment by davidc86** [comment]
Unfortunately the certificate was NOT fixed in time for 1.1 installer, and Windows made me jump through a pile of hoops to get it downloaded and installed. They REALLY don't want people downloading uncertified stuff! So, we are still looking forward to seeing this hurdle removed.

**Comment by markpenny** [comment]
Yes, we're aware (again) and waiting on LSDev to get it together (again)... :-)

**Comment by davidc86** [comment]
Fixed! woo-hoo.
