### ISSUE TITLE
RTL Text not right-aligned

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/ptx2pdf#185]
I’m helping a colleague print some PDFs of some individual Psalms. We are not able to get the text right-aligned. for a language that uses Arabic script. I’ve tried a lot of things without success. We were using a border file.

**Comment by mhosken** [comment]
This is due to NestedStyles accidentally forcing all \q styles to \Justification Left. I have added a fix so that for RTL it makes them \Justification Right. To work around, create a ptxprint-mod.sty and for each \q, \q1..\q4 set:
```
\Marker q
\Justification Right
```

**Comment by rmlockwood** [comment]
It's fixed. thanks!
