### ISSUE TITLE
Arabic-Farsi numbers not working

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/ptx2pdf#186]
I've selected Arabic-Farsi numbers, but I'm not getting them in my pdf.

**Comment by mhosken** [comment]
I'm afraid that we don't have a mapping file for Arabic-Farsi digits. If you would like to give us a list of Unicodes for each digit we would be willing to add it. This is also the case for Urdu. So ptxprint is currently lying about those two digit sets. But we would love to stop that happening by supporting them. So any information you can give us for those digit sets would be most welcome.

**Comment by rmlockwood** [comment]
What’s strange is that in the 0.4.9 Beta Arabic-Farsi digits were working fine. The Unicode values are 06F0  to  06F9. Thanks.

**Comment by mhosken** [comment]
More digging. I see that we have Arabic-Indic and Extended-Arabic (well we do now that I have edited the list). Extended-Arabic maps to Eastern Arabic Digits. I think the name is unhelpful, perhaps we should rename that. Any recommendations? Are there any other digit sets for Arabic that aren't merely feature changes to an existing digits block? Currently the list will include "Arabic-Indic" and "Extended-Arabic". But I am open to name changes there given neither of these have been available until now.

**Comment by rmlockwood** [comment]
Regarding the 2nd set, Scripture App Builder calls them Persian, Paratext Arabic-Farsi. I would lean toward calling them Extended-Arabic, to stay with the same name that Unicode has.

**Comment by rmlockwood** [comment]
It's fixed.
