### ISSUE TITLE
Bleed index tabs

### ISSUE THREAD

**Issue by mhosken** [sillsdev/ptx2pdf#187]
This is to start a discussion of how we might want to facilitate the generation of index tabs. For example if on a right hand page one outputs a small black box that bleeds out of the right margin then that will show up as a black line when viewing the pages with the book closed. This can allow users to find their way to a particular book quicker.

There are lots of options on how to do this and we would need to consider which options we want to support and which not:

1. How many tabs per page
2. The textual contents of the tab
3. Even black text on white allows for easier page riffling.

**Comment by markpenny** [comment]
> * How many tabs per page
> * The textual contents of the tab
> * Even black text on white allows for easier page riffling.

Although I've never done this myself (in the usual publishing path of PubAssist with InDesign) I'm aware of several factors that need to be kept in mind:
0. This isn't really a feature that is useful for small volume local printing/photocopying - but is probably more useful for trial print-on-demand NTs (prior to mass publishing)
1. You would need to access to the toc1, toc2 and particularly the *toc3* settings from PT to use the abbreviated-booknames
2. Some of the smaller books (1,2,3JHN for example) often get to use the same position. So working out how many books need to be spread across how many pages is one of the first calculations
3. I would agree that if you're considering OT and NT together that the index tabs would restart for the NT, and possibly even half way through the OT.
I would advise talking to a typesetter who has done these index tabs for several different publications - to work out what all the variables are - and figure out which ones we'd need to expose in the UI.

**Comment by markpenny** [comment]
@philleckrone Do you have any comments on this idea - based on your vast experience of typesetting with InD?

**Comment by philleckrone** [comment]
Mark I have never done these tabs but I know how the process is supposed to
work in InDesign. Basically it yes puts a black edge around the
abbreviations. In some places use these tabs quite frequently
