### ISSUE TITLE
Change default for locating border art

### ISSUE THREAD

**Issue by mhosken** [sillsdev/ptx2pdf#188]
On a side note: Even when the config file has the spec:
**endofbookpdf = ${workingdir}/EndofBookDesign.pdf** 

Whenever I click on the Select button next to that specification, PTXprint **_never_** opens the file picker dialog at the stored location of my previous file, rather it automatically falls back to the embedded (and obscure to normal users) location of: 
**C:\Program Files\PTXprint\ptxprint\PDFassets\border-art\**

Could we please get PTXprint to recognize the {workingdir} path and use it as the default location when we click the Select buttons? (Normal users, on a Windows machine, should _never_ need to look inside a "Program Files" folder.)  
I don't know if this odd inconsistency is related to this current issue, but it is worth throwing out there while this feature is being reviewed.

Personally, I'd like to see PTXprint put its "working resources" in a folder called PTXprint in the My Paratext Projects folder. At least then we are in the same neighborhood. Or when a user selects a Paratext project in PTXprint, you could copy the relevant "**border-art**" folder into that project's "**shared\ptxprint**" folder, so any further tweaks to that project's files (or backups to that project) the relevant files needed to make it work are already bundled together.

_Originally posted by @davidc86 in https://github.com/sillsdev/ptx2pdf/issues/174#issuecomment-677658080_

**Comment by davidc86** [comment]
Yeah, nor in v1.1.9
Weird.

**Comment by mhosken** [comment]
Don't bother adding: not working in <latest version released> until you see a fixed flag go up on this issue. This applies to all issues.

**Comment by markpenny** [comment]
Part of this issue is that the *installer* needs to know where to place these PDF assets when installing, and depending on which version of PT is installed (and where they have placed their "My Paratext x Files") that path will be different. We also have to think about what paths exist for Linux and make sure those users can also find what they are looking for. I'm open to suggestions...
