### ISSUE TITLE
Bad render of chapter number with no break

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#19]
It appears that chapters that start with a no break \nb instead of a paragraph \p are not rendered correctly. So for example this text:
`\c 9 \nb \v 1 Aa suŋun Kalaagu Nuugu kaa kolii teneenu kan barkag n̰un, waŋgu aa tirii: «Wun̰en wun̰eerin lollii kin, barnugu fiŋ suŋii! \v 2 Almaŋ barnun-naanugu kaa dum, ku
`

is rendering like this:

![image](https://user-images.githubusercontent.com/14953913/69556613-50552800-0fa5-11ea-823f-f0efbdf547b8.png)

**Comment by markpenny** [comment]
Yes, we're aware of this one, and have approached JK for a solution. I think it is an issue when using variable line spacing, but works when you're on fixed line-spacing (however, in your screenshot it looks like you're on fixed line spacing anyway). We'll let you know when it has been fixed.

**Comment by markpenny** [comment]
This has now been fixed in the 0.4.0 Beta version available here: [tiny.cc/ptxprint](http://tiny.cc/ptxprint)
