### ISSUE TITLE
PTXprint 1.0 does not open

### ISSUE THREAD

**Issue by eburgi** [sillsdev/ptx2pdf#191]
I was able to install PTXprint 1.0 succussfully but when I want to open it I just see a short command window which closes quickly and no program window is opened. The older version 0.9.3Beta works fine.

I'm using Windows 10.

**Comment by markpenny** [comment]
Sorry for this - we've hit some problems with an expired certificate and 1.0 got rebuilt while PTXprint was in a broken state. I hope to have ver 1.1 up within the next hour.

**Comment by davidc86** [comment]
1.1 opens just fine. (Even with the lack of certification, still.)

**Comment by eburgi** [comment]
Version 1.1 opens fine. Thank you!
