### ISSUE TITLE
PTXprint v 1.1 seems to be ignoring the picture size specs

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#192]
When I run my nicely spec Config files in v1.1, the pictures don't come out the correct size. 

Specifically the tall "fish and whale creation" picture. Normally I specify this a nearly full page (at "span*.85") but it is not showing up in the PDF that way. I've tried changing this to "col" and to "span*.9" etc. and the picture remains the same. No changes at all. Only if I REDUCE the size of the picture to say "span*.5" do I see a reduction in its size. But for some reason, PTXprint is blocking the picture from being spec'd any larger than about 70% (i.e. plain "span" and "col" both yield a 70% size for this picture). Earlier versions of PTXprint would allow me to spec it to 85%. 

Here is what I'm getting now:
![image](https://user-images.githubusercontent.com/65363206/91186019-83efea80-e6bc-11ea-97cb-b745cda1fbb5.png)

I realize that 100% for this kind of vertical picture is too large, but "span*.85" should still be doable, as this still leaves room for the anchored verse text on the bottom of the page. (Yes, I could go with the new "full page" feature, but I'd rather not for that page, and I'm also trying to make sure PTXprint still consistently recreates what I had working before, hence this "issue".)

**Comment by davidg-sil** [comment]
You are exactly correct... Sorry!
To stop full-page images getting too big a limit on vertical size has been set.  It looks like a change I was trying to make  
yesterday got lost (in debugging other stuff and backing out changes, I guess), and you've got the previous version. 

Current code (in ptx-figure.tex):
```
\p@cheight=0.7\textheight % there should be text on the page too!
```

Revised code:
```
 \p@cheight=\textheight
 \advance\p@cheight by -4\baselineskip % there should be text on the page too - allow for caption+space+2 lines of text!
```

**Comment by davidc86** [comment]
Okay, great, so I'm not going crazy! 
I guess this fix will come in v1.2?

**Comment by davidg-sil** [comment]
No promises on when v1.2 will happen, but yes.
If you're feeling brave you could find ptx-figure.tex and then that line, and change the 0.7 to something bigger.

**Comment by davidc86** [comment]
I would if I was trying to produce a finished product at this point. But what I'm trying to do is develop a configuration file that is formatted great for the needs in our area. Then whenever we need to produce a copy, PTXprint will consistently yield reliable results with minimal end-user effort. It is close now. Just a few recent tweak break my config files here and there, so I've yet to get back to the great results I had at around v0.8.8. This is all part of the development process.
