### ISSUE TITLE
New footnote error in 1.1 (\fq and \ft relative to «»)

### ISSUE THREAD

**Issue by viverechristus** [sillsdev/ptx2pdf#193]
I'm getting a new error in 1.1 in a footnote - the output to PDF doesn't reach completion. Here's the relevant bit from the Log:

```
! Use of \n@xt@ doesn't match its definition.
<recently read> »
                 
l.43 ...េស៊ូ» ពអ្នះ ឋង់ ឡៃគ ហា តុ «\fq បារ៉ាបះ\ft»
                                                   ឌើច។ «បារ៉ាបះ» អ្យឹ ភូង «...
``` 

The portion of the footnote is here:

``` 
\fr 27:16 \ft ហ្លា ហ្រៈ \+pn ម៉ាធឿ\+pn* មឹង ឌីម អា ជិះ មឹង ង៉ាន ពអ្នះ ឡៃគ «\+pn បារ៉ាបះ យេស៊ូ\+pn*», ពអ្នះ ឋង់ ឡៃគ ហា តុ «\fq \+pn បារ៉ាបះ\+pn*\ft » ឌើច។
``` 

The engine seems to stall out either at `«\fq` or `\ft »`

The only other place in Matthew where we also have `«\fq [...]\ft »` also stalls the engine:

```
! Use of \n@xt@ doesn't match its definition.
<recently read> »
                 
l.28 ... យេស៊ូ អ្យវ មត ហ្យិន តុយ «\fq យ៉ង់ ឍើយ\ft»
                                                   ញូ។ អានម៍ \xt រ៉ូម 8:29; ...
```

**Comment by viverechristus** [comment]
I can confirm that removing « and » resolves the problem. However, these never caused a problem before.

**Comment by markpenny** [comment]
@viverechristus Sorry about that. We had a "hack" RegEx rule in the code earlier to make this work for your project, but decided to take it out just over a week ago (in case it caused problems to several other users).
![image](https://user-images.githubusercontent.com/12962708/91264372-b5ec7400-e7c4-11ea-9ea9-dd6e3a68742e.png)
For the moment, your workaround would be to add a RegEx rule to your PrintDraftChanges.txt file which looks like this:
`"\\ft»" > "\\ft »"` 
That should have the same effect.

**Comment by viverechristus** [comment]
Done, and working.

Is this an illegal sequence?

**Comment by markpenny** [comment]
> Is this an illegal sequence?

I am working on the assumption that every marker needs to be terminated (i.e. followed) by a space -- of course with the exception of closing markers which close with an *

**Comment by viverechristus** [comment]
What's a mystery to me is why » is different.

The following sequence produces no problems:

`\fq good \ft bye`

The space before "bye" is of course deleted in typesetting so that only the space after "good" remains. Why is the following sequence treated differently?

`\fq good\ft »`
