### ISSUE TITLE
Matthew (MAT) not showing up in list of available books for project

### ISSUE THREAD

**Issue by viverechristus** [sillsdev/ptx2pdf#194]
We have a secondary project (a manual transliteration), which has 4 books: RUT, JON, MAT, JAS. When I select the project (JraLM) and then click on the book selection list, only RUT, JON, and JAS are listed. So:

![Jarai-LM - NO MAT](https://user-images.githubusercontent.com/915182/91270415-c8ee4c80-e7a2-11ea-8a03-f9681dcc1454.jpg)

However, if it type "MAT," then 28 chapters show up and I can Print. (The Printing doesn't work, but I'll report that separately, since I can't see how it's related.)

I deleted the book MAT and recreated it, opening and closing both PTXprint and PT in different sequences, but nothing makes MAT show up in the selection list.

**Comment by markpenny** [comment]
Wow! Yes - I can replicate the BUG. Thanks for reporting it. Working on solving it now...
![image](https://user-images.githubusercontent.com/12962708/91361779-23dc7e00-e84d-11ea-941e-813eb9017f3c.png)

**Comment by markpenny** [comment]
What is surprising is that the bug has been in there for a while, and no one else noticed it. Fixed now for the next version.
![image](https://user-images.githubusercontent.com/12962708/91363145-1379d280-e850-11ea-8c93-a71758e53780.png)
