### ISSUE TITLE
Font error with Manual Transcription project

### ISSUE THREAD

**Issue by viverechristus** [sillsdev/ptx2pdf#195]
In our manual transcription project, I can print RUT no trouble (main font set to Times New Roman). However, when I try to print MAT (or a single chapter of MAT), I get the following error:

![image](https://user-images.githubusercontent.com/915182/91271991-40bd7680-e7a5-11ea-9d04-82731a4ae374.png)

Here it is from the log:

```
! Font \font<h-12>=12 at 132.04907pt not loadable: Metric (TFM) file or install
ed font not found.
<to be read again> 
                   \font<h-12> 
<inserted text> \hbox to \textwidth {\s@tfont {h}
                                                 \ifm@rksonpage \trace {H}{m...

\makeheadline ...ox to \textwidth {\the \headline 
                                                  }} \ht 0=0.7\fontdimen 6\c...
<argument> \vbox {\makeheadline 
                                \pagebody \makefootline }
\shipwithcr@pmarks ...\XeTeXupwardsmode =\oldup #1
                                                  \if \g@tterside R\kern \Bi...

\plainoutput ...eadline \pagebody \makefootline }}
                                                  \pdfpagewidth =\dimen 9 \p...
...
l.258 \end
```

All the settings are identical as the were for the successful printing of RUT.

This may be connected to issue #194 but I can't see how.

**Comment by mhosken** [comment]
Questions questions questions:
1. Does the document have a \h line?
2. Is there a font set for the project
3. Is \h redefined in any way in the .sty files?

**Comment by viverechristus** [comment]
Well, you answered my questions already! :) 

The only .sty reference to \h is in the usfm.sty file, and it is just as it should be (and doesn't cause trouble for any other book in this project, or for any other project). I can confirm that the custom.sty file for JarLM (the only extra stylesheet called in PTXprint for JarLM) does not (re)define \h in any way. Here's the relevant code from usfm.sty, for what it's worth:

```
\Marker h
\Name h - File - Header
\Description Running header text for a book (basic)
\OccursUnder id
\Rank 1
\TextType Other
\TextProperties paragraph publishable vernacular
\StyleType Paragraph
\FontSize 12
```

Yes, the file does contain an \h line, right near the top:

```
\id MAT - Jarai Cambodia Latin Script Manual Transliteration
\h Mathiơ 
\toc3 Mat 
\toc2 Mathiơ 
\toc1 Klơi Phr̂âo Hiam tui tam mathiơ čih 
\mt2 Klơi Phr̂âo Hiam Tui Tam 
\mt1 Mathiơ 
\mt2 Čih 
```
But so does RUT!

I deleted the \h line (is there a way to comment out lines of USFM in project text?), and I get a new error:

![image](https://user-images.githubusercontent.com/915182/91380619-93ec0380-e84f-11ea-9398-c5c02f150899.png)

Here's some context from the log:

```
(c:/My Paratext 8 Projects/JraLM/PrintDraft/ptxprint-Jarai-Roman-MATJraLM.picpa
ges) (./41MATJraLM-draft.SFM [1
\openout2 = `ptxprint-Jarai-Roman-MATJraLM.notepages'.

\openout3 = `ptxprint-Jarai-Roman-MATJraLM.picpages'.

]
Runaway argument?
=\end@llcharstyle \mcdown \beginL \pdfsavepos \write \p@rlocs {\noexpand \ETC.
! Paragraph ended before \d@ was complete.
<to be read again> 
                   \par 
\p@rstyle ...pos }{\the \pdflastypos }}\endL \par 
                                                  \ifdim \prevdepth >0pt\las...

\ch@pter ->2\s 
               Môt
\ch@ckadjustments ...otL L\else R\fi \fi \ch@pter 
                                                  .\v@rse }\ifx \c@rref \pr@...
<everypar> \the \@veryparhooks 
                               \beginL \pdfsavepos \write \p@rlocs {\noexpan...
<to be read again> 
                   \unhbox 
...
l.54 \c 2\s Môt lơgơi r̂ai mơ̆ng ping gah ngŏ\p \v
                                                   1 Dơdơi mơ̆ng a pơpôn \nd...
```

I get the feeling the app just doesn't want to typeset MAT! I can't find any problem with the USFM at the new stumbling point:

`\c 2\s Môt lơgơi r̂ai mơ̆ng ping gah ngŏ\p \v 1 Dơdơi mơ̆ng a pơpôn \nd Yêsu\nd* mơ̆ng`

By the way, I sent a zip file to the support email address earlier this morning, so that might have what you need to look at.

**Comment by mhosken** [comment]
This looks to be a completely different bug to that reported for RUT. And no you shouldn't remove the \h. The point I was checking that RUT needs a \h line.

**Comment by mhosken** [comment]
I see your bug. There is no space after 2 in \c 2\s. Now whether we should spot that is a different question.

**Comment by viverechristus** [comment]
Shouldn't Paratext see to that? 

In the meantime, should I use RegEx to fix all similar instances and rerun?

**Comment by viverechristus** [comment]
Indeed, note that in Standard View (in Paratext 9) a space is showing up:

![image](https://user-images.githubusercontent.com/915182/91384124-0bbe2c00-e858-11ea-9910-f93277a1c893.png)

But if I switch to Unformated View, it's gone:

![image](https://user-images.githubusercontent.com/915182/91384164-1b3d7500-e858-11ea-9cdf-09a64b23233e.png)

(I know this isn't a Paratext forum. If you think this needs to be reported over there, I'm happy to do that, too.)

**Comment by viverechristus** [comment]
Whatever the case, I used RegEx Pal to add a space before \s after a chapter number, and MAT now outputs as a monoglot, no problem. Thanks!

**Comment by mhosken** [comment]
Your MAT is all one line! No wonder it falls over anywhere and everywhere! And that would mask the \h since the \id line is expected to be on a single line on its own rather than scanning for \ markers on that line.

**Comment by mhosken** [comment]
Probably the easiest way to fix this is to export to USX and reimport from that USX file

**Comment by viverechristus** [comment]
Thanks for the easy fix.

FYI, it was all on one line because my transliteration process is:

1. copy unformated text from PT to Notepad++
2. save a .txt copy in Notepad++
3. open in BBEdit on Mac (hard returns disappear at this step)
4. use AppleScript to run a find-replace routine
5. save a new .txt file in BBEdit
6. reopen in Notepad++
7. copy-paste back into PT

Now that I know about Export to UTX, I can skip Notepad++ and all the copy-pasting into and out of PT. I may still have the problem with carriage returns, though.

**Comment by markpenny** [comment]
wow! That is quite a process. Are you aware that Paratext can
      automatically run transliterations for you (natively) using the
      SIL Converters mechanism (which in turn can call all kinds of
      converters). If you get set that up, you wouldn't need to do steps
      1 through 7 :-)
    Depending on how complex your find-replace operations are, you
      could use something as simple as CC or more likely, a TECkit
      mapping.
    Hope that helps - let me know if you need more details.  -Mark
    
    On 27/08/2020 4:52 pm, viverechristus
      wrote:
    
    
      
      Thanks for the easy fix.
      FYI, it was all on one line because my transliteration process
        is:
      
        copy unformated text from PT to Notepad++
        save a .txt copy in Notepad++
        open in BBEdit on Mac (hard returns disappear at this step)
        use AppleScript to run a find-replace routine
        save a new .txt file in BBEdit
        reopen in Notepad++
        copy-paste back into PT
      
      Now that I know about Export to UTX, I can skip Notepad++ and
        all the copy-pasting into and out of PT. I may still have the
        problem with carriage returns, though.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/sillsdev/ptx2pdf/issues/195#issuecomment-681450116",
"url": "https://github.com/sillsdev/ptx2pdf/issues/195#issuecomment-681450116",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    -- 
ɦuuəd ʞɹɐw ● Language Technology Senior Consultant ● South Asia Group ● SIL International  ● Based in NZ

**Comment by viverechristus** [comment]
Thanks, Mark, for the suggestion. But you've just made my process much
simpler simply with Export to USX!

I created a batch find-replace routine before I knew about the converters,
and it's been easier to modify that routine than to start from scratch.
However, I will say that I've looked at the setup for the SIL converters a
couple times with an SIL colleague, and though it's probably possible, I
couldn't see right off how it could be done, in part because my routine is
sensitive to USFM markup, which ensures that words contained in \nd, \pn,
and \png get capitalized -- I think the converters ignore markup, which is
a nice feature, but means I would have to keep a list of every proper name
that needs capitalizing.

The Khmer script to Roman conversion is also incredibly complicated because
the "series" of the first consonant of the word (or of the main syllable)
determines the value of the vowel (each vowel symbol has two sounds,
written differently in the Roman script), and because consonant
symbols with no vowel symbol are assigned either a "reduced" pronunciation
(if appearing in a "pre-syllable") or a "full pronunciation" (if appearing
in the main syllable), and that full pronunciation in turn depends on the
consonant's series (and often an intervening consonant of a different
series does not have an effect on the vowel!). So the conversion has to
distinguish five types of consonants that are written without a vowel:
final consonants (which are truly vowel-less), main syllable first-series
consonants (which have an inherent "o"), main syllable second series
consonants (which have an inherent "ô"), the first consonant in a main
syllable cluster (which determines the value of the vowel later on, but
which itself has no vowel), and a presyllable consonant (which has an
inherent schwa). As far as I can tell, the conversion has to evaluate a
word in multiple passes and apply changes in a specified order, the output
of each pass providing the input to the next pass. I don't think a CC table
or TECkit can do this. (If you're curious, I can provide details and some
minimal examples demonstrating my point, but it's probably beside the point
for PTXprint!)

**Comment by mhosken** [comment]
No but you can use python for converters and have Paratext call those IIRC. I think you pass SILConverters a python file and a function to call within it that is passed the input text and you return the output text. There is no limit to your power then :)

**Comment by markpenny** [comment]
But I do think PT only passes chunks of text to the converter - which means you can't check for markers to do different things. But yes, there are still plenty of ways around the manual process. (Way before SIL Converters was even possible within PT, I used to run a .BAT file which did the transliteration "behind the back of PT". It still works well in case you want to explore that approach one day).

**Comment by viverechristus** [comment]
Mark, could you send me a sample .BAT file off-list?

**Comment by davidg-sil** [comment]
Am I correct in thinking that Mark's .BAT file will work fine **but only** as long as PT is not running? At least, I've always assumed that 'your important changes may be lost' as they say, if a relevant chapter is open in PT while the other processing is happening.

**Comment by markpenny** [comment]
No, because we are only updating the transliterated project files, it doesn't matter if Paratext is still open/running. All the files (for the entire project) get regenerated within a matter of seconds (but Paratext doesn't know that this happened "behind its back"). When you switch to the next chapter, it refreshes and reads in the new changes. @viverechristus I'll send an e-mail offline with the .bat script. @davidg-sil At one point I also had a .sh script to do the same in Ubuntu, but I haven't used it for a while.
