### ISSUE TITLE
File/folder selection window extends below bottom of screen

### ISSUE THREAD

**Issue by viverechristus** [sillsdev/ptx2pdf#199]
If I click on, say, "Select Folder" on the Pictures tab, the folder/file selection window is consistently too big, hiding the "Cancel" and "Select" buttons at the bottom right. This behavior is independent of whether the selection window has a full list or just a handfull of items.

![image](https://user-images.githubusercontent.com/915182/91513716-34552d00-e90f-11ea-9c8f-3cbd68565489.png)

I've noticed this behavior before but just assumed that there were no buttons to push! Today I thought to drag the window up, and I saw the buttons peeking out at me from the bottom. But Windows 10 doesn't allow the Title Bar to be hidden, so the window slips back into position after I release the mouse. My current workaround is to hold down the Start key and press the right or left cursor arrow, which resizes the window to fill the screen vertically (without extending beyond the visible area) and take up half the horizontal space.

**Comment by davidc86** [comment]
Hmm. I just tested this behavior on my laptop and am not seeing it. On my computer the Select Folder dialog opens up normal sized. Mine opens nearly the same size as the PTXprint window: 

![image](https://user-images.githubusercontent.com/65363206/91563422-d0ca0000-e90c-11ea-822b-fcddd3e3d3a5.png)

(Windows 10 v2004; PTXprint v1.1; 4K screen set at 200%) Just adding this so the developers have another data point.

**Comment by viverechristus** [comment]
OS Name	Microsoft Windows 10 Home Single Language
Version	10.0.18362 Build 18362
System Name	ASUSS510UA
System Model	X510UA

Display:
Name	Intel(R) HD Graphics 620
Resolution	1920 x 1080 x 60 hertz

![image](https://user-images.githubusercontent.com/915182/91632034-49fa4d80-ea08-11ea-8841-a469bae91afc.png)

**Comment by markpenny** [comment]
Yes, seems strange to me too. I wasn't able to replicate it either. But when I resized the window, the next time it opened up at the (new) resized size. Let me know if you're still struggling with it and I'll see if we can assign a smaller default size to begin with.

**Comment by viverechristus** [comment]
Yeah, the problem reappears every time I open a file/folder dialog, even if I already resized the window in the same session with PTXprint. I can solve it myself easily (as described above), so if no one else has the problem, it's not a big deal to me.

**Comment by mhosken** [comment]
Closing for lack of actionable information (through no fault of anyone).
