### ISSUE TITLE
AttributeError: 'TTFont' object has no attribute 'featvals'

### ISSUE THREAD

**Issue by dhigby** [sillsdev/ptx2pdf#2]
I am guessing this is because the Paratext project has alternate glyphs selected.  Like the literacy a and  g, or the eng and enya alternates.

**Comment by markpenny** [comment]
I'll let MH comment on this. In our testing, any font features that were turned on in Paratext also got implemented in PTXprint; so it is definitely supposed to work.

**Comment by mnjames** [comment]
I can confirm seeing this same error a number of time. The project uses an unsual font (Awami Nastaliq), but not any font features.

**Comment by dhigby** [comment]
Mine is just using plain Charis SIL.  In fact I've got this error on all the projects I tried.

**Comment by markpenny** [comment]
This has now been fixed. It will be working for you in v0.2.3 which will get into the Google Drive soon (by the end of today).
