### ISSUE TITLE
Inserted \catcode command (with numbers) causes failure

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#20]
I have a project which fails in PTXPrint like this:
```
(c:/My Paratext 8 Projects/CABRS/PrintDraft/08RUTCABRS-draft.SFM
! Missing number, treated as zero.
<to be read again>
                   1
l.14 \catcode`{=1
                 1┬á\catcode`}=11
No pages of output.
Transcript written on ptxprint-RUTCABRS.log.
```

If I look at the source SFM file, I see that PTXPrint has added a couple of lines to the original SFM file between the \imte2 and \c 1 lines:
```
\imte1 Kitaab Raʼuus
\imte2 min Kutub Taariikh Bani Israaʼiil
\catcode`{=11 \catcode`}=11

\makedigitsletters

\c 1
```

The \catcode and \makedigitsletters commands are not in the original SFM, so they must have been added by PTXPrint. But the \catcode commands have numbers in them, which is a no-no in SFM source files.

So why were the \catcode commands inserted? (I forget what \catcode 11 is...)

**Comment by markpenny** [comment]
Jeff, the catcodes are inserted to wrap the Introductory Outline up to render it as a Table (with right aligned \ior and leading dots). It is a neat, but very fragile feature and depends on several things being "just right" to work properly (see the tooltip for details), otherwise it fails miserably. If you turn off the feature called "Right-align \ior with tabbed leaders" on the Body tab, then these do not get inserted. Try that and let me know if it works. 
BTW - what are the \imte1 and \imte2 codes for?

**Comment by mnjames** [comment]
I've also run across this error. Turning off "Right-align \ior with tabbed leaders" did fix the problem.

I would recommend making the default on that checkbox un-checked, at least until the underlying problems are fixed.

**Comment by markpenny** [comment]
Yes - we discovered yesterday that although it was turned off by default it was being turned back on (behind your back!) due to something strange happening with the settings. I hope it is fixed now (will be available in ver 0.2.5), and let me know if it is still a problem.

**Comment by davidg-sil** [comment]
It looks to me like the inserted code is assuming that digits are numbers, when their catcodes treat them as letters by the time of a USFM file.  I can't remember what the opposite of \makedigitsletters is, but that needs to go before you do that catcode stuff. I'm a bit scared about what you're doing with { } though.... That's going to break other stuff, I expect.

**Comment by markpenny** [comment]
Yes, this feature continues to haunt me, and I wonder about pulling the plug on it, or making it more robust. I had another couple of projects fail because the digits weren't roman/latin 0-9 but were in another script. So we obviously have to do something about this flimsy bit of code.

**Comment by markpenny** [comment]
Closing this issue now. If a user tries to turn on the Option to allow Fancy Into Outlines, PTXprint first attempts to ensure that all the selected files comply to the markup requirements (including normal 0-9 digits and not some other script).
