### ISSUE TITLE
last two lines of Matthew printed in left column

### ISSUE THREAD

**Issue by viverechristus** [sillsdev/ptx2pdf#200]
In today's output of (monoglot) Matthew, I got the following. The two lines at the bottom of the left column are the end of verse 20 and they belong in the right column! This is from the last page of the (full) book of Matthew.

![image](https://user-images.githubusercontent.com/915182/91632180-58953480-ea09-11ea-8741-6ca4dfd3a80f.png)

There's nothing odd about the configuration, and I haven't added anything new to the stylesheets, that I can recall. If you need more details about the configuration, let me know.

**Comment by markpenny** [comment]
@viverechristus Congratulations on submitting the 200th issue :-)
Could you repeat the problem above and then send a .ZIP archive containing the settings (to the ptxprint support e-mail ID). That will help us identify what happened and fix the bug. We've seen this one occur before and thought we had squashed it, but it is back :-(

**Comment by viverechristus** [comment]
I've sent the email. 

I resolved the problem (temporarily) by using the Adjust list. For the second-to-last paragraph, I set it at `MAT 28.11 +1`. This made that paragraph an extra line long, and that made the problem disappear. (But it made for an odd looking two columns, the right one being so long.)

![image](https://user-images.githubusercontent.com/915182/91719957-680aae00-ebc0-11ea-8de1-d9c9a637c054.png)

(I admit I was pleased to submit issue #200, but I promise that I haven't been submitting issues with that in mind! I've been getting ready for a Committee Check, and we needed printouts of Matthew for that. We had the final Matthew check today, and now we'll start moving towards distributing Matthew, our first NT book.)

**Comment by markpenny** [comment]
> We had the final Matthew check today, and now we'll start moving towards distributing Matthew, our first NT book.

Well then, congratulations are definitely in order! :-)

We'll see if we can prevent the bug in future. Thanks for sending the .ZIP file.

**Comment by mhosken** [comment]
Could you undo your fix and make it fail again. Then do the following:
- Turn on 'Peserve Intermediate files and logs' in the View+Edit tab and if necessary re print to generate the files
- In the advanced tab tun on "Archive temporary files for debugging"
- In the advanced tab, press the "Create ZIP archive" button and send the resulting file to one of us.

**Comment by viverechristus** [comment]
I'm afraid too much has changed since Sept 1 (picture resizing, some actual changes in the text itself, etc) -- I don't see how I could reproduce the original problem. And I'm afraid I don't know now to use to the package I generated at the time.

However, at present, I don't appear to be able to create any sort of output at all. Guess I need to report that separately.

**Comment by mhosken** [comment]
OK. Let's start a new issue if we find this happens again and close for now. Thanks.
