### ISSUE TITLE
Diglot print does nothing

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/ptx2pdf#202]
When I try any two project for doing a Diglot, nothing happens when I press the Print button.

**Comment by davidc86** [comment]
I've noticed this "nothing happens" behavior for various reasons (not necessarily related to Diglot). For me, I found that it relates to messed up PicList settings (i.e. something in the files is causing PTXprint to fail early in the export process). For me, I never see the blue progress indicator, PTXprint just bombs back to letting you tweak stuff (it is no longer trying to export anything). It would be VERY helpful if PTXprintn would give some sort of notification that the export bombed, like "Sorry, but for some reason that didn't work. Check that your PicList specifications are valid." (or some such).  

Sorry I don't have an answer. But it might NOT be related to Diglot, but rather you might be asking pictures to behave in a way Diglot can't handle well.

**Comment by rmlockwood** [comment]
I’m getting it now to work for some books, but of course, not for the book I want to print. It does nothing. I don’t have any pictures so no piclist. How can I tell what went wrong?

**Comment by mhosken** [comment]
I have sometimes been fooled by having diglot set and yet not having a secondary project. That can fool ptxprint. Please check that you have diglot disabled. I am reluctant to have all user issues involve sending us an archive of your project. But if you are still stuck, please send an archive to me (Martin) via email.

**Comment by mhosken** [comment]
The core bug exposed here is that usfmerge wasn't handling verse and chapter numbers not including only digits.
