### ISSUE TITLE
Linux version number of PTX Print is still showing [0.8.6 beta]

### ISSUE THREAD

**Issue by KimB2017** [sillsdev/ptx2pdf#208]
I have been updating ptxprint via the repos, and the package name includes "1.1", but the version number in the gui is still at  [0.8.6 beta]!

**Comment by markpenny** [comment]
Hi Kim, Yes, this certainly seems strange. Where exactly are you seeing 0.8.6 in the UI? Is it in the main application window, or some other place? You should be seeing 1.1.8 by now, so anything less than that means that something hasn't updated correctly - which could well be a reason that other anomalies are showing up.

**Comment by mhosken** [comment]
This is a side symptom of the #211 and not running the expected version of ptxprint.
