### ISSUE TITLE
Difficulty regenerating "final SFM" after editing the text in PT.

### ISSUE THREAD

**Issue by KimB2017** [sillsdev/ptx2pdf#209]
Using today's repo version of ptxprint in Wasta 18.04. 
Steps:
1. Edit a verse in PT, with ptxprint open.
2. Save All in PT.
3. Return to ptxprint. In the Viewer>Final SFM tab the Regenerate and Refresh buttons are greyed out. There is no way to update the SFM text to the edited version.
4. Click Print. The newly generated PDF contains the edit, but the Viewer>Final SFM tab still shows the old version.
5. Close and reopen ptxprint. The new version SFM text is now showing.

Another scenario:
1b. Edit a verse in PT, with ptxprint open.
2b. Save All in PT.
3b. Return to ptxprint. There is no way to update the SFM text to the edited version, so close ptxprint in hopes that the new SFM will be generated on reopening.
4b. The SFM text is still the old version.
5b. Clicking Print produces a new-version PDF but the SFM in Viewer does not update until you close and reopen ptxprint again.
 
This is confusing and could cause some people to give up on ptxprint. (It cost me an hour or so of fiddling to figure out what was going wrong.) It seems good that you can't Edit the SFM in ptxprint, but it would certainly be much easier if Regenerate were available for use after editing the project in Paratext.

**Comment by markpenny** [comment]
fixed in 1.1.8 or later
