### ISSUE TITLE
Request: Make it possible to change units globally (mm,in,pt,em)

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#21]
Non-urgent feature request: Allow the user to choose their preferred unit of measurement.

**Comment by davidg-sil** [comment]
Urm... you mean rather than in completely flexible \fontsizeunits?

**Comment by davidg-sil** [comment]
With the use of  sizes < 2\fontsizeunits to scaling, my above comment is less accurate...

**Comment by mhosken** [comment]
Some thoughts on what a dimensioned spinner might look like. The middle one is not dimensioned
![image](https://user-images.githubusercontent.com/5687149/92201611-36873080-eea7-11ea-8ff9-3d0543221d48.png)

The first one takes the same space as a normal spinner but it is lots of work.

**Comment by mhosken** [comment]
While this could be done, it is a large amount of work for very little benefit. Having documented the units for every value, the need for users to be able to change the dimensions is low.
