### ISSUE TITLE
The Default Thumb Tabs settings are too large for the margins settings

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#213]
I'm not sure if you want to automatically setup reasonable size setting for the Thumb Tabs when a user says the want to give these a go. But it seems a fairly simple arithmetic could look at the current page size, current margin sizes, etc. and determine the MAXIMUM size a Thumb Tab could be with those settings so as not to have the thumb tab over write the text. 

I just went with the default Thumb Tabs just to check them out, and I got this: 

![image](https://user-images.githubusercontent.com/65363206/94325667-8e2c2f80-ff6d-11ea-9d19-39d0c6309dd2.png)

So, to help new users, it might be best to set the dimensions up a bit closer to "safe" and if the user pushes the width of the tab into the text, PTXprint might want to give them a warning?

**Comment by mhosken** [comment]
Adjusted the default length (13mm) to be slightly less than the default margin (14mm). We don't calculate a default here, it is set statically at this point. If someone reduces their margins before selecting tabs, they can get the above situation.

**Comment by davidg-sil** [comment]
You now know why the initial version of the code only included rotated tabs...
