### ISSUE TITLE
Suggested Thumbs Tab option: Allow OT and NT to be in different colors

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#214]
I thought we were going to only have BLACK as the option, but since you allow colors, then it would be nice to have the option to assign OT one color and NT another color. (And I've seen Bibles where the Extra Materials in the back are marked with yet another color.) Just for your consideration.

Very cool that you are making this kind of elegance available.

**Comment by markpenny** [comment]
Nice idea. We'll have a think about how best to do this once all the other show-stoppers have been fixed. We also need to get working on the Stylesheet editor, which would be a higher priority.

**Comment by davidg-sil** [comment]
This  is sort of possible, manually,  now,  via the ```\setthumbtabBg{}{}``` command (see documentation).
The code at present has no knowledge of what's OT and what's NT, and my thought is that, in any case, someone might want a colour scheme of Pentatuch / Wisdom / Psalms / Major prophets / Minor prophets / gospels / letters. etc  Or each of the gospels / John's letters having slightly different shades.... There are so many options.

Perhaps a better option would be to allow book IDs to be assigned to 'tag-colour groups'? and then the groups have an attribute? 
I guess the mechanism would be 'default colour'  unless 'group colour' unless 'individual colour'.

**Comment by davidg-sil** [comment]
Whether anyone will actually find the budget to print every page in full-colour is yet another issue, of course.

**Comment by davidg-sil** [comment]
Brave people may now test this with their favourite multi-book volume (see relevant doc change for interface).

**Comment by markpenny** [comment]
So, in summary, the TeX macros can now do this, but we haven't yet updated the PTXprint User Interface to allow people to do this easily. It seems to be low priority at this stage. If you need coloured groups in a hurry, then look at the documentation contained [here](https://github.com/sillsdev/ptx2pdf/blob/08609ddca7a3a1bd9a85fe3f85cafc1c19a1084d/docs/documentation/thumbtabs.md#grouped-tab-settings) and pop the relevant lines into your ptxprint-mods.tex file.
