### ISSUE TITLE
The LINE under the Header text is too close to the Header

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#216]
The dividing line under the Running Header and Page Number and Reference is way too close to the running header text: 

![image](https://user-images.githubusercontent.com/65363206/94327314-2d562480-ff78-11ea-8c57-9ba3a24ad05a.png)

Adjusting the two Header values on the Header & Footer page, did not have any effect on the position of the underlining. I would like to control how far away it is positioned from the header text, so the descenders to not cross it.

Anybody know how to spec the gapping between the header text and the header divider?

**Comment by mhosken** [comment]
On the Layout tab there is the Horizontal Rule vertical offset. Increasing this will move the line down in relation to the header line.
