### ISSUE TITLE
The terms "length" and "height" are confusing on Thumb Tabs page when bookname is set to vertical

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#217]
If the book name is set to vertical, the terms "length" and "height" for the Thumb Tabs is confusing, because the user isn't sure PTXprint will keep "length" referring to how much space it covers "in the same direction as the book name abbreviation" or whether it keeps referring to the space covered from "page edge inward". (The term "length" is usually used to refer to the length of the text, so when the text is set to vertical, the term "length" now refers to the Tabs vertical dimensions. This makes sense, but it is confusing, as the user isn't sure.)

No I don't have any better suggestions. Just letting you know that new-user confused feeling I got when I hit Vertical and the terms "length" and "height" values didn't change places or change terminology or anything. So I wasn't sure I was going to get what I was hoping to get. BTW, it did work as I'd hoped; I just couldn't tell if it was going to.

**Comment by mhosken** [comment]
Closing this issue on the basis that nobody can think of a solution. If someone comes up with a better alternative we would be very open to considering it. If so, then raise a new issue when that time comes.
