### ISSUE TITLE
PicLists not showing!

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#219]
The first time I ran v1.1.9 it showed a piclist (but didn't export pictures)! 
Now it exports pictures and has created a series of PicList files (with the Config file name), BUT it **doesn't show anything** in the View window, and the **Edit button no longer works**! (Even though the file extension is associated with Notepad++).

The PicList folder contains both old versions and new versions of the PicList files. Maybe this is messing things up?

**Comment by mhosken** [comment]
I think this is due to our changing the filenames we use for the .sfm files that TeX reads from file-draft.SFM or file-<config>.SFM (or whatever). I have added transition load code to convert from one to the other on project load. We should probably produce a 1.9.1 to test this.

**Comment by KimB2017** [comment]
I'm seeing the same thing David reports above. I just installed 1.1.9 in a fresh Wasta 20.04 system.

**Comment by mhosken** [comment]
Yup. There is a fix in the works.
