### ISSUE TITLE
Request: Handle missing characters in font more intelligently

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#22]
When a font is missing "special" characters like smart quotes, en- and em- dashes, and so on; allow specifying a "fall-back" font which can handle those better rather than show tofu boxes.

**Comment by devosb** [comment]
I can see the practical issues with having a fallback font. Ideally, there might be a note that is shown with a fallback font saying different fallback fonts might be used (or not used as all) in other publishing environments (print, web, app). Therefore, users should strive to obtain a font with all the needed characters.

**Comment by davidg-sil** [comment]
There's some code [here](https://tex.stackexchange.com/questions/447941/fontspec-fall-back-to-other-font-on-missing-glyph) which could specify some error message code. Alternatively - and what I'd recommend, is if xetex is being run by a program, parse the log file at least enough to find the problem and provide user feedback / error ... I've done this in a Makefile, so I'm sure that other languages can cope!
You need to parse the output anyway to see if there's a 'things may have changed... rerun' type messages.

**Comment by markpenny** [comment]
We now have a system in the UI (on the Body tab) to identify any characters in the text which cannot be displayed by the "regular" font. And then a "Fallback font" can be specified which will be used for these characters.
There are quite a few caveats though: 
(1) The following characters are already being used as "specials" and therefore need to be ignored by the Fallback font functionality:
           \u2018 \u2019 \u201c \u201d * # %
(2) We only have one (regular) face for the fallback font rather than b/i/bi as well.
(3) It doesn't work for characters in footnotes, xrefs, etc.
