### ISSUE TITLE
If we say to use PicList specs, but there are no PicList files, PTXprint crashes

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#220]
As a test, I removed all the PicList files from the PicList folder.
Reran PTXprint, and it runs fine for most of the way through the Print process, but then it simply blinks out! PTXprint crashes and disappears.

So I reran it. And it had rebuilt the missing files, but it still crashes but with this error message: 

![image](https://user-images.githubusercontent.com/65363206/94344858-48fd1180-fff0-11ea-834d-dcdd7d29dde1.png)

I have actually done NOTHING. Just letting PTXprint handle everything. So I don't know what it is complaining about, unless it is because in one of my \fig fields I removed  the Ref=" " bit to verify it was okay to leave out. Apparently it is needed/required (when it shouldn't have to be--ballpark numbers should be adequate to get the picture in the general area).

**Comment by mhosken** [comment]
It seems to be complaining about the \fig entries in your .sfm file. Not sure why they were not deleted but that's why TeX is complaining. Note the .tif in the missing src file. That's a dead giveaway since TeX can't load .tif files, so ptxprint has to do something to avoid that situation. The other dead give away is that the error is for a USFM2 style \fig entry and ptxprint never produces those now.

**Comment by mhosken** [comment]
Crash fixed. I'm not sure the actual error is ptxprint's fault. I'll mark this fixed, but do check and we can go round again.

**Comment by davidc86** [comment]
Just got v1.2 and ran it without changing anything.

I still get the bogus USFM check error saying the \xt marker can't be closed by the \x* marker. This is actually valid as I've mentioned before, but PTXprint is still flagging this as an error (at least now it only flags it on the LAST book where this occurs rather than for each book). Still,PTXprint needs to not flag that as an error.

First run took a VERY long time to finally through the above check error. After which PTXprint continued until it through this (again): 
![image](https://user-images.githubusercontent.com/65363206/95092195-5e132800-06f5-11eb-8db9-33e6d027db35.png)

Here is this same error again, but we use this SAME illustration in other places in the project and those places do not complain and are added to the PDF file correctly. So I'm wondering why PTXprint is not properly seeing this/converting this at this second location? I think I have narrowed down that this complaint is happening in the very last book of the project (a "Maps" book using the BAK book). There are no verses here, so I don't know if this might be throwing things off. The PDF fails to complete, but it is 99% there.

**Comment by mhosken** [comment]
Please submit a zip archive of the config. There is no way I can guess what is wrong with a specific context of a \x without seeing the file in question. As to the missing .tif file, do you have that picture in your project pictures?

**Comment by davidc86** [comment]
I need you to be more specific about what you need. Do you need the original USFM project files? Do you need just the Config folder that is messing up? Do you need the pictures folder too? How will you recreate the problem if you don't have all of these files?

**Comment by markpenny** [comment]
Hi David,
The button on the advanced tab will automatically package up everything
needed from the current (failing) configuration and all you have to do is
to send it to Martin. We can then recreate the job exactly as you see it
and fix the problem. That's the whole point of that button.
Thanks
Mark

**Comment by davidc86** [comment]
I've sent an email with a link to that zip file. (Can't send it through email.)

**Comment by mhosken** [comment]
The cause of the problem is that in your custom.sty you have:
```
\Marker xt
\StyleType character
\TextType notetext
```

I acknowledge that it is a bug not to handle this correctly and we are working to resolve that bug. But a workaround is to fix the caseless character->Character and notetext->NoteText.

**Comment by davidc86** [comment]
I have tweaked these offending lower case letters in my  custom sty file and this seems to have eliminated the \xt ….. \x* error (where there was no \xt* to help close the \xt field).
