### ISSUE TITLE
Info/copyright not updated

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#222]
It appears that when I switch to a project that doesn't have certain info/copyright, it just leaves the info/copyright from the previously selected project:

![image](https://user-images.githubusercontent.com/14953913/94435326-feeb6b80-0168-11eb-9563-5a72abfdab93.png)

**Comment by mhosken** [comment]
Having a hard time replicating this or seeing where it might have gone wrong.

**Comment by markpenny** [comment]
I'm guessing this was something related to the configs not loading properly. Can you confirm whether this behaviour has now been corrected in 1.1.9.6 please.

**Comment by jeffheath-sil** [comment]
It seems to be doing the right thing now.
