### ISSUE TITLE
My old PicList was lost in transition to 1.1.9

### ISSUE THREAD

**Issue by viverechristus** [sillsdev/ptx2pdf#226]
When I opened 1.1.9 and went to my standard configuration (called "Matthew-Standard"), I went to edit the PicList, and it was gone. So I regenerated, but of course that means I need to figure everything out again. Is my old list saved somewhere? People might be frustrated to lose their previous work on PicLists. I was. :)

**Comment by mhosken** [comment]
If you ran as administrator, take a look in C:\ for 41MATPRJ-Matthew-Standard.SFM.piclist (or whatever filename fits for you).

There was a nasty missing path in the transition code that was to copy files from the old naming to the new naming in the project settings. So you will want to copy that file to Paratext8Projects(or whatever)\PRJ\shared\ptxprint\Matthew-Standard\Piclists

**Comment by KimB2017** [comment]
With 1.1.9.6 I still can't find my saved piclist for any saved configuration, or for the previously-open configuration. However, I discovered by accident that I can retrieve the saved piclist (or the last one I used before closing ptxpring, perhaps?) by ticking **Use PicLists** on Pictures tab, then clicking **View/Edit**. Then the piclist appears in the View tab. Hurray!

**Comment by viverechristus** [comment]
You can mark this as fixed -- I never got my piclist back, but I think there's nothing to be done.
