### ISSUE TITLE
NameError: name 'Gtk' is not defined

### ISSUE THREAD

**Issue by eburgi** [sillsdev/ptx2pdf#23]
I got the following error message when I tried to print a book of my test project. 

![grafik](https://user-images.githubusercontent.com/22383998/69711017-6849ba80-1111-11ea-84ba-136db64dfc20.png)

The same error I got for other projects as well. Where would I need to define the 'Gtk' name?

**Comment by markpenny** [comment]
I'm hoping that this has been solved in a more recent version. Would you please download the latest version 0.2.6 which is available at the same link as usual [tiny.cc/ptxprint](http://tiny.cc/ptxprint) and let me know if it solves your issue. Thanks.

**Comment by eburgi** [comment]
Yes, this solved the issue. Thank you.
