### ISSUE TITLE
FRT output fails because of orphan marker \mt2

### ISSUE THREAD

**Issue by viverechristus** [sillsdev/ptx2pdf#231]
The USFM 3.0 [documentation](https://ubsicap.github.io/usfm/peripherals/index.html) for the FRT peripheral materials suggests a layout in which the `\mt#` tags occur under `\periph` rather than `\id`.

Our own draft of peripheral materials looks like this:

> \id FRT - Jarai Cambodia Khmer Script
> \rem Figures in this project may ...
> \periph Title Page
> \mt2 គ្លើយ ផ្រវ ហ្យាមម៍ ទុយ តាម
> \mt1 ម៉ាធឿ
> \mt2 ជិះ
> \pc ហ្លា ពហ្យាប់ម៍ អ៊ើយឋៃ
> \pc ហ្យាប់ម៍ ឆ្រៃ យគ
> \pc Jarai Kampuchea Bible (JKB)
> \periph Publication Data
> \mt3 ផាប់ ហ្រៈ
> \mt3 គ្លើយ ផ្រវ ហ្យាមម៍ ទុយ តាម ម៉ាធឿ ជិះ
> \b
> \mt1 ហ្លា ពហ្យាប់ម៍ អ៊ើយឋៃ
> \mt2 ហ្យាប់ម៍ ឆ្រៃ យគ
> \mt1 Jarai Kampuchea Bible (JKB)
> \b
> \pc © 2020, .... 

In PTXprint this returns the error:

![image](https://user-images.githubusercontent.com/915182/95426750-9ecaa580-0970-11eb-85b6-2470938d928d.png)

I have created (as recommended) a special stylesheet for peripheral materials called frtbak.sty. In that stylesheet I have added the following at the bottom to allow \mt and \mt# to occur after \periph:

```
\Marker mt
\OccursUnder id periph c p pc b

\Marker mt1
\OccursUnder id periph c p pc b

\Marker mt2
\OccursUnder id periph c p pc b

\Marker mt3
\OccursUnder id periph c p pc b

\Marker mt4
\OccursUnder id periph c p pc b

\Marker pc
\OccursUnder id mt periph

\Marker b
\OccursUnder mt p pc

\Marker li
\OccursUnder c p pc
```

This turns off the error marking in Paratext, but PTXprint still refuses to create an output. I'm not entirely certain whether this is a PTXprint issue or a Paratext issue. If I should post somewhere else, please let me know.

**Comment by mhosken** [comment]
Please send a minimal archive

**Comment by davidg-sil** [comment]
It makes perfect sense to me that as USFM3 is allowing multiple types of peripheral material inside one book,   \mtX would need to occur under \periph

Thus I'd say that there are **three** bugs: one with usfm.sty not correctly following the specification, 
secondly, why doesn't the modified style sheet get read / understood by the sanity checker.

And thirdly, there is also a bug / implicit feature request in that if people are putting multiple pieces of  introductory material into the "\id INT" book, e.g
```
\periph Prophecy Introduction |id="intprophesy"
```
(And likewise FRT and BAK) There should eventually be some kind of mechanism to treat these files as databases, where the relevant introductory sections can be pulled from.
Given my prejudices, I'd like to see that handled in .tex :-) , but I expect it'll be easier to do in python.

**Comment by viverechristus** [comment]
This doesn't give an error any more, but I think default behavior should give a pagebreak at each \periph tag, and "Hide/Exclude Content of Marker" should be checked by default.

**Comment by markpenny** [comment]
We plan to work on a \periph viewer/editor in future - so this suggestion can come in at that point. Closing this issue.
