### ISSUE TITLE
Maybe PTXprint should clean up old files from a Config's folders?

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#233]
I'm now using v1.2, and it is working better than v1.1.9, but I did notice a bit of an oddity, where it doesn't clean up after itself when I save a new "configuration". It correctly copies the current active configuration files over to the new configuration folder and even names them (like the PicList filenames all have "default" in them from the Default folder that the new configuration started from). BUT once it saves the new configuration, it creates duplicated PicList filenames with the new configuration name, but it leaves the old "default" files in there too: 

![image](https://user-images.githubusercontent.com/65363206/95588453-7050d700-0a11-11eb-99e3-a0e33c7e3a05.png)

I'm just thinking it'd be neater if, after a Save, PTXprint could clean up the old files from the config's folders.

**Comment by davidg-sil** [comment]
I think I'd want it to be very careful to NEVER delete anything ending in .piclist.
You might want to go back to the other configuration, surely?

**Comment by davidc86** [comment]
The "default" files were copied from the PTXprint "Default" PicList folder into this new Configuration's PicList folder, but then after I ran the Print process, apparently PTXprint saved Configuration-specific PicList files and stored them here too. Seems best, after the PTXprint has done that slight-of-hand, it would clean up after itself. But maybe davidg-sil's point is that for now it might be best to NOT have PTXprint delete stuff, until we know all is working exactly like we want it to.
