### ISSUE TITLE
V1.2 is Quadrupling Illustrations

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#234]
Here is a screenshot of Acts 2: 

![image](https://user-images.githubusercontent.com/65363206/95592743-10f5c580-0a17-11eb-998a-8f7fa7bcceee.png)

Here is a screenshot of the PicList table: 
![image](https://user-images.githubusercontent.com/65363206/95593258-734ec600-0a17-11eb-9a9a-aeae63ce55ed.png)

Interesting to note: the ascension of Jesus picture in Acts 1 did not export to the PDF file (though I saw no notification of any issues). And then the Peter Preaching picture is doubled on two pages (occurs 4 times --two times on two pages), and then a large chunk of the rest of the pictures fail to export, though they have a spot held for them: 

![image](https://user-images.githubusercontent.com/65363206/95593593-e48e7900-0a17-11eb-934b-d4d81e662322.png)

And then a few more pictures show up quadrupled, and then more skips, until eventually no more pictures are exported in the PDF file.

![image](https://user-images.githubusercontent.com/65363206/95594124-84e49d80-0a18-11eb-8321-81a42ac61da8.png)

This is without me tweaking anything in the PicList files. Just Generating the files and clicking Print.

**Comment by davidg-sil** [comment]
That, as you can guess, shouldn't happen! 
It's a shot in the dark, but can you check for \picslurpfalse or \picslurptrue in any file that might get included?
(`grep picslurp *.tex *.sty *.SFM ` from the relevant directory should work if you happen to be on linux)

I see the files are listed as .TIF. Now, since xetex can't export .TIF images to a PDF file these days (but for historic reasons it might still be able to read them, I don't know), I wonder if ptxprint is silently fibbing about what's REALLY in the piclist, or that's why the pictures aren't showing up.

**Comment by davidg-sil** [comment]
As you can probably guess, there's probably going to be a need for a .zip file at some point, if we can't duplicate this problem easily.

**Comment by davidc86** [comment]
I'm not seeing any picslurp strings in any of my files (tmp or otherwise).

I suspect this issue is related to PTXprint v1.2 of adding new entries into existing PicList files for any illustration in the PicList file whose specifications differ from the original \fig field specs found in the Paratext USFM files. (So if the PicList file specifies a Reference location or anchor location that is different than what is in the Paratext USFM files, PTXprint generates a new entry in the PicList file matching the specs it found in the Paratext file. This generates at least 2 pictures for every illustration (that differs from the Paratext USFM).  How it ends up with 4, I've no idea.

**Comment by davidc86** [comment]
On second thought... probably not, because the PicList table does not list more than one map, so that doesn't explain the same 4 illustrations showing up one after the other in one place.
