### ISSUE TITLE
v1.2 is very SLOW

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#235]
I thought it was slow, so I timed it. 
I opened my test configuration (a new one, so it wouldn't have left-over debris from earlier config files).
Clicked Print
........Nothing shows except a spinning mouse and a [Not Responding] in the title bar (which BTW is a bit unpleasant, especially when it takes so long to get to the next step -- enough to make IT users kill the process with Task Manager).....

5 minutes 32 seconds later, the Blue progress bar moves the midway point, and the [Not Responding] disappears from the Title bar. 
A very few seconds later the PDF file opens! 
So, almost 6 minutes on a fully updated Windows 10 v2004 10th Gen core i7 CPU laptop with 16GB RAM and a 1TB SSD drive. This machine is no slouch. 
Something isn't right. It always took a little while before the Blue progress bar showed anything. But now it looks like it freezes for an excessively long time before showing anything. And this is just text manipulation (not video rendering or something intensive). 

Anything I should do differently? Or is this a bug? Maybe in configurations with multiple books, showing the current book being scanned or the current process being worked on in the progress bar would be better than showing nothing.  Is this possible?

**Comment by davidg-sil** [comment]
More data would be useful - is it python or XeTeX that's taking the time?  Task manager might tell you on windows, for example.
Sometimes TeX has a really really hard time breaking a page, and tries going round its loop a lot of times. Sometimes it gets in a stuck condition that it shouldn't ever get into, where it keeps trying 'forever'.  This shouldn't happen and would be classed as a bug.   It may be that ptxprint is detecting that condition and killing the job. If the PDF is truncated, expect that you've hit one of those. 
Often tweaking the size of a preceding picture is sufficient to resolve such issues. Given that 1.2 is giving picture problems, it might be related.

**Comment by davidc86** [comment]
Right now v1.2.9 is so messed up on my machine, I can give you anything. So, once I get that sorted, I can send something if this is still an issue.

**Comment by mhosken** [comment]
Better, please, close the bug if it is no longer an issue, rather than leaving us guessing.

**Comment by davidc86** [comment]
Sorry, didn't see this one. It's fixed. Woohoo!
