### ISSUE TITLE
PicList Table Duplicates entries in the List

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#236]
v1.2
I have carefully gone through the new PicList files generated by v1.2 and edited them outside of the program so as to align the specs with the sizes and verse references that I had working well in the past. 

Saved the edits.
Reopened PTXprint 
Went to the PicList table screen and (ouch!) all the illustrations I edited have been duplicated! 

![image](https://user-images.githubusercontent.com/65363206/95664747-ae84ee00-0b18-11eb-8321-ed8f8c977b8f.png)
 
So then I closed the program, re-edited the PicList file for GEN and to remove the duplicates.
Reopened PTXprint, and (pow!) the duplicates come back in! 
Why is it rebuilding the PicList files each time it opens? It should only do that once, if there are no PicList files. And it shouldn't do it again until the user specifically tells it too. (And even then it should warn the user about losing the current PicList files.)

So what is happening here?

**Comment by davidc86** [comment]
Okay. As mentioned in another issue, while sorting that one out a bit I was able to determine that the bug here is due to any difference between the PicList file illustration specs and the illustration specs found in the original scripture SF files. If there is a difference, PTXprint adds a new entry for the same illustration.

For example, in the screenshot, the first entry was ADDED by PTXprint, because in the USFM file the \fig field specifies GEN 1:19 as the reference. My tailored PicList file does not have an illustration spec'd for GEN 1:19, because after seeing the output from PTXprint (back in v0.8) it worked better to actually ANCHOR this illustration at GEN 1:25, and change the reference to indicate that the illustration is referring to "**Gen. 1:20-23**". (It also needed to be displayed at 90% scale.) I did not see the need to go back to the Paratext project files an tweak these \fig files, because in a different application, with a different font, or page size, etc. ALL of these variables will need to be changed again anyway. (And Paratext is lacking the needed differentiation between anchor location and the "reference" string that is included in the Caption -- these are frequently NOT the same.)

Back in PTXprint v0.8 I had worked through most of my book illustrations and adjusted each for size, anchor, and reference, to get the pages all looking nice and the illustrations sitting adequately on each page. And I saved these settings in all the relevant configuration PicList files. 

So for me, it is not helpful for PTXprint to "fix" my PicList files by adding "missing" illustrations. If I need to get an updated version of the PicList files (say you guys change the specs), then I simply regenerate a set in a new configuration, and then file compare the new versions with my saved versions. (This is how I discovered the "scale=" variable.) Or if you want to automate that process, then rename my original "good" piclist files to "Blah-blah-SAVED" and generate a new set with the new variables or changed formatting/structure. So both forms are in the same folder and I can do a compare to see what tweaks I need to do to my "good" originals to bring them up to the new standard. 

Anyway, I like the table approach. And once it is working smoothly, it will be a very helpful tool!

**Comment by mhosken** [comment]
I think there are 2 things going on here. There is issue #232 which is a discussion on whether we allow multiple figures anchored to the same verse, combined with bugs in saving piclists which were an issue up to 1.3. I'll therefore mark this fixed.
