### ISSUE TITLE
Piclist spinners not retaining typed values

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#237]
v1.2 
PicList Table
SIZING:
I notice that the "span*.8" and "col*.5" etc. are not properly reflected in the table. Rather it says 100% for all the illustrations. (Though the ones I edited outside of PTXprint do have the "col*.7" whereas I was expecting "col" "70%" -- this looks like a bug to me.)

Also, if I set the % to something different that 100, and I save the table and exit PTXprint, when I open the PicList file outside of PTXprint, the file does NOT show any value other than "col" -- so this looks like a bug too.

**Comment by davidc86** [comment]
Testing this a bit more, if I type in the % I want, it doesn't stick, but if I use the Up Down arrows, it seems to retain the size value. But I'm still getting an error when it tries to process the PDF file, saying the size is too large. But the error message doesn't give me a whole lot to go on to track down the problem. (I have approximately 20 books in the configuration file.)

**Comment by davidc86** [comment]
Okay, I was able to create a "corrected" PicList file for GEN. And save it off in a safe place. This "corrected" version no longer uses "col*.7" or such, but rather uses the "scale=0.7" variable. This was finicky but I got it done. (I use single columns, so to be on the safe side I just switched them all to "size=span" as well.)

Then I open PTXprint and go to the PicList table, and the PTXprint v1.2 bug creates duplicates of anything not exactly like the scripture SF files. But then I can go through the list and delete the added (wrong) entries, and export the PDF file and it is finally starting to look like it did back in v0.8  (where I can finely control size). I still wish on "span" we could define a picture as "scale=0.4" and position would be "tl" or "tr" so we could put two similar pictures side-by-side in the same space. (Being < 50% they should fit LEFT and RIGHT in the same location.)

So, I was able to verify the sizing works... it's just that other bugs keep masking the issue. But NOTE: typing in the % does not seem to create a "scale=0.x" where as using the UP and DOWN spinner does see to get the "scale" variable into the PicList file. (So that bug is still in v1.2)

**Comment by mhosken** [comment]
USFM2 and USFM3 differ in this respect. In USFM2 we do all kinds of overloading tricks to store more information in limited fields. In USFM3 we separate things out for clarity, since the format is extensible. Therefore, there is not a 1:1 relationship between fields in USFM2 and USFM3, at least in our interpretation of \figs. I realise that the USFM3 spec may take a different (if unrealistic, in our opinion) view.

**Comment by mhosken** [comment]
The remaining issue here, is that I don't think we have fixed spinners not updating appropriately when one types in a value.

**Comment by davidc86** [comment]
Personally I'm with you on the \fig specs. They seem wholly inadequate. Your specs are much more in line with what a user needs.

Correct the spinner works but typing in the box does not.

**Comment by mhosken** [comment]
Am assuming this is closable.
