### ISSUE TITLE
v1.2 Selecting Multiple Books does not refresh PicList Table correctly

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#238]
v1.2
My config file has 20+ books. 
But if I check Single book for a moment and then go to the PicList table, then only the selected single book's contents show in the table. (Correct behavior.)
But if I then check Multiple books check box again, and then go to the PicList table, it still only shows the single book's contents.
Expected behavior, the PicList files from all the books in the configuration list would be displayed in the PicList table.
The only way I could get PTXprint to properly refresh the table was click the Choose button again on the Multiple books option, and then click OK (even though all the books I want were already listed in the text box next to the Choose button.
After clicking OK, then going to the PicList table did refresh with all the PicList files correctly (well, almost correctly! It keeps rebuilding the PicList files even though I already have tweaked the files just like I want them, and this rebuilding of the table's lists creates duplicates for any illustration where I've specified a reference or anchor location different from what is in the original SF file. But this is a bug listed in a different "issue".) 
Here the issue is PTXprint not refreshing the table with the files from the configuration folder every time the user switches to this tab. (Also, note, if I edit a PicList file outside of PTXprint, while PTXprint is still running, and click "Refresh" -- it does nothing. But here again, it should reload the files from the disk.

**Comment by markpenny** [comment]
Thanks for your helpful feedback David. We've bitten the bullet and decided to re-work the way in which pictures and piclists get processed.
