### ISSUE TITLE
SUGGESTION: PicList table: add Position and Scale columns in the edit view

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#239]
On the Edit tab of the PicList table, it'd be helpful to have the Position and Scale columns in the list displayed above the input area, because it is helpful to see how the illustrations surrounding the current illustration are formatted as well. (So was the last one at 60% or 55%? Was it Top or Bottom or Left or Right, etc.) 

I find myself having to flip back and forth between view and edit to check these attributes. 

(BTW, the "size" column (with span vs col, etc. might also be a useful column to show too--though now the label "size" seems a bit misaligned with its current function--solving that label issue is above my pay-grade. :) )

**Comment by davidg-sil** [comment]
I'm curious why you think that the size column is misnamed. Or are you suggesting it should be 'base-size' or 
something similar?
I hope you don't think the macros take size as anything more than a base-size these days. Position and size are coupled in the USFM spec, but if a position is specified then that very much takes priority.

**Comment by davidc86** [comment]
It used to be that size could look like this: **size="span*.65"** where the picture is to span across the page (margin to margin), but be reduced in size to 65% of the span width. (Maybe this format still works, but it isn't the new format in PTXprint.)
The new format is **size="span" scale=".65"** -- meaning the same thing, but dividing the variable in two (a better approach). 
So with "size" no longer describing the size of the picture but rather the "max base width/height" of the spot where the picture is to go, a different label might be more helpful. But I can't come up with one! Maybe "frame" because we are talking about the frame size of the hole created in the text layout in which the illustration is inserted. So the "box" or the "frame" for the picture. So the "frame" is 
1) column width: "col", 
2) margin width: "span" (with text), 
3) page margins without text: "P", or 
4) the whole page (outside the margins even) "F".
So "Size" still probably works just fine, but "Frame" might be more accurate. 
But not a big deal. Users get it pretty quickly.

**Comment by markpenny** [comment]
I've changed this in the new PicList UI (coming in 1.4). The control now calls it "Frame Size:" and the Column in the table above just has "Frame". I hope this helps people be less confused about Size+Scale.
