### ISSUE TITLE
Possible to print extra books?

### ISSUE THREAD

**Issue by eburgi** [sillsdev/ptx2pdf#24]
Is it possible to use this tool to print the extra books XXA - XXG?
I got the following error message when I tried to print one of these books. I tried it with both a book set up as a Bible Module and one just used as a additional book with Bible stories.

![grafik](https://user-images.githubusercontent.com/22383998/69721795-ac938580-1126-11ea-9ff2-71096710684c.png)

**Comment by markpenny** [comment]
I am 99% certain that the tool won't handle Bible Modules for a while (that's a whole new dimension and something that is quite likely to change within Paratext itself in the next 6-12 months - so it isn't something that we would want to sink a lot of time into developing).
However, it is possible (no promises!) that we might be able to get "normal" XX[a-g] books working. You've found a bug for us, and we'll see what we can do to get it working. Thanks.

**Comment by markpenny** [comment]
Some good news on this front. We found a couple of bugs which were preventing Extra books (and GLO etc.) for printing. These have now been sorted; AND, **yes** it is possible to print Bible Modules too! Please test version 0.2.8 and let me know how it goes. Thanks for bringing this to our attention.

**Comment by eburgi** [comment]
Great, thank you. I tested version 0.2.8 and it works fine.
