### ISSUE TITLE
HELP WANTED: Which Page Layouts do you need?

### ISSUE THREAD

**Issue by mhosken** [sillsdev/ptx2pdf#241]
One of the hardest things to do in TeX is to add a new page layout structure. It is a lot of work. So before we start architecting for new layouts, it would be good to elicit the need.

Currently ptxprint supports 3 page layouts:
- Single column
- Double column
- Vertical diglot

There are others that people want. This issue is your chance to express your desires regarding other page layouts that we may or may not get to producing. Please don't add speculative needs. Only add layouts that you would actually use. Currently known are:

- Single column top / bottom diglot
- Study bible two column notes with double column text

**Comment by davidg-sil** [comment]
Judging by the huge response.....

**Comment by KimB2017** [comment]
Maybe post to the PT newsgroup or the SIL Community software page? Not many people are reading this site, I don't think.
