### ISSUE TITLE
Setting size in Piclist Editor

### ISSUE THREAD

**Issue by KimB2017** [sillsdev/ptx2pdf#243]
> Testing this a bit more, if I type in the % I want, it doesn't stick, but if I use the Up Down arrows, it seems to retain the size value. But I'm still getting an error when it tries to process the PDF file, saying the size is too large. But the error message doesn't give me a whole lot to go on to track down the problem. (I have approximately 20 books in the configuration file.)
> 
> _Originally posted by @davidc86 in https://github.com/sillsdev/ptx2pdf/issues/237#issuecomment-706753196_

(1.2.9) I also see that the Scale % figure does not stick (1.2.9) when I simply type or paste a number into the box, even if I paste it and then hit TAB to move focus to the next box. The only way to register a Scale edit is to use the - + buttons. I think this is a bug.

**Comment by davidg-sil** [comment]
I saw at least one version on Friday evening, I think it was,  when this was fixed... 
However, I can confirm it's still/back in the current head.
I guess it crept back in.
