### ISSUE TITLE
Icon missing in launcher and panel window indicator

### ISSUE THREAD

**Issue by KimB2017** [sillsdev/ptx2pdf#245]
There is no ptxprint launcher icon or app-window icon (on panel for open window); it's just a blank patch on panel and in menu.

**Comment by n7s** [comment]
looks like a path issue with the icon in the .desktop file, will investigate and fix

**Comment by markpenny** [comment]
@n7s Any success on this one?

**Comment by n7s** [comment]
I have isolated the issue and should have the commit ready soon.

**Comment by n7s** [comment]
Should be fixed now with a scalable icon properly installed and called in the Ubuntu packaging. Please test again.

**Comment by markpenny** [comment]
Thank you @n7s for fixing it for us. @KimB2017 Could you confirm that this is all now working as you expect, and if so, please close the issue. If we don't hear back within a few days then we'll assume all is well and close it ourselves.

**Comment by KimB2017** [comment]
It's fixed! Thank you so much, Nicolas.
