### ISSUE TITLE
Superscript height for \v 

### ISSUE THREAD

**Issue by KimB2017** [sillsdev/ptx2pdf#246]
The FAQ in GitHub says:

> Q: I shrunk my verse numbers and now they're just floating in the middle of the line
> A: In your configuration .tex file, you need to adjust this number.
> > \SuperscriptRaise{0.85ex} % note that this is in terms of the scaled-down superscript font size

I tried putting this into ptxprint-mods.tex in the shared/ptxprint folder, and also into the ptxprint-[ConfigName]-MATRTTT.tex file that is generated at each Print run. Modifying the .85 doesn't seem to do anything in either place. Maybe the answer here could include a bit more info for many of us, please?

**Comment by davidg-sil** [comment]
Looking at the code (again, I think it's been modified since I last looked at that section)...
Sorry, there was a typo on the FAQ (or something changed?)
The correct format is:
```
\def\SuperscriptRaise{measurement}% default 0.85ex, measured in terms of the scaled down font. (an x is 1ex high)
```
What it does is alters the default amount that the footnote is raised by, when ```\SuperScript```  is read in the style file. I.e. for changing it to have any effect, it must be set before the stylesheet is read.

There is also individual control within the stylesheet over the raising e.g. ```\Raise  1ex``` in the stylesheet. Note that for this to be effective, the ```\Superscript``` needs to come before ```\Raise```, otherwise its value will be overwritten by the value of SuperscriptRaise

**Comment by davidg-sil** [comment]
At the moment this the ```\def\SuperscriptRaise{measurement}``` global method is not accessible from ptxprint-controlled print jobs,  because the .tex input files are read in after the style sheets. I'm therefore labeling this as an enhancement.

**Comment by mhosken** [comment]
I suggest that what is needed is a \includeifpresent{filename.tex} that only includes the given file if it is present and doesn't complain if not. Then we can insert \includeifpresent{"shared/ptxprint/config/ptxprint-intro.tex"} and people can hack in there without having to add yet more UI to ptxprint (or we can add an edit button if we so want).

**Comment by mhosken** [comment]
As a work around for a specific case one can set the Verse style to be non-superscript; reduce the fontsize to 9 (from 12) and set raise to however many points you want the verse number to rise up. Note this is an absolute value (not ideal).

**Comment by davidg-sil** [comment]
Usage: 
```
\includeifpresent{path/to/filename.tex}
``` 
(ie. quotes should not be included, as they're dealt with internally)
Implementing the python code to include it (before any stylesheets) left to people who know that language.

**Comment by mhosken** [comment]
We added an ptxprint option for ptxprint-premods.tex which is inserted before any stylesheets.

**Comment by KimB2017** [comment]
Sorry, I wasn't following this issue and I have trouble interpreting tex code on the fly. Am I getting it? I think a summary of your fix for this issue is:

> To change the height of a superscript [e.g., cause a verse number to be raised to 100% of its (scaled down from the text) size], add this line to ptxprint-premods.tex:
> `\def\SuperscriptRaise{**1ex**}% default 0.85ex, measured in terms of the scaled down font. (an x is 1ex high)`
>
> Alternatively, one could add to the Verse Number def in **ptxprint-mods.sty** 
>> \v Verse Number
>> ...
>> \Superscript
>> **\Raise 1ex**

**Comment by KimB2017** [comment]
Can I reopen this issue? 

I created .../shared/ptxprint/ptxprint-premods.tex by choosing Edit on the Advanced tab in ptxprint. Contents of the file are:
> % This is the preprocessing .tex file specific for the RTTT project used by PTXprint.
> % Saved Configuration name: Default
> \def\SuperscriptRaise{1ex}% default 0.85ex, measured in terms of the scaled down font. (an x is 1ex high)

When I Print with this file enabled on Advanced, it fails with this:
![image](https://user-images.githubusercontent.com/25071218/105412567-ed8c0a80-5c02-11eb-9568-8625c6c442bc.png)

**Comment by KimB2017** [comment]
On the other hand, I can now specify the superscript height for verse numbers by adding '\Raise 1.2ex' to the \Marker v spec in **ptxprint-mods.sty**.
