### ISSUE TITLE
SUGGESTION: Show the folder name when "Use Pictures from this folder" is selected

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#249]
SUGGESTION: It would be helpful if PTXprint would show the folder name it is looking in if the "Use Pictures from this folder" option is selected. This way, at a glance, the user can know whether PTXprint is looking in the right place.
![image](https://user-images.githubusercontent.com/65363206/96610319-7e341100-12c9-11eb-9bf0-c94040a5ab73.png)

**Comment by markpenny** [comment]
I'm also wondering whether we should display the actual path (to the source) as a Tooltip on each image in the PicList editor.

**Comment by markpenny** [comment]
Added the path below the controls (done in picui branch) - will most likely be available in 1.4
@mhosken - any thoughts on how we could pull off the suggestion above - to show the actual source of each image (maybe just as a tooltip on the Filename control)?
