### ISSUE TITLE
PDF Text Merge

### ISSUE THREAD

**Issue by prabhujes123** [sillsdev/ptx2pdf#25]
I created PDF in PTXprint-0.2.7, found one issue, attached screenshots.  I am finding this issue in Bible text only not in the introduction pages. After introduction of Each book this issue appearing. 

![image](https://user-images.githubusercontent.com/56344868/69799306-09f80700-11f9-11ea-89bb-19ca3d7488b2.png)

![image](https://user-images.githubusercontent.com/56344868/69799341-1a0fe680-11f9-11ea-93da-7ee3c73fe5ad.png)

**Comment by markpenny** [comment]
Yes, Prabhu. We are aware of the issue and are trying to find a solution. As a temporary work-around, try setting this option to see if it solves the problem:
![image](https://user-images.githubusercontent.com/12962708/69824621-6297c600-1232-11ea-9c2b-a2ca448018d2.png)

**Comment by prabhujes123** [comment]
Thank you. It's worked well.
