### ISSUE TITLE
"Failed to create" error saying Unable to load picture

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#251]
I opened v1.2.9 and did nothing to any of my settings, and selected print, and got this message: 

![image](https://user-images.githubusercontent.com/65363206/96622213-a591da80-12d7-11eb-951c-42cd021c6ca7.png)

But v1.2.9 said I had no missing illustrations. And Paratext shows the image just fine. 

This occurred at the "PetaLokasi5T_Selaru.tif" map in 1Tim 1:10, so it is a long way into the whole set of books (usually Gen. Jon. Luk. and Act. are the hardest for PTXprint), so I'll be doing more looking into this.

**Comment by davidc86** [comment]
Never mind. I found the picture. Apparently the "Default" folder had the OLD name for the file in there. 
But this brings up 2 questions:
1) Why did the Pictures tab say there were no missing pictures, if this fig \field had the wrong filename in it?
2) Why did PTXprint go look at the PicList files in the Default folder? This configuration I was working on was based on a configuration that had the correct filename in it. So how did the bad file name end up back in the PicList file?

**Comment by mhosken** [comment]
Question 2 should now be resolved. In answer: probably because it wasn't properly saving the publication piclist file.

**Comment by davidc86** [comment]
Right. I think this is closed (well the main issue is fixed!)
