### ISSUE TITLE
v1.2.9.5 Autoopening missing config is not creating anything

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#256]
When I open version 1.2.9.5 of PTXprint it looks like this: 

![image](https://user-images.githubusercontent.com/65363206/96911657-20d9c480-146f-11eb-84bc-f2d3761d349a.png)

The problem is, there is no configuration **SLUpublished-2020-10-08** in my "shared\ptxprint" folder. There used to be, but I removed it in order to test v1.2.9.5 with a clean setup. So this is a bug. PTXprint should be able to read that folder and show the available configurations it finds there. And if what it thought would be there, isn't, it should drop back to "Defualt" before a user does anything. (I suppose a fancy UI in this case might say, "The expected configuration "SLUpublished-2020-10-08" from the last time PTXprint was run, cannot be found. PTXprint will revert to using the Default settings configuration. OK")

When I change the Default name to something else, and click Save and then move away from the Basic page and then come back, the configuration name has changed back to Default. 

Note: the ptxprint folder has a new folder in it with the new name, but it is empty. Nothing was copied into it.

**Comment by davidc86** [comment]
After my mucking with it and tweaking stuff, apparently PTXprint finally got a fully formatted/fleshed out Default folder configuration. So that now I can save new configurations based on that one. (Program still opens with the wrong configuration name showing.) 

I suggest that whenever PTXprint starts, if it has to create a Default folder from scratch (or there is anything lacking in there), that PTXprint should go ahead and fully populate everything in there, including building a complete piclist file.

**Comment by davidc86** [comment]
BTW, my mucking about makes PTXprint so it won't print any more. I suspect the PicList file.

**Comment by mhosken** [comment]
Fixed a bug where ptxprint was forgetting the config as part of its autostartup and so always reverting to Default. Not sure that is everything for this varied issue.
