### ISSUE TITLE
\zthumbtab not working

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#258]
Not sure what is causing this, but when I first started v1.2.9.5 and finally got Multiple books to print, it was working "okay" (in that it printed a PDF, but it wasn't using any scaling or position features of the PicList files).

I then tried to open a configuration with scaling, etc. and see if I could get it working with a crafted piclist set. But alas, now I can't get it to Print at all. On the first attempt, the button turns Green, then half the progress bar turns blue, then focus simply returns to PTXprint, without every generating an error or a PDF file. The second attempt does nothing at all (well the button turns Green while I'm clicking on it, but reverts back to normal when I let go). 

The Default configuration still has no specs for the illustrations, but the other configurations do. But in either case, it won't print.

**Comment by davidc86** [comment]
Woohoo! Okay, I can print again. Here is what I found:

I had started to test the \zthumbtab field marker as per someone saying in here that they worked (for diglot). So I converted mine back to real markers: 

\id 3JN - Selaru
\h 3 Yohanes 
\toc3 3Yoh. 
\toc2 3 Yohanes 
\toc1 3 Yohanes 
**\zthumbtab 3 YOH** 
\mt1 Yohanes 
\mt2 wasi atyahy a kla-telw ikeskye 
\is Tun a khatu malosu kitab ne 
\ip ...

This was done while trying out other things (My BIG MISTAKE #1). So I had no idea what caused the Print problem.
Finally I narrowed it down to this. Changing it back to 

\rem zthumbtab 3 YOH

To get it out of the process stream solved the print blocking. 
So 3 bugs:
1) if PTXprint runs into a confusing problem like this, it needs to say "Woah! What is that **\zthumbtab** thingy?" (or some such) so we can track it down.
2) if PTX print runs into a confusing problem like this, it'd be nice if it could elegantly ignore it (so, in the above error message it could add, "PTXprint will not be dissuaded by such a deviant marker and will press on without it!" (please revise the suggested message as deemed appropriate)
3) Why isn't the \zthumbtab field marker working? Is the a special way we have to set it up? (If so, this is not a MTT feature.)

**Comment by mhosken** [comment]
1. It should already. That is the most concerning aspect of this issue. Why is there nothing coming up to say there is a problem?
2. It should already, except for diglots where if it can't parse the text, it can't merge it.
3. There is no special UI for zthumbtab support. So you need to handle this in ptxprint-mods.tex and add `\TOCthreetabfalse`. See (https://github.com/sillsdev/ptx2pdf/blob/master/docs/documentation/thumbtabs.md#advanced-use).

**Comment by mhosken** [comment]
Capture all exceptions during canonicalisation. So that should help with 1 and probably 2.

**Comment by davidc86** [comment]
The main issue here was "I can't print now" but the real issue was how it was failing with the \zthumbtab field appearing in the SFM file. Now the \zthumbtab field does NOT kill the print process. But unfortunately it still does nothing. I had hoped PTXprint would automatically know what to do with the \zthumbtab field now. Apparently I need to do more tweaking in another file. And I'm not tech illiterate but the stuff in the ptx2pdf doc was pretty opaque to me. 
I just want to add a 
\zthumbtab KEJ
type of field at the top of each book so PTXprint can use the contents ("**KEJ**" or whatever) for that book's TAB text. I would have thought that was the purpose of this field.

**Comment by mhosken** [comment]
To use \zthumbtab you need to add:

```
\TOCthreetabfalse
```

to your ptxprint-mods.tex file and turn that on in the advanced tab.

**Comment by davidc86** [comment]
Hmm. I just added that to ptxprint-mods.tex file and activated it in the advanced tab. 
Ran the Print,
And the tabs come out blank. 
So the label I gave in the \zthumbtab field was not getting used to paint the tabs: 

![image](https://user-images.githubusercontent.com/65363206/97067363-b027ca80-158a-11eb-964f-99da79190740.png)


(I also noticed in books where I have not yet put in a \zthumbtab field, those tabs were blank too, so PTXprint doesn't use the \toc3 instead if the \zthumbtab is not found. But that is a complication.) 

NOTE: This configuration is the first time I've seen the TOC filled in completely, with the page number for the last line also showing! Tomorrow I'll test some other configurations and close that issue if all is good.)

**Comment by davidg-sil** [comment]
When writing bug reports, please always specify the version. What you're reporting looks very much like something I was hitting last week and thought had been fixed. It would be nice to know if it IS the same problem.
(In that case it was diglot merging removing everything after \zthumbtab so that by the time the file had got to XeTeX, there was no data for it to put in the tab)

**Comment by davidg-sil** [comment]
> To use \zthumbtab you need to add:
> 
> ```
> \TOCthreetabfalse
> ```
> 
> to your ptxprint-mods.tex file and turn that on in the advanced tab.

This is 50% incorrect.
`\TOCthreetabfalse` means that you want blank tabs if `\zthumbtab` is not specified. However, if \zthumbtab is specified then it will always override the toc3 entry (including if it is blank by the time it gets to XeTeX).

**Comment by markpenny** [comment]
@davidc86 - Can you check to see if this issue is finally solved/fixed?

**Comment by mhosken** [comment]
No response. Assume it's solved.
