### ISSUE TITLE
Version 3.0 - choosing Apply printDraft-mods.sty if none exists causes error message that can get hidden

### ISSUE THREAD

**Issue by philleckrone** [sillsdev/ptx2pdf#26]
I had thought I had a printDraft-mods.sty file and selected that option. When I tried to create the PDF an error message appeared and had to be closed several times.

One time when this happened, the error message got hidden behind the main window and I was unable to access it to close it (finally used the taskbar to get at it, but it was not obvious.

**Comment by markpenny** [comment]
All error messages and dialogues which require user interaction now stay firmly on top. Thanks for raising it.
