### ISSUE TITLE
v1.2.9.5 

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#261]
Why is there a picChecks.txt file in the root of the "ptxprint" folder:

![image](https://user-images.githubusercontent.com/65363206/96945725-80a29080-14ac-11eb-9d4a-df8b3f8c18db.png)

Shouldn't this file be in the Default folder, like it is in all the other configuration folders? Or is it a generic Paratext Project Wide settings file? What's its purpose?

**Comment by mhosken** [comment]
There are two picChecks files. One contains the 'global' (within a project) across publication information as covered by the "Across Various Publications" information. That is this file here in shared/ptxprint. Then in each publication there is the publication specific information held in a picChecks.txt file.
