### ISSUE TITLE
v13.1 Not seeing the illustrations in the Edit view

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#262]
When editing the specs for each illustration I don't see the thumbnail picture of the illustration. 

![image](https://user-images.githubusercontent.com/65363206/96946340-1559be00-14ae-11eb-8972-8f5e182a3638.png)

These used to show. Any idea why they are not showing? (The pictures are there and the PDF proves it.)

**Comment by mhosken** [comment]
This is impossible for us to reproduce. Please close if no longer an issue.

**Comment by davidc86** [comment]
Easy to reproduce if you use quality illustrations in TIF format: 

![image](https://user-images.githubusercontent.com/65363206/97066395-27596080-1583-11eb-9294-38ce385a08f3.png)

**Comment by markpenny** [comment]
I haven't been able to reproduce this locally myself (yet) but... @mhosken I wonder whether this is something to do with the PicInfo object pointing to the location of the file (which no longer exists at that location). At what point does it "go looking" for the best match, based on the parameters given on the Pictures tab? High/Low resolution, in a certain folder, etc.

**Comment by davidc86** [comment]
So you all are seeing a picture in that blank area, right?
I'm still not seeing it. in v1.3.1. But the PDF does contain the pictures, so PTXprint finds them some how.

**Comment by davidc86** [comment]
I'm seeing them now!
