### ISSUE TITLE
v1.2.9.5 Changes to the picture scale not retained after closing and opening the app

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#265]
v1.2.9.5 Changes to the picture scale not retained. 
Likely related to the issue in #263 
I get the impression tweaks in this Edit Details tab are not being written out to the PicList file in the config folder.
(I'm assuming here that the whole strategy for PicLists have now been combined into one file with the configuration name as the file name, right?)

**Comment by markpenny** [comment]
Confirming the regression - where scale isn't being remembered.
Yes, your assumption is correct. Each config gets ONE .picList file in which the pics from multiple books are combined. If you generate with another book (which isn't already in the piclist) it should just add those illustrations to the existing list - while preserving the carefully curated/edited list.

**Comment by davidc86** [comment]
Sweet. Much better design.
But apparently PTXprint is not writing out that file, nor saving it. 
When I tweak an illustration in a config with special tweaks, those  tweaks are lost next time I open that configuration.
I even had Default "Generate" a piclist set of pictures for itself, but alas there is no PicList file in the folder.

There seems to be an issue too with naming conventions from a few versions back to now. 
My v1.2 versions had combined piclist filenames that added the Paratext Langauge code to the front of the configuration filename, so configuration "XYZ" in the SLU project, created a PicList file named: "SLU-XYZ.piclist". Is that still the current strategy?

**Comment by KimB2017** [comment]
See https://github.com/sillsdev/ptx2pdf/issues/242. Now I see why the piclists in the shared folders don't have the book id in the filenames, and I see the purpose for the tickbox "only show active books" on the View piclist tab.

But I agree with DavidC that piclist tweaks are not saved correctly. The only place where I see my piclist tweaks saved is in the files that are saved in project/PrintDraft/, saved with the old convention of including the book id in the filename.

**Comment by KimB2017** [comment]
No, this is still not fixed for me in the current ptxprint 1.3.1, Wasta 20.04. After closing/reopening ptxprint, all my piclist edits are lost. They appear to be saved in shared/ptxprint/Newtest/RTTT-Newtest.piclist, but I can't find a way to get that file to load when I start ptxprint; it defaults to all pics displaying what's in the Paratext file.

So it's not just the Scale value that is lost; all fig specs revert to their PT values when ptxprint is opened.

**Comment by davidc86** [comment]
There should be a Default folder in that ptxprint folder. In there you can put a piclist file that you've prepared ahead of time. And when things mess up, Ptxprint pulls from that folder. (I believe this is how it works.)

Also, because the whole PicList system was completely overhauled (like 3 times), I was losing versions right and left, so I kept backup copies in a safe place, so after I notice corruption of my piclist files, I used FileCompare software to restore my piclist files to pristine copies for testing again. I'm currently not having issues (that I'm aware of in v1.3.2). But further testing is needed. Especially when changing anchor points, as this seems to create instabilities in some cases.
