### ISSUE TITLE
v1.2.9.5 Saving a configuration to a new name fails to copy the PicList file

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#266]
I suspected PTXprint wasn't writing out the **configname.piclist** file, so I went to the Basic tab and changed the configuration name "**SLUpublished-2020-10-22**" to "**SLUpublished-2020-10-22-COPY**" and hit Save. 

PTXprint saved the copy (woohoo).
But a folder compare showed these differences: 

![image](https://user-images.githubusercontent.com/65363206/96949446-e21b2d00-14b5-11eb-91d3-eb82e37437a6.png)

I'm not exactly sure what NestedStyles.sty is for, but it didn't get copied, but more importantly, the carefully crafted PicList file did not get copied either.

(One puzzler is the name of the PicList file. It has a **SLU-** added to the front of the config's filename, so "SLUpublishedXYZ" was given the name "SLU-SLUpublishedXYZ.piclist"  
Is this planned behavior. Or is this residue from an earlier behavior pattern? So my thinking is that this file should be just named "SLUpublished-2020-10-22.piclist" rather than having the extra "SLU-" on the front. Your thoughts?)

**Comment by davidc86** [comment]
I have just verified that if I copy of the PicList file to the SLUpublished-2020-10-22-COPY" config folder, I have to add "-COPY" to the filename. If I don't, PTXprint won't read that file. I also have to keep the "**SLU-**" code on the front end, too, because if it isn't there, then PTXprint won't read the values in that file. (In that case, the displayed values revert to "col" "100" etc.--apparently taken directly from Paratext SFM files.)

**Comment by markpenny** [comment]
Thanks for finding this. It will solve several other bugs too.

**Comment by davidc86** [comment]
Looks fixed.

**Comment by listentwice** [comment]
Fixed
