### ISSUE TITLE
v1.2.9.7 colophon did not print for single book PDF.

### ISSUE THREAD

**Issue by mabacon** [sillsdev/ptx2pdf#267]
v1.2.9.7 colophon did not print for single book PDF, but it did print for multiple book PDF (on last page)

We always put colophon on title page, did not see an option for relocating it.

Thanks

**Comment by mhosken** [comment]
The colophon is designed as a simple way for people to get some kind of copyright into simple print jobs, typically consisting of a single book. For more serious publications, a FRT file should be used. Notice that the markers in the colophon may be used in such a FRT front matter book. Thus if you have a title page, then you don't want to use the colophon mechanism, although the useful markers, used in the colophon, may well help you in producing your title page(s).

**Comment by mhosken** [comment]
Could you create an archive of your single book project and send it to one of us. Otherwise we have no way of reproducing the bug or to tell whether there is some user error involved.

**Comment by mabacon** [comment]
[DEWAS 2020-10-24.zip](https://github.com/sillsdev/ptx2pdf/files/5432606/DEWAS.2020-10-24.zip)
Today, it worked twice and failed twice for me, so the results are inconsistent.

**Comment by mabacon** [comment]
> The colophon is designed as a simple way for people to get some kind of copyright into simple print jobs, typically consisting of a single book. For more serious publications, a FRT file should be used. Notice that the markers in the colophon may be used in such a FRT front matter book. Thus if you have a title page, then you don't want to use the colophon mechanism, although the useful markers, used in the colophon, may well help you in producing your title page(s).

Are you saying that we can add these, to the FRT matter to get the info there?
\pc \zCopyright
\pc \zLicense
\pc \zImageCopyrights

**Comment by markpenny** [comment]
Yes - that is correct. You can include \pc \zXYZ... statements and get the same information.
Please note that for some of these (.e.g \zImageCopyrights) you may need to Print TWICE to actually see any credits (as it builds the list of illustrations on the first run and then uses that list on the second run). Yes, it's a bug that it doesn't automatically run twice by itself, but hopefully that's not too much of a burden.

**Comment by listentwice** [comment]
Fixed
