### ISSUE TITLE
v1.2.9.7 unable to add A4 watermark

### ISSUE THREAD

**Issue by mabacon** [sillsdev/ptx2pdf#269]
v1.2.9.7 
I am unable to add A4 watermark.
I tried several different options, FRT / BCK matter is not selected.

![Screen Shot 2020-10-23 at 16 40 44](https://user-images.githubusercontent.com/34570767/96995876-9cf70980-154e-11eb-919a-e5b0caed8de7.jpg)

**Comment by markpenny** [comment]
It seems to be tripped up by the space in the path (in "Program Files") - because when I copy the same .PDF to a path where there is no space, it works fine. Strange - as I am sure we had this working fine in an earlier version. Will look into it and try to fix it next week.
