### ISSUE TITLE
Loss of cutout for chapter numbers if paragraph ends with non-printing text 

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#27]
I've just noticed that where the 1st paragraph after a chapter number ends with 
\rem, or \sts  (or, I assume, other non-printing markers) the second line of the paragraph overwrites the chapter number, but the 1st one is properly indented.

**Comment by markpenny** [comment]
@davidg-sil Could you please check to see if this is still an issue in the latest version, please? There are a number of re-runs that happen now which may solve the problem. (Or is this just wishful thinking!?)

**Comment by markpenny** [comment]
@davidg-sil I'm wondering if I should (internally, on the fly) build a list of non-printing markers and strip those out from the USFM passed to TeX. Would that solve this issue, or am I missing something?

**Comment by markpenny** [comment]
This has now been fixed in 0.6.2
