### ISSUE TITLE
We can't change a picture's filename inside PTXprint 

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#271]
When I tried to fix the corrupted picture filename that a PTXprint bug messed up, I found that I could not change the picture name! 
This is a bug, right? I think we should be able to change picture filenames.

**Comment by markpenny** [comment]
Yes, David - this is a recent change that I made, and here is my rationale...
If there's something wrong with an illustration, we really want to encourage people to fix/change that in the source (which is Paratext). By doing so, it will then be correct for future jobs/publications. If we make it too easy to fix it "on the fly" here in PTXprint, then people may forget to update their UFM source files and run into problems later.
However, I do recognize that this brings an additional cost (and a level of frustration) for the PTXprint user who wants to quickly replace one image with another *without rebuilding* the entire PicList (at the risk of losing all previous customizations). Is there a middle ground somewhere? For example, put in an unintuitive/less-discoverable way to make that field editable?
I welcome your comments/ideas to improve what we have done, or a strong counter argument as to why it *needs* to go back to being how it used to be.

**Comment by davidc86** [comment]
Yes, changing things on the fly without revising the SFM files is a very valid concern. 

But on the other hand, PTXprint allows us to add pictures entries that aren't even in the SFM files, right? Or change caption text. Possibly these tweaks are just as concerning. 

I think if we are allowing a person to setup up various "versions" of a printout, and so allowing them to tweak anything more than position, size, and anchor location of these entries, then we should also assume they are mature enough to realize these textual and picture file changes need to go back in the SFM if they want these changes to stick around for other publications. 

It might be possible, when a textual change or picture file change is made, to pop up a reminder, "Be aware that no changes in this dialog are not written back into the original Paratext source file. If you want any of these changes to be available in other applications, you will need to make these changes in the source file as well." -- or some such.

(I only caught this issue because PTXprint was duplicating my picture entries whenever I changed an anchor ref. and I just wanted to tweak the picture reference back to the correct filename. That is when I found I could not.)

If we stick with _**not**_ allowing changes to this stuff, then the boxes should be **grayed**. (But I would really prefer just letting the end-user fix stuff right there, and be warned to go back and fix it in the original files too. Otherwise, to fix glitches means rebuilding everything all over again, and that's not pleasant -- or hacking the file outside of PTXprint -- which kind of defeats the purpose of your nice dialog on several fronts.)

**Comment by markpenny** [comment]
OK, I've relented, enabled editing of the filename AND added a Tooltip:

Note that any changes you make to the filename
here will NOT automatically be updated in the
Paratext USFM files. Please edit/fit the figure
information manually in Paratext if you change
things here in PTXprint.

There are still a few things to be fixed regarding what happens when the filename is manually changed, but it will be "back" in the next updated version.

**Comment by davidc86** [comment]
Cool. That is probably the most reasonable approach. If someone doesn't remember to make these changes back in PTX, well, that's their mistake. You are giving them a warning.
