### ISSUE TITLE
Header can't display verse numbers when Marginal verse numbers used

### ISSUE THREAD

**Issue by oj-gamache** [sillsdev/ptx2pdf#273]
Chapter number and colon appear, but the space after the colon is blank.

**Comment by markpenny** [comment]
Thanks for finding this bug. Yes, I confirm that we are also seeing the same behaviour. Will hopefully be fixed soon.
![image](https://user-images.githubusercontent.com/12962708/97255981-c5487600-1876-11eb-8282-f6381d317232.png)

**Comment by markpenny** [comment]
Yes, this is now fixed, and will be available in the next updated release:
![image](https://user-images.githubusercontent.com/12962708/97854350-3350d980-1d5e-11eb-94ca-8bf55588a342.png)

However, the alignment of the left page header needs some help, it seems.
