### ISSUE TITLE
Selecting "Letter spacing" prevents printing

### ISSUE THREAD

**Issue by oj-gamache** [sillsdev/ptx2pdf#275]
After checking the "Letter spacing" option, without changing the default numbers, it won't print, and even after un-checking  the option nothing will print. I have to close PTXPrint and re-open it in order to continue.

**Comment by davidg-sil** [comment]
This semi-responsive user interface is a sign that part of the python code (one thread) has crashed. Did it crash immediately, or did you do something else (e.g. try to print?)

**Comment by mhosken** [comment]
Can you save an archive of your project (see advanced tab with a big create archive button) and send it to me and I'll do some digging.

**Comment by markpenny** [comment]
MH: This one is for you:  (usfmutils is calling ucd.py which assumes the palaso lib is available, but it isn't):
  File "python\scripts\..\lib\ptxprint\usfmutils.py", line 304, in fn
    for (islet, c) in groupby(e, key=lambda x:get_ucd(ord(x), "gc") in takslc_cats):
  File "python\scripts\..\lib\ptxprint\usfmutils.py", line 304, in <lambda>
    for (islet, c) in groupby(e, key=lambda x:get_ucd(ord(x), "gc") in takslc_cats):
  File "python\scripts\..\lib\ptxprint\sfm\ucd.py", line 170, in get_ucd
    local_ucd = UCD()
  File "python\scripts\..\lib\ptxprint\sfm\ucd.py", line 79, in __new__
    res = pickle.load(inf)
ModuleNotFoundError: No module named 'palaso'

**Comment by markpenny** [comment]
This has now been fixed (thank you, MH!) and will be available in the next minor update.
