### ISSUE TITLE
Making PDF fails with cryptic error message

### ISSUE THREAD

**Issue by sewhite** [sillsdev/ptx2pdf#276]
![image](https://user-images.githubusercontent.com/16904461/97211370-56dfb700-1795-11eb-8e93-a53f29cf4ba6.png)

**Comment by sewhite** [comment]
The PDF tool in Paratext has no problem exporting this book to PDF.

**Comment by markpenny** [comment]
@sewhite - If you want us to find and fix this bug/issue, then then most helpful thing you can do is to use the "Create ZIP Archive" button on the Advanced tab and send that to us. This will help us (hopefully) replicate the issue and fix the bug. Either send me the ZIP file or a link to the resulting archive.
![image](https://user-images.githubusercontent.com/12962708/97255794-481d0100-1876-11eb-8200-112b6c2287d3.png)

**Comment by sewhite** [comment]
[AAAP-DefaultPTXprintArchive.zip](https://github.com/sillsdev/ptx2pdf/files/5445858/AAAP-DefaultPTXprintArchive.zip)

I'd recommend you mention that Create zip button on the "How to report bugs ..." on the View+Edit Folders and Links page. I looked for it there when I found the link to Github.

**Comment by markpenny** [comment]
Yes, good point Steve - we'll do that, or perhaps even move the
      button...
    
    On 10/28/2020 3:13 AM, Steve White
      wrote:
    
    
      
      AAAP-DefaultPTXprintArchive.zip
      I'd recommend you mention that Create zip button on the "How to
        report bugs ..." on the View+Edit Folders and Links page. I
        looked for it there when I found the link to Github.
      —
        You are receiving this because you commented.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/sillsdev/ptx2pdf/issues/276#issuecomment-717272550",
"url": "https://github.com/sillsdev/ptx2pdf/issues/276#issuecomment-717272550",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    -- 
ɦuuəd ʞɹɐw ● Language Technology Senior Consultant ● South Asia Group ● SIL International  ● Based in NZ

**Comment by davidg-sil** [comment]
Sorry for the delay in replying. I'm not supposed to be doing much on this today, but from a first look at the page before it crashed :
![image](https://user-images.githubusercontent.com/58848232/97705109-32008200-1abc-11eb-9ab1-862fbe97298e.png)

Then my guess was that it's got almost 20 verses of text that it's trying to align with nothing on the other side, that's almost a page-full. 
It doesn't cope with that situation very well at all at the moment:  it detects one side of the page is a long way from full and tries to pull in more text and there isn't more it can pull in, so it typesets what it can and detects the page is a long way from full.... you get the idea. The "25 dead cycles" error is the 'let's not do this forever' check.

I also noticed that if the paragraphing of the texts had made it possible to align the breaks on the English side,  then it wouldn't have entirely nothing to align. I did a quick find find all lines with 0 or 1 word on them after the verse number and replace the end of line with \\p  

Not too hard using my favourite editor, `vim`: 
```
:g/\\v \d* ?[^ ]*$ s/$/^M\\p/
```
(To get the ^M, that's a CTRL-V CTRL-M)

Doing that allowed the job to run to completion.

**Comment by davidg-sil** [comment]
Enhancement: make the diglot code more robust to testing input such as this.

**Comment by sewhite** [comment]
Wow, I had no idea I was doing a diglot. But turning off diglot did solve the problem. 

The diglot box was checked from the last time I used PTXPrint version 1.1 some weeks ago.

**Comment by sewhite** [comment]
So a better error message would have been "unable to make diglot of AAAP and zzTest9a, the content cannot be aligned."
I would have seen that, checked the diglot setting and turned it off.

**Comment by davidg-sil** [comment]
Well, yes, but that error message is internally generated from the XeTeX engine. All **it** knows is that it's been around the output loop 25 times without making any pages. For all it knows we could be trying to print an origami fish or Beethoven's 5th.

**Comment by markpenny** [comment]
Yes, we're making some improvements to the error reporting messages, and I've also added a button on the newly named "Links & Help" tab as seen here:
![image](https://user-images.githubusercontent.com/12962708/97926436-ff120300-1dc7-11eb-8e5b-ebb15a11eb3b.png)

**Comment by sewhite** [comment]
I appreciate having that button for making an archive on the Links and Help page. And the new summary makes several steps in the right direction.

![image](https://user-images.githubusercontent.com/16904461/98121123-df88e200-1e7c-11eb-93d9-1a65e21ed374.png)
Two changes I would suggest:
1) Typo!  "Sory!" > "Sorry!"
2) add something like "Might you have selected a diglot in a previous session and PTXPrint has remembered that setting? Check the Diglot page to see if it is selected."

**Comment by markpenny** [comment]
Thanks @sewhite for picking up my typo and suggesting additional wording. I've adapted it as follows:

Sorry! XeTeX was unable to complete the typesetting.
* If creating a Diglot, ensure both texts can print successfully
  before merging them as a Diglot print. And ensure that there
  aren't any large chunks of missing text in either of the projects.
* Also check that you haven't inadvertently left certain settings on
  from a previous session (Pictures, Diglot, Borders - which will show
  in blue if these features are currently enabled).
