### ISSUE TITLE
Output fails with complaint: Illegal unit of measure (pt inserted).

### ISSUE THREAD

**Issue by viverechristus** [sillsdev/ptx2pdf#277]
In two different configurations, I'm getting similar (but not identical) problems. Both are connected to units of measure. Here's one, related to \r (the other complains about \s -- same text, but different configuration).

The relevant part of the log:

```
Baselineskip for p undefined, set to 18.0pt
topskip=18.0pt
\openout0 = `ptxprint-Default-MATJraKhmr.parlocs'.

(no adjustment list "../shared/ptxprint/Default/AdjLists/41MATJraKhmr-Default.S
FM.adj" found)
(no picture list "41MATJraKhmr-Default.SFM.piclist" found)
(./41MATJraKhmr-Default.SFM
! Illegal unit of measure (pt inserted).
<to be read again> 
                   <
\p@ram ->4 <
            -4 is the value set in usfm.sty
\p@rstyle ...fhe@dings \nobreak \fi \vskip \p@ram 
                                                  \verticalsp@ceunit \fi \re...
l.12 \r
        (លុក 3:23-38) 
Here is how much of TeX's memory you used:
```

I have turned off the extra stylesheets in Advanced, and I'm not including pictures or doing anything unusual. I have not edited the default settings in the new Styles tab. Our USFM.sty is (I think) "out of the box".

I'll send a zip by email.

Josh

**Comment by davidg-sil** [comment]
Did you edit that  log, particularly the '4 is the value...' bit?
If not, well.... that has no business being in a parameter!

**Comment by viverechristus** [comment]
No, that's a straight copy paste job. Do you want a full log?

**Comment by davidg-sil** [comment]
I think I've seen enough of the log... I'd like to see any style files the job calls in, though, or at least, the line where that comment is from.
My guess is that someone has put a comment in the file after what they consider the value, but the code is taking the whole line after the
marker as the value. 
The question from me, thus is actually whether the comment is user-generated or machine-generated....

**Comment by viverechristus** [comment]
> I think I've seen enough of the log... I'd like to see any style files the job calls in, though, or at least, the line where that comment is from.
> My guess is that someone has put a comment in the file after what they consider the value, but the code is taking the whole line after the
> marker as the value.
> The question from me, thus is actually whether the comment is user-generated or machine-generated....

Do you need anything that wasn't in the archive zip that I sent by email? The job shouldn't be calling any extra style sheets:

![image](https://user-images.githubusercontent.com/915182/97520321-8416aa00-19cd-11eb-811d-845c16f1f188.png)

**Comment by davidg-sil** [comment]
It probably was in the zip file, but I don't get the support emails...

**Comment by davidg-sil** [comment]
It probably was in the zip file, but I don't get the support emails...  11 hour time differences don't help either.

**Comment by davidg-sil** [comment]
OK, I have the zip file. 
I see the following in your [project]/shared/ptxprint/Default/ptxprint.sty:

![image](https://user-images.githubusercontent.com/58848232/97674254-e20ec480-1a95-11eb-9871-8324e05138b4.png)

Without rewriting the macros to allow multi-word input on some lines but not others, there is no way for the code to deal with such corrupt input. 

I have checked the code history, 'is the value' was never in any part of the code, so I think it must 
have been a bad manual edit of some style file in the project's history.

The following seems to deal with it:
1) close ptxprint (skipping this step doesn't work, ptxprint seems to remember the file contents).
2) edit the above-mentioned file and remove the extraneous input
3) restart ptxprint.

If this doesn't solve it, then I would assume the offending problematic file is still on your computer, probably called something-or-other.sty

If you know/suspect who might have corrupted the file, please let them know that comments should
be preceded by ```#``` (in style files)  or ```%``` (in style files or tex files).

**Comment by markpenny** [comment]
@viverechristus - is this issue now resolved for you? If so, please close it.

**Comment by viverechristus** [comment]
It is resolvable, but I wouldn't consider it resolved. Sometimes in a stylesheet I like to comment out a line and then give the reason, as in:

`%\SpaceAfter 4 <-4 is the value set in usfm.sty`

When PTXprint runs, it puts in a linebreak after `%`, so that the commented out line becomes active. This seems like a bug to me. Or maybe I'm commenting lines out incorrectly?

And I'm afraid I'm still not clear on where a Configuration's ptxprint.sty is coming from, so I'm not sure whether I need to remove all commented lines just from THAT stylesheet, or from a stylesheet in the printdraft folder, or exactly where. Is each configuration's ptxprint.sty being created fresh (from some source or other) each go? I now have so many .sty files in various places, I don't know which one does what, which one is considered a "master" that gets pulled from to create working stylesheets, etc.

Thanks for your follow-up with this. (Sorry for the delay replying. We just made a temporary move to Phnom Penh for my wife to give birth, so the last week I've been away from PTXprint.
