### ISSUE TITLE
(ptxplus / ptxprint) footnotes vanish under some circumstances

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#28]
It seems that the ptxplus code merged in with commit ` 300c27aafed0dc3c4 ` broke footnote handling in at least this situation: a single page book (e.g. 2John) where the text reaches the bottom of the page and there is not space for the final paragraph [Edit: and the footnote].

**Comment by markpenny** [comment]
Fixed and will be in Beta 0.4.0
