### ISSUE TITLE
Poor margins with Chinese text

### ISSUE THREAD

**Issue by sewhite** [sillsdev/ptx2pdf#281]
Some lines go off the right edge. 
In double column layout the issue is even worse.

This test project has the first 14 verses of Jude from the CU2010T resource.

[Ctt-DefaultPTXprintArchive.zip](https://github.com/sillsdev/ptx2pdf/files/5467204/Ctt-DefaultPTXprintArchive.zip)

**Comment by markpenny** [comment]
Have you set the script for the language? It is possible that xetex isn't
recognizing it automatically, but if you set it manually, it should work.
Mark

**Comment by sewhite** [comment]
Setting the script to Han Traditional doesn't solve the problem. 
[Ctt-DefaultPTXprintArchive2.zip](https://github.com/sillsdev/ptx2pdf/files/5475875/Ctt-DefaultPTXprintArchive2.zip)

**Comment by markpenny** [comment]
Thanks @sewhite  I forgot to mention that there is another setting which also needs to be used for some scripts (highlighted below):
![image](https://user-images.githubusercontent.com/12962708/97920870-fc5ee000-1dbe-11eb-99f6-36afa1c04457.png)

**Comment by sewhite** [comment]
Line break locale does fix the problem. Is this setting documented anywhere? I would never have known it existed except for your comment.

**Comment by markpenny** [comment]
Until now, most of the documentation is aimed at highly technical help for people wanting to use the XeTeX macros directly. So at the moment there is practically none existing for the PTXprint UI. However, there are tooltips on almost every control explaining what the feature is for. I was hoping that it would be enough to do so, but increasingly we are getting requests for more documentation. I think one of the best forms of documentation is a pair of before and after images (this is what it is like before the option is enabled, and this is what you get after it is enabled). This would also make it less work for anyone localizing the help into other languages - as it would be built in, and the before/after images would speak louder and clearer than any prose.
