### ISSUE TITLE
I cannot actually attach files by pasting into this form

### ISSUE THREAD

**Issue by sewhite** [sillsdev/ptx2pdf#285]
Maybe this is a Github issue, and you cannot fix it. But attaching files is awkward.

This form says I can attach files by "dragging & dropping, selecting or pasting them". I have tried copying a file in File Explorer and pasting in here, but that does not attach it. An "attach file" item on the toolbar would be great, so I could select my file, but I don't see that. The only thing I find that works is dragging and dropping, which is inconvenient because I usually have my browser maximized, and I have to restore down, then juggle the open windows so I have both the browser and File Explorer visible to drag and drop.

**Comment by sewhite** [comment]
PS, I have managed to paste an image file I copied in Paint, but copying a zip file archive in File Explorer and pasting into a comment box is not working.

**Comment by markpenny** [comment]
@sewhite The best way to send or "attach" a ZIP file is to upload it elsewhere (GoogleDrive, for example) and then share the link here.

**Comment by sewhite** [comment]
Dang! That does work. Nonintuitive UI though.
