### ISSUE TITLE
v1.3.2 Typing in Spinner boxes in Style Tab don't "Take"

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#286]
First noticed in v1.3.1. Still an issue in v1.3.2

Typing in Spinner boxes in Style Tab don't "Take" **_unless I first click on another widget in that style's setting tab_**. 

For example, if I type a value in a spinner box (like change font size) and then click the next Style in the tree, to change its settings, when I look back at the previous Style's settings, the typed-in value in the previous Style's settings has reverted to the original value; the new value was not retained. 

But if I type a value in a spinner box and then click another widget, the typed value "sticks" when I move off that Style's settings tab.

**Comment by mhosken** [comment]
Assuming this is closable along with the other identical issue on the topic. Sigh!
