### ISSUE TITLE
(1.3.1) USFM3 milestones are completely broken. How to fix them and even make them really useful.

### ISSUE THREAD

**Issue by inkeysoftware** [sillsdev/ptx2pdf#287]
For starters, if "Auto-correct USFM" is turned on, PtxPrint 1.3.1 displays the error message "Failed to canonicalise texts due to a Syntax Error" if it ever encounters a USFM3 milestone marker.  The specific reason that follows this error message varies with the context, but it clearly doesn't expect other markers to come between the start milestone and the end milestone, as they often will. Here's what happens if it encounters a verse marker first:

![image](https://user-images.githubusercontent.com/11741571/98124213-1e646b00-1e70-11eb-9077-3c5ecd0c0578.png)

Here's the source USFM for the above, containing the quote milestones `\qt-s |Jesus\*` and `\qt-e\*`.

`\v 8 But right den Jesus know inside wat dey tink. He tell, \qt-s |Jesus\*“How come you guys stay tink bad kine stuff lidat?\v 9-10 I da Real Kine Guy, an I like show proof you guys, dat I get da right inside dis world, fo let da peopo go an hemo da shame dey get fo da bad kine stuff dey wen do. But, easy fo talk bout throwing out da shame -- anybody can talk lidat. But not easy fo do um. Same ting, easy fo tell one guy dat no can move, ‘Eh, stand up an move aroun!’ -- anybody can talk lidat. But not easy fo do um. But now, I goin show proof you guys -- I goin make dis sick guy make strong.”\qt-e\*
`

The other thing you see happening here is that the green italic formatting I've configured for \qt character style is being misapplied to this text, with the `-s |Jesus` being treated as part of the text.

PtxPrint aims to provide character formatting based on quote milestones, but it's hard for me to see the usefulness of this unless there's some way to link formatting to the default attribute ("who"), particularly for that being Jesus. That's really the only practical use case I can imagine in which quote milestones could have a bearing on a print product.

The demands of \wj tagging are extremely burdensome for translation teams, and even more so if the translator wants to pass the schema check. (They must be closed and reopened around every verse number, paragraph break, footnote, cross-reference, figure, section or chapter break, sidebar, etc., and all character styles found within them must be nested with the plus syntax.) It's a system designed for the convenience of the publishing software, not the convenience of the translator. So the logical mechanism for marking the words of Jesus are quote milestones. The [Voice Marking custom tools for Paratext](https://drive.google.com/open?id=1BVTFJeqORi83wPiBKONjWQ6EKWnEEUFm&authuser=dan%40sall.com&usp=drive_fs) insert quote milestones into a Paratext project based on character assignments made in Glyssen, and can do so either for all characters (to facilitate round-tripping the text back to Glyssen accurately) or for Jesus only (to facilitate \wj marking at publishing time without cluttering the text with fragile \wj markers in the meanwhile).

Here's what I'd suggest:

1.  For now, ignore milestones when attempting to auto-correct USFM. The point of milestones is that they don't fit the hierarchy. Maybe later on you could validate that the `\qt-s |Jesus\*` in MAT 5:3 eventually has a corresponding `\qt-e\*`  (probably in MAT 7:27), but closing by matching sid to eid gets complicated and I don't think there's any urgency to support that, as I don't see Glyssen ever generating these, or distinguishing between levels of quote either, for that matter. Any multi-voice audio recording system only needs to know which characters speak when. The extra abilities of the syntax are interesting from a theoretical perspective, but I don't foresee Glyssen ever needing those kinds of details to be tracked. For now, it's enough if PtxPrint simply stops producing bad error messages.

2. I'm glad to see the attempt for PtxPrint to be thorough and include milestones, but actually, I'd have to recommend dropping the milestone-related styles section from the Styles tab until/unless you actually have a use case for it, which would probably hinge on applying by matching attributes, and require additional information, such as whether this style is supposed to apply to all printable content between start and end, such as including section headers, or just to scripture content.  Not all milestones are paired, for that matter. e.g. A user milestone may indicate something like "everything after this point is dodgy". But apart from the special case of `\qt-s\*` markers with Jesus as the "who" attribute and to be applied only to the actual scripture text, I'm not seeing other practical use cases for milestones to affect style formatting in print outputs.

3. Ensure that quote milestones like `\qt-s |someone\*` and `\qt-e\*` don't get misinterpreted as `\qt` character styling. 

4. Automatically convert Jesus' quote milestones to \wj mark-up on the fly. PtxPrint already handles \wj formatting nicely. The VM_PrintDraftChanges.txt file in the [Voice Marking custom tools](https://drive.google.com/open?id=1BVTFJeqORi83wPiBKONjWQ6EKWnEEUFm&authuser=dan%40sall.com&usp=drive_fs) contains the changes you need to add \wj markers in properly, skipping over supplementary content such as section headings, footnotes, sidebars, etc. This file also includes changes to delete quote milestones of either type, so that PtxPrint does not misinterpret them (that is, it fixes the problems of points 1 and 3).

Thanks so much!

**Comment by inkeysoftware** [comment]
Here are the important parts of the code I mentioned. First, the functions that are called:

```python
# Given a matchObject that has matched a \wj ...\wj* run of text, apply further tagging as needed and return the result  
def processWjRun(m):   
    toWrap = m.group(0)  
    toWrap = re.sub(r'\\(w|nd|add|dc|k|ord|pn|png|qt|tl|em|bd|it|bdit|no|sc|rb|wg|wh|wa)\b', r'\\+\1', toWrap) # Adjust nested tags  
    toWrap = re.sub(r'([\s\r\n]*\\(p\w*|mi?|q\d?|li\d?|b)\b[\s\r\n]*)', r'\\wj*\1\\wj ', toWrap) # close and reopen \wj around paragraph breaks  
    toWrap = re.sub(r'(\\(f|ef|fe|x|ex|rq|fig) .*?\\\2\*\s*)', r'\\wj*\1\\wj ', toWrap, 0, re.DOTALL) # close and reopen around these paired markers  
    toWrap = re.sub(r'(\\v \S+)', r'\\wj*\1\\wj ', toWrap, 0, re.DOTALL) # close and reopen around verse markers  
    return toWrap  
  
# Given a matchObject that has matched a start milestone, content to wrap, and an end milestone,  
# transform it by wrapping it in \wj markers as appropriate, and return it all.  
def processMilestoneRun(m): # matchObject m's groups contain the start milestone, content to wrap, and end milestone.  
    startMilestone = m.group(1)  
    toWrap = "\wj " + m.group(2) + "\wj*"  
    endMilestone = m.group(3)  
  
    # We don't want to make changes inside "excluded" content,   
    # such as on footnotes within section headers or on paragraph breaks inside sidebars.  
    # So first we close and reopen \wj tags around the excluded content.  
    toWrap = re.sub(r'((?:[\s\r\n]*\\(c|ms|s\d?|r|mr|sr|sp) .*\n)+[\s\r\n]*)', r'\\wj*\1\\wj ', toWrap) # close and reopen around single-line fields  
    toWrap = re.sub(r'([\s\r\n]*\\esb .*?\\esbe\b[\s\r\n]*)', r'\\wj*\1\\wj ', toWrap, 0, re.DOTALL) # close and reopen around sidebars  
      
    # Now we can process these \wj runs without worrying about accidentally applying changes to excluded content  
    toWrap = re.sub(r'\\wj .*?\\wj\*', processWjRun, toWrap, 0, re.DOTALL)   
      
    # Eliminate empty \wj \wj*  
    toWrap = re.sub(r'\\wj\s*\\wj\*', '', toWrap, 0, re.DOTALL)   
  
    return startMilestone + toWrap + endMilestone  
```
Then, the code that converts the contents of a USFM book (in the variable newText) is simply this:

```python
# Patterns to match starting milestone, content, and ending milestone  
usfm3MilestonePattern = r'(\\qt\d?-s \|(?:Jesus|[^\\]*who="Jesus"[^\\]*)\\\*\s*)(.*?)(\s*\\qt\d?-e\\\*)'  
endnoteMilestonePattern = r'(\\fe [▶◀]\s*\\ft Jesus\\fe\*\s*)(.*?)(\s*\\fe [▶◀]\s*\\fe\*)'  
  
# For each Paratext book to be processed, newText contains the entire USFM contents of the file.  
    newText = re.sub(  usfm3MilestonePattern, processMilestoneRun, newText, 0, re.DOTALL)   # Process USFM3 milestones  
    newText = re.sub(endnoteMilestonePattern, processMilestoneRun, newText, 0, re.DOTALL)   # Do likewise for special endnote representations of milestones  
```

A regex to match all USFM3 milestones (e.g. to safely delete them) is `\\[a-z][a-z0-9]*(-[es])?\s*(\|[^\\]*)?\\\*`

To also delete any special endnote representation of a quote milestone (see Voice Tools' Help file for an explanation), you can likewise safely replace `\\fe [▶◀][^\\]*\\fe\*` with nothing.

**Comment by mhosken** [comment]
Yes milestones are not supported yet. We are working on them. There are a number of angles that these things need attention and none of them are addressed yet. Maybe we can get them into a 1.4.

**Comment by davidg-sil** [comment]
My milestone-test code is mostly functioning (with some edge cases where results are unexpected), at least in the sense that it can apply styles, matches sid/eid, and doesn't crash on what I've fed it so far (very little).

As with categories, I'm assuming that if the user wishes to apply styling based on the milestone they will specify how the milestone should affect each marker individually, rather than making any assumptions.

However, I'm not certain about the style naming.
At the moment, I have this (for styling applied to marker ```\p```):
```
#\qt-s\* ... \qt-e\*
\Marker ms:qt|p
\Color x00FF00

#\qt-s|James\*
\Marker ms:qtwho=James|p
\Color x0000FF

#\qt-s|who="Fred"\*
\Marker ms:qtwho=Fred|p
\Color x007fFF

#\qt1-s|James\* ...  \qt2-s|Fred\* THIS BIT \qt-e\* \qt-e\*
\Marker ms:qt2who=Fred|ms:qt1who=James|p
\Bold
\Italic

#\qt-s|The crowd\*
\Marker ms:qtwho=The_crowd|p
\Font Andika

```

* At the moment, styling only pays attention to the automatic/default attribute. 
* If an attribute is supplied, then the no-attribute styling is never applied *should this change?*
* If multiple milestones are defined, a match is searched in the following order (and the first match wins):
   * `ms:qtwho=INNER|ms:qtwho=OUTER|MARKER` [i.e. both]
   * `ms:qtwho=INNER|MARKER`
   * `ms:qtwho=OUTER|MARKER`
   * `MARKER`

My main questions are:
*  whether always assuming the style-relevant attribute is the automatic attribute is a safe assumption.
*  whether the `qtwho` (etc) after the ```ms:``` prefix makes sense, or if it ought to be ```qt:who``` ```qt_who``` or include some other separator between the milestone mark and the name of the automatic attribute. This format (while redundant if only the automatic attribute is used) is intended to allow the schema to apply to other attributes in the future.

**Comment by davidg-sil** [comment]
I forgot to answer your points, sorry:
1. My thought is that the 'validate usfm' code should make some attempt at coping with stuff it doesn't understand, building a list of "I don't recognise these markers, please check them."  and concentrate on stuff it does understand but which is used wrongly. MH probably disagrees!
2. While I agree that **milestones** mainly affecting formating for qt-s...qt-e, under the present standards, they also make a useful styling-changing option for other pieces of text, e.g. tables of contents  is somewhere we expect to use them. 
The attribute handling has actually been the harder part, and attribute-based styling was an immediate bit of low-hanging fruit that came with attribute handling.
3. Done... well, partially. If there's a stand-alone marker that matches a character class, then the character class will be opened and then closed at the ```\*``` mark.
4. Thanks, but I don't think we need to do this.

**Comment by inkeysoftware** [comment]
Thanks, David! I couldn't quite wrap my head around all of that. I don't know enough to know where these settings go or what they mean. I should back off from the general-purpose discussion of use-cases for milestones, and ask a bite-sized question: I think what I understand you to be saying is that what you have implemented for milestones should be able to apply red color to the words of Jesus. What would a user need to do to achieve that? What settings would need to exist in which file(s)?

BTW, earlier I was thinking that converting quote milestones to \wj styling would require more involved logic than could be achieved with PrintDraftChanges.txt rules, but it's actually possible, just hairy. I've updated my original post above. What I'm really trying to figure out is how to make it easy for users to be able to get red words of Jesus by having milestones in the text instead of all those \wj tags.

**Comment by davidg-sil** [comment]
Hi. This is very much a work-in-progress. Test code exists, but following a discussion between us, I now realises it needs refactoring, and should work on a different basis. If you are feeling brave and are sufficiently technical, you could try pulling 1a91fb1d25d0f0d970, and putting the examples with ```\Marker``` into your favourite stylesheet. But it is a moving target, the mark-up will be changing and it is not ready for the normal user. Please give us at least a week or so before things settle down!

**Comment by markpenny** [comment]
@inkeysoftware - Are you able to test and let us know where things are at with this? What else do we need to change/fix to make it work like you expect it to?
