### ISSUE TITLE
Bug: Character styles nested with plus syntax don't nest

### ISSUE THREAD

**Issue by inkeysoftware** [sillsdev/ptx2pdf#288]
PtxPrint does not handle one character style or special text nested within another using the USFM "plus" syntax for nested styles. It loses the outer style's formatting, even after the end of the inner style.

For example, if the words of Jesus (enclosed in `\wj ...\wj*`) contain transliterated words, these must be nested as `\+tl ...\+tl*` to become italicized while inheriting red color from the `\wj` markers, like this:

`\v 11 \wj “But; you teacha guys tell; ‘If one guy get someting dat he can use um fo help his fadda o mudda; he can tell dem; “I no goin use um fo help you guys, cuz bumbye I goin give um fo \+tl corban\+tl* to God.”’\wj*
\v 12 \wj Den you guys tell da guy no need help his fadda o mudda.\wj*`

Here's what it produces:

![image](https://user-images.githubusercontent.com/11741571/98268110-5d1a2400-1f49-11eb-9fe0-4438b34260c8.png)

Clearly the end of verse 11 (`to God.”’`) should not be coming through black, so that's a bug. 

What about the `corban` part? Is there a place I should be defining the appearance of the nested style, or should PtxPrint be able to automatically combine red and italics for me?

**Comment by mhosken** [comment]
There was a bug that was deleting the + from `\+tl` hence no embedding, etc.
