### ISSUE TITLE
v1.3.2 Cannonicalise Text Error in BackMatter Books 

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#289]
I just downloaded v1.3.2 and ran it without changing anything in my settings.
I'm now getting this error:
![image](https://user-images.githubusercontent.com/65363206/98831127-29d40b00-2409-11eb-997e-a2e844af60c9.png)

and this one: 
![image](https://user-images.githubusercontent.com/65363206/98831186-3f493500-2409-11eb-881e-92670b8f0e90.png)

As best as I can figure v1.3.2 **doesn't like me specifying \zthumbtab field in BackMatter.**

**Here is the first few fields from the original SFM file BAK: "Maps" book:**

\id BAK - Selaru
\h Gambar o Peta
\toc3 Peta
\toc2 Gambar o Peta
\toc1 Gambar o Peta-nare
\zthumbtab PETA
\mt1 Gambar o Peta
\mt2 ti Kitab Lanke
...

**And here is the Final SFM for this book:** 

\id BAK - Selaru
\h Gambar o Peta
\toc3 Peta

\toc1 Gambar o Peta-nare 
\zthumbtab PETA
\mt1 Gambar o Peta
\mt2 ti Kitab Lanke
...

So, the unused \toc2 was removed from the Final SFM.  This isn't a problem, right? My setup of PDXprint doesn't use the \toc2 field, so that should be fine.

Just before this book is the XXB book.
 
If I remove the BAK book from the multiple book list in PDXprint (because it is causing problems), then rerun the Print, PDXprint now flags the XXB book as having the exact same issues as BAK had. 

**Here is the first few fields from the original SFM file XXB: "Read through the Bible" book:**

\id XXB - Selaru
\h Tbaca Kitab Lanke ti Ainke Krala ne 
\toc3 Tbaca 
\toc2 Tbaca ti ainke krala ne 
\toc1 Tbaca Kitab Lanke ti ainke krala ne 
\zthumbtab TBACA 
\mt1 TBACA KITAB LANKE TI AINKE KRALA NE 
\mt2 (Baca Alkitab dalam Satu Tahun) 
...

**And here is the Final SFM for this book:** 

\id XXB - Selaru
\h Tbaca Kitab Lanke ti Ainke Krala ne
\toc3 Tbaca

\toc1 Tbaca Kitab Lanke ti ainke krala ne 
\zthumbtab TBACA
\mt1 TBACA KITAB LANKE TI AINKE KRALA NE
\mt2 (Baca Alkitab dalam Satu Tahun)
...

Again, the unused \toc2 was removed (which is fine).  

I'm not sure if any of this helps anybody figure out why suddenly v1.3.2 fails whereas v1.3.1 did not. 
Is it because I'm trying to set book thumbtabs in the none scripture "back matter"? 

NOTE: just like the SLU "custom.sty" file, the "fntbak.sty" file also includes the following specs for the \zthumbtab field:

\Marker zthumbtab 
\Name zthumbtab - Thumb Tab Abbreviations
\Description Gives a special Abbreviation for use on Thumb Tab
**\OccursUnder id ide c**
\TextType Other
\TextProperties paragraph nonpublishable nonvernacular
\StyleType Paragraph
\FontSize 12

The error says  it has an invalid "occursunder" spec, but it is clearly spec'd here. Anybody have a clue?

**Comment by davidc86** [comment]
I changed all the \zthumbtab fields in the back matter to look like this: 

\rem thumbtab PETA

(remarked them out)

So now when I run PTXprint it throws this error: 

![image](https://user-images.githubusercontent.com/65363206/98837951-98b56200-2411-11eb-900f-b358f8068e57.png)

Which is the last scripture book in the list approved for publication. BUT at least now PDXprint finishes formatting the file and produces a PDF file. The file has no tabs in the back matter. And the tab for 3 JOHN shows up just fine. 

So, 
1) A \zthumbtab field in back matter will crash the Print process. (If PTXprint won't support tabs there, then it needs to at least gracefully handle it when a user puts them there.)

2) The error that is thrown is not correct. The \zthumbtab may not be a standard USFM marker, but it is defined correctly in the custom.sty (and fntbak.sty) files. PT sees it as a defined field now. 

So, I can begin checking out v1.3.2 now that I have a working PDF process.

**Comment by mhosken** [comment]
See now closed #303. Why should I have to type the same thing twice in two issues. Please only use a single issue for a single issue. Thank you!

**Comment by davidc86** [comment]
Hi sorry for repeating the same bug. Now I will update this one instead. 

I am currently working on just ONE book, Mark, and I'm still getting this error (so it has nothing to do with back matter). 

I have checked every single file in the ptxprint folder and **not a single file has "occursunder" in lower case anywhere**. I have checked and a few style sheets have "OccursUnder" as per the norm. I also checked my "custom.sty" and even the standard "usfm.sty" files. Nope. Nowhere.  

But it does have something to do with the \zthumbtab fieldmarker.
Here is how it is normally in Mark: 
![image](https://user-images.githubusercontent.com/65363206/100111900-9fde6600-2e3c-11eb-95a0-f3e175dc205b.png)

But if I change it to:
![image](https://user-images.githubusercontent.com/65363206/100111970-b5539000-2e3c-11eb-8a9e-81104865204a.png)

And then run Mark I get this:
![image](https://user-images.githubusercontent.com/65363206/100112215-f77cd180-2e3c-11eb-9c1e-8b057882b16b.png)

So something is weird!

**Comment by mhosken** [comment]
Sorry about the case thing. My bad call. The USFM parser is now case agnostic when it comes to stylesheet markers. Best send an archive.

**Comment by mhosken** [comment]
The original issue (lack of occursunder) should be fixed. The subsequent different issue of \fig turning up shouldn't happen because there should be no \figs in the sfm since we strip them out don't we? What is happening at line 1173 (as stated in the error message)?

**Comment by markpenny** [comment]
@mhosken I would be inclined to IGNORE all the occursunder settings for FRT and BAK matter books. Or, putting it another way, we should only pay attention to occursunder for SCRIPTURE books (GEN...REV etc.). I think that would take care of these issues, or at least sweep them under the carpet!
The only other option I can suggest is to use FRTBAK.sty for those books instead of USFM_SB.sty as the base.

**Comment by markpenny** [comment]
Discussed with MH and decided that we (developers) should just keep adjusting ptx2pdf.sty to add **id** to the **occursunder** field for whichever markers that require it. Note also that 1.5.7 will be more robust at hiding the false positive "errors".
