### ISSUE TITLE
Add picture checking filtering

### ISSUE THREAD

**Issue by mhosken** [sillsdev/ptx2pdf#291]
There are a number of ways people may want to filter pictures based on checking values, but I would suggest that we might have an invert filter and then various key filters:

- Not checked
- Has unknown values
- Has all unknown values

**Comment by markpenny** [comment]
Added UI items in picui branch (but not hooked up yet). Hoping to make all this available in 1.4

**Comment by markpenny** [comment]
@mhosken I'm not seeing any changes in the list when I change the filter. Something seems to have come unstuck. Also the "Approved and Notes" controls don't seem to be reflecting reality.

**Comment by markpenny** [comment]
Yes - that's looking great now. Thanks.
