### ISSUE TITLE
v1.3.2 I can't UNCHECK the Table of Contents option in my configuration

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#293]
I'm using v1.3.2
I opened my Test configuration and was  setting it up to print a newly approved book. Just one book. So I don't need a table of contents. But, I can't UNCHECK the Table of Contents option in this configuration. I have not noticed this issue before.  

![image](https://user-images.githubusercontent.com/65363206/99022046-f8099400-252f-11eb-9b71-59cb6d3e4b4c.png)

AH! It's a logic bug.
To work around this issue:
1. I checked the box for multiple books (on the Basic) tab, 
2. Switched to the Body tab and saw that the Generate Table of Contents box was not gray, 
3. Unchecked the Generate Table of Contents box
4. Switched back to the Basic tab and reselected my Single Book option.

Might the problem be that my "Single Book" selection (Mark), is not actually in the "Multi-Book" List? (I haven't put MRK in there full list of books yet.)

Anyway, this work-around works for now.

**Comment by mhosken** [comment]
As per the tooltip, one needs to select multiple books (even if there is only one in the list) to be able to change that checkbutton. I agree, that's not how things should be, but it is a workaround.

**Comment by davidc86** [comment]
Okay, if that's then case then, maybe if the user selects a Single book, then no matter what the state is on the Generate Table of Contents box, it should be ignored and PTXprint should NOT print a one line TOC in the PDF. I vote for this being the default behavior for a single book selection.  

As it is now, if we've set up a multiple book configuration with a TOC checked, and then we need to print just a single book, based on all the layout settings already there, we can't get rid of the TOC without jumping through hoops.

So maybe an bug/enhancement?

**Comment by markpenny** [comment]
OK, this now works like it used to (prior to the regression). Thanks for finding the bug. The behavior now is that if you select a single book, it deactivates AND clears the checkbox for the Table of Contents. [Which means that if you are switching back and forth between Single and Multiple books, you would have to remember to turn it back on after you select Multiple books]. If you really did want a Table of Contents for a Single book, then there's nothing stopping you putting just one book in the list of books to be printed! (will be included in 1.3.4)
