### ISSUE TITLE
Cutout position: new paragraph is started for the verse containing the \fig

### ISSUE THREAD

**Issue by KimB2017** [sillsdev/ptx2pdf#294]
When I create a cutout for a figure, the verse containing the \fig is made to start a new paragraph. This does not seem to happen with spanned figs (in single-column text). As you can see, v 8 starts in the middle of a sentence, but it also starts a new paragraph. This \p is not in the Paratext file.
![image](https://user-images.githubusercontent.com/25071218/99027164-93076b80-253a-11eb-9c47-094eb465e574.png)

**Comment by davidg-sil** [comment]
Yes. This is documented. There may be another way, 'borrowing' the way that no-break chapters operate,  but at the moment this is expected behaviour. It is also the reason that the number of lines delay can be specified. i.e. anchor the image at  verse 7 with  pgpos="cl2" in the example given.

**Comment by davidg-sil** [comment]
Hopefully fixed in main branch of code (i.e. next release).

**Comment by markpenny** [comment]
@KimB2017 - Could you please check if this issue is now solved, and if so, go ahead and close the issue (or let us know that we can do so).

**Comment by KimB2017** [comment]
It looks good now. Thanks!
