### ISSUE TITLE
v1.4 Style First line indent values have issues 

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#297]
In every "hanging indented" paragraph style in the style tab (includes poetry, lists, quotes, etc.) I found that the first line was acting very strange, like the -0.2 value was starting at the Page Margin rather than at the Left Indent Margin, which is where it is supposed to measure from. 

I found the only way to fix this was to change the First Line Indent value to something else and then change it back to what I wanted. Only then did PTXprint register the First Line Indent value and use it correctly.   

I had to do this will all the hanging indented paragraph styles to get them to work.

**Comment by davidc86** [comment]
I suspect that the styles are basically unspecified in the ptxprint.sty file, so the indentions don't "take" until I overtly edit them.

I don't think this issue is limited to "First Line" values, but rather any Style setting needs to be overtly set to get it to work. (I.e. it may show up in the Style tab with a particular value, but PTXprint does not use that value until I alter it and then set it back. In essence "initialize" that variable. Hope this helps track it down.

**Comment by mhosken** [comment]
"To get it to work"? If a style settings is not set in the ptxprint.sty then it takes whatever it defaults to from the other files in the chain including custom.sty, all the way back to usfm_sb.sty. So I'm a little confused by why you feel the need for the default value of a style setting to be output in ptxprint.sty. We might be missing something else here.

**Comment by davidc86** [comment]
I just tested this again today with v1.4 and there is some kind of bug in the behavior of the Left Indent and First Line Indent in the Style tab.

I currently have it working, so I'm not too keen on messing with it until I have Mark done. But, when I try to change the settings for say \q1 and \q2 etc. to create nice hanging indented quotation lines, like poetry lines, those lines go "weird". 

Current settings:
![image](https://user-images.githubusercontent.com/65363206/100153933-d931c880-2e72-11eb-9392-e0e591eb8cbd.png)

\q2 is 
L-INDENT: 0.6
F-LINE: -0.2

and so on.

And right now this is working! So I don't want to mess.

But say I wanted to increase the left indention a bit on all of these to say 0.5, 0.7, 0.9, 1.1, and still keep the first line indent to -0.2 on each of these, what I would expect is the whole set of \q paragraphs to look identical but just shift in slightly more on the left side. (This is how it works in Word and LibreOffice.) 

But what happens is the first line shoots off the left edge of the page! As though the First Line -0.2 value is being measured from the edge of the paper (negatively), rather than from the Left Indention of the paragraph itself, as it should be.

Here is how I think it should work (I may be wrong so please correct me): 

![image](https://user-images.githubusercontent.com/65363206/100155405-37f84180-2e75-11eb-93a7-90ff6155ceef.png)

This is just a mockup. The 0 line is the MARGIN for normal text. The 0.2 line is the indention of normal paragraphs. The 0.4 line is the LEFT INDENT for all \q1 paragraphs. The -0.2 First Line Indent should pull the first line of \q1's back to the 0.2 mark. 0.6 is the Left Indent for all \q1 paragraphs. And again the -0.2 First Line Indent should pull the first line of \q2's back to the 0.4 mark.

That is how I have always understood these things to behave. And right now I have PTXprint behaving this way! Woohoo! BUT IF I try to tweak these values, it goes off the rails. 

Hopefully you can replicate this. If not I will try to come up with a repeatable setup.

**Comment by markpenny** [comment]
I realize now that this setting isn't very intuitively named, but have you tried playing with this setting to adjust your indents?
![image](https://user-images.githubusercontent.com/12962708/100156589-0c756580-2f0e-11eb-89b1-f909f8b5d437.png)

I'm guessing we need to make it more explicit that this also affects \q# indentation as well. This is a "factor" so it needs some "try a setting and see what happens" kind of tweaking to get it right. But my guess is that this is a better way to go about what you're trying to achieve than tweaking all the individual styles themselves. Let me know how it goes...

**Comment by davidc86** [comment]
I'm not even sure what that "Paragraph Indentation Factor" is supposed to do. The whole idea of "factor" when dealing with style sheets is foreign to most users. Factoring is approximate mathematical solution to what most people see as a set of "exact" values. People want to say, the indention is exactly 0.25" or 3pts. They have no idea what the calculated mathematical % value would be if they changed this number. So, fundamentally that is a learning curve right there.

I have mine set at 0.5 (I have no idea what that means, but I assumed it meant "half the normal value" (whatever that is!). Anyway it came out looking okay, so I forgot about it. But if you asked me, "How far are you indenting your first lines in normal paragraphs?" In PTXprint, I'd have no clue. Whereas in Word, I could tell you exactly.

Anyway, back to the Style problem I'm seeing.

Here is how it is supposed to look (using q1,q2,q3 indented at 0.4, 0.6, 0.8 and first lines all -0.2):
 
![image](https://user-images.githubusercontent.com/65363206/100256710-177ec480-2f13-11eb-8bd3-18d8a2fe14d3.png)

Here is how it looks if I go through and change q1,q2,q3 to be indented 0.5, 0.7, 0.9, everything else stays the same): 

![image](https://user-images.githubusercontent.com/65363206/100256651-0766e500-2f13-11eb-9ac4-985ddf6b5d7a.png)

The REALLY weird thing is that SOMETIMES these first lines are **pulled all the way back to the page margin**! (It did this yesterday.) But today (same version, same text, no other changes) they got pushed **inward** a huge distance! 

So some part of the Style data is not talking to some other part of the program. I'm scared to do this testing, because I really need those lines to look right! And since this behaves like it is fragile, I always wonder if I'll get back to what I had before.

Anyway, I hope this helps show what I mean. (If I get an example of the leftward misalignment, I'll upload that too.)

**Comment by mhosken** [comment]
PTXprint lies about poetry indents. This should get fixed as part of #315. Closing to move this over to that bug.
