### ISSUE TITLE
v1.3.3 Still no decorations at end of books

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#298]
This feature has never worked for me. Is there some kind of field or code that needs to be added to the SFM files to get this to work? 

I hope not, as this is a "decoration" that we should be able to turn on or off without having to do any damage to the SFM files.

Others seem to get this to work. Even all the other fancy stuff like borders or verse number decorations, etc. But I just wanted to see if we could get a decoration at the end of each book. So far still nothing. Am I not holding my mouth right?

**Comment by mhosken** [comment]
Please do not raise any issues starting with the work Still. Instead update the original issue to say that it is not fixed in whatever version. Can't be bothered to find the original issue. Closing this and all such issues.
