### ISSUE TITLE
v1.3.3 Saving a Configuration to a new name fails to copy the styles

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#299]
Saving a configuration to a new name should give a complete and exact copy of the original configuration.
v1.3.3 fails to do this.
Here is a folder compare between the original configuration folder (Test v132) and the new one (Selaru Publications): 
![image](https://user-images.githubusercontent.com/65363206/99276134-52d61080-27fa-11eb-8269-b67d4f626114.png)

So, except for the name change between the piclist filenames, all the other content should have replicated exactly, right?

You can see in this comparison that the "NestedStyles.sty" file didn't copy at all. (I'm not sure what that's for anyway, so I'm not too concerned about it.) But more concerning is the ptxprint.sty file is EMPTY in the new copy! Yikes. 

It is also a bit confusing that the CFG file is different. (The "Notes" field is deleted when a new configuration is made. That was the only difference.) May I suggest that if the name is changed and then the user clicks Save, that PTXprint retains even the Notes contents as is. Then if the user wants to change the notes, they can, and then hit Save again. This at least would make the two files identical at first.

Finally, I'm also a bit confused why the piclist filename needs to change when nothing else does? It seems to me that the folder name should be enough to distinguish one set of files from another set. The cfg files are just as detailed and picky as the piclist files, so I'm just curious why only that file gets a new name? (NOTE: I did a file compare, and those two piclist files are identical internally, so that is good!) 

For now, I can close PTXprint, copy over my styles from the original configuration, and restart PTXprint.

**Comment by mhosken** [comment]
Don't know what to say on this one. Did you have outstanding style edits that hadn't been saved before you created the new configuration? That's about the only reason I can see for a 0 sized pxprint.sty. The file is copied just like all the other files in the configuration, so if ptxprint-mods.tex came across, so should ptxprint.sty. We'll keep an eye on this one, but will flag it as non-reproducible for now.

**Comment by davidc86** [comment]
Oops, this one is related but unique to the one I just made (#315 )! Sorry. 

This one is a bug I think. Because if there are any unsaved Style settings (or any settings), then clicking "Save" should copy the old folder to the new name, and then SAVE everything currently in PTXprint and flush it to the NEW folder. 

(An alternative method would be to flush everything to the old folder and then copy that folder, but that might not be what people are expecting in the case where they have made settings changes and then changed the configuration name and click Save. I suspect they would view it as a Save As, i.e. it doesn't save out the current tweaks to the old location, but leaves that alone, and writes out all the tweaks to the new named folder.)

Regardless of the method used, I can't see where it would ever be correct behavior to end up with a new ptxprint.sty file of 0, when the original folder had a ptxprint.sty file with content.

I'm not sure if this is fixed yet, as I have not tried making a pile of changes to the style sheet and then flip over to the Basic page, change the name and click Save just to see what kind of style sheet gets saved to the new location.
