### ISSUE TITLE
Italic and Italic Bold fonts not identified correctly

### ISSUE THREAD

**Issue by philleckrone** [sillsdev/ptx2pdf#3]
When I select the project the "Bold" font is correctly identified, but the Italic and Bold Italic fonts are not listed. When I look at the list of available fonts is lists "Oblique"
![Screenshot 2019-11-20 08 06 04](https://user-images.githubusercontent.com/37958474/69243287-c2c2a400-0b70-11ea-80fd-dc1806df262d.png)

**Comment by philleckrone** [comment]
I was running PTXprint-0.2.exe

**Comment by markpenny** [comment]
Phil - this is a strange GTK+ bug/feature. Even though the fonts are labelled as Italic, some of them are showing up here as Oblique (and then not being recognized as Italic :-(  ) We may end up re-doing this area of the code to compensate, but it isn't high on our priority list right now. Watch this space, but don't hold your breath!
