### ISSUE TITLE
v1.3.3 I added a FrontMatter PDF and now my pictures aren't showing

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#300]
Here is the first page with a picture: 
![image](https://user-images.githubusercontent.com/65363206/99295590-9be68e80-2813-11eb-85e1-c4a3baaac860.png)

NOTE: the "large" high-qulity picture files that I need used are TIF. These are located in the project's "SLU\local\figures" folder, not the folder called "SLU\figures" (which has the thumbnail jpg versions of the TIF files). 

I set the folder to be used to the "SLU\local\figures" folder. This folder only contains TIF files.

Here is the Picture settings tab: 

![image](https://user-images.githubusercontent.com/65363206/99300058-1e724c80-281a-11eb-903d-1628f87370b0.png)

Oddly, the "missing" picture has a JPG extension, yet I specifically asked for the High Res illustrations, which JPGs are not. And I list TIF first in the list of extensions, and the folder it is supposed to look into only contains TIF files, exactly matching the Paratext \fig field. What is also odd (and makes it harder to debug) is why the "missing" picture file is called **CN01651.jpg**, when the actual filename is **CN01651B.tif** in Paratext and the figures folder? (i.e. the _extension is changed_ and _the B is missing_).

NOTE: PTXprint says there are 0 missing pictures. Yet NO pictures are shown in the PDF. 

(ALSO NOTE: Earlier today, before I added a PDF file for Front Matter, PTXprint exported this book with pictures just fine, so I'm wondering if adding the PDF front matter file might have some odd domino effect.)

Interestingly, I just changed the "look into folder to "**SLU**" and said, look anywhere in there (which would include the jpgs in the "SLU\figures" folder, but it still doesn't work.

Does anybody know why suddenly the pictures stopped importing into the PDF file?

**Comment by davidc86** [comment]
Bingo!
It IS because I added a front matter PDF file to the configuration!
When I unchecked that check box, and NO other changes, boom, got this:

![image](https://user-images.githubusercontent.com/65363206/99300811-0f3fce80-281b-11eb-9200-f171b6f1321c.png)

**Comment by davidc86** [comment]
Oh wow, okay, I figured out something. If the PDF filename has a SPACE in it(!) then PTXprint will load that PDF file okay, but bombs on all the rest of the pictures! BUT if I remove the SPACE in the filename of the PDF front matter file, then PTXprint loads the PDF Front Matter file just fine, AND includes the pictures too! 

I didn't see that one coming... 

Hope this little adventure has been helpful for somebody.

**Comment by davidc86** [comment]
Well... that wasn't the solution.
Here is the page with the next illustration: 
![image](https://user-images.githubusercontent.com/65363206/99303488-018c4800-281f-11eb-83a4-11da13b05b87.png)

So now the first picture shows up, but all the rest don't. It is beginning to appear to be random.

**Comment by davidc86** [comment]
Okay...
Further progress is being made here.
Apparently I need to "tweak" every single picture, to get PTXprint to "see" it and print it. (I stumbled on this when I was tweaking a box's size--figuring we'd get them to show at some point. Well, bingo, every picture I tweaked, even if going from 100 to 99% was enough to wake up PTXprint to show THAT picture. 

So far each and every picture I have "touched" now shows up. But if I don't tweak something, it is still a box.

**Comment by davidc86** [comment]
Okay... wow... ah, now all the pictures suddenly started showing up again. NO IDEA WHY.
You are reading a blow-by-blow of me trying try various things to get it to work. I don't think I went all the way through "tweaking" all the pictures yet, but apparently whatever I did finally woke up PTXprint to refresh the whole set of pictures.

Any clues? So next time my messing around might be more directed to a real workaround. Glad it's back. Scared to tweak anything now. (Trying to format a real book, rather than just testing.)

**Comment by markpenny** [comment]
Yes, we also found some similar strange issues with Pictures late last night. We'll be working on getting them working more predictably later today, and hope to have 1.3.4 out at the end of the day which should resolve these bugs. Thanks for your time in researching some of the WHY questions.

**Comment by davidc86** [comment]
Great! Looking forward to using that one. (This one is now working too. So, nice.)

**Comment by markpenny** [comment]
Earlier you had asked:

> What is also odd (and makes it harder to debug) is why the "missing" picture file is called CN01651.jpg, when the actual filename is CN01651B.tif in Paratext and the figures folder? (i.e. the extension is changed and the B is missing).


This is because internally we try to keep track of the "base" filename [without the extension and the quality flag (A,B,C)] so that we are able to select/use the right file when creating the PDF - based on user choices of resolution High/Low and file type (JPG PNG TIF PDF etc.).

**Comment by davidc86** [comment]
Thanks for that explanation Mark. I never new what the A, B, C labels were for. I've never seen A labels. And I figured the B was for Black and White, and a C label might be for Color. Apparently not.

V1.3.4 hasn't showed up on the SIL site yet. I'll keep checking.

**Comment by markpenny** [comment]
@davidc86 FYI - internally we work with the "lowest common denominator" for these files, so we use lower cased 2 letters followed by 5 digits (skipping the A/B/C and extension), and can therefore find the best match on the system according to whether the user wants high resolution or low resolution images, or if they prefer images from a particular folder (+/- subfolders). This enables a user to put their low-resolution .jpgs in the draft, and for a high-end typesetter to use the (restricted access) high-resolution .TIF images later on without changing any of the figure definitions.

Could you please check to see if this issue happened to get resolved in 1.3.8 or do we still have work to do in this area?

**Comment by davidc86** [comment]
v1.3.8 Looks good. No problems. and congrats on getting the Pictures tab combined and issues sorted for v1.3.8 release. That tab is looking great and more intuitive!
This issue can be closed.
