### ISSUE TITLE
v1.3.3 Specified font size is not the size that ends up in the PDF file

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#302]
I discovered in tracking down why my printouts from PTXprint looked anemic compared to the same spec'd printouts from LibreOffice Writer. 

I loaded the PDF file from PTXprint into LibreOffice **Draw**, in order to inspect the values assigned to the text (there may be a way to do this in Adobe Acrobat Reader, but I'm not finding it). Here is what Draw is seeing as the attributes assigned to the scripture text:

![image](https://user-images.githubusercontent.com/65363206/99416253-a9108580-28c6-11eb-91a7-2f162e231dc2.png)

So PTXprint is formatting the **11pt** scripture text **_one point size smaller_** than what is specified in the PTXprint style dialog. This must be an odd mathematical rounding error, because when I checked other types of text, I see the same issue in varying degrees. For example, 
I've set the Intro. material to **9pts** in PTXprint, but it comes out as **8.5pt** in the PDF file. 
I've set the xref/footnotes to **8pts** in PTXprint, but they show up as **7.3pt** in the PDF file. 

So this difference in actual font size specs explains the anemic look of my printouts from PTXprint -- the final text **_is_** smaller. 

Is this due to PTXprint going from Point Size to inches and back or some such? Might it be better if everything was stored in some fine-grained measurement? I.e. all values from PTXprint are stored using measurements in PT size (or mm). 

I'm not suggesting that this is what the user sees, because who knows how many points to indent something? or how many points are required to get a 2cm margin? or a 0.75" margin? etc. But I'm just wondering if this font size error might not be a conversion error, and taking the user's input and storing in a finely grained measurement might help avoid this error? (I recall I once complained that the CFG file had values like 1.00000 -- my bad! Now I see why that was needed!) 

Speaking of granularity, I see now where we can't specify 0.75 inches; we have to chose between 0.7 and 0.8 inches, which seems a bit large of a jump (I'm assuming it is in inches, but I don't know for sure.)

And speaking of units of measure, I find the style dialog measurements confusing. I've no real idea what the units are. For example, the "Line spacing" value is 1.0 -- but what does that mean? Is that 100% of some other measurement? It certainly isn't 1" or even 1cm or 1mm or 1pt. So while this might perfectly clear to some, I'm sure many of us are kind of in a fog here. (I read the popup description on "Absolute..." and that helped some, but not totally clear if the spacing is a measurement of base-line to base-line, or base-line above to the top of capital letters below, or from descenders above to capitals below?)

Maybe the various dialog options could display the expected units for each box. 

Left          [    0.2   ]^v  _inches_
margin: 

or 
Left margin: [    0.2   ]^v  
(_inches_) 

Font Size: [    11    ]^v
(_points_)

etc.

Just a suggestion.

**Comment by mhosken** [comment]
How are you setting the font sizes. Remember that font sizes are scaled according to the font size in the layout tab. The actual font size is scaled by the layout font size / 12. Thus if you set layout font size to 11, then choosing a specific style to have size 11 will result in a point size of 11 * 11pt / 12 = 10.08pt. Likewise a 9 size for a style will give you 8.25pt and 8, 7.33pt, which probably fits with what you are seeing.

This is all in keeping with a design of the ptx macros that you can change the basic size of everything by changing that layout font size. If you want the font sizes in styles to equal their point size, then set layout font size to 12.

**Comment by davidc86** [comment]
Interesting. That seems to account for the behavior, and as you say, it is by design. 

But to a fairly savvy user, this behavior is not standard software behavior. Especially if there are no labels on the Styles tab to indicate the values here do NOT specify font sizes but rather a percentage of the default font size (found on another tab). 

To me, if my setting a style's font size to 11 pt doesn't give 11pt in the output, then what is the point? 

It is very opaque to have a 11pt font style specification run through a mathematical equation based on a value not even shown in this style tab, to arrive at a value not reflected anywhere in the UI. Wouldn't it be better to have the "layout" values show up in the Style tab by default, but if the user changes 11 to 14, then that is what they get! Is not that the whole purpose of a style sheet?  

I know of no other software where specifying a font size in the style results in a calculated value other than the one specified. 
In Word and Writer both, if the default font size is 11, but for a title, I specify 14pt, then I get 14pt in the title, REGARDLESS of the default font value. I.e. **the style completely overwrites the default value for any style where the font size is overtly specified**. It is never a calculated value.

PTXprint's current behavior makes it nearly impossible for normal user to figure out how to get 14pt for titles or 9 pt for footnotes. Can the behavior be reconsidered?

**Comment by davidc86** [comment]
Or maybe just don't let us change the "Layout" default font size from 12 (or warn us sternly that changing it makes a mess). Because as I understand what you are saying, if the default font size stays as 12pt, then on the Style tab the "calculated" font size will be the same as the font size the user enters on the style page, right? 

12pt default * 11pt style size / 12 = 11 pt calculated font size

Though I just tried this and changing the Layout font size back to 12 pt gives "almost right" results: 
11 pt style => 10.9 pt  in PDF
9 pt style => 8.9 pt in PDF
8 pt style => 7.9 pt in PDF 
etc.
This is probably close enough, but just curious why it isn't actually spot on 11pt or 9pt or 8 pt.

**Comment by markpenny** [comment]
Hopefully this tooltip on the Style Editor's "Font Size" label will help somewhat:

![image](https://user-images.githubusercontent.com/12962708/99600695-d003be80-2a62-11eb-8f87-95029e5975c5.png)

And on the Font Size label on the Layout tab I have added a tooltip too:

![image](https://user-images.githubusercontent.com/12962708/99600830-1527f080-2a63-11eb-835a-f6a045d3c02d.png)

**Comment by davidc86** [comment]
Nice. That will help a lot. 
In the second tip box I would have warned the user, but your more mellow NZ approach is nice!
Thanks. I hope I didn't hurt feelings. It was just so counter intuitive to every other style system I've used I thought for sure it was a bug. But there must be some reason someone thought a scaling system would be helpful. For me though, I just need to know that my Layout Font Size needs to stay at 12!! (Get's it close enough. Still odd it isn't exact.)
