### ISSUE TITLE
v1.3.8 Still getting a Failed to canonicalise texts

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#303]
Still seeing this each time I try to Print. Clicking okay lets the process continue.

![image](https://user-images.githubusercontent.com/65363206/99704969-1b1fd080-2a67-11eb-97cc-9ff126a31394.png)

The error message says due to syntax error, but I'm not sure exactly what syntax error is causing this nor where, but I suspect it has something to do with the Thumbs tab field. (The custom.sty does specify an OccursUnder field for the zthumbtab field type, but deleting it doesn't help.)

**Comment by mhosken** [comment]
Lowercase `occursunder`? Try `\OccursUnder`. Yes the error message is unhelpful since it's a bug in the style sheet. But we could spend forever making obscure errors meaningful.

**Comment by mhosken** [comment]
This is just a repeat of #289. Please don't open new issues that simply say another issues wasn't fixed in a recent release.
