### ISSUE TITLE
v1.3.8 Chapter numbers are not big anymore

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#305]
Not sure when the change happened, but the Chapter numbers are no longer showing up very big.

They used to show up at around 2-lines tall, and specified to 18 pt. Now I've even spec'd them to 22pt and they look like this:

![image](https://user-images.githubusercontent.com/65363206/99720514-d81c2800-2a7b-11eb-881e-7869536b3b11.png)

The blank area around it looks like it is trying to fill a 2-line spot. But the actual chapter font is not filling the space. Any ideas? Is it constrained by line-spacing?

**Comment by davidc86** [comment]
Here is how it looked just a week ago. 

![image](https://user-images.githubusercontent.com/65363206/99750619-b25c4680-2aae-11eb-9e78-1351a138c681.png)

I'm wondering if somehow a value got set for \c in the Styles that is blocking it from behaving like it used to.

**Comment by mhosken** [comment]
hard to tell without an archive of this print project ;)

**Comment by davidc86** [comment]
This is back to working in v1.4.
Hopefully this is a "fix" and so can be closed.
