### ISSUE TITLE
v1.3.8 Adjusting Main Title's \mt1 and \mt2 space before and after crashes PTXprint 

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#306]
Just tweaked the Space Before and  After values for \mt2 and \mt1 and now PTXprint crashes with this error:

![image](https://user-images.githubusercontent.com/65363206/99721461-457c8880-2a7d-11eb-8731-c104aa81f82a.png)

I set the above and below values of \mt2 to both be 0.5. It worked with other values. It seems it should work with this value too.

**Comment by mhosken** [comment]
Not to deny a bug here, but TeX is complaining that it really wants that value to be an integer. We should fix it to allow floats, but to get you moving forward, keep those values to integers and it should work for you.

**Comment by davidc86** [comment]
I had them as integers. They were 0 and 2. But nonetheless in v1.4 whatever you did I am now able to specify those values and not crash PTXprint. So this looks good now.
