### ISSUE TITLE
v1.3.8 Adjust List Tip Typo

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#308]
The Adjust List Helps Tip has a minor typo: 

![image](https://user-images.githubusercontent.com/65363206/99752939-4fb97980-2ab3-11eb-81ed-7a7bc60c2ccc.png)

Not a big deal. But if people are confused already by a feature, then the help tip says something that makes them think they really don't understand how this works at all!

BTW, these Help Tips are HUGELY useful. Nicely done.

**Comment by markpenny** [comment]
Thanks for spotting that. Fixed. (I like these kinds of easy-to-fix issues! :-)
