### ISSUE TITLE
ptxprint displays a font name as Unicode code points

### ISSUE THREAD

**Issue by sewhite** [sillsdev/ptx2pdf#31]
The font Noto Sans Adlam does not appear in the Pick a Font dialog by its usual name, but by the Unicode Code points of  the letters.  When I select it, the name appears as it should in the main dialog.

![image](https://user-images.githubusercontent.com/16904461/75485308-75787e80-5978-11ea-8910-e65b59cfd75c.png)

Noto Sans Adlam can be downloaded from here
https://www.google.com/get/noto/

**Comment by mhosken** [comment]
Yeh. This and all other font selector infelicities are GTK bugs and there is nothing we can do about those. Sorry about that. My suspicion is that Noto Sans Adlam Regular and friends have no lower ascii in them and in falling back rendering the GTK control is not falling back to a helpful font but simply to codepoint squares. Feel free to raise a bug against GTK on Windows.
