### ISSUE TITLE
\iex marker error

### ISSUE THREAD

**Issue by Kay-Da** [sillsdev/ptx2pdf#310]
I get an error if a heading (\s1 marker) comes after an \iex marker.
It doesn't show as an error in Paratext and is how I want it to be. Is there any way I can get PTXprint to ignore it?

**Comment by mhosken** [comment]
First think very hard as to why you can't use \is1 in the context you have for \s1. For example you may find that \s1 triggers going from intro single column to double column body text where you don't want it to. If that is your intention (You are wanting a subheading to start the body) then check you can't do \c 1 \s1 My heading, which is the conventional markup.
If all these things do not apply and you are really sure you have the right markup and someone else has checked your work. Then you can tell ptxprint that you want to change the standard marker hiearchy. To do this:
- go to the style tab and select the s1 style
- click the edit button (top right)
- add `id` to the space separated list Occurs Under and click OK

That should cause the error to go away. But it won't necessarily fix any other problems you may have for deviating from the standard hierarchy.

**Comment by Kay-Da** [comment]
Thanks. Sorry, most of that is a bit beyond me. Our consultant and typesetter told us to use \iex for the text explaining missing verses e.g. \iex (We have not yet translated 19:9-22.) So when the rest of the chapter has been translated, it's followed by a heading (\s1). Perhaps that's not how \iex was designed? It seems to have worked well for typesetting, PrintDraft, SAB etc. 

How do I save settings in PTXprint?
I tried adding _id_ to the space separated list Occurs Under to this style: 
![image](https://user-images.githubusercontent.com/74755226/100060429-09c63200-2e74-11eb-8815-7a81442181d1.png)

But I get the same error:
![image](https://user-images.githubusercontent.com/74755226/100060403-003cca00-2e74-11eb-85bf-667f1e30cf6a.png)

And when I close and open PTXprint, the setting reverts to how it was. Is there a way I can save it?

**Comment by markpenny** [comment]
@Kay-Da The [official explanation for this \iex marker](https://ubsicap.github.io/usfm/introductions/index.html#iex) leaves me confused because it is within the section for Introductory materials, but the example then shows an \iex at the end of Romans 16! In all my years of working with USFM, I have never come across other examples of \iex  I'm wondering whether a simple \rem Remark would work better for you instead? (But note that \rem lines are stripped out of the final output; but it sounds like you want this to appear in the output).

**Comment by Kay-Da** [comment]
Thanks, yes we do want it to show in the final output. However, I noticed that the printdrafts show the \iex lines across both columns and then start a new page, so it's obviously not functioning under the chapter marker. I'll look into it.

**Comment by mhosken** [comment]
Re-opening discussion on this, because IIRC the USFM3 spec allows one to use intro markers within the text and we don't want to flipflop to single column for such things. Personally I think that using USFM3 in this way is lazy marker design. But it's standard now. More specifically `\iex` is not actually an introductory marker. Grr. Why couldn't they use a better marker for this?
I propose we treat `\iex` as not an introductory marker.

**Comment by davidg-sil** [comment]
Just had a look... Intro / non-intro is currently a boolean, based on 1st letter of the macro. There's no 'neutral'.  Also,  there's no difference in the stylesheet between ```\ip``` and ```\iex``` as far as style type, text type, etc. (both are stlye:  paragraph, text: other) except that ```iex``` has no specified rank, whereas ```\ip``` has rank 6.

If we made it that  texttype other  made no 1col/2col changes, then text without a section title would not switch to 2column. What we *could* do is make it so that texttyle other switches to 2col if it's non-intro but not to 1col.  I wonder how many texts that would break...

**Comment by mhosken** [comment]
I was thinking of either:
- we just say iex is an exception to the i intro rule
- we have a bool that is set at the start of a book that gets cleared after the first intro to non intro transition and from then on if it is cleared nothing is considered an intro marker (i.e. no switching back to 1col). Tricky for modules though.

**Comment by klassenjm** [comment]
Hi,

Not sure if a further contribution is helpful. I'm not offering a solution, just some background.

Years ago (2012), Paratext 7.3 enabled support for a single project 'study bible'. One of the types of content which study Bible authors added to a project was one or more paragraphs as a division or section introductions. It was decided to encourage \ip for these paragraphs (c. [USFM 2.3](http://ubsicap.github.io/usfm/usfm2.5/about/releasenotes.html#about-release-2-35)). That implies that \ip is not just an introduction paragraph for introduction sections which occur before chapter 1. There were some ways \ip was used like this even prior this more formal SB support in Paratext.

I believe `\iex` was initially added to support bridging paragraphs, which could occur in texts like a "shorter Old Testament", where not all sections of the OT are translated, and some bridge material explains or summarizes a missing section.

I agree that it would be helpful to have an example like that in the docs, and not only the example from the end of Romans.

This is just some background. Perhaps it was a mistake to allow / encourage use of any marker beginning with \i after chapter 1? On the other hand, the semantic in mind is that the content in non-scriptural, introductory material.

In the implementation of support for this in one other place (PA, InDesign), there are a set of styles which are based on an "introDefault", and also have a suffix `_book_intro`. The purpose is to allow styling \i markers which occur in the book intro differently from if they occur after `\c 1`.

**Comment by davidg-sil** [comment]
Thanks, that's good info. It implies to me that there may be almost any "introductory matter" after ```\c 1```, and that any single -> double column differences should be triggered by the chapter mark, not ```\ip``` and friends.

 However, this leaves me a little confused regarding modules (whether using the paratext method or some other cut and rearrange method). I would expect that there will be *some* people out there who expect that a mid-module ```\i...``` marker would switch to single column text, and would desire that effect.  Under what conditions would you expect to transition back to single column, if ```\ip``` and other '"introduction" markers are not the trigger?

Is it reasonable to assume that mid-module  ```\i...``` *section titles* should be assumed to mark a  section of text  even in the middle of a module?

**Comment by klassenjm** [comment]
There could be other introductory markers after `\c` - but defacto really, in practice, it is `\ip`, and (it seems rarely) `\iex`. Those are the ones which have been documented and given a specific use case in a common authoring scenario (study Bible section intros). I could imagine in a rather adventurous study Bible development that someone might add `\ili#` (bullet list) or similar in a division / section intro.

I agree - in some publications a single column introduction, a 2 column body layout, but then a switch to single column span for a division introduction may be desired. In some designs, it could be a helpful visual support. For example:

![image](https://user-images.githubusercontent.com/4420391/100627944-ab76d480-32f5-11eb-9712-239a928573c6.png)

"Scripture body" text is always in a double column here. Introductory content can interrupt it. In practice, as I mentioned, I don't think we should expect or encourage use of _any_ kind of introductory material, and the USFM docs [don't encourage that](http://ubsicap.github.io/usfm/notes_study/intros_div.html). Someone will probably have a good use case for a few other things (like lists perhaps?).

In my own exposure to study Bibles in Paratext, if I encountered an `\i` marker within the body text after `\c 1` I would by default assume it is part of a major or minor section division. If the content was rather there as a kind of extended and embedded 'explanatory text' (not presented as a note or 'sidebar') that is something else altogether -- and perhaps raises other questions about what that content is and how to handle it.

**Comment by mhosken** [comment]
This is asking for confusion. On one hand a shirt single \iex shouldn't
flipflop to single column. On the other hand you say it should. The example
for extended study bibles is ambiguous since it is not clear if the
scripture text us in double columns at that point. I inferred it was and
that the \ip there should not flipflop.

I think it was a lazy bad idea to reuse anything at all from the \i set and
would propose we introduce 2 new markers for when people want to add
explanatory text in column (i.e. no flipflop) and reserve \i for contexts
where the user wants to flipflop, e.g. in modules.

Here is a napkin strawman proposal: \ip -> \pe and \iex -> \pex for non
column breaking material. Otherwise use of \ip etc will cause a column
break and single column.

GB,
Martin

**Comment by klassenjm** [comment]
Hi Martin. I'm not trying to say that `\ip` or `\iex` should or should not do one specific thing. I think I'm implying that for some people or projects it will be a design time decision. But, in my view, that does not mean that you could not design an implementation in PTXPrint around one common layout pattern (that all `\i` before `\c 1` are single column, and anything after follows the current layout stream).

Whether it was lazy or not? I'm not sure. In practice, it started many years ago, and there are _many_ existing study Bible projects in Paratext following this. I think there is a case for `\i..` meaning 'introductory' content, and not only content before `\c 1`. But still, at this point, IMHO, it's not likely a workable plan to migrate all SB projects out there to a new marker.

**Comment by mhosken** [comment]
@davidg-sil I agree that we should probably go with a modal approach, except when typesetting modules. So I suggest that we need two flags:
- We are no longer in introductory material
- We can switch back to single column intro material or not
The latter would be set to disable switching for normal files and the opposite for modules. And of course the first flag would reset at the start of each ptxfile.

**Comment by markpenny** [comment]
@mhosken and @davidg-sil  -  do we have any further thoughts on this issue? Is there a clearer way ahead now? Or is this just an unsolvable issue? If so, can you think of workarounds?

**Comment by davidg-sil** [comment]
New code, I'm assuming it's too close to releasing 1.6 to include it, hence it's on it's own little branch.
Assuming book intros are single column, and body text is double-column, the behaviour of the new code depends on a new flag as follows:

```\ReenterIntroOKtrue``` - old behaviour, a marker starting `i` (introductory marker) will start single-column text, unless it's been declared ambiguous like ```\iex``` was as a stop-gap measure (this approach presents its own problems - ambiguous markers will not *start* single-column text at the start of a book either).

```\ReenterIntroOKfalse``` - chapter numbers set a flag ```\intr@done``` to true. Once this flag is set, then all markers are treated as body-text markers. The problematic ambiguous markers are no longer treated as ambiguous, (except for ```\tr```).  The ```\intr@done```  flag is set to false at the start of a book.

I'm not sure what the default ```\ReenterIntroOK``` setting ought to be. It should certainly be set true for modules and false for new non-modules, but changing it for historic projects may break things in unexpected ways.

**Comment by davidg-sil** [comment]
I'm not flagging it as fixed yet, as the code is in a side-branch.
