### ISSUE TITLE
Make Style editor easier to navigate

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#311]
A couple of neat little enhancements to the Style editor would make it easier for users who are unfamiliar with the whole spectrum of markers in USFM
A) add a filter for the left treeView pane which lists all the styles/markers:
  [  ] Only Show Markers Currently in Use by This Project
or if filtering them out is too hard, or makes it even harder to navigate, then it would be good to style the used markers in **bold**.
Note that If we use the bold option, then we would always do that, and wouldn't need a checkbox.

B) Another similar enhancement in this area is a Find option - to help a user locate a less-used marker without opening each category up to see if it is inside. If Find is too hard to implement, then an option to sort markers alphabetically would also be adequate.

**Comment by davidc86** [comment]
YES! These would be very helpful. 
Just yesterday I was trying to find \q1 and remembered it was a "Poetry" kind of paragraph, so I eventually found it. But if there was a type ahead bar at the top and I just put in \q and the list scrolled open to that entry, that'd be sweet!
Also the "Show only Markers currently in use" would be a boon too! Who needs to see SF markers that aren't used in the project?  (Maybe this should be the default.)
