### ISSUE TITLE
v1.4 PTXprint is reordering of figs in PicList

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#312]
This is a bit weird and may not be important, but in comparing changes as I work, I noticed that PTXprint has been changing the order of picture entries in the PicList file for Jonah. And only Jonah! Yeah, weird. Okay, I'm not working in Jonah right now, so I don't know if this reordering has any effect on the printed order, but it just seems weird to me and you might agree.

Here is what I'm seeing from one day to the next (LEFT is NEW; RIGHT is OLD, and which ones get reordered keeps changing too): 

![image](https://user-images.githubusercontent.com/65363206/100116994-5d1f8c80-2e42-11eb-88a0-599a082a89e2.png)

I have manually forced the order back to JON 1.x JON 2.x etc. but the next day several of the figs from later chapters get flipped to the front again. If you need more info, I can test in out on just Jonah. But it is weird nonetheless.

**Comment by markpenny** [comment]
Yes, I confirm seeing this in other projects too. We'll attempt to fix it before publicizing ver 1.4.1 which should be released shortly.
