### ISSUE TITLE
Failed to execute script ptxprint

### ISSUE THREAD

**Issue by philleckrone** [sillsdev/ptx2pdf#313]
I had not used PTXprint for several days (had 1.3.1 installed and it was working the last time I used it)
Today when I tried to run PTXprint I received the message "Failed to execute script ptxprint"

The only thing that I know I have done since the last run is to remove Java (required by OS) and updated my Paratext to the full PT 9.1. This replaced beta 9.1 and 9.0.

I tried uninstalling PTXprint (removing all entries in the registry as well) and then installing 1.4, but still get the same result.

**Comment by philleckrone** [comment]
I uninstalled PT9.1.101.1 and PTXprint worked again. When I reinstalled PT9.1.101.1 PTXprint failed with the same failure.

**Comment by philleckrone** [comment]
Here is the link to the PT 9.1.101.1 installer
http://update.ubs-icap.org/ParatextTest/Paratext_9.1.101.1_InstallerOnline.exe

**Comment by philleckrone** [comment]
On further testing I see that if I have PT 9.0 installed then PTXprint works. However, the full 9.1 installs the Paratext 9 folder in the 64 bit \program files folder. After this installation PTXprint does not work. This is a blocker!

**Comment by davidc86** [comment]
THANK YOU! I have a field colleague who has been having this same "script" error on his new computer when he tried to run PTXprint. Now I know why! He only installed the latest version of Paratext!! (No idea why this matters, unless PTXprint needs to know where the Paratext Projects are being stored, and that is listed in a different place in the Registry for 64bit PT installs?)

**Comment by markpenny** [comment]
@philleckrone Thanks for this heads-up. Much appreciated. I've replicated the problem and fixed it so that it will now work on any of the following versions: 8, 9.0, 9.1
We hope to get 1.4.1 out containing this fix and others in the next day or 2.

**Comment by philleckrone** [comment]
Great
