### ISSUE TITLE
v1.4 Thank you for including "Mirror" on Pictures!!!

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#314]
Wow, cool! I didn't know what this did, so I messed with it. (A tool tip?)
And it is great. It flips the picture horizontally! 
This is pretty important because many of DCC's pictures do not take into account the dirty Left-Hand culture. Because of this, we had two pictures in Mark that were "awkward" where Jesus  helps up the girl from her bed (after she come back to life), and where Jesus is putting his hand on the blind man's eye. In both cases, DCC has Jesus using his LEFT hand! An insulting thing to do. (Jesus being who he is can get away with this, but it still takes people aback!) 

So doing this: 

![image](https://user-images.githubusercontent.com/65363206/100278400-c67ec880-2f32-11eb-92b3-109a76b5a104.png)

Gives us this: 

![image](https://user-images.githubusercontent.com/65363206/100278449-deeee300-2f32-11eb-9285-312febd57e3f.png)

And likewise here: 

![image](https://user-images.githubusercontent.com/65363206/100278514-fe860b80-2f32-11eb-8f40-2aebe786226f.png)

Sweet! And very convenient. I realize it is probably designed for making it so picture look out from the gutter, but for us, selecting "BOTH" means it can elegantly flip a picture that is awkward culturally!

**Comment by markpenny** [comment]
@davidc86  Perhaps we should have a list of pictures which people around the world have identified as being "insensitively LEFT-handed" and somehow flash up a warning on those "You may wish to mirror this image due to the left hand being used..."

But before that, an appropriate Tooltip or two will possibly help alert people to this option. Good suggestion.

**Comment by markpenny** [comment]
![image](https://user-images.githubusercontent.com/12962708/100294265-318bd600-2feb-11eb-93fb-86db03952684.png)

and the Dropdown tooltip spells that out a bit more explicitly:
![image](https://user-images.githubusercontent.com/12962708/100294307-45373c80-2feb-11eb-9896-d1eb0bd03117.png)

**Comment by davidc86** [comment]
Cool! You just added that! Cuz my copy doesn't have that.

**Comment by markpenny** [comment]
Yes, coming soon...
