### ISSUE TITLE
Request: Add "© David C. Cook" text to his pictures

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#316]
This requirement may have changed, but last I heard, David C. Coook now has requested that a generic copyright can be used in the front, like "**All other illustrations are copyrighted by the © David C. Cook Foundation and used with permission.**" 
BUT they also are asking that each of his illustrations have "**©David C. Cook**" put on them in small print somewhere.

This is doable when we used Word, because it has nice text box capabilities. (PDF much less so) 
I have thought of putting it directly into the TIF file, but then when it gets resized the text suffers, whereas overlaid as a text box, the "©David C. Cook" always looked **_crisp and readable_**. And embedding the text on the picture means we can't use the Mirror feature of PTXprint! 

Anyway, I imagine this is a painful request. But just wondered if it might be possible to do it? This could be in micro font like 4pt and done like a "caption" just underneath the illustration, although of course an ideal solution would be to overlay white space on the bottom of the illustrations with a transparent text box.

So that's the issue and the request. If this requirement in no longer necessary, that'd be great news. But until I hear otherwise, I'm assuming this requirement is still in force.

**Comment by davidg-sil** [comment]
Just writing the figure's copyright text in, say,  the top left-hand corner of the picture box is 'fairly simple', however for 'real world' pictures there would need to be quite a few controls added to the picture definition / globally e.g.:
1. point size / font (global)
2. position
3. rotation?
4. Is there a background box (or not).
5. do this or not (global?)

**Comment by mhosken** [comment]
How about a marker either one we pick or they pick and yet another fig field?

**Comment by davidg-sil** [comment]
I think position and maybe rotation / background box  have to be setable  per-image, but agree that font styling etc. should be a marker.

At the moment I'm drafting code with these extra fig fields:
* credit  - the text
* creditrot - rotation:  0, 180, +/- 90 degrees relative to normal text. (I'm thinking that 180 might be needed for the 'Right-hand edge' on a rotated map)
* creditpos - top-outer side of the image, etc. - I'm assuming this must be flexible to avoid putting the credit on someone's nose,  etc. and wonder if tl(top left), bc (bottom,centred) etc.  give sufficent  control, or ifanyone will ever need to specify something like 10%  in from bottom-left.
* creditbox - Should this just be a boolean, drawing the colour from the stylesheet?  e.g. turn on for a dark image  to specify a white box, but for a mainly-white image, but leave off for a mainly white image to avoid cutting chunks out of it. Or should it be a multiple choice (creditbox="1") to pick one of several stylesheet-defined colours (but  this probably  breaks the stylesheet editor), or should it be a full RGB string to perfectly tone / contrast with the image? In which case don't we also need font colour control?

I think that for the more complex creditbox options above, I'm leaning towards ```credtstyle="red2"```  where that picks a different stylesheet entry. 

I'm assuming that styling will be something similar to other attribute based styles.

**Comment by davidg-sil** [comment]
See [figures.md](https://github.com/sillsdev/ptx2pdf/blob/master/docs/documentation/figures.md#credit-attributes) for current documentation of how it ought to work. I ended up overloading `x-creditbox` so it could be a specific colour, `true`, or a style name, rather than adding yet another figure parameter.

**Comment by davidg-sil** [comment]
Support from python will eventually be needed...

**Comment by markpenny** [comment]
We're working on integrating this into the UI. The Pictures tab now has a "Credit Overlays" tab where users will be able to specify the various options - position, size, background, etc. It has yet to be activated, but we hope to do that soon.

**Comment by davidc86** [comment]
Wow, very cool! Looking forward to this!!
Now I won’t have to feel guilty for being slack in making small run PDFs without the appropriate labels.
-David

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by davidc86** [comment]
So, is this supposed to be working now? Or is it still grayed out on purpose in v1.5.10?

**Comment by markpenny** [comment]
We're working on it now, and hope it will be in 1.6 - but even so, there will be room for improvement, I'm sure.

**Comment by davidc86** [comment]
Thanks! Good to know. And there always is room for improvement in every endeavor. Still looking forward to it! Especially if it makes it possible to put vector fonts (not raster) on the pictures, this will make for a much nicer looking result and save hours manually preparing the illustrations.

**Comment by davidc86** [comment]
Very, very, sweet implementation this! Much appreciated.
