### ISSUE TITLE
Hanging poetry verse numbers also does it for \m?

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#318]
When I apply hanging poetry verse numbers, it also seems to hang the verse number for \m. That actually puts the verse number into the margin (whereas poetry is indented, so the verse numbers don’t go out into the margin). Here’s what I’m seeing:

![image](https://user-images.githubusercontent.com/14953913/100334330-ed410b80-2fd3-11eb-9d02-a508f1f2d4f1.png)

This could be a problem if I have a border around the page, for example. Why is \m being considered poetry?

**Comment by mhosken** [comment]
Can you send an archive of that book? TIA

**Comment by jeffheath-sil** [comment]
Is there a post somewhere that explains how to send the archive (i.e. what to include, zip file?, how to send it, ...)?

**Comment by markpenny** [comment]
Yes, the very sparse documentation needs to get an overhaul. BUT we are also putting a LOT of effort into making things discoverable within the User Interface (like this shows below):

![image](https://user-images.githubusercontent.com/12962708/100481849-60748a00-315a-11eb-8e73-ea2b51e633b1.png)

**Comment by jeffheath-sil** [comment]
sending archive to support email

**Comment by mhosken** [comment]
The fault is that when we stop the para styles with hanging verses, we don't actually turn off that the next verse should hang. Fixing that fixes the problem which is that the paragraph after a paragraph that should hang verses, continues to hang the first verse when it shouldn't.

**Comment by jeffheath-sil** [comment]
This sounds sort of like a past-tense fix... Will this likely be in the next release?

**Comment by mhosken** [comment]
will come in next release, regardless of number. So whatever gets released after 1.4.1, I assume 1.4.2

**Comment by jeffheath-sil** [comment]
I've tested 1.4.2, and it fixes this problem. Thank you!
