### ISSUE TITLE
Separate footnote caller

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#319]
When I use a verse number decorator, I normally want footnote callers to not have the decorator. I've tried to implement that with styles, but there are number of things that I seem to have messed up.

I didn't really know what I was doing, so I tried typing "fcaller" into the Caller Style of \f, without having created the style first. Then I tried to get rid of it, but I'm still getting this error on the first footnote in the text:

![image](https://user-images.githubusercontent.com/14953913/100514570-1dc0ab00-3176-11eb-977e-783e46b544da.png)

Then I noticed the Add button, so I went to the \v style and clicked Add, and tried to make a new style called fcaller. I entered info in the dialog, but OK or Cancel didn't make the dialog go away, and it didn't seem to create the style (I don't see it in the list). Now when I try to click Add it just gives me a small empty dialog.

Count on me to find the edge cases... :-)  I'm sending an archive to ptxprint_support.

**Comment by jeffheath-sil** [comment]
I haven't had any luck with using the Add button to create a new style.

But I was able to copy and paste from my manual XeTeX style file the following lines, to get more or less what I wanted in a separate footnote caller:

\Marker f
\FontSize 10
\CallerStyle fcaller
\NoteCallerStyle fcaller
\CallerRaise 1pt
\NoteCallerRaise 1pt
\BaseLine 10.00pt plus 2pt

\Marker fcaller
\Endmarker fcaller*
\Occursunder None
\TextProperties 
\TextType Unspecified
\StyleType character
\Superscript 
\FontSize 9

**Comment by mhosken** [comment]
The whole of the caller references was a bit of a dog's dinner. Hopefully this has cleared up the mess.

**Comment by jeffheath-sil** [comment]
This seems to be better - when you add a decoration to verse numbers, the footnote callers don't end up with the same decoration.

But how do you set the style for the footnote caller? The f...f* style has blank "Caller Style" and "Note Caller Style" fields. What style is it actually using? It seems to be a superscript, when the verse number with decorator is no longer superscript. If I create a new style fcaller, using similar parameters to verse number, and put that in the Style fields, PTXPrint fails to build the PDF:

(./42MRKTT1-Images.SFM
! Undefined control sequence.
<recently read> \fcaller 
                         
l.19 \v 1 \fcaller
                  *Di hi bichaarat Isa al-Masiih Ibn Allah. Wa l-bichaara badat


(By the way, I think that "Caller Style" in the UI should be called "Text Caller Style", to differentiate from "Note Caller Style".)

**Comment by mhosken** [comment]
Note if you want the main text caller to be different from the note caller you have to set both caller and note caller to appropriate styles, otherwise one defaults to the other.
