### ISSUE TITLE
Custom Script

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#320]
There is no pop-help for the Custom Script options. What do start and end mean? Before/after PrintDraftChanges is applied? And it would be helpful, maybe on the PTXPrint Community board, to have a few simple example scripts. Because I'm not sure what the inputs/outputs would need to be for that script. Just stdin/stdout? I'm thinking something like this in Python:

```
import fileinput
for line in fileinput.input():
    # make changes to line
    print(line)
```

Does that work?

**Comment by jeffheath-sil** [comment]
Nope that doesn't work:
![image](https://user-images.githubusercontent.com/14953913/100517436-cc6ee680-318a-11eb-9495-7ae2d5fac98d.png)

Although that looks more like custom script processing doesn't work at all...

**Comment by davidg-sil** [comment]
It has to be executable. Linux uses its normal #!/path/to/interpreter  to run scripts. I guess for windows that might mean you need a batch file, maybe?

**Comment by mhosken** [comment]
the basic command format is PROG inputfile outputfile

**Comment by mhosken** [comment]
Of course, now you have to tell us *why* you need to run an external program and why a list of masterfully written regexps can't meet all the needs of everyone, ever!

**Comment by jeffheath-sil** [comment]
Feeling sheepish... but I don't know how to apply regexps to a PTXPrint job. Can you enlighten me?

**Comment by jeffheath-sil** [comment]
I just noticed that the default PrintDraftChanges.txt has some RegEx characteristics, like using \1 and \2 in the replacement string. Are you telling me that that file implements full RegEx syntax? If I'm not mistaken this file used to just allow simple replacements. This is a big help, and I don't have to use an external program now!

**Comment by markpenny** [comment]
Yes, that's right. You've got a whole lot of power in PrintDraftChanges.txt to do some clever magic with regex. You also have the "within xyz...pattern" do "a" > "b" - which makes some complex complex rules much simpler.
Here's [a good place to learn some pretty clever things](https://docs.google.com/document/d/1QOwKXPrzaPdHxB_AVhry_-JDWDiN-qm3jY68Ep6PyrI/edit#heading=h.ckb3g27tmfea) that can be done within [PrintDraft]Changes.txt

**Comment by jeffheath-sil** [comment]
It would be helpful if the pop-up help for the PrintDraftChanges file indicated that the changes file can use RegExes and maybe even indicate what flavor of RegEx is used. What flavor would that be?

**Comment by mhosken** [comment]
the python module `regex` as also used by Paratext.

**Comment by jeffheath-sil** [comment]
I can't think of an example of how you would use the `in` keyword in a replacement. Can you share a simple example?

**Comment by jeffheath-sil** [comment]
Oh, I'm wondering if you mean the `in` keyword as described at the bottom of this page:
https://support.paratext.org/t/how-do-i-apply-consistent-changes-to-the-text-when-creating-output-with-print-draft/171

Not the `in` keyword of Python. Is that correct?

**Comment by jeffheath-sil** [comment]
@markpenny Duh, I completely missed your post with the pointer to the Google doc. That answers my questions.

**Comment by mhosken** [comment]
Use PrintDraftChanges.txt. Same as for PA. See advanced tab. Turn it on for
your job and click edit. I'm guessing you'll get something that should give
you a leg up usually with smart quote support. Ask again if we need to
write a tutorial.

GB,
Martin
