### ISSUE TITLE
Failed to canonicalise texts - handling verse number ranges with decorations

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#321]
I'm not sure if this is a problem with PTXPrint, or a problem with my data, but I'm not sure what to do.

I am using verse number decorators, like this:
![image](https://user-images.githubusercontent.com/14953913/100719209-9fa21580-33bc-11eb-9462-b97cef760fd8.png)
(Thank you for implementing verse number decorators!) But when there is a verse number range, that entire range can't fit into the decoration, so I want to separate it into two verse numbers, with a hyphen in between them.

With code stolen from my previous plain XeTeX projects, I define this macro in ptxprint-mods.tex:
`\def\verserange{\kern-0.18em\raise0.09em\hbox{-}}`

And in PrintDraftChanges.txt (which I now know can handle RegExes!), I change the verse range with this:
`'\\v (\d+)-(\d+) '  >  '\\v \1  \\verserange\\v \2 '   # Change verse ranges into two separate verse markers`

This changes the SFM to look like this:
`\v 9 \verserange\v 10 Kooko pa ay ...`

When I print, it produces exactly what I want:
![image](https://user-images.githubusercontent.com/14953913/100719837-72099c00-33bd-11eb-8cb8-79cd20a20d8e.png)

But it also gives me this error message:
![image](https://user-images.githubusercontent.com/14953913/100718423-9b292d00-33bb-11eb-90ff-849f5853dc04.png)

I assume the canonicalization is trying to make sure that markers are in the right places. If I remove the insertion of \verserange, the PDF output just puts the two verse numbers next to each other, and there is no canonicalization error. But with the \verserange inserted, it gives the error. I don't understand why the addition of those few tokens makes the second \v into an orphan marker. It seems like the canonicalization test isn't working quite right. But as I said, the output looks fine, so it doesn't look like it will block me from getting my output.

**Comment by mhosken** [comment]
What you will be wanting is a milestone for your `\verserange`. But we don't support those quite yet. Instead you can use an empty character style: `\verserange\verserange*`. The parser is complaining because you start a `\verserange` character style (or paragraph style) and never close it and so try to fit a `\v` inside your `\verserange`.

Nice hacking though :)

**Comment by jeffheath-sil** [comment]
I can't quite get this. I believe I have to create an empty character style, maybe like this (in ptxprint-mods.sty):
````
\Marker verserange
\OccursUnder v
\Endmarker verserange*
\StyleType character
````

But then am I supposed to put the ending marker into the text as well?
`\v 9 \verserange\verserange*\v 10 Kooko pa ay ...`

That just runs the macro twice (basically superimposing the 2 hyphens over each other), then adds "*" into the text:
![image](https://user-images.githubusercontent.com/14953913/100731331-894f8600-33cb-11eb-923b-e130d10a3d32.png)

I've tried various combinations, like not using \Endmarker, not inserting \verserange* into the text, but I always still seem to get some sort of error. In fact, even with \verserange\verserange* in the text, I still get this error:

![image](https://user-images.githubusercontent.com/14953913/100731561-d6335c80-33cb-11eb-92af-2f068ffb12b0.png)

Any suggestions?

**Comment by davidg-sil** [comment]
What happens if you just have \v 4-5 ? Does it try to put them into the same decoration?

**Comment by jeffheath-sil** [comment]
Yes, I have seen PTXPrint output where it tries (unsuccessfully) to cram a verse range into the decoration. So that's why I need to pre-process and turn it into two separate verse numbers with a hyphen between them.

I still get the syntax error above. Any suggestions for how to set up styles or macros to avoid that? It still produces the PDF output, but I discovered that if I tell it not to keep intermediate files, it will delete my PDF file as well, since there was an error, I guess. It seems like if the canonicalization error is not a fatal error, then PTXPrint should keep the PDF file, even if intermediate files are being removed.

**Comment by mnjames** [comment]
Maybe I'm missing something, but isn't this already built in to the ptx2pdf macros?

If I have markup that looks like this `\v 13-14`
and I include the following in ptxprint-mods.tex
`\def\AdornVerseNumber#1{۝#1}`
then my final result looks like this
![image](https://user-images.githubusercontent.com/30174022/100888411-b3608100-347b-11eb-83e4-9f83706ee88d.png)

**Comment by jeffheath-sil** [comment]
Does this work with a graphic as well as the End of Ayah character? We design our decorations and load them as (tiny) PDF files.

**Comment by mnjames** [comment]
I have no idea... I've never tried that. We're just using the unicode combining character (hence the ۝ followed by 
\#‌1). 

But you might try dropping your code into the AdornVerseNumber brackets and see if it works. Or wait; likely someone on here knows how it works better than I do.

**Comment by jeffheath-sil** [comment]
As I mentioned above, we want to use our own mini-PDF files for the decorators, so I haven't tried End of Ayah. I had been continuing to get a canonicalization error. The PDF was still produced, but the downside was that I had to make sure to "Preserve Intermediate Files and Logs" or the PDF file would be deleted. (Since there was an error, I suppose.)

But with the latest version, the canonicalization error went away. (So now I don't have to preserve intermediate files...) I assume there was some known change that made that happen? So now my modified text which looks like this:
`\v 1 \verserange\v 2 Yoodidu` 
produces a PDF without an error (even though \verserange does not have a closing marker).

**Comment by jeffheath-sil** [comment]
I don’t know why I don’t get the error anymore, but it seems to not be an issue now, so I’ll close this issue.
