### ISSUE TITLE
Adj List broken with verse ranges

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#322]
When the Adj List is created, it appears to include verse ranges at the end of the respective chapter, like this:
```
GEN 6.1 +0
GEN 6.5 +0
GEN 6.11 +0
GEN 6.22 +0
GEN 6.9-10 +0
GEN 7.1 +1
GEN 7.6 +0
GEN 7.11 +0
```

But any adjustments after the verse range seem to be ignored. If you remove the verse range, then following adjustments are again used. So a simple solution might just be to remove verse ranges from the adjustment list.

**Comment by mhosken** [comment]
Verse ranges do work (I've used them before. But bugs may have crept in), but you have to get them exactly right and if you mess up with the adj list, all subsequent adjustments are ignored. This is something we want to change, but we aren't ready to do that yet, so are not shouting about adj lists just at the moment.

**Comment by jeffheath-sil** [comment]
Now I come to think of it, I believe the main problem is that the verses are not "in order". As soon as XeTeX sees GEN 6.9-10, it somehow knows that 6.9 is after 6.22, and it stops processing the .adj file (for the rest of the book). I tried putting GEN 6.9-10 after 6.5 (where it belongs), but that still didn't work. If you leave it as GEN 6.9 (without the range), however, following adjustments do still seem to work.

**Comment by jeffheath-sil** [comment]
FYI With `\tracing{j}`, it shows that once it gets to GEN 6.9-10, it never gets past it, throughout the whole rest of the book:

```
checkadjustments: curref=macro:->GEN6.8, prevref=GEN6.7, adjref=macro:->GEN6.9-
10, curradjpar=1, adjparindex=1
baselineskip = 14.99997pt, looseness = 0
set baselineskip=14.99997pt
checkadjustments: curref=macro:->GEN6.8, prevref=GEN6.8, adjref=macro:->GEN6.9-
10, curradjpar=2, adjparindex=1
baselineskip=14.99997pt; UseGlyphMetrics=0
baselineskip = 14.99997pt, looseness = 0
set baselineskip=14.99997pt
set baselineskip=14.99997pt
checkadjustments: curref=macro:->GEN6.8, prevref=GEN6.8, adjref=macro:->GEN6.9-
10, curradjpar=3, adjparindex=1
baselineskip=14.99997pt; UseGlyphMetrics=0
checkadjustments: curref=macro:->GEN6.9, prevref=GEN6.8, adjref=macro:->GEN6.9-
10, curradjpar=1, adjparindex=1
checkadjustments: curref=macro:->GEN6.10, prevref=GEN6.9, adjref=macro:->GEN6.9
-10, curradjpar=1, adjparindex=1
baselineskip = 14.99997pt, looseness = 0
 [14]
checkadjustments: curref=macro:->GEN6.10, prevref=GEN6.10, adjref=macro:->GEN6.
9-10, curradjpar=2, adjparindex=1
baselineskip=14.99997pt; UseGlyphMetrics=0
checkadjustments: curref=macro:->GEN6.11, prevref=GEN6.10, adjref=macro:->GEN6.
9-10, curradjpar=1, adjparindex=1
checkadjustments: curref=macro:->GEN6.12, prevref=GEN6.11, adjref=macro:->GEN6.
9-10, curradjpar=1, adjparindex=1
checkadjustments: curref=macro:->GEN6.13, prevref=GEN6.12, adjref=macro:->GEN6.
9-10, curradjpar=1, adjparindex=1

```

**Comment by davidg-sil** [comment]
I wonder if this is the same project as your decorated verses? If you split the verse  range in order to decorate them beautifully, then that will break any code that relies on an earlier version of ```\v```

**Comment by jeffheath-sil** [comment]
That may play into the issue, but the Adj List is created from the original SFM file, as you can see from the fact that it has `GEN 6.9-10 +0`. (I split the verse numbers into two with changes in PrintDraftChanges.txt.) But the Adj List is sorted with 9-10 after 22 (as seen above), and I think that breaks the Adj List processing, and prevents any other lines in the list from being used.
