### ISSUE TITLE
Thin space is not non-breaking

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#323]
In the default PrintDraftChanges that PTXPrint uses are lines like this:
`' *»' >    '\u2009»'     # Place non-breaking thin space before closing guillemets
`

But the spaced used there is a thin space but NOT non-breaking:
![image](https://user-images.githubusercontent.com/14953913/100724238-f3aff880-33c2-11eb-8b2f-2a41324f68b2.png)

As you can see here:
![image](https://user-images.githubusercontent.com/14953913/100724317-075b5f00-33c3-11eb-9578-35aeb7c52bc5.png)

I think you want to be using \u202f, the narrow no-break space:
![image](https://user-images.githubusercontent.com/14953913/100724410-21953d00-33c3-11eb-9c05-8f1d05916ef8.png)

**Comment by mhosken** [comment]
We don't provide that default PrintDraftChanges.txt, Paratext does. Feel free to complain to them :)
