### ISSUE TITLE
If the previous job setup specified diglot, the diglot menu item should be visible

### ISSUE THREAD

**Issue by sewhite** [sillsdev/ptx2pdf#326]
On my first attempt with 1.4.2, I was glad it ran, since I'd been having the error from Paratext 9.1 being installed.

But a minor point - I -picked my project, and clicked Print. I was surprised that I got a diglot on my first run because I had run a diglot job with that project in a previous session with an earlier version. I loaded the project again and looked for where the diglot setting was and couldn't see it, until I tried changing the slider to show all the menu items.

I would suggest that when the program opens and the user picks a project, if there is a diglot set from the last time the user ran PTXPrint for that project, that the slider automatically switch to show all the menu items. Or perhaps, if the slider is not set to show the diglot command, that the program not apply the stored diglot settings. Or perhaps a highlight or alert badge on the slider, which if I mouse on it shows a tip like "your stored job settings include a diglot, which is not visible unless you expand the menu options." 

[AAAP-DefaultPTXprintArchive.zip](https://github.com/sillsdev/ptx2pdf/files/5629500/AAAP-DefaultPTXprintArchive.zip)

**Comment by markpenny** [comment]
Thanks for this good suggestion - yes, I think we should do that (and possibly for borders and other settings where the tab name changes to blue [which, BTW, indicates that it is ON].
