### ISSUE TITLE
Shouldn't verse decoration use `\AdornVerseNumber`?

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#327]
The verse decoration snippet in the python code seems to do various complicated things, but seems to have been written before the code to call  ```\AdornVerseNumber{}``` was written, instead operating by start/end hookx. This probably makes it incompatbible  with ```\vp```, nice formmatting of verse ranges,  and other more recent enhancements.

**Comment by mhosken** [comment]
Fixed and we now support verse adornment in Diglot as well with different adornments for the two texts.
