### ISSUE TITLE
v1.4.2 Picture Table List continually resets to the final picture in the list

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#328]
Thanks for the latest version!
Bummer though that there is a bug in the Picture Details table. On my machine it keeps resetting to the final-most picture in the whole book after just a second or so. So it is Click on a picture entry, show that picture's details...1 second...flip! show the details of the last picture in the list. This happens no matter which picture entry I select.

Is there a workaround? Thanks. I'm trying to get the book of Mark out the door.

**Comment by markpenny** [comment]
This is very strange. I have no idea what is going on. Can you check to see if it happens in other projects too. BTW 1.4.3 just slipped out earlier today - so make sure you update to the latest before you do any more testing.

**Comment by davidc86** [comment]
This appears to be fixed.
