### ISSUE TITLE
Use Script for Digits makes no change in output

### ISSUE THREAD

**Issue by viverechristus** [sillsdev/ptx2pdf#33]
I'm using **PTXprint-0.3.0.exe**. Under the Basic tab, if I select "Khmer" under "Use Script for digits (\c and \v)", the output is no different. Numbers are still Arabic. 

(Our project script uses Khmer script. I also tried Thai, just for kicks, and that didn't make a difference either.)

**Comment by markpenny** [comment]
Thanks for pointing this out. We've now fixed the issue as part of the new installer. Hope to have a Beta version available for you to test at the end of this week.

**Comment by viverechristus** [comment]
Works perfectly now. Thanks!
