### ISSUE TITLE
v1.4.1 No Details tab on the Pictures page!

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#331]
Okay, this is weird. I installed v1.4.2 but it is still saying it is v1.4.1.
And when I first opened the project and all seemed fine, except the Details tab kept flipping to the illustration in the last entry of the list.
Then I opened it up again, and all the settings on all the pages were gray! (A similar thing happened with a different project a LONG time ago, but it was fixed at some point) 
So I closed it and opened it again. Same thing.
So I selected a different Language project and its configuration files, Those worked. 
When I switched back to the original project (in a different Paratext project folder) it opened with all the settings working again, BUT now the Picture options is missing the Details tab as well as the Checklist tab: 

![image](https://user-images.githubusercontent.com/65363206/100956045-ab3d2b80-34e5-11eb-80c6-e9847c4c1685.png)

Exiting and re-entering did not help. 

Oddly, I found that if I launch PTXprint from the Taskbar it opens without those tabs.
If I open PTXprint from the Desktop shortcut that the installer put there, it opens with those tabs! Here is the only difference I can see between the properties of the two shortcuts: 

![image](https://user-images.githubusercontent.com/65363206/100956391-5cdc5c80-34e6-11eb-8f8b-3df6bede331d.png)

Any ideas?
Launch from the taskbar I get no pictures in the output PDF.
Now I relaunch and most of the tabs are gray again! No pattern that I can see.

![image](https://user-images.githubusercontent.com/65363206/100956388-5948d580-34e6-11eb-9211-18485577c4ae.png)
**

**Comment by markpenny** [comment]
Hi @davidc86  - apologies for this strange behaviour... We hit a brick wall with turning on (or showing) the Details and Checklist tabs for the pictures after they have been hidden. Whatever we tried kept crashing PTXprint, so the current implementation is a temporary hack to keep us moving. 

The only way I have made it work is to get out of Basic mode (i.e. show advanced mode), then print and finally exit PTXprint. When you start up PTXprint again it should open up in Advanced mode, and then the 3 tabs should be visible, and you should be able to use them as normal until you switch to Basic mode again.

So, YES, we know that it is an issue, and are thinking about how best to solve it, but at least there is a temporary work-around. I'm wondering if we should just disable it instead of hiding it completely, but then the window size will remain large vertically, and one of the aims of Basic mode is to show a smaller, more manageable window to basic users.

**Comment by davidc86** [comment]
Okay, so I'm not going insane! I've never  see this before.
Maybe if the person asks to switch on Advance again, automatically close and reopen the program? Not ideal, but I noticed some other oddities when I was asked to help another team format their new book of Mark. And when I switched back and forth between the SLU projects and the FRDSERA projects, PTXprint did not flush and refresh all its values properly (like the drop-down list of projects were leftover from the previous project's folder, and other values here and there were not loaded properly. So it does seem like the whole clearing out and reloading a new set of values has gaps and bugs in it. (I also noticed some stray PTXprint files showing up in the "shared/ptxprint" folder rather than in the "shared/ptxprint/default" folder where I thought they were all supposed to go.)

**Comment by mhosken** [comment]
How did you manage to change project tree without restarting ptxprint? That's a workflow I can't yet imagine (and yup doesn't work properly). The project piclist ends up in shared/ptxprint. There may be a ugliness with it being called something like SLU-None.piclist. I can't think of anything that should end up in there.

**Comment by davidc86** [comment]
I can change the project tree simply by opening the list of available Paratext Projects, and selecting a different one. SLU (Selaru) is in one folder and all of its PTXprint bits are over there. While FRDSERA  (Fordata Sera dialect) are in the FRDSERA folder and all its PTXprint bits are over in that folder.  

So it is very easy to flip from one tree to another. In fact I imagine that will be standard behavior for most users of PTXprint. (It is likely some IT savvy person will handle this stuff for MTTs for a while, so they will be flipping between various projects. (Unless I completely misunderstood the question.)

**Comment by markpenny** [comment]
@davidc86 I've now got a compromise solution which no longer crashes PTXprint. The 2 additional tabs (Details, and Checklists) on the Pictures page are now ALWAYS visible, but just disabled (and smaller) when Hide Advanced settings is enabled.
