### ISSUE TITLE
Need to escape special characters in copyright messages

### ISSUE THREAD

**Issue by mhosken** [sillsdev/ptx2pdf#332]
Characters like `&` need to be escaped or catcoded appropriately in copyright messages including document copyright and picture copyrights in the colophon.

**Comment by davidg-sil** [comment]
& at least is now catcoded in piclists. Is it ever actually used as an alignment mark?

**Comment by mhosken** [comment]
I think the problem is that the & is not occurring in a .sfm file but in the calling .tex file where all catcodes are as close to default TeX as we can get.
