### ISSUE TITLE
Font features in .sty sheets

### ISSUE THREAD

**Issue by mhosken** [sillsdev/ptx2pdf#333]
Currently we have no way of specifying font feature settings and whether to use Graphite from a font specified in a .sty sheet. I propose we add \ztexfontstyle to add the necessary styling information to the font specification (this should also be used to key the cache). Then we move the feature specification and graphite selection to the font selector and out of Fonts+Script.

The reason for \ztexfontstyle is that we don't want to have to parse a CSS style specification that would be the expected format for such information. The reasons we don't want to parse this information is that TeX doesn't work off feature ids but US English feature names (oh what!).

**Comment by davidg-sil** [comment]
I have stylesheets that say things like ```\FontName Gentium Plus:+smcp```
Are you saying there's no way to do *relative* font settings?

**Comment by devosb** [comment]
I am confused by how to specify the features as well. I have used feature IDs with XeTeX and OpenType rendering, and it worked with Andika New Basic. IIRC, the feature IDs did not work with Charis SIL and XeTeX, and I was not sure what caused the difference. The code I used was
```
\font\oneGR="Andika New Basic/GR:Literacy alternates=False" at 12pt
\font\oneOT="Andika New Basic/OT:+ss01" at 12pt
\font\twoGR="Andika New Basic/GR:Literacy alternates=False;Uppercase Eng alternates=Capital N with tail" at 12pt
\font\twoOT="Andika New Basic/OT:+ss01,+cv43=1" at 12pt
```

**Comment by mhosken** [comment]
The effect of \ztexFontFeatures is pretty much the same, but it separates the font name that identifies the file from the rest of the stuff that XeTeX wants for features. The ptx macros then pull them back together when the font is instantiated in TeX. There are other tags as well \ztexGrSpace for setting contextual spaces. I'm not sure whether to pull out the language code into a separate field or just leave it in the features. It's in the features at the moment, but I do parse it in in and out.

I've also created a font feature editor and integrated so that people don't have to type feature strings and work out what syntax to use, although you can if you want.

**Comment by KimB2017** [comment]
I am not seeing anything about specifying font features in 1.5.6-Linux. Am I missing your font feature editor somewhere? The previous GUI section that pre-filled the PT language-specified features, allowing further edits, seemed somewhat OK to me but I guess it wasn't working very well.
