### ISSUE TITLE
Obscure drop-cap error

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#335]
In stress-testing some revised picture-in-cutout with , I've just met the following case.

* Column X (page n)  has the start of paragraph near the bottom.
* Column X+1 (page n+1) has a chapter  number with ```\nb```
* Column X+2 (page n+1) has the end of the paragraph.

Then the chapter number is in column x+1, but the *cutout* is in the same column as the paragraph break (X+2), because of how the current maths works things out. (lines in parargaph - (end of paragraph y position - cutout y position)/baseline skip)
I've not tested for other arrangements of columns on pages.

I.e. the drop-cap chapter number maths copes with continuation paragraphs assuming that there is **at most one** column/page break between the paragraph start/end and the chapter number, and breaks when this is not true.

With interlinears and diglots, (let alone interlinear diglots) I am fairly sure that multi-column long paragraphs are going to be more common. What I'm not sure about is how often ```\nb``` is used 'a long way' from a par break.

**Comment by markpenny** [comment]
@davidg-sil So is this all fixed now in the latest version?
