### ISSUE TITLE
pytest-3 issues.

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#336]
Some issues:
1.  It seems that a pre-existing .delayed file is not (always?) being  deleted before a run. This gives different run times:
  a.  (1st run after deleting .delayed files) pytest-3 -k OGNT  7 passed, 30 deselected, 5 xfailed in 482.23 seconds
  b. (2nd run) pytest-3 -k OGNT  7 passed, 30 deselected, 5 xfailed in 263.70 seconds
  c. (3rd run) pytest-3 -k OGNT  7 passed, 30 deselected, 5 xfailed in 263.68 seconds

2.  I can't find any record of how many times the job is re-run. Since in testing I've found some situations where there are layouts that can get into unresolved parlocs-loops it'd be good to log repeat runs.

3. Run times have increased substantially  (timings are with .delayed file deleted):
* v1.4.3 : 57.34 seconds
* [3b638952, 15 dec] 86.95 seconds
* v1.4.9 : 95.97 seconds
*  [4d95fefc, 17 dec]  95.96 seconds
*  [a4c1fddaf, 17 dec] 482.42 seconds
* v1.5:  482.52 seconds

[a4c1fddaf] Didn't add any test cases. It introduced a 2 line `.tex` patch; backing out that `.tex` change didn't seem to do anything for the speed. There don't seem to be any changes in the number of runs. Thus, the 500% change in the timing seems to come whatever python changes, but really I don't understand how the changes might cause the observed results.

**Comment by davidg-sil** [comment]
Further observation... it's not that python is doing lots, but that XeTeX is running much 5 times slower. Different renderer choices? Letter spacing options?

**Comment by mhosken** [comment]
One probable cause is the processing of the complete WEB bible which has strongs codes on every word:
```
\v 1 \w In|strong="H430"\w* \w the|strong="H853"\w* \w beginning|strong="H7225"\w*, \w God|strong="H430"\w*\f + \fr 1:1 \ft The Hebrew word rendered “God” is “אֱלֹהִ֑ים” (Elohim).\f* \w created|strong="H1254"\w* \w the|strong="H853"\w* \w heavens|strong="H8064"\w* \w and|strong="H430"\w* \w the|strong="H853"\w* \w earth|strong="H776"\w*. 
```
for 2400 pages, processed twice. This also applies to the OGNT interlinear NTs (of where there are 3 each processed twice) which uses the same WEBorig as the English source text.

We could strip out the `\w word|strong="num"\w*` back to `word` using a PrintDraftChanges.txt. That would speed things up a lot, I suspect.

**Comment by davidg-sil** [comment]
Ah. And [a4c1fdd] stoped stripping them out? *That* makes sense!

At the moment attribute parsing in character styles is processing things letter-by-letter, looking for the next ```\w*``` (or whatever), so it can read that with the wrong catcode and run it properly. That reading is going to be horrendously slow, I'm sure. 
It's just occurred to me that given we know what endmarker we're *expecting*, there ought to be some way to make `|` slurp up the text faster. Maybe. Is there a way to delimit arguments something like this:
```
\def\makeAttMacro#1{\def\AttMacro##1\#1{\def\att@result{##1}\end@attributes\csname#1\endcsname}}
\def\|{\makeAmacro{\m@rker}\AttMacro}
```
(Maybe with a complex heap of \expandafters?) That's basically all the code is trying to end up with.
Failing anything else, I guess we could speed things up enormously by defining some manually...
```
\def\att@parse@w#1\w{\def\att@results{#1}\end@ttributes\w}
```
(things like `\end@ttributes` should be taken as pseudocode not reality - It's a while since I looked at the code)

**Comment by davidg-sil** [comment]
Amazingly, this works:
```
\def\test#1{\x@\def\x@\foo\x@##1#1{we got a ##1 before #1}}
\test{\e}
\def\e{slash-e}
\foo hi\e
```
![image](https://user-images.githubusercontent.com/58848232/103879861-0f54a000-50e1-11eb-97ef-0ab242c2c7ac.png)
