### ISSUE TITLE
v1.5 Fig List Order still weird in Jonah

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#337]
I believe I mentioned this before, but I couldn't find the issue. But since this is the latest version, I figured I should mention it again. I just opened my standard "Selaru Publications" configuration, hit PRINT and then checked to see what changed in the configuration files between the last version and this one. Of course lots of changes in the config file itself and the styles, but what was weird is the PicList order error is still showing up.

![image](https://user-images.githubusercontent.com/65363206/103571917-bcd57280-4e99-11eb-96f5-f9da3b915574.png)

On the LEFT is the v1.5 list. On the RIGHT is the last version's list. NOTE: BOTH have the Jonah pictures listed in the wrong order, but v1.5 did not fix it; it just messed it up in a different order. 

Mostly an FYI, I haven't actually looked at Jonah lately, but I'm thinking these kinds of things should be "self-cleaning" (since I have reordered them in the past to get them in the right order, and PTXprint messes them up again. Oddly, it appears, for Selaru books anyway, only Jonah (JON) is affected. The fig reference order in all other books remains correct and consistent.

**Comment by davidg-sil** [comment]
Interesting bug I'll leave for the python experts. At least the order of the piclist doesn't matter now as far as the XeTeX  code is concerned.... a few months ago that would have been a disaster.

**Comment by mhosken** [comment]
I'm wondering if the space in JON 1.13 is in fact a space or something else that is causing the JON 1.13 to be treated as a single string rather than split into JON,1,13 like the other JON entries. This would cause the ordering you are seeing.

**Comment by davidc86** [comment]
Nope. I just checked this. In Notepad++ I reordered the lines back into logical order. Then I deleted the space and made sure I entered a space with English keyboard as the active keyboard. Then I saved and backed up the file. Then I opened  PTXprint, clicked PRINT, waited until the PDF opened (it is just processing Mark, btw), and then compared the files, and PTXprint reordered the first two JON 1 entries after the JON 4 entries. 

![image](https://user-images.githubusercontent.com/65363206/103919211-cbac6700-50dd-11eb-8c1f-894ee3eb20f6.png)

So by comparing these two screenshots, for some very strange reason, each time it opens PTXprint moves the book of JON's first TWO entries it encounters to the end of that book's section. I.e. this current screenshot is what happened right after I reordered the list to the correct order. The previous screenshot shows the NEXT 2 entries have moved down to the bottom. So, I suspect that each time I open PTXprint, it moves 2 entries. 

It is strange. And it is ONLY the JON book. No other book reorders the entries like this.

**Comment by mhosken** [comment]
I think I've fixed this, but I dread to think what I've broken in the process. Hopefully, nothing.

**Comment by davidc86** [comment]
v1.5.1 says it fixed this issue, but unfortunately, it has not. Here is a new screen shot, of the changes that happened on opening v1.5.1, clicking PRINT, waiting for the PDF to open, and then refreshing the File Compare software (new version on LEFT; old correct version on RIGHT): 

![image](https://user-images.githubusercontent.com/65363206/104235131-844a1180-5422-11eb-86ef-32ee17c54c8b.png)

Were the corrections included in the v1.5.1 update, or should I wait for a v1.5.2?

**Comment by davidc86** [comment]
YES! This appears to be fixed. And it even fixed other places in my PicList file where the pictures were out of order and I didn't notice! So this can be marked as closed.
