### ISSUE TITLE
v1.5 reorders the styles in the STY file each time it saves

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#338]
I like to maintain a backup of all of the configuration files for PTXprint for each version, just so I can see what tweaks you all have done and to recover my work should a bad glitch get introduced into PTXprint's latest version. 

So it is a bit odd now, with this version of PTXprint, that every time I compare the ptxprint.sty files the styles are in a completely different order. It is like scrambled eggs. 

Here is the latest compare showing two versions that were only minutes apart (and I did not change anything in PTXprint):
![image](https://user-images.githubusercontent.com/65363206/103920637-88eb8e80-50df-11eb-92f7-f95f114617e2.png)

Might it be possible/preferable to read in and write out the sty files in an alphabetic order or some other order like the order you use in the style tree? 

This would make it much easier to compare versions of my styles and see which tweak has what effect on the output.

**Comment by davidg-sil** [comment]
Absolutely agree, it's also causing needless deltas in the git repo for the test cases.

**Comment by davidc86** [comment]
Yes. This is fixed in v1.5.1. Woohoo.
