### ISSUE TITLE
v1.5.6 The Layout Base Paragraph Indent value is not retained but reverts to 1.0 after each restart 

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#342]
(still an issue in v1.5.5)

Just checking the v1.5.4 version and found that the Base Paragraph Indent value on the Layout page won't keep my specified value of 0.5. Instead it reverts back to 1.0. Maybe the issue is 0.5 is an invalid value? It seems to work correctly if I set 0.5 and click PRINT. And it even saves this 0.5 value in the config file in the line: **indentunit = 0.500**. 
BUT, when v1.5.4 reopens the config file, it ignores the specified value in the file and reverts to 1.0

**Comment by markpenny** [comment]
Hi David, I've tried to replicate this but can't seem to do so. I'm wondering if there is a "bad" (out of range) value stored in the .cfg file which forces it to return to the default value of 1.0 when it reloads.  Could you open the appropriate .cfg file in a text editor and search for: **indentunit**
It should look something like this:
`  indentunit = 0.500`

**Comment by davidc86** [comment]
I tested this and the "reverted" file is on the left and the original on the right: 

![image](https://user-images.githubusercontent.com/65363206/105440564-c5b59a80-5c34-11eb-9337-03ef60c5f666.png)

The ONLY difference between the two files is the RED LINE. 
And the spec for the "original" **indentunit** looks correct to me.

**Comment by davidc86** [comment]
Still an issue in v1.5.6
Here is an added oddity: 
When I open PTXprint, it automatically changes the 0.50 to 1.00 for **indentunit**. 
If am not paying attention, and click PRINT, the indentions are too large, but the picture show up in the PDF.
If I then fix the layout to 0.50 and click PRINT, the indentions are correct, but the pictures **don't** show up, but are replaced with a BOX in the PDF.
If I exit PTXprint and reopen it, and remember to change the layout to 0.50, and click PRINT, then I get both the correct indention and the pictures show up! 
I remember seeing this oddity a while back where the  pictures didn't show up, but were replaced with boxes. And this issue was fixed. So there must be some other oddity in the CFG file that is throwing PTXprint off kilter. 

Here it is with the .CFG extension changed to .TXT so github would take it.

[ptxprint.txt](https://github.com/sillsdev/ptx2pdf/files/5859572/ptxprint.txt)

**Comment by davidc86** [comment]
Fixed in v1.5.8
