### ISSUE TITLE
v1.5.5 Last picture in Picture List Details tab is hard to select because the scrollbar covers it

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#343]
(updated to say still an issue in v1.5.5)

The last picture listed in the Picture List details tab is very hard to select, because the popup horizontal scroll bar covers it when we move the mouse to select it! See this: 

![image](https://user-images.githubusercontent.com/65363206/104931707-c6200e00-5974-11eb-90e8-b3331a7c0ea4.png)

The problem is the vertical scrolling doesn't take into account the screen space the horizontal scrollbar will hog once it pops open, so it doesn't allow the last line in the pic-list to scroll UP enough to come out from behind the horizontal scrollbar. Just allowing the last entry to come up from the bottom edge of the box would be enough to make it selectable.

**Comment by markpenny** [comment]
A permanent (non auto-hiding) scrollbar makes the last line invisible and makes the scroll area shorter. 
BTW if the 2nd last item is selected and you use the down arrow, it then selects the last (mostly hidden) row and enables you to edit the settings. So, although the current way of working is a little awkward, it is still better than the proposed solution. So, for now, we're not going to change it.
If we find a way of making the horizontal scroll-bar narrower, then we might be tempted to turn it on permanently. But for now, we're leaving it as it is.

**Comment by davidc86** [comment]
Hmm, well, I’m thinking that is a less than ideal direction. Because, basically, for the sake of a little bit of vertical real estate, we are choosing to make it very difficult to deal with the last picture in a list. Why? Who will care about a little bit of real estate if they can’t get at the last picture in the list? (Very few users would think to click on the 2nd to last entry and then press Down Arrow. Clickers will click. Keyboarders keyboard.)

Is the issue that a change here to making this scrollbar show permanently here effect any other areas of PTXprint too? I.e. is such a change global or a widget-by-widget decision?

Or is the concern more about MTTs with lousy screens? I ask because most newer devices should have at least a 1080p screen (FullHD). And if the display is set to 100% then vertical space is plentiful. (Granted if they have it set to 150% or 200%, then vertical space might be an issue.)

I just wish the scroll area was calculated to exclude the scroll bars, whether the scrollbars show or not, so that if we scroll completely to the bottom and the dialog is wide enough to not need a horizontal scroll bar, then the last entry would scroll up a bit above the bottom edge of the list box. To me that isn’t a big deal.

Just asking, as this seems to be a somewhat user-unfriendly direction to head in.

Not complaining, only concerned for usability,
David


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
