### ISSUE TITLE
Step backwards for page filling/balancing?

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#346]
Using the latest (1.5.6), I am seeing significantly worse problems than I was seeing before in page filling. In previous versions (around 1.4 or so, or maybe even 1.5) I was seeing some places where I needed to use the adjustment file to add line(s) to paragraphs to nicely fill pages. But with the latest I see things that can't be fixed with the adjustment file, like this:
![image](https://user-images.githubusercontent.com/14953913/105364362-60928280-5bfd-11eb-9d31-00ae2d0ada43.png)
Why are there 5 blank lines at the end of a page, but then two lines on that last paragraph pushed to the next page? (And no footnotes in sight.) I don't even know how I to fix that...

If you have made some adjustments to page filling recently, I think you need to roll those changes back. I have a single book typesetting job that I need to do in the next week or so, and I think I might need to go back to an earlier version of PTXPrint.

**Comment by mhosken** [comment]
It looks like there was a bug with chapter initial paragraphs in effect not breaking after instead of not breaking after if the paragraph is too short for the cutout.
