### ISSUE TITLE
Centered styles not actually centered?

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#347]
I am using a centered style for \s1 section headings with decorative borders around them, and I have a 5mm binding gutter on my pages. But when the section heading gets to be about the same width as the border it becomes clear that the section heading (and/or the box) is not actually centered on the page:

![image](https://user-images.githubusercontent.com/14953913/105369782-2af09800-5c03-11eb-9584-337c71bc9c3a.png)

You can see that the \s1 text is not centered inside the border. ("Waas almost touches, but "Leŋ" has some margin from the border.) The binding gutter (of 5mm) on this page is on the right, and I'm wondering if that somehow messes up the centering of the \s1 text. (It's not as if it is centered on the page ignoring the binding margin, but it is shifted that same way.) All of the indent factors for that style are zero (0).

Forget that idea that the binding margin is at fault... when I remove the binding gutter, the \s1 style is still offset:
![image](https://user-images.githubusercontent.com/14953913/105371682-21682f80-5c05-11eb-8172-b89274eb0500.png)

Any thoughts as to why a centered paragraph style is not actually in the center?

**Comment by mhosken** [comment]
There is a space leaking into the start of the heading. I.e. that line starts with a space. So, it is centred, but the initial space throws off the visuals. We'll keep hunting for the pesky little thing.
