### ISSUE TITLE
First \v inside a \li, and first \v inside a \q marker do not get FontSize applied.

### ISSUE THREAD

**Issue by KimB2017** [sillsdev/ptx2pdf#349]
![Selection_079](https://user-images.githubusercontent.com/25071218/105440160-1b3d7780-5c34-11eb-9ea8-c556a7d52a7c.png)
![Selection_080](https://user-images.githubusercontent.com/25071218/105440183-22fd1c00-5c34-11eb-9629-0570128270b7.png)

I haven't been able to check this for a multi-book printout yet due to a \fig error somewhere, I think, but this is very consistent. I have FontSize=8 and Raise=1.5em set for \v in ptxprint-mods.sty. The first screenshot shows MAT 1; the second MAT 2. I have not seen any more too-big verse numbers in MAT.

**Comment by mhosken** [comment]
We are somewhat bemused. Could you send an archive (see issue #280 on how to do that). TIA.

**Comment by KimB2017** [comment]
It happens also when I disable all the extra .xty files and specify Raise in the Styles Tab. Also happens in a Module, the first \q marker that occurs even if it's on page 12.

**Comment by markpenny** [comment]
@KimB2017 **We can't make any progress** with this issue until you Create a ZIP Archive and send it to the ptxprint_support@sil.org address...
(see issue #280 on how to do that)

**Comment by KimB2017** [comment]
[RTTT-NewRTTTPTXprintArchive.zip](https://github.com/sillsdev/ptx2pdf/files/5860199/RTTT-NewRTTTPTXprintArchive.zip)
I thought it might have to do with my \v \FontSize 8 \Raise setting 1.2em in ptxprint-mods.sty. But the first \v in MAT 1:2 is bigger than the rest when that -mods.sty is turned off but custom.sty is on, or when custom.sty is off but -mods.sty is on, or both. Custom.sty has just \FontSize 8.

Since you have my archive now... Can you see what causes the superscript raise setting in my ptxprint-premods.tex crashes the program? That's why I put the setting into -mods.sty. I have had to turn off the .tex file in ptxprint.

**Comment by KimB2017** [comment]
Fixed in 1.5.8. Thanks!
