### ISSUE TITLE
Error page in the Print Preview

### ISSUE THREAD

**Issue by jayak-siva** [sillsdev/ptx2pdf#35]
I got such error page when I click print preview. 
This text does have the font, no syntax error and have no picture. I have got this issue even in other projects too.

![image](https://user-images.githubusercontent.com/12491670/77288023-f1a67d80-6cfc-11ea-9b9b-052a7c5c3960.png)

**Comment by jayak-siva** [comment]
I use the latest version.

**Comment by devosb** [comment]
I suspect you have installed the font only for your user login. The font needs to be installed for all users (which might require your administrator password). So uninstall the font, possibly reboot, and then re-install the font.

**Comment by markpenny** [comment]
@jayak-siva Could you please confirm whether re-installing the font (for All Users) solved the issue? If so, we can close this one.

**Comment by jayak-siva** [comment]
It works after installing font again "for all users"
