### ISSUE TITLE
Substitution file for full copyright info

### ISSUE THREAD

**Issue by KimB2017** [sillsdev/ptx2pdf#350]
I would love to have a place to store copyright statements for my less commonly used illustrations (Sweet, LanguageRecordings, NewTribes, other Papua NG-approved illustration sets). 

Suggestion: store a keyword for each source in the Paratext \fig spec copy= field to replace with a statement.
I realize this could be entered into PrintDraftChanges.txt, but that's really not the place for it, and it will get bulky. It is much easier, when adding figs to a book, to type a short keyword than to keep copy/pasting different © statements as I go. 

Is there already a ptxprint-changes.txt?

**Comment by markpenny** [comment]
We need to run our PicLists through the PrintDraftChanges.txt - but also work out how to not change things that shouldn't accidentally get changed. Thinking...

**Comment by mhosken** [comment]
Unfortunately, I don't think we can use PrintDraftChanges for this because we need to capture the copyright statements for the colophon. I propose we extend the two letter filename code ids for this an provide a mechanism by which users can extend or perhaps edit (I realise that may not be desirable) the copyright statement associated with a 2 letter code.

**Comment by KimB2017** [comment]
I like the statement associated with a code approach, extendable by users. I'm thinking that all illustration sets don't use filenames starting with 2-letter id lines, however, and it would be a huge job to rename existing pic files and re-associate them in PT projects. If the copyright match could be a bit more flexible it would help. 

Ethnos360/NTM line drawings, for example, start with a 3-digit code followed by a space. GlobalRecordings illustrations are keyed to the publication they are found in: 2-3 letter codes such as tlc, gn, lll.

It should be a good thing to have the "official" SIL copyright statements non-editable. However, SIL PNG Literacy and Scripture Pub departments seem to recommend a slightly different format than what PTXprint provides, and they are extremely picky about jots & tittles! Seems like they should accept IPUB format, though, so I'm probably overreacting.

**Comment by markpenny** [comment]
@KimB2017 Would it be possible for you to send a few samples/examples of the other (non-SIL/UBS) image FILENAMES that people use. Either a directory listing or a pattern (e.g. XYZ_description). That might help us design a system that works across different sets of images without making too many wrong assumptions.

**Comment by KimB2017** [comment]
Maybe this comment should be moved to a separate issue, but it seems relevant here:

Back in November the Credits statement included my custom copy= statements, transferred in from PT. PTXprint correctly substituted the "real" copyright info for my abbreviated PT statements for the standard SIL figs, and left my copy= statements for the unknown figs. But recently the PT copy= statements are ignored by ptxprint. 

Here's the credits block from November compared with today's, along with a sample from my piclist, after I added the full "by John K. Boire..." statement to that PT \fig field. At least the incomplete/incorrect © statements in Nov's output let me know that I need to correct something. It might be helpful if the ptxprint Picture Detail screen could show the auto-inserted © statement if there is one, or else show the PT copy= statement and allow me to replace it with a correct copyright in the piclist.

![Credits_MAT_Nov2020](https://user-images.githubusercontent.com/25071218/106294102-bf1eb880-621c-11eb-814a-a4c6c1f78eae.png)
![ptxprint-NewRTTT-MATRTTT__Jan2020__piclist](https://user-images.githubusercontent.com/25071218/106294146-cf369800-621c-11eb-9115-5c18629486a1.png)
![Credits_MAT__Jan 2021 (1 5 8)](https://user-images.githubusercontent.com/25071218/106294119-c47c0300-621c-11eb-85e2-8208d468ee73.png)

**Comment by KimB2017** [comment]
Cool! Today in 5.12.4 all my copyrights are showing up! And they appeared on the first run.

**Comment by markpenny** [comment]
@KimB2017 - we've just re-engineered things so that you can add other series of illustrations, and add your own copyright attribution statements.

**Comment by davidc86** [comment]
Thanks! Looking forward to testing this.
Will it be in v1.5.13?

**Comment by markpenny** [comment]
@KimB2017 Please see my e-mail about updating the picCopyrights.json file with user-customizable info. I think we can close this issue once you confirm it is working well for you. 

And keep in mind that the Tok Pisin code is 'tpi' if you want to localize the credits as well.
