### ISSUE TITLE
Verse number sometimes too large

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#351]
I am putting verse numbers in star decorators, and noticed that sometimes the verse number gets larger than it should:
![image](https://user-images.githubusercontent.com/14953913/105580936-b4cd6c00-5d8f-11eb-8576-26c0730494d0.png)
This is Luk 20.43, where the verse number occurs right after a \q2. So I thought that was the problem, but then I noticed another which is directly after a \q1:
![image](https://user-images.githubusercontent.com/14953913/105580919-9bc4bb00-5d8f-11eb-9eac-19521248af57.png)
This is Luk 1.47, and you can see that there are other verse numbers in this screen shot that immediately follow other \q1's and they are fine.

I include the references because these problems appear in the project files I sent you before, so you should be able to see the problem for yourself.

**Comment by markpenny** [comment]
Duplicate of #349 - we're aware and will hopefully solve it in the next day or two.

**Comment by jeffheath-sil** [comment]
Looks good now.
