### ISSUE TITLE
Save configuration - not expected action

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#352]
If I start working on a new project in PTXPrint, it starts me in the Default configuration. Let’s say that I work for a little while making changes, and I kind of like the way it is looking and I want to name the configuration, "NiceLayout". If I type that into the Configuration Name box and click Save, then it creates a brand new configuration with that name, and I have to start from scratch! I think it should save the current configuration under that name, which can then be further modified.

I realize that this is sort of the inverse of what I was asking for before. When you switch to a different project that has no configurations, you need to make sure that you are starting from a default configuration and not copying things over from the previous configuration (which might make the Print fail). I guess this might be another reason why it would be good to have a Reset button in the configuration section, to reset to some base default.

**Comment by markpenny** [comment]
Yes, this is an unintended change, and we should be able to put it back to how it was before (i.e. make changes to any existing configuration and provide a NEW config name and hit Save. This should keep all the existing settings.) We now have a button to reset the Default config (by using the Delete button), so if someone really wants a new config with NO customized settings, then that would be the route.

**Comment by markpenny** [comment]
This has been fixed now, and should be working as you would expect in v 1.5.8

**Comment by jeffheath-sil** [comment]
I think this is better now, but I'm not convinced that it is at 100%...  Is the advanced setting switch stored in the configuration? If I delete Default it goes to non-advanced. If I then go to an advanced configuration, it shifts to advanced view, but then if I go back to Default, it keeps it in advanced mode. Is that intentional?
