### ISSUE TITLE
Base Paragraph Indent keeps resetting

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#354]
I have set the Base Paragraph Indent from the default of 4.0 to 2.0 in my project. I print, and everything looks fine. I close PTXPrint and reopen it, and the value is reset to 4.0. If I print again, I get very large indents.

**Comment by davidc86** [comment]
See #342, I'm having the same issue with my setup. It resets to 1.0 and I want 0.5. I can't even imagine ever needing a 4.0" indent. It is measured in Inches, right? (That is what the popup help says anyway.) Even 2" is pretty big. (Unless there is a way to switch from inches to cm that I'm not aware of.)

**Comment by markpenny** [comment]
Yes, we think we fixed this yesterday. I'll get the next version out later
today for you to confirm whether it has been fixed for you.
Mark

**Comment by davidc86** [comment]
It is fixed for me in v1.5.8
