### ISSUE TITLE
Updating XeTeX

### ISSUE THREAD

**Issue by devosb** [sillsdev/ptx2pdf#355]
Over the past few years I have updated XeTeX in Paratext for Windows so that newer version of HarfBuzz and Graphite would be used, which solves some shaping issues. Today @mhosken suggested that I update the XeTeX (for Windows) binaries in PTXprint instead.

When updating Paratext, I would stop Paratext, make changes to the `xetex` folder in the Paratext Program Files folder, and then restart Paratext to test my work. I can do the same with PTXprint.

Or would it be better to clone the repo, and run from source? If this is the case, what Python distribution do you suggest? ActiveState, python.org, or something else?

**Comment by devosb** [comment]
I now have a [script](https://github.com/sillsdev/ptx2pdf/blob/master/update-xetex.bash) to do the updates. The script helped me see that not all of the files that were part of a stripped down setup for Paratext are in TeX Live (TL) which is where the Windows binaries come from. So I was going to delete some of the files, but wanted input first.

Ideally we would have a clean separation between what TL provides (and thus we do not need to maintain) and those files that we do need to modify, are checked into the this repo somewhere else (outside of the xetex folder) so it is clear that TL will not be keeping them up-to-date. That is, for maintainability, it would be nice if the xetex folder in PTXprint was a subset of TL.

So the question for each point below is do we need them in the xetex folder in the this repo? From testing, I suspect they are not needed, but maybe my testing was not comprehensive enough.

1. All the _fontconfig_ files in [xetex/share/texmf-dist/fonts/conf/conf.d](https://github.com/sillsdev/ptx2pdf/tree/master/xetex/share/texmf-dist/fonts/conf/conf.d) have been removed in TL 2019 (they were in TL 2018).
2. Two PFB font files in [xetex/share/texmf-dist/fonts/type1/bluesky](https://github.com/sillsdev/ptx2pdf/tree/master/xetex/share/texmf-dist/fonts/type1/bluesky) are not in TL in that location, although those PFB files are in TL at `xetex/share/texmf-dist/fonts/type1/public/amsfonts/cm` but we don't have the `amsfonts` folder in PTXprint.
3. The xetex tree that @mhosken imported into the this repo from Paratext for Windows have many TECkit digit mapping files (`.map` and `.tec`) at [xetex/share/texmf-dist/fonts/misc/xetex/fontmapping].(https://github.com/sillsdev/ptx2pdf/tree/master/xetex/share/texmf-dist/fonts/misc/xetex/fontmapping). Many of those are duplicated in [src/mappings](https://github.com/sillsdev/ptx2pdf/tree/master/src/mappings). TL also comes with digit mapping files located elsewhere in the TL tarballs.
4. The file `glyphlist.txt` is no longer in TL (the folder was [share/texmf-dist/fonts/map/agl](https://github.com/sillsdev/ptx2pdf/tree/master/xetex/share/texmf-dist/fonts/map/agl)). We still have that file, in that location, along with `pdfglyphlist.txt` which is still in TL.
5. The files in [xetex/share/texmf-dist/fonts/map/dvipdfm](https://github.com/sillsdev/ptx2pdf/tree/master/xetex/share/texmf-dist/fonts/map/dvipdfm) were removed after TL 2011 but many are in [xetex/share/texmf-dist/fonts/map/dvipdfmx](https://github.com/sillsdev/ptx2pdf/tree/master/xetex/share/texmf-dist/fonts/map/dvipdfmx).
6. The files in [xetex/share/texmf-dist/fonts/enc/pdftex/base/](https://github.com/sillsdev/ptx2pdf/tree/master/xetex/share/texmf-dist/fonts/enc/pdftex/base) are not in TL.

**Comment by mhosken** [comment]
Great let's remove as much as we can. The more the merrier. So. Yes. delete them all.
