### ISSUE TITLE
v1.5.8 Typing in a number value for a style then switching styles doesn't save the number

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#358]
This issue was a problem in the past, but it seems to have come back. 
If I use the spinners the values are saved immediately in the style.

But if I **_type in a value_** in a style box (say font size), and then **_immediately click on another style_** to tweak that one, the first tweak is NOT retained, but it reverts back to the original value.

The only way to retain an edited value (that is typed in) is to click in another widget in the same window, BEFORE I click on another style.

The reason for needing to type in a value is that sometimes the spinner changes the value in very small increments (a good thing), but if I need to change 11 to 10 that would require 10 clicks, rather than just typing "10", so typing is preferred. 

Users will expect their edits to be saved as soon as focus moves anywhere else.

**Comment by mhosken** [comment]
We don't know how to do this.
