### ISSUE TITLE
v1.5.8 Clicking Print, making changes, then clicking Print again causes Pictures to not show

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#359]
I've seen this in the past, but it was fixed, so this has resurfaced. 
If I open PTXprint and click PRINT, everything shows up nicely in the PDF.
But if I see something in the PDF that needs tweaking, and close the PDF, tweak the bit in PTXprint (be it a style tweak or a picture tweak or whatever), and then click PRINT again, the PDF opens but all the pictures are just boxes.

![image](https://user-images.githubusercontent.com/65363206/106161231-b8c50980-6154-11eb-8f88-6775b6f35838.png)

Not exactly sure what all will trigger this, but so far I'm seeing this happen when I tweak a style or when I tweak a "mirror picture" setting. 

If I exit PTXprint and reopen it, clicking PRINT will use the newly saved settings and the pictures will show up correctly again.

**Comment by markpenny** [comment]
We haven't been able to replicate this one yet. But we did find some other bugs while looking for it ;-)

**Comment by davidc86** [comment]
If the temp files are marked to be retained, then subsequent Print processes work just fine. But if the temp files are set to be deleted, then subsequent print processes put empty boxes in the PDF file. (verified with v1.5.9.3)
This could be closed if you want to consolidate issues.
