### ISSUE TITLE
Changes to PrintDraftChanges.txt file require restart to apply

### ISSUE THREAD

**Issue by viverechristus** [sillsdev/ptx2pdf#36]
Using 0.4.3. Option to "Apply Changes Specified (in PrintDraftChanges.txt)" is selected.

If I ...

1. edit the PrintDraftChanges.txt
2. save those changes (and even refresh the editor to confirm that those changes have been made)
3. run Print Preview

... the changes I made to the PrintDraftChanges.txt are not reflected in the output. (The PrintDraftChanges.txt is applying, but it's the version of the file BEFORE I made the edits.)

To make the new version of PrintDraftChanges.txt work, I either have to restart PTXprint, or deselect "Apply Changes Specified" and run a Print Preview then reselect the option and run another Print Preview. In that case, the latest version of the file is applied.

**Comment by markpenny** [comment]
Thanks so much for this thorough investigation. I appreciate the
      time that you have invested in it. We now have something specific
      to fix!
      Mark
    
    On 1/04/2020 9:02 am, viverechristus
      wrote:
    
    
      
      Using 0.4.3. Option to "Apply Changes Specified (in
        PrintDraftChanges.txt)" is selected.
      If I ...
      
        edit the PrintDraftChanges.txt
        save those changes (and even refresh the editor to confirm
          that those changes have been made)
        run Print Preview
      
      ... the changes I made to the PrintDraftChanges.txt are not
        reflected in the output. (The PrintDraftChanges.txt is applying,
        but it's the version of the file BEFORE I made the edits.)
      To make the new version of PrintDraftChanges.txt work, I either
        have to restart PTXprint, or deselect "Apply Changes Specified"
        and run a Print Preview then reselect the option and run another
        Print Preview. In that case, the latest version of the file is
        applied.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/sillsdev/ptx2pdf/issues/36",
"url": "https://github.com/sillsdev/ptx2pdf/issues/36",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    --

**Comment by markpenny** [comment]
@viverechristus Thanks for discovering this. Yes, indeed - there was an issue and I've fixed it now. It will be in 0.4.8 or later (due to be released in a day or two...)
