### ISSUE TITLE
Split/hightlighted tab titles don’t get translated?

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#365]
It appears that tab titles that can be split and highlighted in blue are not translating correctly:
![image](https://user-images.githubusercontent.com/14953913/106356026-8eae4b80-62fc-11eb-8718-46e341bb8825.png)
Note that Images and Onglets are now translated properly (they weren’t in a previous version), but Diglot+Border still does not, maybe because they can be highlighted in blue separately? Border does appear as a separate translation string, so hopefully you can figure out a way to use that.

**Comment by markpenny** [comment]
Once the localization of these (sub) strings has been done, it works fine.
![image](https://user-images.githubusercontent.com/12962708/106418106-679d7880-64ba-11eb-8e27-55366d6152be.png)

**Comment by jeffheath-sil** [comment]
I could have sworn that Border was translated quite a long time ago... But Crowd-in said I only got it translated 2 days ago, so I guess I’m just delusional... I’ll check it out in the next build.

**Comment by markpenny** [comment]
I have also gone through many of the Crowdin 'fr' strings and broken some of the longer ones into 2 lines so that we don't end up with an unnecessarily wide interface for french. Hope to get the latest build out to you by tomorrow... 1.5.9.1
