### ISSUE TITLE
Distressing that PTXPrint doesn’t work on new project

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#366]
I am distressed that in a number of cases, I can’t just select a new project (that I have never used PTXPrint on before), select a book and successfully print.

One one project, I gave me a couldn’t combine Diglot error, and sure enough when I went to advanced mode, Diglot was activated.

On another, it gave me an error about a marker (\v, I think) not being valid under certain markers, and when I went to advanced mode and the Advanced tab, custom.sty was activated.

I don't know what you do when you start working in a brand new project, but it seems to me like you better make sure that all of the special options are turned off, so there is a good chance of success on first print.

**Comment by jeffheath-sil** [comment]
Another case. I downloaded the project for the first time. The PrintDraft folder was almost empty. I chose 1TI and told it to print and I got:
![image](https://user-images.githubusercontent.com/14953913/106358628-ba85fd00-630d-11eb-89f7-969874b6632d.png)

I don't even know what the problem is. This is not the first \xt, there are other places that the Saltillo U+A78C is used. No Advanced things are checked, or Diglot.

OK, it appears that there is a missing \+xt* after the cross reference. But that doesn't seem to show up in Paratext checks...

My point, however, is that we want newcomers to have a high probability of success on their first try. Have you done testing with new users, with projects that have never used the tool, rather than people like me who have been using it for a while and tend to keep using the same test projects?

**Comment by jeffheath-sil** [comment]
(By the way, I don't think a \+xt* is REQUIRED at the end of the cross reference, is it? Like if the cross reference ends at the end of the footnote...)

**Comment by jeffheath-sil** [comment]
Just FYI - If I just put in a change to make the embedding of the \+xt marker go away, that made the problem above (needing to close all of the \+xt markers) go away...

`'\\\+xt ' > '\\xt '`

**Comment by markpenny** [comment]
> I am distressed that in a number of cases, I can’t just select a new project (that I have never used PTXPrint on before), select a book and successfully print.

I have tested this and can't see any evidence of strange settings being left on. We do (intentionally) reset to default values between switching projects, so Diglot shouldn't be left on from a previous project. We do leave "Pictures" on and it seems to be printing pictures even on a first run. Are you sure the "new" (never been used before) project hasn't got a shared/ptxprint folder?

**Comment by markpenny** [comment]
@jeffheath-sil Are you still seeing this strange behavior (in 1.5.9.3 or later), or was it just a temporary glitch in a bad build? Please close if it is resolved.
