### ISSUE TITLE
Localization selection from within PTXPrint

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#368]
I think it is important for there to be an option to select the UI localization language from within PTXPrint. In our part of the world it’s not unusual for someone to have an operating system on their computer that has no relation to the language(s) they speak. Specifically, there are lots of computers here in Chad with an English OS or an Arabic OS, but most of those people want to use software in French, if possible.

I have been told how to open PTXPrint with a given localization from a command prompt window:
`set LANG=fr`
`"C:\Program Files\PTXprint\PTXprint.exe"`
And that works to open the French UI of PTXPrint on my English OS. But I’m pretty sure we don’t want to make people do that just to open the program in French. A nice pop-up selection list would be much better. Maybe next to the the Advanced Settings toggle switch?

Thanks for considering it.

**Comment by markpenny** [comment]
![image](https://user-images.githubusercontent.com/12962708/106418151-8a2f9180-64ba-11eb-87c9-483648605c7e.png)

and the list of languages (so far) - the highlighted ones already have a significant proportion translated (or at least machine-translated):

![image](https://user-images.githubusercontent.com/12962708/106418304-de3a7600-64ba-11eb-8567-734c542d899f.png)
