### ISSUE TITLE
v1.5.9.1 Fails to PRINT because CONFIG file does not maintain paths to specified files

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#372]
Worked fine in v1.5.8
Opened the exact setup in v1.5.9 clicked PRINT, and got this: 

![image](https://user-images.githubusercontent.com/65363206/106487599-d362ef80-6480-11eb-99b6-7823dcddb84a.png)

Apparently the CONFIG file is still not properly maintaining the path to various bits. If found the front matter PDF button did not open to the proper folder (it opened to the project's  "PrintDraft" folder rather than the "shared\ptxprint" folder where I keep the file.

Also the end of book PDF button opened up in the buried Program Folder rather than at the project's "shared\ptxprint" folder, where I keep these things. 

Resetting this to look in the correct place acts like it is going to work, but it **still fails** on PRINT, because PTXprint insists on using the "Program Files\PTXprint\ptxprint\PDFassets\border-art" folder rather than keeping track of what the user has specified.

 Accepting that default location and default filename allows the PRINT to work. But it needs to allow users to specify their own files and locations.

**Comment by davidc86** [comment]
Correction: 
The config file was trying to maintain the path, but PTXprint v1.5.9 is not paying attention to it. 
Here is a compare between what I had to do to get it to work on the LEFT (v1.5.9) and what used to work (v1.5.8) on the RIGHT:

![image](https://user-images.githubusercontent.com/65363206/106491386-d069fe00-6484-11eb-92dc-99c78b059e93.png)

So on the RIGHT, the older config file was maintaining the correct path and file name to the art. But v1.5.9 failed with this configuration.

The left shows that I was required to revert the spec back to the default location and name to get PRINT to work.

**Comment by mhosken** [comment]
I'm sorry. I don't follow. The error says "I can't open the file C:/My Paratext 9 Projects/SLU/shared/ptxprint/EndOfBookDesign.pdf". I don't see any reference to the main assets. Now it may be that in failing to find that file, ptxprint is falling back to a default file (which is probably not a good idea), and that is what is getting saved in the config.

**Comment by davidc86** [comment]
It may be saying that, but why it says that doesn't make any sense, because I haven't moved the PDF file nor changed it in anyway. Here it is: 

![image](https://user-images.githubusercontent.com/65363206/106690811-70687a00-65a0-11eb-8523-6efcccebb30e.png)

**Comment by davidc86** [comment]
I just verified that this is still an issue in v1.5.9.1 (once I got that version to launch, Thanks Mark!)
So, the file is there, but it doesn't like it anymore :(
I did notice that when I opened it in Acrobat Reader, and then closed it. Reader asked if I wanted to save changes??? Not sure what that is about. (This is actually a copied version of your "decoration.pdf" file, to use as a test, so I'm not sure why Reader thinks there is a need for changing it.)

**Comment by davidc86** [comment]
So I saved the PDF to a new file name, and loaded that into the border art instead. And now PTXprint supposedly creates a PDF file, and Acrobat Reader opens, but then says: 

![image](https://user-images.githubusercontent.com/65363206/106692987-8fb4d680-65a3-11eb-8ef0-12779384103a.png)

No idea what is going on here. No problem with these files in v1.5.8. Any clues?

**Comment by davidc86** [comment]
The saga continues. 
So I exited out of Acrobat Reader and tried clicking the PRINT button again just to see what is going on, and I got this:

![image](https://user-images.githubusercontent.com/65363206/106693208-fafea880-65a3-11eb-83b3-df1a358caaa3.png)

So, maybe I should revert back to v1.5.9?

**Comment by davidc86** [comment]
BTW, if nothing else comes of this, PTXprint should at least use the User-specified path and folder location in the Config file whenever the user clicks the Select... button. (ie reopen the folder where his/her stuff is rather than in the Program Files... folder).

**Comment by markpenny** [comment]
All good input. I'm sure these things are related to the change to "disconnect" Paratext, and allow PTXprint to run without it. We'll get there in the end, but my apologies for the bumps in the road...

**Comment by davidc86** [comment]
No problem. I just ran 1.5.9.3 and it prints the PDF just fine with the decoration.
So, all back to "normal" but further down the pitch! So well done. Detaching is always a like untangling spaghetti. So this can be closed and if you want to, the "keeping the path" might be a later "to do" thing?
