### ISSUE TITLE
v1.5.9 shows picture boxes rather than the files

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#373]
Showing boxes instead of pictures occasionally happened in in v1.5.8, but I could not find a pattern, though I suspected it had to do with making changes and then printing again. 

I just verified this in v1.5.9: If I see boxes in the PDF, then if I close PTXprint, and reopen it, and click PRINT, it will output the pictures correctly in the PDF (without me doing anything to any setting).

So there is some glitch in PTXprint where printing, and then making tweaks to the settings and printing again causes it to not export the pictures to the PDF file.

**Comment by davidc86** [comment]
Okay, it's worse than that. Just click Print more than once will cause the pictures to show as boxes in the PDF. On start up PTXprint prints the pictures correctly on the first click of PRINT. But all subsequent Prints mess up. This I have verified even if I don't do anything between clicks except to close Acrobat Reader and click Print again.

**Comment by markpenny** [comment]
Sorry David that you're still struggling with this. Can you help us eliminate a few more variables (as none of us are able to replicate this here).
1. Can you try this on a completely new/different project with no shared/ptxprint folder at all - and see if it happens there as well.
2. In the project where this *is* happening, do you have a PicLists folder? If so, can you delete/rename that (I'm wondering if it is trying to read that in again)
3. Probably the best way to track what has happened between one run and the next is to get 2 or more (before+after) Archive files (with temporary files) - which might help us see what setting is changing between runs.
![image](https://user-images.githubusercontent.com/12962708/106520995-73348200-6542-11eb-9a8a-d812d38bc739.png)
4. I'm not sure what else to suggest - other than taking a look through TeamViewer or Zoom to poke around and watch what might be happening. (If you want me to do so, then let me know in the next 2-3 hours by Skype: mjpenny)

**Comment by davidc86** [comment]
Hmmm. In version 1.5.9.3 we don't get the boxes, we actually get a full failure to open in Acrobat Reader:

![image](https://user-images.githubusercontent.com/65363206/106693943-87f63180-65a5-11eb-9f67-f0992be8b07f.png)

The first time I opened PTXprint v1.5.9.3, I immediately hit print, and it opened with the pictures and decoration etc.
I closed Acrobat Reader, and then clicked Print again in PTXprint. Acrobat Reader opened, but failed to open the file. And if I try to open the file directly, it still fails to open. 

SO, I opened it with Libre Office Draw, and it fails with: 
![image](https://user-images.githubusercontent.com/65363206/106694293-4023da00-65a6-11eb-88cb-c66c2e33aaac.png)

**Comment by davidc86** [comment]
Wow! Okay, I just checked the box "keep temp files" to help you all figure out what might be bombing the process: 

![image](https://user-images.githubusercontent.com/65363206/106695223-27b4bf00-65a8-11eb-9e0b-a7d181e7a44b.png)

Most important: keeping the temp files fixed the issue! Now I can click Print over and over each time, and generates a well formed PDF. So maybe if the "keep temp files" box isn't checked, the cleanup operation is too aggressive? Or maybe PTXprint assumes more files are kept than are, for subsequent PRINTs in a given session?

**Comment by markpenny** [comment]
> Most important: keeping the temp files fixed the issue!

Great sleuthing - now we have something to work with...
