### ISSUE TITLE
v1.5.9.1 fails to launch

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#374]
Well bummer. Just installed v1.5.9.1 to see the tweaks, and got this:

![image](https://user-images.githubusercontent.com/65363206/106611794-60b44b80-6536-11eb-97e5-0b961a1c77cd.png)

Also, this shows up each time I try to launch PTXprint now. So I'm afraid v1.5.91 broke the installation.

**Comment by markpenny** [comment]
Grrr... yes, we're sorry! I've found the bug which is causing it to fail on start-up (and so removed 1.5.9.1 from the site). However, if you want a workaround, I think this should get you back on the road. Edit this file:
`C:\Users\YOUR-USERNAME\AppData\Local\SIL\ptxprint\ptxprint_user.cfg`
And add a final line:
`lang = en`

Try re-starting, and you should have something to test again.

**Comment by davidc86** [comment]
Sweet. That got it open!
So maybe PTXprint needs a fallback behavior, like if some how a specified language doesn't exist or somehow got deleted, then it reverts to Lang = en 
so it can at least launch?

**Comment by markpenny** [comment]
Fixed in 1.5.9.3

**Comment by davidc86** [comment]
Cool! Thanks. I just got it. Didn't see it before.
