### ISSUE TITLE
Image with vertical bars

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#377]
I’m doing a bit of testing inserting images, and I have one image that insists on printing with vertical bars on the side:

![image](https://user-images.githubusercontent.com/14953913/106824523-4b990300-6683-11eb-9ca2-57b0ca6d39d7.png)

I have trimmed the image a couple of times, to really make sure there aren’t any lines there, and there aren’t any. I can insert the image in Word and there are no lines. Another test image shows up fine. This is with latest 1.5.9.3.

**Comment by jeffheath-sil** [comment]
Shows up with lines in the preview as well:

![image](https://user-images.githubusercontent.com/14953913/106824933-2bb60f00-6684-11eb-821e-e72107088ccc.png)

**Comment by mhosken** [comment]
I'm going to push back a little and say that I think ptxprint is looking somewhere else than where you think it does, for its pictures. You can test this by selecting the "Remove image borders" in the Pictures/Settings tab and the bars should disappear (and the images get very slightly larger on the page).

**Comment by jeffheath-sil** [comment]
I hadn't even seen the "Remove image borders" option. Sure enough, when I check that, the bars disappear. So this is sort of a minimal crop?

You say you think PTXPrint is looking somewhere else for the pictures, and sure enough I found a "figures" folder in the project, with low-res .jpg files, and vertical bars on that image. Looking around a bit more in the interface (I usually don't do much with images in my part of the world, but I'm trying to do a demo for others...) I found the place where you select the image folder, and when I select the place with the high-res images, the images look great even without the "Remove image borders" option.

**Comment by mhosken** [comment]
Yes, that option is a hack to spot lines around the edges of pictures which are so hard to spot since most picture viewers put the image on a black background. It just scans inwards until it finds a scan line with less than 80% black and trims the rest.

**Comment by jeffheath-sil** [comment]
Very clever that... :-)
