### ISSUE TITLE
Missing Reference Range in Header

### ISSUE THREAD

**Issue by rfpng** [sillsdev/ptx2pdf#379]
I did some tests printing a few chapters of Genesis, but the Reference Range in the header was always empty, although it was specified in PTXPrint. I checked the \h and the \toc1-3 markers in the book and the book names in the Scripture Reference Settings. They were there! 
Then I finally found out that I had an additional empty \h marker after the \toc1-3 markers. After I deleted it, PTXprint worked as expected. 
It would be great if PTXprint issued a warning in such a case. 
(Actually Paratext's Basic Checks doesn't report a second \h marker as an error. But I think it should. I'm running 9.1)
And thanks for fixing the fatal error in 1.5.9.1. I had run into that too.

**Comment by markpenny** [comment]
@mhosken - is this something that you would want to do in the USFM auto-correct, or should we handle it with the rest of the RegExs which tidy up similar things? We just need to (optionally, FLAG and then) delete empty \h fields.

**Comment by markpenny** [comment]
This has been fixed for 1.5.10 due to be released within the next 24 hours.

**Comment by rfpng** [comment]
Thanks. That's great! (Wasn't really problem for me anymore, I think, but it might help others.)
