### ISSUE TITLE
Case mismatch in illustration filename crashes PTX Print

### ISSUE THREAD

**Issue by KimB2017** [sillsdev/ptx2pdf#38]
I just updated to PTXprint 0.4.5 beta, on Wasta 18.04.

My PT project has LB... and HK... TIF files specified. I have been puzzling over how PTXprint handles pictures: They are not working for me in 0.4.4 at all, though I could get some of them working in a previous PTXprint version that I think I downloaded just before 14 March (based on some of my output file dates).

Assuming that TIF files are not yet working, I have been requesting pics from the [project]/figures (lo-res) directory. But the same thing happens when I request pics from local/figures. It looks like this happens when I click Print Preview:
If "Include Pictures" is ticked each illustration in the selected folder is copied from the lo-res figures folder into [project]/PrintDraft/tmpPics/. Uppercase in the original filenames is copied into tmpPics as lowercase. Print Preview then fails on the first such filename with a message, "unable to load '.../PrintDraft/tmpPics/LB00296.jpg'. If I manually rename tmpPics/lb00296.jpg to LB00296.jpg that picture "works".

The above happens whether or not I specify to use a piclist.

**Comment by markpenny** [comment]
Hi Kim, Sorry - yes, this is very much a work-in-progress right now (especially with the illustrations) and we'll still be working on this area of the code over the next few days. For now, keep the illustrations turned off (until further notice!)

**Comment by KimB2017** [comment]
Thanks, Mark!

**Comment by markpenny** [comment]
Could you try out the latest version 0.4.7 which attempts to preserve the case of any files in the PicList definition, and hopefully handles inline \fig ... \fig* illustrations more consistently. I appreciate your comments and feedback... BTW - are you running the Windows package, or are you getting this to work under Linux?

**Comment by markpenny** [comment]
@KimB2017 If you hang on with your testing until we've got 0.5.0 Beta out of the door in the next few days, then you can test some new functionality (TIF images can automatically get turned into PDF images and used as illustrations). I hope it works well for you, and makes illustration handling a whole lot easier.

**Comment by markpenny** [comment]
@KimB2017 I've just shared 0.4.8 which has the improved illustration handling. Do you want to give that a try and let me know if the case-mismatch issue has been solved. Am I right in thinking you're running this on Windows? If so the URL for the download is here: http://tiny.cc/ptxprint

**Comment by markpenny** [comment]
MH has spent considerable time today making it work right for Linux (with various case-sensitive-related issues fixed). XeTeX now also handles USFM2 markup too, which is wonderful! I'm closing this issue now, but feel free to re-open it if you're still encountering problems. There will be an e-mail later today regarding ver 0.5.0 beta - in which these changes will be.
