### ISSUE TITLE
new developer trying to get setup....

### ISSUE THREAD

**Issue by qfps** [sillsdev/ptx2pdf#380]
I don't know if this is the right place to ask... I am trying to setup a development environment in Windows 10 to help a friend of mine troubleshoot pxt2pdf.

If I run setup.py from Idle, the MSVC Tool fails with missing glib-object.h

If I run setup.py from a cygwin terminal and the cygwin python package (which also calls the MSVC tools) I get the same error. Note that glib-object.h is present in /usr/include/glib

I installed Pygobject with Msys2, when trying to run setup.py from a msys2 terminal, I get a "missing cairo" error.

What is the best way to setup the development environment for ptx2pdf?

Thanks.

**Comment by markpenny** [comment]
Thanks for wanting to help. We appreciate it. Trying to get the development environment working in Windows 10 is a bit of a nightmare. We managed to do this once after a LOT of frustration. Last year a summer intern joined the team and went through the same pain but documented the steps to set up the environment. We thought these instructions were stashed away somewhere safe in this repo, but none of us can find them (yet). We've written to the intern to see if he can find a local copy of his own instructions which you should be able to follow. Thanks for your patience...

Getting going in Linux is a LOT easier, but that's another topic!

**Comment by markpenny** [comment]
We now have a document outlining the [steps to get setup to develop PTXprint in Windows](https://github.com/sillsdev/ptx2pdf/blob/master/docs/dev/WinDevEnvSetupGuide.md)

Please let us know how it goes, and if you encounter any issues - we'd love to improve that guide in order to enable others to get involved without too much pain.

**Comment by qfps** [comment]
it looks close to what I was doing but there might be a subtle difference, I will try it this week end.

**Comment by qfps** [comment]
Ok it worked. I can run the "python python/scripts/ptxprint -p test/projects -f test/fonts"

My problem was probably something missing from the long list of python packages. 
I use TortoiseGit.

The only change you could make to that guide is where it says "pwd (this will tell you where to go later)" and the next command is "cd c:/users/<your username>/ptx2pdf" which should use what you got from the pwd command.

Thanks.

**Comment by markpenny** [comment]
Thanks for the suggestion. I've made an improvement to those instructions:
![image](https://user-images.githubusercontent.com/12962708/110709765-977e2f80-8261-11eb-8cf7-a7a5cc2b26a9.png)

Have you been able to get it up and running? Which are the areas that you would like to contribute to?
