### ISSUE TITLE
v1.5.10 fails to print with an issue with the colophon 

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#386]
I tried to set up the colophon to look more like what we are wanting for the published scripture. I included titles and other details. Apparently this is not allowed?

Here is our copyright page (or at least closer to it than what the default colophon provides): 

\pc BRIT ERAS MARKUS IKESKYE
\pc ti tel Maslyarkwe, Maluku, Indonesia
\pc KABAR BAIK YANG MARKUS MENULIS
\pc dalam bahasa Selaru, Maluku, Indonesia
\pc THE GOOD NEWS WHICH MARK WROTE
\pc in the Selaru language, Maluku, Indonesia
\pc \zcopyright
\pc \zlicense
\pc \zimagecopyrights
\pc ---
\pc Buku ini ditulis dalam bahasa Selaru [slu].
\pc Untuk informasi atas bahasa ini, mari menuju ke situs:
\pc https://www.ethnologue.com/language/slu
\pc dan
\pc https://www.selaru.org
\pc Buku ini disponsori oleh:
\pc Yayasan Pemberdayaan Masyarakat Desa
\pc Jln Ki Hajar Dewantoro
\pc Saumlaki, Kabupaten Kepulauan Tanimbar, Maluku 97664
\pc Edisi Percobaan
\pc YPMD-KKT

Are we not allowed to add text?

**Comment by mhosken** [comment]
Please send an archive

**Comment by davidc86** [comment]
Can't. V1.5.10 fails to create the archive. If you tell me what you want to see I can zip it up.

**Comment by mhosken** [comment]
Yes, we do want to allow you to do things like this. In fact we encourage that. This is what we envisaged as being the way to handle colophon information at the front of book collections. The final colophon was designed to encourage producers of single books to at least have _something_ in the way of copyrights in what they may produce informally.

**Comment by markpenny** [comment]
I don't know yet if MH has fixed something in my (local) version, but it seems to more-or-less work for me:
![image](https://user-images.githubusercontent.com/12962708/107825487-13629480-6de8-11eb-89bd-fc9d539f9139.png)

I had to try some different things to protect the // and / codes in the URLs, so please be aware that you need to add a **space** after any forward slashes. So to get the above URLs to render correctly, I used this (below). Also note that you can use \b to add a blank line between pieces (as empty \pc and \p just disappears):
```
\pc https:/ / www.ethnologue.com/ language/ slu
\pc dan
\pc https:/ / www.selaru.org
\b 
\pc Buku ini disponsori oleh:
```

**Comment by davidc86** [comment]
Thank you! Using your suggestion/trick, I got this more representative copyright page "colophon" to work.
Suggestions/Needs:
1) The editor used in that window is very, very limited. I can move the cursor out of display box (i.e. the text does not scroll to keep the cursor visible inside the box).
2) Hitting <Enter> at the end of the line does nothing visible (it does something, but it isn't visible)
3) To insert a line, I have to start typing it at the beginning of the line and then hit enter to move the current line below it.
4) It is tricky to add new stuff to the end of the colophon.
5) The editor should handle / more elegantly (like automatically add the space for the user, or do it in the background as the colophon is being written out).
