### ISSUE TITLE
v1.5.12 colophon is not picking up Horace Knowles illustrations, nor their joint illustrations

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#387]
The colophon is a nice idea for automatically find on which pages pictures are finally placed in the book.

But the colophon process is not finding any of the Horace Knowles pictures (marked with a filename "HK...").
Nor is it finding all of the Louise Bass pictures (marked with filename "LB..."). 
And I suspect it won't find the pictures that were done by Knowles and modified by Bass either (marked by filename "BK...").

These all have slightly different copyright notation requirements. This is taken from one of our publications: 

![image](https://user-images.githubusercontent.com/65363206/107695516-b4cdd700-6c7e-11eb-9088-eaa19a54da04.png)

It doesn't include the Knowles/Bass copyright line, but I'm sure there is a specification for it somewhere. And I might not be exactly right on these either, as things change from time to time.

**Comment by davidc86** [comment]
TIME OUT!
This issue may be a vestige of me not running the Pint process twice. (Making tweaks between runs, apparently means it then needs to be run twice, again, without tweaks, in order to get the colophon to work.)

Yet I see where you have a Quick option (which I am not using), because you say the normal Print process has to process the file a few times to get everything nicely sorted. Well, then why not just, **run it one more time, _automatically_**, when you see a flag that says it needs to run again to get the illustrations properly sorted? Is that possible? This way, when it finally opens, the PDF is fully formatted and correct.

**Comment by davidc86** [comment]
Well, even after rerunning it twice, it is still missing one of the Horace Knowles illustrations: 

![image](https://user-images.githubusercontent.com/65363206/107705179-5a3b7780-6c8c-11eb-950a-8a7f7441ebf0.png)

This is the missing illustration: 

![image](https://user-images.githubusercontent.com/65363206/107705342-9373e780-6c8c-11eb-8b00-2aa676786ee8.png)

**Comment by davidc86** [comment]
Any particular thing I need to do to let PTXprint know about these? I thought it just picked it up from the filenames.

**Comment by mhosken** [comment]
Normal drill. Please send an archive. Ta.

**Comment by davidc86** [comment]
When I try to build an archive, I get this: 

![image](https://user-images.githubusercontent.com/65363206/107725647-aef2e880-6cb4-11eb-9434-163f933e8625.png)

**Comment by markpenny** [comment]
Hi David. I can confirm that the code should be handling hk, lb and bk codes along with their appropriate copyright wording.
```
    "hk" : ("by_Horace_Knowles\n©_The_British \\& Foreign Bible Society, 1954, 1967, 1972, 1995.", "©_BFBS,_1995."),
    "lb" : ("by_Louise_Bass\n©_The_British \\& Foreign Bible Society, 1994.", "©_BFBS,_1994."),
    "bk" : ("by_Horace_Knowles revised by_Louise_Bass\n©_The_British \\& Foreign Bible Society, 1994.", "©_BFBS,_1994."),
```
Is there anything else different/special about that image?

Could you please send me the SFM file, and the generated .picpages file (in the PrintDraft folder) called something like this:
ptxprint-ConfigName-BUKXYZProjectName.**picpages**

**Comment by davidc86** [comment]
Are you sure your script is not case specific? Because all of my illustration files are HK..., LB..., BK..., and CO...., CN.... but their might be one or two that are Hk or hk etc. Not sure, I'm just using what Dallas gave us a few years back.

FYI, here is what we are looking for (eventually--I created this manually in a Front Matter PDF): 
![image](https://user-images.githubusercontent.com/65363206/107986709-a5aa9a00-6f9a-11eb-8a32-b35f981cfea4.png)

And here is not the current look of the colophon (after two runs): 
![image](https://user-images.githubusercontent.com/65363206/107987017-40a37400-6f9b-11eb-848a-7b972b65671d.png)

So it is getting much closer! Main things I'm seeing are:
1) Running header -- not wanted on the colophon/copyright page
2) How to add formatting like italic or specifying font size
3) How to add a national language version of the illustration's copyright fields?
4) Still missing several of the references to the British Bible Society's illustrations

**Comment by markpenny** [comment]
> Could you please send me the SFM file, and the generated .picpages file (in the PrintDraft folder) called something like this:
> ptxprint-ConfigName-BUKXYZProjectName.**picpages**

This would be really helpful to diagnose why it is missing certain illustrations...

**Comment by davidc86** [comment]
Here it is:
[ptxprint-SelaruNewPublication-MRKSLU.zip](https://github.com/sillsdev/ptx2pdf/files/5984184/ptxprint-SelaruNewPublication-MRKSLU.zip)

I believe the problem is your script does not ignore case. (I see where some of the Dallas illustrations are HK and some are hk etc.)

**Comment by markpenny** [comment]
Yes, you can use character styling in your colophon:
![image](https://user-images.githubusercontent.com/12962708/107994645-f0332180-7041-11eb-8f0c-fb35dc8f3772.png)

The list of character styles are here:
![image](https://user-images.githubusercontent.com/12962708/107994859-5d46b700-7042-11eb-8387-19580044cf3d.png)

We've got to fix the fact that the SmallCaps checkbox isn't checked even though it works to show small caps.

**Comment by markpenny** [comment]
Great - having your picpages file takes me straight to the problem (it is only finding 7 of the 27 pictures, and 2 of them just happen to be lb images):
![image](https://user-images.githubusercontent.com/12962708/107996048-515bf480-7044-11eb-950c-fe3c88935e92.png)
Should be an easy fix for the next version now...

**Comment by markpenny** [comment]
Needed to delete the 'x' in the last { } group! Now all will be well:
![image](https://user-images.githubusercontent.com/12962708/107996357-13130500-7045-11eb-9131-bad8c463508e.png)

**Comment by markpenny** [comment]
> So it is getting much closer! Main things I'm seeing are:
> 
> 1. Running header -- not wanted on the colophon/copyright page
> 2. How to add formatting like italic or specifying font size
> 3. How to add a national language version of the illustration's copyright fields?
> 4. Still missing several of the references to the British Bible Society's illustrations

2 and 4 are done. We should also auto tweak '/' to add a space after '/ '
Not yet sure about 1 and 3. MH may have some ideas.

**Comment by markpenny** [comment]
Thanks to some genius work by MH, we now have multilingual colophons possible (just by localizing the .json file [instructions to follow] and then adding the language code to the end of the \z magic code as shown below):

\pc \zimagecopyrightsEN
\pc \zimagecopyrightsIN
\pc \zimagecopyrightsFR - JH has already localized this for French which shows how it works

\zpchi zimagecopyrightsHI - by using a different code than \pc (i.e. \zpchi) I can assign a different script/font to this one
