### ISSUE TITLE
v1.5.10 footnotes have gone off the rails!

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#388]
No idea what is going on here, but now some of my footnotes have gone off the edge of the paper.

![image](https://user-images.githubusercontent.com/65363206/107695905-3de50e00-6c7f-11eb-9a51-d713d2dcbcae.png)

Any clues?
I strongly suspect special strings in footnotes are being treated as though they don't have valid spaces in them, and is treating the marked strings a though they are all one word! Still not sure why that gives this kind of weirdness, but at least it might explain some of the weirdness I'm seeing. 

Not sure when that started, because earlier today, v1.5.10 didn't have this problem. So I don't know what I might have tweaked that messed this up.

**Comment by mhosken** [comment]
Guess what? Yup. Please send an archive.

**Comment by davidc86** [comment]
Got this while trying to make an archive: 

![image](https://user-images.githubusercontent.com/65363206/107725086-5d962980-6cb3-11eb-9913-0a08defda517.png)

Not sure what that is about.

**Comment by davidc86** [comment]
This footnote bug has disappeared now in PTXprint v1.5.11 and v1.5.12
