### ISSUE TITLE
Linux: PrintDraft Error message screen gets hidden behind other windows

### ISSUE THREAD

**Issue by KimB2017** [sillsdev/ptx2pdf#39]
Wasta 18.04.3 with Cinnamon, PTXprint 0.4.5:

When Print Preview fails, the error screen must be cleared [OK] before anything else can be done, but this screen gets hidden behind any other window that comes into focus, so it can't be seen. The only way I can find the error screen is to "show desktop" and then select the single PTXprint window indicator icon from the Panel. Then the main window and the error screen both appear.

**Comment by markpenny** [comment]
@KimB2017 - Thanks for raising this. It is now fixed for ALL pop-up dialog boxes and error messages. These will always stay on top until they have been cleared. Will be available in ver 0.5.0, hopefully later today.
