### ISSUE TITLE
Proposed UI wording change to make things clearer

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#391]
An advanced user commented to me that "Paragraphed Footnotes" doesn't actually communicate much to them. Instead, they suggested this wording **"Start each Footnote on a New Line"**, and have the option turned OFF by default.
![image](https://user-images.githubusercontent.com/12962708/107826925-a8ff2380-6dea-11eb-8688-127cbe2ea0e9.png)

Thoughts? Feedback?

**Comment by mhosken** [comment]
Sure. Always nice when things default off

**Comment by markpenny** [comment]
Fixed in version > 1.5.12
