### ISSUE TITLE
v1.5.12 the Search feature in Styles has died 

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#395]
I believe this was working in v1.5.10, but now in v1.5.12 it is not working. Clicking in it does nothing.

**Comment by markpenny** [comment]
Strange - it still works for me. Are you saying that if you type wj in the top search bar, nothing changes in the view below? It should at least open up the tree so that you can see that marker.

**Comment by davidc86** [comment]
I mine, that search bar does not respond to anything I do. I can't click in it, I can't type in it.

**Comment by davidc86** [comment]
Well, now I can! Crud. Intermittent -- the worst.

**Comment by markpenny** [comment]
okay - we'll keep an eye on it. But for the moment I'll close this issue. Put it down to GTK having a bad day :-) 
Feel free to re-open if it misbehaves again in future.

**Comment by davidc86** [comment]
Okay. I looks like if I click in that space after the magnifying glass, it seems to open the text box. But if I hover over the magnifying glass, _the cursor changes to an insertion mark_, but clicking there does not work. So, to be totally obvious, the click "hot zone" should be expanded to include anywhere inside the search box.
