### ISSUE TITLE
Project with OT lists Matthew and Mark twice

### ISSUE THREAD

**Issue by philleckrone** [sillsdev/ptx2pdf#4]
In my Bible project the books of Matthew and Mark appear in the list followed by the OT and then the NT with Matthew and Mark repeated.
![Screenshot 2019-11-20 08 03 01](https://user-images.githubusercontent.com/37958474/69243409-00bfc800-0b71-11ea-9234-7e94266a8991.png)

**Comment by philleckrone** [comment]
I was running PTXprint-0.2.exe

**Comment by markpenny** [comment]
This is also fixed now. You can grab v0.2.1 from the same link: [http://tiny.cc/ptxprint](http://tiny.cc/ptxprint)
