### ISSUE TITLE
[ptxprint] Stylesheet \TextType of \d should be section (depending on use of \cl vs \d)

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#40]
When \d is in use but not \cl,  the stylesheet '\Marker d' ought to include  \TextType Section rather than 
\TextType VerseText

When \cl is used, or there are no \d markers, this doesn't matter, but VerseText is taken to mean that the text should immediately follow the chapter number. I've not proven a down-side to making 
it type Section  all the time, but there may be one.

[Edit: This is/was obviously a known issue, because I've just spotted Paratext8 adds an override for this to printdraft-mods.sty.]

**Comment by markpenny** [comment]
[Usage note](https://ubsicap.github.io/usfm/chapters_verses/index.html#cl): _If \cl is entered once before chapter 1 (\c 1) it represents the text for “chapter” to be used throughout the current book. If \cl is used after each individual chapter marker, it represents the particular text to be used for the display of the current chapter heading (usually done if numbers are being presented as words, not numerals)._
@davidg-sil Could you confirm that it is only if \cl is used AFTER the \c # that we don't need to "fix" anything. But I am assuming that if \cl is used in the book BEFORE the \c # (as a generic chapter label - as seen below) we would still need to apply this fix/override, making 'Marker d' \TextType Section.
```
\cl Psalm
\c 1
\q1
\v 1 Happy are those
\q2 who reject the advice of evil people,

```
Are there any drawbacks of ALWAYS making Marker d as a Section type?

**Comment by davidg-sil** [comment]
On Tue, 21 Apr 2020, 17:26 Mark Penny, <notifications@github.com> wrote:

> Usage note <https://ubsicap.github.io/usfm/chapters_verses/index.html#cl>:
> *If \cl is entered once before chapter 1 (\c 1) it represents the text for
> “chapter” to be used throughout the current book. If \cl is used after each
> individual chapter marker, it represents the particular text to be used for
> the display of the current chapter heading (usually done if numbers are
> being presented as words, not numerals).*
> @davidg-sil <https://github.com/davidg-sil> Could you confirm that it is
> only if \cl is used AFTER the \c # that we don't need to "fix" anything.
> But I am assuming that if \cl is used in the book BEFORE the \c # (as a
> generic chapter label - as seen below) we would still need to apply this
> fix/override, making 'Marker d' \TextType Section.
>
> \cl Psalm
>
> \c 1
>
> \q1
>
> \v 1 Happy are those
>
> \q2 who reject the advice of evil people,
>
>
I've tested both positions of \cl. If \cl is being used consistently then
it makes no difference, they both suppress the drop-cap. (cl after removes
the chapter number entirely).

Are there any drawbacks of ALWAYS making Marker d as a Section type?

**Comment by markpenny** [comment]
MH decided that it would be best to ask the PT Devs  / USFM Steward about why this known issue with the Stylesheet is still around. What is the reason that the default value in PT's stylesheet is \TextType VerseText rather than \TextType Section. Could the default be changed globally? Or is there a special reason for it to stay as it is?

**Comment by klassenjm** [comment]
A comment on `\d` being VerseText by default and not Section. I think that the main reason for this will be the fact that the descriptive title / Hebrew sub-title is verse 1 in some church / text / versification traditions. I expect that having this as Section by default would likely have some consequence for how Paratext treats the content when it is verse text.

**Comment by markpenny** [comment]
Thanks @klassenjm - That wider perspective is really helpful Jeff. We'll need to put something into PTXprint to work around the issue.

**Comment by markpenny** [comment]
Yes, this is already in 0.6.9, but we don't yet test for the presence of \cl  -which would make it more smart, rather than relying on the user to put it "back" in their stylesheet.
