### ISSUE TITLE
Vertical placement of section head text (with borders) depends on whether it has descenders or not

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#402]
When I put a border around a section heading, I’m seeing that the text is placed differently within the border if it doesn’t have any descenders. For example, look at the difference in vertical position in the text of these two borders:

![image](https://user-images.githubusercontent.com/14953913/108498680-8323c400-72ad-11eb-8d50-d07de79418fb.png)

The borders are being placed consistently, but a section head text without descenders is placed much lower.

This does bad things when the section head is at the top of a page, because a section head with descenders appears fine:

![image](https://user-images.githubusercontent.com/14953913/108498887-c716c900-72ad-11eb-9548-cbfb15ef9667.png)

But for a section head without descenders, XeTeX thinks it has room enough to fit the section head on one line:

![image](https://user-images.githubusercontent.com/14953913/108498995-f299b380-72ad-11eb-8279-862a7c7669cf.png)

**Comment by mhosken** [comment]
Fixed the top of page issue. More thought needed on the descenders problem.

**Comment by mhosken** [comment]
Added a legacy compatibility option to use glyphmetrics for line heights. Disable this to get what you want.

**Comment by jeffheath-sil** [comment]
In case anyone else is looking for it... It's on the Advanced tab, in the Compatibility box. And that seems to take care of the problem.

The pop-up for this new option says this:
![image](https://user-images.githubusercontent.com/14953913/108683190-8e673180-74f1-11eb-8bcc-e2de7e931a29.png)

That sort of begs the question... If font metrics gives more consistent results, why would you use glyph metrics? I'm OK leaving it in (with this option), but I just thought I'd ask.

And assuming you do The Right Thing with that question, as far as I'm concerned you can close this issue.

**Comment by markpenny** [comment]
Here's how I understand it working...

For any new projects, it will automatically default to the better way of working (i.e. that option to "Use glyph metrics" will default to being OFF). But in order to not break everything for everyone else, existing projects will continue to use the legacy "glyph metrics" - so that box will stay checked for them. But they are free to uncheck it...

Does that make sense as to why it is ON for you? But hopefully OFF for anyone starting out fresh...
