### ISSUE TITLE
Finding fonts

### ISSUE THREAD

**Issue by devosb** [sillsdev/ptx2pdf#404]
In https://github.com/sillsdev/ptx2pdf/issues/398#issuecomment-780434903 @markpenny wonders what changed. The change might have been [removing some (thought to be) un-needed](https://github.com/sillsdev/ptx2pdf/issues/355#issuecomment-768657430) files from the XeTeX setup that is used on Windows. At least some fonts were removed then, I don't know if their removal is related to the [comment](https://github.com/sillsdev/ptx2pdf/issues/398#issuecomment-781821781
) that closed the above issue.

I noticed @mhosken [has recently changed how fonts are found](https://github.com/sillsdev/ptx2pdf/commit/dc9f665829d1804805650ce81e54c16be7005521). One of the changes was to switch away from using the `cmtt10` font, which was one of the fonts that was removed (in the `bluesky` folder) but the font that was removed was a Type1 font, and [`cmtt10.tfm`](https://github.com/sillsdev/ptx2pdf/blob/master/xetex/share/texmf-dist/fonts/tfm/public/cm/cmtt10.tfm) still exists.

Another change in that commit is in the xetex folder. When the xetex files are updated to TL 2021 in a few months, the change to [fonts.conf](https://github.com/sillsdev/ptx2pdf/blob/master/xetex/share/texmf-dist/fonts/conf/fonts.conf) will be overwritten.

**Comment by mhosken** [comment]
Is there some action required here, or is this just a comment for the history?

**Comment by devosb** [comment]
The first two paragraphs are for history. The third paragraph requires action if the change made to fonts.conf need to persist after a TeX Live update.

**Comment by mhosken** [comment]
We now autogenerate the fonts.conf we use, so changing the one in texmf makes no difference.
