### ISSUE TITLE
v1.5.13.1 Error Dialog while editing the Style Sheet 

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#405]
I was just looking around in the style sheet, selected a factor size value, and I had just pressed Ctrl-C to copy it (to use in other similar styles), when this dialog popped open: 

![image](https://user-images.githubusercontent.com/65363206/108607272-58a93800-738d-11eb-8283-0714223be1cc.png)

I've no idea what that is even saying. The only thing I can think of is that I may have accidentally pressed Ctrl-V rather than Ctrl-C (or maybe Ctrl-Z?), and something in the clipboard didn't agree with PTXprint. Other than that I don't have any ideas.

**Comment by markpenny** [comment]
Fixed for 1.5.13.3
