### ISSUE TITLE
Excluding introductions misses some markers

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#406]
If I choose not to include the book introductions (option on the Body Text tab), there are still some introduction markers that are left in the text. Specifically I have a case where I have excluded the introduction (since it will be included as part of a PDF file inserted in the typesetting), but the \imt1 marker has been left in the typesetting. (It's possible other intro markers are also not excluded...)

**Comment by markpenny** [comment]
Thanks for the heads-up. Yes, I've updated the regex to find them all now - as it was missing several from this definitive (?) list:

`\\i(b|ex?|m[iqt]?|mt[1234]?|mte[12]?|p[iqr]?|q[123]?|s[12]?|li[12]?) .+?`

![image](https://user-images.githubusercontent.com/12962708/108688468-cfe0f680-755c-11eb-8124-0b4fdd7a4e1b.png)

Note that the \\io markers are covered elsewhere as these can be toggled on/off separately.
