### ISSUE TITLE
1.5.14.1 Linux: missing font error?

### ISSUE THREAD

**Issue by KimB2017** [sillsdev/ptx2pdf#407]
PTXprint crashes this morning with this error message:

...
(/usr/share/ptx2pdf/texmacros/ptx-cropmarks.tex
! Font \idf@nt="Source Code Pro" at 8.0pt not loadable: Metric (TFM) file or in
stalled font not found.
l.37 \font\idf@nt="Source Code Pro" at 8pt

**Comment by mhosken** [comment]
grr. Packaging bug. Working on it. I thought I had fixed it. But clearly not. ANd it's not easy to check. It takes a while.

**Comment by KimB2017** [comment]
1.5.14.2 works. Thanks!
