### ISSUE TITLE
Clicking link to submit a problem didn't do anything

### ISSUE THREAD

**Issue by sewhite** [sillsdev/ptx2pdf#41]
In Viewer > Folders, I clicked the link to report an issue, and nothing happened. 
I came here to this URL to check and am writing this in my web browser.

**Comment by markpenny** [comment]
OK - I've managed to replicate the issue. I'll try to fix it for the next version.

**Comment by markpenny** [comment]
For now I've got a bit of a hack: **Right-clicking on the link** gives you an option to COPY-URL. I've updated the links to display that too.
We might get around to working out why this isn't working in the compiled version like it is working in the uncompiled version. (Low priority)
