### ISSUE TITLE
If colophon is longer than one page it fails to export

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#410]
If the colophon happens to be longer than one page, it fails to export.
This is complicated by the fact the colophon page puts in a running header (which a copyright page never has), and because we aren't sure how big it will be until after we try to print it. BUT if it is too long, it doesn't print at all, so that makes it difficult to determine what is wrong.

Just have PTXprint send out the colophon regardless. And if it is too long, the user can tweak the texts or the styles to get it to fit.

(And it would help greatly if we could use more of the top portion of the page, especially for our bilingual copyright text.)

**Comment by davidg-sil** [comment]
Yes. That the colphon mustn't grow beyond a page is a known issue stemming from how it was (intended) to be typeset as a 'below the footnotes, on the last page' box.
You may apply alternative settings to it by altering the styling for it in a (hand-edited) stylesheet (the colophon is typeset as `\esb \cat colphon\cat* ....\esbe`)

If you need it to extend beyond a page, then one option that might work is to set the position to `h` (here, i.e. inline), which, as long as there is no border/background colour, ought to just dump the contents as text if I remember correctly (warning: untested in months):
```
\Marker cat:colophon|esb
\Position h
```

Alternatively, the commands that include the bits of the colophon can be used in any front-/back-matter books.

**Comment by davidc86** [comment]
A more elegant way of failing would help here. 
Because if the colophon grows to be larger than what will fit on a page, it just doesn't show up! No explanation. So the user is confused and not sure what they did wrong. For example, their colophon was working just fine, then they decide it would look nicer with a blank line between the two language versions of the copyright text. Boom! Now it won't show up in the PDF, but not because they did something wrong, but rather because they happen to have added that extra line, which just so happened to push the size of the colophon over the invisible edge of its box. 

Maybe just a warning? 
"Sorry, you colophon exceeds what will fit on one page, so it cannot be displayed. 
Please shorten it, or reduce the font size for that text, so it will fit on a single page."  

BTW, I didn't see a "centered intro material paragraph" \ipc in the Style list. So I made one and used that to reduce the font factor to match the other intro material. Providing such a paragraph out of the box might be helpful.

**Comment by davidg-sil** [comment]
Yes, a warning should be possible. The longer term solution is to enable them to break, and that's the aiming point. When we first envisaged them the colophon was at most 5 lines long, so thoughts of them getting too big for a page didn't enter my mind. have you tried telling it to use position h?

**Comment by davidg-sil** [comment]
Warning now added to XeTeX log / screen output (python code might pick it up, I'm not sure):
Example output:
```
*** WARNING: Sidebar or colophon might not print on page 1. (534.15811pt high, 
and page is 527.89981pt)
```
It cannot report that it WILL fail, as not printing is a bug and (at this stage) all it knows is that its big.
(the warning triggers at 80% of the page size, as I'm not sure exactly when strange effects start happening).
