### ISSUE TITLE
The colophon edit box is not a usable text editor

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#411]
The colophon edit box is not a usable text editor. It looks like a single line editor being used for multiple lines.
* If we hit <Enter> it doesn't show the cursor moving down, nor does it open a line, until we start to type something.
* If we move the cursor down or up with the mouse, and the cursor moves out of view, the window does not scroll to track it.
* It does not support Ctl-Z for when we accidentally delete/backspace more than intended.

Is there not good open source editors available for these multi-line text boxes? 
Not complaining, just wanting this to be user-friendly, and it isn't right now.

**Comment by markpenny** [comment]
MH - I'm wondering why/how this text editor box is different from what we use on the View+Edit tab - as it all seems to work better there.

**Comment by mhosken** [comment]
Currently the colophon editor is a simple text edit. We use a gtksourceview for the View+Edit tab. But really, people who want to do serious editing of such matter should be using a FRT book and do the job properly. The colophon is included, as has been stated a number of times, as a fallback to ensure, encourage at least some copyright recognition. It is not designed to carry the wait of a full front matter colophon.

**Comment by davidc86** [comment]
Yes, the colophon should be fairly short text, but it doesn't have to be. So the outlying cases where someone adds a bit more information for their local area, it would be nice for the editor to act like a real editor. 

Hitting <Enter> and nothing happens, or allowing the cursor to scroll out of the viewable area of the box are both unexpected behavior. I don't think I've seen an editor do that in years (like DOS days, or early Windows 3.1 days). 

This is just an FYI, because if a better editor is easy to hook up here, it would be much nicer for end-users.

**Comment by markpenny** [comment]
We're still swimming against the tide on this one, trying to hack around a Glade/Gtk bug. But in the mean time we might have solved the Ctrl-Z (undo) which seems to work now.
So until we can figure out how to tame the GtkSourceView editor, all I can suggest is that you use an external editor and then copy-paste into this box.

**Comment by davidc86** [comment]
Wow. So what are/were you using on the View/Edit tab? That seemed to have a nicer editor. Maybe it just isn't as noticeable because it is a bigger window?
