### ISSUE TITLE
Unpacking DBL texts into Paratext's folder structure causes an issue with PT loading up

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#412]
I discovered today that the DBL project which I "opened" with PTXprint now annoys Paratext:

![image](https://user-images.githubusercontent.com/12962708/109213295-4c9dfa00-7815-11eb-94ed-23ca12cc1083.png)

Should we be doing something different, or should we get the PT team to ignore such projects?

**Comment by markpenny** [comment]
Presumably it is looking for something *else* in this skeleton Settings.xml file:

```
<ScriptureText><Name />
    <Language>Standard Arabic</Language>
    <Encoding>65001</Encoding>
    <CopyRight />
    <DefaultFont>Arial</DefaultFont>
    <DefaultFontSize>10</DefaultFontSize>
    <FileNamePostPart>OpenNewArabic.USFM</FileNamePostPart>
    <FileNameBookNameForm>41MAT</FileNameBookNameForm>
    <FileNamePrePart />
    <StyleSheet>usfm.sty</StyleSheet>
    <MinParatextVersion>8.0.63.1</MinParatextVersion>
    <FullName />
    <Editable>F</Editable>
    <BooksPresent>1111111111111111111111111111111111111110111111111111111111111111111000000000000000000000000000000000000000000000000000000000</BooksPresent>
</ScriptureText>

```

**Comment by mhosken** [comment]
Any chance of a Paratext backtrace/stacktrace on that error. It's on the sparse side. While it could well be the Settings.xml, that file doesn't contain a 'key'. So, there's something deeper going on here. Anyone on the PT team interested in helping is find our sins?

**Comment by markpenny** [comment]
> This issue has been added to our backlog, I will let you know when we are able to take action on it.
> https://paratext.myjetbrains.com/youtrack/issue/PTX-21053
> -Glenn

**Comment by FoolRunning** [comment]
Could someone that has this problem use **Help > Give feedback** inside Paratext to send a report (right after it happens)? That would make tracking down this problem much easier.
