### ISSUE TITLE
picChecks.txt ends up in wrong project when using a DBL bundle

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#413]
Looking at the configuration settings files of a newly unpacked DBL bundle I was surprised to see a picChecks.txt file which contained information from another project (presumably from the PREVIOUS project config that happened to be open at the time of opening the DBL bundle).

![image](https://user-images.githubusercontent.com/12962708/109214161-5aa04a80-7816-11eb-9000-9353f80ee258.png)

It also copies that file into the (Default) config folder, which doesn't seem right either:

![image](https://user-images.githubusercontent.com/12962708/109214843-32fdb200-7817-11eb-859c-7ffc01ddd35b.png)

**Comment by markpenny** [comment]
@mhosken - If I select a project that hasn't run ptxprint before (i.e. no "shared/ptxprint folder) then we get the same behaviour (it takes the settings from the existing project and copies them over to the new project). Instead of this, we need it to start with "fresh" default values.

**Comment by mhosken** [comment]
yup. Only copy config from within the same project not across projects.

**Comment by markpenny** [comment]
Yes - thanks. That's working properly now, and not stealing another project's config files.
