### ISSUE TITLE
Pictures in non-scripture "books" don't print

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#417]
I got FRT to print!
But I see that none of the pictures in the Front Matter and Back Matter or any other non-scripture book files (including Maps, etc.) are sent to the PDF file. I only see big boxes.
 
For earlier versions of PTXprint, we ignored the positioning of pictures in non-scripture files. But now that PTXprint has matured, these "books" should also have a way to anchor the pictures into their proper location (even if it is just "inline" with the text). 

Currently these pictures (logos and maps etc.) are not even listed in the Pictures tab. So we have no way to even specify "inline". (Minimally, "Inline" behavior would be very helpful, because current behavior puts the first map's box ABOVE the Title for the "Maps and Illustrations" book, rather than below the title. So even if nothing else, "inline" for non-scripture books would at least help us get things to layout fairly close to "nice".)

**Comment by davidg-sil** [comment]
No promises when it'll work, let alone released, but we at least have agreed a plan, and we're working on it...

**Comment by davidg-sil** [comment]
Commit 1fe8980d3afe527 (and a few beforehand) fixes half of the problem. There is now a (tentative) mechanism in the ptx2pdf macros to trigger piclist pictures from stand-alone milestones and glossary (```\k Keyword\k*) entries (roughly similarly to how verse numbers do it). The python code necessary to replace ```\fig``` entries in the `.usfm` files with stand-alone milestones and all the the necessary changes to the piclist editor have not been made.

**Comment by davidc86** [comment]
Thanks very much for looking into a solution for this! It will be very helpful. 

I have samples of various fiddly FRT and BAK files with illustrations hither and yon, if needed. 

The design of USFM and Paratext itself anchored to the \v field is problematic for all things related to managing "data in a computer" (\v breaks the data structure rule of mixing data types in a single field). But this is how it has been since the dawn of USFM implementation, so even though some of us have tried to get it changed.... no success. Meaning non-scripture sections of our projects are the "odd-man-out" when it comes to using Paratext Notes, or tracking changes, or synch scrolling, etc. And now it bites us again here with these unstructured "books". So, Yes! using special milestones sounds like a good, creative solution. 

Looking forward to how this progresses.

**Comment by davidg-sil** [comment]
If you're feeling brave, MH and MP have been working on the python side of things today, and I've been complicating the piclist format some more, just in case you need to anchor a picture to the 2nd paragraph of a given key term in the glossary. Very fresh documentation is here: https://github.com/sillsdev/ptx2pdf/blob/master/docs/documentation/figures.md#anchor-references

**Comment by markpenny** [comment]
Yes, we've made some good progress! Thank you DG and MH.

Here's what my BAK book looks like with cutouts:
![image](https://user-images.githubusercontent.com/12962708/110708925-49b4f780-8260-11eb-9832-d03bf490218d.png)

There are a few questions that we can discuss later - particularly regarding cutout vertical positioning (can #of lines to shift be a negative number?), and whether or not the cutout needs to heed paragraph indentation (ie. horizontal alignment).

**Comment by davidc86** [comment]
Wow! That is excellent!

But after reading the section on Anchor references in the ptx2pdf documentation, I'm not sure I understand the details yet. Maybe if it included some examples, like "Here is what the USF file looks like:" "And here is what the results look like:" (From the Paratext end-user's perspective.) 

I'm trying to put together a nice BAK book that includes all the maps we use in Acts, Jonah, and some other things like the temple. So basically it is a list of picture  \fig fields. But I could add something to contain these fields if needed.

Here is how it looks now:
\id BAK - Selaru
\h Gambar o Peta 
\toc3 Peta 
\toc2 Gambar o Peta 
\toc1 Gambar o Peta-nare 
\rem zthumbtab PETA 
\mt1 Gambar o Peta 
\mt2 ti Kitab Lanke 
\rem Di sini kita kumpul semua peta dalam Alkitab 
\c 1 
\p Ti ne tatos gambar o peta-nare ma klyosu o nam rakesy ti Kitab Lanke ne. 
\m \fig Nuske Ktem ne heitlulswo kyoat Yunus imorifke|alt="The world long ago when Jonah was living" src="PetaYunus_Selaru.tif" size="col" ref="Yun."\fig* 
\pc Matos ti Kitab Yunuske 
\m \fig Hulasokwe Seike ti kyoat Yesuske imin ti lasmyer khaha ne|alt="The Temple of God" src="LB00250B.TIF" size="col" ref="Luk. 4:11"\fig* 
\pc \xt Luk. 4:11\xt* 
\m \fig Nus o hnu ti lasmyer Palestinake|alt="The cities and towns in the land of Palestina" src="Holy_Land_BW-Selaru.tif" size="col"\fig* 
\pc Tnyetak Harharkwe 
\m \fig Saulus yor Barnabas wait laklakut mamunake ne|alt="Paul and Barnabas' journey 1" src="Paul1-BW_Selaru.tif" size="col"\fig* 
\pc \xt Kis. 13–14\xt* 
\m \fig Paulus wasi laklakut a kla-ruake ne|alt="Paul's journey 2" src="Paul2-BW_Selaru.tif" size="col"\fig* 
\pc \xt Kis. 15–18\xt* 
\m \fig Paulus wasi laklakut a kla-teluke ne|alt="Paul's journey 3" src="Paul3-BW_Selaru.tif" size="col"\fig* 
\pc \xt Kis. 19–21\xt* 
\m \fig Paulus wasi laklakutke bai nus lan Romake|alt="Paul's journey to Rome" src="Paul4-BW_Selaru.tif" size="col"\fig* 
\pc \xt Kis. 27–28\xt* 
\m \fig Nus o hnu a Paulus yor lianare rabrita Brit Eraske tiare|alt="Map of Italy to Middle East" src="PetaLokasi5T_Selaru.tif" size="col"\fig* 
\pc \xt 1Tes. 1:8\xt* 
\b 

I have no idea why, but when I pasted the text in here, all the line breaks were removed. 
Also, I'm not sure this is the best way to lay this out even for Paratext, let alone PTXprint. But I also need to be mindful of how it will export to Scripture App Builder (as it pulls from the same files).

Any ideas would be helpful.

**Comment by davidc86** [comment]
Okay, I got the Picture tab to accurately display the non-scripture pictures. and I can make tweaks to their specs.
But when I hit print, it still puts out boxes rather than the pictures. 
I suspect it is an error in how I've configured the USFM in my non-scripture books. Is there a way to leave the underlying USFM file untouched but tweak the markup on the fly so it is recognized correctly by the PTXprint process?

**Comment by davidc86** [comment]
I ask, because SAB and other applications work with the non-scripture books just fine as they are, so I don't want to tweak these books "to get them to work" with PTXprint, only to find out I've broken them for SAB etc. 
So, some direction/advice would be helpful. (v1.5.21 still produces boxes).

**Comment by markpenny** [comment]
@davidc86 - I am a firm believer in NOT tweaking the USFM text in order to please some downstream typesetting tool. So, yes, we have to figure out why it isn't doing what it should be doing. Some ideas:
a) Could you backup your existing settings, start from scratch (i.e. with no shared/ptxprint folder) and see if that gives the same result?
b) When you hit the Generate button in the Pictures area (for the peripheral books), are you getting valid PicList entries, and picture previews?
c) When you examine the Final SFM text in the View+Edit, do you see the (modified) \fig definitions with unique anchors that lok like this?
GLO .1
GLO .2
GLO .3 
d) If you're still unable to work it out, please create an Archive with 1 book with some pics, and the GLO book and we'll see if we can work out what's going wrong.

**Comment by davidg-sil** [comment]
Another thought... If you're able to look in the `PrintDrafts` folder, you ought to see a file like ```ptxprint-MyConfig-GEN_GLOPROJECT.piclist```
That's where PTXprint saves the piclist these days. If you have something you can persuade to open that text file (`notepad`? `vim`?) you ought not see any `.TIF` (or other spelling) extensions in there. If you *do* see any `.tiff` images in that file, then (a) something's gone wrong and (b) yes, you're going to have problems, because XeTeX's inner workings can't include `.tiff` images these days.

**Comment by markpenny** [comment]
> That's where PTXprint saves the piclist these days.

Yes, that file is generate by PTXprint at run time and contains the information MERGED from multiple sources. It is only temporary (so don't edit it!) and gets passed to XeTeX to insert the pictures.

Note that you should NEVER see `.TIF` files listed in there as PTXprint converts all the `.TIFs` to `.JPGs`
