### ISSUE TITLE
Mirrored David C Cook illustrations flip the (c) text

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#419]
Nice work so far on adding the (c) David C Cook text to each of their illustrations.
Problem: if the illustration must be flipped (because of the person doing something with their LEFT hand!) unfortunately if it's a DCC illustration, the (c) text flips too. (Cool, but not what we want :) )

![image](https://user-images.githubusercontent.com/65363206/110193442-e65f3b80-7e01-11eb-913b-c60e3bd287c2.png)

**Comment by davidg-sil** [comment]
Embarrassing bug hopefully now solved by getting the order right.

**Comment by davidc86** [comment]
Woohoo! Fixed indeed.
