### ISSUE TITLE
PTXPrint fails when illustration included

### ISSUE THREAD

**Issue by sewhite** [sillsdev/ptx2pdf#42]
I wanted a PDF with a figure and I got this error report
![image](https://user-images.githubusercontent.com/16904461/80279905-625f0200-86ce-11ea-8e78-e3413ac06d26.png)
If I turn off illustrations the PDF prints OK. 
Paratext project:
[PDFP 2020-04-25.zip](https://github.com/sillsdev/ptx2pdf/files/4532932/PDFP.2020-04-25.zip)
PrintDraft files:
[ptxprint-MATPDFP.zip](https://github.com/sillsdev/ptx2pdf/files/4532936/ptxprint-MATPDFP.zip)

**Comment by markpenny** [comment]
Hi Steve, [http://tiny.cc/ptxprint](http://tiny.cc/ptxprint) is now pointing to beta version 0.4.8 which has a whole lot of changes that were done in the last couple of days. My hope is that the illustrations are handled much better now. Would you mind trying out this latest version, please. If it still breaks, then I'll look at it again early next week.

**Comment by sewhite** [comment]
0.49 gives the same result, it fails when the illustration is included.

**Comment by sewhite** [comment]
Tested 0.50, still fails when illustration is included.
