### ISSUE TITLE
Need to get non-breaking spaces (or an Enter) in the copyright line 

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#420]
The current copyright line prints with a break between the (c) symbol and the org. This space should be non-breaking, or we need to be able to hardcode a Return/Enter in the copyright line.

Here is what our copyright line looks like:
**© 2021 Yayasan Pemberdayaan Masyarakat Desa-KKT dan © 2021 Wycliffe Bible Translators, Inc.**

Here is how it comes out:
![image](https://user-images.githubusercontent.com/65363206/110227295-c5135380-7ec4-11eb-9844-13642346fd1d.png)

It would be nice if PTXprint just replaced the normal space with a hard/non-breaking space after a (c) symbol. In fact, I'd probably want a hard/non-breaking space after the Year too, as that sitting by itself would also look weird. 
But the ability to force a line break after "dan" would be helpful too.

**Comment by davidg-sil** [comment]
Don't ```~``` and ```//``` "work" (as NBSP and preferred line-break respectively) in the colophon? I would expect them to, but maybe something odd is happening.

**Comment by davidc86** [comment]
Woohoo! Yes they do! 
But I was not aware of these, and I'm kind of a geek, so I can pretty much guarantee no MTT would know about these unless they need them a lot in their normal orthography.
Maybe a Popup Help Tip suggesting we use a ~ for places where a non-breaking space is needed, and using // where a line break is needed.

**Comment by davidg-sil** [comment]
For what it's worth:
https://ubsicap.github.io/usfm/characters/index.html#spacing-and-breaks

**Comment by davidc86** [comment]
Nice! Thanks. 
Everyday, new stuff.
Glad to know it is in there.

**Comment by markpenny** [comment]
I can add a few more helpful shortcuts to the colophon editor and mention them in the tooltip(s).
