### ISSUE TITLE
v1.5.18 "Generate..." Picture references for books UNCHECKS the "Only Show" option

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#422]
I realize the picture feature in non-scripture books is a new born babe. So, this may sort itself out. But the Generate... button is a bit spooky to begin with and users need to approach it with caution (if they've been working on books for a while now).

So having to first go to the Basic tap and selecting FRT or BAK to set these up as a target book is unusual, but I get it, it leverages a built in behavior to its advantage.
Then switching back to the Picture tab shows nothing, assuming the "Only Show..." box is checked. Good.
Clicking Generate... gives the proper book name in the pop up. Good. 
Clicking OK closes the dialog, but then it shows Genesis pictures in the list!! (Panic)
But then I see that the "Only Show" box is UNCHECKED. 
So I check it, and only the FRT pictures show in the list. Woohoo!

So, when a user clicks OK from the Generate dialog, PTXprint should not uncheck the "Only Show" box. Rather it should keep it and show only the targeted book in the list. 

Still considering where we were last week, this has come miles (or should I say kilometers)!

**Comment by markpenny** [comment]
Fixed in 1.5.19 - please check that the current behavior is as expected. Note that if you select to generate ALL books, then it will remove the filter. But it should retain the filter if the PicList is (re-)generated for just a subset of books.
