### ISSUE TITLE
"no project set" error 

### ISSUE THREAD

**Issue by KenK-3-21** [sillsdev/ptx2pdf#423]
Hello, I am suddenly having a problem with PTXPrint that is really unexpected. No matter what I do, the project and the program are frozen. At the bottom, I see the notice, "no project set". See below:
![image](https://user-images.githubusercontent.com/7024638/110863618-901d4d00-8286-11eb-9bc1-8224722b5151.png)

**Comment by mhosken** [comment]
Now you can't type in the project and get confused. You can only select it from the list. This is assuming you typed the project in rather than selecting it. You didn't tell us what you actually did to get into this state.

**Comment by KenK-3-21** [comment]
Sorry, Martin! Okay, I think what precipitated this event was that I had chosen "diglot"...which was set to my backtranslation project. Then I thought better of it, and set it to a different text. Then the program locked up.

**Comment by KenK-3-21** [comment]
Actually, what I wanted to do was grab the interlinear, but I don't see any provision for doing this...

**Comment by markpenny** [comment]
Hi Ken - look at the Advanced tab if you want interlinear. I'm closing this issue as it is unrelated.

**Comment by KenK-3-21** [comment]
Thank you for your response, Mark, but I still can't use PTXPrint...

Maybe I need to uninstall and wipe out any residual info.

Best, Ken

**Comment by markpenny** [comment]
Make sure you're using the latest version: 1.5.21 or later (1.6 should be out tomorrow).
If you want to start with a clean slate, then delete the folder called ptxprint within the shared folder of your project:
e.g. C:\My Paratext 9 Projects\<ProjCode>\shared\ptxprint

**Comment by KenK-3-21** [comment]
Thanks Mark!
The problem went away with this new version. Didn't even have to wipe out
the folder! BTW, the interlinear diglot option is not straightforward. Are
there some detailed instructions somewhere?
Read through the "What's New" - impressive!  You guys have put a ton of
work into this!
K
