### ISSUE TITLE
v1.5.18 (It's back.) PTXprint reopens previous Project config, after making a new Project Config

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#424]
I made a new print project configuration and saved it. 
I am able to print and tweak this new configuration.
But when I exit and reopen PTXprint, it still opens the old configuration, not the last/latest configuration that I was working on.
I can switch to the new one, and it works correctly for printing, etc.
But if I exit PTXprint, it reopens the old configuration again.

**Comment by markpenny** [comment]
@davidc86 - We think that this has been addressed, but weren't 100% sure as the description above is open to 2 different interpretations. Let us know if we've got it right - if not, we'll go around again.

**Comment by davidc86** [comment]
Looks fixed to me.
