### ISSUE TITLE
Add separator before end-notes 

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#428]
End-notes just crop up where people are expecting the next verse. There ought to be some kind of separator. Needed:
1) TeX code to insert something. A line? an image?
2) (optional) Python to let users control it.

**Comment by davidg-sil** [comment]
TeX code is in place, so I've removed that label.

**Comment by mhosken** [comment]
One other control we may want is whether the line is left aligned, centred or right aligned, along with it's proportion of column/page width and thickness. Do we want indent as well?
