### ISSUE TITLE
v1.6.0.4 the state for: "Override xRef Specific -/+ Settings in Text" is still not behaving correctly

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#434]
Congrats on v1.6!
I'm seeing that the value of the check box for "Override xRef Specific =/+ Settings in Text" is not retained in the Config file. 
Each restart of v1.6 and the setting reverts to clear.
This will then leave "-" marks in the text (and sometimes below depending on other settings)! 

![image](https://user-images.githubusercontent.com/65363206/112329375-884da780-8c8d-11eb-98a5-2b0ed9c42a78.png)

BTW, I think putting "-" in the text or xref area is a bug. Because doesn't "-" mean NO CALLER? If I wanted a "-" as the caller, I'd should have to "override" the settings, and then specify - in the "Use this Caller" box, right? But these "-" show up even if I have everything off: 

![image](https://user-images.githubusercontent.com/65363206/112329647-c2b74480-8c8d-11eb-89f9-e33fb20cf820.png)
 

Anyway, trying to finalize Mark and this threw me for a loop!

**Comment by davidc86** [comment]
Okay, great, part 1 is fixed, that is it retains settings when the project is reopened.

But part 2 is still broken. It prints "-" in the text when these are my settings:

![image](https://user-images.githubusercontent.com/65363206/113011919-45397b80-9148-11eb-9d12-3cdb464478ae.png)

Here are the results: 
 
![image](https://user-images.githubusercontent.com/65363206/113012109-77e37400-9148-11eb-887f-aa473071d743.png)

You can see the "-" mark after verse number 23. This is a bug, right? Because if I'm not mistaken, the "-" in the xref line: 

   \x - \xo 2:23 \xt Ul. 23:25\x*

MEANS "**_no caller_**" right?

So why then, if I don't override the xRef specifications in the text, does a "-" appear in the text?

It seems to me that the way this should work is, if I wanted a "-" to appear in the text (for some unknown reason), then I'd HAVE to Override the xRef specs and then overtly specify "-" in the Show Callers in the Text: text box, right?

Oh, BTW, there is a typo in "Override xRref-Specific...." label, currently it has two-Rs in the xRref label, when it should be xRef

**Comment by davidc86** [comment]
I can currently only get rid of the "-" in the text by Overriding the xRef specs, and specifying "Show caller in Text" but leaving this BLANK. (Glad this works!) 

This is actually helpful for projects where the team has been inconsistent with how they specify their xRefs, where some are \x + \xo ... and some are \x - \xo ..., so we can Override them, to force them all to behave the same, and then we can choose to NOT show a caller. But, this is a fringe case. 
 
But in the more common case where the project is consistent, and maybe they want to only mark xRefs for obvious quoted references to OT verses, etc. then only those might be marked as \x + \xo... and so they'd like those marked with something. 

As I understand how it "should" work, if the xRef is \x - then nothing is shown (unless the override is active). But for those cases where a few are marked \x + then ONLY those should use the caller shown in the Show Callers in Text box. And IFF the Override box is also checked, only then will the \x - print something, as defined in the Show Caller in Text box.

**Comment by davidc86** [comment]
Sorry for the multiple edits on the title! But I just checked this on 1.6.04 and it is still an issue where the "-" is being printed in the PDF if nothing is selected specifically, like this:

![image](https://user-images.githubusercontent.com/65363206/113377646-e68c2180-9342-11eb-8688-6cd05b060f5a.png)

Whereas this should not show any caller for xRefs in the text, because all of our xrefs are marked with a -.

**Comment by mhosken** [comment]
Looks like we were converting the - for the caller into a magic non breaking hyphen and messing up the code that spots the - to not output a caller. I think this is fixed now in 1.6.0.5.

**Comment by davidc86** [comment]
Woohoo! Fixed. Thanks.
