### ISSUE TITLE
Congratulations. PTXPrint solves one mysterious PrintDraft bug

### ISSUE THREAD

**Issue by sewhite** [sillsdev/ptx2pdf#44]
If in custom.sty you try to turn off some formatting from USFM.sty, for example:

\Marker fl 
\Bold -

and you use Paratext export to PDF; set double column and paper size 1/2 letter or A5, you get a weird output where the left edge of text is not on the page.

PTXPrint does not have this problem. 
Just thought I would let you know something you've done right.

**Comment by mhosken** [comment]
On Thu, 30 Apr 2020 07:17:07 -0700
Steve White <notifications@github.com> wrote:

> If in custom.sty you try to turn off some formatting from USFM.sty, for example:
> 
> \Marker fl 
> \Bold -
> 
> and you export to PDF in double column to paper size 1/2 letter or A5, you get a weird output where the left edge of text is not on the page.

Yes. ptx2pdf falls over with the - in the \Bold. To undo bold use

\Marker fl
\Regular

and then redo any superscript. \Regular clears bold and superscript and italic.

> PTXPrint does not have this problem. 

Yes it does. It may not fall over in the same way, but it messes up the rest of custom.sty and any following stylesheet.

**Comment by markpenny** [comment]
Issue documented in #43 - so I'm closing this as a related duplicate.
