### ISSUE TITLE
Add Western Cham digits

### ISSUE THREAD

**Issue by livingfield** [sillsdev/ptx2pdf#444]
Please add support for Western Cham (cja) digits (I've attached .map and .tec files, based on adlamdigits files).

This script is distinct from the Eastern Cham digits already in PTXprint. It has been proposed to Unicode but not yet accepted. (@mhosken has details)
 
[westernchamdigits.zip](https://github.com/sillsdev/ptx2pdf/files/6366241/westernchamdigits.zip)

**Comment by markpenny** [comment]
Thanks @livingfield for sending the map/tec files. It has been added and will be available in the next release (1.7) - hopefully by the end of today. If the codepoints move/change after it is eventually formally accepted into Unicode, please send us an update.
