### ISSUE TITLE
Is there a reason for it being 32-bit only?

### ISSUE THREAD

**Issue by rowbory** [sillsdev/ptx2pdf#445]
My Paratext virtual machine is 32-bit. I know I'll need to change that but for now it's rather annoying that I can't install Ptx2Pdf. Is there a dependency that requires 64 bit?

**Comment by markpenny** [comment]
Sorry - we made a decision a while back to NOT try to support both 32 and 64 bit versions. It is hard enough supporting Windows and Linux, let alone both architectures. Note that PT 9.0 (or perhaps just 9.1) also only works on 64-bit Windows.

If you are really keen you could always pull the source and build your own. But I suspect rebuilding your VM would be easier!
