### ISSUE TITLE
v1.7 Picture List fails to display if project has unknown user-defined SF marker

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#446]
The updated v1.7 just installed.
First test of anything, I looked at the Pictures tab and the picture list won't display: 

![image](https://user-images.githubusercontent.com/65363206/116701771-4b648700-a996-11eb-93e7-331dd849963e.png)

Looks like a bug. Sorry.

**Comment by davidc86** [comment]
And even though the first picture shows in the side thumbnail, When I print just Mark (so I'm not sure why the Genesis picture is showing at all) I don't get any pictures in the print out:

![image](https://user-images.githubusercontent.com/65363206/116702291-e6f5f780-a996-11eb-9792-c9be4aece23a.png)

Also, it appears the Pictures tab/page is ignoring the "show only Active books" check box. 

Again, sorry. Looks like another bug in this tab.

**Comment by davidc86** [comment]
GOOD NEWS: I accidentally solved this by changing the UI language to Indonesian. Then the piclist magically showed up! Switching back to English and it showed up there too! So cool. It isn't thoroughly broken, just "kinda" broken.

**Comment by davidc86** [comment]
Okay, wait... there is another problem. Here is the list of pictures that is currently showing: 

![image](https://user-images.githubusercontent.com/65363206/116705840-fd05b700-a99a-11eb-9868-af496fd32784.png)

Notice it jumps from Jonah to Luke. So it is missing all of the Mark pictures.

Here is a screen shot of the PicList file: 

![image](https://user-images.githubusercontent.com/65363206/116706279-77ced200-a99b-11eb-8d41-e91953566b4b.png)

All of the highlighted lines in this file DON'T show up in the Picture tab. So if I select just Mark in PTXprint's Basic tab, nothing shows up in the Picture tab.

Wait... there might be another bug going on... it appears to keep flipping to "default" settings!

When I switched to my saved settings, I get this error: 

![image](https://user-images.githubusercontent.com/65363206/116707302-85388c00-a99c-11eb-87ff-c192d3db76fa.png)

Any clue what might be going on here?

**Comment by davidc86** [comment]
Running just Genesis the first time caused an error saying it could not find the temp piclist for that project.
Running Mark generated Mark with placeholders.
Running Genesis again, did produce the book of Genesis, but with NO pictures and NO placeholders.

This is getting a bit confusing.

Doing a file compare between "Default.cfg" and "SelaruNewPublication.cfg" there is almost NO difference.
But between the porjects' ptxprint.sty files is the user-defined style **\ipc**: 

![image](https://user-images.githubusercontent.com/65363206/116720673-7e187a80-a9aa-11eb-9d48-43c68d27b569.png)

And THIS if added to the Default Ptxprint.sty, the tabs in the program go gray.
But this works in the SelaruNewPublication config file.

HERE IS A WEIRD THING:
This \ipc is only used in my front matter and in the colophon. So if I turn on the colophon in Default config, it crashes (because there is no \ipc defined--I don't use the custom.sty or frtbak.sty files in PTXprint). 
But the exact same colophon prints just fine in SelaruNewPublication config. BUT no pictures!

HERE IS A REALLY WEIRD THING:
So \ipc needs to be defined, which is is in the SelaruNewPublication config, BUT it doesn't show up in the Style page. (I can't find it anywhere.)

ANOTHER oddity:
In Default Styles page, I see these options at the bottom (after Milestones):
* Obsolete & Deprecated
* Module
In the SelaruNewPublication Style page, I don't see those at the bottom after Milestones, rather I just see:
* Other
(Which apparently has \p in it! I'm wondering if this is supposed to be the \ipc SFM I made. But its attributes are identical to \p and not to \ipc)

Any help would be appreciated.

**Comment by davidc86** [comment]
Woohoo! Here is what happens if I delete the \ipc field from my SelaruNewPublication project's ptxprint.sty file: 

![image](https://user-images.githubusercontent.com/65363206/116759583-ab801b00-a9e0-11eb-8e7f-2be2a34689be.png)

Tell me that's not weird!!
So now that project works. (Well, I had to turn off the colophon, because it uses the \ipc field, likewise with our FrontMatter SFM file.)

So why an unrelated, unknown SF marker would keep PTXprint from loading the picture list is just a bit bizarre, but then computers can be weird.

**Comment by davidc86** [comment]
Also, I should mention that the SelaruNewPublication Style page now has the new additions at the bottom of the list, like the Default has: 

![image](https://user-images.githubusercontent.com/65363206/116759825-4d076c80-a9e1-11eb-8167-f44ddc001ced.png)

I'd be interested in any explanation on what was going on with this. 

(And how I should add "user-defined" SF markers in the system, if how I had it before is not valid. (Also, anybody know why no one has defined "Introduction Paragraph Centered" yet? It works well for copyright  page, etc. Unless there is a better SFM I don't know about. Thanks!)

**Comment by mhosken** [comment]
ptxprint shows styles in a category tree. The category used is taken by splitting the \Name field on - (hyphen). The first field (before the first hyphen) is considered the code, then second the category and the third (if present) the annotation. It then builds entries in the tree view accordingly.

**Comment by davidc86** [comment]
Thanks. But I had that well defined: 
![image](https://user-images.githubusercontent.com/65363206/118666991-9cabad80-b7c1-11eb-9eb1-ba55dabbc9aa.png)

Where the RIGHT side is the ORIGINAL style sheet I had been using in PTXprint. 

But for reasons unknown, I had to delete that user-defined style in order to get PTXprint to display the Pictures in the Pictures tab and to function properly. THIS is the confusion. Why should a well-formed user-defined style cause PTXprint to derail?

**Comment by davidc86** [comment]
Once the ability to correctly handle new/unknown styles was fixed. These issues disappeared.
