### ISSUE TITLE
Can't adjust size of drop-cap chapter (\c) numbers

### ISSUE THREAD

**Issue by livingfield** [sillsdev/ptx2pdf#447]
In the Styles tab, for chapter numbers (\c), adjusting the "Font Size Factor" or checking the box "Scale Relative to Parent" doesn't affect the size of the printed drop-cap chapter numbers. I am, however, able to change the color of the chapter number in the same dialog box. (PTXprint 1.7)

**Comment by mhosken** [comment]
Yes probably. We go through some hard work to come up with a good estimate of the chapter number size. Are you wanting to change it because it isn't quite right for you?

**Comment by livingfield** [comment]
The script I'm using has numerals with either large ascenders or large descenders. Ptxprint generally works around this to avoid overlapping characters but leaves too much space below numbers without a descender while numbers with a large ascender and a long \s or \r line can cause an extra gap between \s and the text.
 
The size of the drop cap chapter numbers are about twice the size that would be aesthetically pleasing. Reducing the size of the numbers would help alleviate these issues.

**Comment by mhosken** [comment]
That's some interesting maths the automatic size calculation is doing. Examining the font, I notice that both the highest and lowest points on any characters are in the digits, so whatever we do they are going to look oversized. So I have added back a feature to allow you to say: I know best. Always a good thing to do.

If you add `\CalcChapSizefalse` to your ptxprint-mods.tex then the macros will not calculate the size or shift of the chapter numbers. I suggest something around 2.5 for fontsize and say 3pt for raise as an example, which you set in the chapter style.

This feature will land with the next code release in a few days.

**Comment by markpenny** [comment]
[Version 1.7.9](https://software.sil.org/ptxprint/) has just been put up on the site. It should have the change that Martin explained above. Here's how to do that:
![image](https://user-images.githubusercontent.com/12962708/118810353-e5698080-b8ff-11eb-904f-6b5cb9e1fd57.png)

then paste the above code:
![image](https://user-images.githubusercontent.com/12962708/118810521-15188880-b900-11eb-94b8-a39b5cfa8099.png)

And then you will need to make your own adjustments to the Style settings for \c
![image](https://user-images.githubusercontent.com/12962708/118810682-44c79080-b900-11eb-9b59-b96afe4eead9.png)

**Comment by livingfield** [comment]
Thanks. This works great!
