### ISSUE TITLE
ptxprint error messages

### ISSUE THREAD

**Issue by craig397** [sillsdev/ptx2pdf#448]
can you help me w these ptx print error messages?
![ptx error02](https://user-images.githubusercontent.com/83631700/116966246-5430c200-ace2-11eb-81fb-c5a35fdbdf3f.JPG)
![ptx error01](https://user-images.githubusercontent.com/83631700/116966254-56931c00-ace2-11eb-9961-8f2413c52cc3.JPG)

**Comment by mhosken** [comment]
Dear Craig,

You need a space between \v and the 3.

GB,
Martin
