### ISSUE TITLE
Book Introductions and outlines

### ISSUE THREAD

**Issue by FlipWester** [sillsdev/ptx2pdf#449]
Using PTXprint with Wasta-Linux 20.04 I am working on a NT project Karenni script, two column layout, chapter numbers centered and marginal verses. Book introductions and outlines are one column. I would like to have the two column text to follow directly after the introduction as shown in the first screen shot of page 1 and 2 of the Gospel of Matthew, where the book introduction is longer than one page.

![Screenshot from 2021-05-15 15-55-37](https://user-images.githubusercontent.com/84236939/118364455-c46bfd00-b598-11eb-99e1-299131000bde.png)

When the introduction is shorter than one page the two column text starts on second page as shown in the two starting pages of the Gospel of Mark. I added the Guides to show that the introduction text is shifted to the left margin and a page break is forced before the two column text.

![Screenshot from 2021-05-15 15-56-20](https://user-images.githubusercontent.com/84236939/118364454-c46bfd00-b598-11eb-85cf-ae1820609df5.png)

Changing the body text to one column this shift and page break don't occur.

![Screenshot from 2021-05-15 16-00-59](https://user-images.githubusercontent.com/84236939/118364452-c3d36680-b598-11eb-82aa-7268949b0f62.png)

Is it possible to get the same result with two column text?

**Comment by markpenny** [comment]
Thank you @FlipWester for unearthing a couple of issues. @mhosken is working on solving them. Currently PTXprint forces a new page (when in 2-col mode) if more than 66% of the page has been covered in text. As a temporary workaround (which might mask the current issue, but not necessarily help in all other books) you could increase that value by putting this line into your ptxprint-mods.tex file:
`\def\PageFullFactor{0.9}`
and that would only trigger a new page after 90% has been covered.

If you are able to, could you please send us a Zip Archive file of this config (to ptxprint_support@sil.org). That might help speed up testing.

**Comment by mhosken** [comment]
Still unfixed: Doing a page full check after the intro pages when both are single (or double column). Not sure if it is needed.

**Comment by markpenny** [comment]
@FlipWester Just wondering if there's anything else to be done about this issue, or whether it can be closed now.
