### ISSUE TITLE
Fails to include image in output

### ISSUE THREAD

**Issue by sewhite** [sillsdev/ptx2pdf#45]
Tested on 0.50 green button edition. 

Same project as #42. 

Progress - no error message, the PDF is made. But the illustration is not included, and white space for it is spread across three different pages. 

[ptxprint-MATPDFP.pdf](https://github.com/sillsdev/ptx2pdf/files/4560472/ptxprint-MATPDFP.pdf)
[ptxprint-MATPDFP.log](https://github.com/sillsdev/ptx2pdf/files/4560475/ptxprint-MATPDFP.log)

**Comment by markpenny** [comment]
@sewhite - I have re-written the code to handle illustrations over the weekend. Could you please re-test with 0.5.1 and let me know if it works for you now. If not, please visit the [FAQs here](https://docs.google.com/document/d/165uGeKNUGDd-GBmhOonHhDUNKSsqqQyzh3sSbveEzSQ/edit#heading=h.mya7r9dn7xfc) to see if you can work out why it isn't working for you.

**Comment by sewhite** [comment]
Thanks, Mark.

0.51 still behaves the same, the PDF still has white space on two pages and
no picture. It has copied the picture file to the tmpPics folder.



Steve White
International Language Technology Consultant

**Comment by sewhite** [comment]
I did run through the FAQ, I don't have a PrintDraft changes file in the
project, it should be looking for JPG files, and I also tried creating a
PIclist, then using that,with no difference.

Steve White
International Language Technology Consultant
