### ISSUE TITLE
Center Column References v1.7.9

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#450]
This is an enhancement request. We almost always use large font single-column layout (A5 sized pages printed side-by-side on A4 landscape paper), because eyesight is not good and the words are long. So the "center column" idea is not a layout for us, UNLESS we think of the GUTTER area as the "center" column of a two-page layout. Then I can see this being very elegant. So if PTXprint were set to single column, then the Xrefs could be loaded into ref columns that occur at the INSIDE margins of the pages (L and R). I.e. a page would be EDGE OF PAPER,GUTTER, MARGIN, XREF COL, TEXT COL, MARGIN, EDGE OF PAPER (and reversed for the even pages). That'd be nice looking I think. 

But as to v1.7.9, the over-all look of the double-column layout with center column Xrefs is very nice.

**Comment by markpenny** [comment]
Yes, @davidc86 - others (at Biblica) have already requested this and I can understand why. I'm not the one who decides whether it is going to be possible or not, but I know that @davidg-sil has been very busy in recent weeks working out how to do a multi-column layout across multiple pages. If that effort proves to be effective, there's a glimmer of hope that what you're requesting might be possible. But don't hold your breath... these things take time.

**Comment by davidc86** [comment]
Totally understandable. Thanks.
