### ISSUE TITLE
Footnote problems with v1.8

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#451]
(Second time posting this as I lost Internet connection, apologies if it shows up twice)

I'm seeing some problems with footnotes in the latest v1.8. Sometimes the caller in the text and the footnote line appear at the bottom of a page, but the footnote is on the next page:

![image](https://user-images.githubusercontent.com/14953913/119522945-47007380-bd74-11eb-94d4-d7cb33656d8c.png)

I have a project backup and PDF, but I think I will attach them in a separate message (so I don't lose it again).

I also saw one case where there were three footnotes at the bottom of the page and the order of the footnotes was (I'm estimating the verse numbers) v.23, v.17, v.20. But the caller for v.23 was in the text on the next page. I don't have a backup for that problem, but it seems to indicate (along with the problem above), that all is not quite right with footnotes.

**Comment by jeffheath-sil** [comment]
Here are the PDF that shows the problem (p. 15, I believe) and a backup of the project that produces this PDF.
[ptxprint-Luka-LUKNgal.pdf](https://github.com/sillsdev/ptx2pdf/files/6540603/ptxprint-Luka-LUKNgal.pdf)
[Ngal-LukaPTXprintArchive.zip](https://github.com/sillsdev/ptx2pdf/files/6540604/Ngal-LukaPTXprintArchive.zip)

**Comment by davidc86** [comment]
This seems it might be related to what I just saw in v1.9.2 (#476), where footnote order is messed up, and copied across pages
