### ISSUE TITLE
Adding a new style fails

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#452]
When I try to add a style we use (\ipc), when I hit OK, it fails with this: 

![image](https://user-images.githubusercontent.com/65363206/119553008-2b43a000-bd69-11eb-88ab-2445d4620561.png)

I think what ever the problem is here, is related to what caused my whole pict list to fail to show in the other issue #446

**Comment by davidc86** [comment]
But it seems to have entered it into the Style layout: 

![image](https://user-images.githubusercontent.com/65363206/119553392-a2793400-bd69-11eb-8836-e44a87a11968.png)

**Comment by davidc86** [comment]
But apparently PTXprint ignores the style! Here is where I specifically use it:

![image](https://user-images.githubusercontent.com/65363206/119553972-2af7d480-bd6a-11eb-8480-916a3213a08c.png)

And here is how it comes out: 

![image](https://user-images.githubusercontent.com/65363206/119554058-3ea33b00-bd6a-11eb-8e78-dafb951bbc43.png)

Any ideas?

**Comment by davidc86** [comment]
Still not using the \ipc style specifications in the colophon, BUT I have figured out what was causing the fail error. 
Here is the well-formed style (that PTXprint doesn't choke on):

\Marker ipc
\Name ipc - Introduction - Centered Paragraph
\Description Introduction centered prose paragraph
\FontSize 10.920
\Occursunder id
\TextType Other
\StyleType Paragraph
\LineSpacing 0.910
\LeftMargin 1
\RightMargin 1  

And here is my bad one: 
\Marker ipc
\Name ipc - Introduction - Centered Paragraph
\Description Introduction centered prose paragraph
\FontSize 10.920
\Occursunder id **periph**
\TextType Other
\StyleType Paragraph
\LineSpacing 0.910
\LeftMargin 1
\RightMargin 1

NOTE: that in the \Occursunder field, I also have "periph", because this \ipc is used in other places. But apparently PTXprint doesn't like the "periph" specification.  I removed that outside of PTXprint, and reopened PTXprint, and it no longer fires an exception when I click on the \ipc style.  (So, why is "periph" not allowed?)

Unfortunately PTXprint still is not using the style specifications from \ipc to modify the colophon.

**Comment by mhosken** [comment]
Fixed the initial exception about None and float. I think the save and reload may have got around the lack of an update due to the exception. If this is not the case, we'll keep an eye open and if it recurs, and you can remember, please link that to this what may be a closed issue by then.
