### ISSUE TITLE
Error in making a PDF with Russian interface of the PTXPrint

### ISSUE THREAD

**Issue by Ar-Paramir** [sillsdev/ptx2pdf#453]
Every attempt to make a PDF ends up with the following error message:

```
PTXprint Version 1.8
Please send to: ptxprint_support@sil.org

PTXprint [1.8] - Error!

Не удалось создать: ptxprint-Default-JONEvnJON.pdf

------------------------------------------------------------------------------------------
Sorry, there is no diagnostic help for this error.
Try using Paratext's 'Run Basic Checks' to uncover any Marker errors.
```

But the projects I tried had no marker or any other errors. The XeTeX log says:

```
Reading Paratext stylesheet "../shared/ptxprint/Default/ptxprint.sty" ()...
! Illegal unit of measure (pt inserted).
<to be read again> 
                   м
l.29 \PaperWidth=148 м
                      м
No pages of output.
```
The only reason I see is that the interface of PTXPrint is switched to Russian (I cannot switch it back to English and I'll make a separate bug report about that issue). And in Russian interface Page size looks this way: "148 мм, 210 мм (A5)", where "мм" is a Cyrillic equivalent for "mm".

This error makes it impossible to finish the task and generate PDF.

Possible solutions: either to fix the code so that the visible localization wouldn't affect the internal work of the "engine", or to change "мм" back to "mm" in the Russian interface (this abbreviation will be understood by the target audience).

**Comment by mhosken** [comment]
One way around this is to type into the pages size 148mm, 210mm using latin m's. That should work, hopefully. I think we have to do some work on localised page sizes. I wonder how important it is for page sizes to be localised.

**Comment by markpenny** [comment]
I am assuming this issue has been resolved, as it seems to work now regardless of what is in the settings 'mm' or 'MM':
![image](https://github.com/sillsdev/ptx2pdf/assets/12962708/b60f2229-7e1a-4a46-b75d-5052897451fc)
