### ISSUE TITLE
Cannot switch back to the English interface

### ISSUE THREAD

**Issue by Ar-Paramir** [sillsdev/ptx2pdf#454]
I wanted to examine how the program is translated into Russian and how it works with localization. Then I wanted to switch back to English. The program restarts, but nothing happens, the interface is still in Russian. Tried to delete all "ptxprint" files and folders in my home folder, it didn't help. Just in case, my system interface is in Ukrainian, in ~/.config/ptxprint/ptxprint_user.cfg is written:

```
lang = en.UTF-8
syslang = uk_UA.UTF-8
```

I even changed the second line to "syslang = en.UTF-8", it didn't help either. The error is serious in my case since the Russian interface produces another error (see https://github.com/sillsdev/ptx2pdf/issues/453) and I can't end the task with it. 

Expected behaviour: to have possibility to switch between different licalizations smoothly.

**Comment by mhosken** [comment]
Extremely odd and probably very hard to replicate. Here's what I suggest:

1. Try deleting ~/.config/ptxprint/ptxprint_user.cfg
2. You can 'force' a language by running ptxprint -L en, which should then get remembered

Just to check. You are still seeing the Russian UI, it's not that you are seeing English UI but the page size is still in Russian?
