### ISSUE TITLE
support for link-href="...." word level attribute.

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#456]
Requested here:
https://community.scripture.software.sil.org/t/hyperlinks-in-front-back-matter-is-remvoed/2278/5

Ideally it would add PDF `\special`s to generate a hyperlink. There is also `link-id` which is supposed to be a document-internal anchor.

Reference: https://ubsicap.github.io/usfm/linking/index.html?highlight=link

**Comment by markpenny** [comment]
@mhosken Is this one related to any of the recent work you were doing on DVI and pre-press PDF work? 
![image](https://user-images.githubusercontent.com/12962708/122368424-712f0500-cfb1-11eb-81a5-e71858670938.png)

**Comment by davidg-sil** [comment]
I don't think it is, I think it needs some extra code to respond to the particular attribute.

**Comment by davidg-sil** [comment]
For the record, the following linking attributes (should) work:
* ```\jmp |link-id="pgtop1"\jmp*``` Jump target
* ```\xt 1:2|TST 1:2\xt*``` Xref as a link. (MUST be 3-letter book-id, L or R for diglot, space, chaper:(start)verse) 
* ```\w here|link-href="#pgtop1"\w*``` Jump to target
*  ```\w here|link-href="https://github.com/sillsdev/ptx2pdf"\w*``` Jump to URL

These do not:
*  ```\w here|link-href="prj:RSV GEN 1:1"``` prj: type links are not handled at present.
*  ```\w here|link-href="git://github.com/sillsdev/ptx2pdf"\w*```  Only `http:` and `https:` URL schemas are currently recognised. Please submit an issue with a use case.
* ```\xt 1.2|1:2\xt*``` - No book ID
* ```\xt 1.2| GEN 1.2\xt* - `.` may be valid in the displayed portion for your project, but link attributes must use `:`
* ```\xt 1.1|GEN1:2``` - the space is required.
* ```\w here|link-href="#my destination"``` Spaces are not allowed.
