### ISSUE TITLE
Indent First Paragraph

### ISSUE THREAD

**Issue by klassenjm** [sillsdev/ptx2pdf#458]
I'm working with PTXprint 1.8

I've noticed that when I uncheck "Indent First Paragraph" on the Body settings tab, then the first line indent is removed from ALL paragraphs in the output, not only the first paragraph after headings.

An archive is [here](https://www.dropbox.com/s/37t2v0zdc4icrgn/GNTPA-60-2Col-2FontPTXprintArchive.zip?dl=0).

**Comment by markpenny** [comment]
@klassenjm Yes - another regression. @davidg-sil or @mhosken it seems to be related to ```\IndentAfterHeadingfalse``` not doing what it was originally doing.

**Comment by klassenjm** [comment]
Tried 1.8.3. This issues is fixed for me.
