### ISSUE TITLE
Just updated to 1.8.3 and now it fails somewhere around the 2nd \wj 

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#462]
I've made no changes to the setup for PTXprint.
I simply updated to 1.8.3
And ran a test print immediately.
If failed with: 

![image](https://user-images.githubusercontent.com/65363206/122619774-32f01f00-d05f-11eb-9d10-a220e52db34f.png)

I've no ideas yet. Do you?

**Comment by mhosken** [comment]
Please send an archive

**Comment by davidc86** [comment]
The archive is 28MB, my email won’t let me. Do you have a better way?
David

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by mhosken** [comment]
Perhaps cut the job down to just a short book, or turn off pictures? Use a
new config for it?

GB,
Martin

**Comment by davidc86** [comment]
Sure, I can do that, but doing so kind of defeats the purpose of a "snapshot" archive of what was configured at that moment in time.
I've just sent an simpler archive without pictures, but when I test PTXprint it works without pictures! So like I said, it defeats the purpose. Surely we could have a Dropbox where we could upload bigger archives, which you could delete once you get them?
(Well, it looks like the zip file won't go through email either even though it is only 4MB. So a solution for these archives would be helpful.)

**Comment by markpenny** [comment]
Okay - here we go... There's [an online folder here](https://drive.google.com/drive/folders/1S63WeFUg96ZdlA5IdS4E3AI7kC3HaxUo?usp=sharing) that you can drop archive files into for us to take a look at:

**Comment by davidc86** [comment]
Wow, Mark, that was fast! 😊
Okay, I uploaded the original archive.
Help this helps you figure out what’s going on.

I found out if I turn off pictures, it prints, but if pictures are on it fails. But I’ve changed absolutely nothing in the Paratext files or PTXprint config files, so something happened in PTXprint from 1.8.2 to 1.8.3.
Blessings onto you all,
David

**Comment by markpenny** [comment]
Hi @davidc86  (and @davidg-sil)
I've got the file now, and have figured out that the problem is that the "After paragraph" positioning of the illustrations is causing the problem. If I change that to "Before verse" or Top or Bottom, then it works fine. So we've obviously broken something in a recent update, and will make sure that this is fixed by 1.8.9 (or 1.9) which should hopefully be within the next few days. BTW - it is an impressive-looking publication with all those official stamps of approval :-) [and that's why I have already removed the file from the publicly accessible dropbox, as anyone with the link could grab the files/pics/seals!]

**Comment by davidc86** [comment]
Thank you!
You guys are awesome.
And also very aware of issues with these things!
So, I'll just wait for the next release, and check it then. I won't mess with anything for now.

Thanks again,
David

**Comment by davidg-sil** [comment]
I found the problem... after about 3 hour's searching it turned out to be a stray carriage return in one of the macros.

**Comment by davidg-sil** [comment]
That made a 'paragraph break' in the middle of the box that the verse number goes in, the 'paragraph break' triggered the picture, and (surprise, surprise) it couldn't put the picture in such a position.

**Comment by davidc86** [comment]
Cool. Glad you found it. Sorry it took 3 hours! This is now working just fine in v1.8.9.1
