### ISSUE TITLE
End of Ayah warning msg

### ISSUE THREAD

**Issue by spsmith57** [sillsdev/ptx2pdf#463]
Congratulations on a great utility! Just one issue (so far): When selecting End of Ayah for the Verse Number Decorator, I get a warning message: 

Could not locate decorative PDF(s): 
Verse Number Decorator
c:/Program Files/PTXPrint/ptxprint/Verse number star.pdf

![AyahError](https://user-images.githubusercontent.com/14273084/123645162-fe7a2100-d81d-11eb-8dcf-9251cd4a7284.JPG)

I found that the "Verse number star.pdf" file is in fact present in trhe "PDFassets/border-art" subfolder but that's irrelevant because I have not selected the "Verse Border Graphic" option and don't want to use that PDF. I have selected End of Ayah, which is supported in the font being used for the verse numbers, and does get used and does display properly in the resulting PDF. So everything actually works, but it's disconcerting to get this spurious warning message.

**Comment by markpenny** [comment]
@spsmith57 Thanks for the heads-up Steve. We'll try to get that resolved before 1.9 is released in a day or two...

**Comment by markpenny** [comment]
@mhosken I haven't been able to replicate this yet, but I am wondering why it is giving that path to the file. It shouldn't even be looking in the ptxprint folder for the pdfs. The normal path would be like this:
"C:\Program Files\PTXprint\ptxprint\PDFassets\border-art\Verse number star.pdf"
I wonder if the code to create a relative path has got carried away for some reason. There was a similar complaint yesterday from a user who hadn't turned on the Watermark feature, and yet PTXprint was complaining that it couldn't find the file. I wonder what we've borked, and when...

**Comment by markpenny** [comment]
@spsmith57 MH thinks this has now been fixed, but I have no way to test that - as I couldn't replicate it. But please let us know if we've solved this for you when 1.9 is released.

**Comment by spsmith57** [comment]
Seems fixed in 1.9. Thanks!
