### ISSUE TITLE
Chapter number issues

### ISSUE THREAD

**Issue by mhosken** [sillsdev/ptx2pdf#464]
- Currently the diglot macros (or whatever) is not allowing different controls over which text has a chapter number and whether to use labels. Thus one can't have only chapters in a secondary text.
- Diglot: If chapter labels are used there is still a drop chapter cutout included
- Diglot: Chapter headings seem to be shifted outwards

- Chapter numbers seem not to be dropping after a heading
- If chapters are turned off, we still want the index destination added to the PDF to v1.

**Comment by davidg-sil** [comment]
I'm not seeing any shifting of position, I wonder if that might be styling-related. 
Nor am I seeing the drop cutouts in my test file, 
.

Some of these could be merging issues. 

If `\cl` occurs before chapter 1 in the USFM file, then it should be treated as header information, and appear in the file just once. If it  occurs after a chapter number, then in the merge file it should likewise occur immediately after the chapter  number. (without side swaps) but may balance with section titles. 
What I'm seeing is that (stand-alone) usfmerge is moving a post-chapter number \cl to a pre-chapter number position (incorrect), and when `\cl` occurs in the header, then it is duplicated to below the chapter  which would also give incorrect results if the header version wasn't set.

**Comment by davidg-sil** [comment]
Column specific OmitChapterLabel and OmitVerseNumberOne now available in macros. They have been implemented as a 'tri-state'  values. 
Thus if no side-specific true/false choices are declared, then the current 'both(all) on / both(all) off' behaviour is preserved.

**Comment by davidg-sil** [comment]
Hopefully PDF marks are also generated when chapter marks are suppressed, but I've not tested whether that actually works.

**Comment by davidg-sil** [comment]
Failure to drop below section headers was USFM error. I think all issues here are solved.
