### ISSUE TITLE
Typing new configuration name selects similar configuration instead

### ISSUE THREAD

**Issue by da4396** [sillsdev/ptx2pdf#468]
I went to save the current configuration under a different name but as I was typing, PTXprint found an existing configuration with the same name and loaded that instead. For example, I have a configuration named "test" and wanted to make a duplicate configuration named "test2" but once I got as far as typing "test" for the new name, PTXprint loaded the configuration named "test". My unsaved settings were lost.

I'm using PTXprint 1.9.

**Comment by markpenny** [comment]
Yes, that's a known bug/feature. I'm sorry your settings were lost. I have experienced the same issue in the past and I'm open to suggestions on how best to solve it from a user-experience point of view (i.e. what would you expect it to do when you type in a config name that already exists?) Perhaps we need to wait until the user clicks elsewhere (or leaves the box where the config name is being typed) before it does anything.

For the moment, a simple workaround [for those who are aware of this pitfall] is to NOT erase the contents of the existing name, but to type the additional characters first. 'Default' > 'Default**2**' > '**Test**2'

**Comment by da4396** [comment]
Thank you @markpenny for your help on this. I didn't lose many settings. I was learning PTXprint and didn't have many changes to lose.

I wonder if this suggestion might work. While the user is typing a configuration name, don't auto-load any configurations. Only load a configuration when the user clicks on a name in the dropdown list.

But this doesn't solve the issue of losing unsaved changes when the configuration isn't saved before loading a new configuration. That is probably a separate topic.

**Comment by da4396** [comment]
... I need to add a scenario. If the user types the name of an existing configuration and then presses Save we have a problem. My guess is that PTXprint would overwrite the existing configuration with the new settings. Maybe have a dialog box ask the user if they want to overwrite the settings in the existing configuration.
