### ISSUE TITLE
Warn user of unsaved changes to configuration

### ISSUE THREAD

**Issue by da4396** [sillsdev/ptx2pdf#470]
I have read that PTXprint saves changes to a configuration when the Save button is pressed on the Basic panel and when the Print button is pressed. But there are a few cases where unsaved changes can be lost.

1. **When closing PTXprint** - The Close button was so close to the Print button that a few times I have hit the Close button and lost my unsaved changes. Or I was finished with some changes for the day I clicked Close because I was going to finish my work and print a PDF later.
2. **When opening/loading a configuration** - On the Basic panel I can select a configuration from the dropdown list and it will be loaded. But any unsaved changes will be lost.
3. **When reverting to the saved copy of the configuration** - It seems obvious that clicking the "reload the saved configuration" would undo any unsaved changes. But if I accidentally click that "reload the saved configuration" icon on the Basic page then I lose my unsaved settings without a warning.
4. **Typing the name of an existing configuration** - This is discussed more fully in #468 

Other than case 4 where a solution is mentioned in the related issue, can a warning dialog be added in the other cases asking if the user wants to save their changes to the current configuration before closing PTXprint or loading a saved configuration? The dialog box would give them the choice of Yes, No, and Cancel.

A small suggestion is to add a * to the configuration name in the title bar or PTXprint. This could help the user know they have unsaved changes.

I know adding a warning dialog or a * in the title bar would mean also tracking if any changes have been made since the last save. So I know this issue isn't a quick fix ... unless PTXprint already knows when a configuration has unsaved changes.

Another small suggestion is to add a Save button beside the Close and Print button. Personally, I find it helpful to always have a Save button nearby as a reminder to save my changes. Although with the protections mentioned above, an extra Save button wouldn't be necessary.

**Comment by davidc86** [comment]
I vote for a SAVE button on the bottom at all times. Many apps do this. 

This would make the Save button on the Basic tab a bit redundant, but not harmful.

If it is too complicated to mark a configuration as "changed", then a Saved button on the bottom would at least put a reminder in the user's face. 

But I like the * idea in the title bar (like many apps do), to indicate there are unsaved changes. 

I also like giving a warning on closing with unsaved changes. 

But if that is too hard to implement, then whenever someone clicks "Close", then have PTXprint just ask "Do you have any unsaved changes you want saved? Yes, Save/No, Discard"

That way the user can catch their mistake (if there is one), and PTXprint is not required to keep track over every possible change that could happen in the configuration file before it is saved.

Just some ideas.
