### ISSUE TITLE
1.9.1 won't open

### ISSUE THREAD

**Issue by JDNystrom** [sillsdev/ptx2pdf#472]
I just installed version 1.9.1. Windows 10 says it can't execute the script. I re-installed 1.9 and I can start PTXPrint with no problem.

**Comment by markpenny** [comment]
@JDNystrom Thanks for alerting us! There seems to be an issue with the SSL certificate authentication which is making it fail. So we have disabled the new feature of informing users of new updates available until the Python bug is resolved. ver 1.9.2 is now available and should work.
