### ISSUE TITLE
'Apply Initial Settings (ptxprint-premods.tex)' calls /inputifpresent{} instead of /includeifpresent{}

### ISSUE THREAD

**Issue by da4396** [sillsdev/ptx2pdf#473]
When I enable **Apply Initial Settings (ptxprint-premods.tex)** in PTXprint I get the same error as mentioned in a comment in closed issue [#246](https://github.com/sillsdev/ptx2pdf/issues/246#issuecomment-764942930). XeTeX crashes and the log says

```
!Undefined control sequence.
l.6 \inputifpresent
```

In commit https://github.com/sillsdev/ptx2pdf/commit/4d1565ef7fba5857fe074c32e664d12e06cf2e71 on Dec 3, **\includeifpresent{}** was implemented in `/src/paratext2.tex` as per the discussion in [#246](https://github.com/sillsdev/ptx2pdf/issues/246#issuecomment-721596127). 

But in commit https://github.com/sillsdev/ptx2pdf/commit/0fbf720b922c00a01dd0fa8948dc03ef591d4f74 on Dec 14, **\inputifpresent{}** was added to `/src/python/lib/ptxprint/template.tex` as part of the **Apply Initial Settings (ptxprint-premods.tex)** setting instead of \includeifpresent{}. It seems \input{} was added to `/src/python/lib/ptxprint/template.tex` in commit https://github.com/sillsdev/ptx2pdf/commit/4d7429e2a12dc714d51efd1df31dfeb55e9e2265 on Dec 4, but subsequently removed or lost.

I would be happy to submit a pull request but maybe it is easier for someone else to make this small change to `/src/python/lib/ptxprint/template.tex`.

**Comment by markpenny** [comment]
@mhosken Is this related in any way to what we found in template.tex yesterday where the *mods.tex file was commented out? Just wondering...
