### ISSUE TITLE
Footnotes messed up (shown repeated on two pages) v1.9.2

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#476]
Here is a screenshot of the issue: 

![image](https://user-images.githubusercontent.com/65363206/128523246-1b3d6a09-c67b-4a97-a456-fca79fd52c71.png)

The only thing that should show up on the left page is the footnote from 9:25 and the xrefs from 10:1, all that other stuff is a glitch from the right-hand page. 

I don't believe PTXprint use to do this.

It looks like the footnote for 10:2 would have fit on the left-hand page if the two 10:4 footnotes had not also been copied over.

**Comment by davidc86** [comment]
When I turned off widow/orphan controls (\widowpenalty=0) in ptxprint-mods.tex file, this problem got "better" but is still **not usable**. Here is the current results with widow/orphan controls turned off: 

![image](https://user-images.githubusercontent.com/65363206/128603496-89be192d-bbb6-4ea1-b8c2-dd559a3e2c39.png)

So less of the footnotes from the right-hand page were left on the left-hand page when PTXprint did its magic, but there is still a residual line. Any ideas why these lines are left in the footnote area when the columns are readjusted? (I'm guessing that is what is happening.)

**Comment by davidg-sil** [comment]
I'm confused... What you're seeing is a result of the combination of (a) footnotes being allowed to split and (b) adjusting the columns to get them to fit/balance, but footnotes *shouldn't* be allowed to split.

**Comment by davidc86** [comment]
The footnotes are allowed to split across the FOLLOWING page. But in both of these printouts, the main footnote is on the RIGHT hand page, but part of it has been left on the LEFT hand (previous) page! This shouldn't happen. 

The first case is the worst I've seen, where not only did part of footnote 10:2 get left on the previous page, but so did both of the footnotes in 10:4 (while somehow the footnote in 10:3 got moved across in its entirety without a problem).

The second case is much better but still not publishable. Here a piece of the _second_ footnote in 10:4 was left on the TOP of the list of footnotes in the previous page (sorry the red mark points to the 1st footnote in 10:4 -- they are nearly identical -- but it should point to the second one). So this is again pretty weird.

Bottomline, neither of these results will allow us to print 1Cor. yet. 

I can only imagine the computational hoops needed to balance pages filled with footnotes. And how worse it is if those footnotes are near the bottom of the column of text, such that, as the columns/pages are balanced,  the footnote callers get moved across to the top of the next page. This (normally) causes the footnotes to move across also. But this often leaves a large gap at the bottom of the previous page. So then they are moved back, maybe?  I have no idea how many attempts are made to balance all of this, but I suspect this involves complex math. However it is done, somehow it is failing to format 1Cor. 10 correctly, with bits of footnotes getting left in the footnote section on the previous page.

**Comment by davidc86** [comment]
I'll try to send an archive, so you can play with it.

**Comment by davidc86** [comment]
[SLU-1Cor10PrintErrorArchive.zip](https://github.com/sillsdev/ptx2pdf/files/6970398/SLU-1Cor10PrintErrorArchive.zip)

**Comment by davidc86** [comment]
Is there a better way to give you Archives? The HELP section of PTXprint says email the archive after it is created, but not provide a link or email address to send it to. (Might should)

**Comment by markpenny** [comment]
> Is there a better way to give you Archives? The HELP section of PTXprint says email the archive after it is created, but not provide a link or email address to send it to. (Might should)

![image](https://user-images.githubusercontent.com/12962708/131210178-e25263e1-b4fe-4d4a-ad40-55f2c8054f57.png)

**Comment by mhosken** [comment]
The footnote in 1CO 10:4 occurs twice, identically, in two different places in the text. If you adjust the page layout such that 10:4 doesn't straddle a page break you will see the footnote occur twice on the same page. It's all behaving correctly.

**Comment by davidc86** [comment]
Well, actually those two footnotes in 10:4 are NOT identical. Just "mostly" identical, but one clarifies the term "wer" and the other clarifies the term "hatw": 

\f + \fr 10:4 \ft Ti ayat ne kbyohe, \fq **_wer a_** Hulasokwe inal ti sirke\fq*, neke tel mabuske ti Kitab Lanke kbyohe, \fqa **_minuman_** rohani\fqa*.\f* 
\f + \fr 10:4 \ft Ti ayat ne kbyohe, \fq **_hatw a_** Hulasokwe inal ti sirke\fq*, neke tel mabuske ti Kitab Lanke kbyohe, \fqa **_batu_** karang rohani\fqa*.\f* 

So that wasn't the problem. If you look carefully at the first two examples, the first one shows the 10:4 footnotes BEFORE the 9:25 footnote! (And it still shows the last two lines of a footnote for 10:2 at the top of the footnote section, but the full footnote appears on the next page .) 

The second example showed the last line of the second 10:4 footnote on the next (right-hand) page showing up at the top of the footnote section on the previous (left) page.

But the good news is, I just downloaded 1.9.3 and reran the export, and it formatted it correctly: 

![image](https://user-images.githubusercontent.com/65363206/131378876-3731d5a6-790b-4670-8006-af704445ce99.png)

**Comment by mhosken** [comment]
Aha. This is why I'm not a typesetter. I miss so much! yes I did notice the other problems but couldn't reproduce them in current code. Good news you can't either :)

Such issues are really tricky to resolve because finding the smoking gun is hard. So if you come across such a problem again. Please capture an archive immediately and we'll see if it exposes a bug deep in the depths. There is a lot of understanding that needs to go into producing such a typesetting engine and there is always more to learn.
