### ISSUE TITLE
Widow/Orphan Control still a problem

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#477]
I don't know why software thinks paragraphs need to have at least two lines to be readable. It seems lots of software behave this way, but in most typeset books I read, this isn't the case. 

Here is an example where it would have been much nicer to put the 2nd to last line of a paragraph on the bottom of the previous page, and leave the last line at the top of the next page. It would have not made it any more difficult to read, and would have made the pages more balanced.

![image](https://user-images.githubusercontent.com/65363206/128528664-c8fa77c5-4540-4712-a251-8ad8862f2469.png)

We would like a way to have PTXprint ignore all widow and orphan control behavior, and then we just have to tweak spacing for the few places that show up that are really ugly (like the last line of a paragraph is only two words long and it ends up at the top of the left-hand page followed by a chapter break). These bad occurrences are so rare I'd prefer to deal with them one by one than to get the default behavior of ragged bottom edges on lots of pages.

Is this possible to do in PTXprint already, but I just haven't figured it out yet? (I know there is a Poetry option, but wonder if there is a more general one, as I don't know the total ramifications of treating all books like poetry.)

BTW, I just tried the Poetry option with Optimized Layout checked, so I would get widow/orphan lines, but it didn't work! Here is a shot of another spread:

![image](https://user-images.githubusercontent.com/65363206/128530812-d083c8c9-b979-4dfa-8770-cc55181ba0e3.png)

NOTE: the bottom right page is missing a line because the top line of the next page has that paragraph ending with two lines: 

![image](https://user-images.githubusercontent.com/65363206/128531023-121920b4-07ec-45e3-b2b4-5422d9172959.png)

If PTXprint allowed that paragraph to end with a single line, then the top line could occur on the bottom of the previous page, making that spread look balanced and nice.

NOTE: Selecting the Poetry for this book did not fix the first layout issue either.

**Comment by mhosken** [comment]
If there is nothing to add to a previous issue that you consider should be
opened again, please reopen the issue and say why it is not working.
TIA

**Comment by mhosken** [comment]
Ignore my last comment. Sorry.

How loose do you want to go? Do we say we really don't care about widows
and orphans.

As an experiment try adding:

```
\clubpenalty=0
```

To ptxprint-mods.tex. does that help?

**Comment by davidc86** [comment]
The word "still" here is _not_ referring to a particular old Issue, but rather is referring to a general behavior that has been in PTXprint since Day 1. 

I'm just saying that there is (yet) no way to get PTXprint (or the underlying processes) to let paragraphs have ONE line on the top or bottom of a page. We believe this should be the default behavior, or at minimum an option, as it makes for neater looking PDFs.

**Comment by davidc86** [comment]
Thanks. I'll give that a try, just a sec.

**Comment by davidc86** [comment]
It doesn't seem to be doing anything, but then I've not used the ptxprint-mods.tex file for several months now, so I don't know if it is being saved into the correct configuration file, etc. (The configuration name in the comment line in the ptxprint-mods.tex file is different from the actual configuration name. So no idea about that either.)

**Comment by davidc86** [comment]
I verified the correct ptxprint-mods.tex file is being read. The line \clubpenalty=0 had no effect.

**Comment by mhosken** [comment]
See the advanced tab. There are controls for ptxprint-mods there for you.

**Comment by davidc86** [comment]
Here is the content of my ptxprint-mods.tex file:
% This is the .tex file specific for the SLU project used by PTXprint.
% Saved Configuration name: SelaruNewPublication
\TOCthreetabfalse
\clubpenalty=0

**Comment by davidc86** [comment]
It has no effect.

**Comment by davidg-sil** [comment]
Since that's a 2 line paragraph, you probably need to set `\widowpenalty=0` as well for it to take effect.

**Comment by davidc86** [comment]
Yes, that worked! Thanks. So,  can this be made a check box option, rather than a ptxprint-mods.tex command?
It could even have a value like 0,1,2,3 etc for specifying how much widow and orphan control a person wants. (Or just a checkbox that turns off widow and orphan control.)

**Comment by davidg-sil** [comment]
Unfortunately Tex's definition of widow or orphan/club paragraphs is fixed.
The only qn is how hard it tries to avoid them.

.

**Comment by markpenny** [comment]
@davidc86 I believe we already have a roundabout (and rather hidden!) way of doing what you're asking for in the UI.

![image](https://user-images.githubusercontent.com/12962708/128647171-307f9ab9-453e-4b61-9e53-aebfbc774edc.png)

The reason that we don't want to make this too easy is that good typesetting usually avoids having widows and orphans - so the default behavior needs to encourage that. But I hear what a lot of teams are saying, "Why is there such a big space at the end of this page when there's obviously enough space to fit a few more lines on?" - and that is a common complaint. I'm wondering whether we should be thinking in terms of a slider, and set the penalty values accordingly so that TeX can have enough flexibility to sometimes allow widow/orphan lines (and therefore less white space) but with unbalanced lines:
Balanced Columns <-----------------|------------> Widow/Orphan Lines

**Comment by davidc86** [comment]
I like this idea very much Mark. A slider is good. And it is repeatable. So I can see where a person could move it left or right to see which gives the best looking layout. Turning off all the widow and orphan controls on 1Cor. did have other less than great effects too, so a blanket On/Off is not necessarily the best approach. 

But looking through the text, I think having paragraphs allow just 1 line to occur at the top or bottom of a page (especially the 1st line of a paragraph on the bottom of a page) is okay. Less so the last line at the top of a page, if that line is very short. Even worse if that last line is short and the next thing is the start of a new section or worse a new chapter! So there is a scale of "badness". But to me, if the last line of a paragraph is "fairly long" (say, nearly half the column width, so as to be noticeable), then I say let it sit alone. As that line gets shorter, then factors like "before a section" and "before a chapter" weigh in on the decision. (I am NOT saying you guys need to implement such a complex process, but it helps to think through the whole range of "badness" that one can see in a document.)

**Comment by mhosken** [comment]
I've tagged this xetex for the moment while we work out the mapping of whatever we give the users to whatever TeX needs. It's tricky getting the penalties right and then thinking about how to present that to users.

**Comment by davidg-sil** [comment]
I don't know enough TeX to know if we can do this (I'm guessing it's yet another 'wait until luatex' idea), but I wonder if there could be some way that the balancing code could add some kind of `\unbalancedpenalty` between lines of the galley, to help the breaking algorithm

**Comment by markpenny** [comment]
Given the new balancing algorithm in 2.1 I think we can close this issue now. The new algorithm tries its best to balance, but IF it really can't, then it settles for 2nd best - which is "up to N lines of unbalanced text is OK" ; where N is set on the Layout tab, and can be anything as small as 0 (=always balance), or as large as 10. Usually 2 or 3 lines of unbalanced text is sufficient to avoid a really ugly page break with lots of white space.

My only thought is that it would be good to have a list of pages, or some highlighting showing which pages didn't auto-balance. That would make it easier for someone typesetting 2000+ pages :-)
