### ISSUE TITLE
Picture folder selection fails

### ISSUE THREAD

**Issue by Don-Tmin** [sillsdev/ptx2pdf#48]
I have trouble selecting the correct folder that my pictures are in. Even when I think I select the correct folder, and I know that the pictures are in that folder (maybe a few folder levels down). It searches elsewhere on my computer and finds the sample pictures instead. Also, it doesn't confirm which folder is selected, so I'm not quite sure where it's looking. 

I would like to have the option to select one folder, and have PTXprint search in only that folder - overrideing the file type and prefer low/high res.

**Comment by markpenny** [comment]
Thanks for this useful feedback. We used to have an option to "[ ] Search sub-folders" but thought it was redundant. Maybe it is time to bring it back! In the mean time, try moving the single folder to a new location where it doesn't have any sub-folders and it should work fine. However, note that it **also** looks in project/figures and project/local/figures - so is quite likely picking up images from there. If that is the case, would you also want to be able to turn OFF those locations? 
Maybe the new option needs to be called "[ ] Exclusively use selected folder" which would turn off the other 2 folders AND turn off sub-folder searches too.

**Comment by mhosken** [comment]
I'm assuming this is fixed. @don-tmin please review or else will close this bug

**Comment by markpenny** [comment]
I'll do this one today...

**Comment by markpenny** [comment]
This should help (and it will be available in 0.7.0 - being released later tonight):

![image](https://user-images.githubusercontent.com/12962708/82732475-0e762600-9d2b-11ea-91c3-b571be78d3b3.png)
