### ISSUE TITLE
Copy config to another project

### ISSUE THREAD

**Issue by mhosken** [sillsdev/ptx2pdf#480]
Add a UI and code to copy a config to another project, copying whatever is needed and updating files as appropriate.

**Comment by markpenny** [comment]
![image](https://user-images.githubusercontent.com/12962708/129878357-a14e4591-ec24-430c-a178-390c36bb459a.png)

**Comment by markpenny** [comment]
But we still need to make sure that the Config's .piclist file and picInfo.txt don't get copied across - or copy them over and then delete??? (a bit more dangerous - especially if they have a valid set of .piclist files in the target folder already)
