### ISSUE TITLE
ptxprint-mod.sty not being included from secondary diglot text

### ISSUE THREAD

**Issue by da4396** [sillsdev/ptx2pdf#483]
When printing a diglot, `ptxprint-mods.sty` from the secondary project is not being included in `PrintDraft/ptxprint-*.tex` in the primary project even though **Apply Stylesheet Overrides (ptxprint-mods.sty)** on the Advanced tab is checked in the secondary project.

Is this line in `/python/lib/ptxprint/runjob.py` the problem?
```python
"_diglotmodsty":            "c_useModsTex",
```
Should it be changed to this instead?
```python
"_diglotmodsty":            "c_useModsSty",
```

As a workaround, I checked **Apply Customized Settings (ptxprint-mods.tex)** in the secondary project which then included `ptxprint-mods.sty` in `PrintDraft/ptxprint-*.tex`.

**Comment by markpenny** [comment]
@da4396 Thanks for this, and for pointing us right to the line of code :-) We'll nail this one before 1.9.3 comes out (any day "yesterday")
