### ISSUE TITLE
--book fails to select book(s) to print on command line

### ISSUE THREAD

**Issue by da4396** [sillsdev/ptx2pdf#486]
I want to print each book of the NT as a separate PDF and figured I could run PTXprint on the command line and use soemthing like

`ptxprint --books LUK --print`
 
On the Basic tab in the configuration I am using, **Single Book** is selected and is set to `MRK` and **Multiple Books** is blank.

But here is what I found:
`--books LUK` printed MRK
`--books "LUK ACT"` printed MRK

It seems there might be two small typos in `/python/scripts/ptxprint` . Here is the existing code along with the suggested changes in comments.

```python 
if args.print or args.action is not None:
    ...
    if args.print:
        if args.books is not None and len(args.books):
            mainw.bookNoUpdate = True
            bl = args.books.split(" ")
            if len(bl) == 1:
                mainw.set("cb_book", bl[0])            # change "cb_book" to "ecb_book"
                mainw.set("r_book", "single")
            elif len(bl) > 1:
                mainw.set("t_booklist", args.books)
                mainw.set("r_booK", "multiple")        # change "r_booK" to "r_book"
```

Haven't tested these changes but figured I would at least submit them for review.

**Comment by markpenny** [comment]
Nice sleuthing work @da4396 !  When will you join the team? :-) 
This will be in 1.9.3 which should be released soon.
