### ISSUE TITLE
\zgap and \zrule needed

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#488]
Given that `\zbl|N\*` creates `N` blank lines, but these aren't maintained at the top of pages/columns, we need to have a way to introduce a vertical space when needed, for example at the top of the title page.

Proposing `\zgap|dimensions\*`  for this where dimensions can be something like `1.5in plus 10pt minus 5pt`

Similarly, we need a way to introduce a horizontal rule, often used to separate intro matter from the rest of scripture.

Proposing `\zrule|width="N.N" align="Y"\*` 
where `N.N` represents the width of the rule relative to the width of text column area, 
and `Y` is `L`, `C` or `R` representing Left, Center, or Right alignment. 
If no parameters are passed (i.e. `\zrule|\*`) then it should be **0.5** width and **C**enter aligned.

**Comment by davidg-sil** [comment]
Hmm. Some comments: 
I see that `\zbl` is introduced as a magic regex. Passing actual numbers to TeX from a USFM file is... a wee bit tricky, as they're read as letters and will need reinterpreting. Not saying it can't be done, just tricky.

But to make blank lines not vanish at the top of the page, you can probably insert something like `\ZWNBSP` beforehand and then they all ought to 'appear' (unless there's page break triggered the first few `\b`s).

`\zgap` as described above seems likely to break grid, which would be problematical, and with the above and gaps not vanishing at the top of page, seems needless.

**Comment by cmahte** [comment]
I use these actual USFM tags for this type of construct: 

\sd 

\sd# (where # = 0-9 number of lines, 0=.5 line) 
*** This seems to be in the spec like this ***

\b# (where # = 0-9 number of lines, 0=.5 line) 

\ib# (where # = 0-9 number of lines, 0=.5 line) 

\imt9 ~

For the rule, I use \mte8 ~ , and \imte8 ~ mostly because thats where it shows up in examples.  I suppose there's a case for \sd8 to be rendered as a horizontal rule also.

The \b# and \ib# predate the creation of the \sd# tag in the spec. They may be apocryphal for all USFM flavors... I seem to remember them in 2.35 or 2.4...

**Comment by davidg-sil** [comment]
Test of current `\zrule`  and `\zgap` implementation. Default attribute of `\zrule` is currently `width`.
`\zgap` makes no attempt at re-gridding.
![image](https://user-images.githubusercontent.com/58848232/131551027-9abf70e0-1905-4507-b343-338a9864be37.png)

**Comment by markpenny** [comment]
Thanks @davidg-sil That works. But I noticed a couple of things:

1. When I use \zgap _at the top of a page_, it behaves similarly to \zbl in that it doesn't appear unless there's a marker or some text above it. We need it to insert a gap regardless of where it turns up.

2. I am realizing that the \zrule\* params probably need some tweaking, especially as some people will want a heavier line than others. I noticed it was a 1pt line by default, and that looked too heavy to me, so I changed the TeX code to 0.5 which looks about right as a default. Could you add a 'thick' parameter with 0.5pt as the default?

**Comment by davidg-sil** [comment]
Oops. This is done on my machine, but the I forgot to commit and it's now tangled up with the stuff on pictures.
