### ISSUE TITLE
Multi-book PDF won't Bookmark beginning of some books

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#49]
Multi-book PDF won't Bookmark beginning of some books if there is a \rem field anywhere between the \id line and the book title field.
So this is valid:
\id COL - Selaru
\h Kolose 
\toc3 Kol. 
\toc2 Kolose 
\toc1 Kolose 
\mt2 Atyahy ne kyosy Paulus ti iry a matohakare ti 
\mt Kolose

But if there is a \rem field anywhere in there, PTXprint will not flag this as a new book, and will combine it with the previous book. 
WORKAROUND: edit Ch1 of each book and move all \rem fields to the end of the intro section (just before \c 1).
SOLUTION NEEDED:
\rem fields should be ignored, so when the daft SFM file is exported by PTXprint, it should just pitch them right out of the gate. This way they don't interfere with any PDF processing, and users don't have to move all their \rem fields down below the Intro. in every book.

**Comment by markpenny** [comment]
Thanks for this good sleuthing work @davidc86 ! We'll pitch all the following nonpublishable markers so they don't interfere: \usfm \ide **\rem** \sts \restore \pubinfo
The fix should be available in 0.6.2 - probably available for download in the next few hours.
