### ISSUE TITLE
zgap and glue

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#495]
currently `\zgap| 9em plus 2em\*` puts  "plus 2em" in the text.

**Comment by mhosken** [comment]
That's because it should have a | in front and since there are spaces it should have the attribute made explicit.
```
\zgap |dimension="9em plus 2em"\*
```
`dimension`? Really? How about `gap` or `height`?

It might even work without the explicit attribute, I'm not sure, but you definitely need the `|`.

**Comment by davidg-sil** [comment]
OK, OK,  I've corrected the typo.

The issue is not actually parsing, it's the late-stage change to use a kern (fixed dimension, with `plus...` ignored) instead of a skip (flexible glue). Revised implementation:
```
\vbox{}\penalty10000\vskip\gap@dim
```
Hopefully this will neither break nor vanish at the top of a page.

**Comment by davidg-sil** [comment]
the empty vbox is to ensure that the skip does not vanish at the top of a page.
