### ISSUE TITLE
Basic booklet cover maker (+/- support for spine)

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#498]
Given that we do everything else, it would be neat to also create a simple cover sheet for booklets. Select an image, or background colour, and/or border and set a title, font, size etc. Also, if publication is > 100 pages, then provide support for spine too.

**Comment by davidc86** [comment]
Sweet. This will be helpful. And I see Mark that you have added a pile of "enhancement" requests. of late I agree with them all and had thought about bringing some of these up, but didn't think that my adding to the pile was something you'd want at this point. Great software, just keeps getting better.

**Comment by markpenny** [comment]
We need to hear from the Nov Karimu workshop participants as to what is needed. Then we can build it.
