### ISSUE TITLE
PTXprint-0.2 doesn't produce PDF

### ISSUE THREAD

**Issue by philleckrone** [sillsdev/ptx2pdf#5]
I get the following error when running PTXprint-0.2. The Options open, but no PDF is produced
![Screenshot 2019-11-20 06 59 32](https://user-images.githubusercontent.com/37958474/69243654-80e62d80-0b71-11ea-8d58-1444b5fc2194.png)

**Comment by philleckrone** [comment]
I've tried starting the exe as Administrator and with PT open and closed.

**Comment by philleckrone** [comment]
Here is the log file
[ptxprint-MAT_REVACR_ATU.log](https://github.com/sillsdev/ptx2pdf/files/3869491/ptxprint-MAT_REVACR_ATU.log)

**Comment by markpenny** [comment]
Hi Phil, try turning off this option:
![image](https://user-images.githubusercontent.com/12962708/69252276-c427b700-0bd8-11ea-8ed0-efe776e30939.png)
That option is problematic as it needs several different pieces in place to work well:
\iot Intro Outline Title
\io1 Some text \ior 1:1-3:4\ior*
\io1 Some more text \ior 3:5-3:20\ior*
etc.
\io1 Last line of outline text \ior 6:1-6:16\ior*
\c 1

**Comment by philleckrone** [comment]
Great Mark - that produced the PDF (in seconds). It is interesting that
before selecting a project the option is unselected, but once a project is
selected it defaults to checked. Unchecking if allowed the PDf to work

Phil Leckrone
Americas Area Language Technology Coordinator
language_software_amareasil@sil.org
704-843-6064 (Office at JAARS)
704-213-2604 (Cell)
Skype name: phil_leckrone

**Comment by markpenny** [comment]
OK - that's fixed now so that once it is unselected it stays that way unless you intentionally select it again. Thanks for helping us squash the bug.
