### ISSUE TITLE
Add an option to have the header in a second language/script

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#500]
Some regions of the world (Biblica South Asia, + BSI India) use 2 different languages or scripts for the header. Currently this is not possible, but perhaps it could be made possible. Consideration also has to be given to digit styles, styling of text, size and fonts etc.

**Comment by mhosken** [comment]
I've worked out how to do it:
![image](https://user-images.githubusercontent.com/5687149/131971446-f79901c6-5b79-4dcb-98c7-a89ffb575e62.png)
You will also probably need to add
```
\OmitBookReftrue
```
to your ptxprint-mods.tex

**Comment by markpenny** [comment]
Looks great - and tomorrow I'll try to work out how to use it (and make it accessible/documented) for other non-technical users too.

**Comment by mhosken** [comment]
Changed this from \zbka and \zbk to \bookalt and \book. One can also use \bookL and \bookR in diglot contexts (he says hopefully).

**Comment by markpenny** [comment]
To help document this for users who will require this feature:
The USFM needs to have an \h marker for the (primary) book name called "Book (\h)" in the dropdown menu, and
if you want an alternate name or script, it needs an \h1 marker for the "Book Alt (\h1)" in the USFM. However, if
you don't have editing rights to the USFM, or don't want to mess it up, you can use the PrintDraftChanges.txt file
like this to insert the additional \h1 codes:
```
'(\\h mārk)(\r?\n)'  > '\1\2\\h1 Mark\2'
'(\\h lūka)(\r?\n)'  > '\1\2\\h1 Luke\2'
... etc.
'(\\h hebri)(\r?\n)' > '\1\2\\h1 Hebrews\2'
```
This then creates the extra \h1 "on the fly":
![image](https://user-images.githubusercontent.com/12962708/132922575-c18c49b1-d801-4ca5-8040-6ab861e143e1.png)

To then get the headers to use this additional code, you will need to do some clever work in the Header settings:
![image](https://user-images.githubusercontent.com/12962708/132922672-86644f99-9f4f-414e-b565-d55eca5fc964.png)
For the **Inner (Left)** setting, manually type `\bookalt\ \rangeref` and for the **outer** setting type `\book\ \rangeref` and also turn OFF (uncheck) the "Include in References: [  ] Book" option as shown above. Of course you can choose whether you want the verse numbers showing or not.

If all goes well, you should see:
![image](https://user-images.githubusercontent.com/12962708/132922302-b4488477-b54d-478b-8fae-a0420137b80a.png)

**Comment by markpenny** [comment]
Here is some generic code that will work for any language back into English:
```
"(\\id\sMAT\s.+)(\r?\n)" > "\1\2\h1 Matthew\2"
"(\\id\sMRK\s.+)(\r?\n)" > "\1\2\h1 Mark\2"
"(\\id\sLUK\s.+)(\r?\n)" > "\1\2\h1 Luke\2"
"(\\id\sJHN\s.+)(\r?\n)" > "\1\2\h1 John\2"
"(\\id\sACT\s.+)(\r?\n)" > "\1\2\h1 Acts\2"
"(\\id\sROM\s.+)(\r?\n)" > "\1\2\h1 Romans\2"
"(\\id\s1CO\s.+)(\r?\n)" > "\1\2\h1 1 Corinthians\2"
"(\\id\s2CO\s.+)(\r?\n)" > "\1\2\h1 2 Corinthians\2"
"(\\id\sGAL\s.+)(\r?\n)" > "\1\2\h1 Galatians\2"
"(\\id\sEPH\s.+)(\r?\n)" > "\1\2\h1 Ephesians\2"
"(\\id\sPHP\s.+)(\r?\n)" > "\1\2\h1 Philippians\2"
"(\\id\sCOL\s.+)(\r?\n)" > "\1\2\h1 Colossians\2"
"(\\id\s1TH\s.+)(\r?\n)" > "\1\2\h1 1 Thessalonians\2"
"(\\id\s2TH\s.+)(\r?\n)" > "\1\2\h1 2 Thessalonians\2"
"(\\id\s1TI\s.+)(\r?\n)" > "\1\2\h1 1 Timothy\2"
"(\\id\s2TI\s.+)(\r?\n)" > "\1\2\h1 2 Timothy\2"
"(\\id\sTIT\s.+)(\r?\n)" > "\1\2\h1 Titus\2"
"(\\id\sPHM\s.+)(\r?\n)" > "\1\2\h1 Philemon\2"
"(\\id\sHEB\s.+)(\r?\n)" > "\1\2\h1 Hebrews\2"
"(\\id\sJAS\s.+)(\r?\n)" > "\1\2\h1 James\2"
"(\\id\s1PE\s.+)(\r?\n)" > "\1\2\h1 1 Peter\2"
"(\\id\s2PE\s.+)(\r?\n)" > "\1\2\h1 2 Peter\2"
"(\\id\s1JN\s.+)(\r?\n)" > "\1\2\h1 1 John\2"
"(\\id\s2JN\s.+)(\r?\n)" > "\1\2\h1 2 John\2"
"(\\id\s3JN\s.+)(\r?\n)" > "\1\2\h1 3 John\2"
"(\\id\sJUD\s.+)(\r?\n)" > "\1\2\h1 Jude\2"
"(\\id\sREV\s.+)(\r?\n)" > "\1\2\h1 Revelation\2"
"(\\id\sGEN\s.+)(\r?\n)" > "\1\2\h1 Genesis\2"
"(\\id\sEXO\s.+)(\r?\n)" > "\1\2\h1 Exodus\2"
"(\\id\sLEV\s.+)(\r?\n)" > "\1\2\h1 Leviticus\2"
"(\\id\sNUM\s.+)(\r?\n)" > "\1\2\h1 Numbers\2"
"(\\id\sDEU\s.+)(\r?\n)" > "\1\2\h1 Deuteronomy\2"
"(\\id\sJOS\s.+)(\r?\n)" > "\1\2\h1 Joshua\2"
"(\\id\sJDG\s.+)(\r?\n)" > "\1\2\h1 Judges\2"
"(\\id\sRUT\s.+)(\r?\n)" > "\1\2\h1 Ruth\2"
"(\\id\s1SA\s.+)(\r?\n)" > "\1\2\h1 1 Samuel\2"
"(\\id\s2SA\s.+)(\r?\n)" > "\1\2\h1 2 Samuel\2"
"(\\id\s1KI\s.+)(\r?\n)" > "\1\2\h1 1 Kings\2"
"(\\id\s2KI\s.+)(\r?\n)" > "\1\2\h1 2 Kings\2"
"(\\id\s1CH\s.+)(\r?\n)" > "\1\2\h1 1 Chronicles\2"
"(\\id\s2CH\s.+)(\r?\n)" > "\1\2\h1 2 Chronicles\2"
"(\\id\sEZR\s.+)(\r?\n)" > "\1\2\h1 Ezra\2"
"(\\id\sNEH\s.+)(\r?\n)" > "\1\2\h1 Nehemiah\2"
"(\\id\sEST\s.+)(\r?\n)" > "\1\2\h1 Esther\2"
"(\\id\sJOB\s.+)(\r?\n)" > "\1\2\h1 Job\2"
"(\\id\sPSA\s.+)(\r?\n)" > "\1\2\h1 Psalms\2"
"(\\id\sPRO\s.+)(\r?\n)" > "\1\2\h1 Proverbs\2"
"(\\id\sECC\s.+)(\r?\n)" > "\1\2\h1 Ecclesiastes\2"
"(\\id\sSNG\s.+)(\r?\n)" > "\1\2\h1 Song of Songs\2"
"(\\id\sISA\s.+)(\r?\n)" > "\1\2\h1 Isaiah\2"
"(\\id\sJER\s.+)(\r?\n)" > "\1\2\h1 Jeremiah\2"
"(\\id\sLAM\s.+)(\r?\n)" > "\1\2\h1 Lamentations\2"
"(\\id\sEZK\s.+)(\r?\n)" > "\1\2\h1 Ezekiel\2"
"(\\id\sDAN\s.+)(\r?\n)" > "\1\2\h1 Daniel\2"
"(\\id\sHOS\s.+)(\r?\n)" > "\1\2\h1 Hosea\2"
"(\\id\sJOL\s.+)(\r?\n)" > "\1\2\h1 Joel\2"
"(\\id\sAMO\s.+)(\r?\n)" > "\1\2\h1 Amos\2"
"(\\id\sOBA\s.+)(\r?\n)" > "\1\2\h1 Obadiah\2"
"(\\id\sJON\s.+)(\r?\n)" > "\1\2\h1 Jonah\2"
"(\\id\sMIC\s.+)(\r?\n)" > "\1\2\h1 Micah\2"
"(\\id\sNAM\s.+)(\r?\n)" > "\1\2\h1 Nahum\2"
"(\\id\sHAB\s.+)(\r?\n)" > "\1\2\h1 Habakkuk\2"
"(\\id\sZEP\s.+)(\r?\n)" > "\1\2\h1 Zephaniah\2"
"(\\id\sHAG\s.+)(\r?\n)" > "\1\2\h1 Haggai\2"
"(\\id\sZEC\s.+)(\r?\n)" > "\1\2\h1 Zechariah\2"
"(\\id\sMAL\s.+)(\r?\n)" > "\1\2\h1 Malachi\2"

```

**Comment by markpenny** [comment]
Note that the Font dialog now allows you to set the digit script mapping, so you can also have the digits in different scripts. Set the \h style for one type of digit, and \h1 for the other digits. See [details here](https://community.scripture.software.sil.org/t/how-to-use-non-western-digits/2770).

**Comment by markpenny** [comment]
@mhosken - This doesn't seem to be working. I'm not sure when the regression was introduced, but we need to fix it ASAP.

**Comment by mhosken** [comment]
It is working. Just not in the way you are expecting. \h1 does get picked up as \bookalt. But the whole header line is set using \h styling. \h1 styling is never used. If you want to style one of the header components differently, then you will need to use a character style around it. For example:
```
\wl \bookalt\ \rangeref\wl*
```
