### ISSUE TITLE
 "Hide Empty Verses" has a dependency on "Auto-Correct USFM" 

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#502]
We need to either turn it on in the UI for the user (and prevent them from turning it off), or just do it programmatically behind the scenes and "check USFM" if Hide Empty Verses is enabled.

**Comment by mhosken** [comment]
Yes there was a bug that hide verses wasn't running unless some other reason to load the doc was. I've changed it at the code level. There is no visual indication of this, and we can add that if we want. But at least now it will do the right thing.

**Comment by markpenny** [comment]
Fixed, and will be available in next release 1.9.4
