### ISSUE TITLE
Full-page picture vertical alignment issues

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#505]
`pgpos="Fct"` ought to position the image at the top of the page, `Fcc` in the middle, and `Fcb` at the bottom. Something considerably weirder is happening, and only `Fcb` is working as expected.
Swittching between `Pcb`/`Pct`/`Pcc` isn't  having any noticiable effect.

**Comment by markpenny** [comment]
Thanks @davidg-sil for looking into this. While you're in there looking at the code, could you also check/confirm whether the absence of a 'c' for both `P` and `F` implies 'c' for both the horiz and vert posn parameters.
i.e. `F` is equivalent to `Fcc`
    and `Ft` would have the same effect as `Fct`
    and `Pb` is the same as `Pcb`
    and `Pr` is equivalent to `Prc`

**Comment by davidg-sil** [comment]
The second letter of all codes is *always* the horizontal parameter: l/r/c/i/o (left/right/center/inner/outer), therefore you can't put `t` in there and expect sanity.
I'm currently aiming for the following:
* Implicit understanding that `F` = `Fc`  and `P` = `Pc`
* Any explicit vertical positioning (`t`, `b` or `c`) makes the image the only one on the page.
* Leaving the vertical positioning unspecified normally centers an image, but if there are 2 images wanting to go on an 'images page' and they both fit on a single page, then it'll try to space them out nicely and save paper by doing  that. I had that working for `P` last night, then broke it in  a refactor

**Comment by davidg-sil** [comment]
Known problem with multiple successive images set 'F' without an explicit vertical position. It works fine for 'P' though.

**Comment by markpenny** [comment]
There's still a minor (?) issue outstanding with the center headers on P images not being centered horizontally:
![2021-09-08 07_56_40-ptxprint-Default-HEBESG pdf -  Aheri Gondi  - SumatraPDF](https://user-images.githubusercontent.com/12962708/132500474-f423e55c-a1b1-4060-83bf-dfc3eb7d22d7.png)

**Comment by davidg-sil** [comment]
This is odd, as I'm not aware of touching anything that would cause this effect.... AFAIK, it  just supplies a box to the normal output routine.

**Comment by mhosken** [comment]
I fixed a minor error in headings. Can you recheck on the off chance that it cleared this up. The headers issue is probably a different problem to the full page image?

**Comment by davidg-sil** [comment]
I think this is all fixed in latest commit
