### ISSUE TITLE
Footnote text not wrapping 

### ISSUE THREAD

**Issue by oyuntugs-ctrl** [sillsdev/ptx2pdf#507]
Hello. My name is Oyuntugs. I use PTXprint(1.8.9.1 version) for creating Pdf from Paratext. But in this version footnote texts not wrapping. 
![Capture](https://user-images.githubusercontent.com/74051653/132282233-d2133f3a-f792-4c4f-9513-a3fc2790d8b5.PNG)

**Comment by markpenny** [comment]
Hi Oyuntugs, 
Thanks for reporting this. Are you able to download the latest version (currently 1.9.3) or wait a couple of days and download (1.9.4) to see if the problem exists in a newer version? Also, for us to repeat this error and fix it, it would be helpful if you can send us an Archive .zip file (by using the "Create Archive" button on the Help tab/page). Send to ptxprint_support@sil.org
Thanks, Mark

**Comment by oyuntugs-ctrl** [comment]
Hello. 
I have deleted the configuration file (folder inside "Shared").  And recreated my configuration. Now it is working correctly. Thank you for your response.
