### ISSUE TITLE
1 line diglot footnotes get a the footnoterule going through them

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#508]
Seems to only affect single line footnotes. Also, the centre rule seems to be missing.

**Comment by markpenny** [comment]
@mhosken just fixed the centre rule. Do you have an image or .zip for the footnoterule?

**Comment by davidg-sil** [comment]
Yes, I have a .zip. Got called away yesterday PM, or would have looked into it.

**Comment by davidg-sil** [comment]
Further testing revealed that this was only present in some one-line footnotes. For future reference, this was caused by \baselineskip of 0 and a negative `\baselinelimit` (inherited from the main text?) that was less than the note height.
