### ISSUE TITLE
Non-merge for seperately sorted diglot glossary

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#509]
If there's a glossary in a diglot were the two alphabets are separately sorted, then they shouldn't be aligned.
The output might need to be:
```
\lefttext
% Left-hand header material
\ritghttext
% Right-hand 
\lefttext
All of the rest of the left hand side (primary)
\rigthtext
All of the rest of the right hand side (secondary)
```
Alternatively it might be sufficient now to not split the files at all, and just load them all. At *some* point, internal limits of TeX will be reached, with the boxes being too big.

**Comment by davidg-sil** [comment]
An alternate approach (avoiding the problem of trying to fit the whole of a file into a single box without it getting more than 575cm tall, ~= 20 pages) might be to have some special TeX code that reads lines from two separate files. The problem with such code is that it would need to know to keep on reading until any groups (e.g. footnotes, side-bars, headings) are closed.

It's tempting to say that the approach of  producing 2 half-width PDFs would be less prone to errors.

**Comment by mhosken** [comment]
Could we have the ability to switch from two columns to two pages or even two books? So the left glossary followed by the right glossary?

**Comment by davidg-sil** [comment]
That doesn't sound unreasonable to me.

**Comment by davidg-sil** [comment]
As a further comment on MH's question "Could we have the ability to switch from two columns to two pages or even two books? So the left glossary followed by the right glossary?" : a return to monoglot is entirely possible, and would require a reloading of stylesheets.

However, it ought to be possible to have a `\monoglotptxfile{L}{filename.USFM}` which would set up all the right internal variables without the need to switch stylesheets, etc. 
Or some other method could be done, e.g. where the merge file contains `\monoglot L` for pure left sections, etc.

**Comment by mhosken** [comment]
Given we now have \dglot |L\* it sounds like we just need a command to drop back from diglot to monoglot. Does that happen automatically at \ptxfile?

**Comment by davidg-sil** [comment]
Yes, `\zglot|L*`  is 3/4 of the way there.
`\ptxfile` starts off in column L if diglot is true, and uses `\diglotcolumns`

I wrote `\zglot| *` (blank argument) to set `\diglotfalse`, but I've not tested it, and I'm not sure if it impacts running via the GUI these days. (With diglot false, styling ought to ignore stylesheets loaded L or R.)

Dropping from diglot to monoglot is `\diglotfalse\singlecolumn` or `\diglotfalse\doublecolumns` as preferred
Switching to diglot layout can be done with `\diglottrue\diglotcolumns`.

I'd say the TeX code is 98% there, it's 'just' the UI work.

**Comment by markpenny** [comment]
@davidg-sil I think we've done this now, right? Can it be closed?
