### ISSUE TITLE
Cross-refs spread across page when "group in paragraph" is used (in some cases).

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#51]
Cross-refs spread across page when "group in paragraph" is used (in some cases). I do have the paragraph set to Justified, but that shouldn't cause the cross-references to spread out across the page.
For example this list:
**2:7** ________ 1Kor. ________ 15:45 ________ **2:9** ________ Why. ________ 2:7; ________ 22:2,14
Stretches from margin to margin with even spaces between each string (can't reproduce it here, so imagine the '_' characters are spaces).
HACK:
Turn of "group in paragraph" and they stack nicely. 
I also suspect that if I turned of Justified they might not stretch out. But the last or only line of a justified pp shouldn't stretch out anyway.
BTW, I figured out how to control Justification with the PrintDraft-mods stylesheet. (tweak the \x marker), and reran the process. It helped SOME. Now they don't stretch all the way across the page. Rather there are just very large gaps where single spaces should be. So it stretches over 1/2 way across the page. Still weird. So, I'm just turning that off for now.

**Comment by markpenny** [comment]
Strange, I'm not seeing that (unless you mean the yellow gaps in the image below):
![image](https://user-images.githubusercontent.com/12962708/82032432-cfa3f880-96b8-11ea-8384-19dc16dfd25e.png)
Send a screenshot if that helps, and a copy of your .sty file(s) offline...

**Comment by davidc86** [comment]
Okay, I’m seeing this when Justification is OFF for the xref line, i.e. In the PrintDraft-mods.sty I have this spec’d the \x field as:

\Marker x
\FontSize 9
\Justification Left

And this is what I get:

[cid:image001.png@01D62AFC.5E84E060]

I find that spacing to be way too large. Why is there any spacing at all? It’s set to “justified left” (which I assume is computerese for “not-justified”), so it should not add any padding spaces at all.

NOTE: my setup is for single column pages. Might that have some affect? (I see yours is double-column.)

Now if I change this to:

\Marker x
\FontSize 9
\Justification

Then I get this:

[cid:image002.png@01D62AFC.5E84E060]

Which is just not pretty.

So, I get the program adding padding to justified a line in a paragraph, but in this case it is acting weird, because a justified paragraph never stretches if it is only one line, nor does it stretch the last line if it is more than one line. So it looks to me like there is hidden stuff causing PTXprint to “think” it wraps.

Hope this helps you track down what is going on, because I would like to group them as a paragraph, it takes less space and is neater. (I could live with non-justified, but in that case single spaces is what we’d expect to see.)

Thanks for a cool tool,
David

**Comment by mhosken** [comment]
Sorry your images didn't come through. Could you go to the issue page and either edit the issue to add them or submit a new comment with them in. Thanks.

**Comment by davidc86** [comment]
Okay, I tried to paste screenshots but it only uploaded them with links, they didn’t embed like others have. Not sure why. Hope this is adequate.

**Comment by mhosken** [comment]
Lots has happened in the last day on paragraphed footnotes. Please review 0.6.7

**Comment by davidc86** [comment]
Most of the cross-references look acceptable and "well-behaved". But occasionally I still am seeing stretched references:

![image](https://user-images.githubusercontent.com/65363206/82478848-84665d00-9a9f-11ea-8db1-9f81aebe32ee.png)

No clue or pattern I can see yet. Though I wonder if the large multi-line footnote above it has any bearing on how the cross-reference line formats.

**Comment by markpenny** [comment]
Thanks for letting us know... It remains a mystery, but we'll have to keep digging until we find it.

**Comment by mhosken** [comment]
This should be fixed now. Not sure in what version, but certainly anything after today.
