### ISSUE TITLE
Vertical Rule in Gutter is disconnected when footnotes are present in diglot

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#517]
![image](https://user-images.githubusercontent.com/12962708/132925798-308a4b1e-2f59-4534-ad90-d42539bfb8f3.png)

![image](https://user-images.githubusercontent.com/12962708/132925432-9405c294-f373-4f12-a624-35c205dd5525.png)

**Comment by davidg-sil** [comment]
You don't like that feature, then?

**Comment by davidg-sil** [comment]
Those that don't like the gaps in example pages 51 and 58 can now have the gutter rule  for the 'abovenotespace' gap above the notes.  Page 51 type gaps, however, are not currently calculated or filled in, as that's trickier.

**Comment by markpenny** [comment]
@davidg-sil Did you mean to say **pg50** type gaps are not filled in? If so, that's understandable.

**Comment by markpenny** [comment]
Given that no one else has complained about this issue, and it hasn't been urgent enough to fix; I think it is best to close it.
