### ISSUE TITLE
Issues with acrostic poem

### ISSUE THREAD

**Issue by oyuntugs-ctrl** [sillsdev/ptx2pdf#518]
Hello. I am working on acrostic poems in Lamentations. I got 2 issues with this book. 
First, This book has  \pc and \c tags.  When \pc tag is after \c tag, chapter number occurs over text.  It is shown in the second screenshot.

Second, As shown in the last screenshot. We got a Hebrew letter on this acrostic poem.  But the bracket of the Hebrew letter is wrong. 

Screenshot of Paratext's unformatted view.
![cap4](https://user-images.githubusercontent.com/74051653/133056298-35c89c08-7d0d-4084-962f-9f984a77fe10.PNG)
Screenshot of Pdf converted by PtxPrint.
![cap3](https://user-images.githubusercontent.com/74051653/133056297-42f9fbf1-828d-4c01-83c4-4c7ee69322c0.PNG)
Screenshot of Paratext's formatted view.
![cap2](https://user-images.githubusercontent.com/74051653/133056292-bc200d71-1047-45d0-b999-f9bf219e28cb.PNG)

**Comment by mhosken** [comment]
There are two issues here:
- The mirrored open parenthesis can probably be fixed by inserting a left to right mark before it, as in this change: `'(\([\u05D0-\u05EA])' > '\u2066\1'` (untested).
- The chapter number, I assume, wants to be over on the left and cutout the second paragraph too.

I would also suggest that perhaps \pc isn't the best here. I'm assuming you want something with a large left indent. Perhaps \pi3 (and then mess with the indent). I doubt it will fix your chapter number problem, but it might make the text look less ragged.

**Comment by davidg-sil** [comment]
Usually, with Psalms, (especially ones laid out as you have here) you don't want to use a 'dropped' chapter number (2 line high number in a box cut-out from the first 2 lines of the paragraph). It looks like that's what you have here. 
`\cl Psalm` (in the local language!) before `\c 1`  will make a heading looking like 'Psalm 1' for all Psalms. You can also make the book-wide `\cl` appear in other places, see: [here](https://github.com/sillsdev/ptx2pdf/tree/master/docs/documentation#ptx2pdf-MacroSetupParameters-Chapters&Verses).  If you don't want text there, just the chapter number, you could put `\cl \ZWNBSP`  then you will get a zero-width non-breaking space before the chapter number, I.e. just the number.  You can also specify individual titles, of course:
```
\c 23
\cl The Twenty-third Psalm
```

**Comment by oyuntugs-ctrl** [comment]
> Usually, with Psalms, (especially ones laid out as you have here) you don't want to use a 'dropped' chapter number (2 line high number in a box cut-out from the first 2 lines of the paragraph). It looks like that's what you have here.
> `\cl Psalm` (in the local language!) before `\c 1` will make a heading looking like 'Psalm 1' for all Psalms. You can also make the book-wide `\cl` appear in other places, see: [here](https://github.com/sillsdev/ptx2pdf/tree/master/docs/documentation#ptx2pdf-MacroSetupParameters-Chapters&Verses). If you don't want text there, just the chapter number, you could put `\cl \ZWNBSP` then you will get a zero-width non-breaking space before the chapter number, I.e. just the number. You can also specify individual titles, of course:
> 
> ```
> \c 23
> \cl The Twenty-third Psalm
> ```

I have tested \cl \ZWNBSP and it works correctly. Thank you for your advice.
