### ISSUE TITLE
Front Matter crash in v1.9.4

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#519]
Just installed v1.9.4 and ran it, and clicked Print.
Got this: 

![image](https://user-images.githubusercontent.com/65363206/133323710-e8754838-f2da-4080-9bde-b134d967b201.png)

I did not change anything from v1.9.3  to v1.9.4 (either in the FRT book nor in the PTXprint software configuration). So something changed between v1.9.3 to v1.9.4 that broke the process.

It says something about p not defined (which it is) and toc4 etc. But I'm not using the TOC feature for this test, so I'm a bit baffled where to go from here.

I thought the problem might be the SPACE in the PDF's filename, but after I changed that, it still failed (but at least reported the correct filename -- so that also might be a bug/limitation PTXprint needs to filter for): 

![image](https://user-images.githubusercontent.com/65363206/133325463-85fa067a-e236-4354-9cc2-a7e053ad3f15.png)

There is nothing wrong with the Front Matter PDF file. It opens just fine in a Reader, and is the exact same one that worked for PTXprint v1.9.3.

Thinking it might be a file location issue, I moved the PDF file to the folder PTXprint wants stuff to be in, but it still fails exactly the same way.

If I deselect the PDF option on the Peripherals page, then the Print process works just fine. 

I suspect a bug in the handling of PDF front matter files.

**Comment by markpenny** [comment]
Hi @davidc86 - yes, I got bitten by the same regression yesterday, and mentioned it to MH. But looking at the latest code and testing it shows that this has been fixed already. So watch out for 1.9.5 whenever that comes out...
