### ISSUE TITLE
Not sure how to get \nd .... \*nd in a footnote to JUST apply CAPS attribute, not FONT SIZE

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#52]
If a name of God (\nd...\nd*) occurs in a footnote, and the footnote is set to be significantly smaller than the body text, the \nd should inherit the fontsize from the surrounding text, i.e. How do we mark attributes as "undefined", i.e. how to we get some of a markers attributes to "inherit" from other markers?   
I think I've determined that the order is custom.sty --> PrintDraft-mods.sty
Because it seems that most every tweak I make in custom.sty is ignored, but if I put it in the PrintDraft-mods.sty it sometimes works. (I made a \marker nd...nd* entry and added \FontSize 9 in the PrintDraft-mods.sty. This now makes the names of God small in the footnotes. But I suspect that if I use \nd in the verse, it will appear very small!

**Comment by davidg-sil** [comment]
Old style is that you edit your stylesheet make your own \fnd  for footnotes, \snd, \s1nd \s2nd for, \s3nd for section heads, etc. You can then mangle your usfm (confusing people when you forget one) or use [this code](https://gist.github.com/davidg-sil/3886e3367844f58c1170851127bd0611)  to apply them in context (hopefully the pattern is clear enough if you need to  expand it). This doesn't save you from copy and paste-ing the stylesheet definitions, but it seems to work.

usfm3 style is to use \+nd ...\+nd*  so-called _stacking markers_. I'm not sure if paratext does some magic on print-draft export or quite how it's supposed to work, but when I accidentally  had such markers in a test file (not via paratext) I was using yesterday to help me debug the diglot stuff I'm working on, xetex gave me some lovely weird errors.

**Comment by markpenny** [comment]
MH has done some magic on this now. Here's what you need to know:
1) It will only work if the font itself supports the SmallCaps feature.
2) It won't work [at present] if Graphite is turned on - check the Advanced tab.
3) You'll probably need to add something to your .sty file (I recommend using PrintDraft-mods.sty)
```
\Marker nd
\Smallcaps
\FontSize .95 
```
4) The \FontSize param can be used to scale the Caps larger/smaller (so .95 = 95%) if you don't like the default size. AFAIK, this is (now) relative to the size of the existing paragraph fontsize. 1=100%

Let us know how it goes, but you should be able to do something like this now:

![image](https://user-images.githubusercontent.com/12962708/82037465-c9654a80-96bf-11ea-9129-3b4848168e50.png)
and in the footnotes:
![image](https://user-images.githubusercontent.com/12962708/82037480-d1bd8580-96bf-11ea-820a-12b8a3360572.png)

**Comment by davidg-sil** [comment]
Interesting. Can I suggest an alternate name, rather than overloading the
current one, e.g. relfontsize?
If someone has set their fontsizeunit to 1cm,  then the <2 test would
suddenly break their layout in mysterious ways!


On Fri, 15 May 2020, 12:52 Mark Penny, <notifications@github.com>

**Comment by davidc86** [comment]
I did wonder about that, because  I have
\fontsize 10
And
\fontsize 9
Etc.
And now I have a
\fontsize .95

Just wondering if adding an \relfontsize as suggested might be safer.
David

**Comment by mhosken** [comment]
I'm open to that. We just need to think it through. I vote for \FontScale. Feel free to code it up :)

**Comment by markpenny** [comment]
\FontScale sounds good to me. @davidg-sil - are you able to code it that way (and drop MH's <2pt FontSize temporary solution?)

**Comment by davidc86** [comment]
\FontScale is fine. Even easier to remember.
Now I just wish we had a cheatsheet for Paratext styles that listed the various variables and their values. Do you know of one?

**Comment by davidg-sil** [comment]
FontScale is now implemented, but it missed the point release tonight.

There's a cheatsheet taking shape on github in the documentation directory.
I can't remember if it's in the FAQ or elsewhere and it's midnight-30 here,
so I'm not going to check, sorry.

**Comment by mhosken** [comment]
Fixed (see docs/documentations/ptx2pdf-faq.md)
