### ISSUE TITLE
esb cat ignoring style parameters

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#523]
Style parameters seem to be ignored in the **cat:boxed|esb** style as shown in the image below. For example, the line-spacing is ignoring the 0.74 value and forcing the text onto the grid behind/below the box of text. Similarly with the justification setting, and left/right indents - everything is being ignored. Maybe we have misunderstood something and we have to set up a different style to control these; if so please advise. And a minor point, the box itself isn't completely centered horizontally - going just outside the right margin. Other than that, I was pleased that MH managed to pull this off using **cat**egories and and the **esb** funtionality..
![2021-09-18 16_25_50-](https://user-images.githubusercontent.com/12962708/133946423-5c2024eb-5af4-4cd5-97b3-d8e8ea0b8e7b.png)
.

**Comment by davidg-sil** [comment]
`cat:boxed|esb` ought to be styling of the side bar itself, not the contents. To style a `\p` for instance, it is:
```
\Marker cat:boxed|p
```
But yes, I agree, there's been a regression and paragraph styling isn't applying properly, only character styling.

**Comment by mhosken** [comment]
The USFM being used is of the form:
```
\esb \cat boxed\cat* Permission requests: The text ...\esbe
```
It probably should be:
```
\esb \cat boxed\cat* \p Permission requests: The text ...\esbe
```
Which would then be styled as mentioned above with `cat:boxed|p`. Or else how about just using `\ipq` instead of `\p`?

This seems to work pretty well:

In the front matter:
```
\esb \cat boxed\cat* \ipq Permission requests: The text ...\esbe
```
In ptxprint-mods.tex
```
\Marker cat:boxed|esb\relax
\Position p\relax
\Border All\relax
```
In the styles:
- set \ipq First line indent to 0
- create a new style cat:boxed|esb (perhaps based on cat)

**Comment by davidg-sil** [comment]
For styling the box, I'd recommend styling added to custom.sty rather than trying to do stuff in the .tex file. Sticking `\relax` after will only work for things not including digits.

There ought to be an implicit `\p` at the start of the side bar, IIRC.

**Comment by davidg-sil** [comment]
Correction: There is no implicit `\p` (trying to put one in causes an strange error elsewhere), and, furthermore, if no paragraph style is given, then no paragraph styling occurs (it's left - mostly - at what it was before the `\esb`), even if paragraph style parameters are given. The `\cat` or `\esb` itself should not be expected to apply paragraph styling.
