### ISSUE TITLE
Add finishing tab

### ISSUE THREAD

**Issue by mhosken** [sillsdev/ptx2pdf#524]
There are a few post print 'finishing' type things that it might be worth providing support for:

- booklet and booklet type signature production

I realise that this could be quite a rabbit hole. We aren't trying to reproduce Adobe preflight here.

**Comment by davidg-sil** [comment]
Other things to possibly include...
* Estimation of spine thickness from number of pages / binding type / paper thickness.
* Pasting together of cover and spine
* For the inside cover, ISBN barcode generation (the TeX code exists...)
* Alternate layouts to 'optimise' signature / flyleaf use.
