### ISSUE TITLE
Can't get pictures to show up

### ISSUE THREAD

**Issue by mgbethiopia** [sillsdev/ptx2pdf#526]
Hello,
     This is my first time to use PTXprint and I can't get pictures (figures) to show up.  I have assigned the folder for it to go to, I have the full range of types of pictures/illustrations, I have clicked "Include Pictures", etc.  So, which of the many choices of boxes have I clicked/not clicked? I'm sure there is an easy solution....I just don't know which one.

Thanks,
Mike Bryant

**Comment by markpenny** [comment]
Hi Mike, Sorry that this hasn't been as predictable, or straightforward as we would have liked it to be. We're trying to work out what is causing it to fail for some people, but not others. Could you confirm whether you saw a dialog like this one, when you first turned on the "Include Pictures" option, and if so, if you clicked OK to generate a "PicList" of images?
![image](https://user-images.githubusercontent.com/12962708/135026642-80836b43-4f0c-405b-9d19-ab569025ae5d.png)

If so, you should be seeing a list of images in that top pane like this:
![image](https://user-images.githubusercontent.com/12962708/135026707-3b990748-c9bc-46e3-8e58-e885237a7f24.png)

Notice that if your top pane is empty, you can click on the Generate... button (top right) to create a list of images to be included.

[If you don't see any top pane at all, then perhaps you need to click the "v Show More" button (bottom left) to show more settings etc.

Do you see the previews of images in the box on the right? If so, you know that PTXprint has found them and *should* be able to use them.

Hope these hints are enough to get you moving again... If not, come back with some more information. Thanks. Mark

**Comment by mgbethiopia** [comment]
Mark,

    No, I didn’t see that box.  Now I licked on the “Generate” button and I have the pictures now.  

 

Thanks,

Mike
