### ISSUE TITLE
Separate settings for fn and xr positioning and rules

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#527]
We need to be able to specify the settings independently for footnotes and cross-references. The UI has been split up to handle these separately.
![image](https://user-images.githubusercontent.com/12962708/135027377-fad64c36-ab99-44cf-a6db-a4734a132ae5.png)

**Comment by mhosken** [comment]
This is implemented. The most significant change is that `\AboveNoteSpace` has been regularised to `AboveFootNoteSpace` (to harmonise with \AboveEndNoteSpace). This could break existing projects, although TeX will shout at them when it does, so it'll be obvious.

**Comment by davidc86** [comment]
I'm not seeing this in my copy of v1.9.5

**Comment by markpenny** [comment]
Sorry @davidc86 that is just my screenshot of what we're still developing. It will be released in 1.9.6 as soon as we can iron out all the new bugs we've made in the mean time.

**Comment by davidc86** [comment]
Okay, cool. Just in the screen shot it says v1.9.5 so I thought I had somehow gotten a wimpy version :).
