### ISSUE TITLE
Footnotes won't Left Align in v2.0.4

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#529]
I wanted to test how it would look if the footnotes were Left Aligned (while the Scripture text is justified), so I set the \f style to Left aligned. But I still get this: 

![image](https://user-images.githubusercontent.com/65363206/135142335-b1426053-a8de-4b2b-bdc6-20b03adef19f.png)

I already have started using the Left align setting on \x cross-references and it works, and it looks neater (no large gaps) too. 

So, PTXprint does it for xrefs, just not footnotes.

**Comment by davidg-sil** [comment]
Given that the code for xrefs and footnotes is the same, I'd assume there's some other factor happening. E.g. xrefs are merged into one paragraph, and notes aren't. It would help us bug-hunt if you could find the setting that causes what you're seeing. There are lots of issues with footnotes in the github code at the moment, as trying to fix one thing seems to have broken lots of others.

**Comment by davidc86** [comment]
It may be some other setting is glitching this, but setting the \f style to LEFT Align does not cause it to left align for us.

But an odd thing I'm seeing is that if I set \f (the MAIN footnote control style) to LEFT:

![image](https://user-images.githubusercontent.com/65363206/138198548-96e9cba6-c2a6-4473-a0da-94bffee2c819.png)

And then I open up a CHARACTER style, like \fq (for quoted text):

![image](https://user-images.githubusercontent.com/65363206/138198645-03adf8c4-dcbd-49f4-a40d-fb1df6d26113.png)

I notice that there is a Paragraph Settings... option (!) Weird for a character style, since they should NOT have paragraph specifications at all, so I open it and presto: 

![image](https://user-images.githubusercontent.com/65363206/138198761-dc409831-f6cd-4b2a-aab5-3e47e3d12164.png)

It says JUSTIFIED!! 
When what it should have is NOTHING in this part, in fact this part should be grayed out right? I understood character styles to have no paragraph attributes and any text they mark inherits the paragraph attributes from the surrounding paragraph. Does PTXprint not work this way? Is it designed differently that this?

I'm thinking this is just a bug, and all the paragraph junk should be turned off in all of these styles.

Is it possible this is causing the bug? Like if a footnote never used a character style it might success in LEFT aligning, but if a character style is embedded inside, its paragraph attributes are overwriting the \f paragraph attributes? Just guessing here.

**Comment by mhosken** [comment]
You can have ragged notes. There is a control for the amount of rag you want in your notes. The default is `\noteRag=0pt plus 36pt` but you could do something like:
```
\noteRag=0pt plus 1fil
```
If you want all the excess space on the line to be soaked up by the right hand rag.

Notice that ragged notes don't work for separate notes (one note per paragraph) until the release after 2.0.4.
