### ISSUE TITLE
Oddball spacing on Section Headings in v1.9.5

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#530]
I'm seeing oddball spacing on Section Headings in v1.9.5: 

![image](https://user-images.githubusercontent.com/65363206/135145711-fe426459-6617-47d5-bef5-87770a2b0ff0.png)

I've been playing with the "before" and "after" values, and currently it is set at "Before = 0.2" and "After = 0.0":

![image](https://user-images.githubusercontent.com/65363206/135147297-6c60daf1-625b-414a-b844-62d214714486.png)

But if you ask me, that doesn't look anything like what I'm seeing in the printout. To me, it looks much more like NEG 0.2% space before and PLUS 0.2% space after. Right? 

I suspect this might be PTXprint trying to keep the Section Heading area constrained to be instep with the grid of the rest of Scripture text (i.e. subsequent scripture lines still occupy the same grid as the scripture on other pages). Am I right?

But this is confusing to me (and I suspect most users). While I appreciate PTXprint's effort to maintain the grid, I wish there was some way to have better control of this. 

What I'm wanting is some way to bracket the section headings so there is a somewhat wider gap before and a somewhat smaller gap after, but in the end the scripture text stays on the grid, just the section headings wiggle about a bit off the grid.

**Comment by markpenny** [comment]
@davidc86 When you download and run 1.9.6.2 it will turn OFF compatibility settings (and tell you about it in a one-off message). This is quite likely to fix the strange behavior you are seeing. If not, then please send an archive.

**Comment by davidc86** [comment]
I'm not seeing strange behavior now.
