### ISSUE TITLE
PTXPrint complains of mysterious error when text passes basic checks for markers.

### ISSUE THREAD

**Issue by sewhite** [sillsdev/ptx2pdf#536]
Attempting to print Mark produces this "failed to canonicalise texts " error. (But it does go on to make a PDF). 

![image](https://user-images.githubusercontent.com/16904461/136274213-70ff494b-b365-4bb5-9213-b7cb13814868.png)
The project passes Paratext basic checks without a problem. I do not see a PrintDraftChanges.txt file in the project folder.

[GSP-DefaultPTXprintArchive.zip](https://github.com/sillsdev/ptx2pdf/files/7296800/GSP-DefaultPTXprintArchive.zip)

**Comment by sewhite** [comment]
I like "Syntax error warning" instead of "Failed to canonicalise text". I think many users will not know what "canonicalise" means, some will think it refers to something about their project canon, and some might even think PTXPrint has issues with Deuterocanonical books. I also like the line number being clearer in the first message.

**Comment by markpenny** [comment]
@sewhite For GSP it found a few more issues in 17, 583, 993 and 1088 but here are some rules that I stuck into PrintDraftChanges.txt (accessible from the Advanced tab) which fixed those:
```
"(\\x .+?\\x\*) ?(\\qt\*)" > "\2 \1"  # Move closing \qt* before the \x ... \x*
"(\\qt )(<)?(\\x .+?\\x\*)" > "\3 \1\2" # Move the opening \qt until after the \x ... \x*

"\\x\* ;\\qt\*>" > "\\x* ;>"
```
Once those were taken care of it quite happily made the diglot PDF. However, I'm aware that the current version which is out there (1.9.5) has an issue with diglots duplicating a chunk of text at each chapter. We're hoping to have 1.9.6 out today which will fix that
[ptxprint-Default-MRKGSP.pdf](https://github.com/sillsdev/ptx2pdf/files/7306634/ptxprint-Default-MRKGSP.pdf)
.
