### ISSUE TITLE
Can't put two pictures on one verse

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#54]
In Gen. 4:21 (showing a pan pipe and a harp) and also in James when giving examples of two kinds of trees, it would be nice to show two pictures side-by-side or one on top the other. But it appears to cause PTXprint to not show the second picture, and to cause all the rest of the pictures in the Pic List for that book to be ignored/skipped.  (Set to single column.)
HACK: keep the verse ref in the caption correct, but change the verse ref in the Pic List to the next verse.

**Comment by mhosken** [comment]
Yup. You can't put two pictures in one verse reliably. Your hack seems a reasonable workaround.

**Comment by davidc86** [comment]
I suggest this be moved to an FAQ -- How to hack two pictures so they look like they are attached to the same verse.

**Comment by mhosken** [comment]
Notes have been added to the FAQ
