### ISSUE TITLE
Handle deadcycles limit better

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#548]
TeX has a limit of how many times it's happy to go in circles before it gets bored. Sometimes (e.g. with big images anchored to the wrong place) we hit that limit. Options include:
1. increase `\maxdeadcycles` even more 
2. Tell TeX to struggle on after errors with `\nonstopmode`

In either case, the output will probably be nasty from  that point, so these should probably be handled in some kind of extra-information mode, with user instructions saying something like: 'Things seemed to be progressing reasonably  until page 15, have a careful look in the three or 4 pages after there to see if you can work out what's going wrong'

**Comment by mhosken** [comment]
Increased maxdeadcycles to 100.
