### ISSUE TITLE
Exclude ref seems incomplete

### ISSUE THREAD

**Issue by philleckrone** [sillsdev/ptx2pdf#55]
I have a project that uses the entire reference (Ro. 1:7,15) for the caption. This information is also found in the ref field of the figure. When the PDF is created I get:

(Ro. 1:7,15) (Ro. 1:7,15)

If I exclude the ref I get:

(Ro. ) (Ro. 1:7,15)

My desired result (which I get with PA) is to remove the second reference and just leave:

(Ro. 1:7,15)

I recognize that the option specifically mentions (ch:v), but it would be nice if it removed whatever was  in the ref field and not the first ch:v that occurs in the caption.

![Picture without reference included](https://user-images.githubusercontent.com/37958474/81998111-a8e5b380-961f-11ea-9906-96382ddb0924.png)
![Picture with reference included](https://user-images.githubusercontent.com/37958474/81998121-b00cc180-961f-11ea-91a5-94f69546a8ae.png)

**Comment by markpenny** [comment]
This seems like a dirty-data issue to me, and the translation team really needs to improve their way of putting captions on illustrations. Nevertheless, it highlights a problem in the code, and so I've put in a fix to ONLY look in the **caption** part of the \fig ... \fig* so that we don't accidentally touch the actual caption text (or filename ref) in any way.
The fix should be available in a few hours - in version 0.6.2

**Comment by markpenny** [comment]
First with the verse refs included (and spurious refs within the caption TEXT itself):
![image](https://user-images.githubusercontent.com/12962708/82022454-58fffe80-96aa-11ea-8850-b15ff47ee95e.png)
Then with "Omit Refs from caption (ch:vs)" enabled:
![image](https://user-images.githubusercontent.com/12962708/82022474-5e5d4900-96aa-11ea-88ba-51171ffb93d9.png)

**Comment by philleckrone** [comment]
Mark,

Thanks! you are correct that that particular example is "dirty", but a more
realistic format that is used would be something like this:

Caption: Mary and Joseph with baby Jesus (Matthew 1:20)
Ref: Mt. 1:20

Since Paratext checks the "ref" field for accuracy it needs to be the
abbreviation, but the team wants the full name in the caption. This is one
way to accomplish this. Often you don't need the book name in the ref
field, but I usually have the translators fill out a spreadsheet with the
data (including the book name) so that I can quickly add the correctly
formatted figures to the text.

Blessings,
Phil Leckrone
Americas Area Language Technology Coordinator
language_software_amareasil@sil.org
704-843-6064 (Office at JAARS)
704-213-2604 (Cell)
Skype name: phil_leckrone
