### ISSUE TITLE
Can we get rid of the spaces in the caller area of the footnotes?

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#557]
Here is a typical footnote:

\f + \fr 4:9 \ft Tunke khatu kibohe, \fq yatke kralake\fq* neke ti tel mabuske desikeo kbyohe, \fqa dalam perang\fqa*.\f*

It comes out like this (ignore here the space before the fullstop): 

![image](https://user-images.githubusercontent.com/65363206/138197776-b9a421ef-6313-4692-90ab-a87d5176c0a0.png)

It would look cleaner if we could remove the spacing between the * and the 4:9, but I don't see how to do this. Is it possible?

**Comment by mhosken** [comment]
It's currently fixed. Let's change that. After the next release after 2.0.2, you will be able to set `\NoteCallerSpace` in your ptxprint-mods.tex. So for example, to make no change you can set it to its current default:
```
\NoteCallerSpace=0.2em
```
or to whatever you want it to be.
