### ISSUE TITLE
Bug in ToC when two \toc1 markers occur on a single page

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#569]
I've created a Bible Module which uses \toc1 markers to create a ToC page where each section heading occurs.

In a number of cases, two section headings (and thus two \toc1 markers) occur on the same printed page in the pdf. When this happen, the ToC lists the wording from the 2nd \s (i.e. \toc1) marker in both cases.

![image](https://user-images.githubusercontent.com/30174022/139205264-f41af6b3-8f6d-4c15-b24f-2d4453b28d8d.png)

**Comment by mnjames** [comment]
I sent an archive directly by email a few days ago. Did it arrive?

**Comment by markpenny** [comment]
@mnjames Just letting you know that I haven't recd anything via the ptxprint_support @ sil.org address. But hopefully you sent it directly to @mhosken's e-mail instead.

**Comment by mnjames** [comment]
I had sent it directly to @mhosken's email because I couldn't remember the support address. I've now sent it to that one also.

**Comment by mhosken** [comment]
Thanks for the ping. Found the archive. The problem was that where there were multiple toc entries on a single page, the text output for each one was that for the last one on the page. This is fixed now.

**Comment by mnjames** [comment]
Thank you. I can verify that this is now fixed (I copied the change into my ptx-toc.tex macro to test it).
