### ISSUE TITLE
milestones and paragraph styles

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#570]
It should be able to style the paragraph parameters via a milestone, as well as character styles. For some reason this isn't currently working.

**Comment by mhosken** [comment]
Yes, but I don't think we need to worry too much. If people want to do paragraph level styling with milestones, then they should be using sample B. I think anyone using samples A and C to do paragraph level styling should not be doing that. Remember paragraph styles don't nest like character styles. So I think we can just go our merry way and ignore the issue, although this issue is a good piece of documentation to have when people do things that don't fit their expectations.

**Comment by davidg-sil** [comment]
The issue (which I've confirmed is real)  is that sample A does no paragraph-level styling, just the relevant character styling within the milestone-defined chunk of text. The user will  be expecting  paragraph (and character) styling with sample B but (unless they read this!) just character styling in sample C too. But that is not what will occur. There is thus the 'opportunity' for unexpected and confusing  side-effects. 

Sample D:
```
\p
\v 12 \qt-s|Jacob\*  ...  \qt-e\*
```
Will only apply character-styling, since the verse is started by the verse number but if someone thinks that they can do paragraph formatting for a certain piece of text with the same milestone because 'they only wrap it around a paragraph in this place`, there will be unexpected results.

Testing that the above is correct also shows another problem, that formatting for the unattributed milestone, i.e: 
```
\Marker qt-s
\Color ...
```
Is applied in samples with the placement as A and  D (as it should be) but not in samples B and C,  In Sample D, the `\v` applies the colour, but the main paragraph text is not coloured.  In samples B and C, the font seems to be set up, in (very) quick succession, and correct styling is applied the 1st time but not the second. More investigation is needed.

**Comment by davidg-sil** [comment]
Applying alternative styling to a *particular* paragraph-style based on a milestone with a special format for the `\Marker` line is possible, and if there is someone with a real need, I can make that change.  There are related issues that make me suspect that that change will  (a) be fragile and (b) need to change in the future (c) be confusing and (d) adversely impact the speed of processing for all users (no idea how much). Thus I am reluctant to make the identified changes until the other issues are resolved.

**Comment by mhosken** [comment]
Let's not do this. Paragraph categories should meet the need for now. I suggest we make this an enhancement and push it off, rather than a bug.

**Comment by davidg-sil** [comment]
Just for the record, categories on paragraphs meet one class of need, (styling a particular paragraph), milestones and paragraph styling meet another (styling a delimited range).  This issue exists because the current mechanism for applying them is appears a bit broken and while characters styles get applied, paragraph styles are not. 
As the *underlying* mechanism is significantly broken, we can hope that fixing that underlying bug will fix this.

**Comment by davidg-sil** [comment]
Reassess after #576 is fixed

**Comment by davidg-sil** [comment]
If anyone wants the confusing (but TeX-like) behaviour from sample C, then `\DefineParBeforeMilestonefalse` Otherwise fixing #576 seems to have solved this.
