### ISSUE TITLE
Module behavior differs between Paratext and PTXprint

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#571]
I've finally understood what ChrDr is complaining about regarding the way PTXprint handles modules. She points out that when you print an XX[A-G] book from Paratext which contains a module, it works fine (and as expected). But her complaint is that if you use the PTXprint's module option on the _same_ module, you get a different result:
![image](https://user-images.githubusercontent.com/12962708/139343933-b5657835-cd85-40fc-aa42-e04b6630e318.png)
The reason is that PTXprint includes things (by default) that Paratext leaves out (by default).

So in this example, ptxprint includes BOTH the original \s section heading AND the replacement \s section heading specific in the module:
![image](https://user-images.githubusercontent.com/12962708/139344410-18b25b1a-8ae1-4ed7-977d-b7b14d72f0e0.png)

If they both handle things the same way*, users would be less confused.

**Comment by mhosken** [comment]
Aaah. Yes we initialise with an empty remove list, we should initialise with a full remove list. No need to mess with UI.
