### ISSUE TITLE
picture associated with poetry won't output

### ISSUE THREAD

**Issue by viverechristus** [sillsdev/ptx2pdf#573]
Genesis 49:2-27 is continuous poetry (in our translation), with each line beginning with \q1 or \q2 and sections separated with \b. There are no \p breaks.

I've tried to include a picture associated with v.22, and it simply doesn't show up in the output -- no box, no empty space, no caption, nothing. Before v.22 is a \b, but not after. So I tried associating the picture with v.21, which has \b before and after. Still no go. 

However, if I associate the image with verse 28 (back to prose, begins with \p) it shows up -- but that puts the image at some distance from v.22.

Here's an archive of the configuration:

[JraKhmr-DefaultPTXprintArchive.zip](https://github.com/sillsdev/ptx2pdf/files/7438874/JraKhmr-DefaultPTXprintArchive.zip)

**Comment by markpenny** [comment]
@viverechristus Could you check and confirm if this one has indeed been fixed for you. Feel free to close this issue if it has, or get back to us if you're not seeing the result you're anticipating. Thanks.

**Comment by viverechristus** [comment]
Works beautifully. Thanks!
