### ISSUE TITLE
Underline on \nd style

### ISSUE THREAD

**Issue by KapalaKamale** [sillsdev/ptx2pdf#574]
We use the \nd ...\nd* character style (Name of Deity) for the name of God in Old testament translation. The problem is that \nd appears underlined in the PTXprint output. I cannot figure out how to remove this underline. We use a custom.sty in the project (TUKIR) to specify that \nd is formatted Bold with no underline. In Paratext \nd appears Bold with no underline after setting these options in the custom.sty. For some reason Paratext's default stylesheet usfm.sty does call for underline for \nd. To test things out I have even removed this underline formatting for \nd in the usfm.sty (although one is not supposed to modify the usfm.sty). The underline option is not ticked in the PTXprint Styles tab for \nd. In fact, it is grayed out.

Where does PTXprint get it's style information from anyway? \nd was not formatted Bold in the output until I checked the Bold box in the styles tab for \nd. It is now formatted (correctly) Bold and (incorrectly) underlined.

Thanks for looking into this

[TUKIR-ABSPTXprintArchive.zip](https://github.com/sillsdev/ptx2pdf/files/7455872/TUKIR-ABSPTXprintArchive.zip)

**Comment by markpenny** [comment]
Yes, it must be turned on somewhere, and we don't currently offer a place to turn it off in the UI. So here's how you can solve it: 
a) Close PTXprint
b) Navigate to the **C:\My Paratext 9 Projects\TUKIR\shared\ptxprint\ABS** folder and open **ptxprint.sty** in an editor like Notepad or Notepad++.
c) Find where it defines any additions/subtractions to **\Marker nd**
d) Add the line shown here with a - (minus) to tell it to turn OFF underlining
e) Save, and re-open PTXprint and check that the issue has been resolved.
![image](https://user-images.githubusercontent.com/12962708/139746041-238ea36b-d407-4781-9778-4e1cd8b3f730.png)

**Comment by mhosken** [comment]
FYI. The underlining of \nd is part of the default system stylesheet that comes from Paratext (usfm.sty). Also, if your custom.sty fixes everything up, that's great, but you haven't turned it on in your project, so ptxprint isn't using it. Go to advanced and enable custom stylesheet.

**Comment by mnjames** [comment]
It seems like @KapalaKamale was a bit confused by the stylesheet hierarchy, so here's my attempt at explaining it. There are multiple levels, and each lower level overrides the settings in the levels above it.
1) usfm.sty: As you noted in the OP, you shouldn't ever edit this file. You "edit" it by changing the files lower down this list.
2) custom.sty: This is primarily for customizing the way things look inside of PT. As with #‏4, this can be turned on or off in the Advanced tab.
3) ptxprint.sty: This is where ptxprint saves its settings when you edit them within the UI
4) ptxprint-mods.sty: This has to be turned on in the Advanced tab, but it allows you to define your own values outside of the UI.

However, if my understand is correct, then I'm a little confused why @markpenny recommended editing the ptxprint.sty sheet rather than turning on the ptxprint-mods.sty sheet and editing it.

**Comment by markpenny** [comment]
Good point, @mnjames! I stand corrected by both you as well as @mhosken.
Perhaps I should withdraw/delete my workable, but not ideal solution.
So @KapalaKamale, either do what @mhosken suggested above, or add these lines to your ptxprint-mods.sty file and ensure that it is enabled:

```
\Marker nd
\Underline -
```

**Comment by KapalaKamale** [comment]
Thank you everybody. Problem solved. It was as simple as turning on the custom.sty in the Advanced tab. All this was a big learning experience. Now the Advanced and View+Edit tabs make sense. Somehow before they did not. Also a big thank you to @mnjames for explaining the stylesheet hierarchy. That was also something that I did not know and understand.

**Comment by mhosken** [comment]
Just for completeness, there is a 1.5 which is:

1.5. ptx2pdf.sty - this is a system stylesheet like usfm_sb.sty (no. 1), but is controlled by the ptxprint project team and adapted to add extra markers, fix up hierarchies and generally make usfm_sb.sty wonderful. You cannot edit this, but you can make application for changes that will affect everyone.

**Comment by markpenny** [comment]
@mhosken I think that (by default) we should get ptx2pdf.sty to turn OFF underlining for the \nd ... \nd* style. As that is what most people would expect to see in their output, without having to turn ON a different stylesheet (custom.sty) just to turn it OFF!

**Comment by mhosken** [comment]
Sure. Make it so!

**Comment by markpenny** [comment]
Done - for 2.0.29 and beyond: \nd and \pn have \Underline turned off.
