### ISSUE TITLE
Add \cat support to paragraphs with font feature merging and adjlists

### ISSUE THREAD

**Issue by mhosken** [sillsdev/ptx2pdf#575]
In addition to being able to perhaps change the number of lines in a paragraph, it is helpful for a typesetter to be able to use the `extend` font feature of a font (which is applied by XeTeX and is not an OT feature), to slightly adjust the width of text and so lines. The compression and stretch is small enough that people do not notice (1-3%). One approach to this is to use different paragraph markers, e.g. `\p_105`. But then one gets into hierarchy problems, since p_105 doesn't appear in OccursUnder lists where p does. In addition, every paragraph style needs its requisite variants and this leads to a big stylesheet.

An alternative mechanism is to extend `\cat` to working within paragraphs and not just extended notes and sidebars. If we could say that the \cat adds a font feature to all fonts within it (or within the paragraph that has the \cat) then the typesetter could insert \cat s105\cat* or whatever name we come up with, to expand or compress the text in a paragraph. It is probable that the same mechanism used to merge features across a marker hierarchy would give the same feature to character styles as well.

To make this work we will need to do the following:

- add \cat support to paragraphs
- add fontfeature merging through the marker hiearchy (a special \getpar@m for that)
- Add a bunch of standard typesetting categories to ptx2pdf.sty.
- Add UI for editing categories apart from categoried markers.
- Add UI for setting just font features for character styles and also categories.

**Comment by davidg-sil** [comment]
Let me get this straight... You want to specify somehting which has an effect on a font feature and is cleared by the end of paragraph. I'm probably not thinking straight, but Isn't this just an (underspecified) character style?

Alternatively, if you're willing to add an end-maker, it seems like a thing that milestones ought to be able to do, possibly with a parameter:
```
\extended-s|105\*
\p text
\extended-e\* 
```

**Comment by davidg-sil** [comment]
`\cat` can now be applied to a paragraph. It is *NOT* a character style. 
```
\esb \cat uncertain\cat*
\s The woman caught all alone in adultery 
\p 
\v 53 Then they went home,
\esbe
```
and
```
\s \cat uncertain\cat* The woman caught all alone in adultery
\p \cat uncertain\cat*
\v 53 Then they went home,
```
Will be formatted the same (Ignoring any styling from the side-bar i.e. if the sidebar has no background, no image, is inline, etc), unless there is over-ridingg formatting for the complex item: `cat:uncertain|p+cat:uncertain+esb`

The relevant stylesheet entry might be:
```
\Marker cat:uncertain:p
```
to style just the `\p`  or:
```
\Marker cat:uncertain:*
```
To style all paragraph styled.

**Comment by davidg-sil** [comment]
With the above mechanism, there should not be a separate category item in the style sheet editor. The thought of trying to merge font features sounds tricky, and there will also need to be a method / decision on what \Regular  does: does that reset font features like it resets bold/italic, or is there a need to somehow undo a potential large set of items?
Another question is are font features assumed to carry over a font change?  That seems dangerous.

**Comment by davidg-sil** [comment]
An idea for controlling cascading font-features:
```
\FontFeatures +[tag1=value,tag2=value,+smcp]
\FontFeatures -[tag2,tag1] +[tag3]
\FontFeatures =[tag=value,tag2=value]
```
Line one would add the different `tag=value` and boolean items to the list
Line two would  search the current tags to build a new tags list without tags 2 or 1, and add tag 3
Line three would set the current tags to exactly the list specified.

Coping with line 2 in TeX might look something like:
```
\def\parseFontFeatures #1[#2]#3\E{.... \edef\tst{#3}\ifx\#3\empty\else\parseFontFeatures#3\E\fi}
```
