### ISSUE TITLE
Processing stacked styles is not working properly

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#576]
I'm not aware of many erroneous results from the current code, but looking at log files (with the right tracing modes) shows that it's buggy, wasting both CPU cycles and memory. It should therefore be fixed.

**Comment by davidg-sil** [comment]
(put here from other document, with further thoughts, so it doesn't get lost).
# More on the bug
There are 2 ‘stacks’ in use by the code at the moment: 
1. the (actual) `mcstack`, which lists all currently in-force markers, their class (P=paragraph, etc), and (in the case of milestones) their significant parameters.
2. `styst@ck` which lists the styles which might have an effect on the style of a font / paragraph.
styst@ck is thus derived from `mcstack`, but is a truncated and simplified list.

`styst@ck` is used:
1. When checking to see if the user has defined any complex styles, `s@tpossParams` builds a (comma  separated) option-list that might exist and then reduces that list to the things that actually have some  parameter defined. E.g. if the usfm is:
`\p <<\qt-s|Jesus\* You shall not put the \nd Lord\nd* to the test\qt-e\*>>`
Then the `nd` will have a `styst@ck` of `nd+Jesus|qt-s+p`, and the code will check to see if there has been any definitions of:
```
\Marker nd+Jesus|qt-s+p
\Marker nd+Jesus|qt-s
\Marker nd
```
2. When caching font definitions (e.g. `font<p-12>` is "Zapf Chancery" at 9pt)  and the above option-lists, they are remembered using styst@ck and currently in force \cats, not the full mcstack (as e.g. the style of a footnote shouldn’t have any dependency on what paragraph style it was called from).

## The problem (s):
1. `getmcp@ram` (and `getmcp@ramR`) currently traverse the full `mcstack` to obtain the relevant ‘built-up’ font parameters, but at present, `styst@ck` is not re-created during their stack traversal operations. 
This gives false cache misses, needless (stupid) checks for complex styles, wastes RAM because it’s caching rubbish,  and slows things down, especially in interlinear text or text with lots of e.g. strong’s numbers).
Recreation of `styst@ck` during stack traversal would probably be an O(n^2) operation, so would be more wasted CPU cycles. Also, as it depends on the portions of the stack below the current values, it’s not clear to me *how* this should happen.

2. At present, with this stack-based naming (and caching) of generated fonts, there is **no list** of what has been made. If a new style sheet is loaded or a style-related parameter is changed, there’s no way for the code to realise that it needs to regenerate, say,  `font<nd+p>` to account for a new font choice for the glossary, and the code will use the old definition.

## Possible Solutions to problem 1.
1.  Alter the definition of `mcstack`, so that as well as class+marker, the `styst@ck` is stored with each mcstack entry. This makes stack traversal easy.
2. Alter s@tpossParams to (optionally) check lower layers of the stack too. I.e. make it tell getp@ram to check:
```
\Marker nd+Jesus|qt-s+p
\Marker nd+Jesus|qt-s
\Marker nd
\Marker Jesus|qt-s+p
\Marker Jesus|qt-s
\Marker p
```
3.  getmcp@ram shouldn't use mcstack anyay, but ought to traverse using styst@ck

Idea 1 is orthogonal to 2 and 3, and should probably be tacked first. It is made a bit complex by milestone entries which can contain user-supplied content, potentially including `+`, `"` and other odd characters.

If 2 is chosen, then 3 becomes needless. 2 probably has greater efficiency gains, 3 may be simpler to implement. For either, implementing idea 1 simplifies things a lot.

Related thought 1: there are places that e.g. `setfont{h}`  is called, which shouldn’t use any kind of stack traversal, as we’re looking for an ‘absolute’ font. This could be solved e.g. by passing setfont `styst@ck` as a second parameter when there’s traversal to be done.

Related thought 2:  even with `s@tpossParams` using cache lookup, it’s a waste to call it X  times per font. It ought to make more sense to call it once as a preparatory step and then save/restore it if we need something special.

## Possible solutions to problem 2:
1. List the fonts created, and destroy them  when a new style sheet is created.
2. Do something complicated with versioning... 
  a)  `font<nd+p>` has `fontversion<nd+p>` of 2 because it uses elements nd and p, which were tweaked in stylesheet 2.
    p was updated in stylesheet 3, so the font needs recreating, but `font<nd+s>` does not. 
This is undoubtedly too complex to manage for the cost-savings.
  b) `font<nd+p>` has `fontversion<nd+p>` of 2, because it was created after stylesheet 2 was loaded. Now stylesheet 3 is in use, so the font needs recreating. **Advantage** over (1) no need to maintain and traverse a long an complex list which (thanks to milestones) may have unexpected characters in it. **Disadvantage**: every font-use needs to check the version number.

**Comment by davidg-sil** [comment]
Regarding the possible unexpected characters from Milestones (e.g. `\ts-s| Mary, Mungo + Midge`)  I propose that (similar to stripping spaces from key terms), '+' ',' and '|' (and any other 'significant' characters) be counted as 'reserved characters', and that they be stripped from milestone identifiers in the `mcstack` (and `styts@k`).
This will make traversing / parsing the style stack **much** simpler. It will also mean that these reserved characters should not **occur** in the stylesheet as part of any milestone definition, (but of course + would have its stacking function). The above example would be, then styled as `\Marker MaryMungoMidge|ts-s`

**Comment by davidg-sil** [comment]
I forgot to write (regarding problem 2 above) that the link to this bug is that both struggle with the traversal of strings that are partially derived from user input. The reserved character removal above goes a long way to simplifying both.

**Comment by mhosken** [comment]
Pipe is now a reserved character and any occurrences in main text are
turned into \pipe.
