### ISSUE TITLE
Reverse Digit Mapping

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#579]
I think this is a feature request, but it also may be a case of me simply not knowing the correct way of doing things.

Under the font dialogue in the Digit Mapping section, I think the assumption is that you're mapping _from_ Latin numbers _to_ other number systems. It would be nice if that map could also be used backward; so if a project used local numbers (in our case Indic-Arabic), that we could print using Latin numbers.

Of course this can be done with the printdraftchanges.txt file, but it would be nicer if it were simply built in.

**Comment by davidg-sil** [comment]
The text has `\v` entries in Arabic script? What does Paratext think of *that*? Or do you by some chance use 
`\v 1 \vp [arabic]\vp*`? If so, then making \vp non-publishable might be something to try. I've not tried.

**Comment by mnjames** [comment]
It's not the verse numbering, it's other numbers within the body of the text.

**Comment by mhosken** [comment]
We suggest using PrintDraftChanges.txt for this. The mapping is done at the font level. You could try to introduce a new mapping that reverses Arabic -> Latin digits. But ptxprint has no mechanism for specifying a mapping outside of the set included as part of ptxprint.

**Comment by mnjames** [comment]
Okay. The PrintDraftChanges.txt rules certainly work, I was just hoping to avoid that route because I don't want to apply this Arabic-->Latin change in all of my different print configs.

However, #587 would solve that problem, at which point using PrintDraftChanges.txt (or the new, config-specific version) would be sufficient.
