### ISSUE TITLE
Generating a PicList should not overwrite other edited PicList files 

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#58]
We are working a combined set of (published) books. And we have modified several of the Pic List files associated with many of the books. But if we need to regenerate ONE PicList (for testing after modifying the source text), how do we do this without overwriting all the other Pic List files?

It would help if the Generate button only regenerated the current book's Pic List, and not all of them. Or better allow the option of "Generate the Pic List for THIS book" / "Generate Pic Lists for all the book in this configuration" 

Current behavior is, if I click Generate, PTXprint warns that Pic Lists already exist for these books (and gives a list). So I Cancel it in order to not ease all the tweaks I've put into those Pic Lists.

**Comment by mhosken** [comment]
There is a work around: Go to the basic tab, deselect multiple books and select the book you want to create a piclist for, then generate just that piclist. 6 clicks instead of yet another button added to the page. If multiple users start reporting that this is onerous then we can revisit the idea.

**Comment by davidc86** [comment]
Cool. That is a legitimate workaround. Thanks.

I imagine multiple books in one PDF is NOT your main “use-case”, so that’s cool.
But supporting multiple books in one PDF as you do, makes the program that much more useful, and using it in this way will likely become more common as teams see the potential.

Still I wonder if providing a way to backup modified Pic Lists would be helpful. Because tweaking the picture details for PTXprint can be tedious, and it would be sad to lose all that work because someone wanted to generate a new Pic List for a new book they added to their growing “Book” and so they hit generate…

Until then, this workaround is a reasonable direction.
David
