### ISSUE TITLE
Centered Headers and Footers on Title pages aren't shifted as expected

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#580]
This seems to affect all title page headers and footers:

![image](https://user-images.githubusercontent.com/12962708/141856451-ffeedce9-8aba-424d-9681-76192672a5d2.png)

as well as the odd page centered footer:
![image](https://user-images.githubusercontent.com/12962708/141856984-9e235773-c50e-4784-bc4c-d2d7d88f1cb6.png)

**Comment by davidg-sil** [comment]
I don't know who added the control to the UI, but it's an enhancement opportunity. There's nothing in the TeX code for it to control, and I don't know if the python has any action, either.

I guess it might look OK for the centre heading  to be off-centre if the shift is small, but I think it would look very odd for the centre  heading to follow if the page were split 60-40.

For polyglot, there are worse problems. I presume that people who didn't want it actually central would want it 'nearest the division or mid-point that's closest to the centre of the page' or something similar, and we'd need to invent an algorithm in TeX code to find that 'best indent'.

**Comment by davidg-sil** [comment]
If it is working anywhere, (as I see it seems to be, looking at the blue-green header) that is because there have been some calculations being added somewhere (not the underlying tex) to produce a box that when centred on the page produces text that's off-centre.

**Comment by markpenny** [comment]
indeed, this was all being controlled by some fancy footwork by python while generating the tex file. MH has fixed it now, so this issue can be closed.
