### ISSUE TITLE
Generated AdjList for diglot publications are faulty

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#581]
There seem to be a couple of issues in the AdjLists generated for diglot publications:
a) The verse shown is the LAST verse in the paragraph [usually we show the starting verse of the para]
b) when the L and R lines are displayed for verses with more than one paragraph, the [2] numbers don't seem to be right:

1JNL 2.13 +0% +-[2] +-[4] +-[6]
1JNR 2.13 +0% +-[3] +[5] +[7]
1JNL 2.14 +0% +[2] +[4] +-[6] +[8] +[10] +[12] +[14]
1JNR 2.14 +0% +[3] +-[5] +-[7] +[9] +[11] +[13] +[15]
1JNL 2.17 +0% +[2]
1JNR 2.17 +0% +[3]
1JNL 2.19 +-0

The para counter seems to be incrementing for both the L and R in 2's, whereas it should presumably only increment in 1's

**Comment by davidg-sil** [comment]
What's actually happening is that the paragraph counter has not been made side-specific. So if there is no reset e.g. caused by a verse number, then it counts both left and right paragraphs. This is a bug, and in some cases can lead to duplicate 'labels'.
