### ISSUE TITLE
v2.0.11 styles not working?

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#583]
Just installed v2.0.11 and tested the output without changing anything, and the style for \s and \s1 (and maybe others?) is being ignored. I use a different font for the \s1 content, but it is coming out looking just like the main text. And the "space before" setting is also being ignored.

It also looks like all the indentions are now being ignored. (Regular first line indentions as well as hanging indentions for quotes and poetry.) Also line spacing is not working as defined (so the \b line is supposed to be a very small 1/2 space, so the first and last one together realign the body text line spacing, but v2.0.11 is showing it as having full line spacing.)

Did something from the style sheet get disconnected?

**Comment by davidg-sil** [comment]
did a half-height `\b` ever work?  I'm surprised.... And this would cause gridding problems if the poem crossed a page boundary.

**Comment by davidc86** [comment]
Personally I care more about the final "looks" than mitigating bleed-through issues by holding the text to a grid, because the stuff we print using PTXprint is mostly short-run printings photocopied onto fairly stiff photocopy paper, so bleed-through is not an issue like it is with rice paper.

**Comment by davidc86** [comment]
But v2.0.13 fixed the "missing stylesheet" mystery. Thanks!
