### ISSUE TITLE
Line wrapping in ToC

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#584]
I'll admit that long ToC entries are unsightly, but one of the teams I work with has a few examples that the don't feel they can shorten. Furthermore, the size of the paper and font result in quite a few ToC entries going to a second line.

The major "bug" currently is that the page number should probably line up with the 2nd line, not the first (see red).

A minor issue is that it would be nice if the 2nd line were indented on the right side (see green).

![image](https://user-images.githubusercontent.com/30174022/142043337-0c2dfe22-8b03-4771-94d8-dc7993b7e270.png)
[zEngTest-XXA_testPTXprintArchive.zip](https://github.com/sillsdev/ptx2pdf/files/7548878/zEngTest-XXA_testPTXprintArchive.zip)

**Comment by davidg-sil** [comment]
Your minor issue is solvable: I added a stylesheet entry for `cat:toc|tc1`  in order to control the indents. Note that of the paragraph settings, only *left margin*, *first line indent* and *right margin* factors are used. 

![image](https://user-images.githubusercontent.com/58848232/142163624-65fea7b0-615b-4b78-aa36-ccaccef9dd4e.png)

**Result**:
![image](https://user-images.githubusercontent.com/58848232/142163917-2595381f-fff6-432c-b47a-2771c698e476.png)

**Comment by davidg-sil** [comment]
Unfortunately, having spent about 45 minutes looking at the table-handling code to try to understand it, I can now say with relative certainty that what you're asking for would need a  significant rewrite. At present it formats the cells, and then goes through splitting off line 1 of cell 1, line 1 of cell 2, etc and makes that a line of text, outputs that, and moves onto line 2. 
This is wonderful in terms of avoiding alignment problems that come from putting multi-line boxes with mixing fonts / sizes next to each other, but to adjust the algorithm for what you're asking? ouch.

**Comment by mnjames** [comment]
> I added a stylesheet entry for `cat:toc|tc1` in order to control the indents.

I'm assuming this will show up in some future build, correct?

I used that idea to add entries to my own stylesheet. However, I had to adjust `tr` to move the second line. Did you?

```
### This shifts the 2nd line, when the ToC runs too long
\Marker cat:toc|tr
\LeftMargin 0.5
### This then puts the beginning of the 1st line back in place
\Marker cat:toc|tc1
\FirstLineIndent -0.25
```

**Comment by cmahte** [comment]
Can you address this with the table definition.  That is, change the cell
definition to align to bottom?  Is it actually a "table" in the eyes of
TeX, or just a bunch of text boxes?

**Comment by davidg-sil** [comment]
I only did the changes shown, both in the tc1. But if it works, great!

**Comment by davidc86** [comment]
Nice. The only thing missing from the request and this solution, is getting the page number to line up with line 2 not line 1 (so it occurs at the end of the ..................)

Am I seeing this correctly that getting the page number in the right place is still a limitation?

**Comment by markpenny** [comment]
![image](https://user-images.githubusercontent.com/12962708/142803926-4e7ddb69-8420-4ab4-ad69-7b8acdd4dabd.png)

Don't have any leading dots on 1st line and move everything else down.

**Comment by davidg-sil** [comment]
> Can you address this with the table definition.  That is, change the cell
definition to align to bottom?  Is it actually a "table" in the eyes of
TeX, or just a bunch of text boxes?

Each cell starts off as an hbox. Each column starts out as a vbox of hboxes.
At the end of the table, the natural width of the columns  are compared to tablewidth/Ncolumns, and 'spare space' gets taken from narrow columns and reallocated to 'oversize' columns.  Thus e.g. page numbers (being narrower than width/Ncolumns) will never get wrapped, but sections titles may be.

Then the columns get taken apart box by box and  wrapped to their allocated widths. Beyond that, I don't really understand what's happening. It gets complicated.

**Comment by mhosken** [comment]
If you want to take it on, then the ***@***.*** macro counts the number of
lines needed to render a row and then emits an hbox or empty hbox for a
particular line and column in the row. Currently if there are fewer lines
in the cell than the row needs, it emits full boxes for each one from the
top. We would need to reprogram to emit empty boxes at the top and fill
from the bottom.

**Comment by davidg-sil** [comment]
Something garbled your macro name I guess it decided it was an email address... `\getnth@line` looks like the emitting empty/full boxes bit. And `\nth@line` ==1 for the 1st line. 
`\line@count` gives us the total number of lines for all cells, `\lc@tmp` gives us the count for *this* call.
**Someone check my maths...**
There will be `\line@count-\lc@tmp` lines of blanks. 
So.. if we have 'bottom alignment', we subtract this from `\nth@line` between calculating `\lc@tmp` and doing the output.
Then, we add a condition to give a blank line if `\nth@line <1`, then urm, we've broken the loop variable.  but other than that, should it work?
For centre alignment we could  subtract (integer) half the offset value, optionally remembering if the offset was odd to `\lower` the box by 0.5 lines.

**Comment by davidg-sil** [comment]
I've implemented the following. 
Table cells of a given column (and category) get an extra `\VerticalAlign` option control, (feel free to nominate/vote on alternative names!)
This can take the following values:
`t` - top (default!)
`b` - bottom
`c` - center (shifting result by 0.5 baselineskip if there's an odd number)
`g` - gridded center (staying on grid, only moving by whole lines, not half lines.)


![image](https://user-images.githubusercontent.com/58848232/143129790-0fc98f2d-6657-43e2-b57a-771cc4e70ce7.png)
![image](https://user-images.githubusercontent.com/58848232/143129926-ad5a4946-0a05-4fae-867c-d1502fffa712.png)
![image](https://user-images.githubusercontent.com/58848232/143129999-3b9e4bb7-4e72-437c-9b2a-139b4181ea81.png)

**Comment by davidc86** [comment]
Sweet!
The "b" one is the one I've been looking for. Thanks. (Maybe "b" should be the default?)

Your naming is great. 

Is this put in the custom.sty file or ptxprint-mods.sty file or where?

**Comment by mnjames** [comment]
Thanks for all your hard work on this. I just tested it on two projects where we had seen this problem, and it looks great in both of them!

@davidc86, you ought to be able to put this in any stylesheet you want. Personally I'd put the change in custom.sty if I wanted it to affect everything I ever print (which in this case is true) or in ptxprint-mods.sty if I just wanted it to affect one particular print config. And of course this won't go into affect until program installer gets updated or until you move the source code onto your machine.
