### ISSUE TITLE
Has the "cleanup" button been removed from PTXprint?

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#588]
I recall there used to be a "cleanup" button which deleted all the temp files and processing files and just left the results. I can't find this button anymore. Does PTXprint always delete these files now?

I'm finding piles of old PTXprint files in several locations, like in 
...\SLU\local\ptxprint
...\SLU\shared\ptxprint
...\SLU\printdraft   (here I found a pile of old stuff) 

So, over the last years of its development has PTXprint changed where it stores its working directory, its output directory, and its shared directory?

Just curious what I can get rid of safely.

BTW, I'm hoping the "shared" directory is copied automatically through the Paratext Send/Receive process, so the teams can get copies of the latest PTXprint formats and layouts, and used them "ready-made". Is this how you understand the contents of the "shared" folder to work? (I tried to share files with a colleague by copying these setup files from my shared folder to his project's shared folder on my computer, and then do a S/R, but the files were not sent. --Maybe only administrators for a project can do that kind of  slight-of-hand?)

Things are looking good on v2.0.14

**Comment by mhosken** [comment]
Yes we did away with the cleanup button. We could replace it. But dealing with temp files is so much easier now. All temp files are stored in the `<project>/local/ptxprint/<config>` directory with the resulting pdf in `<project>/local/ptxprint`. So if you want to really clean up everything just delete `<project>/local/ptxprint` or the `<project>/local/ptxprint/<config>` directory if you want to keep the pdf.

Everything of worth is kept in `<project>/shared/ptxprint/<config>`.

**Comment by markpenny** [comment]
Yes, you are right about how the "shared" folder is supposed to work. But whether anything actually gets sent (almost certainly) depends on what role you have on the other project. I am guessing that settings don't get propagated for Observers, but do for everyone else, but I haven't tested this yet.

Note that there is no longer a need to manually copy-and-paste settings, as there is a button to copy a (source) configuration to one or more other (target) Paratext projects:
![image](https://user-images.githubusercontent.com/12962708/142806983-e35555a2-3da0-4826-9d2c-7909abddf3e0.png)

**Comment by davidc86** [comment]
Wow, Nice feature! I just never noticed it. (Always something new to discover in PTXprint.)
One thing though: Does it give a chance to rename the configuration file as it is saved? For example, say I've created a great looking "SLU-Approved Publications" configuration, and a "SLU-UNS Checks" configuration. If I had the option to save these two configurations to 4 other languages, but with the code "SLU" replaced with the codes of the target languages, that would be elegant. That is probably asking too much, but I am hesitant to have multiple copies of files on our computers that are named the same but could be unique (where users in language JMD changed a setting, while no one else did). 

Also, can these be made to lock on the fly? Or do we need to "lock" the configuration first, and then copy them? Will they be locked in the new locations too? 

And how locked is "locked"? Like, does it actually mean "write protected" whereby the user can tweak a setting in this instance, but when they exit, the configuration is not changed? Or is it locked down such that no settings are tweakable? I'm thinking it acts like "write protected" but wanted to verify that.

**Comment by davidc86** [comment]
On the cleanup button... well, maybe PTXprint could be set to always automatically cleanup after itself. i.e. it never leaves any temporary files laying around, and only leaves the PDFs in the <project>/local/ptxprint folder. 

IFF the user has a problem or needs to debug something, then they use the "Archive" button, which could bundle up those temp files into its zip file (along with whatever else it does), and then after zipping them, it also deletes the temp files/folders off the hard drive. 

This would keep the user's computer clean without her needing to do anything. (Just a thought.) --I realize I've been doing testing for a while now so my clutter reflects over a year of messing about. So my case is not the same as new users. I like the current folder decisions, but I think clearing out the local folder of everything but the PDFs is better for most users. (Maybe a "keep temp files" check box in the Helps tab next to the Create Archive... button would help developers and testers? Default is off. But if checked, then PTXprint would behave like it does now, leaving the config folder and temp files in the local folder, whether the user actually clicks the Archive button or not.)

**Comment by markpenny** [comment]
We have some more ideas about how best to share configs with other projects, and this involves being able to lock certain parameters while leaving other parameters open to be changed according to the end user's preferences. Right now we're experimenting with an idea of using Ctrl+Click to LOCK a control (i.e. that would de-sensitize the checkbox, drop-down option or some other adjustment setting). This would then enable the person creating the "template config" to allow some wiggle room within other tightly controlled settings.

Right now the lock is all or nothing; and in fact it appears to be broken. On the last try, it not only enabled me to change a setting, but saved the new values in the (updated) config :-(  The lock only seems to [currently] stop them from switching to a different view, so in some senses, it is working: Use full view to set all the parameters, then turn on Mini/Basic view, then LOCK the config, and then share it. Now they can only see the Mini/Basic view and change just those parameters. But we have no way of locking other user-specified values; and that would be good to have.

**Comment by markpenny** [comment]
On the cleanup-up side. The main reason that we aren't offering that button now is because there are a LOT of 'temp' files in there that *do* get used time and time again - especially between runs. So if we deleted them by default, each run would take significantly longer (especially if pictures are involved, as it scans multiple folders looking for the best match size/quality etc. and then if needed, converts the image to the correct format [TIF->JPG] and if "PDF-X/1a" output is required, it also converts each picture pixel-by-pixel into the right image format to comply with the standard). Yes, there's a lot going on behind the scenes.

I think the best we could/should do is to scan the `<project>/local/ptxprint/<config>` folder**s** at start-up, and if the size of any folder > **x** Megabytes, and/or the latest datestamps are > 1 week (i.e. stale files taking a lot of space), then we could show a "Tidy up temporary files" button on the Advanced tab. That would just delete "old unwanted stuff" while keeping the PDFs intact. How does that sound?

**Comment by davidc86** [comment]
Thanks for clarifying the reason for maintaining "temp" files around. Speed is a nice goal. So, I agree, don't automatically delete stuff. I'm not even sure we need a "x MB then delete". If the Helps page just mentions the folder were "Temporary PTXprint files are kept (these can be deleted if needed)" and a hyperlink to that location, then people could go and delete it themselves. 

I see that currently it says, "Output PDF Location" for this. That is a more useful label. 

But this is also where the temporary config files are kept. So if under that "local/ptxprint" folder PTXprint created another folder layer, like "**local/ptxprint/temp**", and in _there_ all the temp folders and files for each PTXprint configuration. (Yeah, a hassle to make a tweak like that. But at least then any user can tell that if they delete that folder, they won't lose valuable settings, etc.) 

Another option is just to call the Output folder "**local/ptxprint-temp**". Everything else just stays the same. I like this idea, because while that is also where the final PDFs are put, even those output PDF files will get written over each time a config file is run, so, they too are temporary, and if the user needs to keep them safe, then he needs to manually copy them out of that folder and put them somewhere more permanent. 

Just something to think about. I for one, find it confusing (and scary) when two folders are named the same, but the content is not the same. I try to avoid it.

**Comment by davidc86** [comment]
Very interesting about the "lock" feature (probably these should be moved to another "issue" thread?)

I like the idea of setting up the advanced tab, and then collapsing it to mini-view and then locking it. So that it limits the kind of tweaking the end user can do. Very, very nice. I can see where the "mini-view" would be very helpful to many MTTs. 

Basic view is also nice for more savvy users. 

(Uh-oh, it just crashed on me while flipping between Full, Mini, Basic, Mini, Full.)

**Comment by markpenny** [comment]
I think this tweaked Label and tooltip is probably adequate for most users:
![image](https://user-images.githubusercontent.com/12962708/150713692-d73a34f6-84e3-4e6e-8a11-d21e3551a03e.png)

**Comment by davidc86** [comment]
Nice! Thanks for that.
________________________________

**Comment by markpenny** [comment]
While I was in the area, I decided to make life easier for everyone by adding a [Delete] button as well:
![image](https://user-images.githubusercontent.com/12962708/150724159-812d5bb0-3a4e-407d-a393-2cce6c85edb1.png)
I think it makes more sense here than on the "Advanced" page which most users would never see anyway.
