### ISSUE TITLE
Please allow PTXprint to fail graciously if the ptxprint file is currently open in Adobe

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#59]
If the ptxprint export file is currently open in Adobe, PTXprint fails with an export error that looks scary, when in fact it is harmless! 

HACK SOLUTION: Don't have a coronary; just close the file, and rerun the "PRINT" process. 

POSSIBLE DESIRED BEHAVIOR:
1) Say, "Hey, I think the old xxxx file is open in another program, that means I can't generate a new version of the PDF file. Please close the file, and rerun the Print function."     
2) Say, "The xxxx file is open in another program, please give another name for the export file...." And open a dialog box to get a new name.
3) Just append the *time stamp* on the file name each time, so this problem never comes up. 
Yeah, we may end up with a pile of these exported files if we are testing stuff. But they can easily be deleted. And there is a benefit to having a history of PDF versions, as it's easier to see the affects changes we make in PTXprint options and stylesheets have on the exported file. And we can then compare and decide which looks best.

Personally, I vote for option 3.
PS The SumatraPDF reader didn't help. And most people use Adobe anyway, so a solution for the masses would be good.

**Comment by mhosken** [comment]
I vote against solution 3. I really don't want to see us go the timestamp route. It litters peoples file systems, and it's not like you can go back and do anything about the previous versions.

I vote for solution 1 (with "Try again" and "cancel" buttons)

If we are forced to go with solution 3, then I would probably have it switched off by default and have a checkbox on either the advanced tab or in a yet to be defined general tool config tab.

**Comment by davidc86** [comment]
I'm good with that. Solution 1 is the easiest, and with a Try again button, they user could simply kill the PDF in Acrobat Reader and then hit try again, in theory without having to reprocess the whole file? (Depending on where it fails currently.)

**Comment by markpenny** [comment]
Ideally we would check whether that file is locked immediately after hitting "Print" before we go through the long process of creating it. Or, we could colour the Print button orange if the file is still open (AND locked) by a tool like Adobe Acrobat Reader.
Personally, my preference is that people use a reader that doesn't lock the PDF, as it makes the whole process far more re-runable and easy to tweak. But I agree that most of the world is using Acrobat, and changing the tide is difficult.

**Comment by markpenny** [comment]
OK - done. Thanks for good suggestion!
![image](https://user-images.githubusercontent.com/12962708/82115817-c4b59a80-9782-11ea-972d-f57190afa32d.png)

**Comment by markpenny** [comment]
![image](https://user-images.githubusercontent.com/12962708/82119684-23d4d880-979e-11ea-92e2-b2ee5fc10504.png)

The more important info is at the top and hopefully more obvious now...
