### ISSUE TITLE
Should there be a way to force invalidation of the font-cache?

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#590]
Related to #589...

If, e.g. for the glossary  it were desired that **everything** be 5% smaller,
then the 'natural' decision might be to try to alter `\FontSizeUnit`. 
Crude testing shows this only affects unmet fonts, as existing fonts are saved as `\font<p-12>` etc. 

Fonts not in the stylesheet but 'calculated` on-the fly, such as `\font<nd+p-12>` will not be invalidated by reloading the stylesheet.

Should there be some way to force all these fonts to be re-calculated?

**Comment by mhosken** [comment]
While it may seem simpler to just change the fontsizeunit to reduce all the fonts in some peripheral book, PTXprint doesn't facilitate that. If it did, then it wouldn't be hard to have PTXprint also output the necessary macro call to clear the ptx macros font cache.

**Comment by davidg-sil** [comment]
At present there's no record of the on-the-fly created fonts.
Stylesheet-based fonts will be reset if stylesheets are reloaded (I think)
but not complex 'situation' based fonts, like the plus forms of character
styles.

This issue is about that lack of a list to reset.

**Comment by davidg-sil** [comment]
While mainly a separate issue, this enhancement will be very much aided by the list-traversal-simplification referenced in #576
