### ISSUE TITLE
Page numbering bug in ToC

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#592]
When creating a table of contents based on section titles in a book, if a section title (and hence a \toc1 marker) falls at the very top of a page, it gets listed in the ToC list with the page number of the _previous_ page.

[zEngTest-DefaultPTXprintArchive.zip](https://github.com/sillsdev/ptx2pdf/files/7618459/zEngTest-DefaultPTXprintArchive.zip)

**Comment by mhosken** [comment]
This is probably due to the toc entry being output before the vbox for the heading block. Perhaps move the \toc1 to after the \p. I know that feals late but there cannot be a page break after a heading block, so it should be safe. So, this change seems to work:
```
'\\s (.*?)\n+\\p(\s+)' > '\\s \1\n\\p\n\\toc1 \1\n'
```

**Comment by mhosken** [comment]
OK push it even later! After the first word so that the new paragraph has definitely started:
```
'\\s (.*?)\n+\\p(\s+\S+)' > '\\s \1\n\\p\2\n\\toc1 \1\n'
```
This now seems to work

**Comment by mnjames** [comment]
Thank you. This almost works. The one place it doesn't work is when there are two heading, so the formating is 
```
\s title1
\s2 subsection
\p
```
It only happens once in the document I'm working on, and I'm willing to modify the Bible Module text if necessary, but I have experimented and can't get it to work.

[I'm using an extra regex, now `'\\s2 (.*?)\n+\\p(\s+\S+)' > '\\s2 • \1\n\\p\2\n\\toc1 ~~~~~~~~~~~~~~~~~~~~~~~~~~\1\n'`, to visually indent the s2 markers in the ToC. So it actually does makes some sense to have both \s and \2 markers show up in the ToC.]

Incidentally, this is a nice workaround but I'd still consider this a bug, since I think the average user would assume if the \s marker breaks at a page, that the \toc marker after it would be considered on that page. But I'll leave it to you to decide if other people will have this problem and if it's a bug worth spending time on.

**Comment by mnjames** [comment]
I was able to create a (very ugly) hack to get this working, so I now have output which looks correct.
