### ISSUE TITLE
\toc1 marks cause the following paragraph to have incorrect justification

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#595]
If a \toc1 mark is added into a Bible Module, the following paragraph has a small indent at the end of the first line. In a RTL language this means the left margin is slightly shorter than the lines below it (I haven't tested in LTR languages). Removing the \toc1 marks appears to remove the problem.

If the sfm looks like this:
```
\s
\toc1
\p paragraph one
\p paragraph two
```
then the problem is in paragraph one

If the sfm looks like this
```
\s
\p paragraph
\toc1
one
\p paragraph two
```
then the problem is in paragraph two (see #592 for why that second format might occur).

I've sent an archive via email.

**Comment by mhosken** [comment]
Sounds like an extra space is leaking somewhere in the TOC code and I think I may have found the offending spaces. But I can't test. If you can update your macros from the source repo (see the src/ dir) then you can test. Although why the space is added at the end of the first line, is certainly a brain teaser.

**Comment by mnjames** [comment]
I'm not seeing any recent pushes to github. I updated the only file that had changed since I last updated from /src but that didn't change anything.

**Comment by markpenny** [comment]
@mnjames This has been fixed. Please confirm and close the issue.

**Comment by mnjames** [comment]
Looks great. Thank you very much. Thank you also for the config-specific printdraftchanges!
