### ISSUE TITLE
Section Headings (\s, \s1, etc) L/R Indentions not working correctly

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#596]
(PTXprint v2.0.20) 
On the Layout page we have the base indention set at 0.20 inches.

On the Style page, if we set the Left and Right Indentions for the Section Heading (\s1) to 0.00 (the default) PTXprint formats the PDF accurately and does NOT indent either the left or right side of the \s1 line.
 
But if we change the Left and Right Indentions to 1.00 (i.e. 1.00* 0.20" = 0.20", correct?), we get this:

![image](https://user-images.githubusercontent.com/65363206/145106936-0cfe140a-3b0d-4083-9ba4-bd9b67f8895b.png)

See how the Left and Right Indention on that section heading are WAY too big? If you look at the first-line indention for the main paragraphs, you will see what 0.20" should look like. The indentions in that section heading are way bigger than 0.20".

If we change the Indentions to only 0.75, the indentions INCREASED in the printout! (Expected results would be 0.75*0.20 = 0.15" a smaller value.)

If we change the Indentions back to 0.00, the indentions correctly return to Zero.

Even more concerning, if we change just the LEFT Indention to 1.00 and leave the RIGHT indention at 0.00, PTXprint indents BOTH sides (L/R), and the results of this setup look identical to the above screen shot. 

So, something is amiss.

**Comment by markpenny** [comment]
@davidc86 As far as I understand, there is something else special going on with section headings where it is trying to BALANCE text that flows onto 2 lines. By "Balance", I mean that it intelligently saves itself from coming up with really ugly looking headings, where all but the last word fits on the first line, and you are left with an ugly one-word second line. So it tries to put an equal amount of text on each line.
So those indentation values won't work exactly as you're expecting them to. But if you do set a left and right indent factor, it will make sure that the section heading never goes all the way to the margins. Instead, it will break the line in 2 "as evenly as possible".
If I have misunderstood the issue, then please clarify again.

**Comment by davidc86** [comment]
Okay, maybe PTXprint (or the underlying macros) are being too smart. 

The purpose of the style sheet is to allow the end user to control the look of the output. If the user specifies a left/right indention with a factor of 1.0, that means the user only wants the section headings to be indented that far. If they specified 2.0x then they want to double the base indention. Any other behavior is seen as a bug.

 I find the highly indented double lines in the screenshot above rather unpleasant to look at. I was expecting something more along the lines of:

    Paulus syalak eraske ba ti Hulasokwe ti eras inal ti  
                               iry a Korintus-are ne

This way the first line of all the section headings will look uniformly the same length (or close to it). 

If for some odd-ball reason we need to break the section heading in a different place, e.g. I need that "ti" at the end of the first line to go onto the second line, I believe there is a SF code for forcing line breaks. (I don't have it memorized, but I recall there is one.)

My point here is that the style sheet provides important features that the macros ignore. 

If some would prefer to just let PTXprint "balance multiple title/heading lines" then that should be a selectable option on the relevant style page (which if selected would turn off the Left and Right indent measurements in that style's UI).

**Comment by mhosken** [comment]
The way things work in centred text, TeX is not penalising short lines. This means that it will tend to create balanced lines. If you want to force a later line break, you can, by inserting a // in your heading (probably via a changes.txt). E.g.

```
'(\\s bagavantanor mari yēsu) (kiristu āndur)' > '\1//\2'
```

This seems to be the opposite from InDesign where you have to manually balance headings by inserting appropriate line breaks. Also, do remember that TeX isn't going to end up with more lines as a result of the balancing. It's only where it has a choice between balancing the lines or unbalancing the same number of lines.

**Comment by markpenny** [comment]
@davidc86 I'm coming from a background of typesetting scripture for several projects using InDesign and Publishing Assistant. I know how frustrated typesetters get because InDesign can't do what PTXprint does for us "automatically". So I'm surprised that you actually want it to have a long line followed by a short line. Most typesetters spend hours going through the entire NT manually adjusting those kinds of things to make them look balanced.

Is your preference based on some past experience, or is it just what you (or the readers) are used to? And what do they feel when they see the "balanced" way of doing things? Curious.

**Comment by davidc86** [comment]
I guess it is just personal preference. I'm sure neither the team nor the community have a huge opinion on this, but if the sides are indented too much, it brings more focus to the Heading as being something special, set apart with very wide margins-more like a picture caption or some such, rather than just a piece of centered peripheral text that just happens to be too long to fit on one line. The idea for the small left and right indentions was simply too keep some of the headings from nearly touching the margins-set them in a bit, so it is clear they are not verse text, but not so much that it draws a lot of attention to them.

BUT my main point is make sure the UI matches the behavior.

  *   If the UI allows the end-user to specify some numerical value for an indention (left, or right, or both), then the software/macros should behave that way.
  *   If the software doesn't want to give that kind of fine-tuning to the end-user for section headings, then the section headings style UI should NOT imply it supports that. I.e. the Left and Right Indentions should be removed and replaced with one check box: [ x ] Indent and Balance long (multi-line) sections headings.
And the default should be Checked.

Personally, I don't think any centered paragraph should be allowed to get closer than 1 Basic Indention away from the Left and the Right Margins, whether the length of the multiple lines are "balanced" or not.

Obviously, how it behaves isn't a hill to die on. If more experienced Publication specialists think balanced line lengths are ideal, then who am I to say that is not right. So don't go through special hoops to make it do something else, if it already does something really nice. I'm just wanting to help point out places where the UI and behavior don't match up. Because if the UI implies one thing and the software doesn't behave that way, users will see this as a bug. (If you want to go the extra mile and allow both types of behavior, that's cool. But I think going the route of just changing the UI to match behavior is the quickest solution at this point. If others whine about not having fine control over the L/R indention, then this feature could be revisited.)

Blessed Holidays for you all!
David
