### ISSUE TITLE
Could PTXprint be made to optionally remember the last Config it had open?

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#60]
It would be helpful (especially for MTTs) if PTXprint could remember the last config file it had open. Or minimally the last Paratext Project it had open. It be best if teams didn't need to scroll through a list of other projects unless they specifically knew what they were doing.  

This setting could be optional ("normally selected"). Thoughts?

**Comment by mhosken** [comment]
added to dev/

**Comment by davidc86** [comment]
Sweet! THANK YOU. Nicely done.
