### ISSUE TITLE
"Contextual Spaces" option is not saved

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#602]
In the font dialogue, if I choose the "Contextual Spaces" option it has the expected affect on output. However, if I save the current configuration and then re-open ptxprint and/or change configurations, it forgets that "Contextual Spaces" was chosen. In other words, I have to re-check that box every time I load ptxprint or change configurations.

**Comment by markpenny** [comment]
This should now be fixed in 2.0.30

**Comment by mnjames** [comment]
I've checked and it works great. Thank you very much.
