### ISSUE TITLE
Can’t type in configuration name field with Keyman keyboard

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#606]
I haven’t tracked down exactly when this happens, but when I’m just starting out with a new project, I make a couple of changes to the configuration, print a couple of times, and I decide that I’m ready to save my configuration... If I click in the configuration name field (with my Keyman keyboard activated), I can’t type anything. If I turn off my Keyman keyboard, it works fine. But also later on when I just click in the configuration name field (with the Kyamn keyboard activated), I can type just fine. So I don’t know when it happens, but I have a sequence of events (starting up with a new project) where I can get it to happen every time.

**Comment by markpenny** [comment]
@mhosken We you able to glean any insights about this bug when you worked with Jeff?

**Comment by jeffheath-sil** [comment]
OK, I have it down to a very basic consistent failure path. 

If I open PTXprint with my sil_tchad (version 4.2) keyboard activated, then click at the end of the Saved configuration name field, **I try to type and I get nothing out**. If I turn off the keyboard, I can type, and if I turn it back on, I can type.

If I open PTXprint with my sil_tchad keyboard off, then I can type in the configuration name field without a problem, even if I turn on the keyboard before I start typing.

In both cases I’m opening PTXprint (French interface, Basic View, but I think it happens in English interface as well) on a brand new project, i.e. the ptxprint folders in the shared and local directories of the project have just been deleted.

Hope that helps...

**Comment by mhosken** [comment]
I'm almost certain this is a GTK interaction bug and outside the scope of what we can program from within the python. Am leaning towards a nofix on this.
