### ISSUE TITLE
PTXPrint "just closed"

### ISSUE THREAD

**Issue by SaraMeiSL** [sillsdev/ptx2pdf#608]
I installed, as a first installation, 2.0.33 and was looking around. I have Full View chosen and when I clicked on Styles, the program just closed. On re-opening, no further such closes have been encountered so far.

**Comment by markpenny** [comment]
Thanks for pointing this out. Yes, there's a new bug lurking in the Styles area. It is most likely something to do with the new twisties/exanding sections; but we haven't been able to nail it down yet. If you want/need stability, then I suggest reverting to 2.0.30 (as there were a bunch of significant changes made shortly after that - some of which are only partly stable).
