### ISSUE TITLE
Getting a reference memory error in 0.6.2

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#61]
I moved a picture, and removed two \b and \m markers, and now I'm getting a referenced memory error.

![image](https://user-images.githubusercontent.com/65363206/82123023-1818f000-9765-11ea-92dd-65437b9a7b59.png)

Also Adobe Acrobat Reader is complaining:

![image](https://user-images.githubusercontent.com/65363206/82123096-72b24c00-9765-11ea-9ea2-84ab19125b73.png)

Not sure what changed. I did also change a picture from |span*.7| to |span| so now I will try to roll back what I did to see at what point it completes okay.

FYI, I changed nothing, but restarted PTXprint and Adobe Acrobat Reader, and it created the file just fine. The trigger might have been not closing the PDF file first. So it fired off the 0.6.2 error message which is supposed to be fixed in 0.6.3. So hopefully this is all mute.

**Comment by markpenny** [comment]
@davidc86 Could you confirm that this was just a temporary glitch, which no longer happens now that we test for the PDF being open (and ask you to close it) before we try to re-create it.
0.6.6 should be available later this evening - and has some nice additions for you to test and give feedback on. I hope you will like the "Filtered Glossary" option on the Body tab.

**Comment by davidc86** [comment]
I say close this issue and if it rears its head again, we can make a new issue.
