### ISSUE TITLE
Nested quotes font change

### ISSUE THREAD

**Issue by LouKehler** [sillsdev/ptx2pdf#613]
I'm seeing a problem in multiple RTL projects involving nested quotes. Where a single closing quote is followed by a double closing quote the double quote appears in a different font. Where the closing double quote occurs on its own, it is in the correct font.

The same behaviour occurs in the case of a double closing quote followed by a closing single quote followed by a double closing quote. The first double quote is in the correct font but the following single and double are in a different font.

![NestedClosingQuotes](https://user-images.githubusercontent.com/39006144/152190550-5b2fdedd-e570-40c8-b887-93ce4538ee5a.jpg)

**Comment by davidg-sil** [comment]
I'm wondering what the input USFM is. If the original uses << < > >>, it might be  a printdraft-mods.txt bug that's not giving the right unicode character for combinations but is for stand-alone. Is that possible?

**Comment by mhosken** [comment]
Is there an archive for this?

**Comment by LouKehler** [comment]
I did some digging and the problem has to do with the ptx2pdf macro file "ptxplus-character-kerning.tex". When I comment out the lines
%\catcode"2018=\active
%\def^^^^2018{\futurelet\knext\soqtest}
%\catcode"201C=\active
%\def^^^^201c{\futurelet\knext\doqtest}
%\catcode"2019=\active
%\def^^^^2019{\futurelet\knext\scqtest}
%\catcode"201D=\active
%\def^^^^201d{\futurelet\knext\dcqtest}
then it works fine. It seems to lose the right-to-left aspect after the first closing quote.

**Comment by markpenny** [comment]
Thanks @LouKehler - when the TeX guys get back in August, they'll be able to look into this further. In the mean time, I'm glad you have been able to locate a work-around.
