### ISSUE TITLE
Column width/alignment in ToC

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#615]
Between 2.0.30 and 2.0.33, something happened to the columns in table of contents. In 2.0.30 in a RTL document, the first column (\toc1) was nicely lined up on the right margin. In 2.0.33 and later, though, that column is indented most of the way into the page.

I'm happy to set new margin numbers if necessary, but I can't remember how to do that.

![image](https://user-images.githubusercontent.com/30174022/153201484-2fe432ec-bbe1-4b27-b721-a409a33f293d.png)

**Comment by markpenny** [comment]
@mnjames  Wondering if this issue has been resolved in 2.1 or later. If not, then please send an archive to the usual e-mail address.

**Comment by mhosken** [comment]
Examining the .toc file (local/ptxprint/config/....toc) shows me lines like this:
```
\doTOCline{XXC}{\NBSP \NBSP \NBSP \NBSP \NBSP \NBSP \NBSP \NBSP \NBSP \NBSP \NBSP \NBSP \NBSP \NBSP \NBSP \NBSP \NBSP \NBSP \NBSP
 \NBSP \NBSP \NBSP \NBSP \NBSP \NBSP \NBSP \NBSP وحی کَے ذرِیعے حضرت\NBSP یحیٰیؑ کی پَیدائش کی خبر}{}{}{5}
```
I don't understand all those \NBSP. Might they by affecting things. Notice that they are all in column 1. If you think they are right and can explain what you want them for, I'll dig deeper to see what we should do to handle them.

**Comment by mnjames** [comment]
This was intentional, though I'm quite happy to be taught if there is a better way to accomplish what I was doing.

The goal was to have some ToC entries indented to have a "level 1" and "level 2" sorts of entries. But we didn't want them in completely different columns, which is why I didn't use \toc2 and \toc2. I've sent another pdf so you can see the desired output.
We accomplished this using this changes.txt entry:
```'\\s (.*?)\n+\\p(\s+\S+)' > '\\s \1\n\\p\2\n\\toc1 ~~~~~~~~~~~~~~~~~~~~~~~~~~~\1\n'```

[[Just a reminder that the strange regex syntax, putting the \toc1 mark mid-paragraph, is a result of Issue #592.]]

**Comment by markpenny** [comment]
@mhosken This overlapping of the dots on the Table of Contents is also affecting a typesetting job that I'm currently working on. Is there any possibility of expediting this issue so it gets fixed (before 2.1.5 is released)?

**Comment by davidg-sil** [comment]
Until a recent fix (committed on 23 Feb), the table row's left and right margin,  were being applied to cells within the table (and the cell left and right margin were not). This has now been fixed: only the cell margins are applied.
It may be that this fix breaks someone's formatting, but in general terms the new behaviour is much more correct.

**Comment by mnjames** [comment]
I think this is fixed, and the overlapping leader is also fixed from what I can see.

The final thing I'm interested in knowing as this issue gets closed is what marker settings affect the width of columns. Is it if you change the styles for "tc1", "tc2", etc? Or is it "cat:toc|tc1", "cat:toc|tc2", etc? Are there always 4 columns, even if you're only using one \toc marker? Are the page numbers always in tc4?

**Comment by davidg-sil** [comment]
If you apply a styling to tc1, then that applies to all tables everywhere
(unless it is overwritten by another more specific style).
If you apply it to cat:toc|tc1, then that will only apply to the tables of
that category.
So you probably want to apply it to to cat:toc|tc1 (etc)

**Comment by mhosken** [comment]
OK I think this is fixed now. The only change is that you will want to use \tc1 for your table and perhaps set tc1 space before to 0.3 or somesuch.
There is still an outstanding issue with \cat for tables, but we are chipping away at that one, it may already be fixed.

**Comment by mnjames** [comment]
My problems are solved, and I'm assuming the \cat-for-tables issue is tracked elsewhere. Thus I'm closing this.
