### ISSUE TITLE
RTL marker causes printing a Bible Module to fail

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#619]
When I try to print Bible modules in a couple of our project, I get a message stating:
![image](https://user-images.githubusercontent.com/30174022/153829097-25dae8e0-430b-405f-ae51-70c9e44b2ec1.png)

I'm almost certain this is being caused by a RTL marker (u+200F) which Paratext is adding in automatically (and which can't be avoided). For some reason that I can't figure out, a few of our projects add RTL markers after the chapter number and before the colon, and the printing fails:
\ref MAT 1[u+200F]:2[u+200F]-3
One other project, using a very similar language setup, doesn't add that first RTL marker, and it prints fine:
\ref MAT 1:2[u+200F]-3

[[Note: I expect this will be an easy fix, possibly just removing RTL markers from the module before printing. However I'll also state that we can bypass the problem by printing "Single Book: XXB" instead of "Bible Module: name_of_module.sfm". So this is a very minor problem and can be ignored if it's too much work.]]

**Comment by mhosken** [comment]
This is easy enough to fix but it raises a question over whether RLMs should be inserted into references when they are generated by ptxprint. Should we output them if the Text Script is Arabic, or if the Text Flow Direction is Right to Left (what does Hebrew do? Is there any difference of opinion within Arabic? etc.)

**Comment by mnjames** [comment]
IMO ptxprint should remove or adjust RLMs which it needs in order to make the underlying code to work. As with these \ref markers in Bible Modules and also the actual underlying pointing code in \xt markers.

However, also just my own opinion, ptxprint shouldn't change markers in the *display versions* of references, since hopefully the translation team will have worked to make the order correct. Paratext (sometimes aggravatingly) inserts markers where it thingk they're necessary, but it also allows additional markers to be inserted to change (or override) behavior. It is also possible to write regex codes fairly simply which would change display order, if the correct RLMs aren't getting inserted in Paratext. I would probably prefer that over ptxprint adding markers itself (unless the behavior were more predictable or adjustable than Paratext's behavior).

The projects I'm working would display `MAT 1:23-34` like this:
![image](https://user-images.githubusercontent.com/30174022/154000733-29e1f646-088e-4607-b0d6-0ad23519634f.png)
(yes, because of education in our country they default to Latin numbers, but the order would be the same with Arabic ones)
![image](https://user-images.githubusercontent.com/30174022/154000900-5724016f-d6af-477a-af0f-22b65a6f731a.png)

I *think* this is considered standard order. I know quite a few projects which have questioned reference order and tested different ideas, but I don't know of anyone who has actually adopted any other order. I just experimented and it looks like Paratext adds RLMs to automatically put things in this order in one project I have, but not in a second. I'm not sure what settings I made to change that behavior, and I don't have time at the moment to experiment more in Paratext.

**Comment by mhosken** [comment]
It's not references in the text that may have problems, it's things like cross references from databases or when PTXprint generates a localised reference or when the macros do that (e.g. \rangeref in headers). It would be good to spec out the range of options that people want for displaying scripture references rather than having to have them insert changes, and tex hacks and even then have to tell PTXprint what to do. So we may as well do it all once (hopefully).

**Comment by mnjames** [comment]
In theory this does sound nice, so that ptxprint fixes direction problems that are common in RTL work. But how would the user choose? Would it be another option in the gui, like saying:
```
How do you want references to look?
1) BOOK ch:v1-v2
2) v2-v1:ch BOOK
```

As I said, the 2nd option is how all projects I know of in the RTL world display references, but my world is certainly small and wouldn't say that other areas don't act differently.

**Comment by LornaSIL** [comment]
There are some (many?) African projects that use option 2.

About 1/3 of the way down this page (with "Digits" as the section head): https://software.sil.org/arabicfonts/rs-to-as-conversion/ we talk about how to implement option 2.

**Comment by mhosken** [comment]
Let's try the opposite question. Are there any Arabic script projects that don't want option 2 and if so what do they want?

**Comment by mhosken** [comment]
BTW, modules should work fine in the next release, I added stripping the RLMs from references when parsing. This happens everywhere we parse a reference, so should be good to go. But it does raise the question if we then regenerate a reference into the output what we do about RLMs, hence my questions above.

**Comment by mnjames** [comment]
For the broader question as to whether there are languages that don't follow one of the two reference-orderings that we've written here; is there any way of asking around and getting input? I know of a couple of RTL typesetters who we could ask, but it seems like the question is broader than that.
