### ISSUE TITLE
More verbose debugging needed for finding substitution / regex-induced errors.

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#623]
Given how many textual changes are introduced by regexes and other substitutions, it is sometimes hard or impossible to determine where the bug is that is damaging a particular verse or piece of text.
I'd happily search through a few megabytes of logfile to find the first place where damage occurs.

I suggest that there be a extra debugging mode  (e.g. `-l SUBSTITUTIONS`) that:

**Basic version**
For each regex / substitution, print the line before and after, assuming there is a change made. (along with some kind of indication about what's doing the change).

**Lean-logfile version**
Allow the user to specify some specific chunk of text to print out, whether that's chapter:verse or based on some kind of string-matching.

Even if the whole file is processed in one line of code, then some kind of "current status after regex" would be helpful.

**Comment by davidg-sil** [comment]
Just reporting here, MH suggests that another possible source of problems with the final USFM is the parser/writer.
It would be good to be able to isolate which problem is coming from which source.

**Comment by mhosken** [comment]
Added support for printing regex substitutions (level 7) and full file printing when unparsing (level 5). Use numeric values for the -l option to ptxprint.

**Comment by mnjames** [comment]
Are these sorts of flags for ptxprint only available when running it from the command-line using python, or are they available in the compiled (.exe) version? Can they be set from within the UI, or only prior to launching?

**Comment by markpenny** [comment]
As far as I know, you can use these flags from the commandline - even for the compiled version. However, since we have turned off all terminal output, the results of -h is invisible too! :-(   Here's what it *should* show.

```
usage: ptxprint [-h] [-c CONFIG] [-M MODULE] [-p PARATEXT] [-d DIRECTORY] [-P]
                [-b BOOKS] [-R RUNS] [-L LANG] [-m MACROS] [-l LOGGING]
                [--logfile LOGFILE] [--timeout TIMEOUT] [-T] [-f FONTPATH]
                [--nofontcache] [-A ACTION] [-D DEFINE] [--debug] [-C CAPTURE]
                [-z EXTRAS] [-I]
                [pid]

positional arguments:
  pid                   Project id or full path to a ptxprint.cfg file

optional arguments:
  -h, --help            show this help message and exit
  -c CONFIG, --config CONFIG
                        Configuration path to load
  -M MODULE, --module MODULE
                        Module to print
  -p PARATEXT, --paratext PARATEXT
                        Path to Paratext Projects directory
  -d DIRECTORY, --directory DIRECTORY
                        Directory to store temporary files in
  -P, --print           Hits print
  -b BOOKS, --books BOOKS
                        Space separated bookid list to set
  -R RUNS, --runs RUNS  limit xetex runs
  -L LANG, --lang LANG  Set UI language code
  -m MACROS, --macros MACROS
                        Directory containing TeX macros (paratext2.tex)
  -l LOGGING, --logging LOGGING
                        Enable logging level [DEBUG, *INFO*, WARN, ERROR,
                        number]
  --logfile LOGFILE     Set logging file [ptxprint.log] or "none"
  --timeout TIMEOUT     xetex runtime timeout
  -T, --testing         Run in testing, output xdv
  -f FONTPATH, --fontpath FONTPATH
                        Directory of fonts to include (repeatable)
  --nofontcache         Don't use system fonts
  -A ACTION, --action ACTION
                        Run view method instead of print
  -D DEFINE, --define DEFINE
                        set UI component=value. Repeatable
  --debug               Give debug output
  -C CAPTURE, --capture CAPTURE
                        Capture interaction events to file. Not to be used yet
  -z EXTRAS, --extras EXTRAS
                        Special bit flags: 0-3 - verbosity of xdvipdfmx
  -I, --identify        add widget names to tooltips

```
