### ISSUE TITLE
PTXprint errors when \k  ...\k* markers are found in footnote text

### ISSUE THREAD

**Issue by sewhite** [sillsdev/ptx2pdf#625]
PTXprint Version 2.1.4
Please send to: ptxprint_support@sil.org

PTXprint [2.1.4] - Error!

Failed to create: ptxprint-Default-MATSafwa.pdf

 (./41MATSafwa-Default.SFM [1
\openout4 = `ptxprint-Default-MATSafwa.picpages'.

]
! Undefined control sequence.
\c@rref ->\id@@@ k.\kr@f 
                         
\settrign@me #1->\edef \trign@me {trigger-#1
                                            }
\stdtrigger ->\settrign@me {\c@rref }
                                     \x@ \let \x@ \tmp \csname \trign@me \en...
<inserted text> \stdtrigger 
                            \ch@ckpiclist 
\runtrigg@rs ...gers \c@rref }\the \trigg@rchecks 
                                                  
l.31 ...:1 \fk ʉDaudi \ft Bhaazya izwi \k Daudi\k*
                                                   hu Ngalulanyo ɨyɨ Mazwi a...
 
------------------------------------------------------------------------------------------
This might be related to a USFM marker error (using an unsupported marker).
Try running 'Basic Checks' in Paratext to validate markers.
[Safwa-DefaultPTXprintArchive.zip](https://github.com/sillsdev/ptx2pdf/files/8164163/Safwa-DefaultPTXprintArchive.zip)

**Comment by sewhite** [comment]
This version of Matthew, with no \k ...\k* markers in the footnote text, prints without errors.
[41MATSafwa.txt](https://github.com/sillsdev/ptx2pdf/files/8164371/41MATSafwa.txt)

**Comment by davidg-sil** [comment]
Is `\k` permissible in footnotes? I thought that the only place it occurred was the definition of key words in the glossary. `\w ...\w*`  is the body-text markup for keywords.

In terms of deciphering this error, `\k...\k*` provides an anchor-point much like verse numbers do. I'm not very surprised that it  appearing in an unexpected, not-in-a-paragraph place gives unexpected results.

**Comment by sewhite** [comment]
Thanks. David. I remember now that the usual marker to show that a word can be found in the glossary is \w, not \k. If I change the text so all the \k markers in the footnotes are \w, that version prints OK in PTXPrint. I've passed this on to the project team.

**Comment by sewhite** [comment]
The team administrator says they will switch to using \w in footnotes instead of \k.
