### ISSUE TITLE
Marginal Verses not respecting RTL

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#626]
If a language is RTL, when the "Marginal Verses" item is checked, the verse numbers still appear in the left side of the column. I would expect them to either 1) switch to the right side following the overall text direction, or 2) let me choose which side I want them on.

**Comment by mhosken** [comment]
Moving marginal verses right for rtl is a bit of work. Allowing it to be
user selected is even more. How high is the need for user selectable?

**Comment by markpenny** [comment]
This is now working *with* a user-configurable position on the page.
![image](https://user-images.githubusercontent.com/12962708/194977490-88267611-9215-496d-a66f-71efd791ea56.png)
