### ISSUE TITLE
Column headers in ToC

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#627]
Is it possible to add column headers to the ToC. Things like "Book Name" and "Page Number"?

**Comment by mnjames** [comment]
For my purposes, adding this line to the Front Matter right before the ToC line fixed my problem
`\m Book Name \hfill Page Number`
So there's no hurry on this.

However, this wouldn't work if the ToC were more than 2 columns. So it would still be nice if there is a proper way to do this.

**Comment by davidg-sil** [comment]
I don't have the time to work out  the exact syntax tonight, but an only-run-once trigger on the start of a `toc` class table seems like it **ought** to work.... assuming that's a valid trigger point. `\tracing{T}` and careful reading of log-files would tell you that, probably.

**Comment by davidg-sil** [comment]
OK... I've spent some hours battling this, and I'm giving up for now.
It *ought* be possible to prepose something like this:
```
\tr \cat toc\cat*\th1 Book name \th2 \thr3 Page Number
\ztoc|main\*
```
But unfortunately that doesn't work, giving errors about missing endgroups (a strange bracketing failure).
Without the `cat...cat*` it sort of works, but then you get an uncategorised table which looks horrible.

Likewise it ought to be possible to inject the columns via:
```
\sethook{start}{cat:toc|cat}{....}
```
Which is fired as the `ztoc` sets the category. But I had even less  success with this than I did with editing the FRT book.

I think the best approach is now for either the tocfile itself to include the headers.( i.e. a modification from the python side of things), or a modification of the `\ztoc` code to try to pull out some values for table headings.

**Comment by davidg-sil** [comment]
Update... The error was not caused by a problem with magic in ztoc, but a more global issue of `\cat ...\cat*` causing crashes when used with a table. I've just pushed code that makes this work once more.
```
\tr \cat toc\cat*\th1 Book name \th2 \thr3 Page Number
\ztoc|main\*
```
@mhosken  has also been working on tables and it's looking possible that some of our 'fixes' disagree with one another about what ought to be happening where, so don't leap too soon...

**Comment by mnjames** [comment]
Using 2.1.8 your code is working but the final column (the Page Number one) isn't aligned in the same way as the actual page numbers. In fact, it's showing up in middle of the table instead of at the left edge (in a RTL language).

One other potential problem, this code adds leaders between the table headers. My gut reaction is that they shouldn't be there--though maybe having them set independently from the regular lines would allow the user more choice.

For my current project I have a nice looking workaround and so don't need this, but I think long-term it would be natural/expected for ptxprint to support ToC headers. Exactly how that would operate might need further discussion. At the least, I would say something like @davidg-sil's code directly above here ought to be added to the front matter template.

**Comment by mnjames** [comment]
Multiple columns of header can be now added using the snippet
```
\ztocbefore
\tr \cat toc\cat*\tc1 Index\tc2\tcr3 i
\ztocbefore*
```

This doesn't fully add the functionality that I was suggesting since the header line can't easily be styled differently, but I personally do not need anything other than what is currently implemented.
