### ISSUE TITLE
Can't run a custom script

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#629]
I've tried to create a custom script to pre-process my text, but I can't get it to work.

Originally I wrote a [python script ](https://github.com/sillsdev/ptx2pdf/files/8196390/script_verse_numbers.py.txt), but when I tried to load it into ptxprint I got the error:
```
PTXprint Version 2.1.5
Please send to: ptxprint_support@sil.org

Traceback (most recent call last):
  File "ptxprint\gtkview.py", line 1016, in onOK
  File "ptxprint", line 204, in doit
  File "ptxprint\runjob.py", line 270, in doit
  File "ptxprint\runjob.py", line 270, in <genexpr>
  File "ptxprint\runjob.py", line 395, in dojob
  File "ptxprint\texmodel.py", line 1065, in convertBook
  File "ptxprint\texmodel.py", line 1018, in runConversion
  File "ptxprint\runner.py", line 39, in checkoutput
  File "subprocess.py", line 424, in check_output
  File "subprocess.py", line 505, in run
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
OSError: [WinError 193] %1 is not a valid Win32 application

<class 'OSError'>: [WinError 193] %1 is not a valid Win32 application
```

I have python in my Windows path, so I would have expect ptxprint to recognize this and use that to run the script. Anyway, I then created a [batch script](https://github.com/sillsdev/ptx2pdf/files/8196398/script_verse_numbers.bat.txt) to call the python one (as you'll see from these files, my programming skills are very rudimentary and I don't really know anything about batch). I then got this error.
```
PTXprint Version 2.1.5
Please send to: ptxprint_support@sil.org

Traceback (most recent call last):
  File "ptxprint\gtkview.py", line 1016, in onOK
  File "ptxprint", line 204, in doit
  File "ptxprint\runjob.py", line 270, in doit
  File "ptxprint\runjob.py", line 270, in <genexpr>
  File "ptxprint\runjob.py", line 395, in dojob
  File "ptxprint\texmodel.py", line 1065, in convertBook
  File "ptxprint\texmodel.py", line 1018, in runConversion
  File "ptxprint\runner.py", line 39, in checkoutput
  File "subprocess.py", line 424, in check_output
  File "subprocess.py", line 528, in run
subprocess.CalledProcessError: Command '['D:\\Documents\\UP\\Computer\\python programs\\script_verse_numbers.bat', 'D:\\Documents\\UP\\My Paratext 8 Projects\\GJU\\72SIRGJU.SFM', 'D:\\Documents\\UP\\My Paratext 8 Projects\\XXX\\local\\ptxprint\\2021\\72SIRXXX-conv.SFM']' returned non-zero exit status 1.

<class 'subprocess.CalledProcessError'>: Command '['D:\\Documents\\UP\\Computer\\python programs\\script_verse_numbers.bat', 'D:\\Documents\\UP\\My Paratext 8 Projects\\XXX\\72SIRXXX.SFM', 'D:\\Documents\\UP\\My Paratext 8 Projects\\XXX\\local\\ptxprint\\2021\\72SIRXXX-conv.SFM']' returned non-zero exit status 1.
```

Am I doing something wrong, or will it not accept a batch or a python script? Is there documentation on custom scripts? I've searched the repo and can't find much, other than an issue which gave me a little of the syntax for arguments which I tried.

**Comment by markpenny** [comment]
Thanks to a clever 1st line snippet, this approach works fine for me (in Windows):

1. Create a **.bat** file with the python script embedded within it:
```
@echo off & python -x "%~f0" %* & goto :eof

import sys
with open(sys.argv[2], "w", encoding="utf8") as outf:
    with open(sys.argv[1], encoding="utf8") as inf:
        for l in inf.readlines():
            outf.write(l.replace("a", "A"))

```

2. Select that script/batch file on the Advanced page

![image](https://user-images.githubusercontent.com/12962708/157398417-85a85777-10cd-4ee8-8163-11c5a3ebe2cd.png)

3. Note that you can Edit it in the View+Edit pane if needed

![image](https://user-images.githubusercontent.com/12962708/157397455-7e9016a8-a66f-4729-9754-a906918a3072.png)

4. Hit **Print** 

5. The effect of the script (in this case turning a > A) should be immediately obvious:
 
![image](https://user-images.githubusercontent.com/12962708/157398264-9cf8dd79-50b9-4616-ad0c-7b4b92bf1f52.png)

Amazing!

However, I have noticed that we aren't processing the illustration captions (as they're already in the PicList file)

**Comment by mnjames** [comment]
The idea of embedding the python code inside the .bat file is very elegant, and I'll definitely do that when I get things working. Sadly, I'm running into the same problem.

To try to narrow down the problem, I tried a few different tests. I'm still getting the problem when:
1) The .bat file is in the root of the c:\\ drive (so there are no spaces in the path)
2) I'm running the file on a test English project, not just my more complicated RTL projects.
3) A .bat file as simple as `echo malachi`, or yours, or mine with the python code embedded.

Also, I know the .bat file is good because if I manually run the following in the CMD terminal, it works:
```
script_verse_numbers.bat "d:Documents\UP\My Paratext 8 Projects\zEngTest\42MRKzEngTest.SFM" "d:Documents\UP\My Paratext 8 Projects\zEngTest\local\ptxprint\Default\42MRKzEngTest-conv.SFM"
```

I'm still getting an error which is basically the same as the one in my OP.

**Comment by markpenny** [comment]
Argh! My initial enthusiasm has come back to reality... You are right - I was only able to make it work for myself in the uncompiled version. When I run the .exe version I'm getting the same error that you see. So at least we can now replicate and track down the cause.

**Comment by markpenny** [comment]
@mnjames Please check if this is now working for you. Note that you do not need to wrap a python script in a .bat file. It should just work as a .py script.

**Comment by mnjames** [comment]
I tested both a .bat and a .py file and both worked great. Thank you!
