### ISSUE TITLE
How should heading lines be let off baseline grid?

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#63]
At the moment, if, say a \mt has a large font and a narrow column (or it's just really long), 
then the line-spacing is very cramped (as it's set to use \p's baseline).
This is a real issue on diglot setting, as both texts will want their \mt displayed next to each other.
 
A two line addition can apply the baseline to headings, but, surprise surprise, would probably make pagination changes to every single typeset page in a book. (prompting rampaging hordes of typesetters armed with pitchforks, and/or beautifully typeset letters of protest :)  Should it be:

- a global change, (on the basis that the stylesheet can be altered to put it back if desired)
- turned on in the diglot code, where it's met most frequently
- controlled by some other on/off boolean?
- Controlled per-marker (a bit like \Paragraphednotes)?
- something else

Without the fix:
![withoutfix](https://user-images.githubusercontent.com/58848232/82259257-ef127e00-9963-11ea-8d25-0df721107210.png)

With the fix:
![withfix](https://user-images.githubusercontent.com/58848232/82259254-ee79e780-9963-11ea-9efe-7a4c77c59f03.png)

**Comment by mhosken** [comment]
I don't think this is a question of forcing the grid. Headings are already taken off the grid and the grid resumed after a heading block. It's a question of setting a linespacing for a particular marker. There is a \LineSpacing control in .sty that isn't being acted upon yet in ptx macros. Perhaps we should get that working (you can set the baselineskip using a start hook, so all we need do is set the baselineskip and default it to some general parameter in the .tex file.

**Comment by davidg-sil** [comment]
Urm, what's the difference between a marker's \LineSpacing and \BaseLine (already in the TeX code for footnotes, pic and my 2 line patch)? Is it that \LineSpacing relative to \BaseLine an absolute?

**Comment by mhosken** [comment]
There is no difference whatsoever:
```
\let\LineSpacing\BaseLIne
```

**Comment by davidg-sil** [comment]
OK, I've pushed my 2 line patch, baseline for headings (as calculated or supplied in .style) is now applied to the master branch.
