### ISSUE TITLE
Ability to specify (TeX) plugins

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#636]
(related to  #497, and a recent [community post](https://community.scripture.software.sil.org/t/diglot-on-facing-pages-single-column-per-page/2936) )

We have a plugin mechanism on the TeX  side of things. Because of how they need to work, any requested plugins need to be specified by TeX code like this:
```
\def\pluginlist{polyglot-simplepages,ornaments}
```
**BEFORE** the `\input{paratext2}` line. (comma separated list with no spaces).
The ornaments plugin is 'simple' enough that it works if included via the `ptxprint-premods.tex` file, but the polyglot-simplepages plugin is not.
Thus at present the only way a user can use the UI and the features enabled by the simplepages plugin is to generate the .tex file via ptxprint and then hand-edit it to include the above line, and run XeTeX from a command line.
It would be really great if there were some way to populate that line!

**Comment by markpenny** [comment]
@mhosken Am I mistaken in thinking this should be almost trivial to do? I could either:

a) put a label and **textbox** on the Advanced page allowing users to type in one or more plugins
    or
b) we keep a bit more control and have a **couple of checkboxes** on the borders and tabs page (1 for each of the known plugins).

Later on we might want to be more fancy and have a drop-down list with available plugins with checkboxes beside each, and perhaps have parameters etc. But for now [at least for the thin end of the wedge] either of the above should be OK, right? Any preferences?

**Comment by davidg-sil** [comment]
Exactly, it's a trivial challenge for a python-programming UI person, which would vastly simplify things (see the 10 step work-around in the [community post](https://community.scripture.software.sil.org/t/diglot-on-facing-pages-single-column-per-page/2936) )

**Comment by mhosken** [comment]
My struggle us not with there being a UI element, but how to stop them
proliferating. Are we going to needx one per plugin? Do plugins really have
to load before paratext2 loads? What about plugins that need to load after?
What is an appropriate abstraction for dealing with complex borders? What
is the UI abstraction for polyglot, even if two languages?

And so on. But I need to concentrate on getting training out for this next
week. But happy to think about these things after that.

**Comment by davidg-sil** [comment]
A belated answer to MH's questions:
As a minimum, a single text field would allow multiple plugins to be selected. All it needs is a comma-separated list. 
The plugin control file allows dependencies / load order to be specified, so all the user needs to do is type correctly and not add any spaces. As plugins are expected to be for rarely-used features, configuring most plugins should be expected to be by tex file and styles sheet, etc.

Yes. Some plugins (e.g. diglot-simplepages) need to load in the middle of paratext2.  Things like setting up new columns make use of macros that become aliases to macros/primitives  that are `\outer` and thus once those aliases are defined  they become 'protected' by TeX's  'Knuth/someone thinks you've no possible reason to using this here, you must have a corrupt file, there's no way you'd use it in this place' errors.  
Refactoring to pollute the TeX namespace some more would, I guess, be another option.

I don't grok UI abstraction beyond a text editor. sorry.
