### ISSUE TITLE
Remapping input files

### ISSUE THREAD

**Issue by mhosken** [sillsdev/ptx2pdf#637]
When we create an archive, some files are moved from their original locations relative to the .tex file created. For example, border images are moved from an absolute location to somewhere in the project tree. We do this by analysing the user's configuration and moving things around and creating an archive specific configuration file that points to the new locations.

The problem is that there are more and more places where arbitrary files may be pulled in by the TeX. For example, sidebar graphics or arbitrary trigger files and the like.

My suggestion is twofold. Firstly, we have TeX output something clearly parsable into the .log file that indicates that TeX loaded an external file and from where. Secondly, the archive creation code parses this log file and from that has an understanding of every file that is loaded and from where. It can then find those files to include in the archive. In addition, it can create a map from the old location to the new location. This map file is used by the TeX macros to remap the original filename to the archive specific filename.

The types of files that we can monitor and map are:
- \input texfiles
- \XeTeXpdffile pdf files
- \XeTeXpicfile image files

Unfortunately we can't do this for fonts :(

**Comment by markpenny** [comment]
@mhosken - Until I hear otherwise, I'm assuming this *is* fixed now. Closing...
