### ISSUE TITLE
Table is failing (like maybe no tabs are being used?)

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#638]
v2.1.9
I've not changed anything on my part, but now the "read through the Bible in a Year" section is corrupted.
I'm not sure when this started, I only now just tested it after not testing it for several versions.

![image](https://user-images.githubusercontent.com/65363206/159130820-d05fe1eb-4077-479c-8cbe-aa6db119097d.png)

Here is a screen shot of the SFM: 

![image](https://user-images.githubusercontent.com/65363206/159130884-0808372c-dd2a-4a8e-ba4e-4369f1c179c9.png)

This configuration does use the "ptxprint-mods.tex" file with this in it:

% This is the .tex file specific for the SLU project used by PTXprint.
% Saved Configuration name: SelaruNewPublication
\TOCthreetabfalse
% \clubpenalty=0
% \widowpenalty=0 
\NoteCallerSpace=0.0em
% \noteRag=0pt plus 2fill

I'm not sure what **\TOCthreetabfalse** is all about. As best as I can remember, these are things you all recommended I put in at some time or other for some particular glitch. I'm wondering if I need any of these now.

Removing the \TOCthreetabfalse key did NOT change anything, still messes up the table.

**Comment by mhosken** [comment]
For styling tables we encourage the use of \ztablecategory|fred\* and the use cat:fred|tc1 etc. for styling the cells in the table.

**Comment by davidg-sil** [comment]
TOCthreetab is part of the thumtabs mechanism. It uses the `\toc3` abbreviation text for thumbtabs. I wholeheartedly agree that tables ought to work sensibly without any special styling.
