### ISSUE TITLE
The TOC is not paying attention to the order of books as listed in the Multiple Book selection list 

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#639]
PTXprint v2.1.9
Here is a screen shot of the test results of a few books and back matter:

![image](https://user-images.githubusercontent.com/65363206/159131401-0eb01140-13f4-405e-8188-1d9715072319.png)

Compare the Bookmarks list on the left with the TOC that is printed on the right.
The PDF Bookmarks show that the PDF was produced with each "book" in the order I selected.
But notice that NONE of the back matter books are listed in the TOC in the correct (i.e. actual) printed order. (You can also verify this by looking at the page numbers.) 

Here are the selected books in Basic "Multiple Books" Option: 

INT 1JN 2JN 3JN OTH TDX XXB GLO BAK XXE

**Comment by davidg-sil** [comment]
PTXprint makes a variety of toc lists available. One of them (`main`, I think) is in 'printed order', others are in various other orders, segregated into NT and OT, etc. I'm guessing that you've selected one in a standardised or sorted order. 

If you look in the `ptxprint-PTPROJECTconfiguration.toc` file with a text editor you'll see all the options that are available. They might be listed in a tool-tip somewhere too, but I've not found it.

**Comment by markpenny** [comment]
Here is a list of options (also for sorting) the Table of Contents:

![image](https://user-images.githubusercontent.com/12962708/161353168-5cd5e34c-171c-47b8-b1ad-470c9e50326f.png)

Note that there are some strange things happening with sorting, especially **pre** and **post** at the moment.

@davidg-sil said: 

> ... all the options that are available. They might be listed in a tool-tip somewhere too, but I've not found it.

It would be nice to include this info somewhere within the program, but where? The FRT is just another text file being edited in the generic text editor. Maybe it needs to go on the Table of Contents tooltip (which currently has nothing) on the Peripherals tab.
