### ISSUE TITLE
Paragraphed footnotes - uneven layout

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#64]
When I use the paragraphed footnotes (recommended) option, it gives some not so impressive layout:

Some paragraphs, some not paragraphs?
![image](https://user-images.githubusercontent.com/14953913/82300247-7684df00-99ae-11ea-842c-270cea1604cb.png)

Verse number at end of line:
![image](https://user-images.githubusercontent.com/14953913/82300301-8997af00-99ae-11ea-8912-330f6b23284d.png)

**Comment by markpenny** [comment]
Yes, I've noticed some of these things myself and I'm not yet sure what is causing them.
![image](https://user-images.githubusercontent.com/12962708/82302333-15bdcc80-99d7-11ea-99a9-6d2809eba1af.png)
My earlier understanding was that a footnote doesn't start on the same line unless it fits on that line. But clearly that's not the case all of the time. There must be some other reason/penalty being invoked.

As for the 3.2 (in your screenshot) and 3:14 in mine, we clearly need to stop that from happening.

I notice that in your 2.1 "1 Samiyel" is split from 16.1 and that certainly shouldn't be happening. Thanks for finding that bug. I've found out why it was happening, and have fixed the missing '.' (it was only searching for ':' as the ch-vs separator).

**Comment by davidg-sil** [comment]
The cause: 
\def\internotepenalty{-10} (default configuration value)
Thus tells the code that while it can make paragraphs, breaking the paragraph just before a new a footnote is much better than breaking the line in any normal place. It couldn't do all the notes in less than three lines and it gets a nice bonus score for breaking it before the footnote, so it does.
The solution:
\def\internotepenalty{5} or some other number (you may need to tweak it). If you increase too far,  then it'll prefer to hyphenate a word than break there , which probably isn't what you want. 
(This needs to go in a .tex file, not in the .usfm)

**Comment by mhosken** [comment]
\internotepenalty of -10 isn't that bad. It's a juggling act. The ideal would be to say: either break here or at least 1inch further on, but not in the next inch. But you can't do that in TeX. I've fiddled around with the footnotes some and I think things are much better. We'll see. And that's without changing the internotepenalty. So we do have somewhere else we can play if needbe.

**Comment by markpenny** [comment]
@jeffheath-sil Please give 0.6.7 a try and let us know if you think it is handing the paragraphing of notes adequately now. If not, then re-open this issue.

**Comment by jeffheath-sil** [comment]
Current settings are much better. Than you!
