### ISSUE TITLE
v2.1.10 weird BAK picture problem

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#641]
I've had problems with getting maps and pictures to display properly in BAK since PTXprint started, but I figured it was a low priority. But now that the main text is working really nicely (for most of us!), now I figured is a good time to bring up the issue I'm seeing in BAK.

Here is a snippet of the BAK file's SFM: 

\b 
\m \fig Hulasokwe Seike ti kyoat Yesuske imin ti lasmyer khaha ne|alt="The Temple of God" src="LB00250B.tif" size="col" ref="Luk. 4:9"\fig* 
\pc \xt Luk. 4:9\xt* 
\b 
\m \fig Nus o hnu ti lasmyer Palestinake|alt="The cities and towns in the land of Palestina" src="Holy_Land_BW-Selaru.tif" size="col"\fig* 
\pc Tnyetak Harharkwe 
\b 
\m \fig Saulus yor Barnabas wait laklakut mamunake ne|alt="Paul and Barnabas' journey 1" src="Paul1-BW_Selaru.tif" size="col"\fig* 
\pc \xt Kis. 13–14\xt* 
\b 
\m \fig Paulus wasi laklakut a kla-ruake ne|alt="Paul's journey 2" src="Paul2-BW_Selaru.tif" size="col"\fig* 
\pc \xt Kis. 15–18\xt* 
\b 

As far as I can tell (and PT can tell), these are all well formatted \fig links.

But when I Generate the BAK final SFM in PTXprint, I see this: 
\b
\m 
\pc \xt Luk. 4:9\xt*
\b
\m 
\pc Tnyetak Harharkwe
\b
\m \zfiga|.3\*
\pc \xt Kis. 13–14\xt*
\b
\m \zfiga|.4\*
\pc \xt Kis. 15–18\xt*
\b

NOTE: the two empty \m fields with no \zfiga|.* codes.
Why is that? What can I do to get PTXprint to see these other pictures in BAK? (SAB sees the pictures and formats them in the app just fine.) Thanks.

**Comment by davidg-sil** [comment]
What PTXprint *should* have done is strip those images out, and add them to the piclist.
It should have replaced the image with a properly formed "figure anchor" milestone. e.g. `\zfiga|somekindofid\*`
It looks like its given you a mangled milestone instead.  `somekindofid` takes the place of chapter.verse in the piclist.

So hopefully your piclist should have a picture anchored at `BAK .4` etc.
But those milestones ought to be fixed.

**Comment by davidg-sil** [comment]
For the record, (and while we're waiting for @markpenny or @mhosken to fix the python code), there are various ways you can anchor images, e.g. to paragraphs, \k Glossary Entries\k*, etc.  and you can enter images within PTXprint without ParaText ever knowing anything about them. It is certainly annoying that PTXprint is removing them without leaving something **valid** in their place. [The documentation](https://github.com/sillsdev/ptx2pdf/blob/master/docs/documentation/figures.md#anchor-references) about possible anchors is still up-to-date.

**Comment by mhosken** [comment]
An archive really helps us to debug things.

**Comment by markpenny** [comment]
@davidc86 Is this still an issue? Or has it been fixed now? Please also try out the Booklet feature on the Finishing tab to see if it does what you need it to do.

**Comment by davidc86** [comment]
Yes, this is still an issue, see #732 for a complete rundown on the current state of this problem. 

The BOOKLET feature now works for what I need! Nice, thank you.
