### ISSUE TITLE
Error involving figures, I think; print fails on XXA containing a module

### ISSUE THREAD

**Issue by KimB2017** [sillsdev/ptx2pdf#646]
In the attached archives (same project, 2 failures at different points) the Gen22 Module in XXB works great. The Gen+Exo Module in XXA was working great, too, last Friday, but it is broken now. The error message suggests unticking some items on the Advanced tab, but this does no good.
![image](https://user-images.githubusercontent.com/25071218/161522596-f2b2dee0-7c59-405c-acff-0650b57c59d6.png)

The only way I can get it to print at all is to untick "Include Pictures", print without pics, and then enable Pictures again. This appears to delete some of my Figure settings (scale, copyright); however, the vertical and horizontal positions are still in ptxprint; . After doing this, I can Print the book (but all the pics are at 100%. So I start from the top tweaking the Scale and adding the copyright line. 

It is repeatable, but the error does not always occur with the same picture.

**Archive_XXA-failure-1** 
I set the first pic, clicked Print and it worked. Then I set the second pic and it gave the error you can see in the log. I created the archive at this point.

**Archive_XXA-failure-2**
I reset the pics as per above and tried again. This time I successfully set the pics through page 9. Then the error happened after I set scale on the snake pic on page 10. At this point I created the second attached archive.

Can you see what is going wrong? I'm getting a bit desperate; I'm supposed to demo this on Thursday (it's Monday night here now).

[TTCBks22-BookWPicsKYXPTXprintArchive_XXA-failure-2.zip](https://github.com/sillsdev/ptx2pdf/files/8408683/TTCBks22-BookWPicsKYXPTXprintArchive_XXA-failure-2.zip)

[TTCBks22-BookWPicsKYXPTXprintArchive_XXA-failure-1.zip](https://github.com/sillsdev/ptx2pdf/files/8408671/TTCBks22-BookWPicsKYXPTXprintArchive_XXA-failure-1.zip)

**Comment by mhosken** [comment]
When was "last Friday"? What version were you running? What version are you running now?

**Comment by davidg-sil** [comment]
TeX code included in the archive looks like 2.1.12

**Comment by davidg-sil** [comment]
OK. I've found out why it's crashing: There are multiple lines in the copyright text of the piclist. The piclist format uses one line per picture, and it cannot interpret something that splits the copyright text onto multiple lines.

**Comment by davidg-sil** [comment]
Running an updated version of ptxprint on the archive seems to 'fix' the problem by trashing the copyright statement and everything that comes after it, which includes the `scale="0.65"`, etc, which is probably why @mhosken couldn't replicate the issue.
