### ISSUE TITLE
2.1.13 Fails with error

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#647]
Just downloaded 2.1.13 to test the changes for Front Matter illustrations, and I get this:

![image](https://user-images.githubusercontent.com/65363206/161550615-12185794-afeb-42c8-b35f-bcd84d47d358.png)

So I cannot getting any output now.

[SLU-SelaruNewPublicationPTXprintArchiveFRTissue.zip](https://github.com/sillsdev/ptx2pdf/files/8410010/SLU-SelaruNewPublicationPTXprintArchiveFRTissue.zip)

**Comment by davidg-sil** [comment]
Bother. Quick suggestion: try putting `|intbible` or similar. at the end of (all) `\periph` lines. I obviously failed to test the code it without that bit. Will work on a fix later today.

**Comment by davidg-sil** [comment]
Good news... it looks like the work I was doing yesterday fixed this bug.

**Comment by davidc86** [comment]
It no longer fails with an error.
