### ISSUE TITLE
2.1.13 Does not remember the state of the "Only Show Active Books" option on the Picture tab 

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#650]
I almost never want to see the pictures from books NOT in the current publication we are working on.
So, I have to click the "Only Show Active Books" every time.
Is it possible for the Config file to save the state of this option?

(I'm pretty sure it is more confusing to see pictures from Genesis, when a person is working on a publication of the Gospels, than the more remote chance that a user will wonder what happened to their pictures from Genesis while working on a publication of the Gospels.)

**Comment by KimB2017** [comment]
Yes, please. It seems like it would be helpful either to save the state of this option or to make "Only active" the default.
