### ISSUE TITLE
Complete scalability on a single factor

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#651]
I'm passing on this **enhancement request** from an experience typesetter in Asia:

I know this may sound too innovative, too far ahead of the pack, but after going around and around in a dance with the XYZ team to find the best font size and leading, I've come to the conclusion that we're actually talking about font size and leading wrong. Putting them both in absolute terms, like "10.7 pt font size with 15.08 pt line spacing", made it very difficult to get meaningful comparisons between the array of samples they needed to consider. It finally worked when I described things in terms of the ratio between font size and leading. While there are multiple ways to do this, I believe the most intuitive is like this: "This sample is at 10.7 pt font size, with line spacing at 141% of that." Talking about line spacing as a ratio enabled us to give meaningful comparisons with other publications, and helped the team to accept a more aesthetic line spacing than their original specs called for.

What if PtxPrint provided a mechanism to specify one setting in terms of the other? For example, if there were an option to specify base line spacing in terms of its ratio to the base font size (e.g. Scale factor 1.41), changing the font size would automatically adjust the line spacing. Advantages:

Generating a variety of samples is simpler for the typesetter, as there's just one setting to change to scale the entire publication. PtxPrint has already done all the heavy lifting of specifying all other settings in terms of scale factors. It's already everywhere except between font size and leading.

Typesetting training can give more-easily applied guidance. e.g. "Generally, when typesetting with Annapurna SIL, the ideal line spacing is close to 140%. Using 133% will be so tight that it affects readability, while 150% will use more paper than necessary."

Even experienced typesetters sometimes stray too far from the ideal (as you saw I had), and having line spacing in relative terms helps us to recognize when this happens.

The "fine tune line spacing" button could just as easily suggest the perfect scale factor as it currently does with the absolute point size.

As far as the GUI is concerned, perhaps toggling a checkbox determines whether the Base Line Spacing setting contains an absolute point size or a scale factor, and converts the setting accordingly. e.g. If Base Font Size is 10.0 pt and Base Line Spacing is 13.0 pt, and you check the "Scale factor relative to font" box, the line spacing setting changes to 1.300, and can be adjusted from there. e.g. Fine tuning may make it 1.314

This idea may seem a little out of the box, but the more I think about it, the more useful I think it will be. What do you think?

**Comment by mnjames** [comment]
I like this idea. In a lot of ways it seems like this functionality is already there for almost everything _except_ for the base line spacing... in Styles you can scale font sizes (and line spacing) all relative to parents. So it seems natural to extend it to the base line spacing.
