### ISSUE TITLE
No pictures when printing from Module spec (not loaded into an XX book)

### ISSUE THREAD

**Issue by KimB2017** [sillsdev/ptx2pdf#654]
V 2.1.15--No pictures are displaying when I select Module ... on the Basic page of ptxprint. The pics show up fine when I print from the XX book with module loaded.
[TTCBks22-BookWPics_tpiPTXprintArchive_noPicsInModulePrint.zip](https://github.com/sillsdev/ptx2pdf/files/8447313/TTCBks22-BookWPics_tpiPTXprintArchive_noPicsInModulePrint.zip)

**Comment by markpenny** [comment]
Note that this issue is related/similar to #652

**Comment by davidg-sil** [comment]
Similar to, but distinct.:
*  I'm not seeing any `\zfiga`s in the final SFM
* The final SFM has `\id MOD` while no figures have been added to the piclist for that.
Basically it appears as if the `\fig` lines have been totally ignored.
Datapoint that might help python debugging.. : If I modify the module to put in a `\p`  before the `\fig`, then the `\fig` is not deleted.  However, it is getting passed through complete with the original `.tiff` extension, which XeTeX can't handle so there is still no image in the  output.

**Comment by KimB2017** [comment]
It's true–I hadn't noticed that no pics were added to the piclist for the MOD file. The Generate (piclist) button doesn't even do its normal thing of asking if you want to generate all or just "current book".

[https://github.com/sillsdev/ptx2pdf/issues/628](url) also has to do with printing from the MODULE option–paragraph style of referenced verse range is ignored. I dunno if these are related but maybe they could be?

**Comment by markpenny** [comment]
@KimB2017 I'm hoping that a relatively recent fix for finding \fig markers in peripheral books will fix this issue as well. Please could you re-test and let us know...

**Comment by markpenny** [comment]
@KimB2017 Any update on this one? Could you confirm whether it is fixed now?
