### ISSUE TITLE
Embed the settings used to create the PDF within the PDF itself 

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#657]
By embedding all the config settings (as a zipped blob) within the PDF, it will be possible to re-create the exact same config at a later date just by having access to the PDF.

**Comment by davidg-sil** [comment]
Especially combined with the SHA of the git commit... :-)

**Comment by markpenny** [comment]
Yes indeed. And I think that is already stored in the PDF now, as well as in the .cfg file.

**Comment by mhosken** [comment]
This is done, now what do we do with them once they are in there?

**Comment by markpenny** [comment]
@mhosken - we need to be able to import them into a NEW config (even in a different project, but preferably where the user sets the name of the config being created). [But what if they want to update an existing config? Do we do the whole merge routine etc.?] Non-urgent. Just very cool when it becomes possible!
