### ISSUE TITLE
Ability to search the tooltip help text

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/ptx2pdf#660]
Often I know there is a capability in PTXprint, but I don't know where to find it. It would be nice if I could do a search and maybe it would find the keyword(s) I'm looking for in the tooltip help or in a text label and could point me or link me to where I need to go in the tool to do that thing.

**Comment by mnjames** [comment]
I've mentioned this in the past, but probably never formally written it up. So this is my "second" on this request.

What I envision is something that mimics the search box in PT--where when you search for a term and then click on the results, it will open whichever dialogue or tool you clicked on. In ptxprint at the very least it would be nice if it jumped to the appropriate tab, but would be even nicer if it flashed color or something to show which area of that tab included the tooltip that it had found.
