### ISSUE TITLE
Copying configs to projects for a diglot doesn't copy the font settings.

### ISSUE THREAD

**Issue by Ben-Pehrson** [sillsdev/ptx2pdf#662]
I'm using version 2.1.17

After copying the configs from the aArp and aArpBT projects to the cWol and cWolBT projects, using the "overwrite with recent changes" option, the font selections do not copy.

**Comment by Ben-Pehrson** [comment]
I also tried copying the configs from aArp and aArpBT using the "Do NOT Replace Existing Config" after deleting the recently copied configs in cWol and cWolBT with the same name, but this worked for cWolBT but not for cWol. In the cWol project, no config was produced.

**Comment by markpenny** [comment]
Hi Ben. I'm not yet able to replicate the bugs that you have discovered, BUT there definitely are errors in the way that it is currently working. We'll look into it and get back to you soon. Thanks for helping us discover the shortcomings.

**Comment by Ben-Pehrson** [comment]
I'm using 2.1.19 now, and font settings copied from a base project are now being preserved. I'm making sure that when I copy a config, the identically named folder from a previous attempt must be manually deleted first, and then I use the "Do NOT Replace Existing Config" option. This seems to be preserving all the config settings fine then.
But I'm still experiencing funny behavior when I try to adjust the first line indent and the raised verse numbers.
