### ISSUE TITLE
"Failed to create" error

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#664]
Without changing anything on my end, both v2.1.16 and v2.1.17 of PTXprint give this error:

![image](https://user-images.githubusercontent.com/65363206/165965710-3e59f8c8-fb3e-45fa-9562-dc2ddd50c8d3.png)

Not sure what the issue is. Any ideas?

(You probably want an "archive" which I've created, but the Help page says "...and send it to them" without actually saying how to send it to them. I can send it to you via this GitHub page (if the zipped file is not too big), but for "normal" users? What is the suggestion for them? It isn't clear from the Help page. Maybe the phrase "send it to them" should be a hyperlink to a place where the user can drop their archive?)

Here is an archive of the current project:

[SLU-SelaruNewPublicationPTXprintArchive.zip](https://github.com/sillsdev/ptx2pdf/files/8591566/SLU-SelaruNewPublicationPTXprintArchive.zip)
 
NOTE: Odd that the error message itself says it is PTXprint v2.1.16-10-gda4e92b9, when this heading says it is v2.1.17.

**Comment by markpenny** [comment]
For future convenience, here's a [Google Drive "dropbox" for PTXprint Archives](https://drive.google.com/drive/u/6/folders/1S63WeFUg96ZdlA5IdS4E3AI7kC3HaxUo).

I think this was fixed in 2.1.18 or later. Could you confirm if that is indeed the case...

**Comment by markpenny** [comment]
@davidc86 I can confirm that the bug (related to pictures in the BAK book) is still around. We'll look into it.

**Comment by davidg-sil** [comment]
I think I've fixed this in the github code. It was one of those "something's using this wrong" (unexpected expansion order) weird TeX errors where the code is perfectly fine until something changes in a totally different place.
