### ISSUE TITLE
Diglot tab Gears auto calculate runs maybe once and progress bar doesn't update

### ISSUE THREAD

**Issue by Ben-Pehrson** [sillsdev/ptx2pdf#665]
I'm using 2.1.17. When I click the Gears icon on the Diglot tab, it doesn't seem to run more than once, but it's supposed to run 10x or more. It produces a PDF that is drastically unbalanced, which also indicates it doesn't run enough times. I only saw the PDF update once in the process. And the progress bar at the bottom of the window never shows anything.

**Comment by Ben-Pehrson** [comment]
This behavior is still happening with 2.1.19

**Comment by Ben-Pehrson** [comment]
I just started training a teammate on PTXPrint today, and this behavior did NOT happen on his computer. He had a fresh install of 2.1.19, and I walked him through the same steps I have been doing to produce our diglots, but with different projects. So I'm not sure what the difference is. Afte looking at PDFs, he had manually adjusted the Percentage of Page Width slider to 51.9 and then after clicking the Gear button, it ran through it's calculations and produced a PDF with 52.0. So that's the kind of thing I would expect to happen. When I do the same thing on my computer with different projects, I'll adjust the slider to something like 51.6 and then the Gear button doesn't take as long but only spits out what seems to be the first run at something like 40.1 width, and not balanced at all.

**Comment by mhosken** [comment]
One reason the diglot optimiser might bail early is if the rendering of the diglot at that width failed for some reason. Check that the diglot prints fine. Check the end of the XeTeX log for errors. If it doesn't then that is your problem.

**Comment by markpenny** [comment]
@Ben-Pehrson Are we OK to close this issue, or is it still a problem?
