### ISSUE TITLE
Unexpected verse number style change, first line indent, and unable to reverse changes

### ISSUE THREAD

**Issue by Ben-Pehrson** [sillsdev/ptx2pdf#666]
I'm using 2.1.17.
I'm producing a diglot, and I noticed that the verse numbers in the secondary text were not raised as high relative to the text as in the primary text. So I thought I could fix that by clicking the "Switch to Other Diglot Project" in the Diglot tab, going to the Styles tab in the secondary project, and then either adjusting the Tont Size Factor or the Superscript / Raise setting. I tried both, getting unexpected results in the PDF. In those two changes with print jobs in between each, somehow the verse numbers increased in size rather than decreased as I had expected, the verse numbers ended up on the baseline, and the secondary baseline text ended up the same size as the primary text (previously 1.5 pts) different. I only made those two changes, so I attempted to reverse them to the way they were before; however, reversing those settings did not correct the output, and it is producing the same output as I had previous to these two small changes. This suggests that I had made another change previous to these two changes without producing a PDF. 
The last thing I had changed before trying to adjust the superscript verse numbers in the secondary text was the first line indentation. I had mixed results with changing the Base Paragraph Indent of the Primary text. It had been set to 1.00, which was too small. At some point I was successful at changing to to 2.00 which helped. But when I experimented with other values like 1.50, I got messages like this...
Please send to: ptxprint_support@sil.org

PTXprint [2.1.17] - Error!

Failed to create: ptxprint-Base02JBooksWol-1JN_JUDcWol.pdf

! Output loop---300 consecutive dead cycles.
\run@a@trial ...penalty \penalty \endtri@lpen@lty 
                  \relax \relax \let \after@...
\n@xt ...ilht \global \p@rtlsetfalse \run@a@trial 
                  \relax \fi \fi \relax \relax 
\diglot@run@nxt@trial ...rtlsetfalse \run@a@trial 
                  \relax \fi \fi \relax \relax 
\t@mpc@mmand ...@@pcount =1 \diglot@run@nxt@trial 
                  \fi 
\lefttext ->\pr@sideswitch {lefttext}{L}
              \global \allNeedEmptyingfalse \swap@...
l.143 \lefttext
------------------------------------------------------------------------------------------
Oops! Something unexpected happened causing this error.
If you are unable to solve this issue yourself, use the 'Create Archive...' button
on the Help page to create a .zip file and send it to <ptxprint_support@sil.org>
for further assistance. Please include a description of the problem, and if
known, tell us which setting was changed since it last worked.
PTXprint Version 2.1.16-10-gda4e92b9

I don't know why it lists version 2.1.16 at the end there. I actually have 2.1.17 installed.

**Comment by Ben-Pehrson** [comment]
Another thing I had recently changed just prior to the above problems was to try to make the diglot unjustified. I tried doing that in the paragraph settings of the Style tab. But I remember I got an error, so I reversed the change. I see that the error message I posted above refers to "lefttext" so that seems to be the problem. But undoing these experimental changes does not undo the problem. I have the settings back to Justified now, and it's still giving that error.

**Comment by Ben-Pehrson** [comment]
I also saw that in the Style tab, both the Alignment and First Line Indent Factor were bolded, so I clicked on each one of those parameters to reset them to the stylesheet. But no change was made in the parameters, except those are not bolded anymore, and Print still yields the same error as above that ends in "lefttext".

**Comment by Ben-Pehrson** [comment]
Selecting "Justify Paragraphs" in the Body tab finally gets me past getting that error. But I don't want it justified.

**Comment by markpenny** [comment]
Ben, it would be very helpful if you can create an archive for us:

Use the 'Create Archive...' button on the Help page to create a .zip file 
and send it to [ptxprint_support@sil.org](mailto:ptxprint_support@sil.org) for further assistance.

There is also a "[PTXprint archive dropbox](https://drive.google.com/drive/u/6/folders/1S63WeFUg96ZdlA5IdS4E3AI7kC3HaxUo)" on Google-Drive if you prefer to drag-and-drop the .zip file rather than e-mailing it to us.

**Comment by Ben-Pehrson** [comment]
@markpenny I've uploaded the archive zip file to the Google Drive folder.

**Comment by Ben-Pehrson** [comment]
I tried again just now with a clean new config to use the Diglot tab's "Switch to Other Diglot Project" and adjust the style of the verse number in the secondary text. When I made adjustments to the Font Size Factor of the verse number and the Raised value, it worked fine. But it didn't produce exactly what I wanted, so I tried again. But this time, when went to the settings for the secondary project, those things I had just changed had not been saved. And when I tried to adjust them again, this time the adjustments affected the settings of the paragraph marker rather than the verse marker. I can chance the size or raised value in the verse marker, immediately go look at the paragraph marker, and it's value is changed.

**Comment by davidg-sil** [comment]
Sorry you're hitting so many UI issues as well as everything else.  Total guess (I don't touch the UI code at all) it might be that the 'switch to other diglot' isn't updating the screen properly and is leaving you showing one set of data when it thinks it's showing you something else.

@mhosken  The first page of 3Jn  is showing some merging issues, with both strategies as far as I can see (at least, flipping strategy and clicking generate doesn't change it) it's doing: 
```
\lefttext imt, imt2, ip
\righttext, imt imt2
```
When normally the imt bundle stops before the ip.

Regarding the 300 dead cycles, that means it's totally failing to work out how to split the page. I see you've got some very long notes on some pages, and some big pictures too.  Both of those can cause it, especially if they're ending on the same page. Moving a figure anchor, shrinking the image, or making the image full-page are all options that solve such issues.

**Comment by markpenny** [comment]
> I can chance the size or raised value in the verse marker, immediately go look at the paragraph marker, and it's value is changed.

I have come across similar behaviour in the Style Editor, but we can't seem to make it start happening predictably. I have found that when this happens (when it gets into a strange pattern or displaying spurious/out-of-date values for parameters), the only sensible thing to do is close PTXprint and start again. It then behaves right for a while.

If you manage to nail down a predictable way of getting into this state, that would help us find and fix the nasty bug.
