### ISSUE TITLE
Remember latest scope and config for each project

### ISSUE THREAD

**Issue by Ben-Pehrson** [sillsdev/ptx2pdf#669]
I almost never change the scope of the publishing project I'm currently working on, but I frequently move back and forth between different Paratext Projects. It would be great if PTX Print could remember the latest Scope and Saved/Shared Configuration for each project. Then when moving back and forth between projects, it would be one selection rather than four (two clicks rather than seven).

**Comment by markpenny** [comment]
Yes, related to #684
