### ISSUE TITLE
Book names too long for Table of Contents & leader problem

### ISSUE THREAD

**Issue by Ben-Pehrson** [sillsdev/ptx2pdf#670]
I'm trying to format my diglot TOC, and this is what I'm getting...
![image](https://user-images.githubusercontent.com/104610062/166217151-be482615-e391-488d-ad62-1af9ba9a63a4.png)

In the View Edit Front Matter, it's these codes for the T1 part of the TOC... 
\mt3 \zvar|t1contentstitle\*
\ip \ztoc|mainL\*

I was able to change the \mt3 style from centered to left since it looked funny having these long TOC titles centered and being slightly off from each other.

I was hoping I could do something similar to change the font or size of the book titles, but it's a \ip code. We also use that in the text of each book. So I'm not sure how else I might change the formatting of these long book names to help them fit without going to a second line. 

Then there's the leaders. I don't know why the leaders are going beyond the page numbers. And of course the leaders look especially bad when the book name goes onto a second line.

**Comment by Ben-Pehrson** [comment]
Okay, I figured out that I can adjust this style...
![image](https://user-images.githubusercontent.com/104610062/166218963-bec26bce-508e-4b3e-bcc2-1cc884ef3128.png)

And when I changed the Font Size Factor for \cat:toc|tr I was able to get this beautiful result...
![image](https://user-images.githubusercontent.com/104610062/166219429-db9fc94e-5ebb-4100-8c22-5d722ec7acb7.png)

But still the problem with the leaders extending past the page numbers.

**Comment by davidg-sil** [comment]
There's still a bug, in that the table of contents ought to be defaulting to implemented-a-few-montths-ago bottom alighment for columns 2 and 3.
@mhosken , any idea why my bottom-alignment setting isn't getting used? Or has it broken?

**Comment by mhosken** [comment]
send an archive

**Comment by markpenny** [comment]
fixed in 2.1.24

**Comment by markpenny** [comment]
@Ben-Pehrson This should be behaving as you would expect it to now.
