### ISSUE TITLE
Can footnote callers across diglots be identical on facing texts?

### ISSUE THREAD

**Issue by Ben-Pehrson** [sillsdev/ptx2pdf#674]
The way footnote callers are working now in the diglot project I'm working on has each caller sequence following the primary text first and then the secondary text, so parallel footnotes across the columns have different callers. Is there a way to make these parallel callers to be identical such that both would refer to caller 'a' or both to caller 'b' but in their separate columns? Here's what's happening now...
![image](https://user-images.githubusercontent.com/104610062/166338424-8c985180-7386-46b5-80a3-02c89f9752ba.png)

**Comment by mnjames** [comment]
I'm curious how you envision ptxprint knowing the difference between "parallel footnotes", and two footnotes that just happen to fall in the same verse.

**Comment by Ben-Pehrson** [comment]
I'm not the software engineer, so I have no idea how ptxprint would know the difference. But I also don't think PTXPrint would need to know the difference. In the sort of diglot that we're producing, every footnote in the primary text is also in the secondary text, so if they both start and follow the same sequence, then they would match. If they don't match, that would be a problem for a human to fix in Paratext.

**Comment by markpenny** [comment]
I would say that if both the Primary and Secondary projects have footnotes (and Xrefs) set to "**Reset Callers on Page**", then 95% of the time it would be right and match. Occasionally when the part of the verse with the footnote falls on the previous/next page it will be "out of sync" but only for those couple of pages.

**Comment by mnjames** [comment]
It's a manual fix and might take time, but you can set the callers in the secondary project by hand when necessary. Instead of the normal `\f + ...` beginning of the footnote, just replace `+` with whatever caller/letter you'd like.

**Comment by davidg-sil** [comment]
It is possible to have separate counters for the left and right columns. I don't think anyone's asked for that before, but yes, it can be done. But, if footnotes are reset each page, (as opposed to never or each book/chapter), and the footnotes do not appear on identical pages, then the parity will of course disappear.

**Comment by davidg-sil** [comment]
There are diglot options for which separate counters would be undesirable: if the notes are not kept separate (`\diglotSepNotesfalse`) then it would be confusing to have the notes using the distinct counters.

**Comment by davidg-sil** [comment]
Once you have the new code, then adding `\ParallelNoteNumbering{f}` to your `ptxprint-mods.tex` ought to mean that  `\f` notes count the left and right sides separately.  (repeat for {x} {ef}, etc).
Whether this is desirable or not may depend on your use case. If left and right notes are merged (`\diglotSepNotesfalse`), then it is presumed that parallel note numbering is not in the least desirable. 

I've just realised that any resetting of the note counters via a hook may not work, and there should be some more code to help with that by the end of the day.

**Comment by davidg-sil** [comment]
Hmm. Further testing needed. The code isn't working like expected.

**Comment by Ben-Pehrson** [comment]
Thank you! I'll pass this on to my teammate who was asking about this.
