### ISSUE TITLE
Removing ssl from setup.py for develop mode in Jammy

### ISSUE THREAD

**Issue by n7s** [sillsdev/ptx2pdf#676]
on Jammy, having ssl in in install_requires in setup.py prevents python3 setup.py develop to work

**Comment by davidg-sil** [comment]
FWIW, I've had the same thing on 20.04 focal. I think it's probably a bug that it's there, but don't understand python well enough to know for sure.
@markpenny, The git blame says "Mark Penny 2021-12-08 23:31:25 +1300"  Or do we say we were just following Martin's orders?

**Comment by n7s** [comment]
AFAICT that separate ssl module is deprecated/unmaintained and use of the built-in module is what is recommended.

**Comment by davidg-sil** [comment]
I don't know, but I think the external module is not actually used, and that it this just a needless dependency that was part of a change that was  rolled-back, and this is a remnant of.

**Comment by markpenny** [comment]
We've removed this from setup.py for 2.1.21

**Comment by n7s** [comment]
6fc2192 brings back the comma that prevented setup.py from doing its thing
