### ISSUE TITLE
Suddenly it's taking 7-15 minutes to create a PDF

### ISSUE THREAD

**Issue by KimB2017** [sillsdev/ptx2pdf#678]
I haven't used ptxprint for a few weeks. The presentation we did for PNG's Interact Language Workers conference went well, but I haven't heard much about how/whether people are using ptxprint.

Today I need to print a number of Scripture portions for village testing, but it's taking up to 13 minutes to generate a simple double-spaced A4 PDF of John 1-5! This should take just a few seconds, I think; certainly less than a minute. I'm using the saved configurations that I created back in February; the only thing I can think of that has changed has been normal wasta updates and the version of ptxprint... I think. The version I used last in April was 2.1.12 or possibly 13. Today I started with 2.1.19, then I upgraded to .20 to see if it would fix the problem, but both versions are behaving the same way. Python packages are up-to-date; I almost never just fetch a ptxprint update without "updating all". I also tried rebooting the computer with no effect. The computer has 20GB of RAM so that should not be slowing it down. The system is Wasta 20.04.

PT Marker Checks come out clean except for missing verses.

When I click Print, the button turns green and stays that way. I don't see the progress bar moving along. At first I was in a hurry and kept killing the process and starting over, but after seeing a PDF from 3 tries ago pop up I rebooted to clear any backlog, then I hit print and went on to something else. Literally 13 minutes later the PDF appeared! Then I tried just John 3:1-20, which took 6 min to appear. Printing Mark does the same thing. I've tried my various saved layouts, and Default. And printing from a different project is doing the same thing.

Printing an entire book is no different than specifying Single Book (selected chapters) or Multiple books (selected verse range): It just took 7 minutes to print Colossians (clean text), has been printed before with no problem.

I did make sure that "Autocorrect Markers" is unticked, and that the Advanced tab doesn't try to pull in any non-existing control files. Somehow these settings seem not to stick across version upgrades, I think.

My RAM in use is only 20%; the cpu trace shows a lot of action with one at a time of the 8 cores, but "CPU Time" for ptxprint seems low enough, considering I've formatted 10+ books this session.

I've checked settings in Finishing and even tried turning our flaky wifi off. Still having the problem. 
[RTTT-EditingCopy(double-spaced)PTXprintArchive2022-05-06.zip](https://github.com/sillsdev/ptx2pdf/files/8639335/RTTT-EditingCopy.double-spaced.PTXprintArchive2022-05-06.zip)
.

**Comment by Ben-Pehrson** [comment]
Hi Kim,
Do you have PDF Output Format in the Finishing tab set to something other than Screen? When Print is selected, it takes longer to produce, but then the PDF also doesn't pop up on your screen as it is simply exported to a folder. I'm not sure about the other options.
Ben

**Comment by markpenny** [comment]
@KimB2017 You can ignore the email message from MH about sending an archive; aswe've got that (from the link above), BUT we still can't replicate the delay. MH tried in Linux and I tried in Windows, and both systems can generate the whole of John's gospel in under 5 seconds.

If this is still an issue, could you please do the following:

1. Start ptxprint from a terminal with the **Debug** flag on:

`python ptxprint -l Debug`

2. Open the same config and hit print.
3. After it has finally produced the PDF, CLOSE ptxprint
4. Locate the file called **ptxprint.log** (which should be in the same directory you called ptxprint from) and send that log file to us for us to delve into further

**Comment by KimB2017** [comment]
I didn't get back to this quickly because of other jobs, but today I deleted the temporary files via the button on the help page, which didn't help. Then I purged ptxprint and reinstalled 2.1.22, but it's still happening. Here's the log file from starting with Debug. It also happens with all my PT projects, not just RTTT. I don't know if it'll help but I'm planning to reinstall all the dependencies to see if that helps. 

Sure wish I could get back my magical print formatter. And I'm sure glad this didn't happen during our PNG Conference, when I was demoing the program.

Thanks!

[ptxprint-Default-MRKRTTT.log](https://github.com/sillsdev/ptx2pdf/files/8692770/ptxprint-Default-MRKRTTT.log)

**Comment by mhosken** [comment]
Please submit ptxprint.log this is different from the job Tex log file. It
resides in the same directory from which you ran ptxprint -l debug.

GB,
Martin

**Comment by KimB2017** [comment]
Sure enough, it was in my home folder! I thought it must be in the project folder somewhere. I should have trusted your wording :) .
[ptxprint.log](https://github.com/sillsdev/ptx2pdf/files/8692839/ptxprint.log)

**Comment by mhosken** [comment]
It seems that xetex is taking 5 mins to process a 24 page file and the
doing it twice. We've seen this happen in one or two cases where the
paragraph breaker (I'm guessing) gets really busy.

Since you are running on linux, you can see approximately which page xetex
hangs on, if you run ptxprint from a terminal and watch the world go by as
it runs xetex. The trick is to track down the offending probably really big
paragraph and somehow stop xetex from having to work quite so hard on it.

How do you do that? Good question? Are you using hyphenation files? Doesn't
look like it. Or an adjustment list? Ditto. So I'll admit I'm confused.
Especially since when we run it, it runs fine.

What version of Ubuntu are you running? Are you ready to try 22.04? Might
that fix the problem?

**Comment by markpenny** [comment]
@KimB2017 I'm setting this issue to "No action" because (based on your e-mail today) it seems that it is system-specific. But if you ever do figure out what was causing it to behave in this way, then please do tell us about it; it might help someone else in future.

**Comment by KimB2017** [comment]
Yes, I agree with your "no action" conclusion; I'd already
      decided this a while ago, after I first wrote that Steve's
      computer is working fine with the same projects. 
    
    But now I desperately need help getting my ptxprint program back!
      I have written a couple of times asking for advice. Please, can
      someone tell me how to get rid of any possible corrupted settings
      or control files or whatever..., without wiping and reformatting
      my entire computer?
    Thanks! Kim
    
    On 20/5/22 6:27 pm, Mark Penny wrote:
    
    
      
      @KimB2017
        I'm setting this issue to "No action" because (based on your
        e-mail today) it seems that it is system-specific. But if you
        ever do figure out what was causing it to behave in this way,
        then please do tell us about it; it might help someone else in
        future.
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you were mentioned.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/sillsdev/ptx2pdf/issues/678#issuecomment-1132626949",
"url": "https://github.com/sillsdev/ptx2pdf/issues/678#issuecomment-1132626949",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
