### ISSUE TITLE
Headings printing even when "Body > Section Headings \s" is unchecked

### ISSUE THREAD

**Issue by 4etc** [sillsdev/ptx2pdf#679]
Hi,
In v. 2.1.20, even when I have unchecked the option to include section headings, they still are printing to the PDF.

Here are the relevant files (changes.txt, ptxprint.cfg, ptxprint.sty, custom.sty):
[PTXprint_settings_Eric.zip](https://github.com/sillsdev/ptx2pdf/files/8660884/PTXprint_settings_Eric.zip)

The saved/shared configuration I was using was this one: "LETT2columnNoFNsEachV_Sep_NoHead".

I created that configuration trying to get the output mentioned here: https://community.scripture.software.sil.org/t/each-verse-a-separate-paragraph-is-it-possible/3058/2

Thanks!
Eric

**Comment by markpenny** [comment]
Hi @4etc ! It would be really helpful if you could use the Create Archive button on the Help tab/page to send us the configuration. This then includes all the files, settings and (limited) data to replicate the issue exactly. You can also drop it in this issue, or if you prefer in this [PTXprint Archive dropbox](https://drive.google.com/drive/u/6/folders/1S63WeFUg96ZdlA5IdS4E3AI7kC3HaxUo) folder in GoogleDrive.

**Comment by mhosken** [comment]
A full archive needed. When I run a test locally on other data the scripture subheadings disappear but the introductory paragraph subheads remain. Is this what you are talking about?

**Comment by 4etc** [comment]
Hi,@markpenny and @mhosken,

Sorry to be slow getting back to you today. I was unsuccessful at uploading it to GoogleDrive, so here is a link from sync.com: https://ln5.sync.com/dl/cb061bf80/zdr2arnw-qijre7jm-ckkxcwxq-w5d8y9bh

To try to answer @mhosken's question, the output we are looking for is exemplified in the last sample Mark Penny posted here: https://community.scripture.software.sil.org/t/each-verse-a-separate-paragraph-is-it-possible/3058/2

Here is that same image. 
![5179ca6eb309d207b6d55d7b4d222e8b415ce2a6](https://user-images.githubusercontent.com/101527253/167945406-a6ad6634-936a-4384-b308-be74ab62543a.png)

**Comment by markpenny** [comment]
@4etc Thanks for the archive. This helped confirm that we're obviously only checking for \s and not \s1 or \s2 when stripping out section headings. We'll update the program to handle that better in future. But in the meantime, here's an easy way to get what you're looking for:
![image](https://user-images.githubusercontent.com/12962708/167958667-d1e82484-8ed4-49ed-915b-1c3b85615467.png)

BTW, given that you have a long and detailed Copyright statement (along with the licensing information), feel free to DELETE the License text - as it essentially repeats the same info.
![image](https://user-images.githubusercontent.com/12962708/167958835-58d95e78-6156-49e6-a4b8-f07dcafa5e5f.png)

**Comment by 4etc** [comment]
@markpenny
(1) Thank you very much for the tip on how to exclude `\s1`. I had not ventured into that set of options yet. I tried to do that, but I got some really strange output:
![PTXprint_no_s1_unexpected_output1](https://user-images.githubusercontent.com/101527253/168152255-91f759c4-0c0e-4119-90b5-56259e01736a.JPG)

Here is the archive file: https://ln5.sync.com/dl/0716d7ab0/fi86zqrt-ep5twchm-6dsa7pzd-qggstb3w

You said this: `BTW, given that you have a long and detailed Copyright statement (along with the licensing information), feel free to DELETE the License text - as it essentially repeats the same info.` ![image](https://user-images.githubusercontent.com/12962708/167958835-58d95e78-6156-49e6-a4b8-f07dcafa5e5f.png)>
I don't see a way to delete the license text. There is no blank option to select in the dropdown at `Basic > Copyright & Licensing > License`. For me – maybe because I already selected one option – there are four possibilities, but no option to leave it blank.

Thanks!
Eric

**Comment by markpenny** [comment]
@4etc The License drop-down box is actually editable. So you can select whatever is in there and delete it, or type some other custom wording in there.

The original issue (of \s1 not disappearing) has been fixed in 2.1.22 released yesterday. Please confirm and then close the issue.

**Comment by 4etc** [comment]
Thank you very, very much! All is well with this now.
