### ISSUE TITLE
Clicking a style causes program window to resize

### ISSUE THREAD

**Issue by KentSpiel** [sillsdev/ptx2pdf#688]
I need to be able to compare styles to make sure certain parameters are the same. I like to make the style area large so I can see all the  settings. This is difficult to do because when I click on another style the PTX Print window collapses to it's default size and I have to resize it again. 

- Please make it so the program window's size does not change when clicking on a style.

**Comment by mhosken** [comment]
We are confused by your request. Are you saying that you want the twisties to keep their state when switching markers? We don't see the actual ptxprint window changing size. If this is what you mean, then I think this may be asking for ptxprint to read your mind as to when you want this to happen and when not. In most cases switching marker means that we only want the twisties relevant to that marker to be open not the ones for the last marker.

**Comment by markpenny** [comment]
@KentSpiel Are you able to clarify what you mean. See MH's questions above...

**Comment by markpenny** [comment]
A video is worth a thousand words: [Click to watch](https://somup.com/c3iinuuiF6)

**Comment by markpenny** [comment]
@KentSpiel - This has now been fixed in 2.2.4 - just released.
