### ISSUE TITLE
v2.1.27 Footnotes right-justification is weird again

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#691]
![image](https://user-images.githubusercontent.com/65363206/172782331-f6df5f97-c375-4333-8ed1-5c4eb9be9c12.png)

It only seems to be affecting the footnotes on the first page or so. Here is the next set of footnotes in the body of the book: 

![image](https://user-images.githubusercontent.com/65363206/172782680-c4d5df06-648b-4f11-b1f3-966c89ffb89c.png)

But I did see where a footnote from FRT was repeated at once in the intro part of the first scripture book.

Here is the (messed up) footnote from the FRT:
![image](https://user-images.githubusercontent.com/65363206/172783195-9706672c-e9d7-4d05-a464-ea541e44f828.png)

And here it is again showing up in the intro of the scripture book: 

![image](https://user-images.githubusercontent.com/65363206/172783275-e2872a49-99f8-4903-a463-cdf2961ffe78.png)

We don't have a footnote caller in that intro, so I'm not sure why it is showing up again there. 

(Personally I don't want justified text in footnotes, and I had that turned off. But it seems that PTXprint turned it back on.)

**Comment by mhosken** [comment]
Please send an archive

**Comment by markpenny** [comment]
I believe this was fixed in the last version shipped.
