### ISSUE TITLE
v2.1.27 Setting the Sheet per Signature to something other than 0 creates a messed up PDF

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#693]
PTXprint will create a PDF if "Sheets per Signature" is set to 2 or 4 etc. but the PDF file has many blank pages in it. And Acrobat Reader says the file is corrupted. SumatraPDF can show it, but it also shows lots of blank pages.

**Comment by mhosken** [comment]
this is the same bug as #692
