### ISSUE TITLE
Can't select the last search element in the settings search pop-up list

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#694]
In French, some of the settings search elements are pretty long, so there is usually a horizontal scroll bar at the bottom of the list. Unfortunately, that scroll bar prevents me from selecting the last element in the list:

![image](https://user-images.githubusercontent.com/14953913/173602269-806056a8-8950-4b25-a59f-31e2553a1d7c.png)

I'm not sure that just making the pop-up list wider would solve the problem, as there could be arbitrarily long entries. You might be able to add an empty entry at the end of the list? (Ideally only if the horizontal scroll is activated, but even if not, it wouldn't be the end of the world, and you could just turn selection of that empty element into a no-op.)

Latest version, 2.2.1

**Comment by markpenny** [comment]
Good to know that the horiz-scroll bar gets in the way. I'll have a think. In the meantime, I'd encourage you (and others) to use this KEYBOARD-only sequence, which seems to work fine (even for the last row):
1. Ctrl-F
2. Type word (or even just part of a word)
3. Press <Enter>
4. Use the up/down arrow keys to scroll through the list until you find the right item
5. Press <Enter> to jump there

**Comment by markpenny** [comment]
The search widget has been moved and the box that displays the list of items is wider, so hopefully this will be less of an issue going forward. (Note that there have been quite a few UI changes/improvements as we work towards integrating PTXprint into Paratext's menu system. Most of the changes were suggested by the PT UX team.)
![image](https://user-images.githubusercontent.com/12962708/182287156-a141d2ed-5927-4d7b-a8d4-878aedc49bc6.png)
