### ISSUE TITLE
Unable to print PDF of 2CH

### ISSUE THREAD

**Issue by philleckrone** [sillsdev/ptx2pdf#7]
I've tried a couple of different projects and am unable to print 2CH. When I look at the list of output .sfm files they end with 131CH... Here is the zip file of my project. I can select the entire OT and it fails with an error that it can't find 2CH. If I unselect 2CH then the rest of the OT will output to PDF.
![Screenshot 2019-11-20 17 07 48](https://user-images.githubusercontent.com/37958474/69282418-49e73a80-0bb8-11ea-808a-1eae452f03ed.png)
[JAI_ATU 2019-11-20.zip](https://github.com/sillsdev/ptx2pdf/files/3871665/JAI_ATU.2019-11-20.zip)

**Comment by markpenny** [comment]
This has now been fixed. Thanks for finding the issue. It was a typo in the booklist.
