### ISSUE TITLE
How to move the left and right margins for \s and illustration captions

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#70]
I can't seem to get this to work:

\Marker fig
\LeftMargin 0.50
\RightMargin 0.50

I'm wanting to pull the left and right margins in on certain kinds of things (like section headings and captions) so they don't run out to the margin of the page (as this looks bad). Am I doing this wrong?

**Comment by mhosken** [comment]
Margins have no effect on figure captions, only the font styling (size, color, name, bold, italic, superscript) is applied. Captions are always centred below images. Setting margins would not affect the position of figures anyway. This is out of scope for standard scripture typesetting.

**Comment by davidg-sil** [comment]
In the case that there's a long caption but the image-width has been set small, e,g, to (say) span*0.5, might there be a case for setting the caption length to the width of the image?

**Comment by markpenny** [comment]
My only comment on the captions is that if they _do_ have to wrap, it would be good to do a "line balanced" wrap (in the same way that \s Section headings get cleverly wrapped onto two lines and try to keep the width of the wrapped lines as similar as possible). I don't know how hard that is to do, but if it is already happening for \s I would hope that it can be done for the captions too.
**my very long section heading
gets wrapped like this**
_my very long caption for an illustration strangely gets wrapped
like this (ch:vs)_
And I would prefer if it tried to balance the lines better.
_my very long caption for an illustration 
strangely gets wrapped like this (ch:vs)_

**Comment by markpenny** [comment]
@mhosken Great work again to get captions looking much better. I hope you also notice the difference in multi-line captions @davidc86 Are you still stuck without being able to pull in the margins for \s section headings?

**Comment by davidc86** [comment]
The suggestion for AI based "balanced" wrapping would be better than me trying to guess a margin indention. So I'm all for that. So, I can't tell, but did this enhancement get approved for \s, \s1, \s2, \m, \m1, \m2 (as these are all kind of the same kettle of fish), and also captions? 

What version will have this enhancement in it?

**Comment by davidc86** [comment]
Sweet. Just updated to 0.6.8 and got this: 

![image](https://user-images.githubusercontent.com/65363206/82600073-4b031f80-9b7b-11ea-9a0c-e4f312cd48bf.png)

Which is much nicer than just the "de (1:31)" on the second line! Thank you.

It also automatically fixed many other long captions. 

There was one that was pretty though, yet not long enough to wrap, but it was significantly longer than the picture was wide. So that would be a place where if the indentions were set with some kind of AI wizardry, it might wrap that kind of line as well, since we'd never want a caption to go from nearly margin to margin like regular text. That would just look weird. Something to mull over.

But honestly, for now, what it is doing appears to hit 95% of the needs.

**Comment by davidg-sil** [comment]
I often do somethin like
\def\zobrk{\penalty 0\ }
(in the .tex file. I think it's a 0 anyway,  it might be -1 or -2)
and stick a \zobrk into the usfm at a preferred break point in psalms, for
example, immediately after the previous word (ie no space). It would
probably help your captions too.
That tells tex that if it's got  to break the line somewhere, then here is
almost certainly the place to do it. I prefer it to non-breaking spaces and
other tricks, because it just gives it a hint, without laying down laws
that become inconvenient in other column widths.

**Comment by markpenny** [comment]
USFM defines a discretionary break // which acts in the same way as what you are describing here. And I just checked to see that it works already:
![image](https://user-images.githubusercontent.com/12962708/82695180-3bbac980-9c82-11ea-9cd6-2b34acda31b6.png)
And then when I added the // to the line like this:
![image](https://user-images.githubusercontent.com/12962708/82695377-98b67f80-9c82-11ea-8a49-d6c946a24c54.png)
It made the break where I had requested it:
![image](https://user-images.githubusercontent.com/12962708/82695393-a23fe780-9c82-11ea-91f2-fedabc863398.png)

So can we close this issue now? Or is there still something outstanding?

P.S. I artificially lengthened the section heading to test it (so please don't judge the text :-)

**Comment by davidg-sil** [comment]
Hey, I've never seen that! Excellent!

>
>
>
