### ISSUE TITLE
Adj list too long to get to the yes button at the bottom

### ISSUE THREAD

**Issue by BillDyck** [sillsdev/ptx2pdf#701]
When I click to generate the Adj List for a Bible, the list is too long and the bottom where I am supposed to click to OVERWRITE the above-listed files cannot be displayed. It is below the bottom of my monitor. This is a bug that needs to be addressed.
![long list](https://user-images.githubusercontent.com/109174131/178571831-54f767ef-dbaf-4f69-924a-9861a7c27632.jpg)

**Comment by markpenny** [comment]
Thanks @BillDyck for finding this absurdity for us! I think I'll use ellipsis for the middle items on the list in an upcoming release...
