### ISSUE TITLE
I need to make a ptx into pdf

### ISSUE THREAD

**Issue by deefrmkkw** [sillsdev/ptx2pdf#703]

**Comment by markpenny** [comment]
@deefrmkkw - I'm afraid you are going to have to tell us more if you expect to receive help. **This** is the site for posting issues/errors/bugs. 
But there are a number of helpful links on [the main website](https://software.sil.org/ptxprint/support/). There is also a [PTXprint community site](https://community.scripture.software.sil.org/c/ptxprint/27) which might help answer some of your basic questions. And there are several [training videos on the Vimeo platform](https://vimeo.com/showcase/9331905).
