### ISSUE TITLE
Wrong file picked up if more than one SFM file exists

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#704]
I recently had a strange thing happen where the text being typeset wasn't what was being displayed in Paratext. On closer investigation, I discovered that there were two .SFM files in the project folder: "19PSAPBN.SFM" and "19PSAPBN - Copy.SFM"
And PTXprint was using the - Copy version (as seen by the image below) rather than the standard named version.
![image](https://user-images.githubusercontent.com/12962708/179864090-1b99418f-a6bb-461f-807c-c0c4ec6367a3.png)

**Comment by mhosken** [comment]
How is ptxprint to know which is the right file given it has to infer just from the filesystem what files are sfm files to use?

**Comment by markpenny** [comment]
Good question! I have no idea. In this case, with human eyes, it is easy to spot the exception, but how could the code "spot it"? Ideally, it should first attempt to use the pattern in settings.xml; but if it doesn't find anything matching that prescribed patters (or can't find settings.xml), then PTXprint can infer and guess...
