### ISSUE TITLE
Custom footers don't appear unless \NBSP specified in main UI

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#705]
I tried to add custom footers using this kind of .tex snippet in ptx-print.mods 
```
%% Footer
\def\RFoddright{My sample book [\pagenumber]}
\def\RFevenleft{[\pagenumber]\ If there are chapter and verse nums}
\def\RFtitleevenright{My sample book\ [\pagenumber]}
\def\RFtitleoddleft{[\pagenumber]\ On Title page}
\def\RFnoVoddright{My sample book\ [\pagenumber]}
\def\RFnoVevenleft{[\pagenumber]\ Where there are no verses}

```
but nothing showed up in the output as long as the footer area had:
![image](https://user-images.githubusercontent.com/12962708/180681331-ccf8d322-3fb3-4423-b5d1-c351bee5cc04.png)

As soon as I added \NBSP to the footer in the UI, the custom footers showed up in the output.

![image](https://user-images.githubusercontent.com/12962708/180681284-81c6d733-0b56-49b1-b947-b4a29fb449d4.png)

**Comment by davidg-sil** [comment]
Are you sure that *all* your footers are displaying?  I don't get anything at all to display  from oddleft / oddright, only evenleft/evenright on even pages. 
oddcenter works OK.

**Comment by markpenny** [comment]
Do you have scripture ch:vs text on those pages? I was earlier puzzled by why nothing was appearing (for a module), and then remembered that I had to use the noVoddright and noVevenleft etc... It certainly gets complicated and hard to debug when there are so many variables and contributing factors to success (or failure).

**Comment by davidg-sil** [comment]
I've worked out what's going on here, and am working on a fix.  But note that in your above snippet 'titleevenright' and 'titleevenleft' don't currently get checked for.  The 'title....' fields didn't have odd/even variants except for the centre in the footer (very confusing!). 
The fix will therefore add full odd/even control for header and footer, but if those aren't set fall back to titlecenter etc.

**Comment by markpenny** [comment]
Thanks - that's working as expected now.
