### ISSUE TITLE
\pn within \li# does strange things

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#706]
A project has reported an issue where they are wanting to underline any proper names marked up like this \pn Abraham\pn* 

They have added a .tex snippet for the underline:
![image](https://user-images.githubusercontent.com/12962708/181395085-ada16aa0-befd-433d-9507-89ebb28b7088.png)

And this works fine in some situations, but goes wild when combined with any of the \il# markers:
![image](https://user-images.githubusercontent.com/12962708/181395492-e4b6cde4-87b7-4eb3-8487-eb0ec7db933e.png)

Note that if I change \li1 to \m then it works fine:
![image](https://user-images.githubusercontent.com/12962708/181395527-2ddb2585-8d45-450e-82ba-3412d5ca1d41.png)

**Comment by davidg-sil** [comment]
Hmm. Yes, this makes sense to me, thinking about it. The `\pn` sets a paragraph-initial indent, and `\underline` puts text into a paragraph in order to separate the words. Obviously, the `\underline` code needs to unset any indents better than it currently does.
