### ISSUE TITLE
The special field \zfiga is sensitive to how it is closed

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#707]
Usually in Paratext, we can close fields with \fig ... \fig*
But the \zfiga field is not so configured.

This format works:
\zfiga|001\*

This format crashes PTXprint: 
\zfiga|001\zfiga*

**Comment by davidg-sil** [comment]
Zfiga is a milestone, not a character style. It must be closed with the
milestone end-marker \*

**Comment by davidc86** [comment]
That's fine. I figured it was something like that. But I flagged it just so you all know that a normal user will likely stumble on this difference. 

It would be much better/safer for variables to be entered into the FRTLocal file by PTXprint itself through a drop-down list or some such (like Paratext SFM markers), rather than having the user type each one manually. Because a) they are likely to make mistakes, which will throw errors when PTXprint formats the PDF, and b) there are likely many more variable possibilities than the average user is aware of. 
    
I suspect supporting this is not trivial, but if it were similar to how Paratext reacts when the user hits <Enter> or "\", i.e. when a user hits "\" in the Front Matter Window, it opens a "Variable" dialog which allows the user to select the variable he needs. OK would then insert this variable and its argument(s) into the file well-formed. 

This might go a long way to solving the errors that could be introduced. (Clearly an "enhancement".)

**Comment by davidg-sil** [comment]
Yes... users are always a problem :-) 
I think the rationale goes like this:
* Character styles always contain textual content, and only within a paragraph.
* Stand-alone milestones (`\zfiga |foo\*` and `\zrule|width="0.6"\*`) might do interesting things but they enclose no text.
* Ranged milestones (`\qt-s |Pilate \*` What I have written, I have written! `\qt-e\*`) define some range of textual content and might affect formatting, but the the markers themselves don't contain text. (i.e it's not `\qt-s What I have written... |Pilate\*`)
