### ISSUE TITLE
v2.2.8 TOC doesn't print when I use "Local Front Matter" option

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#708]
v2.2.8 TOC doesn't print when I use "Local Front Matter" option. 
Does the TOC need a field in the FRTLocal file to trigger its inclusion?

![image](https://user-images.githubusercontent.com/65363206/182456502-47be7a4d-c1e5-4165-a07c-c98b49c23513.png)

If I turn off Local Front Matter, the TOC is produced.

**Comment by markpenny** [comment]
I agree that this is confusing, and will add some tooltips to explain how things work.

The main idea is that if someone just wants a simple ToC, they can check the Table of Contents option and get the default output. However, if they are using Front Matter, they need to specify exactly what kind of ToC they require, and sometimes there can be more than one (as shown in the {Advanced} Generated Front Matter sample here):

![image](https://user-images.githubusercontent.com/12962708/182486292-0fdbc82f-6f0f-42e6-af7f-45f88772c26a.png)

There is some {now [outdated} documentation](https://software.sil.org/ptxprint/documentation/how-to-generate-table-of-contents/) on this on the main website, but we probably need to make a link to this, and/or add enough info in the Tooltips.

**Comment by davidc86** [comment]
Okay, I wasn't aware that the TOC would be considered part of the front matter (as in my mind that front matter stuff is mostly title page, copyrights, letters of recommendations, forewords, etc. not actual TOC, which to me is something that comes even after the INT book and before Genesis. 

If I have to put the codes in FRT, then what about my INT book? I had separated out the "front matter" stuff like publishers require (in FRTLocal), from the actual Introduction from the translation for the whole publication (in the INT book). But I'd want the TOC to come after the INT, like: FRT, INT, TOC, GEN, EXO, ...

I think the UI might need reordering, and/or it might need to use radio buttons, if you can't have both the TOC automatically generated along with using the Local Front Matter. 

I see that the Local Front Matter file is becoming a complex control file for specific results. Very powerful, but also opens lots of possibilities for typos and error messages, as there is no editor controls/checking.

Personally, I'd like the TOC to be its own "book" and we insert it where we want it. And it could be simple like the check boxes you already have, or more complex like what you are showing above, but it would be in its own "Table of Contents" tab, separate from the Front Matter tab. Just a thought.

**Comment by markpenny** [comment]
This has now been solved in recent versions. The FRTlocal book (only used by PTXprint, not by Paratext) can pull in everything it needs to create the PRE-scripture pages, including the wrap-around cover page, the title page(s), the introductions, ToC, etc.

We still need some explanation / documentation or training videos to explain how to do all this, but the functionality is in place now. 

So I'm closing this issue.
