### ISSUE TITLE
v2.2.8 confusing unlabeled check box on bottom of UI 

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#709]
There is a confusing unlabeled check box on the bottom of the UI: 

![image](https://user-images.githubusercontent.com/65363206/182456910-221ef687-03eb-4964-938d-e7fb90815d20.png)

The tooltip says it is for "Quick Run". I'm thinking we need to have that "Quick Run" label back in the UI. As it is now it looks like it relates to the Save Config button, and if we leave this UNchecked, then whatever we do WON'T be Saved.

**Comment by markpenny** [comment]
I agree. Fixed for 2.2.9

![image](https://user-images.githubusercontent.com/12962708/182482946-388f8ba6-6fc6-4681-b696-e0db33e8f398.png)
