### ISSUE TITLE
The marker \periph confuses page numbering layout

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#712]
The sfm \pb correctly causes a page break in the book, but it incorrectly triggers a "page number at bottom of page on first page of section" behavior, and it does this apparently after it has triggered the formation of the header, so we get this: 
 
![image](https://user-images.githubusercontent.com/65363206/182459211-0b9f7020-6363-44be-9573-1f3c8f14602a.png)

I'd prefer if the \pb field did NOT get treated as a section break, but just as a page break, though others may argue differently. 

But if it is going to be treated as a section break, then it needs to NOT format the header on those new section fist pages.

**Comment by davidc86** [comment]
By the way, if I take away the \pb and use \periph ... it acts the same way: 

![image](https://user-images.githubusercontent.com/65363206/182501587-dfef6ce7-fd3f-4d74-8a97-fb68576acdcf.png)

(It is page 9 now only because I shortened the previous section.)

**Comment by davidc86** [comment]
Here is the SFM for that break: 

\tr \tc1 Asw desike myaty de.\tc2 → Asdwesige myatdye. \tc3 \it Anjing itu sudah mati.\it*
\b
\periph Introduction ‑ Nomanclature
\is1 NYATOS MALEKU IKE ( ), ODE NYATOS MAKA KSIKUKE [ ]
\ip Nyatos a maleku i neke ( ), rpake ti brit a anakyai mamin ti tel Yunanike wasi tkunw a rakeskye. Neke wasi kbuanke kolnye:
\ili1 Nyatos neke ktyenuk nam dum ma kyety a nyalarkye ti brit ne, ta
\ili1 Nyatos neke ktyenuk nam dum ma rkesy ti kitabare ti iry mabacake.

**Comment by mhosken** [comment]
you know the drill

**Comment by markpenny** [comment]
@davidc86 - I think MH is waiting for an Archive file ... ;-)

**Comment by davidc86** [comment]
Sorry, been putting out other fires.
[SLU-SelaruNewPublicationFRONT-MATTER-TESTPTXprintArchive.zip](https://github.com/sillsdev/ptx2pdf/files/9601523/SLU-SelaruNewPublicationFRONT-MATTER-TESTPTXprintArchive.zip)
I've noticed that now, without me doing anything that I'm aware of, the cover picture and the logos now are marked as "missing". (I'll look into that.) But the original issue with the page number on the top of page 9 and also on the bottom of page 9 is the reason for this Issue.

**Comment by davidc86** [comment]
Okay, here is a comparison of two spreads. 
1) Taken from 2John Intro and ch1:
![image](https://user-images.githubusercontent.com/65363206/193377683-804ba9b1-04dc-4828-b343-c551c141ced7.png)

2) Here is a spread taken from the INT book in Paratext (this is **_not_** the Front Matter stuff): 

![image](https://user-images.githubusercontent.com/65363206/193377698-34e2caec-3553-4fd3-915c-b0689c6d3e05.png)

 The weird bit is that to get a pagebreak at the new topic (NYATOS...) we include this in the INT book:

\periph Introduction - Nomenclature 
\is1 NYATOS MALEKU IKE ( ), ODE NYATOS MAKA KSIKUKE [ ] 

Rather than how a \c 1 in a scripture book causes this page break to work just fine.

**Comment by davidg-sil** [comment]
OK, I've worked out what's going on. The code used to assume that headers were generated before footers, and one critical value was only getting defined by the header-generating code. Recent changes to support 'no ink in margin' broke that assumption.
