### ISSUE TITLE
Can't find file 'paratext2.tex'

### ISSUE THREAD

**Issue by oyuntugs-ctrl** [sillsdev/ptx2pdf#714]
Hello.
PTXprint is not creating pdf file. In XeTeX log window i have following report.  

This is XeTeX, Version 3.141592653-2.6-0.999993 (TeX Live 2021/W32TeX) (preloaded format=xetex 2021.6.19)  3 AUG 2022 19:55
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**ptxprint-Default-ESTMSV.tex

(c:/My Paratext 9 Projects/MSV/local/ptxprint/Default/ptxprint-Default-ESTMSV.t
ex
! I can't find file `paratext2.tex'.
l.3 \input paratext2.tex
                        
(Press Enter to retry, or Control-Z to exit)
Please type another input file name
! Emergency stop.
l.3 \input paratext2.tex
                        
No pages of output.

**Comment by markpenny** [comment]
Hi @oyuntugs-ctrl  It seems like something may have gone wrong with the installation. Does this issue happen with only one configuration, or any of them? Have you tried to re-install the latest version to see if the problem goes away? If not, then I can take a look via Zoom. Let me know what time would be convenient for you.

**Comment by oyuntugs-ctrl** [comment]
Hi @markpenny  It happens to all configurations and projects. And I have tried re-install on 2 different computers.

**Comment by markpenny** [comment]
@oyuntugs-ctrl Please let me know when I can connect with you on Zoom to troubleshoot this issue. Thanks.

**Comment by markpenny** [comment]
@oyuntugs-ctrl Is this still a problem? If so, please tell us how you would like us to help you. If zoom is not an option, then suggest an alternative.
If the problem has been solved, then please close the outstanding issue, or let me know so that I can close it for you. Thanks!

**Comment by oyuntugs-ctrl** [comment]
@markpenny Yes. It is still a problem. 
But after one thing, it is working now. I have copied all .tex and .sty files that's inside ptx2pdf folder (_C:\Program Files\PTXprint\ptx2pdf_) to each configuration folder (_C:\My Paratext 9 Projects\MSV\local\ptxprint\configuration1_).  And it needed to repeat this step after each update of PTXprint.

**Comment by markpenny** [comment]
Sorry to hear that it is still a problem. For some reason, it isn't seeing the macros where they normally are located. Could you please give me a screenshot like the one below. This will help me see if there is something wrong with the paths:

![image](https://user-images.githubusercontent.com/12962708/191889209-bff005ec-cfad-424b-bca6-66486e95a6d7.png)

Also, I am wondering if there might be an over-aggressive virus checker that is treating those .tex and/or .sty files as suspicious and is deleting them, or quarantining some of them...

What do you see in your **C:\Program Files\PTXprint\ptx2pdf** folder? It should look like this:

![image](https://user-images.githubusercontent.com/12962708/191889482-2f4f8d6b-c2cc-42bf-9c12-018b5763e757.png)

**Comment by markpenny** [comment]
Another thought is to uninstall it, then completely remove the PTXprint folder from Program Files, and then re-install (with Administrator permission?); and try again.

I'm clutching at straws here, trying to guess what might be wrong. It might be easier to do a Zoom support session together to solve the problem. Let me know if you want me to look.

**Comment by oyuntugs-ctrl** [comment]
Thank you for your response and support. I am sending you 2 screenshot
pictures. It seems like doesn't have any differences.

**Comment by oyuntugs-ctrl** [comment]
Thank you for your reply and support.
It seems like it doesn't have any differences.  When can you do the Zoom support session with me? 
![ptx2pdf](https://user-images.githubusercontent.com/74051653/192415044-2a02c77d-8e41-4d9f-af48-9433a31195ed.png)
![ptxprint-help](https://user-images.githubusercontent.com/74051653/192415047-974dbb36-c1d2-4131-880d-8659dae75179.png)

**Comment by markpenny** [comment]
@oyuntugs-ctrl Sorry for the delay. I was away for a week, and this issue slipped my mind. I am in NZ (13 hours ahead of UTC). Which time zone are you in? If you would rather communicate via e-mail, please use the ptxprint_support address as shown on the Help tab.

**Comment by mhosken** [comment]
is this still an issue?
