### ISSUE TITLE
When selecting a new project, the B, I and BI fonts don't get filled in

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#715]
When selecting a project for the 1st time, PTXprint correctly loads the font name for Body Text (Regular), but doesn't fill in the remaining fonts for B, I and BI leaving the user with a "Font(s) not set" informational status message.

![image](https://user-images.githubusercontent.com/12962708/182955983-2fdc65ab-faee-4285-a408-9bc9bc21c5ca.png)

**Comment by LornaSIL** [comment]
Is this because there is no "Lateef Lateef KasLow" Bold, Italic or Bold Italic? I know we've recently added Light, Medium, Bold, ExtraBold, etc to Lateef, but at least in the past (and that looks like an old font name) there was only a Regular. How would ptxprint know how to set the other weights if they don't exist?

**Comment by mhosken** [comment]
It would fake them!!!

**Comment by markpenny** [comment]
Closing this issue until I can get more evidence of it happening. It is rare, but I think it still happens. Once I work out the sequence of events leading to this situation, I'll re-open the issue.

**Comment by markpenny** [comment]
Aha! It just happened to me again (setting up someone else's machine), and this time I think I can see why:

![image](https://user-images.githubusercontent.com/12962708/195753283-afb96256-44b7-41e5-adb9-ebc65666c469.png)

Paratext has "Andika" set as the font to use. BUT the (new) computer on which PTXprint is running this project for the first time DOESN'T have that font installed (at all). So it seems to fill in the first "Regular" font name (from Paratext settings), but then can't find any of the other fonts, so leaves them as "Select font..." and disables the Print button with a status message "Font(s) not set".

I don't know what the best way to fix this is; but it is probably more common than we realise, and would probably stump new users.

**Comment by mhosken** [comment]
Should we remove the font setting if when we load a project the font requested is not available? I.e. reset to now known font?

**Comment by markpenny** [comment]
But if we do that, then the user doesn't know WHICH font he/she is looking for. So perhaps it is better to leave it as it is.
