### ISSUE TITLE
Main buttons lost localisation

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#716]
With latest 2.2.10, when I change the UI to French, the main buttons (Print, etc.) are in English:
![image](https://user-images.githubusercontent.com/14953913/183650214-827877c8-e4fb-4aec-8789-5a48cec8949a.png)

The French localisation is still at 100% - are those strings not in the localisation?

**Comment by markpenny** [comment]
@jeffheath-sil We'll refresh the crowdin strings once the dust has settled (probably next week).

**Comment by markpenny** [comment]
@jeffheath-sil The Crowdin files have been refreshed over the weekend, so there's some work to be done there now on localization. Version 2.3 will include any updates that you make and should solve this issue.
