### ISSUE TITLE
Some ideas for more informative error messages and to make self-diagnosis easier.

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#717]
1. PTXprint could read the log-file to determine more precisely there was an issue, e.g. 'while reading custom.sty, in marker definition of zwomble' 
1b. TeX should cooperate by log-file entries more machine-readable, e.g. '# opening file xyx' '# closed file xyz', '##  marker definition of zwomble', or something similar

2. A style-sheet linter, which warns about unexpected content in the style sheet, e.g paragraph/char  styles getting used, unknown options, any output-producing text coming from accidental line-breaks, commas in space-separated lists, etc. I'd be able to bash something out in perl, but presumably it ought to be in python.

**Comment by davidg-sil** [comment]
>
> Really? You can insert \thisisanerror in a custom style sheet, and it'll
tell you which \Marker definition it's in?
That certainly wasn't the case when the issue was flagged.

Other ideas:
1. Stuff that shouldn't be there (hard one that!), I guess XeTeX could read
the stylesheet in a group and \def\p{\NotHere{p}} etc. That's a bit of a
coding pain, though, and it means everything would have to be defined
globally. Maybe it is, I don't know.
I'm hesitant to suggest such a list should be in python, since that becomes
an issue for stylesheets adding new/rare features with old versions, when
bisecting.
2. The stylesheet parser doesn't seem to care about commas in
space-separated lists.

**Comment by mhosken** [comment]
This bug is too vague to action.
