### ISSUE TITLE
Some headings not printing in Bible Modules

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#718]
Headings (\s) which precede verse 1 will be correctly imported and printed when using a XXA style book, but will not when using a Bible Module directly. Oddly enough, those headings get dealt with properly _if_ the \s marker precedes any verse other than 1.

For example, if MAT starts with
```
\c 1
\s The beginning of the Gospel of Matthew
\p
\v 1 The book of the genealogy of Jesus Christ, the son of David, the son of Abraham.
```
and the Bible Module spec has
```
\inc v f s
\ref MAT 1:1
```
then the heading won't print when ptxprint points directly to the module spec.

**Comment by mhosken** [comment]
Try MAT 1:0 or MAT 1-1:1.

MAT 1:1 starts at the start of the verse, not the chapter

**Comment by mnjames** [comment]
Okay, it looks like including verse 0 is a viable _workaround_. But I'll argue that it's not the full solution.

If the \s marker occurred _before_ the chapter number, I'd agree with you. But since it occurs afterward I think what I wrote in the OP ought work. To back up my argument, PT creates the Bible Module exactly as I would expect it to, so that XXA version works.

For example, if the text was
```
\p 
\v 1 The book of the genealogy of Jesus Christ, a the son of David, the son of Abraham. 
\s The list of names
\p 
\v 2 Abraham became the father of Isaac. Isaac became the father of Jacob. Jacob became the father of Judah and his brothers.
```
Then both PT (XXA) and ptxprint (via the Bible Modules option) **treat the \s as part of verse 2**, and will import it when the module states
```
\ref MAT 1:2
```

**Comment by mnjames** [comment]
Thank you!!!
