### ISSUE TITLE
By Default not seeing \mt2 fields in the PDF file

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#72]
Here is a typical header to a NT book:
\id 3JN - Selaru
\h 3 Yohanes 
\toc3 3Yoh. 
\toc2 3 Yohanes 
\toc1 3 Yohanes 
\mt1 Yohanes 
\mt2 wasi atyahy a kla-telw ikeskye 
\is Tun a khatu malosu kitab ne 
\ip Iry a makesy a Kitab 3 Yohanes neke, ani Yohanes. I neke Yesuske...

The \mt1 comes through (so long as it is not \mt), but the text in \mt2 is lost -- though the space for it is held open in the PDF.

I finally got them to show if I specified the font size and the color (not sure which triggered it). But it was odd they wouldn't print "from the factory".

**Comment by mhosken** [comment]
Not sure how to test this. Please could you recheck with 0.7.1 once it is released and if it is still failing, submit a sample file (-draft.SFM) with supporting .sty other than usfm.sty.

**Comment by mhosken** [comment]
Please re-test or we will close assuming it's fixed on next release.

**Comment by davidc86** [comment]
I'm not seeing it any more. It may have been a weird interaction with my .STY files and the color settings early on. (Apparently they were displaying in "white" so I couldn't see them!). Either I fixed the styles or you fixed the color palette or both.
