### ISSUE TITLE
Multiple Books range (discontinuous verses in same chapter)

### ISSUE THREAD

**Issue by viverechristus** [sillsdev/ptx2pdf#722]
If I want discontinuous verses from the same chapter and use "Multiple Books" to achieve that, the result is that the verses are printed twice, as here:

![image](https://user-images.githubusercontent.com/915182/185577546-d7880f47-d85d-4750-8d66-2b796d1ae419.png)

I get the same results however I do the input:

`EXO 3:13-14,21`
`EXO 3:13-14 3:21`
`EXO 3:13-14 EXO 3:21`

Our own use case was preparing a booklet of short selections that the Committee needed to review because of issues that had arisen since the previous Committee check.

**Comment by markpenny** [comment]
Duplicate issue, first raised by @markpenny in #702

**Comment by markpenny** [comment]
This has now been fixed and will be available in the next released version (2.2.17 onward).
