### ISSUE TITLE
Color Images are now washed out (v2.2.20)

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#726]
I was testing the various PDF output options and the results ended up changing from somewhat vibrant to washed out.

Original PDF (earlier version of PDFprint):
![image](https://user-images.githubusercontent.com/65363206/188948231-ab546e99-1952-48b9-8368-d500e86a5467.png)

The current version of the same picture:
![image](https://user-images.githubusercontent.com/65363206/188948637-d437e28b-69a0-4d55-a1c9-24d813cc33d7.png)

I've tried every PDF output setting and I can't get it to return to the vibrant colors. (It does change to grayscale. And I can change it back to washed out, but not back to vibrant). Even the black lines are not as crisp now. 

I expected Print CMYK to be the most vibrant or true to the original image. But I've never had a problem with the Default version in the past. Always looked nice enough for eBooks/PDF readers. 

Any clue what might be happening?

**Comment by mhosken** [comment]
When viewing a PDF on a screen, the image needs to end up in RGB. If your image was originally CMYK, then it may be that you are using a different cmyk to rgb mapping to what ptxprint is using. Ptxprint tries to obey color profiles, but that doesn't mean that it's roundtrip is perfect. Anyway, once in cmyk, when you open in a pdf viewer the cmyk has to be mapped back to rgb and that often does wash out colours. I would expect the screen output format to help most if your images are RGB already. Likewise the digital output formats. Feel free to submit your source image.

**Comment by davidc86** [comment]
The PDF is back to displaying on screen the cover graphic (a scanned image) in normal vibrant colors. Right now, I'm not ready to mess with changing the PDF export to other versions again. It's working. Cool. Maybe PTXprint got its settings twisted, and my exiting and rerunning PTXprint solved it. (I can't recall when and how exactly it sorted itself, sorry.)
