### ISSUE TITLE
Unable to print a previously archived project

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#728]
After restoring a .Zip Archive file, the Print button is disabled due to the "Font(s) not set" flag being raised. However, the Fonts+Scripts tab shows that the fonts are selected (as expected). 

![image](https://user-images.githubusercontent.com/12962708/189786410-d76b30f7-8122-4b9e-b708-b125c9da5c2a.png)

NOTE: This issue may be related to the relative paths not being able to make the D:\ to C:\ transition (as an error along those lines was reported by the original user).

**Comment by mhosken** [comment]
Is the font missing from the archive?

**Comment by markpenny** [comment]
This continues to be an issue. The font is in the archive, and when you select the Font button, it is correctly selected, BUT the Print button remains inactive until you go in and select the font.
