### ISSUE TITLE
Find an alternative way to format Table of Contents entries

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#73]
I'd like to uniquely specify the attributes of the page numbers listed in the TOC. Do they have a unique "marker" that can be defined in the STY file?

**Comment by mhosken** [comment]
See docx/documentation/ptx2pdf-faq.md

**Comment by davidc86** [comment]
Well, I found that location (with other documentation too), thanks.
But it didn't work. I tried this example:
\Marker pgnum
\StyleType character
\FontSize 9
\Bold

In the PrintDraft-mods.sty file, and this had no effect on the page number either in the header or the Table of Contents. 

But I DON'T want to tweak with the Header. Its formatting is just fine. 

I ONLY want to tweak the Page numbers that show up on the Table of Contents page. I need to reduce their fontsize to match my Table fontsize. Here is what I'm seeing:

![image](https://user-images.githubusercontent.com/65363206/82597937-cb278600-9b77-11ea-8cd3-bd9446caabee.png)

I'd like to change those to FontSize 8 but keep the PageNumber on the Running Headerings as they are.

**Comment by mhosken** [comment]
Context context context. There is nothing magical about a page number in TeX, it's just some textual content. It's all about styling text (which happens in this case to be a pageno). So I leave this to you as an exercise in styling TOC content. For example styling \tcr3 as a character style.

**Comment by davidc86** [comment]
Okay, so I got this to work, but it was a bit counter-intuitive. Here are the results: 

![image](https://user-images.githubusercontent.com/65363206/82671883-8fd79680-9c0d-11ea-9b87-22235c4a81a1.png)

Looks nice.
The very odd thing is: This is a Table of Contents (TOC), but it is *NOT* using the TOC fields that are specified in the PrintDraft-mods.sty file.
 
Instead, as mhosken clued me into (thanks!), it is using the standard "table" fields (the ones used in scripture text for "the number of fighting men per tribe", etc. 

My problem was, I'd assumed these fields controlled the TOC:
\Marker toc1
\FontSize 8

\Marker toc2
\FontSize 8

\Marker toc3
\FontSize 8

\Marker toc4
\FontSize 8

Apparently not.
Does anybody else think it would be better if the Table of Contents page used the TOC fields rather than the \tc* fields?

**Comment by mhosken** [comment]
I wonder if we can poke in a `\cat toc\cat*` into each cell in the table of contents and when we get category based styling going then a user could add styling to `\cat:toc|tcr3` or whatever. Just a possible path forward on this. They could also poke in categories using anchors or even `\cat:army|tr+tcr2`.
Warning. This is not possible now. But this am capturing this as a use case for some of our future thinking.
