### ISSUE TITLE
Creating new saved configuration resets Scope and sets password

### ISSUE THREAD

**Issue by cdfarrow** [sillsdev/ptx2pdf#731]
PTXPrint 2.2.22
I changed the Scope to Psalms, then created a new Saved Configuration (entered a name and clicked Save at the bottom), and it reset the Scope to the previous book (combination) settings. Creating a new configuration shouldn't change the settings in Project and Scope (even if the Configuration includes the Scope (see discussion here #684)), 
Secondly, I had added a password to one configuration, but now whenever I create a new Saved Configuration the new one has the password set, too (the same as the first one).

**Comment by mhosken** [comment]
Please only raise one issue per issue. It's tricky to say: well I've fixed part 2 but not part 1 of this issue, but then in further discussion someone added another subissue on a completely different topic that we haven't fixed yet. (I know that's overstating the problem, but you get the drift from us developer's POV) Thanks. And now to addressing the actual issue...

**Comment by mhosken** [comment]
Committed fix to part 1.

**Comment by markpenny** [comment]
and Part 2.

**Comment by cdfarrow** [comment]
> Please only raise one issue per issue.
Sorry; they seemed closely related, but I did know better :-)
