### ISSUE TITLE
Generate PicList Append duplicates picture entries

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#735]
I just "Generated" a PicList for a single book with only 2 pictures in it, and it produced this: 

![image](https://user-images.githubusercontent.com/65363206/191521352-c1c01d9f-7fd0-4949-9c99-98e7d77d5754.png)

So, something in the Generated "Append" option is doubling the entries.

**Comment by markpenny** [comment]
Hi @davidc86! I'm still unable to replicate this behavior on my system. Do you have a specific set of steps that you go through to make it happen, or does it just randomly happen? If it is predictable, then send us a small archive to test with. Thanks.

**Comment by davidc86** [comment]
Here is my GLO list (v2.2.25 now):

![image](https://user-images.githubusercontent.com/65363206/192373319-ee933423-08b0-483a-b9cd-b2a77e1a23e1.png)

I click Generate, and I get this: 

![image](https://user-images.githubusercontent.com/65363206/192373413-efb8c1e2-bf5b-4e5a-afce-a82ae8a7d64e.png)

Click OK and I get this: 

![image](https://user-images.githubusercontent.com/65363206/192373505-3779d7ab-30c2-414a-abfe-54b50d602982.png)

Every time.

This is the exact same project I've submitted the last few times, but just in case there is something different, I'll send another archive.  

[SLU-SelaruNewPublicationPTXprintArchiveGLO.zip](https://github.com/sillsdev/ptx2pdf/files/9649517/SLU-SelaruNewPublicationPTXprintArchiveGLO.zip)

This archive includes the whole list of books I'm testing, but if you want to test it with just the GLO book, switch to that first. 

Is it possible there is a default PicList laying around somewhere that PTXprint is combining with this configuration's list when it regenerates the list? (Just a thought.)

**Comment by markpenny** [comment]
This should be working now in 2.2.26 (just released). Please confirm,

**Comment by davidc86** [comment]
Yes! V2. 2.26 has fixed this issue in the GLO book. I assume it is fixed elsewhere (but don't want to recreate the settings for more than a few pictures).
