### ISSUE TITLE
Any way to suppress the Intro material for certain books? 

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#736]
I would like most intro material (stuff before \c 1) to print. But in a few back matter books, there is intro material which is fine for apps, but not nice looking in a printed book.

What is the trick to selectively suppress these?

**Comment by markpenny** [comment]
Just add this line of Regex magic to your changes.txt file:

at 2JN, 3JN, JUD "\\i.+\s.+\r?\n" > ""

and replace 2JN, 3JN, JUD with whichever books you want the intro material stripped from.

**Comment by davidc86** [comment]
Cool. Thanks. I have tried this, and it kind of worked.
It throws this message: 
![image](https://user-images.githubusercontent.com/65363206/191638484-127d610c-6380-47e0-9787-dda476895d96.png)

But it creates the PDF, and the book came out okay, but it was not listed in the PDF's Bookmarks pane (so this Regex code pitched the necessary SFM for generating the TOC codes).

I'm using it in the XXE book which has the beginning like this: 

\id XXE - Selaru
\h Nam Tanal ma Tasambayanare 
\toc1 Nam Tanal ma Tasambayanare 
\toc2 Tal ma Tsambayan 
\toc3 Tsambayan 
\rem Tata Ibadah (baru dua: 1) Doa Bapak Kami, 2) Aku Percaya) 
\rem SIAP untuk Aplikasi, asal dari XXA pasal 23,24 
\mt Nam Tanal ma Tasambayanare 
**\is Kisike kolnye 
\io1 1. Tsambayan ti ity Amatke 
\io1 2. Tou ity wait Tohtohakke** 
\c 1 
\rem Sudah periksa tim sama konsultan MTB, dan sesuaikan dengan terj. Lukas (April 2012). 
\rem Diperiksa sedikit oleh Michael Martens, 25/Okt/2012 
\rem Dikoreksi sedikit oleh Tim dan Kons MTB, 16/Okt/2019 
\s TSAMBAYAN TI ITY AMATKE KOLNYE 
\r (\xt Mat. 6:9-13; Luk. 11:2-4\xt*) 
\q1 Oo, ara Amamy a mamin ti wen a sra eras so. 
...

I'm just trying to pitch the \is ... \io1 ... stuff.

**Comment by davidc86** [comment]
Here is the Final SFM file:



\toc1 Nam Tanal ma Tasambayanare

\toc3 Tsambayan
\mt Nam Tanal ma Tasambayanare
\s TSAMBAYAN TI ITY AMATKE KOLNYE
\r (\xt Mat. 6:9-13; Luk. 11:2-4\xt*)
\q1 Oo, ara Amamy a mamin ti wen a sra eras so.
...
(Looks fishy in the \toc area.)

**Comment by markpenny** [comment]
Sorry, my bad! It has obviously clobbered the \id line as well ... Try this (which is a bit more specific):

`at XXE "\\i[so]\d?\s.+\r?\n" > ""`

**Comment by davidc86** [comment]
Woohoo! That solved it! Thank you. 
I think this might be a useful capability for others too. Now whether it warrants a UI is another question, but I could see where a tick box next to a book name in the selected book list: 
REV [ *] Include Intro 
BAK [*] Include Intro

would allow users to easily remove Intros they don't want. 
But how often will this be needed? (Though I do find more and more places where the demands/desires of an app and what looks good in a book, fight with each other.) 
So, for now, a "Cheat Sheet" explaining how to do these special things is all we need. I know there is such a webpage somewhere, is there a link to it on PTXprint's Help page?

**Comment by markpenny** [comment]
This has been added to the [snippets.md documentation page](https://github.com/sillsdev/ptx2pdf/blob/master/docs/documentation/snippets.md#suppress-introductory-material-for-some-books-but-keep-it-for-others) now.
