### ISSUE TITLE
Nested character styles not behaving as expected

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#737]
A user has reported that nested character styles are being reset too early:

![image](https://user-images.githubusercontent.com/12962708/191620331-40bfa7fc-4cf6-432b-8a1e-63120666c19c.png)

I wondered if it was the \bdit* which was turning off both the \it and the \bd and causing the issue, so I temporarily changed the \bdit ... \bdit*  to just a \it ... \it*  but the bug persisted:

![image](https://user-images.githubusercontent.com/12962708/191620287-fb66845e-e70e-4179-a023-66eb3d9c2904.png)

**Comment by markpenny** [comment]
Okay, so if I manually add the + to the marker to show that it is embedded: i.e.  \+bdit ... \+bdit* then it works:

![image](https://user-images.githubusercontent.com/12962708/191621491-34f28d4e-4389-42f1-8fab-867e34723349.png)

And similarly with \+it ... \+it* which is noticeably different:

![image](https://user-images.githubusercontent.com/12962708/191621609-af9ba8ca-1dc8-4c68-b832-82e63bcea75b.png)

So is this a BUG or a FEATURE?

**Comment by davidg-sil** [comment]
This is actually how it's supposed to work. In the first example:
`\bd` - character style is now bold (on top of `\m` style).
`\bdit` - Implicit end of bold. Character style is now bold-italic (on top of `\m` style).
`\bdit*` - explicit end of bold-italic character style, return to `\m` style.
`\bd*` - Marker error

The + forms of character styles are nesting, but `\bdit` implicitly *ends* any previous character styles, just like \p ends any previous paragraph style.

[USFM documentation](https://ubsicap.github.io/usfm/characters/nesting.html)

Note that while PT objects to using + forms at the outermost level, PTXprint accepts them. Thus any changes file based formatting should probably use the + form.

**Comment by markpenny** [comment]
Okay, that is clearly how it is intended to work. So I can close this issue.

More details about nested styles is [available here](https://ubsicap.github.io/usfm/characters/nesting.html?highlight=nested#indicating-that-a-character-marker-is-nested).
