### ISSUE TITLE
Reset callers on page - not working

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#74]
When the Footnotes have "Reset callers on page" checked, it doesn't actually reset the list of callers for each page. It just continues through the whole list of callers on successive pages until it finishes the list, then restarts. Note that this is with a list of callers defined in PTXPrint (not pulled in from Paratext).

**Comment by jeffheath-sil** [comment]
Well, call me a liar... Now it seems to work. Maybe I had to uncheck it, Print, then check it again? Don't know, but you can probably close this since I've seen it work.

**Comment by markpenny** [comment]
Thanks for getting back to us about it working. There are still a few strange (hard-to-repeat) bugs lurking, so I'll close this issue for now, but keep an eye out for this kind of strange behavior.
