### ISSUE TITLE
Add Front Matter PDF exported from Word 2019 - no longer builds PDF

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#740]
I'm not sure there's anything you can do about this, but when I export a PDF of title/credit pages from Word 2019, and then add that to my PTXprint project as a Front Matter PDF, PTXprint no longer can create a PDF.

I had this problem a few months back (emails with Mark from March 27-28), and at that point PTXprint was actually producing an error. Mark used Adobe Acrobat to "repair" the PDF that came from Word and then it worked fine. But with the latest version of PTXprint, now when I add a Front Matter PDF exported from Word, when I click the Print button it works a little bit and then does nothing. I'm attaching a PDF file that shows this behavior: [LUC Title pages Mawa.pdf](https://github.com/sillsdev/ptx2pdf/files/9626911/LUC.Title.pages.Mawa.pdf)

There are a variety of work-arounds. You can repair the file with Acrobat, or a number of PDF utilities that write out the PDF file again. You can open the file in LibreOffice and export to PDF (of course, you might lose a bit of formatting in that process). You can also, interestingly enough, print to "Microsoft Print to PDF", and that version of the file seems to work fine. I'll also attach that version here, in case that helps any analysis: [LUC Title pages Mawa.pdf](https://github.com/sillsdev/ptx2pdf/files/9626967/LUC.Title.pages.Mawa.pdf)

The most annoying thing is that I had to figure out this problem all over again (eventually I had a vague recollection of having done something like this 6 months ago...). So if PTXprint isn't able to handle that PDF for some reason, it would be really helpful to have some sort of message, like "Cannot process [file].pdf." Is there any way that you can tell that the processing has failed, and at least alert the user to that fact? (Even if you can't tell that it was a problem with a PDF?)

**Comment by markpenny** [comment]
@mhosken Here is the error that is appearing behind the scenes when the (1st of the 2 PDFs above) is used:

![image](https://user-images.githubusercontent.com/12962708/191914560-41618ba3-7068-41d7-8209-2e71704c8504.png)

Obviously a malformed PDF by M$ Word's PDF maker with no EOF where one is expected. But how can we either code around that, or at least give some helpful feedback to the user so that they're not left waiting indefinitely?

**Comment by mhosken** [comment]
It would help to have an archive of your project rather than my trying to create my own and not doing it quite the same and so not being able to recreate the bug. Currently I can't get it to go wrong with a simple open close.

**Comment by jeffheath-sil** [comment]
Attached is an archive which I think should show the problem.
[MCW-LUKPTXprintArchive.zip](https://github.com/sillsdev/ptx2pdf/files/9648661/MCW-LUKPTXprintArchive.zip)

**Comment by markpenny** [comment]
Yes this issue has been resolved now so that even "bad" PDFs get fixed (on the fly) so that they can be incorporated in the final PDF. We hope to release 2.2.26 later this evening.

**Comment by jeffheath-sil** [comment]
Wow, you're fixing Microsoft's bugs for them?! Good on ya...

**Comment by mhosken** [comment]
Not exactly. The file is conformant pdf. But xdvipdfmx which does the merge
can't handle a missing element that is allowed to be missing. So we quietly
add it back in.

GB,
Martin
