### ISSUE TITLE
v2.2.25 selecting "Hide missing verses" gives error

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#741]
v2.2.25 when I selected "Hide missing verses" I get this:

![image](https://user-images.githubusercontent.com/65363206/192308446-8093e58f-7046-4c24-885f-e4d0017518b0.png)

PTXprint doesn't fire this error if I turn this off.

NOTE: in the Basic tab, we've specified various chapters of Psalms that are ready for printing. 
GEN PSA 1; 6; 8; 12; 19; 23; 27; 32; 42; 48; 51; 67; 100; 103; 108; 112; 119; 121; 122; 125; 126; 127; 133; 139; 145; 150 GLO 2

Is there some error in this listing? And does this listing interact badly with the Hide Missing verses feature?

Currently I'm getting results like this, which isn't what we want:
![image](https://user-images.githubusercontent.com/65363206/192309478-1c3d1c4d-b650-4c84-ac29-55f3a7cdc75e.png)

NOTE: Mazmur = Psalms. Nothing printed from Psalms except the book divisions. This used to work. So is this a regression error?

NOTE: Kamus = GLO. I suspect the chapter number 150 is from Psalms! I has nothing to do with the GLO book (where chapter 1 is for NT glossary terms and chapter 2 is for OT terms). Our print list specifies GLO 2, so only OT terms would print. We don't want any chapter numbers in these "back" materials. So, I'm not sure why 150 is showing up.

**Comment by mhosken** [comment]
Are you raising two issues in a single issue again? Please send an archive, particularly for the second issue.
