### ISSUE TITLE
v2.2.26 crashes when switching to a different configuration file in the Paratext project after a print

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#744]
v2.2.25 crashes when switching to a different configuration file in the Paratext project
I'm in the FRD Paratext Project folder.
It starts out on Default.
I switch to PublikasiKejMazFordata (fine)
I switch to PublikasiKejMazFordata-TES (fine)
Print PDF (fine)
! switch back to PublikasiKejMazFordata (PTXprint blips out)

Ok. Bummer this happened TWICE. Now I try to repeat it again, it won't!
Sigh. Maybe it has something to do with initialization, because I was clicking along pretty fast when it crashed, i.e. maybe PTXprint didn't have itself organized before I started messing around with switching hither and yon.

**Comment by davidc86** [comment]
Now it just crashed after printing to PDF the Default configuration and then switching to another configuration.

**Comment by davidc86** [comment]
I use the SLU and FRD projects all the time, so this is not just a delay due to missing Settings files.
Just installed v2.2.26, started in FRD. 
Tested the chapter listings in the Basic page (still not working). (So this was a Print operation.)
Needed to test pictures in back matter in SLU.
When I tried to switch to SLU (going to Basic page and selecting SLU from the list), Instantly PTXprint HUNG. 
Or if not "hung," it's pretty close to it. It won't respond to clicks or anything. After several minutes I had to kill the process.

After killing it and restarting it, I was able to switch from FRD to SLU almost instantly.

**Comment by markpenny** [comment]
Thanks for this very helpful report. There were 2 hard-to-find but easy to fix bugs introduced (one 3 weeks ago, and another 10 days ago) which have now been dealt with. Version 2.2.27 will include the fix. Please test and confirm that all is well.

**Comment by davidc86** [comment]
Yep, that fixed the issue!
Thanks!
