### ISSUE TITLE
v2.2.26 Selecting chapters doesn't work

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#746]
It seems in v2.2.25 selecting chapters to print doesn't work.

In the Basic tab, we've specified various chapters of Psalms that are ready for printing.
GEN PSA 1; 6; 8; 12; 19; 23; 27; 32; 42; 48; 51; 67; 100; 103; 108; 112; 119; 121; 122; 125; 126; 127; 133; 139; 145; 150 GLO 2

Currently Psalms (Mazmur) prints out like this:

![image](https://user-images.githubusercontent.com/65363206/192534110-f23359ad-b513-4533-8824-67b1f99688b8.png)

Kamus is the beginning of the GLO book. It should only show chapter 2 (with no chapter number). The 150 might be from Psalms? Something isn't right. 

We are needing to get this formatted in the next day or so! So this has us concerned. (I touched on this same issue on Hide Empty verses, but thought it needed its own issue entry.)

**Comment by davidc86** [comment]
I just uninstalled v2.2.25 and installed v2.2.20 and reran the exact same configuration file and got this: 

![image](https://user-images.githubusercontent.com/65363206/192538243-e642b0f1-f3e0-4af6-9b29-f402139e3b94.png)

I will keep updating to see where it fails.

**Comment by markpenny** [comment]
@mhosken I've bisected this one and here are the results:

The first bad commit could be any of:
06abf7c3e6c29404db06aa39f49162e000de004e
e45ed7a635d4022eff001b0b7e9592063d50fc7a
We cannot bisect more!

**Comment by davidc86** [comment]
Fixed in v2.2.27
Woohoo!
