### ISSUE TITLE
Cutout option acts odd depending on the anchor point (verse 1 is weird)

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#749]
We were working on getting the Cutout option to work on a tall narrow picture, (see #747) and when it didn't work right in Indonesian we switched back to English--thinking maybe something in the UI is misaligned. Well, after the first fairly good run, I had done earlier in the day, we could never get it to act consistently again. 

Also, the selection options for Cutout are a bit inconsistent between UIs (the option jumps in the listing order). Also when we change the option to Cutout, the available options in the horizontal position drop-down get weird, like it defaults to -

![image](https://user-images.githubusercontent.com/65363206/192612757-a602aa5c-18be-4218-9ced-db876daa6054.png)

Maybe - means "behind the text"? That is a cool option to have, and I can see uses for it. But maybe "Behind Text" would be better? Or is it a UI mistake?

So here is the weird(er) bit: I hit Print to PDF on the above configuration and got this: 

![image](https://user-images.githubusercontent.com/65363206/192613969-4481d216-7331-47ad-92e8-25cffabdcbc5.png)

BUT, when PTXprint was brought into focus, the Details tab showed "Right" in the horizontal position list (even though I had done nothing, and the option "-" is still in the drop-down list): 

![image](https://user-images.githubusercontent.com/65363206/192614100-c27dc47d-b90b-40a9-8bdf-7b0fe5896e96.png)

**Comment by davidc86** [comment]
Changing this to Left did move the Chapter number, but not the text.

![image](https://user-images.githubusercontent.com/65363206/192614965-940a1140-b370-49f0-9d19-042a6abaafe4.png)

**Comment by davidc86** [comment]
If I set the Anchor to v2 rather than v1 (I've mirrored the image here), we get this: 

![image](https://user-images.githubusercontent.com/65363206/192619680-57f0b7af-33d5-46c9-aa9a-4c4ad307804d.png)

This is EXCELLENT! So hopefully the only problem is anchoring it to v1. (At this point, I'm not sure I want to fiddle with this any more for fear of breaking it.)

**Comment by mhosken** [comment]
Given the complexities of cutout images and cutout chapter numbers, I am inclined to accept the folk wisdom of "don't anchor a cutout image to v1". But this would require some deeper research to see whether it is true and/or if there is a fix.

**Comment by davidc86** [comment]
I just verified that in v2.2.27 this issue still shows itself.  So if anchored to v2, we get the above picture in 2.2.27. But if anchored to v2 we get this:
![image](https://user-images.githubusercontent.com/65363206/193376360-79c2b7d0-ae78-40ca-8be5-8d55ccc6ee56.png)

That is consistent across PTXprint versions now. So this is a "bug" of a sort. One option is the warn people if they have selected anchor a cutout picture to v1 (or disallow it with a popup warning). But at least let the user know that anchoring to v1 will not yield the results they are looking for.

**Comment by davidg-sil** [comment]
A question for you.... I see you're using 'Chapter number in cutout' in a  poetry book.  Is this a deliberate design decision? I'd feel that  poetry looks better if it doesn't have chapter number cutouts in it, and instead the book used a vernacular equivalent of `\cl Psalm`  at the top of the file (before `\c 1`).

I've not tested if `\q1` and friends affect picture placement, but they might well.

**Comment by davidg-sil** [comment]
@davidc86  My test-case for #757 is behaving properly. When the next release happens, could you check to see if the over-writing of figures is fixed?

**Comment by markpenny** [comment]
@davidc86 [Non urgent request] Whenever you get a chance, please confirm if this one has been fixed. If so, go ahead and close.
