### ISSUE TITLE
File path has backwards slash on Windows

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#75]
Hover over file in Viewer tab, and the path shows Linux-style slash for the first divider:
![image](https://user-images.githubusercontent.com/14953913/82536997-40c42f80-9b41-11ea-87e1-b043262a65c8.png)

Same is true on the Folder Paths in the About tab of the Viewer as well.

**Comment by markpenny** [comment]
The bane of cross-platform development :-) \ / / \/ /\ /\/ \/  - I'll look into it Thanks for alerting me.

**Comment by davidg-sil** [comment]
At least in the past, windows libraries accepted both slashes... but yes, we can't  deliberately confuse the users, can we?

**Comment by mhosken** [comment]
No but we might do it unwittingly ;) I don't think anyone intentionally confuses users.

**Comment by markpenny** [comment]
@mhosken Given how many times we deal with paths, should we add our own customized os.path.join function which ensures we're using all / or \ depending on OS? That would spare us a lot of fiddling about with .replace("\\", "/") all over the place. However, there are some places (like in the .tex file) where it always wants/them/that/way, so we need to be careful not to trip those ones up.

**Comment by davidg-sil** [comment]
Does it had a path.split too? Then  OS.path.jointhe result of that? and a
then a tex.path.join()

Speaking out of pure ignorance, with autospell trying to help too

>

**Comment by mhosken** [comment]
We should probably use python3's pathlib and do things properly. And certainly use that over rolling our own.

**Comment by mhosken** [comment]
Restructured to use pathlib, which allows us to subclass and store relative paths in the .cfg file.
