### ISSUE TITLE
v2.2.26 Crashes when switching configuration files within a project

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#750]
I successfully switched to a new Paratext project (after a crash, see #744 ) 
But I didn't notice it has switched to "Default"
I poked around in Pictures, turned on "Only Show Active books"
Was confused by the blank list! Realized it was not using my working Configuration setup.
Switched to Basic page.
Selected my preferred configuration file.
PTXprint Hung. Eventually it closed itself. 

So, I:
Reopened PTXprint, switched to SLU and immediately selected the preferred configuration setup. 
Closed PTXprint, reopened PTXprint, now it is good to go!

**Comment by markpenny** [comment]
I am assuming that this one has also been fixed with the other crashing bug which was fixed yesterday. Please confirm.
