### ISSUE TITLE
Force Pagebreak option before colophon doesn't work

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#751]
Here is my settings:
![image](https://user-images.githubusercontent.com/65363206/193376656-0f78ee13-b3d1-47ba-bd66-954a4950f236.png)

Here are the results:
![image](https://user-images.githubusercontent.com/65363206/193376669-2065497d-2a3a-4620-8d56-a4bda60804d1.png)

Checking and unchecking that option makes no difference.

**Comment by davidc86** [comment]
Sorry, but I don't think so. I just turned the colophons on for my project and when it tried to create the PDF, I got this: 

![image](https://user-images.githubusercontent.com/65363206/194948928-352f5ee2-cd5d-4bb1-8594-9e9867bf6cf8.png)

**Comment by davidc86** [comment]
My TEST colophon looks like this: 

\ipc \bd Brit Eras Markus ikeskye\bd*
\ipc ti tel Maslyarkwe, Maluku, Indonesia

\ipc \bd Kabar Baik yang Markus menulis\bd*
\ipc dalam bahasa Selaru, Maluku, Indonesia

\ipc \bd The Good News which Mark wrote\bd*
\ipc in the Selaru language, Maluku, Indonesia
\b
\ipc \zcopyright
\b

\ipc \zimagecopyrightsID
\b
\ipc \zimagecopyrightsEN
\b
\ipc Buku ini ditulis dalam bahasa Selaru [slu].
\ipc Untuk informasi atas bahasa ini, mari menuju ke situs:
\ipc https://www.ethnologue.com/language/slu
\ipc dan
\ipc https://www.bahasaselaru.org

\ipc Buku ini disponsori oleh:
\ipc Yayasan Pemberdayaan Masyarakat Desa
\ipc Jln Ki Hajar Dewantoro
\ipc Saumlaki, Kabupaten Kepulauan Tanimbar, Maluku 97664
\b
\ipc Edisi Percobaan
\ipc YPMD-KKT

**Comment by markpenny** [comment]
Hi @davidc86 - thanks for testing this. I also got it to fail with the above colophon text, but when I changed \ipc to \pc **everywhere** it worked as expected.

![image](https://user-images.githubusercontent.com/12962708/194976070-ed5a93fb-6725-49c3-a23b-80048953a018.png)

I'll let @mhosken or @davidg-sil explain why that might be, but at least you have a workaround for now.

**Comment by davidc86** [comment]
Glad you narrowed it down. But I'm still not getting it. I edited the \ipc SFMs, and I still get the error message: 

![image](https://user-images.githubusercontent.com/65363206/195489647-26fce1f1-82fc-4869-b8cb-ac156ef0acdf.png)


Here is the colophon as it now stands (and I'm not seeing any problems in the text):

\pc \bd Brit Eras Markus ikeskye\bd*
\pc ti tel Maslyarkwe, Maluku, Indonesia

\pc \bd Kabar Baik yang Markus menulis\bd*
\pc dalam bahasa Selaru, Maluku, Indonesia

\pc \bd The Good News which Mark wrote\bd*
\pc in the Selaru language, Maluku, Indonesia
\b
\pc \zcopyright
\b

\pc \zimagecopyrightsID
\b
\pc \zimagecopyrightsEN
\b
\pc Buku ini ditulis dalam bahasa Selaru [slu].
\pc Untuk informasi atas bahasa ini, mari menuju ke situs:
\pc https://www.ethnologue.com/language/slu
\pc dan
\pc https://www.bahasaselaru.org

\pc Buku ini disponsori oleh:
\pc Yayasan Pemberdayaan Masyarakat Desa
\pc Jln Ki Hajar Dewantoro
\pc Saumlaki, Kabupaten Kepulauan Tanimbar, Maluku 97664
\b
\pc Edisi Percobaan
\pc YPMD-KKT

**Comment by mhosken** [comment]
Please submit an archive (complete with some pictures). TIA.

**Comment by markpenny** [comment]
does it work if you do this:

\pc \zimagecopyrightsid
\b
\pc \zimagecopyrights

Lower case ID and no EN

**Comment by davidc86** [comment]
No, sorry. That didn't work either. Weird eh?

-------------------------------------------------------------------------------------------
PTXprint [2.2.33] - Error!

Failed to create: ptxprint-SelaruNewPublication-INT_XXESLU.pdf

! Undefined control sequence.
\zcolophon ...opyright \b \pc \zimagecopyrightsid 
                  \b \pc \zimagecopyrights \...
\postptxfile ...l}\csname bookend-final\endcsname 
                  \par \fi \singlecolumn \bo...
l.574 \ptxfile{98XXESLU-SelaruNewPublication.SFM}
------------------------------------------------------------------------------------------
This might be related to a USFM marker error (using an unsupported marker).
Try running 'Basic Checks' in Paratext to validate markers.

PTXprint Version 2.2.33
-------------------------------------------------------------------------------------------

It is the same project I've sent several times now. The only difference is if I check the box "Colophon at End of Publication" I get an error. If I uncheck that box, I get a PDF file.

Do the zcopyrightsid need to be defined somewhere? 
The confusing thing is that this used to work with zimagecopyrightsID and zimagecopyrightsEN (which is much easier to read, btw).
[SLU-SelaruNewPublicationPTXprintArchive-Colophon.zip](https://github.com/sillsdev/ptx2pdf/files/9816715/SLU-SelaruNewPublicationPTXprintArchive-Colophon.zip)

Any more clues?

**Comment by davidg-sil** [comment]
Thanks for the archive. I've tested it and can confirm that using `\ipc` isn't causing problem, it's zimagerightsID / zimagerightsFR /zimagerightsid / etc,  my only guess is that Mark accidentally removed `\zimagecopyrightsid` while he was doing that.

I don't know python well enough to really comment but it looks to me like `\zimagecopyrightsid` *ought* to be getting automatically generated after the code has looked for all occurrences of `\zimagecopyrights`  followed by 2 or 3 other letters.  It appears to me  that the code looking for that code expects upper case letters, and later on converts what was input to lower case, but somewhere in that logic it's not actually defining the value.

**Comment by markpenny** [comment]
Thanks for pointing me in the right direction, David. I've got it now. But don't yet know which route to take to fix it.

The problem is that your can EITHER have your imagecopyright credits in the colophon (as you are trying) OR have a Front Matter book (which is assumed to contain the imagecopyright credit lines). In this case, the configuration has BOTH, and it that's why it is getting confused. If you just uncheck "Front Matter" it all works fine.

So, now the question is... what *should* it be doing? I am tempted to disable the Colophon option entirely IF/WHEN Front Matter is enabled. As you don't normally really want BOTH at the same time.

What are your thoughts, @davidc86? Tell me if the statement above is reasonable, and if not, why not?

Yes, either way, we need to fix the UI so that we don't pretend to do something that we can't; and we should probably handle the situation more gracefully too :-) but let's first decide what's the best way forward... (one possibility [if both are turned on] is that it looks in FRT first, and if it *doesn't* find any \zimagecopyrights there that it then looks in the Colophon text next to see if the user is asking for them there).

Sorry that it has taken us so long to get to this point; but it underlines the importance of having and archive with EVERYTHING just as you have it (i.e. FRT ... XXE) and both things enabled. Without that we were just scratching away in the sand like chickens hunting for bugs :-)

**Comment by mhosken** [comment]
Or we can fix it to handle both FRT and colophon. I'm going to claim this fixed since I don't have an archive I can actually test with.

**Comment by markpenny** [comment]
@mhosken  There is an archive submitted above (3 messages earlier)... :-)

**Comment by davidc86** [comment]
Well, logically one probably doesn't need both Front Matter and colophon. But it seems to me it would be easiest just to allow them both and even allow copyright info in both in case for some bizarre reason the user needs such weirdness.

I can see where a user might choose to include Front Matter but use it for something other than copyright stuff.

Also creating a UI that excludes FRT or colophon depending on the content, and making it so the UI is comprehensible, would be way too much work.

Just allow both to be used and allow both to contain duplicate content. The user will need a brain at some point, and this is a pretty low bar. A quick review of the results should get them tweaking things in a better-looking direction.


________________________________
