### ISSUE TITLE
PTXprint switched back to the day's initial Paratext project and PTXprint configuration file!

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#752]
v2.2.27
Sorry. No pattern yet. But this is what happened: 
I had been using PTXprint for over an hour, testing this and that. 
I started with PTXprint in the FRD language and my FRD PTXprint configuration.
I did some testing there (to close bug reports).
I then switched to SLU and my SLU PTXprint test configuration.
I tested several things there too. (Printing to PDF numerous times)
I messed with editing the Front Matter. I also edited the SLU INT book in Paratext and saved it and then printed again from PTXprpint.
Then when I was about to print again to test more tweaks, I saw the PTXprint window flicker. 
I then hit print, and it opened up the FRD project PDF!
Weird. But thinking maybe Sulawesi PDF software just switched tabs on me, I go back PTXprint to look at the Front Matter. NOTHING THERE! (Yikes, about to write a bug report about Front Matter disappearing!)
But looking around in PTXprint I finally noticed that the listing of Pictures were not the ones we are testing in SLU, but the ones we are testing in FRD! So going to the Basics tab, I see that PTXprint has reverted to my day's start-up configuration! It is like something restarted PTXprint, and it reverted in a flicker.
The good news is that the tweaks for testing I had made in SLU configuration were still there, I just needed to switch it back.

Like I said, weird. 
I assumed "Save" or "Print to PDF" would bookmark the current configuration and project as the one to use next time PTXprint opens, but apparently not. Right now, if PTXprint crashes even after printing and Saving multiple times, on restart it will revert back to whatever it started with that day. I think users expect it to update that startup Project and configuration specs on Save and on Print.

**Comment by markpenny** [comment]
This almost makes it sound like 2 different instances of PTXprint were open at the same time and you somehow unknowingly switched between them (which wiped out the settings). I know it is unlikely to be true (given that you are an advanced user/tester) but is it possible?

MH is away today, but can probably look next week; although it will be a pain to reproduce and track down...

**Comment by davidc86** [comment]
You are absolutely correct!!!
I had two instances of PTXprint running at the same time. 
I only noticed because when I was shutting down and one of them was on my external monitor, and behind the Sumatra PDF viewer.
WELL, this certainly adds weight to my request elsewhere that the Start up for PTXprint is waaaaay slow, and there needs to be some kind of indication that it is launching. On my very fast machine it takes over half a minute to show up. And from the click time until the first sign of life there is no indication anything is happening.

**Comment by mhosken** [comment]
Quicker than paratext then ;). Could you run ptxprint from the command line
with "-l debug". Then exit after it takes a long time to start and send the
ptxprint.log file that is created in the directory you were in when you ran
ptxprint. Don't worry if it takes a few runs before it's slow, just run
ptxprint -l debug each time and the grab the ptxprint.log when you get a
representative run. Remember to quit befor grabbing the log file.

**Comment by markpenny** [comment]
> send the ptxprint.log file that is created in the directory you were in when you ran ptxprint.

Actually on Windows it ends up in a location like this:
`C:\Users\<Username>\AppData\Local\SIL\ptxprint\ptxprint.log`

But very glad to hear that we don't have to go looking for a rare obscure bug next week! But you have raised an important topic of whether we should allow/prevent multiple instances of PTXprint to run (especially when connected to Paratext) -- especially when you consider the negative consequences when a user does so by mistake.

**Comment by davidg-sil** [comment]
I wonder if a per-project lock would be the right solution?  I can see it really useful to have 2 PTXprints running e.g. when fiddling with a diglot, or to check what settings you've used on another project. Just as long as when you accidentally try to open the same config twice it moans "You already have this project open, only press 'I know the risks and don't care what chaos my settings end up in'  if you really mean it." My ideal wish-list would include another button to bring the lost instance to the front, unminimised.
Or how about an 'open in read-only mode'?  But I guess that would need quite a careful combing through code to 
avoid gotchas.

**Comment by davidc86** [comment]
I like the idea of having two+ instances of PTXprint, so I can compare configurations between projects.

But for sanity's sake I don't think we should be allowed to open the exact same configuration file in two different instances, unless both are editing the exact same memory space (any change in one is an instant change in the other--Shoebox/Toolbox did this and it was fine). So if that kind of instant awareness is not doable, then I suggest blocking/locking each configuration file that is already open in another instance.

(BTW Notepad++ can instantly tell if the file it is displaying has changed, and asks if we want to refresh the content, so something like that would work too. But maybe the user should not be allowed to refuse to refresh the content in PTXprint? I can see where this could become a dog chasing its tail.)

Two+ instances would be good/useful. The ripples are for you all to decide!

Regardless, Thanks for this amazing tool.

His Grace, insight, and patience in the tedious bits be yours,
David

________________________________

**Comment by markpenny** [comment]
I suggest that we WAIT on doing anything further on this one until we have ironed out all the (similar) issues surrounding Paratext integration. Some of what you're asking for may come out in the wash anyway...

**Comment by markpenny** [comment]
@davidc86 Can this issue be closed now? Or is there still something that needs to be done?

**Comment by davidc86** [comment]
Sorry Mark,

Yeah, close that out. If this kind of problem surfaces again, I'm sure you'll get a lot of pings. It looks like that was an old integration glitch as that was from 2022!

I haven't had a chance to test this again, but the most interesting bit in all that verbiage was this: "I assumed "Save" or "Print to PDF" would bookmark the current configuration and project as the one to use next time PTXprint opens, but apparently not. Right now, if PTXprint crashes even after printing and Saving multiple times, on restart it will revert back to whatever it started with that day. I think users expect it to update that startup Project and configuration specs on Save and on Print."

I'm not sure where the "Start with this configuration file" information is kept, but apparently it wasn't being updated until PTXprint was exited with grace and happiness. Is this how we want it to behave? (Hopefully PTXprint will never crash again, and this is a moot point!)

Thanks for the reminder that I have a few outstanding bugs still open. I need to put those on my list to deal with.

Blessings on you all,
--David
________________________________
