### ISSUE TITLE
The \nopagenums  flag doesn't work in other books

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#755]
We use the PTXprint Front Matter for doing the very front part of the book.
But we use Paratext's INT book for the Grammar section and other "guidelines" for symbols using in reading the text.
We don't want page numbers to print in this INT book either. 
The flag \nopagenums  works fine if put in PTXprint's Front Matter file.
But \nopagenums  does NOT appear to work in other books. 

(We added \nopagenums to the INT SFM file in Paratext, but the PTXprint Final SFM view does not show the \nopagenums marker. So, does it get deleted out?)

**Comment by davidg-sil** [comment]
I think that non-scripture books ought to have some kind of quad-state: option: no pagenums / roman numerals / normal page numbers / Prefix  / Suffix.
But you can almost certainly do it with \addtrigger  or \sethook in ptxprint-mods.tex

**Comment by markpenny** [comment]
I believe this one has been resolved recently, particularly as the INT matter needs to be pulled into the FRTlocal book, so numbering is controlled there.
