### ISSUE TITLE
Pictures not positioning correctly and not taking changes to position

### ISSUE THREAD

**Issue by LouKehler** [sillsdev/ptx2pdf#760]
I am using pictures in a publication and have been struggling to try to make them position correctly. I think I have found out why. I am using cutouts:

    GLO p007 |src="LB00186B.TIF" size="col" pgpos="cl-1" ref="1â€:0" scale="0.3"

When I select to only print the GLO then I get the correct positioning:
![GLO Only](https://user-images.githubusercontent.com/39006144/197064844-1374346e-f14e-400b-b7c8-504e7712c2f1.jpg)

Without changing anything, I print the whole NT and get a different (incorrect) positioning:
![GLO in whole NT](https://user-images.githubusercontent.com/39006144/197064864-846508a7-23f8-4596-8e4d-78aa90165661.jpg)

If I run each of these jobs twice in a row their positioning doesn't change, even though they share the same "ODK-Default.piclist" file.

I have created a screen capture video 

https://user-images.githubusercontent.com/39006144/197064959-8389174d-7888-4d58-9680-d6920a2e80bc.mp4

 that shows the following:

    I change the number of lines from 1 to 0, printing both times and there is no change.
    I restart PTXprint and print again and there is no change.
    I change the number of lines from 0 to -1 and there is no change.
    I change the scale to 25 and back to 30 and and there is no change.
    Finally, I include all books in the NT and print and the picture is a line higher.

I tried tidying up to force it to generate the intermediate files. This turned up another problem. This video shows 

https://user-images.githubusercontent.com/39006144/197065075-e35bfceb-1389-49d2-97d8-8c21ccd50d0d.mp4

that it now gets missing files ./tmpPics/lb00186.jpg" etc. because it didn't regenerate the temporary picture files.

Switching to printing only the GLO does the same thing, generating boxes where the pictures should have been.

When I restart PTXprint, this time it includes the pictures and printing GLO and the whole NT produces the same result as printing GLO by itself with the correct positioning parameters:

https://user-images.githubusercontent.com/39006144/197065137-a46eba04-4ffb-468e-a671-47b5a8957957.mp4

I am seeing a workaround as I put together this problem report. It seems to update the picture properties properly when I follow the following procedure:

    Make a change to the picture parameters
    Tidy up
    Restart PTXprint
    Print

It seems to me that one of the temporary files is not being properly regenerated when changing the picture parameters. Each different configuration of print has a different set of temporary files which is why I was getting one placement for the whole NT and a different one for just the GLO.

I tried to isolate which temporary file in the local/ptxprint folder needed to be deleted to see if I could avoid restarting PTXprint because changing parameters was getting tedious but it seems the restart is necessary to flush some of PTXprint's cached settings.

**Comment by davidg-sil** [comment]
Anchoring a picture to something that moves easily, like the middle or end of a paragraph means that if the anchor point moves, the picture moves, which means the cut-out needs to move and that reshapes the paragraph which means the picture moves, etc. 

Anchoring to paragraph start is much more predictable. Can you try to anchor to the keyword, (GLO k.TheKeywordWithNoSpaces) rather than something mid-paragraph? It ought to improve stability a lot.

**Comment by davidg-sil** [comment]
I've seen (complex) situations where a picture could end up cycling between  four different locations, every subsequent run moved it to the next one.

If the picture placement (or rather, the cutout position) is not ultra-critical, then you could allow more slop in the position. I.e. if the slop is set to 3, then if it works out the picture's cutout starts on  line 14 of the paragraph but you wanted it on line 11, it counts as good enough and doesn't move it any more.  It takes some detective work to identify the figure. For details look for  `\setCutoutSlop`  in [figures.md](https://github.com/sillsdev/ptx2pdf/blob/master/docs/documentation/figures.md)

**Comment by davidg-sil** [comment]
Sorry, I've just understood what you're doing. I think these are mentioned in figures.md:
1. The slop setting mentioned above is (+/- 2) for figures.  Therefore, tweaking the position it has found by 1 may not work. 
**Work-around:** If it was at +1 and you want it to move to 0, say, then start by moving it to +5, do a quick-run and then set it to 0. It will not find a good position for +5 that is equally good for 0. 
Alternatively, remove the `whatever.delayed` file, but that migth mess up the positioning of any earlier images.
2. Negative cutouts cannot affect a proceeding paragraph, so if you give a negative offset with a start-of-paragraph anchor, you risk the image crashing into text.

**Comment by markpenny** [comment]
@LouKehler Just checking to see if this issue has been resolved for you. If so, please go ahead and close it. If not, let us know what else you're waiting on. Thanks.
