### ISSUE TITLE
Indonesian and English Illustration copyright lines are the same

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#762]
v2.2.34 Including both Colophon and FRT matter now works, thanks! 

PROBLEM: the Indonesian and English Illustration copyright lines are output the same!
 
![image](https://user-images.githubusercontent.com/65363206/197667368-f1684f7f-5bc1-43dc-9b4f-258c9818c3dd.png)

It used to be that the \zimagecopyrightsID field gave an Indonesian translation of the copyright text. Whereas \zimagecopyrightsEN (or simply \zimagecopyrights) would give the English version. Now they output the same text.

**Comment by markpenny** [comment]
@davidc86 It looks like you might have been using a self/locally localized picCopyrights.json file which was working fine until we made a minor change to that file and then (most likely) overwrote your localized version. (BTW - there is a very subtle difference above, and/dan which shows that the code is working fine, but we haven't got your "id" = Indonesian localization data).

Could you check on your system, or in your backups for an (older?) version of that file which *does* include the "id" translated strings? And if you find that and send it to us, we'll ship it in a subsequent version along with the other languages.

**Comment by markpenny** [comment]
Update: I have sent the picCopyrights.json file to DC/RN to localize into "id". No other work is needed for this issue. So closing it.
