### ISSUE TITLE
In Basic View > Notes+Refs > Cross references tab is empty

### ISSUE THREAD

**Issue by ianhewubs** [sillsdev/ptx2pdf#767]
Version 2.2.37
In Basic View > Notes+Refs > Cross references tab is empty. In the previous version I used, it wasn't empty for this Paratext project.

**Comment by markpenny** [comment]
Thanks @ianhewubs for discovering this oversight. It took a while to find it, but was an inadvertent regression. Fixed now for 2.2.38 which should be released soon. Nice catch - thanks!
![image](https://user-images.githubusercontent.com/12962708/199620548-0b27903c-59a9-4268-a7cd-d116be2459cd.png)
