### ISSUE TITLE
Filter glossary option breaks chapter titles

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#768]
If the glossary is segmented into chapters (for starting letters) like this:
```
\imt Dikcionari 
\c 1 
\cl A 
\p \k Aaron\k* ....
\p \k Azerty \k* ...
\c 2
\cl B
\p \k Balam\k* ...
\p \k Barnabas\k* ....
```
Users will almost certainly expect that the processing would split the file so that `Azerty` not appearing in the text would not delete the chapter number or chapter label.

It seems at the moment that chapter labels are preserved but chapter numbers are not, which then means you get things like this in the output:
![image](https://user-images.githubusercontent.com/58848232/199577573-c647a9f4-fa77-404f-b958-8bbae9dd9b14.png)

What seems to be happening is that:
*  `\c 2` has been deleted. 
* `\cl Ä` is then taken as setting a 'global' pre-chapter label, that should apply to all following chapters.  
* Because that is set, when `\c 3` is met, it is immediately printed out with the 'global' label. Then `\cl B` is met and so on.

The glossary can (nominally - actual behaviour in all of Paratext's functions is a bit less reliable) be split into chapters and verses. 
I would suggest that the glossary first be segmented into chapters and verses and *then* split into key-words.

**Comment by mhosken** [comment]
Don't use \c for these. Use \s or some other \zs or whatever. This is not about chapters surely? If they do use chapters then use a change to remove them and turn \cl into \s or whatever
