### ISSUE TITLE
widow & club/orphan lines - per paragraph style setting?

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#769]
eTeX  (and thus XeTeX) allows `\widowpenalties 3 10001 10002 0`  to specify a penalty 1 line, 2 lines, 3+ lines before the end of the paragraph. Similarly `\clubpenalties` 
The number of allowable lines possibly should be set for different paragraph styles, either by some kind of heuristic that defines `\q` lines as poetry, etc, or simply as a stylesheet addition. (which could then be overridden by more specific styling).

**Comment by mhosken** [comment]
You can do this using \sethook{end}{q}{\widowpenalties 3 10001 10002 0} etc.

**Comment by davidg-sil** [comment]
Yes indeed. I was wondering if:
there was mileage in a few `\def\poetrylinebreaks{\widowpenalties....}` `\def\wisdomlinebreaks{.....}` `\def\normallinebreaks{...}`
etc would help things along,  and whether doing this in the stylesheet would be a useful addition for those who didn't want to go through their every paragraph style and set a (possibly conflicting) hook.

**Comment by mhosken** [comment]
Maybe we need \addhook. If something is generally useful, we could add UI for it. I doubt many users (if any) will multiline widowpenalties.
