### ISSUE TITLE
custom script needs to use telepathy?

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#77]
The custom script gets called with no command line parameters nor any environment variables that might give it a hint about where it should be  running,  what the files it should be working on, or where they should come from.

Furthermore, when multiple books are used,  it gets called once for each new file, again with no apparent info about which one it's supposed to be processing. My guess is this is a bug!

**Comment by markpenny** [comment]
:-)  The Windows side calls the script (along with the full path) and passes 2 parameters (1) file to be processed and (2) processed file. - both with their entire path. So, for example, a batch file could be called that uses %1 and %2 to process the entire book (yes, one file at a time).

I'm not sure what the Linux side does yet, but you are right that we need to document all this before we ourselves forget how it works... :-)

Eventually we'd like to be able to call TECkit maps directly (without having to pass parameters around) and even CC tables. Maybe next month.

**Comment by davidg-sil** [comment]
My linux command is getting nothing on its command line.
Re CC / TECkit... I'm sure it's possible to re-write my current perl code for dealing with paragraphed quotation style into a CC table, but I'd rather not! I.e. please keep the ability to keep it any script at all.

**Comment by mhosken** [comment]
That's a bug, it should be getting input_file output_file. If we supported CC or TECkit, this would not detract from supporting a script file of the user's choosing.

**Comment by mhosken** [comment]
Fixed in 1bc1687. The moral of the story is you can't pass command line parameters as a list to Popen if you set shell=True.
