### ISSUE TITLE
Image selection from outside Paratext directory breaks after the first time round.

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#771]
I don't know if this is just sidebars, but if I select a foreground or background image that is outside the Paratext tree (e.g. from my `~/pictures`  directory) and print, then the picture displays perfectly. If I then return to the settings file, e.g. to change the picture size or position, then PTXprint 'corrects' the displayed image location from "`~/pictures`" to "`~/Paratext8Projects/pictures`".

I assume that what it ought to do is either leave the name alone, and assume that others are going to get a copy some other way, or copy the image to under ProjectName/shared/, but it doesn't do either of those things.

**Comment by markpenny** [comment]
I am hoping that we fixed this when working on Covers. Could you confirm either way, and close it if it is now behaving.
