### ISSUE TITLE
Is there any way to print a whole book chapter by chapter (with each chapter starting on a new page)?

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#774]
USE CASE: When we do consultant checking, we'd like each UNS to have their own copy of the chapter, formatted nicely, with all the footnotes, pictures, extra line spacing and larger letters than the final publication, e.g. a UNS Checking Scripture Copy

ISSUE: The consultant only wants the UNSs seeing ONE chapter at a time. And for large books (like Matthew with 28 chapters!)  it is very tedious to select the chapters to print in the Basic boxes: "From chapter 1 to 1" and then format the PDF and print it, and then changing these to "2 to 2" and then format the PDF and print it, and then "3 to 3" etc. all the way through all 28 chapters. (I tremble to think of Psalms) So the formatting and printing of each chapter must be done one chapter at a time. 

NEEDED: A check box that says, "Start each chapter on a new page." Then we could print all 28 chapters, and PTXprint would export the whole book with page breaks before each chapter, meaning we can very easily divide them up and stable them and distribute them individually.

Does this option already exist? If so, I haven't found it yet. I looked on the Body page, and it has "Always start 1st chapter on a new page", so it would be logical to add "Start EACH chapter on a new page" on the Body page too. This simple enhancement would save a huge pile of clicking and tweaking for the end user.

**Comment by markpenny** [comment]
Yes, we offer that for \c 1 but not for ALL chapters:
![image](https://user-images.githubusercontent.com/12962708/201923155-09d42107-7aa7-4cca-a85d-64061489ed4e.png)

But DG's suggestion works fine for now as a workaround. One of my questions for the consultation is "What principle(s) should we use to decide whether to add such feature requests to the UI, or leave them as documented DIY snippets?"

**Comment by davidc86** [comment]
I just verified the "hack" solution 
'\\c ' > '\\pb\\c '
in the change file works! Woo-hoo. That is nice. And it gives us what we need.  Thank you for that solution.
Just thinking that we might not be the only ones who would have a need for this feature/capability.

**Comment by davidc86** [comment]
I wish I could attend! If for no other reason than to hang out with you all.

Yes, every tweak to the UI is a costly decision. So I understand why you might need to give it significant thought first.
As you say, every UI faces feature creep, and it is hard to keep a UI clean and easy to use, while being also feature rich. 

I've shared the "hacked" PTXprint configuration for printing a whole book chapter by chapter with the team, and they will be using it right away. Again, thanks for that. (You all can choose to close this or keep it as a "Request")

**Comment by mhosken** [comment]
Closing since we aren't going to add it to the UI
