### ISSUE TITLE
Incorrect default (reset) value calculation for note character styles

### ISSUE THREAD

**Issue by klassenjm** [sillsdev/ptx2pdf#775]
I was adjusting the font size for footnote and cross reference origin references. After some experiments, I decided to reset the values to their default. I understand that in the Styles editor this can normally be done by clicking on a **bolded** UI field label.

When I did this for `\fr`, and ran Print, it seemed as though the fr's disappeared in my layout. Then I noticed that the settings which were reset seemed odd. The font scale was set to 0.08, with Scale Relative to Parent enabled (although I'm not sure if that got enabled by resetting -- probably not). The result being 0.9pt.

![image](https://user-images.githubusercontent.com/4420391/202736607-21a3b864-2c0e-4873-b13d-16f459260a4c.png)

**Comment by davidg-sil** [comment]
I've seen something like this sort of thing if you have a custom style sheet loaded which also affects a marker you're adjusting through the GUI. (I can't remember if it was custom.sty or another one), it can get confused about what the 'normal' value is.  If an edited .sty file accidentally sets an odd value, PTXprint will think that's 'normal' and then you might fix it in the file and it seems to *still* think the odd version is the unedited one and even impose that, if I remember correctly. I hope that makes sense.

**Comment by klassenjm** [comment]
Thanks for your reply, David. I do have a `custom.sty` in this project -- but only a few overrides there, and not related to `\fr` or `\xo`

**Comment by markpenny** [comment]
This has been fixed now, and should be working more predictably in 2.2.44
