### ISSUE TITLE
The styles no longer default to the Font we set as default

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#779]
First off, for some reason, my project suddenly had Graphite specified for my Font. I don't need Graphite anywhere in our projects, at least until we try hymns or something with Jon Coombs' music notation font.   

Why is GR turned on by default?
Turning it off on the Font page did not turn it off in the Styles page.
How to get the universal Font reapplied to all the Fonts that are currently unmarked as to typeface?

**Comment by mhosken** [comment]
Close until we can reproduce it
