### ISSUE TITLE
Callers in footnotes have variable width

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#78]
If you look really carefully, the \xo text  doesn't quite line up in cross-references. I guess footnotes are similar. 
![Xrefs2](https://user-images.githubusercontent.com/58848232/82565405-0b403600-9b83-11ea-8137-fb4c56adf21d.png)

This of course only shows up when the notes are one below another. But would it cause any problems if I put a fixed-width box (say, ```\hbox to 1.2ex{ ... \hss}```) around all the callers?

**Comment by mhosken** [comment]
Almost certainly not and you can do that using a style character marker for the \NoteCallerStyle and then using start and end hooks to do the box.

**Comment by mhosken** [comment]
btw there is nothing stopping you putting hooks into your .sty file.

**Comment by davidg-sil** [comment]
Fix committed

**Comment by davidg-sil** [comment]
Change implemented. There was already a box, so I set a width for it and
put a  \hss either side.

.
