### ISSUE TITLE
copyright picture label is too high

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#780]
![image](https://user-images.githubusercontent.com/65363206/202852442-7897a73d-a721-4436-8525-cb358afe98fb.png)

It used to put the label right at the bottom edge which was nice. Now it puts it a good ways up inside the picture, which is not desirable.

It would be even better if we had the option to add a blank area below the illustration and placed the label in that area, so it never overlaps with the illustration itself. (For rotated left right placement a slight extra white space on the sides would allow for the label to go up the side without overlap either.)

**Comment by davidg-sil** [comment]
There is a parameter `\FigCreditPadding` which you can define, e.g.:
```
\def\FigCreditPadding{1pt}
```
This is the size of the coloured box the credit text is put in, but also positions the text (as the credit box hugs the edge). TeX crashes if you make it negative, but you can put it to 0pt if you want your descenders hitting the edge.
 I assume you know that you can set (any) background colour to help with contrast.

**Comment by mhosken** [comment]
@davidg-sil anything more to do on this or is this issue done?

**Comment by davidc86** [comment]
Sorry, I'm a bit of a noob and I only test and use what is provided for us to use in PTXprint. I have no idea where to put the line:

\def\FigCreditPadding{1pt}

Nor do I know how to change the background color other than using the copyright dialog in PTXprint. This is currently experiencing another glitch. See #776

**Comment by davidg-sil** [comment]
No doubt, eventually, @markpenny  could add it to the TeXpert Hacks page, I don't know how it's escaped so far.
For the moment, the line would need to go into ptxprint-mods.tex, on the advanced tab. 
![image](https://user-images.githubusercontent.com/58848232/230013860-11fa3107-7e3b-4213-8c96-11f85dcd6d58.png)

Make sure the box is ticked / checked, click on edit, and add it to the opened file. 
A `%` sign makes everything after it a comment

![image](https://user-images.githubusercontent.com/58848232/230014879-cff76ddd-4e43-423b-a3af-3c84653822ca.png)

**Comment by davidc86** [comment]
Thanks for that clarification. That seems to adjust the text within the text box. But my main issue is with the position of the text box itself.

Here it is set to the default {1pt}:

![image](https://user-images.githubusercontent.com/65363206/230087090-2782f968-428f-4466-b342-d8e63e479e07.png)

Here it is set to {0pt}: 

![image](https://user-images.githubusercontent.com/65363206/230087268-a5ffc78f-7960-41e7-a541-640166751736.png)

So the text is more crowded in the text box, but the text box itself didn't move down to the bottom of the picture.

**Comment by davidc86** [comment]
BTW, I like the vertical look of {0pt} but not the horizontal look (the "k" butts right up against the box (i.e. "0") , so a vertical zero and a horizontal 1 would likely be more useful to folk.

**Comment by davidg-sil** [comment]
See my comment on #853
