### ISSUE TITLE
Question, is PrintDraftChanges.txt format in CC?

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#783]
I'm trying to remove \b if it happens to occur before a \s or \s1
So, I added this to the PrintDraftChanges.txt files:

# REMOVE \b before \s or \s1
# ------------------------------------------------------
  '\b ' \n  '\s '                 >  '\s '
  '\b ' \n  '\s1 '               >  '\s1 '

It is the "Enter" command that I don't know. I also tried CC's nl keyword, but that didn't work either. But maybe my whole approach is wrong. It would be nice for us vintage models to have a way to use CC commands in PTXprint, but what I really need is just help in getting the change table to pitch \b if it is followed by a section heading. (Don't need the extra space.)
Thanks!!

**Comment by mnjames** [comment]
Without testing, I'm guessing it's something like
'\\b( )?(\r)?\n\\s ' > '\\s '

I can't remember if the \b has a space after it when PT outputs it. I do
think that the new line coming from PT is Windows \r\n, but making the \r
optional like I did should work either way.

You can't turn the ' ' marks on and off with changes.txt like you tried.
But you also don't need to.


*---------------------------------------------------------*
*Malachi James*
LT Consultant in Training | The Evangelical Alliance Mission, working with
SIL
+1 262 4562756 | +359 88 212 4021 | ***@***.***

**Comment by markpenny** [comment]
To answer your question, no it doesn't use the 'CC' (as in Consistent Changes) format although I can see why it might appear to do so, as there are a number of similarities. It uses Regular Expression syntax.

@mnjames has a solution that will work (except for the \s1 won't be caught). And presumably if there ever was an \s2 you'd want the \b to be removed from that too. So just removing the final space after the \\s might be enough.

If you want something a little bit easier to read, you could do this:
`'\\b[ \r\n]+\\s' > '\\s'`

This says \b followed by any one or more of the things inside the [square brackets], followed by \s needs to be replace with \s. So inside the [ ] we have a space, a \r =return and a \n = newline. As long as we have one or more of these, the rule will work.

By the way, _these_ kinds of questions would be excellent in the [PTXprint Community forum](https://community.scripture.software.sil.org/c/ptxprint/27), as they help other users too, and aren't really related to a bug/issue.
