### ISSUE TITLE
Picture placement is off (too high by at least 1 line)

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#786]
If I set the Picture to "Bottom", I get this: 

![image](https://user-images.githubusercontent.com/65363206/203013052-63b4725f-1209-4576-96e5-d2725eeb0c88.png)

Here is the settings for that picture: 

![image](https://user-images.githubusercontent.com/65363206/203013159-98f35365-4380-4f25-86b3-415f95c5eff0.png)

**Comment by davidc86** [comment]
I tried to create an Archive, got this error: 
Please send to: ptxprint_support@sil.org



Traceback (most recent call last):
  File "ptxprint\gtkview.py", line 3187, in onCreateZipArchiveClicked
  File "ptxprint\view.py", line 1575, in createArchive
TypeError: __init__() missing 1 required positional argument: 'args'

<class 'TypeError'>: __init__() missing 1 required positional argument: 'args'


PTXprint Version 2.2.40

(Looks the same as my other configuration archive error)

Here is the archive: 
[SLU-PublikasiSelaru-RutPTXprintArchive.zip](https://github.com/sillsdev/ptx2pdf/files/10055126/SLU-PublikasiSelaru-RutPTXprintArchive.zip)

**Comment by mhosken** [comment]
This should be fixed in 2.2.41, I hope
