### ISSUE TITLE
Bug: Indenting in RTL Footnotes

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#788]
If "First Line Indent Factor" is increased in the footnote style, the indent occurs on the left side of the page even though the writing system direction has been set to RTL.

**Comment by mnjames** [comment]
First Line Indent Factor now works for Start Each Footnote on a New Line, but still needs to be fixed for paragraphed footnotes.

In addition, for paragraphed footnotes Left Indent Factor does not work at all, and Right Indent Factor works very oddly (actually, it behaves as if it were First Line Indent).

**Comment by markpenny** [comment]
@mnjames Has this one been solved in the last 18 months? Or is it still an issue?

**Comment by mnjames** [comment]
It looks good now. Thanks.
