### ISSUE TITLE
Diglot periph handling

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#795]
We need to handle periphs in diglot.
Suggestion:
* FRT books get loaded with an active zglot  (setting the current diglot side)
* \zgetperiph|side="L" id="intnt"\\*

**Comment by davidg-sil** [comment]
The TeX side of this seems to be working, but python needs to present each side to TeX so that TeX can do the right thing.

**Comment by JDNystrom** [comment]
@mhosken Martin, please let me know when this is fixed and I will test it on our diglots. --JN
