### ISSUE TITLE
Config parser fails with complex copyright string

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#799]
When a long and complex copyright statement (which also includes an href) tries to get stored in the project config, it crashes with this error:
![image](https://user-images.githubusercontent.com/12962708/208565914-3ba02904-ea4d-4c6e-b4f8-c36ad352da22.png)

I have an offending settings.xml file if you need it.

**Comment by mhosken** [comment]
There is a simple answer to this. Do not do that. Instead put a summary statement in the copyright field and then typeset the rest of the statement into the FRT. I would suggest a copyright statement of merely: "Copyright©2020 by The Pakistan 
Bible Society" given the rest is actually the license statement.

Please don't complain about it crashing when you abuse it so. No XeTeX will not typeset HTML. No you can't put links in your copyright statement. No you may not put more than one paragraph in the copyright statement. No you can't put markup in there. No we are not going to check for the many myriad ways users might try to abuse the copyright statement entry box.

I realise this is coming from the Paratext Settings and so we should probably just strip the whole thing and put in a statement like: Copyright too complex and leave it up to the user to sort out. Perhaps if we see a </ in the copyright message we do that.

I have little time for this kind of behaviour. Perhaps crashing is the best solution and then just tell people to fix their copyright statement. A copyright statement is a statement of copyright ownership. It is not also a full license statement. People should not be putting license statements in their copyright statement.

**Comment by markpenny** [comment]
The problem here is that it was crashing so bad that it didn't let them even switch to a different project (or that's how it appeared to the user). So, I like the idea of scanning for </ and then throwing up an "unsupported" copyright statement. However, I know that there are LOADS of these badly formed <p>© 2018 My Organization</p> statements in the settings as they come in from updates to the PT registry (which is how they get there in the 1st place).

So, yes, I agree that we shouldn't have to deal with bad stuff people put into their copyright field; but the reality is that they aren't usually doing this themselves or even intentionally. And they can't even fix it in Paratext! They have to know to go to the registry and fix it there.

So if it just "happens" to them, we still want people to use PTXprint, and so need a work-around, or a warning; but we don't really want it to bomb out completely.

I'll see what I can do...

**Comment by mhosken** [comment]
This should also not blow up quite so hard, so change to a non interpolating config parser that won't get upset by %.
