### ISSUE TITLE
Graphite fonts

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#8]
I think there needs to be a checkbox in the GUI to indicate when a font is a Graphite font. I think that's the only alternative available nowadays, but if not then maybe a dropdown menu with multiple font technologies (OpenType, etc.)

The underlying code needs to change from
`\def\regular{"Awami Nastaliq:"}`
to
`\def\regular{"Awami Nastaliq/GR:"}`

**Comment by mhosken** [comment]
It *should* work it automatically, but clearly it failed. Perhaps it can't
find the font. It is installed? Can fc-list.exe see it? Don't feel you have
to answer that last question if you are unsure about fc-list.

GB,
Martin

**Comment by mnjames** [comment]
I'm pretty sure it's finding and using the correct font. The reason I immediately associated it with a Graphite issue is because the glyphs are all displaying but are not connecting to each other (a normal behavior of Awami Nastaliq when displayed in a non-Graphite program).

**Comment by mhosken** [comment]
Yes but ptxprint needs to find the .ttf file to.look inside to see if it is
a graphite font.

GB,
Martin

**Comment by mnjames** [comment]
I don't know which instance of fc-list you're accessing. I'm on Windows and have 8 different versions of the file in different places. I'm assuming you're either running it from the PT8 xetex folder, the PT9 folder, or you're unpacking it on the fly (but I can't find it in Temp if that's the case).

The PT8 and PT9 instances of fc-list both see the font.

**Comment by markpenny** [comment]
OK Malachi, MH has fixed this and it is finding the font(s) now, and recognizes them when they are /GR-capable. It also automatically applies any font features that have been turned on in Paratext. The fixed version 0.2.3 should be available later today.

**Comment by mnjames** [comment]
0.2.3 works great. Thanks for doing all this work!
