### ISSUE TITLE
USFM \q indent defaults are terrible

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#80]
I'm not sure why the default settings in the USFM stylesheet for (\q poetry markers) are so bad, but I'm proposing that we do something to fix them (by default).
![image](https://user-images.githubusercontent.com/12962708/82636121-93741900-9c1f-11ea-84c0-90040f74d462.png)

The defaults in PrintDraft-mods.sty are far better and produce what we really want.

![image](https://user-images.githubusercontent.com/12962708/82635967-1cd71b80-9c1f-11ea-97f7-4906cde605c2.png)
But most people won't know that they have to turn on this Stylesheet file (which may or may not exist on their system), and may conclude that the layout is no good.
I'm proposing that we put these settings into NestedStyles so that we *always* do better than the ugly settings currently in USFM.sty.
```
##### Adjust poetic and list indents
\Marker q
\LeftMargin 0.6
\FirstLineIndent -0.45
\Justification Left

\Marker q1
\LeftMargin 0.6
\FirstLineIndent -0.45
\Justification Left

\Marker q2
\LeftMargin 0.6
\FirstLineIndent -0.225
\Justification Left
```

**Comment by davidg-sil** [comment]
My assumption has always been that they're deliberately so terrible to strongly encourage people to edit the style sheet at least once, so they can learn it's not *so* scary.
But actually they're not a total disaster on A4 single column. Maybe someone actually likes that, or something? 
Anyway, you have my support!

**Comment by mhosken** [comment]
Sure, although if single column looks better with different values, then maybe we need appropriate values for single column and double column put in. What happens if you switch back and forth, well you, the user, better do it yourself :)

**Comment by markpenny** [comment]
I'd like to calculate the optimum values based on page size and, more importantly, column width. And then populate the NestedStyles with those values. If they don't like our defaults, they can visit the stylesheet themselves.

**Comment by klassenjm** [comment]
Hi @markpenny,

The default indents do look pretty bad, I agree. I suppose that one explanation is that the stylesheet values were organized around rather large visible indents which would be suitable on the screen, in Paratext, for the translators. And they needed to accommodate from `\q1` to `\q4` with a single wrap indent (even though most projects would not use more than 2 levels)

Even so, the wrap indent is rather too much.

I'm not sure that some of the ideal values for view in PT will ever be as ideal for print layout in small column widths and small font sizes. But, what does the following adapted USFM.sty result look like to you (in PT). These are all increments of the `\p` first line indent.

![image](https://user-images.githubusercontent.com/4420391/82679683-41c89000-9c19-11ea-9fb6-6b567d4e0185.png)

And - how much better is this this than the current default USFM.sty result. Here's a link to an updated .sty file. I can check in these changes to the main USFM.sty if y'all think this is a better starting point.
https://www.dropbox.com/s/al7d3gnb5yo3zu5/usfm.sty?dl=0

Jeff

**Comment by markpenny** [comment]
Hi @klassenjm !
I'm glad to see you keeping an eye on this development. Thanks for engaging with us about the quote marker indents. I **do** like what you're proposing above - especially as it shaves off 1/2" from the wrapped indent (1.25 - .75 =.5 further left). This will make a significant improvement to narrow width layouts, and especially for users of PTlite - where the 1.25" indent almost makes it impossible to edit poetry on a small screen.

Earlier today I came up with my own set of values based on single-column or double-column layouts:

![image](https://user-images.githubusercontent.com/12962708/82691922-59853000-9c7c-11ea-86bb-58f7a46d119e.png)

And I notice that your values are between these two sets (and a bit more logical in their 1/8" step values). We may just go for your defaults instead of making life overly complicated.

So, yes, I'm in favour of the new values in USFM.sty.

**Comment by mhosken** [comment]
I suggest we leave our 'fix' in there until PT's new usfm.sty has been deployed in both currently installed pt9 and pt8.
