### ISSUE TITLE
Failed to output module text

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#801]
I had a user (BB with xltDdgo - [sensitive] archive available on request) report that a particular project would not output any scripture text when a module is applied. It managed to output the scripture reference (using the $(ref markup), but no text.

The flattened USFM text looks like this:
![image](https://user-images.githubusercontent.com/12962708/208577210-17185d69-31f1-4cb9-ab37-997fc96b6538.png)

What is strange is that normal text prints fine for this project; and when this module is used on other projects, the text shows up. So there is something strange with the particular project (or config settings) which is blocking the module from working as expected.

**Comment by mhosken** [comment]
Please include the source module for this.

**Comment by markpenny** [comment]
Here is the module. Please unzip to find the .sm file. (Presumably you already have the xltDdgo archive from earlier).
[TheChristmasStoryHarmony.zip](https://github.com/sillsdev/ptx2pdf/files/11331618/TheChristmasStoryHarmony.zip)
