### ISSUE TITLE
Picture Cutout and Text Formatting fails with negative positioning 

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#805]
I'm using the picture cutout setting, and I need to use the NEGATIVE positioning to move the picture up a bit on the page.
PROBLEM: when the picture moves up into the previous verse, that verse fails to wrap to allow the picture to fit. So some of the text gets cut off!

![image](https://user-images.githubusercontent.com/65363206/210375142-261cad64-8267-4e14-9cdd-e8adb3c6c82e.png)

The yellow is the selected text from the previous verse. 
This picture set to Cutout, Outer, Mirror on Odd pages, and to a position of -4.0 lines from v10. 
PTXprint does all of the picture settings correctly, but the text in v9 does not rewrap to give space to the picture.

**Comment by davidg-sil** [comment]
**Yes.** Negative cutouts do this, it is [documented behaviour](https://github.com/sillsdev/ptx2pdf/blob/master/docs/documentation/figures.md) in note 6 under the table.
You need to anchor the figure earlier (e.g. anchoring  to a paragraph e.g. `PSA5.9=3` ) and don't avoid negative cutouts except where you know there's space.
