### ISSUE TITLE
Tooltips for cutouts and anchors could be improved

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#807]
#805 and  #806 made me look at the tool-tips for cutouts and anchor points in PTXprint.

**Cutouts and paragraph offset**
  The tool-tip might easily give the impression that there is no limitation on negative offsets, whereas there is the very significant one that while the image can be raised,  the cutout can never extend above the start of the paragraph containing the anchor.  Also negative or non-integer paragraph offsets will not work.

I suggest adding the text '_Negative counts for cutouts raise the image, but the cutout will not affect earlier paragraphs. Negative and fractional paragraph counts are invalid_.'

For people to discover this on their own, without there being a tool-tip entry, they would need to go to the help-page, follow the link to advanced technical documentation and look at footnotes  7 on the table in figures.md.... i.e. they can get there, but it's not very  accessible.
 
**Anchor points**
There is no mention of 'Nth paragraph'  (`GLO k.Harp=2` or `PSA 23.4=3`) in the anchors tool-tip.
I suggest adding the text '_Where there are no intervening anchors, you can anchor to the Nth paragraph of e.g. poetry or a keyterm definition, by specifying the paragraph number after an = sign. I.e. GLO k.Harp=2 or PSA 23.4=3. This can avoid the need to insert an explicit milestone to anchor a cutout if there is a page or column break after the start of the verse._

**Comment by markpenny** [comment]
Updated: 
![image](https://user-images.githubusercontent.com/12962708/211439531-4371e2cc-0cc2-4b00-85ed-db042709adea.png)

and:
![image](https://user-images.githubusercontent.com/12962708/211439875-e6d34b9b-edf1-46b1-8d2f-3ed86c6ca387.png)
