### ISSUE TITLE
error when I try to create the PDF

### ISSUE THREAD

**Issue by kylak** [sillsdev/ptx2pdf#809]
Hi,

I have this error after pushing the print create pdf button (I am on Ubuntu 22.04.1 LTS) :
![Capture d’écran du 2023-01-08 00-54-05](https://user-images.githubusercontent.com/16438248/211174543-675a423d-9fea-4560-94de-a0f9bf9c2494.png)

Blessings.

**Comment by mhosken** [comment]
This is saying there is something deeply wrong with the Bold font. Try changing or resetting the main font. Or choose a different one if you can. Otherwise, send an archive or the font file itself. I've never seen a font with not hhea table in it (that's techie).

**Comment by kylak** [comment]
The font was the problem, thanks!
