### ISSUE TITLE
Readme says 'master' branch is stable and follows paratext branch

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#81]
I don't think we can call master very stable these days. [Ed: bug found]

**Comment by davidg-sil** [comment]
Yet another footnote-eating bug detected, in master.

**Comment by davidg-sil** [comment]
OK, for posterity... bisecting shows that at least half this bug has been present in all versions since PTXplus was merged in :-(
Early verse in 2Jhn has a footnote, last verse has a footnote, at certain \LineSpacingFactors the text fits on the page but the footnotes vanish, possibly being pushed off the page. The last 5 lines of the text are pushed onto the next page (with last verse, and caller).

To add to the excitement, if \unbalancedfalse is set, then the left column contains lines 1,2,4,5, while line 3 is in the right hand column. The caller is in line 4.

**Comment by markpenny** [comment]
@davidg-sil You're doing a great job of finding them for us - and fixing them too. I've just pushed 0.6.9 up to the [site](https://software.sil.org/ptxprint/) with today's tweaks and fixes. We're still very much in beta testing mode, and dangerously working on the 'master' branch; but I think people know that this is a work-in-progress, so expect a few rough edges.

**Comment by davidg-sil** [comment]
My suggestion is we change the readme blurb... beta test, known bugs, etc.

**Comment by mhosken** [comment]
fixed? in bd00848.

**Comment by davidg-sil** [comment]
Real bug (missing footnotes / verses) seems fixed in [2c076e3](https://github.com/sillsdev/ptx2pdf/commit/2c076e33220ba3e28ba2fcf3f84dd8834402000a)
