### ISSUE TITLE
Support numerals from other writing systems

### ISSUE THREAD

**Issue by JimSmith763268** [sillsdev/ptx2pdf#811]
It would be nice to be able to have chapter and verse numbers displayed in other writing systems. [Here is a list.](https://en.wikipedia.org/wiki/Hindu%E2%80%93Arabic_numeral_system#Glyph_comparison)

**Comment by mhosken** [comment]
Yes you can do that now. For any marjernor for the main body fonts  when
you set the font in the font selector, you can set a digits mapping there.
The button is at the bottom of the font dialog. It has a big list to choose
from.

**Comment by JimSmith763268** [comment]
Thanks for the quick reply! From "Fonts+Scripts" I see buttons under "Font Configuration". Then I get a font configuration dialog. But I don't see anything to do with digit selection. The "Typeface" combo box doesn't have any relevant settings. Am I looking in the wrong place?

**Comment by mhosken** [comment]
Enable full mode

GB,
Martin

**Comment by JimSmith763268** [comment]
Ah, thank you. Is this all documented someplace and I missed it?
