### ISSUE TITLE
\fp causes Diglot to fail

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#813]
If one of the texts (in my case, the main one) has \fp in footnotes and I try to print a diglot, the printing fails. This happens even if I tell PTXprint not to print footnotes.

I've discovered that the problem can be fixed by adding this line to the Changes.txt file
`'\\fp\*' > ''`

I think that during the merging process (or maybe during it's normal prep process), PTXprint is changing \fp to actual new line markers. The .sfm file shows a blank line where that \fp marker used to be. So I think if that's happening then that process ought to also remove the \fp* marker.

I've submitted an archive to the support email.

**Comment by davidg-sil** [comment]
You are probably right. The *other* issue is that \fp just plain breaks the footnote handling.  The code *assumes* that it will have no knowledge of how wide the footnote paragraphs will be at the time the notes are read, and therefore puts each note into a single run of text that can grow to be infinitely wide. When it's 'print out the footnotes' time, it then takes those (potentially) very long lines and try to re-arrange them into paragraphs or at least paragraphed notes. 
For some (not very strange) reason, it gets upset if you try to put a line break in to a run of horizontal text. In other words the whole mechanism will need rewriting.

**Comment by davidg-sil** [comment]
A recent patch stopped `\fp` from crashing things. Now it just causes ugliness, unless `\newparnotestrue` is set, in which case   `\fp` causes a paragraph break in paragraphed footnotes (although there may be some baseline irregularities -- TBD).

I don't understand how a new paragraph `\fp` can be a character style, or what the `\fp*` is supposed to do, so deleting `\fp*` seems like a sane idea.
