### ISSUE TITLE
\s in just one text causes problem in diglot

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#814]
When the main text has an \s marker in it, and the secondary doesn't, I'm getting output where the \s marker text shows up on the first page across from verse 1 of the secondary text, but then there is blank space under it and verse 1 of the main text doesn't start until page 2.

See the archive I submitted via email for Issue 813 to see an example.

In this case the paragraphs of the two texts are not at all similar and so I don't really expect much other than the diglot will realign itself after each chapter. But I still wouldn't have expected a full blank page like happened.

If I choose the option in PTXprint to not show Section Headings, then things look fine.

**Comment by davidg-sil** [comment]
There are actually two separate issues that end up giving the same visual error:
1. Merge fails to do the right thing.
2. a long-standing bug deep in the gory depths of diglot that  sometimes decides to ignore the merge-program's alignment and push the heading into the previous paragraph or the next paragraph into an empty chunk.

A horrible work-around that can work is to use a changes file to insert a section-heading with a something invisible, e.g. a non-breaking space to balance the one that's there on the other side.

**Comment by davidg-sil** [comment]
Doing some digging late on Friday, I found that (one way) to trigger a type 2 bug was if the merged data contained something like:
```
\lefttext 
\p
\righttext
\s Some title
```
or
```
\lefttext
\c 4
\righttext
\c 4
\s some title
\p
```
I.e. TeX is told that column text should be *expected* but (as \c is interpreted as saying 'remember this but don't do anything until you find out if  what's next is a \cl, \cp or paragraph')  it actually gets no settable content.  Might the data in your failing file fall into a similar case?

**Comment by davidg-sil** [comment]
**Update on this bug...**
I hoped that a fix that made its way into 2.4.49 might have fixed the issue. It did so in my test-case, but another data-point demonstrated that fix did not seem to affect diglots created with old-style `\lefttext` `\righttext` column switching. Manually editing that diglot to use the new-style (`\polyglotcolumn L`, `\polyglotcolumn R` `\endpolyglotcols`) column switching solved the problem.

 Therefore, as of just now, the python code has been altered to  generate the new-style code. I guess it will be included in release 2.4.50. Hopefully this change doesn't break anyone's project.

**Comment by mnjames** [comment]
Testing with the pre-release of 2.2.50 (unless your 2.**4**.50 is somehow ahead of github 🙂), things seem to merge a lot better.

However, the `\s` heading itself is still causing a blank page. I've submitted another archive to the support email.

**Comment by davidg-sil** [comment]
Hmm.
I've done some initial digging... That page-break only doesn't happen with chapters 1-10, just when chapter 10 is on its own, and according to the logs, it's a real page-break request, which is getting remembered from some earlier time.

I guess the code that says 'don't process  empty bits of page' needs to be cleverer, and try to do a page-break if there was one requested.

**Comment by mnjames** [comment]
The commit above appears to fix the problem I had reported.

I'm submitting a new archive to @davidg-sil because in reviewing the changes I found _other_ issues with \s not lining up correctly. But the above issue fixes the immediate problem we were having in drafting/production, and so this side quest is much lower priority.

**Comment by mnjames** [comment]
Thank you.

This looks good. The other issue which I sent an archive to @davidg-sil might still be present, but it's not too big of a problem. If it becomes so, I'll open a new issue.
