### ISSUE TITLE
Optionally transfer piclist data to daughter project 

### ISSUE THREAD

**Issue by JDNystrom** [sillsdev/ptx2pdf#817]
In a multi-language translation team setting where the mother translation is typeset first, a lot of valuable information is created in the mother translation's PicList, including how large a picture should be. In fact, a large percentage of the time it takes to typeset a new book is consumed by placing and sizing pictures appropriately. It doesn't make sense to do that same work 13 times. We would assume that if we found it appropriate to print a picture at 50% size in the mother translation, we will probably need to do the same, or at least close to the same, in a daughter translation. 

For routine printouts where we want to keep naïve users on the Mini View, the picture info from the mother translation would give the daughter translation team all they need. For publications, when the daughter team must venture off the Mini View to tweak things, they would not be starting with all pictures at 100%. 

So perhaps PTXPrint could **optionally transfer the PicList with the configuration**. Then, when the configuration is opened in the daughter project, PTXPrint could **update the PicList with the daughter translation's captions**, without any intervention from the user who wants to stay on the Mini View in PTXPrint. 

This method could also be used by teams that are not in the same cluster project. This could be part of a series of things (which would need to include extracting and importing \fig...\fig* fields) that could be done to help jump-start the publishing process for teams who like the picture choices another team has made. 

A less helpful alternative that does not involve transferring PicList data from mother to daughter: Perhaps PTXPrint could help keep naïve users on the Mini View by automatically generating a PicList from data in the daughter project, and if a PicList already exists, update it with any new data from the user's project without overwriting any other data already in their PicList. This is related to an issue David Coward submitted, asking to be able to add a few pictures without losing piclist data users have carefully edited.

**Comment by davidc86** [comment]
Excellent idea! I could see a standard "_starting PicList_" for each book done in the area, that could be shared around.  I'd use it immediately. (I assume for this to work it means the daughter's Paratext files would also need to have matching \fig fields.)

**Comment by davidg-sil** [comment]
I wouldn't assume that, as piclists can be entirely independent of anything in paratext. I've always considered it odd that PT would include any figure information, but maybe that's just a 'how different places work' thing.

**Comment by davidc86** [comment]
We need figures and captions in Paratext because pictures are not universally comprehensible. So it is ideal that they are included during checks (or around that time) to confirm the chosen pictures actually communicate the right meaning. Captions need to be check as well. So it is best that everything the end-user might someday see in a publication is managed and validated in Paratext first.

**Comment by markpenny** [comment]
I think there are at least 2 possibilities for a solution here:

a) an independent "Custom Tool" for Paratext which will copies all \fig ... \fig* (pl) from one source project across to one or more target projects. [A prototype has already been created and is pretty effective and simple to use. It may need a few refinements, e.g. only bring in NEW/missing figs and leave the rest alone]. The advantage of this is that it is easy to do a whole bunch of projects in one step.

b) The new Import Settings dialog (still being built) will make it easy (or easier) to import PicLists from ther configs (or even another PDF or ZIP archive):

![image](https://user-images.githubusercontent.com/12962708/220873552-1200b64b-a9e0-4ad5-bf2b-150fb5a65f02.png)

Is there something else that I've missed that you're asking for, or would one or the other options above meet the need?

**Comment by markpenny** [comment]
Note that the (new) **Import Settings...** dialog is still mostly vaporware; but will eventually get completed. And the other important piece of information is that there is currently no way to allow a Custom Tool in Paratext to output to (or update) multiple projects. So a standalone tool would need to be built to make this happen (unless the PT devs open the lock to multiple projects being updated at once). [Watch this space, but don't hold your breath!]

**Comment by markpenny** [comment]
I believe that **this now works** (i.e. no longer vaporware) using the new Import Settings dialog. You can selectively import piclists (but not the pictures themselves) from other projects/ZIP-archives/PDFs. Note that this does NOT do anything to the target USFM files in Paratext (i.e. it creates a new/updated PicList in PTXprint, but doesn't put \fig xyz|abc.jpg|etc.\fig* in their text).

![image](https://user-images.githubusercontent.com/12962708/234475123-5d2634bc-0528-4663-9f85-a9bdca28a04f.png)
