### ISSUE TITLE
Missing space before v1 marker in \nb paragraph

### ISSUE THREAD

**Issue by livingfield** [sillsdev/ptx2pdf#819]
There is no space between the last letter of the verse and the following v1 marker within a \nb paragraph. For now, I'm fixing it with this in changes.txt:
`"(\n\\c \d{1,2}\n\\nb)"	>	"\u2002\1"`

**Comment by davidg-sil** [comment]
Verified and hopefully the fix committed. Please check in the next release and close this issue or comment if it isn't fixed!
