### ISSUE TITLE
Suddenly getting an Error I wasn't getting minutes ago 

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#82]
Here is the error:

![image](https://user-images.githubusercontent.com/65363206/82670432-1dfe4d80-9c0b-11ea-9c57-e3d404cf1563.png)

The only thing I changed in the entire config file was adding \Marker tcr1 bundles to the PrintDraft-mods.sty file to test the TOC controls.

I've no idea, what else might be causing this. I built the PDF, saw my tweaks to the \toc1 field had no effect on the look of the TOC, so I tried the \tcr tweak that was suggested. And now this.

Looks like it is complaining about stuff in the BAK file (which I have not edited). So maybe it is just hitting the last book and realizing something is amiss?

**Comment by davidc86** [comment]
Solved by moving the \tcr* specs down to the "Table" section of the PrintDraft-mods.sty (rather than in the TOC section!) -- which makes no sense has to how that would have any bearing on the problem.

Also I removed the \TextProperties paragraph nonpublishable vernacular 
field from the specs. Maybe that was causing the problem? 
Anyway, those two changes caused the error to go away.

**Comment by markpenny** [comment]
Closing this one for now, but feel free to re-open it if you hit the issue again.
