### ISSUE TITLE
 Interlinear with 2 text directions

### ISSUE THREAD

**Issue by klassenjm** [sillsdev/ptx2pdf#822]
Hi,

I've initiated a conversation in the [PTXPrint user forum](https://community.scripture.software.sil.org/t/interlinear-with-2-text-directions/3476) about working with an interlinear layout which has 2 text directions (Greek with Urdu glosses). There have been some very helpful suggestions, and an update in PTXPrint from Martin, but so far no solution.

**In summary:** The Urdu glosses need to run full right-to-left below the Greek words. Some of the Urdu glosses contain whitespace, and at these locations, the directionality (appears) to revert LTR, and then back to RTL for the next Urdu text string. This results in an overall LTR presentation for a sequence of 2 or 3 RTL formatted Urdu words. If I use changes.txt to replace spaces with some other non-whitespace character (tried lots), things flow in the correct order.

I doubt it's helpful to repeat here what is written in the forum. The last attempt was an option to apply:

`\sethook{start}{gloss|rb}{\beginR}`

using some support added to 2.2.46. I added this to ptxprint-mods.tex. Unless that was not the right place to add this, it did not fix the rendering.

Would anyone here have other suggestions?

**Comment by mhosken** [comment]
Jeff, can you send me an archive of where you have got to? TIA.

**Comment by klassenjm** [comment]
Martin, I just updated to 2.2.50, and tried this again before making an archive.

`\sethook{start}{gloss|rb}{\beginR}`

It's rendering correctly now. Wonderful! I quite sure I had 2.2.46 installed before the update. Regardless - things seem OK now. Thanks for your effort to help.
