### ISSUE TITLE
Mangled interlinear + diglot gives confusing error message from UI merge process.

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#824]
Due to a slightly mangled interlinear (evidently there's been a change and it needs the interlinear approver person to approve the back translation again), I have this on one line of my processed text:
```\v 1 ....[deleted]...  \rb |Patrad, \rb o|the\rb* \rb Isus|jesus\rb* \rb avilo|came\rb*  ....[deleted]....```

For some reason, in monoglot mode this utterly fails to crash XeTeX, and it even prints mostly OK.

If I try to make a diglot, things get worse.
Running the usfmerge stand-alone program, I get this:
```
SyntaxError: local/ptxprint/testInterlinear/44JHNTBRS-testInterlinear.SFM: line 15,219: orphan marker \rb
```
It's clearly spotted that the \rb is without its end-marker and has decided that's significant enough to scream and throw its dinner on the floor. At least the error makes a lot of sense, even if it's more picky than XeTeX.

The UI, however, said:
```
Failed to merge texts due to a Syntax Error:
TBRS JHN line: ar/44JHNTBRS-testInterlinear.SFM: line 16,1: orphan marker \v
```
Urm... eh?

**Comment by mhosken** [comment]
what parameters did you pass to usfmerge, and what mode (and sync) did you run ptxprint?

Perhaps it is to do with which stylesheets you used in each case. Clearly in the ptxprint case the parser thinks it can keep going when it can't in the former case.

**Comment by davidg-sil** [comment]
Closed as replication is too hard
