### ISSUE TITLE
\refnp failing in Bible Modules

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#825]
This is reopening #720 (since I can't reopen it myself).

In certain cases Bible Module text like this
```
\ref REF#1
\refnp REF#2
```
fails to combine into a single paragraph. Letting PT compile the module in an XXA book works correctly, but printing in PTXprint directly from the spec file results in this bad behavior.

I think I've _finally_ discovered the conditions under which this happens.

If the original context of REF#1 ends mid-paragraph, then REF#2 will correctly combine with REF#1 into a single paragraph in the Bible Module.

But if the original context of REF#1 ends at the end of a paragraph, then the Bible Module created by PTXprint will include a \p marker after REF#1 and before REF#2.

All the archives for #720 should still be applicable, but I'm sending a new archive too which lists my tests that led me to finding this condition.

**Comment by mhosken** [comment]
Looking at the latest code. This seems to be working fine. But it did expose a bug. If the body tab include verses is off, the module would include them but not print them. Turning verses on meant the module excluded them but would have printed them. Inverted that so now it works :)

**Comment by mnjames** [comment]
This works when printed via XXC.

But it still does not combine correctly into a single paragraph when printed via the "Bible Module" function on the Basic tab.

In testing it, I made a few changes to the module and changed some settings to work with newer versions of PTXprint. It's in the Drive folder and starts with `825b`.

**Comment by mnjames** [comment]
They are mostly fixed, but the 3rd example in my 2nd archive is still failing. It is:
```
\ref GEN 13:1
\refnp GEN 13:3
```

**Comment by mhosken** [comment]
This could easily turn into a game of wackamole. But I've cleared any final empty elements and also handled if there is a chapter lurking at the end of the results. This should get you close. This all needs to be defined clearly in a definition of a module. One day. One day!

**Comment by mnjames** [comment]
Thank you very much.

I'm eagerly awaiting the formal write-up of Bible Module specs.
