### ISSUE TITLE
Textborder only showing bottom corner element in 2.2.50

### ISSUE THREAD

**Issue by klassenjm** [sillsdev/ptx2pdf#826]
I've installed PTXPrint 2.2.50. For one project and configuration I have a textborder configured as follows:

\Marker id:FRT|textborder
\TextProperties nonpublishable

```
\SetBorder VectorianSKR
\BorderPatternTop 39|||2.5, 72||+A, 73||+B, 72||-, 73||+C, 72||+C, 73||-, 72||+B, 73||+A, 39|h||2.5
\BorderPatternBot 39|v||2.5, 72|v|+A, 73|v|+B, 72|v|-, 73|v|+C, 72|v|+C, 73|v|-, 72|v|+B, 73|v|+A, 39|d||2.5
\BorderPatternLeft 72|r|+A, 73|r|+B, 72|r|-, 73|r|+C, 72|r|+C, 73|r|-, 72|r|+B, 73|r|+A
\BorderPatternRight 72|l|+A, 73|l|+B, 72|l|-, 73|l|+C, 72|l|+C, 73|l|-, 72|l|+B, 73|l|+A
\BorderRef Vectorian20inside

\Marker textborder
\TextProperties publishable
\BorderStyle ornaments
\BorderRef VectorianSKR
\BorderWidth 12
\BorderColour 0 0 0
\BorderFillColour 0 0 0
\BoxPadding 0
\BoxVPadding -10
\BorderVPadding 14
\BorderHPadding 8
```

(other pieces are enabled, such as the ornaments plugin, `\stylesheet{standardborders.sty}` in ptxprint-premods.tex etc.)

This has worked. It produced a full border in 2.2.42 and 2.2.46. In the latest PTXPrint 2.2.50 only the bottom right corner decoration is being rendered.

![image](https://user-images.githubusercontent.com/4420391/216656058-c103e653-1fef-4ed5-9817-19e2f8384392.png)

**Comment by markpenny** [comment]
Hi @klassenjm - yes, I stumbled upon this regression myself a few days ago. There was some work done to cache the ornaments, but it has had some other unforeseen side effects. I trust that @davidg-sil will be able to fix it soon, but until then, here's a workaround that should bring things back. Pop this into your `ptxprint-mods.tex` file:
```
% This hack brings the missing border(s) back
\XformOrnamentstrue
```
if that alone doesn't solve it, then also add this line:

`\CacheOrnamentsfalse
`

**Comment by davidg-sil** [comment]
Hopefully, I've just committed a fix for this bug.

**Comment by mnjames** [comment]
I was having the same issues on a project I'm working on, and I can confirm that @davidg-sil's commit fixes things.

**Comment by klassenjm** [comment]
I updated my installation with the commit from David, and also confirm a fix. Thanks @davidg-sil

**Comment by markpenny** [comment]
Nice to hear that you're running from source as well @klassenjm ! That means I don't have to rush another release out to make it work for you. [Note: We're currently doing some major refactoring and adding features that might break Master for a few days... so be aware of that.]

**Comment by klassenjm** [comment]
Well, actually @markpenny - I just looked at the commit David made and identified the file I needed.

What is the recommended way to setup running from source? (_not urgent to know_ -- but I'd be happy to get set up that way, sometime)

**Comment by markpenny** [comment]
Aha, that makes sense! We have some [instructions on how to set up the development environment on Windows](https://github.com/sillsdev/ptx2pdf/blob/master/docs/dev/WinDevEnvSetupGuide.md); there's a long list of packages etc. and it is complicated, but possible. If you're not trying to build the .exe you can skip the instructions about installing InnoSetup.

@mnjames Also worked out how to run it from a shortcut in Windows if that's important. He said: "You create a normal Window shortcut, and use this line to launch the program:"
```
C:\msys64\msys2_shell.cmd -mingw64 -c "python /d/Documents/github/ptx2pdf/python/scripts/ptxprint -I"
```

Obviously you'd need to change the directories to fit your context.
