### ISSUE TITLE
Enhance Illustration Permission Request template 

### ISSUE THREAD

**Issue by JDNystrom** [sillsdev/ptx2pdf#827]
Thank you for making the Request Permission feature. I wonder if we could extend it a bit to reduce the amount of editing required after the template is pasted into an email. This is a list of items to be filled in by the user and where I think PTXPrint could get the information so the user doesn't have to fill in this info every time. 

<Country> The user could put this in a variable field somewhere. 
<Requester's Name> Same
<SIL Entity> Same
<Title> PTXPrint could take this from the \toc1 or \mt1 field in the case of a single-book publication. The user can change it if it's not appropriate. 

This would be a big help when we have a number of languages we need to request pictures for.

**Comment by markpenny** [comment]
Thanks for the suggestion. This now works better, and the Requester name AND Entity are available as zvar variables.

By the way, the first time you click on the Permission Request... button, it looks to see if any of the zvars are missing, and if they are it will add them to the list AND you'll get a message that encourages you to fill in the missing values:
![image](https://user-images.githubusercontent.com/12962708/218048052-f59e2366-961b-411f-af67-da33397d435e.png)

This will be available in the next release.
