### ISSUE TITLE
Password Security

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#829]
I was sort of surprised today to discover that config passwords are stored unencrypted.

I understand why this is the case, and don't think doing otherwise is worth the hassle. But I'd recommend adding a warning to the tooltip so that people explicitly know this. Maybe something like this:
`The purpose of password locking configs is to prevent teammates from inadvertently changing settings someone else has worked on, and not to be hack-proof. A moderately skilled computer user could find out what the password is, and as a result we highly recommend against using passwords you use for other things (like your bank!).`

**Comment by davidg-sil** [comment]
Good point.

**Comment by markpenny** [comment]
Done - available in next release! Thanks @mhosken!
![image](https://user-images.githubusercontent.com/12962708/218404980-0bd3a6e2-2c2c-460c-a1fa-79099d909e72.png)

**Comment by mnjames** [comment]
Thank you very much! More than I expected.

Just a note (though not necessary a request to change anything): it appears that you have to unlock and relock the file to get it to copy over the old password. I was sort of expecting it to just happen automatically since as I booted PTXprint the command line had a note regarding `fwdConfig-Updating pw to: ... `

**Comment by markpenny** [comment]
Yes, we hadn't noticed that it *isn't* saving the updated/hashed password after it converts it. Presumably because the Config is locked and you can't save/overwrite it in that locked state! :-(   We would have to force an update of the config, but then that ruins the whole idea of "locking it so that nothing changes" - which is a high value too.

**Comment by markpenny** [comment]
This should be fixed in 2.2.51 to be released soon.

**Comment by mnjames** [comment]
I had gotten the impression that maybe you were changing it so that unlocking/relocking the file wasn't necessary, and that it would automatically convert any passwords into hashes.

In 2.2.51 that _isn't_ happening, but I'm satisfied with the current implementation and re-reading the comments here it's very possible I misunderstood. I'm closing the issue, but feel free to reopen it if you thought the passwords were being automatically converted.

**Comment by markpenny** [comment]
Thanks for catching the fact that it _still_ isn't working as we want/expect it to. I'll have another go to make it SAVE the hashed password (without the user having to do anything).
