### ISSUE TITLE
Ubuntu packaging

### ISSUE THREAD

**Issue by n7s** [sillsdev/ptx2pdf#83]
See the following branch for initial attempts at developer mode and packaging for Ubuntu (targeting py3.8/setuptools on 20.04/Focal Fossa): 
https://github.com/n7s/ptx2pdf/tree/ubuntu-packaging

**Comment by mhosken** [comment]
Please can you commit changes to the main tree to master in this repo and just keep anything you want kept separate in your repo.

**Comment by n7s** [comment]
This needs more testing and review by the ptxprint team before merging.

**Comment by n7s** [comment]
See f229421 and https://github.com/sillsdev/ptx2pdf/tree/debian/master/debian

**Comment by markpenny** [comment]
@n7s Hi Nico, Has there been any progress on this? Or are you waiting for @mhosken to do something? I'm hoping we can have this packaged for ver 0.9.0 RC so that the Linux people can test it before we release ver 1.0
If you are looking for a tester for the package, then let me know and we can pass on names of known Linux users who are beta-testers.

**Comment by n7s** [comment]
I got some more feedback from @mhosken on this recently and will adjust the packaging over the next few days. There are some paths issues to be sorted out, but I'm looking at pybuild params to override the basic conventions. Yes it will be good to have testers. Thanks.

**Comment by n7s** [comment]
Some progress has been made, path issues remain.

BTW lintian (package checker) reports these: 

W: python3-ptxprint: binary-without-manpage usr/bin/ptxprint
W: python3-ptxprint: binary-without-manpage usr/bin/xdvitype
W: python3-ptxprint: executable-not-elf-or-script usr/share/ptx2pdf/ptx-tracing.tex
W: python3-ptxprint: executable-not-elf-or-script usr/share/ptx2pdf/ptxplus-character-kerning.tex
W: python3-ptxprint: executable-not-elf-or-script usr/share/ptx2pdf/ptxplus-marginalverses.tex
W: python3-ptxprint: executable-not-elf-or-script usr/share/ptx2pdf/usfm.sty
W: ptxprint source: source-contains-prebuilt-windows-binary python/scripts/diglotMerge.exe

**Comment by n7s** [comment]
A package has been build and uploaded to this PPA: https://launchpad.net/~silnrsi/+archive/ubuntu/ptxprint  

I've sent an email to the beta-testers. 

And I've committed the small permissions changes that lintian flagged above.

**Comment by markpenny** [comment]
@n7s Thanks so much Nico - great to hear. I've been migrating over the last few days, so HI FROM NZ! I hope the testers are able to give you some good feedback.
