### ISSUE TITLE
Import Config from PDF does not update UI

### ISSUE THREAD

**Issue by klassenjm** [sillsdev/ptx2pdf#830]
I'm working with 2.2.50. My current experience with loading a configuration from a PDF is that
- the configuration is loaded and written to the `ptxprint.cfg` file (I see the file updated in my text editor)
- the UI is not updated with the new values

Result - if I click Save or Print, the values from the UI are written to `ptxprint.cfg` and the imported values (which had been saved in the file) are lost.

If I load config from a PDF, and the restart PTXPrint immediately (before any other activity in the UI), the desired values for the config are re-loaded as desired.

**Comment by markpenny** [comment]
Great timing, @klassenjm! Just earlier last week we were working on a fix for this (rather embarrassing!) bug. We think we have fixed it, but we're also going the extra mile to enable "selective importing" of configs (either from a PDF or from a different config). It might be another week or so until this is released, but this is what we're aiming at:

![image](https://user-images.githubusercontent.com/12962708/220043006-a2a4673e-3994-4f39-a724-931de97cc1a1.png)

**Comment by klassenjm** [comment]
Thanks @markpenny . This looks very helpful!

Anecdotally -- A person I was working with was somewhat confused when I directed him to begin by importing a configuration from a PDF file. It had just not occurred to him that something other than the printable content (like a PTXPrint configuration and all that goes with it) could possibly be inside a PDF file. I explained that it could. Before I did, that part of the configuration process seemed like a mystery step to him.

Not critical: This made me wonder if it might be just as well to be able to save / import a configuration from a zip file (perhaps this is just a minimal version of an Archive file), in addition to the PDF option (which has the benefit of being able to see what it looks like!)

For the "A Previously Saved Configuration" in your screenshot -- I can imagine someone making a 'special' PT project to hold all of their PTXPrint configurations, and perhaps sharing that project with some others. (An alternative would be a folder of configuration archive files).

**Comment by markpenny** [comment]
@klassenjm Just a brief update on this issue. (I know the feeling well - "How on earth can you store *other* stuff in a PDF?" was my reaction to Martin when he proposed the idea last year.) 

For the latest 2.3 release we hadn't completed the coding to integrate the new Import Settings... dialog shown above, so the import button is back to its previous (simple) behavior of "Select a PDF file to import from..." but [for an upcoming version] I have taken your suggestion on board to allow the user to select either a PDF or a ZIP archive file. Watch this space, but don't hold your breath. MH is away at a Dev conference, and then we've got several workshops to prep for, so it might be a while.

**Comment by klassenjm** [comment]
Thanks @markpenny. I appreciate the note.
Watching, and breathing... :-)

**Comment by markpenny** [comment]
I believe this issue has now been resolved with the recently implemented Import settings functionality.

![2023-04-26 13_01_09-_new 3 - Notepad++](https://user-images.githubusercontent.com/12962708/234490823-2cd0619f-6dba-4d3e-8112-c70b19ec6683.png)
