### ISSUE TITLE
An underlined word space is wider than normal

### ISSUE THREAD

**Issue by livingfield** [sillsdev/ptx2pdf#836]
`\nd` is formatted to underline text using these two lines in **ptxprint-mods.sty**:
```
\Marker nd
\Underline
```
The space between Lord and God is wider when the phrase is enclosed in `\nd ... \nd*`
`\nd Lord God\nd*`

If only "Lord" or only "God" is enclosed in \nd then the space is the same width as unmarked text.

<img width="864" alt="Screenshot 2023-03-10 at 11 07 47 AM" src="https://user-images.githubusercontent.com/15900199/224221019-22e815ce-252d-49e0-a3c7-0e2d856c035f.png">

**Comment by davidg-sil** [comment]
Martin is incorrect (or rather, out of date), as underlined spaces are now flexible (and breakable), as they are made with `\leaders\hrule`
However, the amount of that measurement is currently fixed (to `1ex plus 0.2ex minus 0.2 ex`). The correct approach, of course, would be to set the skip based on the relevant dimensions of the currently active font.  The TeXBook seems a bit reticent on what those dimensions actually are.

**Comment by davidg-sil** [comment]
Apparently `\font` can be used to specify *this* font. and the dimensions are fontdimen2, 3 and 4. 

`\fontdimen2\font plus \fontdimen3\font minus\fontdimen4\font`
![image](https://user-images.githubusercontent.com/58848232/224343984-526c3ca1-cc72-4282-ac6f-b0b2541d3488.png)

**Comment by livingfield** [comment]
Appears to be fixed in build 2620.
