### ISSUE TITLE
New justification types

### ISSUE THREAD

**Issue by mhosken** [sillsdev/ptx2pdf#838]
Currently we have 4 justification types for a paragraph: justified, left, right, center. But we realise that there are some issues with left justified. There are 2 aspects to left justification:
- Whether spaces flex or are set rigid
- Whether the end of the paragraph may try to stretch the last line or whether it tries for the shortest last line. Stretch is good for poetry where we don't want lots of 1 word lines and want to encourage more balanced paragraphs. But normal text wants lines to be as long as possible regardless of the effect on the last line.

We can merge these two concepts by saying that setting left rigid, then we want the longest lines. If we want a balanced paragraph we can also afford to let spaces stretch. So, the proposal is to add 2 new paragraph justification types:

- justify
- left (rigid): left
- right (rigid): right
- centre
- left (balanced): leftbal

**Comment by davidg-sil** [comment]
Also:  
*  right with flexible spacing: `rightbal` or `rightflex` ?
Having some flexibility in the spaces might let the paragraph fit in less lines. I'm against rightbal, because  we can't have **unbalanced** right justification without doing some very complicated things that might break if there's e.g. a verse on the last line.

**Comment by davidg-sil** [comment]
Update: having rigid spaces makes page/column balancing harder (it basically means that negative  adjust-lists  cannot  work in such text).  Also, rigid spacing for some paragraph types would need additional processing overhead in the already complex paragraph setup process.
 For the moment we're not implementing per-paragraph type space .

**Comment by klassenjm** [comment]
FWIW: I would view 'rigid space' as a manner of performing the initial paragraph layout for non-justified / ragged text. I would not have assumed that this meant someone would not choose to stretch or shrink spaces in specific paragraphs for fitting purposes, as needed.
