### ISSUE TITLE
Overfull lines in RTL languages

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#840]
If a line has an overfull box in it, the extra material will hang over the *right* margin. In LTR contexts that's fine, but in RTL contexts that's the beginning of the line, not the end.

I'm hoping that this is a simple fix.

If it's not, it's not causing very much trouble. So make this very low priority, and just resolve it if it's not worth messing with.

Archive submitted via email.

**Comment by davidg-sil** [comment]
I cannot find a way to make anything work, sorry. I think it's too deeply burried in TeX's internals.

**Comment by mnjames** [comment]
No problem. Thank you for looking.
