### ISSUE TITLE
Creating division of words fails in 2.3.1

### ISSUE THREAD

**Issue by philleckrone** [sillsdev/ptx2pdf#841]
When I try to create the list of divided words I get the following message:
Mailto: <ptxprint_support@sil.org>

Traceback (most recent call last):
  File "ptxprint\gtkview.py", line 3633, in onGenerateHyphenationListClicked
  File "ptxprint\view.py", line 1403, in generateHyphenationFile
ValueError: expected '}' before end of string

Versión de PTXprint 2.3.1

NOTE that this worked in 2.2.1

**Comment by markpenny** [comment]
Hi @philleckrone - Could you please send me an archive of this project. I'm not able to reproduce the error without it.

**Comment by philleckrone** [comment]
[PDT15-DefaultPTXprintArchive.zip](https://github.com/sillsdev/ptx2pdf/files/11139734/PDT15-DefaultPTXprintArchive.zip)
Mark - I had the same result with a couple of projects. In 2.2.1 the project seems to create the list and do the work. In 2.2.50 and higher I get the error referenced above. I noticed that the zip doesn't include the hyphenatedWords.txt so I'm sending backup of the entire project also.
[Palabra de Dios Para Todos - para entrenamiento 2023-04-03.zip](https://github.com/sillsdev/ptx2pdf/files/11139763/Palabra.de.Dios.Para.Todos.-.para.entrenamiento.2023-04-03.zip)
