### ISSUE TITLE
Scripture text is off the baseline on first page of single column books

### ISSUE THREAD

**Issue by livingfield** [sillsdev/ptx2pdf#842]
Using Build 2630, If the following conditions are met, then a bit of extra space appears between the introduction and chapter 1, making all of the Scripture text on the first page lose backup.

This happens if:
- "Use Special Features for These Books" is checked and PSA PRO are listed next to it.
- "Chapter Label" is `\ZWNBSP`
- "Use One Column Layout for These Books" is checked and PSA PRO are listed next to it

On the other hand, when PSA and PRO are set to two columns like the rest of the Bible, then everything prints nicely.
I've inserted a horizontal rule at the end of the introduction, but removing this does not appear to have an effect.

<img width="889" alt="Screenshot 2023-03-23 at 8 57 36 AM" src="https://user-images.githubusercontent.com/15900199/227079416-df15c729-12d5-4718-aa90-cf385e8c461e.png">

**Comment by davidg-sil** [comment]
If the above isn't enough help for you to resolve it yourself, please submit an archive.

**Comment by davidg-sil** [comment]
I did some digging last week and spotted some issues with the horizontal rules, among other things. I've finally managed to get your project to run to completion, and it looks like one of the bugs I fixed was your bug. 

PTXprint 2.3.2 contains those bug-fixes. Can you close this issue if it is indeed fixed for you? Thanks!

**Comment by mnjames** [comment]
Possibly completely unrelated, but I was having trouble recently with being off grid starting starting from the first line of pages. @markpenny suggested checking off `Advanced-->Compatibiliby-->Use glyph metrics`, and that solved my problem. I think certain fonts use unusual line height measurements and that that options deals with the problem.

**Comment by livingfield** [comment]
Looks good with build 2638. (so presumably 2.3.2 as well)
