### ISSUE TITLE
Want to be able to print portion of a chapter

### ISSUE THREAD

**Issue by SaraMeiSL** [sillsdev/ptx2pdf#844]
Currently it is possible to specify the required chapter from a book, or range of chapters. Are there any plans to be able to select a range of verses? 

Use cases:
1) printing, for example, one specific parable for community testing
2) school situation, where students are not asked to translate an entire chapter

In case 2, currently an incomplete chapter fails to create a .pdf. Workaround is to delete the markers for the empty verses in the chapter, then a .pdf is generated.

**Comment by mnjames** [comment]
![image](https://user-images.githubusercontent.com/30174022/227424577-234fed7e-5c7d-4a90-8b3b-08b2b115a72f.png)
Are you seeing something like the above picture? In "Single Book" can you choose chapter ranges?

For specific verses, in the place where you choose what to print--where it says "Choose Books:", you can type what you want to print. It will take standard English abbreviations and can be fairly complex. For example:
`GEN 1:5-10`, or `MAT 9:1-8; MRK 2:1-12; LUK 5:17-26`

However, if chapters with empty verses aren't printing, that sounds like a bug. On the `Body` tab, have you tried checking `Hide Empty Verses`? (You have to be in Basic or Full View to see that option.)
![image](https://user-images.githubusercontent.com/30174022/227424830-bc74defb-d1a2-4d4a-916e-a614c24242c0.png)

**Comment by SaraMeiSL** [comment]
We did try checking the "hide empty verses" box, yes.

Will investigate the ranges as you specify, thanks.

**Comment by markpenny** [comment]
@SaraMeiSL Did this work? Or are you still waiting for us to fix/improve something here? If there's nothing else to do, then go ahead and close the issue.
