### ISSUE TITLE
Diglot Facing Pages: Header for 2ndary project doesn't appear

### ISSUE THREAD

**Issue by KimB2017** [sillsdev/ptx2pdf#846]
After I temporarily removed a verse bridge in both projects my diglot-on-facing-pages is working beautifully. Very cool!! ... except for a few odd bits:
1. The 2ndary project Header (\h John (2001) never appears. Since this project is to compare two different translations of John in the same language I really need the visual label on each page for which is which. At first I thought the Primary/Secondary radio buttons on the Headers/Footers page would allow me to specify separate text for these fields, but they just specify formatting.
2. No matter how I set "Use Default Settings for Diglot" the primary Header is at Inner and page# at Outer margin of each page.
3. The "Secondary on Left" setting does not work.
4. "Separate Notes in Two Columns" still places footnotes mostly off the right side of each page (not that I wanted that, but it was somehow ticked by default. I'm glad another user commented on this recently. Maybe a tooltip popup would be helpful?

And a question: Does it matter whether the secondary project is assigned a Diglot Configuration? (vs. just "A5 booklet" as copied from my main project)

**Comment by davidg-sil** [comment]
Answering your last question first: it shouldn't matter for a facing-page diglot, but...  it depends. If you end up making any changes for the diglot that you wouldn't want in the "A5booklet", then yes, at that point you should make a second configuration.

The GUI does not help you set the odd and even page headers, but you can do so via `ptxprint-mods.tex`:
[documentation here](https://github.com/sillsdev/ptx2pdf/blob/master/docs/documentation/README.md#odd-header).
You can choose side-specific versions of much everything you might want to put into a header by appending the one-letter column ID to it (`L` = primary, `R`=secondary). e.g. `\def\RHevencenter{\bookaltR}` = the **center** slot of the  **R**unning **H**eader on **even** numbered pages should have  `\bookaltR` in it, i.e. secondary text's alternate bookname (`\h1`). You can also put literal text in there, if you want.
Most variables automatically swtich fonts for you, but `\book` and  `\bookalt` do not, and nor does literal text, of course. To switch fonts, you should do something like this`\def\RHevenleft{\headfootL{book: \bookL}}

Once you're doing a facing-page diglot, many of the GUI settings are getting overridden. The which text goes on which page is controlled by what you give to `\polyglotpages`:
`\polyglotpages{R,L}` ought to put the 'secondary' text on the left.

**Comment by markpenny** [comment]
> Does it matter whether the secondary project is assigned a Diglot Configuration? (vs. just "A5 booklet" as copied from my main project)

If the secondary project is *also* a diglot, then yes - there will be problems. Make sure the secondary isn't also calling another project/config.

**Comment by markpenny** [comment]
> 1. At first I thought the Primary/Secondary radio buttons on the Headers/Footers page would allow me to specify separate text for these fields, but they just specify formatting.

AFAIK, these buttons *do* actually control where the information is coming from; so it should work. However, I also know that these radio buttons are a bit stubborn at times, and you may need to toggle them the other way, hit print, and then toggle them back to what you actually want before they work as needed. [That would be a nice bug to fix one day soon...]

![image](https://github.com/sillsdev/ptx2pdf/assets/12962708/1510a2dc-62f7-42cc-8e95-ee5dac54cb2a)

**Comment by markpenny** [comment]
> * No matter how I set "Use Default Settings for Diglot" the primary Header is at Inner and page# at Outer margin of each page.
> * The "Secondary on Left" setting does not work.

I don't know for sure, but it sounds like this could be the result of "Mirror Pages" being turned off on the Layout page:

![image](https://github.com/sillsdev/ptx2pdf/assets/12962708/d8415852-4818-4ec2-aa9a-43f7ee1b2fb9)
