### ISSUE TITLE
Gear bold 'warning' about lines per page issue

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/ptx2pdf#849]
In a workshop I'm at, I was told if the gear button  to the right of Base Line Spacing is bold on the Layout tab, there's an issue with the lines per page. How does one know this secret knowledge? This should be explained in the tool tip. Even better, I think would be to show some red text so that a person knows there is some action to take. The bold gear button isn't intuitive to me that something is wrong.

**Comment by markpenny** [comment]
Sorry, I'm not sure that the person explaining the gear button was accurate. It is NOT a problem, or major issue if you choose to use a less-than optimum line spacing.* The gear icon appears clickable if the lines per page isn't an integer; and I thought that the tooltip on the gear button explains things clearly enough. What else would you add and where?

![image](https://user-images.githubusercontent.com/12962708/229259114-d5962b48-ac9d-4fd9-8286-4eccd735eca7.png)

* Some people think it is foolishness to adjust the line spacing by a tiny fraction, and prefer precise numbers (like 12.5, or 14.0) for their line spacing and would tweak the header or footer size (also using their corresponding gear buttons).

**Comment by mnjames** [comment]
I think maybe the new information--at least for me--was that that those gears switch between black and grey at all. I wouldn't word it as fixing a problem, but as indicating a solution.

So maybe something in the tooltip like:
`The icon will turn black when PTXprint has a suggestion that would minimize waste, and grey when it feels like the ideal solution is already in place.`

**Comment by markpenny** [comment]
Thanks for the suggestion. I have updated the tooltips for all 3 "gear" buttons on the Layout tab (new wording is highlighted here in Yellow):
![image](https://user-images.githubusercontent.com/12962708/229410719-42ac0177-e683-44f1-9603-3decba20a7e5.png)

**Comment by rmlockwood** [comment]
Thanks!
