### ISSUE TITLE
Requesting a minor tweak to the position of the copyright text box on pictures 

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#853]
I believe I've mentioned this once before (#780) , but it is showing itself again, so I thought I'd again request a minor tweak to the position of the copyright text box on pictures. It looks like it is one pixel too high. (Personally I'd like it if PTXprint added a slight additional white space below or to the side of the picture that is going to get a text box, so it isn't even on the picture, but I'm sure others would disagree.)

Here is what I'm seeing:

![Screenshot 2023-04-05 213705](https://user-images.githubusercontent.com/65363206/230084565-55448d5b-1e16-4bde-a564-82635bb5b22a.png)

It just doesn't look quite right. It is too high, and the box seems a bit too large vertically for the text inside--it goes way above the capital letters, and seems to have a lot of room for large descenders too. What to you all think?

Is it possible the end-user can adjust this? What determines the placement? Do the font choice, line spacing text box margins, etc. all crowd together into the final calculation of how much space is actually needed? Maybe a "rounding error" that only shows up on certain fonts and certain sizes? Or is everybody seeing this?

Thanks for looking into this, when there is time. (Clearly NOT a show-stopper. More of an "elegance" thing.)

**Comment by davidg-sil** [comment]
The image showing 'below' the credit box seems to be in the class of 'rounding error'.  I have also found it in my test files. I don't think it is so much a function of the text box, but of how XeTeX inserts the image. Moving the box by 0.07pt seems to work for me.

Anyway, 2.3.6 when it comes out, should apply that fix and hopefully all will be wonderful. If it doesn't there are some extra special  tweaks to override my 0.07pt tweaking value.  As a bonus, for the cost of a  bit of stylesheet adjustment I've give you the ability to move the credit box away from the corners they like to nestle in, even to the extent of making them sit outside the image area if that's what you really want to do.

![image](https://user-images.githubusercontent.com/58848232/230495936-445fe821-503e-489c-a6ce-acb152560671.png)

I assume that the real-world use of this would be for credit boxes with no background, but  note that if you do it on a full-span image (or even a full-page on) then the credit box will be outside the margins or even off the page.

**Comment by davidc86** [comment]
Wow! Just wow. 
Looking forward to this enhancement.
