### ISSUE TITLE
Browsing from the Add button on the Pictures tab fails to find .tiff files

### ISSUE THREAD

**Issue by livingfield** [sillsdev/ptx2pdf#857]
.tif files work fine, but the browser filters out .tiff files. Does the same thing happen with .jpeg files?

**Comment by markpenny** [comment]
How important is this for you? Given that there are dozens of places that look for the usual 3-letter extensions (.jpg, .tif, .png, .pdf, etc.) I am a bit reluctant to open the can of worms which could break picture handling in a number of different ways.
So my recommendation for .tiff and .jpeg is to rename your local files before trying to use them in PTXprint.

![image](https://github.com/sillsdev/ptx2pdf/assets/12962708/5908637a-1e0d-46bd-870e-a2e0641004ae)
