### ISSUE TITLE
Regression with stacked verse bridges (hanging verse numbers)

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#86]
I just notice that we're now getting a blank line where we shouldn't:

![image](https://user-images.githubusercontent.com/12962708/82698325-32ccf680-9c88-11ea-92be-a259d0b004a3.png)

**Comment by mhosken** [comment]
Fixed in bfad9de.

**Comment by markpenny** [comment]
Yes, I can confirm that it has been fixed. Thanks!
