### ISSUE TITLE
Bug in loading Bible Modules

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#865]
When I go to the Basic tab, choose "Bible Module" and then click the Choose button, navigate to a .sfm file and then click Open, I get the following error (and the file does not get loaded)
```
Traceback (most recent call last):
  File "ptxprint\gtkview.py", line 3326, in onSelectModuleClicked
  File "ptxprint\gtkview.py", line 3326, in <listcomp>
  File "ptxprint\utils.py", line 285, in saferelpath
TypeError: object of type 'Path' has no len()
```

**Comment by mnjames** [comment]
Thank you.

**Comment by JimSmith763268** [comment]
Sorry, what was the fix? (Is it perhaps in a commit but not yet released in a new version?)

**Comment by mnjames** [comment]
Yes, it's been committed but not released. Presumably it will be in 2.3.10.
