### ISSUE TITLE
Stretching Graphite fonts

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#867]
I used the UI to copy the `ft` footnote marker and create a new marker called `ft_95`. In the settings I set the stretch to .95 and marked it as a graphite font. However, when I printed it none of the Arabic letters were joined (a classic result when graphite isn't actually enabled).

In the `ptxprint.sty` file the UI had added these two lines:
```
\FontName Awami Nastaliq
\ztexFontFeatures /GR:extend=0.95
```

I copied the entire marker definition into `custom.sty`, but edited those two lines to read like this:
```
\FontName Awami Nastaliq/GR
\ztexFontFeatures extend=0.95
```

After doing that, it printed correctly (with letters joined, and the horizontal stretch diminished).

--------------------
Assuming that the 2nd format is actually the correct way of doing this, then I would recommend that the UI be updated to handle Graphite fonts correctly.

**Comment by mhosken** [comment]
My first reaction is that it shouldn't make any difference. But clearly it
does and needs a bit of digging. I may ask you to help trace this. From
memory there is a tracing fonts, probably \tracing{F}, but check the
technical reference manual or look in ptx-tracong.tex or look in
ptx-char-style.tex and look for \font and set it so it traces the line
before or thereabouts, he says from memory.

GB,
Martin

**Comment by davidg-sil** [comment]
`\LogFontstrue`  will write a file (`whatever.fontusage`)  containing the internal font name (basically the marker stack) and the font string  that defines it, as well as the page it's first used on.  It's been around for something like a year, but I don't think it made it into the UI. It'll probably be easier than wading through the whole log file.

**Comment by mnjames** [comment]
For the bad one, here's the result:
`font<ft_ui-9.96+f>="Awami Nastaliq":extend=0.99:/GR at 9.13005pt (page 1)`
and the good one
`font<ft_mods-9.96+f>="Awami Nastaliq/GR":extend=0.80 at 9.13005pt (page 1)`

**Comment by mhosken** [comment]
I've committed a change that might fix this. Moving things like GR into the
font name. Of course now it might go bang somewhere else.

**Comment by mnjames** [comment]
I haven't seen any new code. Did you push your commit?

**Comment by davidg-sil** [comment]
I've just pushed a patch that, when features are getting processed, migrates features starting with `/` to the start of the list. This doesn't guarantee that `/GR` ends up before `/B`, but that doesn't actually seem to matter, based on a bit of manual testing I did. Please shout if it does!
 
It seems to work, and enables strange activities like turning on graphite rendering via feature-addition. 
(`\ztexFontFeatures +[/GR]`)  - note this is available in manually written stylesheets  only, so far.
 I don't know if Martin's patch (which I assume was to the python side of things) ever arrived at the server, but this patch closes the TeX / feature maths side of things. Note that Martin's patch will make anything set in the font-name a permanent and un-modifiable feature of the font/style, not amenable to feature maths.

**Comment by davidg-sil** [comment]
Oh, by the way, I *also* pushed a patch earlier on that makes `\ft^95`, and `\+nd^98`, etc.  auto-set the extend feature. Note that it still multiplies with any paragraph-based extend
 
However the markup of applying this approach to notestyles such as `\f^95 + \fr....` makes the USFM look too ugly  to contemplate implementing, until someone screams a lot that they've got footnotes with umpteen sub-styles and they really need to control the whole lot.  Actually, I'm  still not sure I'm going to do it... it: in my brief experience while testing,  the visual impact of extending bold text, e.g. `\fr` is far more noticeable than that of  extending regular text, and therefore I expect that results will be better leaving `\fr` at normal size, and using an appropriate rule in the changes file.

**Comment by mnjames** [comment]
Yes, David's patch fixes the graphite font not having the letters connected. I still haven't seen a patch from Martin regarding this, but as far as I know it's not necessary now.

Thank you making the `\ft^95` feature also. I'm looking forward to using it.
