### ISSUE TITLE
Strange Section Heading spacing when using Chapter Label option

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#87]
I've noticed that when the \cl Chapter Label option is enabled, I'm not getting a strange vertical spacing issue:

Before:

![2020-05-22 18_33_53-ptxprint-RUT_HEBWSGBT pdf - SumatraPDF](https://user-images.githubusercontent.com/12962708/82732833-64e46400-9d2d-11ea-826d-f35e41a1beb0.png)

After:

![2020-05-22 18_34_15-ptxprint-RUT_HEBWSGBT pdf - SumatraPDF](https://user-images.githubusercontent.com/12962708/82732840-7168bc80-9d2d-11ea-9045-e7c7874a4eff.png)

**Comment by davidg-sil** [comment]
this looks like something I thought I fixed on Friday, commit fa45ea0603. Have you fulled that commit?

**Comment by markpenny** [comment]
Indeed - it is already fixed. I must have been testing with a stale copy. Sorry for raising it as an issue. It looks great now:
![image](https://user-images.githubusercontent.com/12962708/82761300-4eb2d280-9e17-11ea-931e-6ecacf4efa7a.png)
