### ISSUE TITLE
Figures in the glossary

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#878]
Executive summary: The code at present turns chapter-verse locations of scripture text into piclist anchor points when images are found. A similar process would be useful for the glossary, using the `\k ... \k*`  headword. 

More details:

The current   `\zfiga|p001\*`  image anchor is problematic in the glossary and it is also causing problems with filtering, etc. 
Since `\k Festival of Pentecost\k*` (e.g. in `GLO`) triggers an automatic image anchor point of `GLO FestivalofPentecost` (like verse numbers trigger and anchor point of `BKK CCC.VVV`), it would be most appropriate if the automatic piclist entry used that in a book that used `\k ... \k*` markup, before falling through to `\zfiga` markup for figures.

I don't know where most people are putting their images in the glossary, but I anticipate there are 3 possibilities:

1) Fairly nasty  to parse:
```
\p \k Tabernacle\k* Description
\p
\fig Temple layout| .....\fig*
\fig Holy of Holies| .....\fig*
(\p) The \k Temple\k* Description
\p more description
```
But (while I've not checked) I suspect this will get Paratext very confused, and when a new entry is made for `Tamerisk` the figure will need to be moved (to below that entry)

2) Much easier to process: 
```
\p \k Temple\k* \fig ..... \fig*
Description
\p More description
```

3) Also easy to process:
```
\p The \k Temple\k* Description 
\p \fig .... \fig*
\p More description

```
4) Not possible to parse:
```
\p \k Tabernacle\k* Description
\p Here is a picture of what our artist thinks the tabernacle might have looked like:
\fig Tabernacle| .....\fig*
\fig Temple| .....\fig*
\p  \k Temple\k* Description
\p more description
```  
I would like to suggest that we declare  (4) above to be unsupported at present, and prioritise support (2) and (3).
(1) would need to look for a the sequence `\\p\s*(\\fig ...\\fig*)+\s*(?:\\p)\s[^\\]*\\k([^\\]+)\\k`  or something like that.

**Comment by markpenny** [comment]
This now seems to be working, **and only affects the GLO book** - as the previous p001, p002, or bk ch.vs anchoring systems seem to be working fine in other contexts.

**Comment by mhosken** [comment]
We have implemented this, but having done so, I'm confused as to what it gains us. Note that if you have more than one picture in an entry, it will be given an anchor of the keyword followed by an arbitrary (the ith figure in the file) number.
I can only think that the advantage is in giving users some hope of finding one image among many in the pictures editor.

**Comment by davidg-sil** [comment]
The benefit should be in combining piclist edits with glossary filtering, and there's no need for the auto-inserted `\zfiga`.
