### ISSUE TITLE
Front Matter PDF(s) option clears if we click Cancel in the Select... window

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#887]
I have a PDF selected for inclusion in the Peripherals options Front Matter PDF(s):

![image](https://github.com/sillsdev/ptx2pdf/assets/65363206/81a7622f-6579-45f7-922c-b1dcf42c1c26)

Today I wanted to check where that PDF file was located (I need to update it). So I clicked the Select... button. 
Saw the path and then clicked "Cancel". Expected behavior is that this would simply **back me out of the dialog, with no changes.** 
But nope. It cleared the option and caused PTXprint to forget the PDF file and its location!

![image](https://github.com/sillsdev/ptx2pdf/assets/65363206/2df72eef-2a60-4542-a23a-da0708046404)

I had to find the file again and reselect it to get it back to how it was before that "Cancel" event.

Minor, but should be fixed. Especially as I almost didn't notice that PTXprint had cleared the setting!

**Comment by mhosken** [comment]
Without adding a button. How, if cancel doesn't clear, might someone clear
the setting?

**Comment by davidc86** [comment]
Simply uncheck the option. (But it retains the information for later use.)

**Comment by davidc86** [comment]
I would think checking/unchecking is how people would use this. I don't expect that people would hardly ever want to clear out the filename and location.

Because for the next book we need to print, we'd have a different front matter file to attach, but it would be in that same folder location as the previous book's frontmatter PDF. So, we'd open this up and select the new file.  Click OK. 

Next time, when we want to verify where PTXprint looks for these files (because PTXprint keeps stuff in several places), we open this up, see the path, and MUST then remember to click OK, in order to back out of the dialog without trashing the location. 

(BTW, it would be nicer/easier to use, if PTXprint used the default folder/file manager of the OS, rather than whatever it uses. The default Windows file manager is powerful, for copying and pasting in files into the folder via the dialog box, etc. But maybe that is too hard to implement?)

**Comment by davidg-sil** [comment]
Regarding Done vs cancel, I agree with davidc, people *will* expect that cancel leaves things unchanged, because... that's just what cancel buttons are for, surely?

Regarding using a system file selector... on linux I see the same file selector for firefox, libreoffice and ptxprint. Is that just because they're all built using gkt?

**Comment by markpenny** [comment]
@davidc86  This has now been implemented (as suggested). Changed behavior will be available in the next release.
