### ISSUE TITLE
PTXprint now hangs when exporting my project

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#888]
First time 2 times I tested PTXprint this morning it worked fine. But I needed to change the name of one of the picture files. (It wasn't exporting because the name didn't match.) I fixed the name in PTXprint, it exported and opened in Sumatra PDF, but PTXprint hung, and never returned control to the window. It had to be put down. 

In subsequent testing (restarting PTXprint), it hangs every time now and no PDF is created.  

[SLU-PublikasiSelaru-TESTPTXprintArchive.zip](https://github.com/sillsdev/ptx2pdf/files/12361188/SLU-PublikasiSelaru-TESTPTXprintArchive.zip)

Any clues?

**Comment by markpenny** [comment]
I believe that this has now been fixed (and should be working again in 2.3.35). Please let me know.

**Comment by davidc86** [comment]
Seems to be working!! Thanks. This fix helps a LOT when iterating through multiple tweaks and testing.
