### ISSUE TITLE
PTXprint installer for Windows gives App Error on first run after launch

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#89]
Each time that I have updated PTXprint using the Windows installer (this time for v0.7.0)  the installer automatically launches the PTXprint app. The first time I run PRINT, I get this error message:

![image](https://user-images.githubusercontent.com/65363206/82825952-32944d00-9e7a-11ea-805a-914e33f33481.png)

Clicking OK on this error gives this error from Adobe Acrobat Reader: 

![image](https://user-images.githubusercontent.com/65363206/82826334-eb5a8c00-9e7a-11ea-8e86-3e7e07a86aac.png)

I must first CLOSE the app and close Adobe Reader (which was opened by PTXprint), then reopen the app, in order for the PRINT process to run successfully.

Hopefully you all can recreate it. (I just verified the PRINT ran successfully after a restart of v0.7.0. I changed nothing in the configuration file.)

**Comment by markpenny** [comment]
Oh, @davidc86 we put that bug in there just to help you know for sure that you've successfully upgraded to a new version  ;-)

Oh well, back to hunting for it...

**Comment by markpenny** [comment]
The next time you do this (upgrading to 0.7.x), could you wait 10 seconds (after the installer has completed) before doing the "Finish" and run... A few versions back I was getting a similar error message (but I don't recall if it was exactly the same) - which made me feel like it hadn't really finished installing. Pausing for a few seconds before running stopped those messages from coming. But, yes, it would be nice to know WHY this is happening...

**Comment by davidc86** [comment]
Correct. It finishes installing and tells me it's done. The "Launch PTXprint" option is selected. And when I click Finish/Done (whatever), it closes the install window and launches PTXprint. All is good. I can edit and do stuff in that PTXprint window just fine. But when I first hit PRINT, it goes off and gets busy, and then pops these 2 errors. 

Closing Acrobat Reader and closing PTXprint and re-opening PTXprint gets it all sorted out again. The only clue might be that I launch the installer with Admin privileges, so maybe the installer launches the first PTXprint with Admin privileges? But the Acrobat Reader is launched by Windows to open the PDF file, and maybe the two are using different "privileges"? Because Acrobat says it can't open a file "inside an AppContainer in protected mode." -- whatever that means. So I'll leave this in y'alls capable hands. I'm clueless...

**Comment by davidc86** [comment]
Still an Issue. 
Installed 0.8.1, let it launch itself. Waited awhile. Didn't change anything. And hit Print. And this popped up:

![image](https://user-images.githubusercontent.com/65363206/84382865-4ac5d500-abb9-11ea-915b-20aa8931016e.png)

Maybe it is due to another issue. I'm still checking. But I wanted to capture that screenshot before closing it.

**Comment by mhosken** [comment]
You think we know? We aren't a big team with lots of Windows experience (2/3 are working on linux). All bug testing on this from anyone will help. I doubt anything has changed with 0.8 but removing the splash may have helped.

**Comment by davidc86** [comment]
I'll test it next update! During the last update my data and style sheets were giving error messages, so it spoiled the test!

**Comment by davidc86** [comment]
FIXED! I finally didn't mess up my test configuration before checking this. 0.8.2 did not throw an error on first build after installation. Nice.
