### ISSUE TITLE
How to suppress the LINE drawn between books on same page?

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#892]
Any way to suppress displaying the LINE ("rule") drawn between two boks when the next book is set to continue on the same page as the last book?

![image](https://github.com/sillsdev/ptx2pdf/assets/65363206/b2b3e342-a7e7-4518-a3bc-3eae9fe8d094)

**Comment by markpenny** [comment]
@davidc86 I haven't been able to find a way (yet) to remove the horizontal rule between books that have been flowed together on the same page, but I have managed to tighten up the gap between them by using **negative** Space Before/After values as shown below:

![image](https://github.com/sillsdev/ptx2pdf/assets/12962708/a5e09122-46fb-444a-a1d0-d0aa2cce7901)

**Comment by davidg-sil** [comment]
But, but, the line is a requirement!

Oh all right then, I'll make it a bit cleverer:
Default definition, for replacing, fiddling with, **etc.nn:**
```
\def\bookendrule{\vskip\baselineskip
  \hskip -\columnshift\hrule\vskip 2\baselineskip}
\def\lastbookendrule{}
```

**Comment by markpenny** [comment]
@davidc86 This means that you can pop this into your **ptxprint-mods.tex** file to prevent the line from showing up at all:

`\def\bookendrule{}`

![image](https://github.com/sillsdev/ptx2pdf/assets/12962708/f59d50d6-2b7f-4c6e-93ef-f62a17b46d4d)

But note that you may now need to restore the \mt1 and \mt2 (negative) line spacing values to their defaults in the Styles section. Otherwise the \mt1 will back up into the text of the previous verse.

**Comment by davidc86** [comment]
Thank you for working on this. So, I popped:

\def\bookendrule{}
 
Into the ptxprint-mods.tex file, and it did get rid of the rule between books. 

But when I commented this line out with %, it **did not restore the rule/line**. Any clues? 
Or does the user now have to do more than just leave this out or comment it out to get a rule between books?

**Comment by markpenny** [comment]
@davidc86 That's very strange. It works fine for me :-) 

Does it work if you put all this in?

```
\def\bookendrule{\vskip\baselineskip
  \hskip -\columnshift\hrule\vskip 2\baselineskip}
\def\lastbookendrule{}
```

**Comment by davidc86** [comment]
Yes, it does. But I didn't expect add/removing a bookendrule would be so complex. :) I had assumed like a dummy that it would be like the Registry and {0} would clear the rule and {1} would show the rule. My bad.

**Comment by davidc86** [comment]
Well, bummer. Now that I tested it with:

\def\bookendrule{\vskip\baselineskip
  \hskip -\columnshift\hrule\vskip 2\baselineskip}
\def\lastbookendrule{}

I tried to remove it again, and now I get an error: 

![image](https://github.com/sillsdev/ptx2pdf/assets/65363206/c5d2a5d2-896a-4a7e-bc84-8e8655a9b356)

Restarting doesn't help. I'm stuck.

**Comment by davidg-sil** [comment]
Yes, you told it to output `def `. It didn't have a recognised font set (that's fixable, I think) so it fell back to something it assumed would always be available, the orginal TeX font.
