### ISSUE TITLE
Copyright Picture text box style for None is ignoring its settings

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#897]
This may be related to the Font Size issue in #896

If I specify a (c) text box **offset** using _**Space Before**_, this works just fine for the "Light|x-credit" style. (It shifts the (c) box down slightly to not overlap the pictures.)

It doesn't do anything for the Pictures that use the specs "br,0,None" (i.e. the "None|x-credit" style).

**Comment by davidg-sil** [comment]
I'm assuming that this is the same cause as #896, and I suggest the same remedy - `ptxprint-mods.sty` overrides anything set in the user interface.

**Comment by davidc86** [comment]
Not using any style files. Just the Styles tab in PTXprint.

**Comment by davidg-sil** [comment]
Aaargh!
Some change compared to when I last checked has meant that the piclist is not being written correctly!
When box style 'None' is selected, it's (now) not writing the `x-creditbox="None"` that TeX expects. 
'None' is not a special value to TeX, but it obviously is to python. Not specifying the x-creditbox settings means (to TeX) that you only want to apply settings from  `x-credit`. Which might well include a defined background colour, whereas `x-creditbox="None"` is supposed to be a pre-defined value associated with there not being a box. I'll see if I can decipher the python code, but I'll probably have to pass it on to Mark/Martin
