### ISSUE TITLE
PTXprint's drop-downs and dialogs (like the (c) spec dialog) show up on a different screen from the main window

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#898]
If I put PTXprint on my external monitor (set above my laptop, so it is a vertical motion to move stuff up to it), and then if I open a drop-down or a dialog (like the (c) spec dialog), they will show up on the top far right of my laptop screen. Usually, I don't even see the drop-down lists as they are so small, and I think PTXprint has crashed or become unresponsive.

Can the dialogs and drop-down lists be calculated so they open up on the main PTXprint window?

Here is a screenshot with the (c) dialog open:

![image](https://github.com/sillsdev/ptx2pdf/assets/65363206/e5814085-0dc6-4fe1-8878-79de43f8d179)

And with a drop-down list open:

![image](https://github.com/sillsdev/ptx2pdf/assets/65363206/8f2931aa-005c-4b57-adfd-23d944031cd6)

My external monitor is 1920x1080 set at 100%

My laptop screen is 3840x2160 set at 200% (so the same amount of content is shown on each).

Any clue what is going on?

Here is the arrangement:
![image](https://github.com/sillsdev/ptx2pdf/assets/65363206/71f01c38-ef11-483f-ab1d-13525c6b37b4)

**Comment by davidg-sil** [comment]
So the new pop-up windows are always cropping up on 'screen 1'? I wonder if that's reproducible. I'll need to dig up a semi-retired laptop to find out, as all my external monitors are VGA and my laptop doesn't have VGA output. Maybe someone else can try who does have a second screen?
Windows/linux comparison would be good too.

**Comment by davidc86** [comment]
Yes, it is reproducible. Has happened every time with this laptop and monitor. And it did with my last laptop and monitor (I just didn't mention it.) Kind of weird.

**Comment by markpenny** [comment]
@davidc86 I'm still unable to reproduce it, but will keep an eye out for it on another laptop+large screen combo. However, I am guessing it is just some deep down bug in PyGTK which we won't be able to do much about. Something obviously related to scaling of monitors, but that's as far as I can work out.

**Comment by davidg-sil** [comment]
Right... here are some testing results, 2 monitors, 2 laptops:

OS | Laptop| screen | External screen | PTXprint | dropdowns/popup
--------|--------|-----|-----|---|---
Linux (xfce)| 1| 1920x1080 | 1024x768 | Laptop | laptop
Linux (xfce)| 1| 1920x1080 | 1024x768 | external | external
Linux (xfce)| 1| 1920x1080 | 1600x900 | Laptop | laptop
Linux (xfce)| 1| 1920x1080 | 1600x900 | external | external
Linux (xfce)| 2| 1366x768 | 1600x900 | Laptop | laptop
Linux (xfce)| 2| 1366x768 | 1600x900 | external | external

i.e no sign of problem here. We obviously need more test results if it's still playing up for you.

**Comment by davidc86** [comment]
Well, bummer. I just updated PTXprint, to see if the problem has been resolved, but if I put the app window in the external monitor and press the drop down arrow, I get this: 

![Screenshot 2024-03-09 150628 (Large)](https://github.com/sillsdev/ptx2pdf/assets/65363206/bd35a268-78d1-48a1-a186-d6d584e4d9f0)

So, are you all testing this on Windows 11 (not Linux), with the external positioned ABOVE the main laptop screen? Just wondering if that is the problem.

**Comment by davidg-sil** [comment]
More thoughts.... I wasn't testing with above/below earlier, but I've just re-tested a few other arrangements and I can't make it break on linux. It looks like it's either windows-specific or high-res monitor-specific.

@markpenny, were you testing up-down or only left-right?
 
@davidc86, Can you confirm that it's *all* dropdown menus? 
Also, do you have an old monitor  / change the resolution of the external monitor, to see if it's only affecting you at certain resolutions or might it even be only USB monitors not HDMI??

Everyone else... I wonder if anyone knows of other python+glade programs that davidc could  test, to see if it's not just PTXprint that's misbehaving?

**Comment by davidg-sil** [comment]
I've no idea if this helps:
https://stackoverflow.com/questions/22772968/python-pygtk-how-to-put-a-window-on-a-specific-display-monitor

**Comment by mnjames** [comment]
I can reproduce this.

My standard setup is almost like @davidc86. A 1080p external monitor and a 4k laptop monitor. Here's what I found.
* When the external monitor was set in Windows to the right of the laptop screen (my normal setup), the dialogues always worked as expected.
* If the monitor was moved to above the laptop, and if I ran ptxprint from source via MinGW (my normal way), everything worked fine.
* But, if the monitor was above the laptop and if I ran ptxprint from the standard Windows version installed from the website, then I'm getting the same behavior--disconnected dialogues on my primary (laptop) screen.

**Comment by davidc86** [comment]
As to the question: is this all drop-downs? Yes. All drop-downs. 
My external monitor is fairly old, but uses HDMI. But its best resolution is 1080. While my laptop is native 4K (which I've set to 200% to help make it readable). 
Just seems really strange to me that in Windows, a drop-down dialog's default screen position is NOT a function of the calling application's screen position/location. 
Mine might be an edge case, but it catches me out ever time. Thanks for looking into it.

**Comment by mhosken** [comment]
This looks to be a GTK bug. The problem is that we are using GTK3 which is not receiving updates (sigh. Oh for some maturity in the computing world). There are two workarounds, either of which should work:

1. Ensure that the left most monitor is the primary monitory, or
2. Run PTXprint from the primary monitor.

For the record, this patch should fix things: https://gitlab.gnome.org/GNOME/gtk/-/commit/9f9479a50fe9dac5a17b1026d665b7c5b87d1f75

**Comment by davidc86** [comment]
This looks fixed in PTXprint v2.6.1 
Woohoo! 
Now if only FLEx would fix this issue too. (Apparently it isn't a bug with our software, eh?)
