### ISSUE TITLE
inner margin verses problem

### ISSUE THREAD

**Issue by kylak** [sillsdev/ptx2pdf#900]
Hello

I have a problem to do inner margin verses on the family 35 new testament. I followed these steps https://software.sil.org/ptxprint/documentation/how-to-reader-layout-inner-margin-verses/ but it doesn't work ..

Anyone could help me ?

Thanks.
Gustav

**Comment by davidg-sil** [comment]
"It doesn't work" is almost certainly too vague for anyone to give any help.  Could you be more precise? Do you get the marginal verses on the outside, or not at all, or does it crash? If there are rights/permissions/sensitivity/etc reasons you can't post a screenshot of a page not working, then please post a clear description.

**Comment by kylak** [comment]
@davidg-sil Here is a screenshot of the result I get :

![Capture d’écran du 2023-08-26 17-02-49](https://github.com/sillsdev/ptx2pdf/assets/16438248/7b908235-20a6-4185-9539-8fedaf406e2a)

As you can see the verse numbers are not in the margin but rather in the text.

@mhosken concerning the archive, the mail you shared seems to be encrypted.

Best regards,
Gustav

**Comment by davidg-sil** [comment]
The email address is written next to the 'create an archive button' (on the help menu), among various other places:
![image](https://github.com/sillsdev/ptx2pdf/assets/58848232/8a8f1f96-388e-4e43-a94e-5cb0f805b300)

**Comment by kylak** [comment]
Ok! email sent, thanks!

**Comment by markpenny** [comment]
Thank you @kylak for bringing this to our attention, and for sending in an archive. I have replied to your e-mail, and also updated [the instructions online](https://software.sil.org/ptxprint/documentation/how-to-reader-layout-inner-margin-verses/).

Please follow the new instructions and let us know how it goes. If all is well, then close the issue.
