### ISSUE TITLE
Have an initial font selected.

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#901]
If there's any text output in ptxprint-mods.tex, (e.g. because someone lost a slash) then XeTeX, not having a font selected, starts looking for cmr10. If we set another font, then windows users wouldn't crash so spectacularly and would just be left with random stuff on page one of their output.

**Comment by devosb** [comment]
The [CM fonts are included](https://github.com/sillsdev/ptx2pdf/tree/master/xetex/texmf-dist/fonts/tfm/public/cm) in the TeX tree on Windows, so I am surprised that cmr10 is not found, thus causing a crash. In the recent update of TeX Live, some [CM fonts were removed](https://github.com/sillsdev/ptx2pdf/commit/5d5c063706d0fe202fb1bae39a9bc87938558d4d#diff-4ceff89b6960da36b1c7453f1fcd3aa7018b8f04dede1d275805e4f3a94dafe4R48-R53) from PTXprint, as they were included in the W32TeX build, but not the current TeX Live.

**Comment by davidg-sil** [comment]
The crash (see #892) was in 2.3.37, so before your latest changes. I don't know if that's at all significant. 
Oh! I see what it is!

The tfm (TeX Font metrics) files are there, but not the metafont source (to draw the bitmap font). So it can lay out the file, but not actually generate the bitmaps. That metafont source (`texlive/texmf-dist/fonts/source/public/cm`)  looks like being about 880kb on my Linux box. There may be other config files needed as well, I don't know. I don't think it's worth the pain / additional download space, since we don't want anyone using bitmap fonts anyway. So setting a default font other than cmr10 still sounds like a good idea!

**Comment by mhosken** [comment]
We do ship with sans source pro or whatever it is (see ptx-cropmarks.tex)

GB,
Martin
