### ISSUE TITLE
Adjustment to page num posn in non-Diglot back matter

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#904]
When the page number position has been tweaked to align with slight changes in the col widths for Diglots, it looks great:
![image](https://github.com/sillsdev/ptx2pdf/assets/12962708/9fa5a06f-7373-4fd8-b7dc-7c5fc26081b6)

But when the GLO (and presumably other back matter is produced) in monglot format, we need to be able to suppress that tweak so that it appears in the middle, not offset as it does now:
![image](https://github.com/sillsdev/ptx2pdf/assets/12962708/4ea620a8-2cd4-4dc6-a386-efa5dc3d51a5)

**Comment by davidg-sil** [comment]
Addressed in 295082e9f3
