### ISSUE TITLE
--nofontcache does not do what it says it does

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#908]
The command-line `--nofontcache` "Don't use system fonts" Does not alter the `fonts.conf` file generated by ptxprint and then used by TeX. I've added a `notpytest` boolean to `fonts.py` that probably needs renaming and attaching to the command-line  flag, but I don't even know *if* that sets a global variable, let alone what it's called.
Not obeying that option leads to needless xfails when running pytest-3

**Comment by markpenny** [comment]
@mhosken Did you already fix this one? If so, go ahead and close it.

**Comment by davidg-sil** [comment]
Closing this, as I've now added another command-line option that resolves the issue.
