### ISSUE TITLE
PTXprint won't let me specify a reasonable \b line-spacing value

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#909]
PTXprint won't let me specify a reasonable \b line-spacing value.
Sure the default, preferred method of formatting printed documents is to try and keep lines on a grid.

But sometimes it just would be nice to do something like make \b = 1/2 line space, so that OT quoted verses can have a \b above and below. And the 1/2 + 1/2 line spacing from the 2 \b's brings the rest of the text back onto the grid.

Something in PTXprint is not allowing this. Can this "policing" be overridden?

**Comment by davidg-sil** [comment]
The provided definition of `\b` in `ptx-stylesheet.tex` is to produce a gap equal to its linespacing. There have been, at various times in history, other definitions in snippets. Including, I see,  one in `snippets.py`'s definition of 'unusedstuff'  which defines it as a rigid 10pt.
I wonder if you might have some definition in a custom `ptxprint-mods.tex` that overrides the default value, or if there is a customised value in the 'i**gnore the User-interface, I know what I'm doing'**  style sheet overrides file, `ptxprint-mods.sty`

**Comment by davidg-sil** [comment]
Sorry,  I should have checked before writing from my phone. A typo meant the code was getting the *previous* marker's baseline, not its own.
