### ISSUE TITLE
PicList doesn't allow references to segmented verses

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#91]
A good place to put a picture of the stoning of Steven is at the end of Acts 7 or the beginning of ch8. Our version of Acts 8 has a 1a before the section heading and a 1b after the section heading. (This is required for other audio playback reasons.) I have found that PTXprint won't display the picture if I try to reference 8.1a 

I think this limitation should be added to the notes about PicList at the end. You do say that \v 3-4 needs to be referenced as 8.3 but I don't see any tips on how to handle segmented verses.

I'm wondering if 8.1 would work for \v 1a but I believe I tried that too, and it didn't work.

And, I just tried point to a verse range *Acts 13:6-8*. I marked it in PicList as **ACT 13.6** as directed, but the picture **failed to show** there as well. So it looks like if the verse reference is anything other than a plain number, PicList isn't handling it yet.

**Comment by mhosken** [comment]
Yes, the ptx macros only allow a piclist to reference to the verse level, not the paragraph level. This differs from .adj files which can reference paragraphs within a verse. There are no plans to change this.
If you need that level of accuracy, then you can insert a \fig into the text itself, either by typing it into the source .sfm or using a change to get it in there (e.g. a milestone in the text which gets swapped out with the appropriate \fig line).

**Comment by davidc86** [comment]
The problem is not the limitations of PTXprint design. The problem is with our understanding of how the PicList can be made to reference a verse in the scripture text which happens to be marked by a verse segment or a verse range. I.e. it just so happens the picture needs to hook to a verse marked by **\v 6-8** or to **\v 4a**. 

The instructions for PicList say to use the *first number*, like **GEN 10.6** for a verse range **\v 6-8**. But I found that this didn't work. (The picture didn't display.) I also don't know what to put in the PicList if the referenced verse is a segment, like **\v 4a**, because **GEN 12.4** does *not* work. (The picture didn't display.)

So the "bug" is with how PicList fails to handle it when the reference verse in the PicList points to a verse number which is a mixture of range or letter segments in the PT scripture text.
