### ISSUE TITLE
No such file or directory: /home/user/Paratext8Projects

### ISSUE THREAD

**Issue by burntsun** [sillsdev/ptx2pdf#911]
I installed PTXPrint on Ubuntu. When I launch it, it fails to open. When I launch it from the terminal, I see this error:

```
Traceback (most recent call last):
  File "/usr/bin/ptxprint", line 331, in <module>
    mainw.setup_ini()
  File "/usr/lib/python3/dist-packages/ptxprint/gtkview.py", line 741, in setup_ini
    for d in os.listdir(self.settings_dir):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/Paratext8Projects'
```

I don't have a `Paratext8Projects` directory in my home directory. I think it would be better if PTXPrint recovered from this well and launched the program, or at least to displayed an error in a GUI.

**Comment by davidg-sil** [comment]
Most users do have paratext, so testing on machines without it has always been a bit sparse. Sorry for the unannounced bug. 
While PTXprint does not require you to have paratext installed, it does need to have a 'Paratext Directory' (discovered or set). You can tell it what that directory should be with the command-line argument  `-p /path/to/directory` 
An empty directory is fine, if you're going to be e.g. using bundles from the DBL, or unwrapping backups from Paratext there.

If you have USFM you've been editing in some other scripture-editing program, then it  expects that to be in a 'project directory', below the paratext directory. That directory should include the following:
* **A `Settings.xml` file** in (each) project directory. Solving crashes one by one, it looks like a minimal usable example would be:
```
<ScriptureText>
  <FileNameBookNameForm>MAT</FileNameBookNameForm>
  <FileNamePostPart>.usfm</FileNamePostPart>
  <FileNamePrePart />
</ScriptureText>
```
* **Scripture in one-file-per-book** named according to the schema specified. Paratext normally uses `ProjectID` for the PrePart,  `40MAT` for the BookNameForm, and `.SFM`  for the PostPart, giving you files like ProjectID01GEN.SFM.
 The above Settings.xml expects a simpler `GEN.usfm` file,  but I don't think there is any way to make it expect e.g. `Exodus.usfm`, let alone one-file-per-chapter. 
 
 Some scripting can be set up to update your USFM files if that's desirable. PTXprint will treat the above USFM files as read-only (unless you generate a Strong's concordance and save it as book  `XXA`).

**Comment by burntsun** [comment]
Thank you so much for the help!

**Comment by mhosken** [comment]
More. You don't need a settings.xml. ptxprint will generate one itself when
it loads your project.

**Comment by davidg-sil** [comment]
Is this a very recent change, @mhosken, or something that used to work but doesn't now, I wonder? I arrived at that set of criteria by trial and error, starting with just some USFM in an otherwise empty 'project' directory (without the settings.xml, I don't think the project directory was available on the menu).
