### ISSUE TITLE
Creating a new saved configuration is quirky (workshop suggestion)

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#918]
Creating a new saved configuration is quirky.  You are looking at the current configuration name and you can type over top of it to save a new one, but that feels wrong.  It feels like you are renaming the current configuration instead.  People are familiar with Save, Save as….  It seems that it would be more helpful to have buttons like these standard ones:
New - Make a new configuration based on the Default style
Open - (Could skip this as open is simply selecting from the dropdown)
Save - (No change needed as the save button is already prominently displayed) After I said that, I realize how important the save button is to people.  I don’t want to lose my existing configuration when I create a new one, so I would be looking for the save button before I would dare click the New button to create a new configuration.
Save as… - Copy the existing configuration into a new one, based on the current configuration.

**Comment by mhosken** [comment]
Perhaps we simplify to add an "add config" button and make the config list not typable?
