### ISSUE TITLE
Reset all settings on the current tab/page (workshop suggestion)

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#919]
It would be nice if there were a way to reset the defaults on each sub-page, rather than having to reset via delete all the current settings.

This is being implemented:
![image](https://github.com/sillsdev/ptx2pdf/assets/12962708/dcf1cf0e-1de2-48ac-b0b2-7f00c7247c5e)

**Comment by mhosken** [comment]
This is hard. But we do have most every different setting now with a bold label so it's easy to find which ones need resetting and you can click on them to reset them.
