### ISSUE TITLE
decison needed on merging diglot branch into master

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#92]
Maintianing 2 code-bases and manual merging isn't fun, and there are a lot of tweaks happening here and there which turn into manual merges.
Once I've merged in my 'where have my footnotes gone' patch, (not tonight, maybe tomorrow, maybe Wednesday?) then I'm not aware of anything in diglot that breaks stuff that works in master... it ought to just be extra functionality.  I wonder if some brave folks could checkout diglot and try to use it on their favourite bug-hunting (monoglot) examples?

**Comment by davidg-sil** [comment]
OK, well, I wasn't going to... but I did it... except some diglotty python edits have been pushed that conflict with master and I don't know enough to try to resolve them.
i.e. https://github.com/davidg-sil/ptx2pdf/tree/diglot can now apply cleanly to silsdev/master, but not to silsdev/diglot.

**Comment by markpenny** [comment]
@mhosken I'm not following the significance of this, but wonder what @davidg-sil means by that last comment: i.e. https://github.com/davidg-sil/ptx2pdf/tree/diglot can now apply cleanly to silsdev/master, but not to silsdev/diglot.
Were there 2 different 'branches' called diglot? If so, did we get the right one? If not, can we close this issue?
