### ISSUE TITLE
Change the default behaviour so that FN/XR callers are reset at every book

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#923]
According to GPS, the callers need to be reset at the start of EVERY BOOK. However, we should also be able to override that behaviour if the user prefers not to do so. (perhaps a TeXhacks checkbox)

**Comment by davidg-sil** [comment]
I'll implement this on the TeX side as  `\ifbookresetcallers`  (true to do it)

**Comment by davidg-sil** [comment]
There is a potential clash between `\bookresetcallerstrue` and `\PageResetCallers(f)` I propose to make it so that book resets only happen to a given marker if page-based resets are not happening.

**Comment by markpenny** [comment]
@davidg-sil I couldn't make it work, and don't see any reference to bookresetcallers in the code, so wonder if something didn't get saved before you pushed.

**Comment by davidg-sil** [comment]
Fixed now, I hope! A key file got left out :-(
