### ISSUE TITLE
Spacing Bug for Marginal Verses

### ISSUE THREAD

**Issue by RCraigWebb** [sillsdev/ptx2pdf#926]
Hello PTXPrint,

I've been working on formatting for marginal verses and when I click on Advanced/Misc Refinement Settings and change the After Verse Space Factor it works well on regular verse numbers but doesn't adjust the verse bridges. I've been changing the default setting of 0.15 to 0.30 to increase the spacing from 1mm to 1.5mm and noticed the numbers aren't lining up anymore. If I set it back to the default the numbers are in line again. This is with Paratext project KHT in the book of Mat with \versehyphentrue added in the mods. Let me know if you want me to send examples and/or the Paratext files.

Marginal verses are looking much better than they did before. I know this is low priority for most of the world so I appreciate your work.

Craig

**Comment by mhosken** [comment]
I'm not sure I understand the problem, do a couple of close ups of 1mm and
1.5mm will help me see what you are seeing.

**Comment by RCraigWebb** [comment]
Hello Martin,

 

Here are two files, the 15 is the default setting and all verse numbers are aligned. The 30 is with the adjustment and the single verse numbers are adjusted correctly and the verse bridges are still in the same place as with the default setting.

 

Low priority but when you get time.

 

Hope you are enjoying your visit home. Your presence is missed.

 

Craig

________________________________

 

R. Craig Webb
Publishing Coordinator
MSEAG 

Mobile: 099-136-7746
________________________________

**Comment by RCraigWebb** [comment]
![Default of 15](https://github.com/sillsdev/ptx2pdf/assets/140577140/05808384-9df2-407f-9850-1318d6f2078a)
![Setting at 30](https://github.com/sillsdev/ptx2pdf/assets/140577140/5704522a-b2e2-4964-9f03-a3ab6916d498)
Here are screenshots

**Comment by mhosken** [comment]
I think the increased space after the verse has meant that the overall
space taken up by a bridge plus the space after the verse number is greater
than the space allocation for marginal verses and so the bridged verses
push in towards the text. Try increasing the space allocation for marginal
verses.

**Comment by markpenny** [comment]
@RCraigWebb Did @mhosken's suggestion solve this issue? If so, please go ahead and close the issue. If not, we will have to dig further for a solution.
