### ISSUE TITLE
PicList has a bug where it can't reference a verse that is not a plain number

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#93]
I'm reissuing this bug, because it is a bug, not an "outside the scope of PTXprint design" issue.
The bug is that PicList is unable to reference a verse which is not a plain number.

PicList can't be made to reference a verse in the scripture text which happens to be marked by a verse segment or a verse range. I.e. if the picture needs to hook to a verse marked by **\v 6-8** or to **\v 4a**. (I'm not asking for the ability to hook it to \v 4b rather than \v4a or the end of \v 6-8 rather than the beginning. I'm just letting you know that PicList fails to link to any such verse.)

The instructions for PicList say to use the *first number*, like for a verse range **\v 6-8**, you tell us to use **GEN 10.6**. But this didn't work; the picture didn't display. 

Likewise, if the verse happens to be a segment, like **\v 4a**, it is unclear how we can reference that as the anchor for the picture. because I tried both **GEN 12.4a**  and **GEN 12.4** and neither worked. (Again, the picture didn't display.)

So the "bug" is that PicList fails to handle it when the reference verse in the PicList points to a verse number which happens to be a mixture of range or letter segments in the PT scripture text. 

PicList should be able to point to whatever is in the scripture text. (I.e. if it is \v 4a, then GEN 12.4a should work; if it is \v 6-8, then GEN 10.6-8 should work. Or if it is easier to code, then GEN 12.4 and GEN 10.6 should work. Either way, PicList should not fail to link just because it can't handle complex verses.)

**Comment by mhosken** [comment]
Odd that GEN 12.4a doesn't work or that GEN 10.6-8 doesn't work. Basically the verse part of the reference needs to be exactly what is the value of \v in the text. I'll add some tracing into the macros and you can take a look. Add \tracing{g} into your .sty or .tex addin file and look for the many Compare statements. It'll be in the next .tex macros you get (either from source or the next point release).

**Comment by markpenny** [comment]
For the moment the generated PicList will now point to the verse BEFORE the segmented verse ref. (e.g. if the \fig ....\fig* is pointing to \v 45b  then the anchor will end up at \v 44. This at least ensures that the image will show up, and not prevent other images later in the list from disappearing.
At a later point we may be able to fix the macros to make it possible to anchor at verse segments, but for now (as we try to get to a RC for v1.0), this will have to do.
