### ISSUE TITLE
E: Internal Error, No file name for python3-ptxprint:amd64

### ISSUE THREAD

**Issue by KimB2017** [sillsdev/ptx2pdf#931]
I'm getting this error each time I install/update any packages in Synaptic, Wasta 20.04. The PTXPrint version that gives this error is 2.4.4, and I have been using this same version heavily with no apparent problems. I have tried reinstalling PTXPrint with no change in this error message... but I haven't wanted to uninstall it because I am on a tight schedule. I went to /var/cache/apt/archives and deleted the .deb file, thinking it would download again, but the installer files must be stored somewhere else because the package does not get redownloaded.

Should I be concerned, and is there anything I can do about it?
Thanks!

**Comment by mhosken** [comment]
I'm suspicious that the 20.04 distribution is a bit messed up at the
moment. We will try to sort it out.

**Comment by markpenny** [comment]
@KimB2017 Did this issue resolve itself in the end, or is there still something to be done?
If all is well, please close the issue yourself. Ta!

**Comment by KimB2017** [comment]
Yes, sorry... I figured you had fixed in the next update after this one.
