### ISSUE TITLE
Problem on pages

### ISSUE THREAD

**Issue by KNNettey** [sillsdev/ptx2pdf#935]
[GBVN96_Default_MRK_ptxp.pdf](https://github.com/sillsdev/ptx2pdf/files/13740813/GBVN96_Default_MRK_ptxp.pdf)

You will notice that some of the pages do NOT have the suggested number of lines on them. Page 1 has the title of the book and then 2 text lines.

How do I get all the to have the same number lines except the last page which may be shorter.

Thank you.

**Comment by mhosken** [comment]
Are you running the latest version of PTPrint? If so, send an archive and
we'll see why such a bad break is occurring and hopefully fix it for a late
version, or tell you what you need to do to fix it.

**Comment by mhosken** [comment]
Please do send an archive to ***@***.*** These bad breaks are
something I want to fix, but it's hard to generate them, so I value every
example I can recreate.

**Comment by KNNettey** [comment]
Kingsley Nettey

AF130 Mantse Ayiku Street

GZ-144-4161

P. O. Box AN12464

Accra, Ghana

E-mail: ***@***.*** ***@***.***> 

          ***@***.*** ***@***.***> 

Telephone No./WhatsApp No.: +233208612951

Cell No.: +233554660961

**Comment by KNNettey** [comment]
Kingsley Nettey

AF130 Mantse Ayiku Street

GZ-144-4161

P. O. Box AN12464

Accra, Ghana

E-mail: ***@***.*** ***@***.***> 

          ***@***.*** ***@***.***> 

Telephone No./WhatsApp No.: +233208612951

Cell No.: +233554660961

**Comment by mhosken** [comment]
Sorry the email address didn't come through. ptxprint_support at sil.org.
All email addresses are scrambled for security reasons, by github, so I
can't see yours I respond.

You can find the Create Archive button on the help page.

**Comment by KNNettey** [comment]
[GBVN96_Default_MRK_ptxp.pdf](https://github.com/sillsdev/ptx2pdf/files/13752105/GBVN96_Default_MRK_ptxp.pdf)
[GBVN96-DefaultPTXprintArchive.zip](https://github.com/sillsdev/ptx2pdf/files/13752107/GBVN96-DefaultPTXprintArchive.zip)

Yes, I installed the newest version of the program.

Attached is the archive.

**Comment by markpenny** [comment]
Dear Kingsley,
Apologies for the long delay in responding to you. I have been away and just picked up your message.
One work-around for the bad page breaks is to allow 1 or more "Unbalanced Lines" as shown here:
![image](https://github.com/sillsdev/ptx2pdf/assets/12962708/5174b01a-5724-4cef-b851-b4c1999206de)
That will allow PTXprint to fill the page even if it isn't able to balance the number of lines in each column.
[GBVN96_Default_MRK_ptxp.pdf](https://github.com/sillsdev/ptx2pdf/files/13957960/GBVN96_Default_MRK_ptxp.pdf)
It is clear that the main problem here is that EVERY verse starts as a new paragraph, and that makes proper typesetting rather difficult.
