### ISSUE TITLE
End of Book pdf no longer gets output

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#938]
v2.4.7
The End of Book PDF no longer gets put into the output PDF file.

Here is what always worked before:
![image](https://github.com/sillsdev/ptx2pdf/assets/65363206/da5b8f02-308d-44d4-b076-3a763072dc7c)

It looked like this when it worked: 
![image](https://github.com/sillsdev/ptx2pdf/assets/65363206/94b5641f-5a82-41c1-98ac-6211791b5282)

Now it looks like this:
![image](https://github.com/sillsdev/ptx2pdf/assets/65363206/7deb655e-f9b7-438d-bd44-c18e4229c5b2)

All I did was update PTXprint from 2.4.6 to 2.4.7

**Comment by davidg-sil** [comment]
Having had a quick look through the changes between 2.4.6 and 2.4.7, urm... I really can't see anything that would do that.  I think we'll need an archive.

**Comment by davidc86** [comment]
[SLU-PublikasiSelaru-RomaPTXprintArchive.zip](https://github.com/sillsdev/ptx2pdf/files/13865093/SLU-PublikasiSelaru-RomaPTXprintArchive.zip)

PTXprint fails to print the End of Book PDF on all our books, so I'm sending Romans which is smaller.
