### ISSUE TITLE
Is there a way to turn off "widow/orphan control"?

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#94]
I'm not seeing an option to turn off "widow/orphan control", but I can tell PTXprint (or something underneath is using that kind of control. Some programs allow us to specify these separately (like: "Allow a single line from the beginning of a paragraph to occur at the bottom of the page." 
"Allow a single line from the bottom of a paragraph to go to the next page."

I mention this because if both widow and orphan controls are always on, then any paragraph that is only 3 lines long never split across the page, and this leaves a pretty large gap at the bottom of pages. 

Just wondering what other folk are seeing and thinking on this.

**Comment by mhosken** [comment]
TeX is never so black and white. There is a cost associated with a widow or orphan which impacts linebreaking. But it doesn't preclude widows and orphans if that's the best option in the circumstances. If you want to get into that kind of thing, feel free to read the TeXbook and use hooks to set appropriate values in appropriate places.
