### ISSUE TITLE
Center vertical grid line needs shifting in diglots

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#941]
When Show Grid lines is enabled for a diglot with 40/60 col widths, the even/left pages position the middle red line correctly, but the odd/right pages fail to move the line as needed. (Hope it is an easy fix!)
![2024-01-16 19_00_16-OYBC_Yid-Latn-Eng_MAT-REV_ptxp pdf -  Orthodox Yiddish Brit Chadasha New Testame](https://github.com/sillsdev/ptx2pdf/assets/12962708/5c7ffc6a-e261-408b-b1ba-fce0cf275e4c)

**Comment by mhosken** [comment]
Just need to not mirror the grids
