### ISSUE TITLE
Problem with Hanifi text

### ISSUE THREAD

**Issue by sewhite** [sillsdev/ptx2pdf#948]
A user reports a problem with the Hanifi script for the Rohingya language.
 I tried it and got  this error.
 
![image](https://github.com/sillsdev/ptx2pdf/assets/16904461/a897450b-265a-4069-85de-8527e1a0718e)
My test project just has two words in Gen 1:

\c 1 \p \v 1 𐴀𐴞𐴕𐴐𐴝𐴦𐴕 𐴁𐴠𐴒𐴧𐴟𐴕

The font used is "Noto Sans Hanifi Rohingya".

**Comment by sewhite** [comment]
The font page:
https://fonts.google.com/noto/specimen/Noto+Sans+Hanifi+Rohingya

**Comment by markpenny** [comment]
Hi Steve,
Thanks for reporting this. Could you ask the user to create an Archive file using the button on the Help tab. That will allow us to get all the settings (and the font) in order to reproduce the issue locally, If it can't be attached here, then please send by e-mail directly to the ptxprint _ support @ sil.org address (without any spaces of course).
Thanks.

**Comment by sewhite** [comment]
Here is my archive. I don't know if the user is having the same problem I have. 
[RFT-DefaultPTXprintArchive.zip](https://github.com/sillsdev/ptx2pdf/files/14918921/RFT-DefaultPTXprintArchive.zip)

**Comment by markpenny** [comment]
@mhosken Do you know if we can handle these clever/new variable weight fonts? This is the name of the file: NotoSansHanifiRohingya-**VariableFont_wght**.ttf
and this is what the Font config looks like in PTXprint:
![image](https://github.com/sillsdev/ptx2pdf/assets/12962708/59bc5771-29e6-4032-84d3-06075a856e75)

**Comment by mhosken** [comment]
No we can't. We need a way to point that out to users, or to create static
instances for xetex.

GB,
Martin

**Comment by mhosken** [comment]
Here are the static instances that are on my machine. Notice you will also need to turn on the script in the script selector (I've refactored that list a bit, and updated it)
[NotoSansHanifi.zip](https://github.com/sillsdev/ptx2pdf/files/14931019/NotoSansHanifi.zip)

**Comment by mhosken** [comment]
Once I removed the variable font, set the script to Hanifi and set the text direction to right to left, and then set the chapter a verse styles to Noto Sans, I got:
![image](https://github.com/sillsdev/ptx2pdf/assets/5687149/ab84f295-5b4f-4430-b3f6-d37c4dbbff0b)
