### ISSUE TITLE
pre 1.0 cleanups

### ISSUE THREAD

**Issue by mhosken** [sillsdev/ptx2pdf#95]
This issue collects things we really need to fix before 1.0

1. check path is sane in GtkViewModel.onDeleteConfig()
1. only look one dir down in GtkViewModel.updateDiglotConfigList and GtkViewModel.updateSavedConfigLIst
1. make config passwords do something
1. deal with GtkViewModel.onHyphenateClicked
1. decide on a good working dir

More to come, just number them sequentially after these and so on.

**Comment by mhosken** [comment]
5. Fixed in dd161de
1. Rather than some random length test, use whether the folder contains ptxprint.cfg
2. Fixed in f09b53a

**Comment by markpenny** [comment]
* Fixed 3 in 4d8782b
6. Need to update all calls to configPath to make sure the cfgName is passed.

**Comment by markpenny** [comment]
7. When creating a didoc, the footnote area needs to sit on the bottom margin rather than float up to meet the text:
![image](https://user-images.githubusercontent.com/12962708/83335460-95e30c80-a2ca-11ea-94a4-d87f8c6ef5bc.png)
@davidg-sil - I hope that's an easy fix.

**Comment by markpenny** [comment]
* Fixed 4 on [1-June](https://github.com/sillsdev/ptx2pdf/commit/6aaf5845262e56f8ad5b729452bbda4d0dfc74fd)

**Comment by markpenny** [comment]
8 and 9 fixed
11. paths for saved PDFs are being dropped when re-loading from config file. ${workingdir} needs to be populated.

**Comment by mhosken** [comment]
All look fixed. Closing.
