### ISSUE TITLE
Minor UI glitch: the A5 measurement says ...(A4) 

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#950]
This might only be an issue with the Indonesian version of the UI, but in the dropdown list for available page sizes, the A5 measurement says it is "(A4)" not "(A5)".

![PTXprint Pagesize error](https://github.com/sillsdev/ptx2pdf/assets/65363206/20141db0-5ba6-4a21-9c77-3897ef23a826)

It's minor but it really confused us, as we printed out stuff and it came out wrong!

**Comment by markpenny** [comment]
Indeed, it looks like it is a localization issue (which I have now fixed in CrowdIn). It will be right after the next build once Crowdin data is updated. Nice catch.
![image](https://github.com/sillsdev/ptx2pdf/assets/12962708/c8a458de-f9df-494a-b381-2100d413aaf9)

**Comment by davidc86** [comment]
Woohoo! Thanks.
