### ISSUE TITLE
Error on trying to open an SFM file without first selecting a Paratext Project.

### ISSUE THREAD

**Issue by davidbaines** [sillsdev/ptx2pdf#960]
I installed PTXprint Version 2.4.22

Without selecting a Paratext Project I clicked to select a "Bible Module".  I don't want to select an installed Paratext project, I'm just trying to open a single SFM file.

Here's the error message:
```
Traceback (most recent call last):
  File "ptxprint\gtkview.py", line 3690, in onSelectModuleClicked
  File "ntpath.py", line 137, in join
  File "genericpath.py", line 152, in _check_arg_types
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
```

I didn't know that a "Bible Module" means "SFM file" so it looked to me as though it wasn't possible to open a single SFM file.

**Comment by mhosken** [comment]
You have to have a project. Where is PTXprint supposed to keep all its files? It's not just your module we have to think about ;)

**Comment by markpenny** [comment]
I'm closing this issue as there isn't anything to fix. "Bible Module" is a well-know and accepted (but not widely used) term within Paratext, so anyone who uses them within Paratext would know what that means.

And no, we don't intend to just print *any* SFM file without the wider context of a project and all the related settings.
