### ISSUE TITLE
Suppress chapter number in Glossary?

### ISSUE THREAD

**Issue by viverechristus** [sillsdev/ptx2pdf#97]
Is there a way to suppress the chapter number in the Glossary (besides suppressing chapter numbers globally)? If I print Matthew and Glossary at the same time (taking advantage of the option to include only Glossary entries that occur in Matthew), it's not clear to me that there's a way NOT to show a big "1" at the start of the Glossary.

**Comment by davidc86** [comment]
Agreed. Or even better, how about suppressing chapter numbers in all non-scripture books (front matter, back matter, XXA-XXG books, other matter, etc.)? That would help our teams, because we use a lot of these, and none of them need chapter numbers.

**Comment by markpenny** [comment]
OK request granted! By default it will remove chapter numbers from ALL additional/peripheral/non-scripture books. But if you need those numbers to appear (for example, if you used XXA for a song book), then you need to check a box on the advanced tab to show them. We might move this to the "Body" tab later, but for now, I'm keeping it "out the back"!
![image](https://user-images.githubusercontent.com/12962708/83628944-e900dc00-a5b6-11ea-9852-ff47a5f306d5.png)
This will be available in 0.7.1 whenever that comes out...

**Comment by davidc86** [comment]
Sweet! Thanks. Looking forward to 0.7.1
