### ISSUE TITLE
Table alignment

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#973]
I'm having trouble with alignment in tables.

The project is RTL.

In 2.4.21, with Styles > tc1 having Alignment set to "Left", the table was right-aligned (correctly, since it is a RTL project).

In 2.4.22 things went haywire, with it being left-aligned.

Since 2.5.1 the table is now centered. While I can set alignment to "Right" and thus get it left-aligned, there aren't any settings which result in it being right-aligned.

**Comment by mhosken** [comment]
Can you send us an archive to play with? Set it up how you would want to
express the table and then make sure we get you the output you want.

**Comment by mnjames** [comment]
Thanks. This works now.
