### ISSUE TITLE
SyntaxError: expected ':' in ptxprint/xdv/layout.py", line 68

### ISSUE THREAD

**Issue by n8marti** [sillsdev/ptx2pdf#974]
I got multiple warnings while installing python3-ptxprint v2.5.8 on Ubuntu 24.04:

```
/usr/lib/python3/dist-packages/ptxprint/pdfrw/objects/pdfstring.py:6: SyntaxWarn
ing: invalid escape sequence '\('
  """
/usr/lib/python3/dist-packages/ptxprint/sfm/usfm.py:125: SyntaxWarning: invalid 
escape sequence '\z'
  '''
  File "/usr/lib/python3/dist-packages/ptxprint/xdv/layout.py", line 68
    if b.type == btype
                      ^
SyntaxError: expected ':'
```
The syntax error keeps the package from being installed.

**Comment by n8marti** [comment]
I see that the `SyntaxWarnings` are actually in docstring content and probably won't be an issue. I've submitted #975 to fix the `SyntaxError`.

**Comment by mhosken** [comment]
I'm not sure how you came across this bug given this code is not used in any application, etc. But thanks for spotting it.

**Comment by n8marti** [comment]
You can thank dpkg in Ubuntu. It does Python syntax checking when
installing Python packages, and the package failed to fully install because
of it.

**Comment by n8marti** [comment]
I should say, the python3-ptxprint package failed to install

**Comment by devosb** [comment]
A Python lint like checker (such as flake8 or ruff) can spot issues like these during development.

The issue that generates the warning `about invalid escape sequence` has been deprecated for quite a while in Python. What is [new is that in Python 3.12](https://docs.python.org/3/whatsnew/3.12.html#other-language-changes) (which ships with Ubuntu 24.04, older versions of Ubuntu shipped with older versions of Python) the severity of the issue has been increased (from `DeprecationWarning` to `SyntaxWarning`, in the future that will be `SyntaxError`) so good that this issues gets fixed now.
