### ISSUE TITLE
PTXPrint should let me make output from Paratext resources which are in the public domain

### ISSUE THREAD

**Issue by sewhite** [sillsdev/ptx2pdf#976]
There are some Paratext resources which are in the public domain, for example the World English Bible or the Berean Standard Bible. Since these are public domain, users should be able to make a PDF from them, there is no need to block this, like for resources which are restricted. Can PTXPrint include these public domain resources in the list of available Paratext projects? 

(Recently, a user wrote to Paratext help wanting to get started with learning how to use PTXPrint by working on the WEB, so this is not just a theoretical consideration).

**Comment by mnjames** [comment]
PTXprint has an option built into it (right next to the place where you choose projects) that walks you through the process of downloading projects from the DBL and setting them up for printing. I just did it with WEB to test it.

No, you can't print from the DBL bundles which you've downloaded inside of PT. That's a decision by the Paratext developers--they lock _all_ zip files from DBL, not just the copyrighted ones. So there's no way for the PTXprint team to use the files that PT downloads.
