### ISSUE TITLE
unable to start newer versions

### ISSUE THREAD

**Issue by pacovsky** [sillsdev/ptx2pdf#980]
The last working version that can be downloaded is the 2.5.8, newer return error upon launch: 

Traceback (most recent call last):
  File "ptxprint.py", line 197, in <module>
  File "ptxprint.py", line 197, in <listcomp>
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by markpenny** [comment]
Thanks for reporting this issue. We recently changed the way that projects are located (enabling multiple locations, and duplicate short project codes). This regression was as a result of that. It has now been fixed, and will be made available in the next release (2.6.3) which should be in the next day or two.

**Comment by pacovsky** [comment]
Hi,

I just checked what was going on... 

The args.project on a fresh install was returning by me [None]. 

Best,
Jan

**Comment by markpenny** [comment]
@pacovsky Has this issue now been solved for you? If so, go ahead and close the issue. Thanks.
