### ISSUE TITLE
Print Glossary with select chapters?

### ISSUE THREAD

**Issue by viverechristus** [sillsdev/ptx2pdf#99]
Could there someday be the option to print a filtered Glossary with just select chapters from a book? Right now you can (1) include Glossary entries as footnotes (which works with just a range of chapters) or (2) print the whole Glossary as a stand-alone or with a whole other book (but not part of a book).

**Comment by markpenny** [comment]
Thanks for this idea @viverechristus . I understand what you need, and like the idea. I even started down that track to code it up for you, BUT then I've realized that we can (currently) only specify a start+end chapter if ONE book selected (i.e. not using the Choose books). And we can only have the GLO appened when using the Choose books... So until we re-work a few things in the UI to make this possible, these concepts are mutually exclusive.

We might re-visit this after v1.0 is released. But for now. I'm just tagging the issue as an enhancement request - and hope to return to it another time.

**Comment by viverechristus** [comment]
Thanks!

**Comment by davidg-sil** [comment]
With MH's new work on the book-select allowing you to enter selections, it looks like this issue is now fixed!
