### ISSUE TITLE
PTXprint is very slow to open

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#990]
Is it just my computer or has the PTXprint startup speed taken a major hit?

I remember a long time ago PTXprint had a very slow startup speed. But then something was done (in v2?) to speed this up.

But now it feels like we are back to the old slow startup speed again. 

Main problem: 
There is no indication at all that PTXprint is starting. 
This causes MTTs to click the PTXprint icon over and over, launching several copies of the app.

A splash screen with "Loading x, y, z..." text is helpful. 
(Adobe does this all the time. It's a bit lame, but it at least lets us know that they are working at startup.) 

We'd all prefer it if the app just opened quickly, but maybe that isn't possible. So, if it is going to be slow, then please consider a splash screen with progress indication or notifications, so we at least know PTXprint got the command to start and is very busy working meeting our needs.

**Comment by mhosken** [comment]
Is this a first time loading after a new release download? Did it speed up again after that first run? Do you have A LOT of anything (fonts, projects, images in a project it is loading). You can try running -l debug and then quit and look at the ptxprint.log file that is created somewhere (whatever the current directory is when ptxprint is run, which may be simpler if you run it from the command line to add the cli option). It has timings so you can see where ptxprint is spending its time during startup.

**Comment by davidc86** [comment]
Sorry, but I'm not finding the Log file. I'm running the program from C:\Program Files\Ptxprint\ and I've tried the -l and the -cli and -debug but so far no luck. So am I doing something wrong? This is one of the commands I've tried: 

C:\Program Files\PTXprint>ptxprint.exe -debug

Any help would be appreciated.

**Comment by markpenny** [comment]
@davidc86 Try this command:

`"C:\Program Files\PTXprint\PTXprint.exe" -l debug`

That's a minus lowercase L before the debug [the joys of San Serif fonts!]

As soon as PTXprint opens, click on Quit and then look for the .log file. When you find the ptxprint.log file, the first line will look something like this:
15/Nov/2024 14:55:57.744 INFO:ptxprint(123) git sha: $Id: ff7086d0bc6e19ca2a518bb778f081875e6b96df $
...
...
... and then near the end, you will see a line with:
15/Nov/2024 14:56:13.870 DEBUG:gtkview(981) Starting UI
There may be a couple of lines after that too with a date stamp. Subtracting the end from the start time should give you the time it took. Note if you find any long delays (> 5 seconds) between lines, then that is a clue that something is not right.

So in my case (above) it took 14:56:13.870 minus 14:55:57.744  (or 56m14s minus 55m58s)  = 16s to load.
